- runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java
Thix fixes a bug caused by 6c6238d60f41c98aee2bb8b08ded040351e7ef27 where if Hide Skill Icons is enabled and an XP drop to be recolored due to prayer fires, the Widget array is filled with nulls which causes anyMatch to throw an NPE.
> xpdrop: hide skill icons after recolor

- runelite-client/src/main/java/net/runelite/client/Notifier.java
- runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java
This change adds a configuration option to the 'RuneLite' settings under 'Notification Settings' that allows users to set the color and opacity of notification flashes.
Fixes #10761
> Add configurable color and opacity to the notificaion flash (#10761)

- http-api/src/main/java/net/runelite/http/api/item/ItemEquipmentStats.java
- runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatOverlay.java
- runelite-client/src/test/java/net/runelite/client/plugins/itemstats/ItemStatOverlayTest.java
Adds some logic to account for two handed weapon interactions when hovering over items to get stat changes with the itemstats plugin. Requires runelite/runelite-wiki-scrapper to be updated with this [pull request](https://github.com/runelite/runelite-wiki-scraper/pull/14) to have the functionality work properly. Without this, the old behaviour remains.
Examples:
Switching to 2h accounts for shield removal:
Switching to shield accounts for main hand being two handed:
Equipping a 2h with only a shield:
> Update itemstats plugin to check for two handed interactions

- runelite-api/src/main/java/net/runelite/api/SpriteID.java
I just stumbled across this one.
Didn't check all of them, but did check that the numbers were all ascending, which they now are.
> Fix sprite id of "UNKNOWN_STANCE_ICON_2"

- runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonSpots.java
Closes #12046
Adds common cannon spots for bears, black demons, black knights, elder
chaos druids, fire giants, greater demons, hill giants, scorpions, and
zombies in the wilderness.
> Cannon Plugin: Add more common cannon spots

- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/Produce.java
On farming contracts and the time tracker plugin, the Poison Ivy bush simply shows up as "Poison". This PR simply changes the name to "Poison ivy".
"Dwarf Weed" is also changed to "Dwarf weed" for consistency with other produce such as "Snape grass" and "Celastrus tree".
> Change names of Poison Ivy and Dwarf Weed in TimeTracker plugin for consistency

- runelite-client/src/main/java/net/runelite/client/plugins/cooking/CookingPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/cooking/CookingPluginTest.java
Successfully cooking raw beef into sinew didn't count in the cooking
counter. Added the chat message for successfully cooking sinew to
CookingPlugin.
Close #12090
> cooking: fix sinew not registering as cooked

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/BeginnerMapClue.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/MapClue.java
All but one of these did not have a description to go with the WorldPoint. This adds descriptions for all of them to help with clue completion.
Also fixes a small typo in CrypticClue (Seers' vs. Seer's).
> clues: add location descriptions for MapClues

- runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
This PR fixes [a bug which would "push" overlays resized in the right/down-ward directions beyond their minimum sizes](https://cdn.discordapp.com/attachments/419891709883973642/732737803447959672/2020-07-14_19-18-16.gif). A video demonstrating the updated behavior can be downloaded here: https://cdn.discordapp.com/attachments/419891709883973642/732809556131840081/simplescreenrecorder-2020-07-14_21.02.28.webm
> Fix minimum overlay size resizing

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/SkillChallengeClue.java
Fixes clue referencing d'hide instead of dragonhide
> SkillChallengeClue: Dragonhide instead of d'hide

- runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilitySession.java
This commit increases the number of laps used to calculate laps per hour
from 10 to 30.
Resolves: #12125
> agility plugin: increase number of laps for laps per hour calculation

- runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/screenshot/ScreenshotPluginTest.java
The clan chat I'm in has a game that requires having screenshots for BA high gambles.
I thought this feature might be helpful for others, as well.
> Add ability to automatically screenshot Barbarian Assault high gamble rewards

- runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonSpots.java
Since the Sins of the Father quest release there is a new efficient spot to do Bloodveld tasks (assuming not alt barraging) since it's in multicombat and you can use a cannon. This adds the cannon spot as seen in the video from the Skilling Discord: https://www.youtube.com/watch?v=JfN29yq5U7Y
> cannon: Add Bloodveld cannon spot in Meiyerditch Laboratory

- runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordGameEventType.java
The underground portion of castle wars has a different regionID to the rest of the minigame. This commit adds `9620` to be more accurate when sharing via discord.
> discord: add missing castle wars regionID

- runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityOverlay.java
Previously they would be highlighted with graphics.setColor(configColor) when config.highlightPortals was set to false.
Closes #12269
> agility: Fix prif portal highlighting

- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
* Added Menu Entry Swapper configuration for Advisor Ghrim on Miscellenia (swap talk-to with collect)
* default is false
Note the option is disabled and talk-to option is shown on hover
Note the option is enabled and collect option is shown on hover
Closes #11905
> Added Advisor Ghrim Collect swap to Menu Entry Swapper

- runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZoneConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZonePlugin.java
Addressing feature request #4279
Currently there is no option to display notifications BEFORE an overload potion expires in nmz, either in the Nightmare Zone plugin or NMZ Utilies plugin.
Proposed change in nightmarezone plugin:
* Config option for adjusting how early to output notification
> Add notification BEFORE nmz overload expires

- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
This will track seed bird nests in the loot tracker plugin and ultimately get the data sent to the wiki to further improve their data sets. Inspired from JihadSquad's sheet where he asks people to send him seed data to improve his rates.
> Add bird nest to loot tracker plugin.

- runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java
After the 2020-08-06 game update[1] the Bracelet of slaughter gives a
slightly different text than before. This commit updates the slayer
plugin to identify that new text.
[1]: https://secure.runescape.com/m=news/pvp-changes?oldschool=1
Fixes #12299
> slayer: Fix slaughter bracelet proc text

- http-api/src/main/java/net/runelite/http/api/loottracker/LootRecord.java
- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/loottracker/LootTrackerPluginTest.java
This will let us separate out loot-related distributions that are more granular than the eventType.
Implemented for:
- Fishing Trawler (fishing level)
- Drift Net (fishing level)
- Herbiboar (herblore level)
- NPC loot (NPC ID)
> Add metadata field to LootRecord

- runelite-client/src/main/java/net/runelite/client/plugins/mousehighlight/MouseHighlightOverlay.java
Currently, since Drop isn't part of the known Widget Menu Actions list, it'll skip over checking if the user wants to display tooltips on the interface.
Thanks to `neekz` on Discord for reporting this.
> mousehighlight: make "drop" not show when interface tooltips are off

- runelite-api/src/main/java/net/runelite/api/GraphicID.java
- runelite-api/src/main/java/net/runelite/api/ProjectileID.java
- runelite-client/src/main/java/net/runelite/client/plugins/zalcano/ZalcanoOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/zalcano/ZalcanoPlugin.java
This PR adds a plugin that assists the player with Zalcano, similarly to OSbuddy's Zalcano helper.
The plugin currently assists the player by:
* Highlighting the glowing rocks with hint arrows;
* Highlighting the weakened Zalcano with hint arrows;
* Highlighting tiles where rocks are falling;
* Highlighting if Zalcano shot a fireball at a glowing rock;
Some example images:
> Add a zalcano helper plugin

- runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningRocksOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningSession.java
- runelite-client/src/main/java/net/runelite/client/plugins/mining/Pickaxe.java
- runelite-client/src/main/java/net/runelite/client/plugins/mining/Rock.java
- runelite-client/src/test/java/net/runelite/client/plugins/mining/MiningPluginTest.java
Rename MiningOverlay to MiningRocksOverlay to match how other plugins with session stats do it. (Woodcutting for example)
Create a new MiningOverlay to track session stats & state of mining or idle.
MiningPluginTest is created. 
I only have 75 mining and am not sure if I have all the onChat message mining.  (Ess/Pure Ess do not have on chat messages)
I watched youtube videos to find the lines for gem rocks & quarry mining.
I don't know how useful mining/not mining is but I added it because it was a why not type of thing.
When mining:
When not mining:
> Mining: Add session stats

- http-api/src/main/java/net/runelite/http/api/loottracker/LootTrackerClient.java
Currently the LootTrackerClient will claim it has successfully submitted loot as long as a response came back.
> Make the LootTrackerClient log when submitting isn't successful

- runelite-client/src/main/java/net/runelite/client/plugins/gpu/GLUtil.java
- runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPluginConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/gpu/TextureManager.java
Closes #7212 
Zoomed in video example [with](https://imgur.com/YatSjYw) and [without](https://imgur.com/yfeynlP) anisotropic filtering
Example images
Left side has anisotropic filtering disabled. Right is 16x anisotropic filtering
> Add Anisotropic Filtering 

- runelite-client/src/main/java/net/runelite/client/Notifier.java
I didn't see a bug reported for this so I decided to make a fix it myself.
When the "Flash Notification" setting is set to "Flash until cancelled" or "Solid until cancelled" and the notification goes off, changing the setting to "Off" keeps the notification solid even if you move your mouse or click in the game window panel.
This fix simply disables any flash notification currently active if the setting is changed to off.
> Notifier: Disable flash notification when off is selected

- runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/prayer/PrayerPluginTest.java
The current implementation of calculating the time left on prayer only shows minutes remaining. When the time left on prayer was over an hour, it would cut off the hour and only show the minutes left.
I ran into this when I wore high prayer bonus (50+) and used a slow draining prayer (Preserve) with a high Prayer level.
I also added tests for the prayer text formatting :)
> Prayer: Fixed time remaining text when time was greater than an hour

- .travis.yml
[`sudo` does nothing anymore](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration)
[`os` is linux by default](https://docs.travis-ci.com/user/reference/overview/#for-a-particular-travisyml-configuration) but it would be configure it verbosely
> Remove deprecated/default Travis config

- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
> The ‘Travel’ options for some NPCs in Rellekka will now list the relevant destinations 
https://secure.runescape.com/m=news/a=13/darker-graceful-and-other-changes?oldschool=1
This pull request adds `Ungael`, `Waterbirth Island`, `Pirate's Cove`, and `Miscellania` as menu options that are now toggled by the Travel config in the Menu Entry Swapper plugin.
> Rellekka NPCs travel destinations added to menu entry swapper

- runelite-client/src/main/java/net/runelite/client/plugins/bank/BankPlugin.java
Fixes the following NPE:
```
2020-08-15 02:26:10 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
at net.runelite.client.plugins.bank.BankPlugin.onScriptPostFired(BankPlugin.java:241)
at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:73)
at net.runelite.client.eventbus.EventBus.post(EventBus.java:222)
at net.runelite.client.callback.Hooks.post(Hooks.java:165)
at client.wf(client.java:55513)
at ar.o(ar.java:154)
at bz.m(bz.java:97)
at client.up(client.java:2959)
at client.y(client.java:907)
at bn.fm(bn.java:358)
at bn.run(bn.java:337)
at java.base/java.lang.Thread.run(Thread.java:832)
```
Occurs when you close the bank **immediately** upon opening it.
You can reproduce it by holding down …
> Bank Plugin: fixed a NPE when opening and closing the bank too quickly

- runelite-client/src/main/java/net/runelite/client/ui/overlay/worldmap/WorldMapOverlay.java
Current behaviour: 
New behaviour:
Vanilla behaviour for reference:
> World Map: adjusted the height of tooltip text to match vanilla tooltips

- runelite-client/src/main/java/net/runelite/client/plugins/slayer/Task.java
[An update in April](https://secure.runescape.com/m=news/poll-70-improvements?oldschool=1) added Elves in the Iorweth slayer dungeon, but these aren't tagged correctly in Runelite as they're Iorweth Warriors. Added Iorweth Warriors to the list of Elves in the Slayer Plugin.
> Slayer: Add Iorweth Warriors (Priff dungeon) to list of targets for elves

- runelite-client/src/main/java/net/runelite/client/plugins/blastfurnace/BlastFurnaceClickBoxOverlay.java
Previously, all clickbox overlays had a red translucent fill, even if the boundary is green and should symbolise a "good" state.
Now, use the same color as the border but with alpha for the fill.
> Blast Furnace: Use border color for clickbox overlay fills

- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/OverviewTabPanel.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TabContentPanel.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TimeFormatMode.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TimeTrackingConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingContractInfoBox.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTabPanel.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/hunter/BirdHouseTabPanel.java
Closes #4896
Closes #4959
Closes #7449
Closes #7612
I've always assumed that the locale of the OS set the time format before, but I can't find evidence of that. Even if that was the case, relying on the OS screws over those users who want to go against the norm for their locale.
> timetracking: add configuration for displaying time in 12 hour format

- runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/screenshot/ScreenshotPluginTest.java
Because both level up dialogs and BA high gambles use the same widget
interface, commit 40f032bede826714ad431f912889f6a527fcd0c9 caused BA
high gambles and some level up dialogs to trigger screenshots if either
config was enabled in the config, as that would set a flag to capture a
screenshot on the next game tick based on the widget text. This commit
adds config checks to the DIALOG_SPRITE_TEXT branch to ensure the
appropriate config flag must be set for a screenshot to be captured.
Fixes #12339
> screenshot: Fix BA high gamble toggle

- runelite-client/src/main/java/net/runelite/client/ui/components/colorpicker/ColorValueSlider.java
- runelite-client/src/main/java/net/runelite/client/ui/components/colorpicker/RuneliteColorPicker.java
Existing behaviour:
New behaviour:
Not sure if the 2 pixels extra on either side of the slider track are desired, perhaps people would prefer it if the knob bottomed and topped out.
> UI Component: color slider resized to fit knob at max rgba values

- runelite-client/src/main/java/net/runelite/client/plugins/zalcano/ZalcanoPlugin.java
Currently the zalcano plugin keeps references to `GraphicsObject` to highlight the falling rocks and relies on the `GraphicsObject.finished` method to remove them. The problem is that if the player teleports out, the client will clear it's references to the GraphicsObjects that the plugin is currently holding, meaning they will no longer be ticked and `GraphicsObject.finished` will never return true. This PR simply clears the references whenever the game state changes to anything that is not `LOGGED_IN`.
> zalcano-plugin: Fix lingering graphicsobject highlighting

- runelite-client/src/main/java/net/runelite/client/plugins/corp/CoreOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/corp/CorpConfig.java
Closes #12452
Adds a config option to toggle core highlighting. Enabled by default.
> corp: Add toggle for dark energy core highlighting.

- runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_firemaking.json
- runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_woodcutting.json
Close #12455
Add entries to Woodcutting and Firemaking skills for Blisterwood logs.
> Enhancement: Add Blisterwood Logs to Skill Calculator Plugin

- runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_agility.json
This merge adds each hallowed sepulchre agility course into the agility calculator by floor, not sure how we would go about making "combined" run when a person completes floors from 1-5 in one go, not sure if that needs to be handled? Icon might need to be changed so happy to take suggestions
> Added hallowed sepulchre floors into the agility calculator

- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/WesternDiaryRequirement.java
Close #12492 
Changed the requirement for Monkey Madness 1 to simply being started instead of being completed for the task "Chop and burn some teak logs on Ape Atoll" in the Western Provinces Diary.
Before:
After:
> achievementdiary: Fix Western Provinces quest requirement

- runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordGameEventType.java
The region for Barbarian Assault had a typo from a couple of years ago that I didn't catch in my Discord PR. This commit fixes that typo as well as adds the regions for the minigame itself, as previously (without the typo) it was only accounting for the lobby.
> discord: fix Barbarian Assault regions

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
Close #12514
Updated cryptic clue to reflect changes where clue was moved from 1st floor to ground floor.
> clues: Add updated Falador cryptic clue

- runelite-client/src/main/java/net/runelite/client/plugins/timers/ElapsedTimer.java
- runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/timers/ElapsedTimerTest.java
- runelite-client/src/test/java/net/runelite/client/plugins/timers/TimersPluginTest.java
Closes #12401
Fixed inferno timer being 10 ticks (6 seconds) behind. Timer now starts at `00:06` once `Wave 1` message is displayed.
Elapsed timer now displays in `mm:ss` to be better inline with the ingame timer.
> Inferno timer improvements

- runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
Closes #3700
Notes the world on which the cannon was placed in its timer tooltip.
> timers: add world placed to cannon timer tooltip

- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/loottracker/LootTrackerPluginTest.java
Adds actual birdhouses to the loot tracking plugin. I wasn't sure if Jagex puts a comma in the XP drop, they don't for redwoods but I didn't test for yew and magics. No reason to think they would but made the regex account for it anyways.
> Add birdhouses to loot tracker plugin

- runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPanel.java
- runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/devtools/MovementFlag.java
Background: I created this tool to assist a Hallowed Sepulchre plugin (in progress) and I thought it might be useful to others.
This plugin highlights the tile the player is currently hovering over and displays the movement flags above it. The movement flags can be useful for pathfinding and other debugging purposes.
> DevTools: Add Movement Flags DevTools Plugin.

- runelite-client/src/main/java/net/runelite/client/input/KeyManager.java
We receive numerous support queries regarding unknown or errantly-set
keybinds causing issues during normal gameplay for our users, especially
since the plugin hub has been released and more plugins are able to
register keybinds. This commit adds logging for keybind registration and
activation for ease of troubleshooting.
> KeyManager: Add debug logging

- runelite-client/src/main/java/net/runelite/client/plugins/inventoryviewer/InventoryViewerConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/inventoryviewer/InventoryViewerOverlay.java
Closes #12298
Also possibly closes #4148
Added a toggle for the Inventory Viewer plugin's overlay. Added a toggle which hides the overlay on start, this is off by default.
> inventoryviewer: Add a keybind toggle to hide the overlay.

- runelite-client/src/main/java/net/runelite/client/util/ColorUtil.java
- runelite-client/src/main/java/net/runelite/client/util/ImageUtil.java
- runelite-client/src/test/java/net/runelite/client/util/ColorUtilTest.java
- runelite-client/src/test/java/net/runelite/client/util/ImageUtilTest.java
ImageUtil had previously provided a number of image fill and outline
methods which accepted Predicates to control the fill and outline
behavior, but they are not used anywhere in the client or by external
plugins. This commit removes these methods and the
is(Not)?FullyTransparent ColorUtil methods which existed solely as
Predicate defaults for them.
> util: Remove unused and unneeded methods

- runelite-client/src/main/java/net/runelite/client/plugins/config/PluginHubPanel.java
- runelite-client/src/main/java/net/runelite/client/plugins/config/PluginListItem.java
- runelite-client/src/main/java/net/runelite/client/plugins/config/PluginListPanel.java
- runelite-client/src/main/java/net/runelite/client/plugins/config/PluginSearch.java
- runelite-client/src/main/java/net/runelite/client/plugins/config/SearchablePlugin.java
- runelite-client/src/main/java/net/runelite/client/util/Text.java
- runelite-client/src/test/java/net/runelite/client/plugins/config/PluginSearchTest.java
Resolves https://github.com/runelite/runelite/issues/11520
- Introduce `SearchablePlugin` and extract plugin search code to `PluginSearch`, which is now used by both internal and external plugin searches
- Order search results using a few heuristics such that exact or close text matches occur higher up in the results
I tried using JaroWinklerDistance but it didn't have very good results, probably due to the varying name-length of plugins, so I settled on more human heuristics.
> Sort plugin search results with better text matches higher in search results

- runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java
This pull request simply adds a world check before rendering the cannon overlay.
Fixes #12532
> cannonplugin: Check world when drawing overlay

- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingContractInfoBox.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingContractManager.java
- runelite-client/src/test/java/net/runelite/client/plugins/timetracking/farming/FarmingContractManagerTest.java
Fixes #12124 
Also fixes an issue with crops requiring health checks showing as in progress instead of occupied if they were already planted and checked before the contract.
> Check diseased and dead states on the Farming Contract Indicator

- runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesPlugin.java
Allows for the xp globes to stack vertically.
Closes: #12280
> XPGlobes: allow stacking vertically.

- runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
Adds shorthand names for all agility courses, including common misspellings.
I have confirmed each `longBossName` in game, as they don't all match what is shown when talking to Grace.
Closes #12529
> chatcommands: add shorthand names for all agility courses

- runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/ShiftDepositMode.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/ShiftWithdrawMode.java
Adds withdraw/deposit swaps for the chambers of xeric storage unit. This uses the same config item as the regular bank, and for options which do not correspond to a storage unit option, "all-but-1" becomes "all", "eat/wield/etc." does not perform a swap, and "Withdraw-X" (which withdraws the last set custom quantity in the bank) selects the option named "Withdraw-X" (which opens a dialog).
This would fix issue #11920.
> Adds bank withdraw/deposit swaps for the chambers of xeric storage unit.

- runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/Library.java
- runelite-client/src/test/java/net/runelite/client/plugins/kourendlibrary/LibraryTest.java
The Varlamore Envoy is a quest item which, while having a known location
in the library once a rotation is determined, cannot be found under
certain circumstances. (when the Depths of Despair quest has not been
started, has been collected while completing the quest, and after the
quest is completed) Previously searching a bookcase which could contain
this book and not finding it would cause a state reset. This commit
keeps those null finds from resetting the known library state.
Fixes #12041
Closes #12338
> kourendlibrary: Don't reset state when not finding Varlamore Envoy

- runelite-api/src/main/java/net/runelite/api/Perspective.java
- runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java
Added `zOffset` argument for `Perspective.getCanvasTilePoly` and `Perspective.getCanvasTileAreaPoly` to allow Ground Items to render the tile overlay at the correct height (for example tables).
> Render Ground Items tile overlay at correct height

- runelite-client/src/main/java/net/runelite/client/plugins/banktags/BankTagsPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java
The config server replaces periods in keys with colons. When the config is downloaded by the client, the colon is then replaced with a period.
Closes #10500
> banktags: don't allow colon in tagtab names

- runelite-client/src/main/java/net/runelite/client/plugins/screenmarkers/ScreenMarkerOverlay.java
- runelite-client/src/main/java/net/runelite/client/ui/overlay/Overlay.java
- runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
Halve the minimum for Screen Marker Overlay (set to 16). Any smaller than 16 makes subsequent resizes impossible because the cursor type never changes from center (move mode). All other overlay types are unchanged from the default (32).
If the reasoning for the original default was the same as above, it might be worthwhile to change the default to 16 as well. And maybe in that case undo most of this commit and just change the original constant to 16, ha.
Fixes #12267
> Make minimum overlay size configurable per-overlay

- runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordGameEventType.java
- runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordState.java
- runelite-client/src/test/java/net/runelite/client/plugins/discord/DiscordStateTest.java
Fixed the discord plugin's action timeout to match expected behavior and clear the activity from presence. Previously if there was only an event removed (such as training herblore), then the presence was not updated. Updating with the current game state fixes this.
I've also added an option to show total time in game rather than time elapsed performing the current activity. This option is the default.
Closes #12438
> discord: Fix action timeout, add in game time elapsed option

- runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java
- runelite-client/src/test/java/net/runelite/client/config/ConfigManagerTest.java
- runelite-client/src/test/java/net/runelite/client/config/TestConfig.java
None of the @Alpha default methods currently return null, so I changed the one in CannonConfig.java to replicate the exception.  Default method returning null behaves as though there is no default method, in both cases of individual reset and plugin-wide reset.
Fixes #12226
> Fix NPE on resetting configs with null default value

- runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZonePlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
Close #12493 
The timers plugin was not checking to see if the player was still inside NMZ, causing the timer to stay when the player left or hopped worlds. Now checks to see if the player is inside the NMZ region.
For the nightmarezone plugin, `overloadNotificationSend = true` when the player drinks an Overload potion. When the player leaves NMZ before the Overload expires and re-enters, `overloadNotificationSend` is still `true`. This results in the notification still being sent based on when the potion was drunk in the previous NMZ instance. Now sets `overloadNotificationSend` to `false` upon leaving.
> Fix Nightmare Zone Overload timer and notification

- runelite-client/src/main/java/net/runelite/client/plugins/worldmap/KourendTaskLocation.java
- runelite-client/src/main/java/net/runelite/client/plugins/worldmap/KourendTaskPoint.java
- runelite-client/src/main/java/net/runelite/client/plugins/worldmap/WorldMapConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/worldmap/WorldMapPlugin.java
Adds tooltips for all Kourend task locations, including House names, the percentages at which the tasks can be completed, and percentages for other House unlocks. 
Also fixes a config typo in "transportation" but does not change the keyName since that was spelled correctly.
> worldmap: add Kourend task and unlock tooltip descriptions

- runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java
Fixed #12652  by resetting the lastAnisotropicFiltering value to the default on startup when shutting down the gpu plugin.
This is my first contribution to runelite 😄
> Fix anisotropic filtering resetting to 0 after GPU plugin was restarted

- runelite-client/src/main/java/net/runelite/client/plugins/worldmap/DungeonLocation.java
Adds worldmap tooltips for the North and South entrances to the new Wilderness Slayer Cave.
> worldmap: add Wilderness Slayer Cave entrances

- runelite-api/src/main/java/net/runelite/api/IconID.java
- runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
Closes #12722
Currently !lvl only worked in public/mod chat if you were on a league world with the person who sent it. Adds broad support for the other cases.
> chatcommands: handle league accounts properly

- runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpGoalTimeType.java
- runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java
- runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpSnapshotSingle.java
- runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpStateSingle.java
- runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerConfig.java
Add option to display XP goal times in hours rather than days, since some people find it easier to visualize goals that way. This means hours can go above 23 in XP goals. In addition, add an option for showing the current percentage of an XP goal in the progress bar tooltip.
> XP Tracker: Goal time formatting options

- runelite-api/src/main/java/net/runelite/api/Varbits.java
- runelite-client/src/main/java/net/runelite/client/plugins/regenmeter/RegenMeterPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpWorldType.java
The varbits are gathered from [\[proc, league_relics_draw_selections\]](https://github.com/RuneStar/cs2-scripts/blob/1c404f9e5b31ba09661f7f1fbc6af90dbf30f867/scripts/%5Bproc%2Cleague_relics_draw_selections%5D.cs2#L72-L87) and verified with my first three selected.
This also replaces the Endless Endurance HP regeneration modifier from twisted league with fluid strikes from trailblazer.
> xptracker: account for relic modifiers when tracking kills left

- runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java
- runelite-client/src/main/java/net/runelite/client/ui/overlay/WidgetItemOverlay.java
This adds widget overlay support for inventory in both trading screen and duelarena screen for plugins such as **[Inventory Tags]** and **[Item Charges]**.
Fixes: #12584
> Extended widget support for showOnInventory

- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
reopens and closes #11930 
This issue was originally closed due to: 
Swapping while equipped is banned by the Jagex Statement
However, the Prayer Book from The Great Brain Robbery quest is not an equippable item.
> Add menu entry swap for recite-prayer option of the Great Brain Robbery prayer book

- runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPluginConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/gpu/config/ColorBlindMode.java
- runelite-client/src/main/resources/net/runelite/client/plugins/gpu/colorblind.glsl
- runelite-client/src/main/resources/net/runelite/client/plugins/gpu/fragui.glsl
Implements an accessibility option that allows protanope, deuteranope and tritanope colorblind players to be able to add color correction to the game and gui colors via a dropdown in the GPU plugin.
Screenshots below were taken on a 2019 Macbook Pro, so there's no compatibility issues there.
Currently in the RL discord under the user bpl#1337 if you'd like to discus there.
> Colorblindness correction option for GPU plugin

- runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java
> widgetid: correct kingdom reward group

- runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java
Right now when finding out the raid starting room's location relative to the other rooms it looks at the rooms to the left and right of the starting room. When I made this logic I assumed that the player would always be in the starting room when this code ran but that was a wrong assumption. Now it just silently fails when the player can't see the room to the right of the starting room instead of erroring. This will almost never happen under normal use anyways.
Closes: #12545
> raids plugin: fix array out of bounds error when scouting for a raid

- runelite-client/src/main/java/net/runelite/client/plugins/chatnotifications/ChatNotificationsPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/chatnotifications/ChatNotificationsPluginTest.java
Closes #12524 
Fixes highlight message matcher to correctly match messages that end in a `.`
> Chat Notifications: Fixed highlighting messages that end with a period.

- runelite-client/src/main/java/net/runelite/client/plugins/config/PluginListPanel.java
Since the plugin hub "isn't a total disaster" I thought it would be neat if you didn't have to scroll so much when accessing it.
> plugin-panel: stick plugin hub button to bottom of plugin list

- http-api/src/main/java/net/runelite/http/api/config/ConfigClient.java
- http-api/src/main/java/net/runelite/http/api/config/ConfigEntry.java
- http-api/src/main/java/net/runelite/http/api/config/Configuration.java
- http-service/src/main/java/net/runelite/http/service/config/ConfigController.java
- http-service/src/main/java/net/runelite/http/service/config/ConfigService.java
- runelite-api/src/main/java/net/runelite/api/events/PlayerChanged.java
- runelite-api/src/main/java/net/runelite/api/events/WorldChanged.java
- runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java
- runelite-client/src/main/java/net/runelite/client/config/RuneScapeProfile.java
- runelite-client/src/main/java/net/runelite/client/config/RuneScapeProfileType.java
- runelite-client/src/main/java/net/runelite/client/events/RuneScapeProfileChanged.java
- runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangePlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TimeTrackingPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingContractManager.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/hunter/BirdHouseTracker.java
- runelite-client/src/test/java/net/runelite/client/config/ConfigManagerTest.java
- runelite-client/src/test/java/net/runelite/client/plugins/chatcommands/ChatCommandsPluginTest.java
- runelite-client/src/test/java/net/runelite/client/plugins/grandexchange/GrandExchangePluginTest.java
This adds support for per runescape save configuration, allowing plugins to correctly keep account data (slayer task, farming timers, etc.) separate on leagues from the standard game.
Requires internal!122
Closes #8050
Closes #12563
> Per RuneScape-Profile configuration

- runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/grounditems/config/DespawnTimerMode.java
By sudden popular request, here's some numerical despawn timers. Available in both seconds (accurate to 0.1s) and ticks!
The code that calculated the despawn time and pie colour has been refactored out into 2 functions; it's execution should remain unchanged.
The pie will still appear when holding Alt, as it did before, since the numbers would interfere with the controls.
> grounditems: add numerical despawn timers

- runelite-api/src/main/java/net/runelite/api/VarPlayer.java
- runelite-client/src/main/java/net/runelite/client/plugins/zalcano/ZalcanoPanel.java
- runelite-client/src/main/java/net/runelite/client/plugins/zalcano/ZalcanoPlugin.java
Adds a panel which tracks damage dealt to Zalcano's health and shield
to make it easier prioritising what to focus on at a low level.
> zalcano: add damage counter

- runelite-client/src/main/java/net/runelite/client/plugins/itemprices/ItemPricesOverlay.java
This PR fixes the platinum token formatting by forcing an implicit cast to `long` using a `long` literal. This should resolve the issue where values of `qty * 1000` exceeding the maximum value of an `int` would format as "-1,000 gp".
These changes were tested by forcing `qty` to `Integer.MAX_VALUE` and verifying the output within the client:
Closes #12934.
> Fix issue #12934: Correctly format large platinum token GP values

- runelite-client/src/main/java/net/runelite/client/plugins/config/PluginHubPanel.java
This normally relies on ExternalPluginsChanged being emitted to rebuild
the ui, but that doesn't happen in safe mode
> config/PluginHubPanel: show uninstall ui feedback when in safe mode

- runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/blastmine/BlastMinePluginConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/blastmine/BlastMineRockOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java
- runelite-client/src/main/java/net/runelite/client/plugins/driftnet/DriftNetConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/herbiboars/HerbiboarConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/herbiboars/HerbiboarOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/hunter/HunterConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/hunter/TrapOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/implings/ImplingsConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcSceneOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/pyramidplunder/PyramidPlunderConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/pyramidplunder/PyramidPlunderOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/slayer/TargetClickboxOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/tithefarm/TitheFarmPlantOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/tithefarm/TitheFarmPluginConfig.java
- runelite-client/src/main/java/net/runelite/client/ui/components/ColorJButton.java
- runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayUtil.java
- runelite-client/src/main/java/net/runelite/client/ui/overlay/components/TextComponent.java
- runelite-client/src/main/java/net/runelite/client/util/ColorUtil.java
- runelite-client/src/test/java/net/runelite/client/util/ColorUtilTest.java
Add the ability to configure alpha for various different color config options.
Implement a new ColorJButton to preview colors with alpha in the config sidebar by overlaying them on top of the classic checkerboard pattern.
ColorUtil: Add new methods: `toAlphaHexColor` (yields a colors hex string including alpha), `colorOfAlpha` (change alpha of a given RGB color), and `luminance` (calculate luminance of a color). Also add unit tests for these methods.
OverlayUtil: Remove alpha from minimap dots and text overlays.
TextComponent: Remove alpha from text color.
Closes #12353
> Add alpha channel to relevant color config options

- runelite-api/src/main/java/net/runelite/api/Varbits.java
- runelite-client/src/main/java/net/runelite/client/plugins/statusbars/StatusBarsOverlay.java
Display a pink color in the healthbar if the player gets infected by a parasite during the nightmare of ashihama fight.
Adding PARASITE Varbit in Varbits.java
Closes issue #12857
> Adding Color change in statusbar if infected with a parasite

- runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/timers/TimersPluginTest.java
Update Sire Timer to account for stacking stuns, change method of detection to chat message. should make it more robust so it should not break if jagex makes changes in the future.
> Timers Plugin: Update Sire Timer to account for stacking stuns

- runelite-api/src/main/java/net/runelite/api/events/WidgetClosed.java
- runelite-api/src/main/java/net/runelite/api/widgets/WidgetModalMode.java
- runelite-client/src/main/java/net/runelite/client/plugins/devtools/WidgetInfoTableModel.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/Tab.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TimeTrackingConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TimeTrackingPanel.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TimeTrackingPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingContractManager.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingNextTickPanel.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingRegion.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingWorld.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/PatchImplementation.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/Produce.java
Automatically tracks and applies your accounts offset to farming ticks. For a general user, your farming times will become more accurate over time as you inadvertently observe crops growing.
For anyone looking to quickly get accurate times the simplest solution is to plant a normal tree and keep it within your render distance for 40 minutes. After observing the tree growing one stage your timers for all crops will be 100% accurate.
Closes #8381
Requires !127
> Add farming tick offsets to time tracking plugin

- .github/FUNDING.yml
[Sponsorships](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository#displaying-a-sponsor-button-in-your-repository) first needs to be enabled in the repository settings. It will allow for a sidebar link to Patreon:
> sponsors: add patreon link

- runelite-client/src/main/java/net/runelite/client/plugins/tearsofguthix/TearsOfGuthixOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/tearsofguthix/TearsOfGuthixPlugin.java
This PR adds an optional Green Tears timer to the Tears of Guthix Plugin (fixes #12858).
> Add Green Tears of Guthix Timer (fixes #12858)

- runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordGameEventType.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingWorld.java
Fixes https://github.com/runelite/runelite/issues/12787. 
From the issue:
> I am far enough along in Song of the Elves that Lletya has been attacked, and is "scorched". Without completing the quest, I have planted a palm tree in the fruit tree patch there, but it is not timed in the Time Tracking plugin.
> [...] when passing through the tree entrance to Lletya, your character is warped from region 9265 on the left side, to region 11103 on the right side.
This patch adds recognition for region 11103, so that players who are partially through Song of the Elves still have their fruit tree timers accurately tracked.
> Add "scorched" Lletya regionID recognition to TimeTracking and Discord plugins

- runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_herblore.json
- Added 4 dose **Extended Antifires** and **Anti-venoms** to the herblore skill calculator. These potions are able and often are made using 4 doses at a time.
- **Super Antifires** and **Anti-venom+'s** can not be made using 3 doses at a time, so were fixed to display the right potion dose (4).
> SkillCalculator: Added support for 4 dose potions, fixed invalid 3 dose potions

- runelite-client/src/main/java/net/runelite/client/plugins/barrows/BarrowsBrotherSlainOverlay.java
Closes #12916
Closes #12918
Using the power of `DecimalFormat`, the reward potential is now rounded to 2 decimal places. Can easily be changed to more or less if needed.
> barrows: fix reward potential formatting showing too many 0s

- runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialCounter.java
- runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialCounterConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialCounterPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialWeapon.java
- runelite-client/src/test/java/net/runelite/client/plugins/specialcounter/SpecialCounterPluginTest.java
Close #12568
Add feature to existing special attack counter plugin which allows users to set a threshold and receive a notification when it is met.
For example, if a user sets their Bandos Godsword threshold to two, after two special attacks with the Bandos Godsword, they will receive a notification.
> Special attack counter notifications

- runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatChanges.java
Close #12817 
Changed zamorak brews to use current defence level to calculate delta
> itemstats: correct zamorak brew defence drain to use current level

- runelite-client/src/main/java/net/runelite/client/plugins/worldmap/MinigameLocation.java
- runelite-client/src/main/java/net/runelite/client/plugins/worldmap/TransportationPointLocation.java
Adds Mahogany Homes minigame locations (Falador, Varrock, Hosidius, and Ardougne) to the world map
EDIT 1/11/21: Adds Soul Wars minigame and teleport locations
> worldmap: add Mahogany Homes and Soul Wars minigame locations

- runelite-client/src/main/java/net/runelite/client/game/chatbox/ChatboxTextInput.java
Previously, when pressing left or right without Shift pressed, the
cursor would end up one character left or right of the start of the
selection, which is not expected behavior compared to how most programs
handle this case. This commit changes this behavior to place the cursor
at the start or end of the selection when pressing left or right,
respectively, when a selection is active.
> ChatboxTextInput: Improve open selection left/right handling

- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
Adds loot tracking for Spoils of war from Soul Wars
Also ignore player loot while in Soul Wars regions (like LMS) since the only loot received are bones and occasionally soul shards, which populates the loot tracker very quickly.
> loot tracker: Add Spoils of war (Soul Wars)

- runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatChanges.java
The new potions in Soul Wars act as a Super Combat/Range/Magic potion as well as have the prayer restore properties of a Super Restore. The bandages heal 20% + 2 and restore 100% run energy.
> itemstats: Add Soul Wars Potion of Power and Bandages

- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
~~This modifies the current bird nest loot tracking to improve the wiki data sets. Currently, the system combines all types of bird nests and it is tracked under "Bird nest".~~
~~**Changes made:**~~
~~- Wyson nests -> Bird nest (Wyson)~~
~~- Regular nests (miscellania, birdhouses, woodcutting) - Bird nest (Seed)~~
~~- Ring nests -> Bird nest (Ring)~~
~~- Egg nests-> Bird nest (Egg)~~
~~- Empty nests -> Not tracked~~
~~_Note: Historical nests with the ID 5073 and 13563 are tracked with under the -> Bird nest (Old) and (Old v2) respectively for data purposes._~~
Update: This PR modifies the current bird nest loot tracking to include the object id as metadata.
> loottracker: added bird nests to track type

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/MapClue.java
This is to clarify that digging from inside the building does work.
> Update Yanille Anvils Map Clue description

- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/Produce.java
Sweetcorn and watermelon were both one stage off. Verified in game.
> Fix growth stages of sweetcorn and watermelon

- runelite-api/src/main/java/net/runelite/api/kit/KitType.java
The arms slot is a slot similar to jaws in that no item can be equipped there, but it affects the player's appearance, namely when certain "sleeveless" items are equipped, such as d'hide bodies and chainbodies, making the arms appear like they do when nothing is equipped in the torso slot. Most torso slot items (platebodies, etc) remove the arms. I found this out by examining `PlayerComposition::getEquipmentIds`.
I would like this added for a plugin I'm working on. Happy to provide more info / tests if that helps. Not entirely sure how to test this, though.
> Add arms kit type

- runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
Currently many people have been using `!lvl soul_wars_zeal`, which isn't exactly the easiest to type, and due to it being recognized as a skill, the output incorrectly displays it as such. 
This commit adds the `!sw` command to more easily and appopriately display one's Soul Wars Zeal and rank.
> chatcommands: Add Soul Wars Zeal command (!sw)

- runelite-client/src/main/java/net/runelite/client/plugins/inventorytags/InventoryTagsConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/inventorytags/InventoryTagsOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/inventorytags/InventoryTagsPlugin.java
- runelite-client/src/main/java/net/runelite/client/util/ImageUtil.java
Closes #12518
Includes a spinner for alpha values from 0-255
Looks like this at 100:
> Add Fill Option for Inventory Tags

- runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/xpglobes/XpGlobesPluginTest.java
Resolves https://github.com/runelite/runelite/issues/12871
Current configuration:
New configuration:
Current behavior:
After change (toggled off, default):
After change (toggled on):
After change (Hide maxed skills toggled on) (lol)
Changes come with tests.
> XP Globes: add virtual level to config and xp globes

- runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
This is a redo of PR #3069.
It seems the code was good, the only thing that was outdated would have been the config positions conflicting with other fields added over time.
I took the liberty to add an energy regen notification to accompany the low energy one.
Closes #3057
> Add Low/High Energy notifications to idle notifier

- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TimeTrackingConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TimeTrackingPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java
Closes #9445
Closes #12287
Currently, the overview tab of Time Tracking shows when a group of patches will all complete. This is problematic when you have, say, Hardwood trees or a Redwood tree growing, and want to know roughly when your normal trees will finish to do a run, since they have a much longer growth time. This PR simply adds an option to show the soonest completion, which is more likely to be a better indicator of when the group of patches is finished.
`Dusk the Umbreon` brought this up in Discord, and I thought it was a nice idea, and an easy one to implement.
Also, yes, apparently `extremum` is the collective term for maximum and minimum. I think it's a bit weird too, suggestions very much welcome.
> timetracking: Add option to show the soonest completion time of a tab

- runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerSharingManager.java
Closes #7853.
Adds two menu options to the World Map globe: `Export Ground Markers` and `Import Ground Markers`.
Selecting `Export Ground Markers` will serialize all ground markers in active scenes into JSON, then copy the result onto the clipboard.
Selecting `Import Ground Markers` will deserialize clipboard JSON, then copy the results into the config, merging the points with already existing points for that region, and reloading. Importing points does not overwrite existing points.
Here's a video of the import in action:
https://user-images.githubusercontent.com/1868974/103497492-aa165b80-4e0f-11eb-8611-0296581c6b0d.mp4
Since this feature got a bit large to implement, I placed it into its own GroundMarkerSharingManager class, which takes an injected GroundMarkerPlugin to communicate …
> Add shareable ground markers

- runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcMinimapOverlay.java
Some NPCs have color tags to make them look like objects rather than NPCs, like the Totems at Nightmare. With the `Draw names on minimap` setting enabled, the colors tags are visible for tagged NPCs on the minimap, thus it is necessary to strip those tags.
Before:
After:
> npc indicators: remove tags from minimap npc name

- runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatChanges.java
The amount of healing was changed on the 27 Jan. 2021 game update from 20% + 2 to 15% + 1.
> itemstats: Update Soul Wars Bandages healing

- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/worldmap/MinigameLocation.java
Adds loot tracking for new Gold keys in Shades of Mort'ton
Also adds missing minigame icon label
> Shades of Mort'ton loot tracking and minigame location

- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
They have the same description and behavior as stone chest. From melky test:
```
2021-02-03 13:54:03 [Client] DEBUG n.r.c.p.l.LootTrackerPlugin - Tick: 417
2021-02-03 13:54:04 [Client] DEBUG client-patch - Chat message type SPAM: You manage to unlock the chest.
2021-02-03 13:54:04 [Client] DEBUG n.r.c.p.l.LootTrackerPlugin - Tick: 418
2021-02-03 13:54:04 [Client] DEBUG client-patch - Chat message type SPAM: You steal some loot from the chest.
2021-02-03 13:54:04 [Client] DEBUG n.r.c.p.l.LootTrackerPlugin - Received icc: [Item(id=12791, quantity=1), Item(id=13068, quantity=1), Item(id=13222, quantity=1), Item(id=13069, quantity=1), Item(id=5698, quantity=1), Item(id=6705, quantity=1), Item(id=6705, quantity=1), Item(id=6705, quantity=1), Item(id=6705, quantity=1), Item(id=6705, …
```
> Add support for new isle of souls chests

- cache/src/main/java/net/runelite/cache/fs/flat/FlatStorage.java
When saving FlatStorage indices the index `named` value writes the value of the index compression instead of the `isNamed` value.
> Fix incorrect named value when storing FlatStorage caches

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java
This adds the two new coordinate clues found on the Isle of Souls:
1. [North-east corner of the island](https://cdn.discordapp.com/attachments/269673599554551808/806697122379595796/Screenshot_20210204-012549_Old_School_RuneScape.jpg)
2. [West side of the island](https://www.reddit.com/r/2007scape/comments/lchm83/new_elite_coordinate_clue_location_at_west_coast/glzsuhv/?utm_source=reddit&utm_medium=web2x&context=3)
> Add Isle of Souls coordinate clues

- runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordGameEventType.java
- runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordPlugin.java
Currently, after being in a ToB party, Jagex does not properly unset `Varbits.THEATRE_OF_BLOOD` when leaving the Theatre area, only when returning. Since we use that varbit for discord activity, if you were to do a ToB and then leave afterward, your discord activity would continue to show `Theatre of Blood` regardless of your location, until you either log out or return to Ver Sinhaza. 
With that in mind, it is much easier to use the regions for raiding activity rather than the varbits. With those changed, it is no longer necessary to handle varbits within the discord plugin, thus all code related to varbits can be removed.
> discord: Use regions for raiding activity and remove varbit handling

- runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java
Adds the Nightmare instance to the ground items instance whitelist as dropped/spawned items do not stay on the ground indefinitely.
Before:
After:
> ground items: add Nightmare instance to normal despawn timers

- http-api/src/main/java/net/runelite/http/api/gson/IllegalReflectionExclusion.java
This broke plugin hub plugins using our gson, which is valid since you
can reflect into any unnamed module.
> http-api: allow gsoning classes outside of net.runelite

- runelite-client/src/main/java/net/runelite/client/plugins/chatnotifications/ChatNotificationsConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/chatnotifications/ChatNotificationsPlugin.java
With e71b18b02b124bff69cc347238551d2e0d3bf29b, repeated chat notifications are no longer a concern, thus it is now more feasible to make this addition.
Closes #7687
> chatnotifications: add private message notification

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java
Makes the coordinate clue more descriptive and adds a recommendation to both to bring a Facemask or Slayer Helmet.
> Update Sulphur Mine description for Hot-Cold/Coordinate clues

- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Adds the option to swap Use with Wield on battlestaves with no orbs in a similar vein to bury bones / clean herbs
> MenuEntrySwapper: added use-swap for battlestaves

- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TabContentPanel.java
Use `TextStyle.SHORT` to avoid pushing notification icons off of the panel.
> TimeTracking: Return shortened weekdays in doneEstimates

- runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerPlugin.java
Currently, labelling a ground marker will give the user an empty box. This is problematic if they just want to slightly change what's there, if they've got a lot of text in there. I personally ran into this issue making markers for Hydra that had instructions in them, and while that is quite an extreme example, it would be nice if the information wasn't cleared out.
Aside from that, the only functionality that changes with this PR is the existing point is always looked up (which is very very minor overhead if the user decides not to enter anything), and the user is now unable to try to label a marker that does not exist.
> ground markers: show existing label when labelling a marker

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java
Commit 36bb7c8401fdd9ae88a185e9e193b4f7183aed54 improved the clue scroll
plugin by resetting the active clue step when a beginner or master clue
item was displayed in the chat dialog when receiving a new step. This
commit caused a new bug, however, in that it became possible to click on
a new clue step while the new step dialog was open such that the new
step dialog persisted through a GameTick due to client-server delay,
causing the saved clue item ID to be lost. This commit fixes that issue
by resetting only the active clue object, but not the recorded clue item
ID, as beginner and master clues only use a single item ID.
Fixes #12565
> cluescrolls: Fix beginner/master clue step reset

- runelite-client/src/main/java/net/runelite/client/chat/ChatMessageManager.java
- runelite-client/src/test/java/net/runelite/client/chat/ChatMessageManagerTest.java
When checking if a message's sender is your friend for username recolouring, the `ChatMessageManager` fails to account for any icon the sender might have, eg. if they're an ironman or a PMod. This PR rectifies that.
Issue initially reported by `ol long sack` in Discord.
> chat color: fix usernames not being recoloured if they have an icon

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java
> cluescrolls: Re-check named object highlights after hopping

- runelite-client/src/main/java/net/runelite/client/plugins/emojis/EmojiPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/emojis/EmojiPluginTest.java
Chat messages edited through the emoji plugin would lose their color whenever the chat color cache was rebuilt from changing any chat color because they were `setRuneLiteFormatMessage()` on the message nodes without the `<colNORMAL>` indicator.
In this gif, the regular message does not change because it has no runelite format, so the widget's text never gets updated by the reloading of the color cache.
Edit: This is somewhat outdated. We are no longer using runelite formatted messages.
> Fix emoji plugin losing chat color

- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Attempt at implementing the suggestion from #11267.
This has been done by implementing a config setting in the Menu Entry Swapper UI which, if activated, will swap any set Left Click teleport for the Teleport Menu option.
Not sure if this is the most efficient way to do it so happy for feedback!
> Portal nexus menu entry swapper

- runelite-api/src/main/java/net/runelite/api/GraphicID.java
- runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java
- runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/timers/TimersPluginTest.java
As is the case with other graphics-based timers, the imbued heart timer
will not fire if other graphics animations are triggered (such as those
created when fighting the Dagannoth Kings). To add this timer more
reliably, this commit will add the timer when a Magic stat boost occurs
of the appropriate amount after recently clicking on an imbued heart.
Because the magic level boost, combined with an imbued heart click
check, is a reliable way to detect usage of an imbued heart, the
graphics check is removed.
Closes #3516
> timers plugin: Improve imbued heart detection

- runelite-client/src/main/java/net/runelite/client/plugins/cooking/CookingPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/cooking/CrowdsourcingCooking.java
Based on my spreadsheet on https://docs.google.com/spreadsheets/d/1UrDkEdgC6dl3DVPn5kQFaT8B5qUdB4YijWARSffCFDY/edit?usp=sharing this should cover all cookable items outside CoX.
> Add additional cooking messages to crowdsourcing + cooking plugins

- runelite-client/src/main/java/net/runelite/client/plugins/worldmap/TransportationPointLocation.java
Adds Ice Mountain minecart location to the world map.
Adds destination information for minecarts in the Keldagrim system and clarifies that minecarts in the Lovakengj Network are separate from those to/from Keldagrim by using proper names.
> worldmap: clarify minecart systems tooltips

- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Close #13232
Adds a Menu Entry Swap option for the Fossil Island Rowboat. Swaps the Travel option with Dive.
> Plugin: Menu entry swap for Travel/Dive on rowboat in Fossil Island

- runelite-client/pom.xml
After the addition of runelite-jshell, some of its dependencies are not
preserved during jar minimization, causing the shell dev tool to fail on
some systems. This change ensures all dependencies are preserved in the
resulting shaded jar. This change results in a roughly 2Mb larger output
shaded jar.
For reference, this error happened on my machine at runtime prior to this change:
```
client.log snippet</summary>2021-02-26 13:38:40 [AWT-EventQueue-0] DEBUG n.r.c.plugins.devtools.DevToolsPanel - Shell is not supported
com.google.inject.ProvisionException: Unable to provision, see the following errors:
1) Error injecting constructor, java.lang.InternalError: Cannot find TokenMakerFactory: org.fife.ui.rsyntaxtextarea.DefaultTokenMakerFactory  
at …
```
> client: Remove shaded jar minimizing

- runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPluginTest.java
This change ensures that tagged NPCs will be tracked throughout any
NpcChanged events, but highlighted NPCs will only display an overlay
when the current NPC name matches the config list.
Fixes runelite/runelite#5161
Closes runelite/runelite#6300
> npchighlight: Apply correct highlights to changed NPCs

- runelite-client/src/main/java/net/runelite/client/plugins/bank/BankPlugin.java
Closes #12923 
Chose the "When the bank pin interface is open, the digit keys should not be able to type into the chat" behavior to follow the same existing logic applied to chatbox/public chat.
> BankPlugin: avoid keyboard input going to input text

- runelite-api/src/main/java/net/runelite/api/Varbits.java
- runelite-client/src/main/java/net/runelite/client/plugins/kingdomofmiscellania/KingdomConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/kingdomofmiscellania/KingdomPlugin.java
I dreamt of an additional feature for the KingdomPlugin several months and finally decided to implement it. Upon login, if the user is managing the kingdom, their coffer and favor will be sent as a chat notification. The values are calculated using the last known coffer and favor values the same way the server calculates them.
~~Let me know if I should create a corresponding issue for this feature and amend this PR to close it.~~
closes #10939 
Brandt
> Feature - Kingdom of Miscellania notification message

- runelite-client/src/main/java/net/runelite/client/plugins/friendschat/FriendsChatPlugin.java
Noticed that the user count for friends chats didn't get removed if the user doesn't have `Recent Chats` enabled.
> friendschat: remove user count after leaving chat channel

- runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerSharingManager.java
As per a requested feature on the Runelite Discord
The changes in GroundMarkerSharingManager to prevent duplicate adding of the menu options are likely unnecessary. The underlying LinkedHashMultimap in MenuManager seems to handle that correctly. Should this particular piece of the PR be added "just in case" or should it be dropped?
> Ground Markers: Add toggling for Import/Export and a Clear option

- runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java
Modifies the Slayer Plugin to use the newly added RSProfiles feature to ConfigManager. This closes #249.
The website actually pulls the info from the old config fields though.
I'm not sure what needs to be done on that end. Someone who knows his way around the rl.net code would have to help with this.
With that said, this shouldn't be merged until the website can support the new config path.
> slayer: Modify to use RSProfiles Config

- runelite-client/src/main/java/net/runelite/client/plugins/bank/BankPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/itemidentification/ItemIdentificationPlugin.java
Add some more related keywords to the item identifications plugin. Open to suggestions for others to add, was considering if it's worth adding all the other kinds of items that the plugin can label for example.
Also add the keyword "pin" to the bank plugin to help find the Keyboard Bankpin feature.
Closes #13291
> Add more plugin search tags

- runelite-client/src/main/java/net/runelite/client/plugins/objectindicators/ObjectIndicatorsPlugin.java
Closes #12943
On `CONNECTION_LOST` either it reconnects and goes back to `LOGGED_IN` or falls to `LOGIN_SCREEN`, so a clear isn't needed in this transition state.
> Prevent to clear object markers on connection lost

- runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/opponentinfo/OpponentInfoPluginTest.java
Made the health bar continue to display while the opponent attacks the player.  Useful for keeping track of enemy hp while recoiling.
> opponentinfo: make health bar more active

- runelite-client/src/main/java/net/runelite/client/plugins/chatnotifications/ChatNotificationsConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/chatnotifications/ChatNotificationsPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/chatnotifications/ChatNotificationsPluginTest.java
- Added config field for regular expressions to highlight in style with ChatFilterPlugin
- Rearranged config order to follow ChatFilterPlugin style with the lists in their own section at the start
- ~~Currently no tests for regexp available~~
- Overlapping regexp is currently undefined behavior although one will guaranteed be highlighted
> ChatNotificationsPlugin: Added support for regular expression highlights

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/MapClue.java
Remove duplicate clue from MapClue causing overlay to override CoordiinateClue for hard cluescroll by magic axe hut in wilderness. Closes #13335
> Cluescroll: Remove duplicate clue from MapClue

- runelite-client/src/main/java/net/runelite/client/util/GameEventManager.java
Currently when the `GameEventManager.simulateGameEvents` is simulating `GameObjectSpawned` it does not handle correctly `GameObject`s that span multiple tiles, causing multiple events to be fired for the same object.
> Dedupe GameObjectSpawned events when simulating events

- runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/chatcommands/ChatCommandsPluginTest.java
This PR changes the capture groups for the the Hallowed Sepulchre kc patterns to match values that contain commas, and then strips those commas before invoking setKc.
> change hs kc patterns to match values greater than 999

- http-api/src/main/java/net/runelite/http/api/chat/ChatClient.java
- http-service/src/main/java/net/runelite/http/service/chat/ChatController.java
- http-service/src/main/java/net/runelite/http/service/chat/ChatService.java
- runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java
- runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/chatcommands/ChatCommandsPluginTest.java
With the addition of precise PB timings on 24/02, anyone using the new feature wouldn't be able to have their PBs saved, and they wouldn't be able to be shared even if they were saved.
This PR adds support for doubles to be stored in the config, and then uses that support to store and display all PBs as doubles. I also ended up modifying all tests that use PBs, just in case something affects the specific case it was testing, and 2 new tests were added: one for the collection log due to the existing test's size, and one for `timeStringToSeconds`
Additionally, due to precise PBs always being an integer number of ticks, it's possible to mostly know whether a PB was set with or without precise timing, which I have implemented.
In this example, the first lap was with precise timing, and second …
> add precise PB support

- runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonSpots.java
Because of shooting star update a cannon can no longer be placed at the old Cannon spot. Moved location of Cannon spot a few tiles south-east to a spot where the cannon can be placed and the cannon can hit an optimal amount of skeletons. Closes #13365
> Cannon: Wilderness Skeleton Location Change

- runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesOverlay.java
- runelite-client/src/main/java/net/runelite/client/util/ImageUtil.java
Currently the scaling does not look good, as it just forces the image into the size of the orb, not respecting the aspect ratio
This PR streamlines the code a lot (not sure why the old code even defined width and height given the values were always the exact same), while also correcting the scaling so it actually looks good. This is done through an interesting feature of `Image.getScaledInstance` whereby giving a negative value for either width or height will result in it using a value that keeps the aspect ratio for the image.
> xp globes: scale icon while respecting aspect ratio

- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/loottracker/LootTrackerPluginTest.java
Adds loot tracking for the Reward pool (Tempoross) and the new Casket. Per the request of the wiki, fishing level metadata is included.
> loottracker: Add support for Tempoross Reward pool and new Casket

- runelite-client/src/main/java/net/runelite/client/chat/ChatMessageManager.java
- runelite-client/src/main/java/net/runelite/client/config/ChatColorConfig.java
Testing out my first contribution by tackling a simple feature request from #13355 . Options added in 'Chat Color' config for both transparent and opaque.
> Added chat color option for User's own RSN

- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TimeTrackingConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/hunter/BirdHouseTabPanel.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/hunter/BirdHouseTracker.java
Closes #13262
Closes #13270
This moves the birdhouse notifications over to the notify buttons in the panel, instead of using a config option.
> time tracking: fix birdhouse notification buttons not doing anything

- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/ArdougneDiaryRequirement.java
Remove lvl 15 requirment from fishing trawler task in ardy easy diary
Closes #13476
> Remove lvl 15 requirment from fishing trawler task in ardy easy diary

- runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java
- runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/hiscore/HiscorePanelTest.java
Currently, when using the shortcut to lookup yourself on the hiscores (double clicking the magnifying glass), the normal account tab is used no matter what was set before.
Earlier, a conversation was had on Discord about getting this to also work off of chat message, since the information is available. The PR now covers this.
> hiscore: correctly look up ironmen players from chat message or self lookup

- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/ArdougneDiaryRequirement.java
- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/FaladorDiaryRequirement.java
- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/FremennikDiaryRequirement.java
- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/KaramjaDiaryRequirement.java
- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/KourendDiaryRequirement.java
- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/LumbridgeDiaryRequirement.java
- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/VarrockDiaryRequirement.java
All diary steps involving runecraft now specify that the runes must be crafted from Essence rather than the cores dropped by the new golems.
Tested in game.
Closes #13480
> achievementdiary: Update Runecraft task texts to match latest ingame texts

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java
Skill challenge clues, although they have item requirements, are not currently filtered by the `clue` bank tag.
A more proper fix might be to create an interface for clue scrolls to implement, like `ItemRequiringClueScroll` or something. Let me know if you'd prefer that.
> Add item requirement filtering for skill challenge clues

- runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/cannon/CannonPluginTest.java
A cannon that has been destroyed with cannon balls loaded
will still have them loaded when reclaimed.  This commit
does a diff of the inventory on the first message that says 
you are loading the cannon.  If the diff and inventory 
after that message both have cannon balls in them, then
we know the maximum amount possible were stored so set 
the counter to max.
Fixes #13105
> Cannon: fix reclaimed cannon initial cball counter

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollWorldOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/EmoteClue.java
- runelite-client/src/test/java/net/runelite/client/plugins/cluescrolls/ClueScrollPluginTest.java
Closes #12254
Doing this with MenuOptionClicked and ChatMessage means that the overlay will persist even when the clue scroll ends and gives you a casket.
> clues: highlight the last clue's STASH until items are deposited back

- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPluginTest.java
After subduing Tempoross, to save some time, most players choose to "Leave" instantly by interacting with one of four NPCs in the cove. I believe swapping the default "Talk-to" with "Leave" would be a minor QOL improvement for the boss.
Some self-asked QA questions:
**Is there a risk that players will leave by accident before the fight is over?**
Nope, because the option to leave early is called "Forfeit", which is not being swapped. So throughout the fight, the left-click option for each NPC is going to be "Talk-to".
**Should this swap be enabled by default?**
In my opinion, yes. I believe in 99% or even more cases players just want to leave the cove once the fight is finished. These NPCs are available outside of the cove should anyone want to learn how to play. There's also plenty of …
> menu entry swapper: add Tempoross leave swap

- runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java
Forced anti-aliasing by the GPU applies multisampling to the default
framebuffer, and when blitting between two multisampled FBOs, the number
of samples in both FBOs has to match.
In order to make sure our anti-aliasing FBO has the same number of
samples as the default FBO, we bind the default FBO and check whether
its number of samples is non-zero. If it is, use this as the number of
samples for our anti-aliasing FBO instead of getting it from the
configured anti-aliasing mode.
This unfortunately still doesn't work with `8x (4xSS, 2xMS)` forced anti-aliasing, but oddly enough works fine with `16x (4xSS, 4xMS)`. All other modes using only multisampling work fine on my Nvidia GTX 970.
> gpu: Workaround for forced anti-aliasing

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/SkillChallengeClue.java
The inactive version of the crystal pickaxe doesn't count as a pickaxe during Charlie the Tramp task to mine an iron ore.
This should fix that by adding the inactive version as an item in the requirement collection for pickaxes.
Fixes #13515
> fix crystal pickaxe inactive not counting #13515

- .github/CONTRIBUTING.md
- README.md
- runelite-client/src/main/resources/net/runelite/client/runelite.properties
Currently, the client's Discord link goes to #runelite, which means that people don't directly see the rules and general information provided in #welcome. The PR also updates the README and CONTRIBUTING files, which are still using the really old original invite.
Counterpart PR at runelite/runelite.net#400 to change the website's Discord link
> update discord links to use a link that starts users in #welcome

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
In the hard-level cryptic clue with the description
> This aviator is at the peak of his profession.
the WorldPoint for Captain Bleemadge is not set correctly.
This PR sets the correct location for him, so the world map overlay works correctly.
> Fix location of Captain Bleemadge clue

- runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java
- runelite-client/src/test/java/net/runelite/client/menus/MenuManagerTest.java
This ensures that entries added via MenuManager are added in insert order, with newly-added managed menu entries being placed lower in the menu than older ones.
For instance, with #13124 applied and all other plugins disabled, this changes the behavior from what is shown on master when opening the minimenu of the world map widget:
```
Floating World Map
Fullscreen World Map
Clear Ground Markers
Import Ground Markers
Export Ground Markers
Cancel
```
to what would be expected, given the entries are added in the order: (Export, Import, Clear)
```
Floating World Map
Fullscreen World Map
Export Ground Markers
Import Ground Markers
Clear Ground Markers
Cancel
```
> MenuManager: Add menu entries in insert order

- runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpAction.java
- runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java
- runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpPanel.java
- runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpState.java
- runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpStateSingle.java
- runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerPlugin.java
Add a menu item "Reset/hr" to reset the xp/hr and actions/hr for single skills and "Reset All/hr" to reset xp/hr and actions/hr for all skills including Overall. This option resets the per-hour rates without resetting the UI or total xp or actions this session.
Added configuration option "Auto reset per hour rates after" that resets per hour rates of a skill if xp not gained in that skill for the set number of minutes. This works like "auto pause after". If no XP is gained over that time then all skills are reset including overall. (Fixes #13001)
Single skill:
All skills:
Notes
-
Several changes were made in XpState.java to javadoc comments by IntelliJ's formatter.
> XpTracker: Reset per hour rates

- runelite-client/src/main/resources/net/runelite/client/plugins/skybox/skybox.txt
Part of #13644
Set the clan hall region to use the same colour as the GE (and a lot of other overworld places)
Wasn't sure exactly where to put the region in the skybox file, since there are a couple of entries with this specific colour
> skybox: add clan hall

- runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java
| Before | After |
|:------:|:-----:|
| ![xpinfobox-before](https://user-images.githubusercontent.com/2199511/108317390-1bd71880-71b6-11eb-8ff8-2bb95eecdcc9.png) | ![xpinfobox-after](https://user-images.githubusercontent.com/2199511/108317391-1c6faf00-71b6-11eb-8270-be61bc8ad682.png) |
Fixes #3781
> XpInfoBox: Give stats panel equal column widths

- runelite-client/src/main/java/net/runelite/client/ui/components/ProgressBar.java
BorderLayout does not guarantee equal sizing of its children, so having
a component centered between two components of unequal sizes will leave
it centered relative to their sizes, such as the following:
```
|-----BorderLayout-------------------------------------------|
||----WEST----||------CENTER------||----------EAST----------||
||------------||------------------||------------------------||
|------------------------------------------------------------|
```
Conversely, GridLayout uses fixed, equal-width columns for its children,
ensuring the center component will always occupy the center third of the
parent's dimensions.
P.S. This change causes labels to truncate earlier as they do not expand
beyond a third of the parent container's dimensions. Because the use
case for this component is …
> ProgressBar: Remove unused maximumValue field, fix center label centering

- runelite-client/src/test/java/net/runelite/client/plugins/itemidentification/ItemIdentificationTest.java
This will ensure any ImmutableMap building errors are caught at build
time rather than at runtime.
> item identification: Add item mapping test

- runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
Six hour notification could trigger incorrectly when the plugin was enabled if the player disabled -> logged out -> logged in -> enabled, since the notification timer was not reset.
> idle notifier: prevent six hour notif on enable

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/ThreeStepCrypticClue.java
- runelite-client/src/test/java/net/runelite/client/plugins/cluescrolls/clues/ThreeStepCrypticClueTest.java
Prior to this commit, ThreeStepCrypticClue simply returned a
concatenation of the active step locations without filtering the mapped
locations in any way. This could lead to NPEs in the plugin as some
cryptic clues have null locations for steps which have no specific
location or have a variable location. This commit addresses this by
making CrypticClue's location field `@Nullable`, filtering null
locations from ThreeStepCrypticClue's getLocations stream, and by adding
a test to ensure ThreeStepCrypticClue's getLocations method cannot yield
any null entries in its return value.
> clues: Fix three step cryptic clue getLocations NPE

- runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
Closes #13673
Takes a screenshot when the new collection log entry `ChatMessage` appears 
(e.g. `Chat message type GAMEMESSAGE: New item added to your collection log: <col=ff0000>Partial note</col>`)
> Add option to Screenshot plugin for new collection log entries

- runelite-client/src/main/java/net/runelite/client/plugins/statusbars/BarRenderer.java
This drop shadow was present prior to the plugin refactor in
1165780f427e1d9f86f2d658b050bf04a7ae237e which erroneously removed it.
Fixes #13271
Closes #13328
> status bars: Add counter text drop shadow

- runelite-client/src/main/java/net/runelite/client/ui/overlay/worldmap/WorldMapOverlay.java
- runelite-client/src/main/java/net/runelite/client/ui/overlay/worldmap/WorldMapOverlayMouseListener.java
Currently, icons snapped to the edge of the world map hang off the edge in a way that looks bad. This PR addresses that by making those icons use a slightly smaller area to position themselves, which keeps them on the map when snapped. This doesn't affect icons that don't snap, as they use a different rect.
This also fixes an issue that arose with icons overlapping the close button, which close the map when clicked. This is due to the overlay being drawn on top of the close button and completely covering it. I fixed this by consuming the mouse click event if an icon is clicked.
> world map overlay: make icons display fully on the map when edge snapped

- runelite-client/src/main/java/net/runelite/client/plugins/chathistory/ChatHistoryPlugin.java
After the clan update, every chat line is now 4 dynamic widgets rather than 2, in the order of Sender, Message, Clan Name and Clan Rank. The last two are hidden for messages not coming from clan chats.
The incorrect multiplication was causing the copy to clipboard feature to either fail from grabbing the empty text from a hidden or clan rank widget, or pick up a more recent message than the one selected.
> ChatHistory: Fix "Copy to Clipboard" after clan update

- runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java
Updated ground items to include tempoross in instances that have a 3 minute despawn timer.
Fixes #13456
> Tempoross timer bug

- runelite-client/src/main/scripts/ToplevelCompassOp.rs2asm
When clicking the compass, the vanilla camera will jitter randomly within 5 values. With "compassLookPreservePitch" enabled, spam clicking the compass would cause your camera pitch to rise repeatedly by that random jitter. This places the camera pitch restore callback after the random jitter, to eliminate that discrepancy.
Current:
Patched:
> camera: prevent pitch increment with "preserve pitch" enabled

- runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java
Adds toggle option for player to choose to override the default client xp drop colors, allowing for more options/variety.
Does not affect the ability to change colors when using prayers.
> Xp Drops: Add option to override standard client xp drop colors

- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
Adds loot tracking for Supply crate from Wintertodt
Closes #5824
Closes #5883
> loot tracker: Add Supply crate (Wintertodt)

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java
The current description dates back to before the addition of the Ferox Enclave into the game. This updates it to be closer to the new landmark.
Edit: Don't mind the "east" in the picture.
> clues: Update description for coordinate south-west of Ferox

- runelite-client/src/main/java/net/runelite/client/util/ImageCapture.java
#7840
Unrestricted/Beta worlds are the same as Tournament worlds - this change saves screenshots in different folder when a user is on such a world.
> Added suffix to screenshot folder when on tournament world

- runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialCounterPlugin.java
When leaving Vorkath or Alchemical Hydra fights, the spec counter does not reset, despite the boss resetting their stats. This could cause the spec counter to add the player's next trip spec to that, giving an inaccurate total spec count. This clears that counter when leaving the vork + hydra region instances.
Needs to be tested at hydra, since I don't have access to that fight to test myself. Drafted until then.
> Reset spec counter when leaving instanced fights

- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
Make the loot tracker check the MenuAction of the menu entry when setting the event. 
This came about due to a bug with the Wintertodt crate tracking. Turns out that 20703 (the ID of the Wintertodt crate) is shared with the
impostor for the doors at barrows, which can have an Open option. This
caused random entries to be collected at Barrows as if it were crate
loot. As this could unknowingly affect other events in future, it's now future-proofed against that.
> loot tracker: check for correct menu option type when deciding event

- runelite-api/src/main/java/net/runelite/api/AnimationID.java
While working on something tangentially related, I noticed that the animationID for doing construction with the Imcando Hammer was wrong. I don't think Jagex changed the animation recently, so it's likely my fault from when I added it, sorry.
> api: correct imcando hammer construction animation

- runelite-api/src/main/java/net/runelite/api/SpriteID.java
- runelite-api/src/main/java/net/runelite/api/Varbits.java
- runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java
- runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/timers/TimersPluginTest.java
Arceuus spells have two different timers: the duration of the effect, and the cooldown before they can be cast again. There are 5 types of spells (all 9 thrall spells share the same timers):
* Shadow Veil
* Ward of Arceuus
* Death Charge
* Thrall spells
* Corruption (cooldown)
How Ward of Arceuus looks with both options enabled:
SpriteID also had a lot of bit-rot with the old arceuus spells
> timers: add duration and cooldown timers for arceuus spells

- runelite-api/src/main/java/net/runelite/api/SpriteID.java
Turns out that when Jagex updated the hitsplats, they moved some of them around, and the venom splat got moved far away from the others.
This has been the case since 28/04.
> poison: fix venom hitsplat sprite

- runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/timers/TimersPluginTest.java
turns out that thrall spells are seemingly the only arceuus spell with a
magic-level based duration that uses the boosted level, at least out of
the ones we have timers for
> timers: make thrall timer use boosted magic level

- runelite-client/src/main/java/net/runelite/client/plugins/mta/alchemy/AlchemyRoom.java
the plugin used to use 8-12 for names and 13-17 for points, but it should actually use 7-11 and 12-16. This fixes the issue of leather boots not being highlighted when they are the highest value item (as they use ids 7 and 12), as well as the cupboard not resetting when leather boots become the highest valued item.
Fixes #13787
> Fixes mta alchemy room widgets ids.

- runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
Closes #13792
The OverlayRenderer clamps overlays to an overlay-defined parent. This clamping wrongly assumes that the parent is in the top-left corner of the screen. Up until last week, this seemingly had no ill effect on functionality, but with the Great Widget Shift of 2021 a few widgets parents now sit down from the top corner, giving the issue seen in #13792.
This is what the range of the GWD currently looks like when not accounting for the parent's position.
Blue is the parent's true bounds, and Green is the range that the overlay has to be inside, aka the effective bounds.
> overlay renderer: account for parent's position when clamping location

- runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java
Closes #13764
Something to note is that this change does not cause a line to the drawn at the right edge of the box when using level-aligned goal ends, which is nice.
> xp tracker: fix intermediate markers not showing for xp based goal ends

- runelite-client/src/main/java/net/runelite/client/plugins/wintertodt/WintertodtPlugin.java
This change also sets player fletching status from game chat message as a redundancy when onAnimationChanged does not fire quickly enough when you restart fletching.
Fixes #8412
> wintertodt: bugfix fletching activity status detection

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/AnagramClue.java
Seems like this NPC's capitalization changed with the Shayzien rework, breaking this specific anagram clue.
**Before:**
**After:**
> clues: Fix capitalization for "New Recruit Tony" master anagram

- runelite-client/src/main/java/net/runelite/client/plugins/chatnotifications/ChatNotificationsConfig.java
A simple non-functional change that should clarify usage.
Clarify that multiple words can be entered in the input box by separating them with commas.
> Clarify how to enter multiple words

- runelite-client/src/main/java/net/runelite/client/plugins/inventoryviewer/InventoryViewerConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/inventoryviewer/InventoryViewerOverlay.java
Added new setting to only show the inventory viewer overlay when the inventory tab is not selected.
Closes #13318
> Add option to only enable inventory viewer when inventory tab is closed

- runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java
With debug assertions on, the "Screenshot Scout Overlay" keybind sometimes fails for me with a stacktrace saying it should be run on the client thread (I couldn't get it to appear when I went back to try and grab it for this PR, but I will update this if I can get it again).
The offending call chain is `RaidsOverlay#render` -> `RaidsOverlay#shouldShowOverlay` -> `client#getVar`.
Moves the call to the client thread to prevent issues.
> raids: screenshot overlay from client thread

- runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
Display the cannon timer upon setting up the first cannon part. The decay timer is reset after adding an additional part to the cannon. This change is useful when only setting up the cannon base, instead of the entire cannon. Example use case [here](https://youtu.be/Ce5qU85QPUc?t=14).
> timers: add cannon parts

- runelite-client/src/main/java/net/runelite/client/ui/overlay/outline/ModelOutlineRenderer.java
The model outline renderer can simulate model rasterization on the top 4 pixel lines outside the clip area in fixed mode. The clipped rectangle doesn't allocate memory there which causes a write into negative index in an array which causes the overlay to crash.
Fixes #13864
> Fix model outline renderer crashing in fixed mode

- runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java
- runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
Adds a simple timer when your cannon breaks, showing the 10 minutes you have to repair it. Uses the icon for the Repair Kit used in the Dwarf Cannon quest.
> timers: add cannon repair timer

- runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java
- runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
A simpler implementation of the feature request brought up in #12720.
Timer displays how long the player is stunned for (5 seconds for most pickpocket targets).
> Added pickpocket stun timer to timers plugin.

- runelite-client/src/main/java/net/runelite/client/plugins/statusbars/StatusBarsConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/statusbars/StatusBarsOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/statusbars/StatusBarsPlugin.java
**Duplicate of #7445 due to Orphaned Source branch.** 
Upon many emails and several requests to fix the review suggestions made by @Nightfirecat in #7445 , I came back to clean up those review items in hopes to have this merged into a release for all those people that have asked.
_Duplicate PR content:_
This is to only show the Status Bars only when in Combat, and hides it based on the delay set.
Closes #7436
Toggle Demo: https://gyazo.com/ee277e5f0d4bfad598a7a1049d972a67
Delay Demo: https://gyazo.com/421e2a4a725725f1b7b5e62f96a6a8a3
> Add a Toggle to the Status Bars w/ a Delay to show only in Combat

- runelite-client/src/main/java/net/runelite/client/ui/overlay/worldmap/WorldMapOverlay.java
> worldmap: use correct bounds for tooltip hit checking

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
Fix location of the cryptic clue crate to search in Shayzien.
> clues: Fix Shayzien cryptic clue crate location

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/Enemy.java
The Isle of Souls only spawns an Armadylean guard at the western
location, and a Bandosian guard at the eastern location.
> CoordinateClue: Fix Isle of Souls enemies

- runelite-client/src/main/java/net/runelite/client/plugins/music/MusicPlugin.java
Fixes #13881
This may also fix #13817 if it caused by thrashing the music player as I suspect, but I am unsure as I still don't have a reproducer for that bug.
> music: use vanilla's volume percentage conversion

- runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
Close #13916 
Change messageNode `setValue` to `setRuneLiteFormatMessage` to correctly accept colour overrides
**Screenshot**
> Chat commands: add colour override fix to pet cmd output message

- runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java
Closes #13934
Currently, if `Only show loot` is enabled, loot beams won't show up until the item pile changes on the floor. This is due to a race; when the item spawns, it's not been decided whether it's your loot or not. As a result, if the player has `Only show loot` enabled, they won't get a loot beam. Also making the plugin handle the lootbeams in the `lootReceived()` function causes them to get set correctly, as by this point the loot's owner has been decided.
> ground items: make loot beams work with only show loot

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
I noticed this inconsistency when doing easy clues. Almost all of the Wizards' Tower clues contain a fairy ring code, except for this one line. I decided to edit it and add the code in to keep it in line with other clue hints. Certainly not the biggest commit but I figured this would help out.
> Cryptic clue: update missing Wizards' Tower fairy code

- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
Performs RegEx to determine what loot was received from the chest.
**Screenshot:**
> added rogues' chest loot tracking

- runelite-client/src/main/java/net/runelite/client/util/Text.java
- runelite-client/src/test/java/net/runelite/client/util/TextTest.java
**Note:** A blank character in this context represents any of a space (either normal or non-breaking), `_` or `-`. I am also replacing spaces with `+` in this message because GitHub markdown appears to delete extra spaces in their one-liner code blocks.
While the game does not allow players to enter names containing trailing/leading blank characters or multiple blank characters in a row, there are seemingly ways around that (such as the infamous `+Spacehack`, but also `0++Crazy++0` (notice the double spaces). Trailing and leading blanks are currently handled correctly in all cases, but there are issues with blanks inside of the name.
Taking `Crazy` as an example here, in Jagex's database it would be distinct from, say `0+Crazy+0`, and any of the blanks should be able to be substituted to …
> Fix toJagexName removing double spaces in some cases

- runelite-client/src/main/java/net/runelite/client/plugins/banktags/BankTagsPlugin.java
Prior to this change, an extra row of empty space was added to tag tabs
with items reaching the end of a row (ie. multiples of 8) which led to
scroll behavior not matching vanilla for tabs with enough items to
require scrolling. This change fixes this behavior to add extra scroll
height only when a new row is started.
In addition to the 36 pixels of height allotted to each bank item row,
an additional 4 pixels of height exists at the bottom of the bank item
container. This change ensures that a bank tag scrolled to the bottom
will have its items displaying at the exact same y values as that of a
normal bank tag.
Fixes #13676
> banktags: Fix bank scroll height with separators hidden

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
Fixes the arrow coordinates so the crates are highlighted
Before:
After:
> Cryptic Clue - Fix hosidius fruit store crates highlighting

- runelite-client/src/main/java/net/runelite/client/account/SessionManager.java
- runelite-client/src/main/java/net/runelite/client/plugins/account/AccountPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/info/InfoPanel.java
- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerConfig.java
A couple of months ago (217a5425d408dd22ab0ccf1f6e902886647cc342), the wording of the import button was changed to refer to the `signed-out` account. The rest of the client still refers to the user being `logged in` to a RL account however. This changes that to standardise the wording onto `signed in/out` instead of `logged in/out`.
This PR only changes the user-facing text; If desired, I could also update variables and functions, or even the web addresses used for signing in and out.
> client: update various wordings to use "signed in/out" for RL accounts

- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerBox.java
Also removes the unnecessary HA line for Coins and Platinum, along with the GE line for Coins
> loot tracker: add ea display to tooltips

- runelite-client/src/main/java/net/runelite/client/plugins/roofremoval/RoofRemovalPlugin.java
Since instances shift around real regions to WorldPoints that don't
match, the override system was trying to apply overrides to areas that
don't currently exist.
This will mostly affect quest areas (eg. Harmony Island Church during The Great Brain Robbery, which is where I first heard of this issue), but it will also allow for the POH to receive overrides in the future.
> roof removal: properly account for instances when applying overrides

- runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesOverlay.java
Currently, the xp's bounds do not account for the progress arc, as it is drawn either side of the perimeter of the background circle. This PR addresses that.
On `master`:
With this PR:
This also fixes the progress arc being drawn off-screen or interfering with other overlays when the progress arc size is excessively high (shown here with 20px):
> xp globes: account for progress arc width when deciding overlay bounds

- runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonSpotOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonSpots.java
Adds two Dagganoth cannon spots in Jormungand's prison which closes #13503 
One spot it to the West and enjoys more low-level Dagganoths which are better due to their nonexistent Ranged defence, and one to the East which is more open and therefore has more targets to shoot at. The positions themselves are relatively optimal in terms of cannon range and respawn positions but may possibly be altered based on more concrete data.
Also took this opportunity to combine the max rendering distance for both cannon overlays (cannonballs left, double-hit spots when the cannon is placed and the optimal positions when the cannon is not placed) which were for some reason separate but almost identical. Also increased the distance itself to somewhere around the maximal distance in which you can also …
> cannon: add recommended spots for dagganoths and increase overlay distance

- runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java
When interacting with another player's cannon, a completely different
message is returned. Using this, if we ever get a normal cannon message
after clicking on a cannon, we can be 100% certain that it is ours.
Closes #8106 by allowing the player to fix it without a re-place
Also cleaned up the mess that is `onChatMessage`, which was doing an unnecessary amount of string operations on cannon-related messages.
> cannon: update cannon location when interacting with the player's cannon

- runelite-api/src/main/java/net/runelite/api/coords/WorldPoint.java
- runelite-api/src/test/java/net/runelite/api/coords/WorldPointTest.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java
- runelite-client/src/main/java/net/runelite/client/plugins/skybox/SkyboxPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/cluescrolls/ClueScrollPluginTest.java
This PR moves the clue scroll plugin's `getMirrorPoint()` to WorldPoint so it can be accessed across multiple plugins.
Fixes #13730
> skybox: Show surface color while in Prifddinas

- runelite-api/src/main/java/net/runelite/api/coords/WorldArea.java
- runelite-api/src/main/java/net/runelite/api/coords/WorldPoint.java
- runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaPlugin.java
These utility methods are useful in plugins both for the hub and runelite. I swapped out one of the old ways it was done in the NpcAggroAreaPlugin as an example. I ran some unit tests and the methods seem to functionally be the same as the distance == 0 checks.
> Add new utility methods for checking if world points are inside world areas

- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/ShiftDepositMode.java
This required 2 changes:
- adding the identifier (9) to ShiftDepositMode.
- Updating the swap code to only swap with the entry with the correct identifier. This is necessary because the deposit box can have options with both 1 and 2 identifier, while the regular bank only has one with identifier 2 (not sure on chambers of xeric storage unit as I don't have membership). Not including this change breaks the swap when the deposit box vanilla left-click option has values other than deposit-1.
Tested a few combinations of menu swapper and vanilla bank left-click options, and it seems to work (did not test all combinations since there are a lot).
Did not test that chambers of xeric swap still works, as I don't have membership.
> Fix for extra op swapping on the deposit box.

- runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
Adds `cg` as a shorthand for Corrupted Gauntlet, for `!kc cg` and `!pb cg`. As Corrupted Gauntlet becomes a better moneymaker and more popular, I think this is a good addition and not likely to be confusing.
The wiki also considers `cg` to be shorthand for the Corrupted Gauntlet, via a redirect page.
https://oldschool.runescape.wiki/w/Cg
> chatcommands: cg shorthand for corrupted gauntlet

- runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/SkillCalculator.java
Update skill calculators to correctly show plurals of action as "0 actions", "1 action", "2 actions", "3 actions", etc.
Old behavior showed "0 action", "1 action", "2 actions", etc
> Update to skill calculator "action" plurals

- runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java
Currently it's not easy to tell exactly what GPU is being used by the plugin in multi-GPU systems. This becomes a problem when the dGPU decides to not do any work, and forces the iGPU to do GPU rendering. Whenever someone comes into the support channel with performance issues with the GPU plugin, we just have to guess whether it's actually a real performance problem, or if it's just on the iGPU that has no/bad drivers. This change should help with that.
Since it uses the GPU's default profile, it shouldn't have any compatibility issues as long as the GPU isn't from the 90s, and it will always run before it would fail to get an OpenGL 4 profile (tested that this happens on my i5 2nd gen craptop)
This may also help to narrow down potential driver-based issues, since `GL_VERSION` spits out …
> gpu: display device and driver being used during plugin startup

- runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargePlugin.java
Close issue #14008
Plugin: ItemChargePlugin
Makes ring of forging charges correctly reflect upon triggering the Varrock platebody effect.
Decrements charges by two if player has at least two iron ore in inventory.
Decrements charges by only one if player only has one piece of iron ore and the platebody effect is triggered.
> Makes Ring of forging correctly reflect charges when using a Varrock platebody

- runelite-client/src/main/java/net/runelite/client/plugins/slayer/Task.java
Duck is missing from the list of monsters to kill for a bird slayer task.
Updated the birds targetNames to include "Duck" within the slayer plugin.
> Update slayer plugin to include "Duck" as a slayer monster for a birds task

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CipherClue.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/MapClue.java
This mostly speaks for itself. `itemComposition != null` is removed from the plugin as it is vestigial--it will never be false.
> cluescrolls: Add X Marks The Spot quest solutions

- runelite-api/src/main/java/net/runelite/api/Varbits.java
- runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/timers/TimersPluginTest.java
Found a nice little Varbit (5361) that gets sent to the client in intervals of 6 containing remaining Imbued Heart cooldown time.
So instead of utilizing the menu entry coupled with the actual Magic boost to figure out when the player started the boost (which introduced an issue of "forgetting" remaining time when logging off or hopping worlds), it's switched to using information from the Varbit (which has a nice side-effect of "remembering" cooldown between logins).
Also fixes the bug of using the Heart while in the bank
Technically it would be a little cleaner to simply re-create the timer every 6 seconds, but for the sake of performance I simply saved a reference.
Closes #14091
> timer plugin: overhaul handling Imbued Heart cooldown

- runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java
Clan hall has normal despawn time, not 3000 ticks. Exclude clan hall from default instance despawn time.
> Fix clan hall ground items despawn timer

- runelite-client/src/main/java/net/runelite/client/game/RunepouchRune.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/runepouch/RunepouchOverlay.java
- runelite-client/src/test/java/net/runelite/client/plugins/cluescrolls/ClueScrollPluginTest.java
Closes #11319
This makes it so the contents of the Runepouch are added to the inventory items, which allows them to be used in item requirements.
> clues: make item requirements work with the runepouch

- runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterPlugin.java
- runelite-client/src/main/java/net/runelite/client/util/Text.java
- runelite-client/src/test/java/net/runelite/client/plugins/chatfilter/ChatFilterPluginTest.java
- runelite-client/src/test/java/net/runelite/client/util/TextTest.java
This lets plain latin-character filters to match messages with accents
and diacritics which are not easily typed on all keyboard layouts.
Fixes #13097
> chat filter: Ignore character accents for matching

- runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialCounterPlugin.java
Prevents spec counter resetting when attacking a skeleton hellhound spawned by Vet'ion. The hellhounds are spawned at 50% HP, and are required to kill to continue the fight, so the player will continue fighting Vet'ion after they are killed.
It's possible that a player may want to use a spec against the hellhounds, but I'm not aware of any reason for it.
> special counter: ignore vet'ion hellhounds

- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
This is related to https://github.com/runelite/runelite/issues/14353
The max cape teleport menu entry wasn't being swapped with wear by the plugin because it has a `Teleports` entry rather than a `Teleport` entry.
> max cape teleports swap

- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/KourendDiaryRequirement.java
Closes #14390
Removed the quest requirement for the "Browse the Warrens General Store" task.
> achievement diary: remove quest requirement

- runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
Currently the pickpocket stun timer does not take the dodgy necklace protect into consideration. If you fail to pickpocket but get saved by the dodgy necklace, the timer indicator still shows up.
This change makes it so that when the dodgy necklace protection message shows up, the pickpocket stun timer started previously is removed.
Notice that the indicator only shows up when failing to pickpocket and no dodgy necklace protection.
> Add dodgy necklace protection to pickpocket stun timer

- runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/Tree.java
Changed respawn times to the wiki values this closes issue 
#14285
Timers now also match the style of the rocks (based on gameticks)
- [Oak](https://oldschool.runescape.wiki/w/Oak)
- [Willow](https://oldschool.runescape.wiki/w/Willow)
- [Maple tree](https://oldschool.runescape.wiki/w/Maple_tree)
- [Teak](https://oldschool.runescape.wiki/w/Teak)
- [Mahogany](https://oldschool.runescape.wiki/w/Mahogany)
- [Yew](https://oldschool.runescape.wiki/w/Yew)
- [Magic tree](https://oldschool.runescape.wiki/w/Magic_tree)
- [Redwood tree](https://oldschool.runescape.wiki/w/Redwood_tree)
> Tree respawn times updated based on wiki info

- runelite-client/src/main/java/net/runelite/client/plugins/party/PartyConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/party/PartyPanel.java
- runelite-client/src/main/java/net/runelite/client/plugins/party/PartyPlugin.java
I've seen requests in the discord to be able to persist parties between sessions so this PR adds that and since you need a party uuid to join a party, I also added the option to join a party by id and a button to copy your current parties id.
[gif of it in action.
](https://cdn.discordapp.com/attachments/836283317036122192/897990216948785272/Animation11.gif)
It's hard to see that I am copy pasting the uuid into the plugin search but its meant to show that after I had left and rejoined, the party id was the same.
> Add party persistence config and ability to join by party id.

- runelite-client/src/main/java/net/runelite/client/Notifier.java
- runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java
Now allows to change the time a notification is shown, or if the
option is set to 0 it should use the system configuration.
Should be noted that Ubuntu and CentOS ignores these options, see
``man notify-send`` for more info.
> notifier: add timeout option for Linux

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java
We have some residual code that handles Leagues 2 hot/cold clues.
Because Leagues is pretty unique, it is unlikely this code pathway will be run again -- and even if it does, it could be implemented in a different way such that things will break. For example, Leagues 9 could have beginner clues residing in Kandarin, using Watson as the source.
So in this PR, we remove this code path.
> clue: Delete Leagues 2 code relating to hot/cold clues

- runelite-client/src/main/java/net/runelite/client/plugins/roofremoval/RoofRemovalPlugin.java
Related to: https://github.com/runelite/runelite/pull/14529
The first [commit](https://github.com/runelite/runelite/pull/14536/commits/3af75e6752deb963dc9da690d5afe4f442b041e7) fixes an issue where POH roof removal overrides weren't initialized on plugin startUp when configured to do so.
The second [commit](https://github.com/runelite/runelite/pull/14536/commits/99b0a18a4c4c159b5a480c5fb2a069babf33469e) moves the `configOverrideRegions.contains(regionID)` conditional out of the inner for loop, as it's parameter did not change across loop iterations.
> Roof removal poh fixes

- runelite-client/src/main/java/net/runelite/client/util/SwingUtil.java
Currently, clicking the tray icon on macOS doesn't bring the client to the front like it is supposed to. This PR fixes that.
> Fix clicking tray icon not bringing client to front on macOS

- runelite-client/src/main/java/net/runelite/client/externalplugins/ExternalPluginManager.java
if you started 2 clients with different configs at the same time one
client could delete files out from under the other while it was trying
to load them, causing them to fail to load
> rl-client: keep plugin hub jars around for longer

- runelite-client/src/main/java/net/runelite/client/util/SwingUtil.java
After https://github.com/runelite/runelite/pull/14543, clicking the tray icon on macOS when the client is focused results in a flicker. The flicker is due to the visibility change required to correctly restore focus, but there's no reason to run that when the client is already focused.
Sorry for not catching this before submitting the last PR.
> Fix flicker when clicking tray icon click on macOS when client is already focused

- runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordPlugin.java
Discord avatarId can contain underscores when the image is animated (it has prefix a_ when that happens).
Fixes #14594
> Add underscore to Discord avatarId matcher

- runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
A simple change to let the user know if they're running the client in safe mode, similar to how other applications display it (e.g.  
[LibreOffice](https://user-images.githubusercontent.com/2979691/149822381-c8071303-f45e-450e-8a5f-23946cd821b6.png)). This will help with users in #support who swear they've ran the client in safe mode, but have screwed it up somehow.
> clientUI: show if the client is in safe-mode in the window title

- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Tested on stairs and ladders. Does not interfere with barbarian assault quick-start swap or volcanic mine pay swap.
Would close #14568 
Closes #3562
Closes #7450
Closes #5247
> Menu Entry Swapper: add climb-up and climb-down swaps for stairs/ladders/etc.

- runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/ShiftDepositMode.java
This adds the shift-deposit functionality to the group storage inventory in the menu entry swapper plugin.
> MenuEntrySwapper: Group Iron Storage shift deposit

- runelite-client/src/main/java/net/runelite/client/plugins/dailytaskindicators/DailyTasksPlugin.java
UIMs can't claim sand from bert, so this message should be hidden.
> Remove daily sand check for UIM accounts

- runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaOverlay.java
This adds a toggle setting in the NPC Aggression Timer plugin to hide the aggro lines when not in combat.
> Add option to hide npc aggro lines when out of combat. SupahSoftware

- runelite-client/src/main/java/net/runelite/client/plugins/PluginManager.java
- runelite-client/src/test/java/net/runelite/client/plugins/PluginManagerTest.java
This PR has 2 commits. The first is a minimal change which reproduces the concurrent modification exception (CME) I mentioned in #14552 on my machine (openjdk 17 and 11). The second is a fix which prevents the CME from happening by making a new hashset in every iteration in `topologicalSort`.
Code formerly built a directed graph, topologically sorted it then reversed
the sorted list. This is mathematically equivalent to reversing the edge
direction in the directed graph. Changing the edge direction (and removing
the call to Lists.reverse) causes a CMEin the topologicalSort function
Copy pasted log tail including stacktrace:
```
2022-02-04 20:04:16 [main] DEBUG n.r.client.config.ConfigManager - Loading configuration value groundMarker.rememberTileColors: true
2022-02-04 20:04:16 [main] …
```
> Fix topological sort Concurrent Modification Exception

- runelite-client/src/main/java/net/runelite/client/plugins/fairyring/FairyRings.java
The Land of the Goblins quest introduced a new fairy ring. The fairy ring plugin currently displays it as an invalid location, so this PR fixes that.
> Add new Yu'biusk fairy ring

- runelite-api/src/main/java/net/runelite/api/Varbits.java
- runelite-client/src/main/java/net/runelite/client/ui/overlay/WidgetOverlay.java
The Wilderness and PVP kill-death information box is created while in
these areas regardless of whether the setting (configured via the notice
board at the Edgeville bank) is enabled to show the text, meaning the
widget contains only empty text widgets when the setting is disabled
rather than being null, causing a bounding box to still be drawn and
affecting other snapped widget layout. This commit adds a child class of
WidgetOverlay specific to this widget and prevents it from being drawn
when the setting to show this information is disabled.
Fixes runelite/runelite#6089
> widget overlay: Don't draw empty wilderness K/D box

- cache/src/main/java/net/runelite/cache/definitions/loaders/ModelLoader.java
Only variable names here have changed, except var41 in face index decompression appeared to be an unnecessary duplicate of var40 so I removed it.
> Rename automatically-named variables in ModelLoader.decodeOldFormat

- runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java
This commit works around a bug with loading natives when the user's home folder contains special characters such as `&`, `^` or `!`.
When Gluegen loads native libraries on Windows, it uses a temporary directory located in `%appdata%` under the user's home directory, and Gluegen [checks whether files can be executed](https://github.com/runelite/gluegen/blob/5d144eb31e9623d33074c105013595592b0e1ec5/src/java/com/jogamp/common/util/IOUtil.java#L1049-L1054) from this temporary directory. To perform this check, it writes an executable to the directory, executes it, and ensures that the return code is zero. The executable file it writes is by default a `.bat` file, but it can be told to write an `.exe` file instead by supplying this VM argument: `-Djogamp.gluegen.UseNativeExeFile=true`.
The …
> gpu: Fix loading Gluegen natives on Windows with special characters in the username

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
Fixes incorrect capitalization used on the Guardian mummy hard clue step, causing the npc not to be highlighted.
Before:
After:
> Fix Guardian mummy capitalization on hard clue step

- runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java
The Slayer plugin highlights target monsters based on their name rather
than NPC ID, as many common monsters (skeletons, zombies, etc.) have
nearly endless variations for different models and combat levels.
Previously, this name matching was done via a simple
`String#contains()`, which led to some incorrect matches such as pirates
being highlighted while on rat tasks and Jonny the beard being
highlighted while on bear tasks.
This commit changes matching to use regex to match string boundaries or
whitespace at either end of the task string, ensuring these substring
matches can only happen when word breaks occur. The only known existing
case where this would apply is for baby dragons and brutal dragons,
which are valid alternatives for their respective chromatic dragon
tasks.
Fixes #6285
> slayer: Fix name matching

- runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
`onDeactivate()` currently only runs when the plugin panel is explicitly closed, but not when it's implicitly closed from switching to a different panel. This fixes that.
There currently doesn't seem to be any core plugin that actively uses `onDeactivate()`, but there are some plugin hub plugins that are affected by this bug.
> ClientUI: Run PluginPanel#onDeactivate when switching panels

- cache/src/main/java/net/runelite/cache/script/assembler/ScriptWriter.java
A flaky test is found in this project and this PR proposes to fix it.
1. How to reproduce the flaky test
- The project is built and tested under `javaJDK8`.
- The tool used for the flaky test detection is [NonDex](https://github.com/TestingResearchIllinois/NonDex).
- I ran `mvn -pl cache edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=AssemblerTest`, which produced
> testAssemble\[0\](net.runelite.cache.script.assembler.AssemblerTest)  Time elapsed: 0.114 sec  <<< FAILURE!
> org.junit.ComparisonFailure: expected:<...
> [3: LABEL20
>  5: LABEL54
>  6: LABEL54
>  7: LABEL3]
> jump            ...> but was:<...
> [5: LABEL54
>  3: LABEL20
>  7: LABEL3
>  6: LABEL54]
>  jump            ...>
2. Why the tests failed
- In the failed test, the method `assemble` of class `Assembler` is used to …
> Fix a flaky test

- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
fixes  #14787
Not a lot to it. 👍🏼 Simple add ability to swap "Deposit" with "Deposit-runes" on the Deposit pool in Guardians of the Rift. I think this should be the default.
> [Menu Swapper] Swap "Deposit" with "Deposit-runes" for the Deposit pool in Guardians of the Rift.

- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
fixes #14788 
Adds the ability to swap the left-click Take option for the Uncharged Cells in Guardians of the Rift.
> [Menu Swapper] Add Take-X Uncharged Cells swap for Guardians of the Rift

- runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaNotWorkingOverlay.java
Currently, the tutorial overlay is hidden when no tracked NPC is in range. This makes knowing whether the plugin has been calibrated very annoying unless the user has `Always active` enabled. By making it always visible when not calibrated, the user can be sure when they've done it correctly, and easily prepare for it before the long trek to Sand Crabs. 
I've also updated the message to be more specific for what the user should do, though I have no idea why they need to do anything more than teleport/enter a cave to fix it as it wasn't reproducible during testing.
If the user does not want to see the overlay all the time, they can turn off the plugin; it wasn't calibrated before, so they lose out on nothing by turning it off.
> npcaggro: always show tutorial overlay if plugin is not calibrated

- cache/src/main/java/net/runelite/cache/definitions/loaders/ScriptLoader.java
- runelite-client/src/main/scripts/ChatBuilder.rs2asm
- runelite-client/src/main/scripts/ChatSplitBuilder.rs2asm
- runelite-client/src/main/scripts/FriendUpdate.rs2asm
- runelite-client/src/main/scripts/LayoutResizableStones.rs2asm
- runelite-client/src/main/scripts/PrivateMessage.rs2asm
- runelite-client/src/main/scripts/SkillTabBuilder.rs2asm
This makes the order of cases preserved to what they are defined as in the script file. Since this might cause issues with mapping scripts, this also included ordering the switches in overridden scripts based on the new output.
@abextm
> Use LinkedHashMap for switch jump tables

- runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargePlugin.java
When using a binding necklace in crafting combination runes with the Guardians of the Rift minigame, the chat message given is always "You partially succeed to bind..". This modifies the regex to match these messages as well. Since this is also the message sent when the player does not have the necklace equipped, there is an added check to ensure the player has one equipped.
> Item Charge: fix binding necklace degrading in gotr

- runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/chatcommands/ChatCommandsPluginTest.java
Adds the shayzien basic and advanced agility course to the 'boss' list.
This way commands like !kc and !pb will work accordingly. Also moved
prif agility course closer to the other agility related bosses.
---
This should resolve issue #14796
> Add support for shayzien agility course

- runelite-client/src/main/java/net/runelite/client/plugins/inventoryviewer/InventoryViewerOverlay.java
Fixes issue where inventory viewer still shows on the bank interface being open if the configurable setting "Hidden on inventory tab" is checked
> Inventory Viewer: Hide inventory viewer when bank interface opens

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CipherClue.java
March 23 2022 update changed his name to have "Wizard" in front causing cryptic clue to not highlight him.
See: https://oldschool.runescape.wiki/w/Wizard_Traiborn
> clue scroll plugin: Rename Traiborn to Wizard Traiborn

- runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/AggressionTimer.java
- runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaPlugin.java
After using 8ad5977ad5ef61ea84cb89a89956402e951b013f for a while, I noticed that the plugin would lose calibration seemingly at random. Given I was sitting at Redwoods, this didn't make sense. I want to give some context as to what was happening and why, baked permanently into the commit history:
The plugin requires that a few things exist when it saves data, or else it assumes that something went wrong and it resets the config. One of these things is that the infobox object exists.
Usually, this is fine, as one is created on login with the stored duration, as long as said duration is not negative.
However, if the user stood in the same area for 10 minutes and then logged out somehow (either manually or through AFK), upon logging back in the config would not create a new infobox as the …
> npcaggro: fix unintended loss of calibration

- runelite-client/src/main/java/net/runelite/client/plugins/bank/BankPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/bank/BankPluginTest.java
Closes: #14814
Added bank search query for item quantities.
Note: Treating placeholders as quantity 0 by checking placeholderTemplateId
Examples:
4/26 edit: Now using "qty" as the search term rather than "q"
> Bank Search: Quantity search query

- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Closes: #14813
Added new picklist in the UI section of the Menu Entry Swapper plugin to control what destination 'teleport to house' should take.
This is needed because Jagex added new right-click teleport options for group ironmen.
The new picklist of options can only be utilized if the 'shift-click teleport spells' checkbox is also checked*
GIM teleport example:
Non-GIM teleport example:
> Menu Entry Swapper: Add configurable house teleport swap options

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/AnagramClue.java
It seems like the capitalization changed at some point, likely after GotR.
> clues: Fix capitalization for Dark Mage anagram

- runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatKeyboardListener.java
Prevents a binding of "Ctrl+Backspace" from triggering the "clear single word" and also removing the remaining trailing space.
Closes #14941
> chatcommands: consume "clear single word" keypress

- .gitignore
.DS_Store is an invisible file created on MacOS that stores metadata about the files. They are similar to temp files like pycache or .vscode where they differ from programmer to programmer. This PR adds .DS_Store to .gitignore in order to make the coding environment more user-friendly for Macs and less cluttered for non-Mac users who have no use for all of these files.
It is also a safety thing, as shown below with this quote.
"Back in 2015, a .DS_Store file was exploited and used to gain access to an admin portal of the TCL Corporation, a multinational Chinese electronics company. The entire backend and database of the application were exposed to anyone that accessed the .DS_Store file." - Quote taken from [this link](https://buildthis.com/ds_store-files-and-why-you-should-know-about-them …
> Added .DS_Store to .gitignore for ease of access and security concerns

- runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
Prevents an issue with clients being resizable with toolbar-less means in some environments (e.g. double clicking title bar on macos).
Honestly I'm not entirely sure why this is ignored if the window isn't visible, rather than being propagated to the window manager when the window is shown, but I guess Swing isn't that smart (like always).
I originally found the information on [this SO answer](https://stackoverflow.com/a/14884056) and it seemed to resolve the issue. The original author seems similarly unsure about its internal mechanisms.
Closes #14235
> clientui: setResizable after setVisible

- runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsConfig.java
Ctrl + backspace is an overwhelmingly common keybind for clearing the
word before the cursor. Meanwhile, clearing the current line is not as
common a keybind, so having an unset default is more sensible here for
users to decide for themselves what keybind they would prefer.
Closes #14754
> chat commands: Update clear word and clear line defaults

- runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/mining/Rock.java
Add support for ore respawn timers on Mineral veins in [Dondakan's mine](https://oldschool.runescape.wiki/w/Dondakan%27s_mine).
Here is what it looks like:
> Add gold vein respawn timer to mining plugin

- runelite-client/src/main/java/net/runelite/client/party/PartyService.java
- runelite-client/src/main/java/net/runelite/client/plugins/party/PartyPanel.java
Method was named incorrectly, `generatePasspharse` -> `generatePassphrase`.
~~In case any hub plugins are using this method, this adds a deprecated shim method of the original name.~~ It is not used by any hub plugins.
> party: spelling generatePassphrase

- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/KourendDiaryRequirement.java
Probably due to the recent change that the true blood altar now exist, the requirement for the Elite Kourend & Kebos task for crafting blood runes was missing. The sentence got changed so I fix it.
Before:
After
> Fix kourend elite diary requirement for blood runes task

- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/MorytaniaDiaryRequirement.java
Starting Ghosts Ahoy isn't actually required to enter Port Phasmatys or use the furnace. I just completed this task without this requirement:
This matches the lack of a requirement for the thin snail task in the easy diary:
> Fix Morytania diary cannonball task requirements

- runelite-client/src/main/java/net/runelite/client/externalplugins/ExternalPluginManager.java
As a utility to plugin hub developers, this PR prevents built-in external plugins (as provided to ExternalPluginManager#loadBuiltin) from conflicting with their installed hub version, if any of the fully-qualified class names match.
This makes no changes to the behaviour of the ExternalPluginManager when *not* using loadBuiltin.
> plugin manager: don't load builtin externals from hub

- runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargePlugin.java
Fixed issue where charge was not decrementing-
Mining soft-clay in Trahaearn mine will give you 2x soft-clay at the cost of 1 charge from the Bracelet of Clay. The fix now reflects this.
fixes #15221
> Fix: Bracelet of Clay in Trahaearn Mine

- runelite-client/src/main/java/net/runelite/client/party/PartyService.java
- runelite-client/src/main/java/net/runelite/client/plugins/party/PartyStatusOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsService.java
Adds an option to highlight party members and recolor their names in the minimenu. Places higher priority on party members than all other options, since it is the least likely group for a player to be in, and likely used for short time frames while participating in an activity (raiding/pvming).
Colour chosen was to avoid clash with other existing default colours.
> player indicators: highlight party members

- runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsPlugin.java
Current behaviour will fail to pull clan ranks for the minimenu when a player is in a higher-priority recoloring group (friends/party members), despite the player names overlay correctly displaying both. This PR just rearranges the rank image selection to be independent of colour selection.
Current behaviour:
With PR:
> player indicators: show fc/cc ranks on friends in minimenu

- runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPlugin.java
To match recent changes to NPC death detection, this prevents recoloring NPC menu entries on NPCs that are at 0hp but not dead.
> npcindicators: isDying checks for menu entries and highlighting

- runelite-client/src/main/java/net/runelite/client/party/PartyService.java
Fixes a bug with players containing dashes failing to be rendered by both the PartyStatusOverlay and the PartyIndicatorsOverlay, as the name being searched for was not sanitized in the same manner as was stored by the StatusUpdate#characterName field.
> party: getMemberByDisplayName search by jagex name

- runelite-client/src/main/java/net/runelite/client/game/NpcUtil.java
Transition forms of [Hopeless creature](https://oldschool.runescape.wiki/w/Hopeless_creature) from quest A Souls Bane added to blacklist.
fixes https://github.com/runelite/runelite/issues/15250
> game: Add Hopeless creature to isDying blacklist

- runelite-client/src/main/java/net/runelite/client/plugins/party/PartyConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/party/PartyStatusOverlay.java
The following is what this PR would change:
+ Adds an option to display the party info (hp, prayer, stam, spec) with smaller font, stacked, and offset from the player as to avoid being covered by hitsplats/hp bar
+ Changes the color used to identify special attack percent to yellow, as more players associate special attack with energy transfer and having multiple components of the overlay set to green is confusing
+ Changes the overlay layer to under widgets to show hitpoints above hitsplats when using the diamond shape
> Compact party overlay

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
fixes #15203 
Incorrect 'x' coordinate for one of the Vannaka instances, changed to the correct 'x' coordinate
> clues: fix world map location for Vannaka

- runelite-client/src/main/java/net/runelite/client/plugins/bank/BankPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/bank/BankPluginTest.java
Based on #12851 with fixed merge conflicts, unit tests and a small change to allow for `per>100k` syntax. Tested in-game.
Closes https://github.com/runelite/runelite/issues/12771
> bank: add individual item value search

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdSolver.java
- runelite-client/src/test/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdSolverTest.java
While mostly correct, the narrowing which occurred for colder and warmer
temperature changes was previously too lenient and did not filter out
locations which were previously the same distance away. This PR
expands that filtering to remove any same-distance locations from
consideration for these cases and adds minimal test cases (from ingame
tests) to validate their behavior.
> HotColdSolver: Simplify temperature change filtering, improve temperature change narrowing

- runelite-client/src/main/java/net/runelite/client/plugins/worldmap/RunecraftingAltarLocation.java
Now that the Meiyerditch laboratory is displayed on the world map, we can put the True blood altar icon. 
I've taken the center tile of the altar.
> worldmap: add true blood altar location

- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/ArdougneDiaryRequirement.java
Ardougne Elite Diary task at Castle Wars was changed by Jagex at some point. I've updated the string for the requirements to display again.
> achievementdiary: fix castle wars task's requirements

- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/FremennikDiaryRequirement.java
Fremennik Elite Diary task at God Wars Dungeon was changed by Jagex (probably due to Nex). I've updated the string for the requirements to display again.
> achievementdiary: fix fremennik gwd task text

- runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java
Description:
Per 09/02/2022 update: https://secure.runescape.com/m=news/a=97/tombs-of-amascut-balance-changes-revisited?oldschool=1
"We've adjusted Liquid Adrenaline to give it a little more oomph by increasing the duration that a single dose lasts from 30 seconds to 150 seconds."
> GameTimer: Update Liq Adrenaline time 30s >150s

- runelite-client/src/main/java/net/runelite/client/plugins/devtools/LocationOverlay.java
When not in instanced regions, the Location devtool highlights the map region including your player as green:
This does not currently work in instances since the player region id is not transformed to its corresponding map region.
When in an instance, this PR normalizes the region ID for highlighting to use non-instance regions.
> devtools: highlight current region in locations tool inside instances

- runelite-client/src/main/java/net/runelite/client/plugins/barbarianassault/BarbarianAssaultPlugin.java
Thanks @Kamielvf 
https://github.com/runelite/runelite/commit/668d99dfef72c900b1c6c7a5ab121863ddb06252 changed it from checking the old varbit value for being 1 to checking the new varbit value for being 1. As a result, `currentRound` was set to null when the wave started, instead of when the previous wave ended. Due to raciness between the varbit change and the widget load, this resulted in either a null or a properly initialized `currentRound` variable value. So, it was broken some waves and not others, randomly.
Closes #15638
> Fix BA plugin, which was broken in 668d99

- runelite-client/src/main/java/net/runelite/client/plugins/runenergy/RunEnergyPlugin.java
Previous code overestimated time remaining by about 5% in general. The correct formula was probably not known in 2018 when this code was written, but can be found on https://oldschool.runescape.wiki/w/Energy#Using_energy
I've also attempted to improve the handling on other edge cases, although there are fundamental limits to how well this works when both `client.getWeight()` and `client.getEnergy()` are truncated before we have access to them.
> Improve rune nergy remaining formula

- runelite-client/src/main/java/net/runelite/client/game/NpcUtil.java
Close #15683
Stop wall beast/hole in the wall from disappearing when dying NPCs are hidden in Entity Hider
> Fix NPC Util Wall beast transition

- runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
Fixes commands such as "!lvl toa expert" by adding tombs of amascut: expert mode to longBossName.
findHiscoreSkill checks ```if (longBossName(skill.getName()).equalsIgnoreCase(s))``` but HiscoreSkill.java only contains the names with a colon, while ```s = longBossName(search)``` by definition does not contain any colons. This PR makes sure this check doesn't fail.
> chat commands: fix !lvl toa expert

- runelite-client/src/main/java/net/runelite/client/Notifier.java
Per https://github.com/runelite/launcher/pull/111; as long as the user has their shell profile set up for whatever package manager they're using, this should reliably find `terminal-notifier`.
> notifier: get terminal-notifier from login shell on macOS

- runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
OnChatMessage to support Liquid Adrenaline because the varbit alone won't track the reset of the timer.
The varbit tracks if Liquid Adrenaline is active but does not track the length left.
Using both Varbit & Chat message will cover both.
> TimersPlugin Liquid Adrenaline

- runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargePlugin.java
Fix for explorer ring not updating its charge count on login in some cases (those being that it is currently full and the varbit was last at its full state or it is a fresh login). Likely caused by a regression in 668d99dfef72c900b1c6c7a5ab121863ddb06252.
The reason it was broken was that if the varbit is supposed to be 0 it may not fire varbitchanged on login. Before 668d99d any varbit change could trigger the update code so it would update anyways but afterwards only the explorer ring varbit updating would do that.
> Fix for explorer ring not updating its charge count on login in sometimes.

- runelite-client/src/main/java/net/runelite/client/plugins/slayer/Task.java
https://oldschool.runescape.wiki/w/Slayer_task/Ogres
"Ogress" includes "Ogress Shaman" and "Ogress Warrior"
> Slayer: Add alternatives for Ogres task

- runelite-client/src/main/java/net/runelite/client/plugins/xpupdater/XpUpdaterPlugin.java
Wise Old Man will start utilizing the account hash for local player name changes when a player is updated.
For more context https://github.com/wise-old-man/wise-old-man/commit/d9dc11ffb2a3c8d9fd6122fb75ec960414873421
> xp updater: send account hash to wise old man

- runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerBarOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerDoseOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerFlickOverlay.java
Add ability to change the colour of the 'PrayDoseOverlay' and Pray Flick overlay for colorblindness support and aesthetic reasons.
Since the Prayer dose overlay might be a bit tricky to setup for people initially; I've added 3 new preset colour options along with the default. On-top of this the final option 'Custom' will allow users to create a custom set of colours to fade in and out of.
Colour pickers are below the appropriate places where the settings that enable the colours are to make it intuitive about what option changes what overlay. ( Picture below if you don't understand what I mean )
> Prayer overlay | Customisable Indicator Colours

- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
Seems to be the only reference to item value in this file that does not respect the price type option. Closes #15763.
> Show chat message for NPC Kills respects Price Type option

- runelite-api/src/main/java/net/runelite/api/MenuAction.java
- runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsPlugin.java
Resolves #15892
After this is shipped we should eventually let these library owners know, and then remove this deprecation, and leave only the properly spelled ENUM
> Fix misspelled enum 

- runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPluginConfig.java
Draw distance requires compute shaders to be enabled, so:
1. Move compute shader's config item before draw distance
2. Mention the dependency in draw distance's description
> gpu: add draw distance requires compute shaders

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/SkillChallengeClue.java
Fixes #16043
idk if it matters all that much, but this does change these clues' config keys. I suppose they are effectively completely different clues now (since there is no item gathering/creation step anymore) so it should be fine for new clue notes to be created for them.
> SkillChallengeClue: Fix Charlie clues update regression

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollOverlay.java
Fixes https://github.com/runelite/runelite/issues/15994
The ThreeStepCrypticClue [makeOverlayHint](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/ThreeStepCrypticClue.java#L88) function overrides the PreferredSize of the panelComponent. Before making any subsequent hints resetting it to default would avoid retaining this overridden value.
> Added overlay panel width reset for clue scrolls

- runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
The anti-venom timers currently expire too early. Fix based on these lines https://github.com/Joshua-F/cs2-scripts/blob/0286ddf0dfbd37f0abfc16afcad34270c65891d2/scripts/%5Bproc%2Cbuff_bar_get_value%5D.cs2#L64-L71
**Before:**
- Anti-venom: 
https://user-images.githubusercontent.com/96100526/209685333-dabfd164-e312-4660-9a6e-a3a12d332f49.mp4
- Anti-venom+: 
https://user-images.githubusercontent.com/96100526/209685470-8111522d-83e5-4f75-b787-5d093bf8e3f2.mp4
**After:**
- Anti-venom: 
https://user-images.githubusercontent.com/96100526/209685711-cc2fe758-14c7-46b6-9734-f35918eefb59.mp4
- Anti-venom+:
https://user-images.githubusercontent.com/96100526/209685660-e2d49c82-316a-432d-a24d-0c660180e0ca.mp4
> Fix antivenom timers expiring too early

- runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsConfig.java
Just adds a couple extra lines to the description in the "NPCs to Highlight" text label above the textbox to clarify how to add multiple entries. 
it's sorta redundant information since the wiki gives examples for how to do it, but I was really dumb and never clicked on the wiki button for months. Maybe there are other dumb guys like me.
Replaces this:
With this:
> npc indicators: add list format to config description

- runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java
When dying in the Inferno with a Zuk task (and only 1 remaining), your task is cancelled. However, the Slayer plugin still tracks that your task is ongoing.
The plugin rightfully recognizes players *leaving* the Inferno and the Fight Caves, but there is a distinct, less specific message that appears when failing the Inferno: `You no longer have a slayer task.`
This commit generalizes the message check to merge the three possible messages (two original, one new) into a regex.
I have not confirmed whether this message appears when failing the Fight Caves. I also do not know for certain whether this message could appear from anything else, but if so it probably has the same effect.
> slayer: cancel task on inferno fail

- runelite-client/src/main/java/net/runelite/client/plugins/itemstats/potions/PrayerPotion.java
- runelite-client/src/test/java/net/runelite/client/plugins/itemstats/ItemStatEffectTest.java
Previously, PrayerPotion only checked for the nightmare zone imbue version of the Ring of the gods, and did not include the soul wars and pvp arena variants. This commit updates it to use ItemVariationMapping to ensure other variants are included.
> item stats: Fix Ring of the gods (i) detection

- runelite-client/src/main/java/net/runelite/client/plugins/twitch/TwitchPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/twitch/irc/TwitchIRCClient.java
- runelite-client/src/main/java/net/runelite/client/plugins/twitch/irc/TwitchListener.java
Twitch display names can contain characters outsize of `a-zA-Z0-9_ `. For such special names, we fallback to the user's login name to avoid `?`. (note: this PR does not tackle the problem of nonalphanumeric message content)
Before:
After:
> fix(twitch): use login name in place of unrenderable display names

- runelite-client/src/main/java/net/runelite/client/plugins/questlist/QuestListPlugin.java
Close #16176
Currently, the method to check whether the quest list tab is open is testing the incorrect tab index (presumably since the addition of the Character Summary tab). This causes the search input chatbox to close on any varbit or varClientInt update while viewing the quest list, where the expected behavior is the inverse.
> questlist: Update quest list tab index

- runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
This allows timers based on varbits to turn red at the correct time even when refreshed early.
> timers: Reset var timers when duration increases

- runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerPlugin.java
When I maxed Firemaking with a goal of 99, the XP tracker showed me unexpected values in the sidebar related to my goal, rather than progressing to a lvl 99 -> lvl 100 progress bar:
I believe this occurred because I have "Hide maxed skills" enabled in the config, although it's difficult to recreate even with devtools.
This PR removes the skill in question from the side panel and overlays upon reaching 99, respecting the "hide maxed skills" option.
> xptracker: prevent negative values with hide maxed

- runelite-client/src/main/java/net/runelite/client/plugins/config/ProfilePanel.java
assign lastFileChooserDirectory as RuneLite.RUNELITE_DIR on first load, then use the last location as the next time (until new window opened)
> Profile Panel Import Profile default directory

- runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/skills/RunecraftAction.java
Add entry for true blood altar to the SkillCalculator plugin. 
Blood runes crafted at the true blood altar give significantly less xp than ones crafted at the zeah blood altar. Add a nameOverride field to RunecraftAction so users can distinguish between old zeah blood rune xp and true blood altar xp
I can provide a before and after screenshot if that would help reviewing this PR
> Add true blood rune to rc calculator

- runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayManager.java
I just copied the contents of onPluginChanged into onProfileChanged.
This fix only applies when both profiles have the same plugins and therefore no PluginChanged events happen.
How to replicate:
1. create 2 "new profile"s.
2. move, resize, or change snap point of an overlay in one of the profiles.
4. switch between the 2 profile and observe that the infobox does not change position/size.
5. disable any plugin in one of the 2 profiles.
6. observe that the infobox properly moves/resizes when changing profiles.
> Fix overlays not updating their size, position, and location when changing profiles if no plugins changed.

- runelite-client/src/main/java/net/runelite/client/ui/overlay/outline/ModelOutlineRenderer.java
This allows for the RuneliteObject's orientation to be considered when rendering a model's outline.
Previously a RuneliteObject could be passed in as a GraphicsObject, but this would not consider the orientation.
Before:
After:
> Add RuneliteObject as an option for the ModelOutlineRenderer

- runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/KourendLibraryPlugin.java
From the blog today:
> Players inside the Arceuus library will now receive a message in their chatbox letting them know when the books have shifted locations.
Unfortunately I forgot to take a screenshot of the chat message before resetting my client. But, this was tested using the JShell.
> kourendlibrary: reset state on new gamemessage

- runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java
The liquid adrenaline timer should not be removed on actor death as it still remains active.
https://user-images.githubusercontent.com/77599829/229376155-49cd7b55-c239-49bf-8595-d16c7012a454.mp4
> timers: fix liquid adrenaline timer being removed on death

- runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonSpots.java
The original location will aggro circled bloodveld but cannot hit it when it gets stuck. 
Moving it one tile west allows it to hit the stuck Bloodveld
> Cannon plugin: Move Mutated Bloodveld recommended spot

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollOverlay.java
The recent update added an item called the `Eastfloor spade` which is functionally equivalent to a spade for the purposes of clue scrolls. This should count as a valid spade item, and not give an error message in the overlay when doing clue scrolls.
This PR broadens the `HAS_SPADE` check to also include the `EASTFLOOR_SPADE` item. This is done similarly to the the `HAS_LIGHT` check below it.
- https://oldschool.runescape.wiki/w/Eastfloor_spade
> Add `EASTFLOOR_SPADE` as a valid spade item in the clue scroll helper overlay

- runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargePlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/itemcharges/ItemChargePluginTest.java
Fixes #12725 
The issue is that when a ring breaks, the client sends the message for the ring breaking, followed by a message that the ring has been used. Consequently, we need to set the number of charges one higher when we get the break message, so that when the use message arrives and we decrement the number of charges, we end up with the correct amount.
The test for this has been redesigned to send both the break and use messages, simulating actual client behavior, and tests we end up with the correct number at the end.
> Fix ROF off by one error

- runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningRocksOverlay.java
Close #16512
Relevant information regarding the updated min/max respawn timers can be found in the issue above.
> Mining plugin: Update ore-vein respawn timers

- runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/Tree.java
- runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/WoodcuttingTreesOverlay.java
I tested that this draws the axes in a similar fashion to the woodcutting guild trees. I tested various combinations of turning the plugin on/off and confirming that axes still draw.
In the trees enum, the null object IDs are the 4 choppable spots' imposter objects and then the real object IDs are the corresponding choppable objects.
Closes #7404
> woodcutting: Add redwood tree at farming guild

- runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangePlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/grandexchange/GrandExchangePluginTest.java
This pull request adds a new configuration option to the Grand Exchange plugin that allows users to specify whether they want to receive notifications for all transactions, or only for those transactions that have finished. 
Added a new configuration option onlyFinishedTransactions in the Grand Exchange plugin configuration. This option defaults to false, preserving the current behaviour of the plugin by default.
Updated the onChatMessage function to check the onlyFinishedTransactions configuration option. If it's true, notifications will only be sent for chat messages that start with "Grand Exchange: Finished buying" or "Grand Exchange: Finished selling".
Users can now reduce the number of notifications they receive from the Grand Exchange plugin by choosing to only be notified when …
> GrandExchangePlugin: Add Option for Notifications on Finished Transactions Only

- runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/timers/TimersPluginTest.java
In most cases, the var for having a thrall will be set to 0 and then back to 1 when a thrall is created, but that is not always the case.
For example, if you summon a thrall in one ToA room (e.g. the hub room) and then summon another in another room (e.g. one of the paths), the var won't be reset to 0 in between, which will lead to the timer expiring early.
Fixes #16288
> timers: Re-add message-detection for thrall creation timer

- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Fixes the issue of walk here being unswappable for things with multilocs such as the pyramid plunder sarcophagus or the hole in the lumbridge basement.
Copy-paste of code from the regular object swaps to the walk here object swaps.
> fix object walk here swap with multilocs

- runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java
~~Sets loginflag on connection lost, to prevent initial task amount from being set to the remaining task count when disconnecting and immeditately reconnecting, which seems to re-send the vars just like it does on login~~
Sets `amount` to 0 on `CONNECTION_LOST` to prevent the `initialAmount` from being set to 0 in `updateTask` when the var for the current task amount gets set to 0.
Fixes #16469
> Slayer plugin: Prevent initial task amount getting an incorrect value when disconnecting.

- runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/chatcommands/ChatCommandsPluginTest.java
This fixes #15122.
!pb will now format the time as:
- M:SS
- M:SS.mm
- H:MM:SS
- H:MM:SS.mm
> ChatCommands - Add support for hours in !pb

- runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialCounterPlugin.java
> specialCounter: fixed bug where 1 tick specs are tracked with the previous spec weapon

- runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeOfferSlot.java
Previously, the offer slot panel's detail view displayed the item price and spent amounts in separate labels wrapped by a grid layout panel which caused unusual unwanted behavior when some items had a spent amount which wrapped to two lines. (this would be the case when buying or selling items totaling about 10 million gp or more) This commit changes these items to be wrapped by a box layout panel, which is then centered vertically within another box layout panel with vertical glue spacers.
This bug technically affects the face card as well, but is unlikely to ever appear as the numbers there are processed by
`QuantityFormatter.quantityToRSDecimalStack()`, and are thusly shortened significantly from their raw number values. (eg. `123_456_789` becomes `123.5M`)
| Before | After | …
> grand exchange: Fix slot detail panels with wrapped text

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/AnagramClue.java
closes #16331,
kept location text as `southeast` to be more consistent with the other anagram clue location text. Could change to south-east, let me know.
> cluescrolls: update location text for Gallow medium anagram clue

- runelite-client/src/main/java/net/runelite/client/util/OSXUtil.java
Fixes: https://github.com/runelite/runelite/issues/16503
Tested on Ventura 13.4 --
The problem was within `ContainableFrame.java:contractBy`
At the top exists a check `isFullScreen()` which was returning `false` because the `getExtendedState()` call was returning state `0` (NORMAL -- aka not fullscreen) even when we were in full-screen mode on MacOS.
I'm not really sure why this happens. The extended state wasn't being set correctly on Mac devices and I assume its some Apple integration issue with Java Swing. I'm not an expert on this stuff.
Anyways,
What I did to fix it added a full-screen listener to the window which sets the extended state accordingly. Currently, this is only being done when the client is running on MacOS!
**Demonstration:** …
> [MacOS] Closing the side panel doesn't resize the game. #16503

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java
The fairy ring is pretty darn close to this clue, and is generally easier to get to then a gnome glider which the current entry currently states.
> clues: add fairy ring to elite clue step for gutanoth

- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
Add player's fishing level to metadata submitted for Larran's chest and brimstone chest loot events for OSRS Wiki crowdsourcing efforts. Originally mentioned in the Runescape Wikis Discord.
> loottracker: Add fishing level to slayer chest metadata

- cache/src/main/java/net/runelite/cache/IndexType.java
- cache/src/main/java/net/runelite/cache/definitions/InterfaceDefinition.java
- cache/src/main/java/net/runelite/cache/definitions/loaders/ItemLoader.java
- cache/src/main/java/net/runelite/cache/fs/ArchiveFiles.java
- cache/src/main/java/net/runelite/cache/fs/FSFile.java
- cache/src/main/java/net/runelite/cache/util/GZip.java
- cache/src/test/java/net/runelite/cache/ItemManagerTest.java
- checkstyle.xml
- runelite-api/src/main/java/net/runelite/api/IndexedSprite.java
- runelite-client/src/main/java/net/runelite/client/chat/ChatMessageManager.java
- runelite-client/src/main/java/net/runelite/client/plugins/blastmine/BlastMineOreCountOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/fps/FpsDrawListener.java
- runelite-client/src/main/java/net/runelite/client/plugins/fps/FpsOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargePlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/itemidentification/ItemIdentification.java
- runelite-client/src/main/java/net/runelite/client/plugins/itemprices/ItemPricesOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/AbsorptionCounter.java
- runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/skills/PrayerBonus.java
- runelite-client/src/main/java/net/runelite/client/plugins/timestamp/TimestampPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TimeablePanel.java
- runelite-client/src/main/java/net/runelite/client/plugins/worldmap/TeleportLocationData.java
- runelite-client/src/main/java/net/runelite/client/ui/overlay/outline/ModelOutlineRenderer.java
- runelite-client/src/main/java/net/runelite/client/util/LinkBrowser.java
- runelite-client/src/test/java/net/runelite/client/OkHttpTest.java
- runelite-client/src/test/java/net/runelite/client/ui/overlay/components/TextComponentTest.java
Expands the existing CheckStyle rule which detects trailing whitespace to also apply to blank lines.
Could also be split out with something like 
```xml
<module name="RegexpSinglelineJava">
<property name="format" value="^\s+$"/>
<property name="message" value="Empty lines should not contain whitespace"/>
<property name="ignoreComments" value="true"/>
</module>
```
> checkstyle: no trailing whitespace on empty lines

- runelite-api/src/main/java/net/runelite/api/Varbits.java
With [Poll 78](https://oldschool.runescape.wiki/w/Update:Even_More_Poll_78_Changes), the special attack orb is [no longer hidden](https://github.com/Joshua-F/cs2-scripts/commit/07331f5cc86cda8af2e2a42eaee24b4543d37168#diff-5452a23d06fba4601158b625323e5a8f3222e605c48789835aed2b8faafc9347) in PvP. 
However:
* The varbit value [does](https://i.imgur.com/YNUvPzE.png) still update as in the past
* The varbit [is](https://github.com/Joshua-F/cs2-scripts/blob/master/scripts/%5Bproc,magic_spellbook_redraw%5D.cs2#L115) still used elsewhere in cs2
This PR updates the javadocs for the varbit to reflect this information
> docs: update explanation of Varbits.PVP_SPEC_ORB

- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/ArdougneDiaryRequirement.java
Changed the chest steal task text to match the current in-game one. The "Attempt to" part has probably been removed and now it doesn't match the in-game text and thus doesn't show the requirement.
> Fix Ardougne chest steal task requirements.

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/SkillChallengeClue.java
When I noticed my abyssal tentacle did not ✔️ the step, I went ahead and tested it myself and noticed it worked exactly as expected. Also tested the ornament kit variation.
I know there is also a hard clue step that uses Abyssal whips as well, but I'm far away from doing more hard clues, so if I run into that it can be a separate PR.
<details>
<summary>Abyssal tentacle</summary>
</details>
<details>
<summary>Abyssal tentacle (or)</summary>
</details>
> clues: Add Abyssal tentacles to Sherlock master challenge

- runelite-api/src/main/java/net/runelite/api/Varbits.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/AnagramClue.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CipherClue.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/EmoteClue.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/FairyRingClue.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/LocationClueScroll.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/LocationsClueScroll.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/MapClue.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/MusicClue.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/ThreeStepCrypticClue.java
- runelite-client/src/test/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClueTest.java
- runelite-client/src/test/java/net/runelite/client/plugins/cluescrolls/clues/ThreeStepCrypticClueTest.java
Adds support for dynamic locations in the LocationClueScroll and LocationsClueScroll types, by exposing a ClueScrollPlugin instance as a parameter.
Also uses this to determine Viggora's location by varbit 815 and show the appropriate one.
Closes runelite#2142
> clues: dynamic viggora location

- runelite-client/src/main/java/net/runelite/client/plugins/entityhider/EntityHiderConfig.java
Edited 'Hide Pets' name to 'Hide Other Players' Pets' to be more clear that it does not hide your own pet
> Entity Hider: update "hide pets" label for clarity

- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/WesternDiaryRequirement.java
Both RuneLite and the Wiki had it wrong for a while that Tree Gnome Village is required to pickpocket gnomes. There's plenty of them roaming around in the Stronghold that can be pickpocketed just fine without the quest being completed and having only 75 thieving.
> Remove Tree Gnome Village requirement from Hard Western Provinces diary task

- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/ArdougneDiaryRequirement.java
As noted in #16761 - the `attempt to` has been removed from the tasks in this diary, so this one needs to be updated as well.
before:
after:
> achievement diary: update ardy picklock task

- runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatOverlay.java
Adds support for the group storage overlay so you can see stats in the UI
> itemstats: show stat tooltips in group storage view

- runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonSpots.java
Multicombat area which is great for farming Moss keys, already a regular cannon spot for a lot of players
>  cannon: Add Moss Giant spot in the Edgeville Dungeon

- runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonSpots.java
Fixes #14184 
New suggested cannon spot shown in the picture below, as well as two spawn points on cannon double hit spots marked near cannon and the old suggested cannon spot marked for reference.
> Update Lizardman suggested cannon spot

- runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerMinimapOverlay.java
The stroke is set in the renderPolygon method, along with drawing the polygon
> groundmarkers: Fix minimap stroke

- runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
Adds aliases so Calvar'ion kill count can be checked without apostrophes like Vet'ion.
> chat commands: add calvarion aliases

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/AnagramClue.java
Another clue, `TWENTY CURE IRON` uses "Shayzien Graveyard", and I think it's clearer that way than "Graveyard of Heroes".
This also fixes his location to be more accurate (world hopped through 3 world, he is in the northeast room each time).
Fixes #16860
> Clue Scroll: Improve Captain Bruce clue location and clue hint.

- runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaPlugin.java
Bug behavior:
When on a slayer task the "NPC Aggression Timer" should become active if the config "Show on slayer task" is enabled. This has been observed to only work sporadically, unless the user manually disabled and re-enabled the option while on task.
Expected behavior:
When on a slayer task the "NPC Aggression Timer" should consistently become active when "Show on slayer task" is enabled.
Issue found:
NPC aggression timer was receiving NPC spawn events before slayer plugin was, so the target check was failing. Changing the priority in NPC aggression timer fixed the issue.
> Fix NPC aggression timer not enabling properly when on a slayer task

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java
Capitalized the fairy ring code because fairy ring codes are always capitalized, seems to be the only one that wasn't.
Also I didn't even notice it was there because it wasn't capitalized
> clues: Update Necromancer Tower Master clue hint

- runelite-client/src/main/java/net/runelite/client/plugins/inventorytags/InventoryTagsPlugin.java
Before this, the sub-menu to add tags when you shift-click on an item only pulled up colors of tagged inventory items, and not colors of tagged equipped items. Now it will consider both inventory and equipped item tags.
> inventorytags: Add colors of equipped items to Inventory Tag submenu

- runelite-client/src/main/java/net/runelite/client/plugins/combatlevel/CombatLevelPlugin.java
Fixes #16971
This was an oversight I should have caught in my original PR. Sorry.
> Respect "Show precise combat level" config on character summary tab

- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/loottracker/LootTrackerPluginTest.java
Presently, it is possible to have loot from Theatre of Blood not be captured by the loot tracker by looting the lobby chest for one run and looting inside of the theatre for the following run, because `chestLooted` would never be reset. (because all game state changes to LOADING would be within the theatre, which is instanced) This commit changes that behavior to track the previous instanced state and reset `chestLooted` whenever outside of an instanced area like before, but additionally when entering an instance from a non-instanced area.
> loot tracker: Fix chest re-opening detection

- runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java
- runelite-client/src/main/java/net/runelite/client/plugins/screenmarkers/ui/ScreenMarkerPanel.java
- runelite-client/src/main/java/net/runelite/client/ui/components/colorpicker/RuneliteColorPicker.java
`setLocationRelativeTo` should be the correct answer for this problem but the jdk implementation for `Window::setLocationRelativeTo`  neglects to account for toolbar insets.
https://github.com/adoptium/jdk11u/blob/master/src/java.desktop/share/classes/java/awt/Window.java#L3273
https://bugs.openjdk.org/browse/JDK-6297309
Closes #15418 
Closes/supersedes  #15426
Closes/supersedes #7642
> Clamp color picker window position to screen bounds

- runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatChanges.java
The wiki was wrong and now it isn't. Energy mix and combat mix heal 3 instead of 6.
> Update barbarian mix heal amounts

- runelite-client/src/main/java/net/runelite/client/game/ItemManager.java
- runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerBox.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TimeTrackingPanel.java
- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTabPanel.java
- runelite-client/src/main/java/net/runelite/client/util/AsyncBufferedImage.java
- runelite-client/src/test/java/net/runelite/client/plugins/chatcommands/ChatCommandsPluginTest.java
- runelite-client/src/test/java/net/runelite/client/plugins/specialcounter/SpecialCounterPluginTest.java
This is to prevent needing to invoke your callback twice in cases where loading is not guaranteed to finish immediately.
> AsyncBufferedImage now runs onLoaded callback if image is already loaded

- runelite-client/src/main/java/net/runelite/client/plugins/objectindicators/ObjectIndicatorsPlugin.java
Using the same solution as [NpcIndicatorsPlugin.java](https://github.com/runelite/runelite/blob/4700013ffbd089899df9cb675ff53b00d381cae5/runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPlugin.java#L874-L893)
<details>
<summary>Image before</summary>
</details>
<details>
<summary>Image after</summary>
</details>
Fixes #17018
> objectindicators: deduplicate color suggestions

- runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaConfig.java
> npcaggro: fix typo in Notify Expiration description

- runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
Currently the cooldown timer for corruption spells is not removed when disabling the "show arceuus cooldowns" config setting.
> timers: remove corruption cooldown on configchange

- runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialCounterPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialWeapon.java
- runelite-client/src/test/java/net/runelite/client/plugins/specialcounter/SpecialWeaponTest.java
Closes #16516 
Adds support for Accursed Sceptre & Accursed Sceptre (a) in the Special Attack Counter plugin. Tested at all ranges (1-9 tiles).
> specialcounter: add accursed sceptre

- runelite-client/src/main/java/net/runelite/client/plugins/worldmap/TransportationPointLocation.java
Fixes the destinations of the two rowboats located at The Stranglewood.
Also corrected the capitalization of **T**he Stranglewood.
Before:
https://github.com/runelite/runelite/assets/7929021/3dbb5be5-7b54-4bfc-8607-db40af76e8bf
After:
https://github.com/runelite/runelite/assets/7929021/b5858751-f890-4f09-8025-f010ff35e2b6
> worldmap: fix stranglewood rowboats destinations

- runelite-client/src/main/java/net/runelite/client/game/FishingSpot.java
Changed ItemID in Fishing spot enum constant from karambwanji to raw karambwanji. (cooked karambwanji sprite erroneously shows ingame)
> fishingspot: raw karambwanji sprite instead of (cooked) karambwanji

- runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoOverlay.java
Allows the Opponent Info plugin's custom health overlay to be toggled off, so that only the in-game setting 'boss health overlay' is affected.
Use case is I want to have both exact health amounts and percentage displayed on boss health bars (below), but I do not want the custom overlay displayed for non-boss monsters or players.
This is the overlay that is being made toggleable (example of an NPC and a player): 
This overlay is unaffected, can still be toggled on/off independent of the new config:
> Opponent Info plugin: add toggle to only show boss health overlay

- runelite-client/src/main/java/net/runelite/client/plugins/twitch/TwitchPlugin.java
The `oauth:` prefix is [required](https://dev.twitch.tv/docs/irc/authenticate-bot/#sending-the-pass-and-nick-messages) by twitch. Sometimes users don't include it, which leads to support requests (for example these two from the past month):
* https://discord.com/channels/301497432909414422/442492468307427330/1164687514859216896
* https://discord.com/channels/301497432909414422/334801290645209099/1160017867929047110
> twitch: prepend oauth prefix to token if missing

- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/FaladorDiaryRequirement.java
- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/FremennikDiaryRequirement.java
- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/KaramjaDiaryRequirement.java
- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/LumbridgeDiaryRequirement.java
- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/VarrockDiaryRequirement.java
Jagex updated these steps to explicitly mention that they cannot be completed with Extracts
Also the typo wording for Astral Runes is currently correct
> achievement diary: fix runecrafting steps

- runelite-client/src/main/java/net/runelite/client/plugins/reportbutton/ReportButtonPlugin.java
You still 6-hour log even if you lose connection and re-connect without going to the login screen.
> report button: Don't reset login time on connection lost

- runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/screenshot/ScreenshotPluginTest.java
#17152
When level-up dialogs are disabled, we check chat messages to capture screenshots for level ups. However, the chat message displayed for level 99 level ups is slightly different than non-99s, meaning we weren't taking screenshots for 99 level ups.
This PR adds a pattern to capture the 99 message, and checks for it after checking for the non-99 pattern.
> Fix screenshots for level 99 messages with level-up dialogs disabled

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/item/MultipleOfItemRequirement.java
- runelite-client/src/test/java/net/runelite/client/plugins/cluescrolls/clues/SkillChallengeClueTest.java
Removes quantity check for MultipleOfItemRequirement
Fixes #17186
<details>
<summary>
Before:
</summary>
</details>
<details>
<summary>
After: (i do not have an ensouled abyssal head)
</summary>
</details>
Note: As far as I can tell this doesn't affect other things
> cluescroll: remove quantity check

- runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerReorder.java
When prayer reordering is enabled and the prayer plugin gets disabled, the ``drag`` and ``drag on`` flag are not removed on plugin shutdown. Thus, the prayers remain draggable.
Before:
https://github.com/runelite/runelite/assets/7929021/7af73acb-74a5-4187-bc80-af0d370dbf2c
After:
https://github.com/runelite/runelite/assets/7929021/7efc3527-ec39-4178-8399-417c1469d146
Alternatively add something like this and invokeLater it on shutDown on the clientThread:
```
if (isInterfaceOpen(InterfaceID.PRAYER))
{
var prayerbook = client.getVarbitValue(Varbits.PRAYERBOOK);
var prayerBookEnum = getPrayerBookEnum(prayerbook);
var prayerIds = defaultPrayerOrder(prayerBookEnum);
for (int prayerId : prayerIds)
{
var prayerObjId = prayerBookEnum.getIntValue(prayerId);
var prayerObj = …
```
> prayer: fix dragging prayers when plugin is disabled

- runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java
This bug was added in 035d056 by removing a bank widget visible check.
This fix not only prevents the unwanted closes (such as of my transmog plugin which had its input closed regardless of whether the bank was open or not), but also improves the bank tags plugin's behavior, since it no longer closes the chatbox input when doing things like clicking the compass while in the bank.
I also documented the purpose of this piece of code, based off of a conversation with @raiyni in discord.
> Fix Bank tags plugin closing chatbox interfaces on most menu option clicks.

- runelite-api/src/main/java/net/runelite/api/AnimationID.java
- runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
Depending on what you use as an ingredient will change the time it takes to churn, and subsequently a separate animation ID
```
2793 milk->cream
2793 butter->cheese
2793 cream->butter
2794 milk->butter
2794 cream->cheese
2795 milk->cheese
```
With manual counting you receive your item from `2793` after 4 seconds, `2794` takes 8 seconds, and `2795` takes 12 seconds, so they've been named accordingly to what polar pulled during [discord discussion](https://discord.com/channels/301497432909414422/419891709883973642/1190148661506736152)
I split the commits up if we want to split them, otherwise I gave the PR a reasonable commit name
Fixes #17310 
<details>
<summary>milking</summary>
</details>
<details>
<summary>2793(short) milk->cream</summary>
</details>
<details>
<summary>2794(medium) …
> idle notifier: add cow milking & diary churning animation ids

- runelite-client/src/main/java/net/runelite/client/plugins/party/PartyPingOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/party/data/PartyTilePingData.java
Currently, the ping duration is tied to the current fps. This commit solves this by instead decreasing the ping alpha by checking the elapsed time of when the ping was first created, and the current time.
(Clips are taken at 165fps)
Before:
https://github.com/runelite/runelite/assets/83369117/fe64a31b-5516-4c4f-8b25-3a8f9ffff7fa
After:
https://github.com/runelite/runelite/assets/83369117/67aa6aa3-d64a-408b-9a02-cf2856b41f8f
> party: tie ping duration to system time

- runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java
This is most commonly encountered when players are assigned a Tzhaar task, but elect to upgrade it to a Jad or Zuk task. When this happens, the SLAYER_TASK_SIZE and SLAYER_TASK_CREATURE varps are set when starting the assignment dialog, and are later changed after opting in to the task change. The plugin had code which would preserve the previous initial amount (as of 1dbf432377f4b0355117b25ecde66915456b0ff8) but should no longer be needed as we can update it directly from var changes as opposed to tracking it ourselves.
Fixes #16470
> slayer: Fix initial amount when task changes

- runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaPlugin.java
In Falador, there's a duck named "Drake". If you have the Drake enemy in your patterns list, it'll trigger whenever you are near the Falador park. I assume this will also help fix other false positive matches due to accidental name collisions with non-attackable NPCs.
> Ignore unattackable NPCs

- runelite-api/src/main/java/net/runelite/api/AnimationID.java
- runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
Like all of these obscure activities, they have intricate animations, which these ones sometimes factor in the `-1` idle animation.
Because of this using `1000ms` will sometimes trigger while you are still cleaning, bumping this to `2000ms` resolves that problem. I do believe this sometimes happens with mining related notifs, which the user is often told to increase their delay, so I assume it's fine that these require said longer delay.
Unlike something like the dairy* churns, these animations seem to be not based on time, but something else (maybe what reward you get). e.g. I've seen these animations be both short and long, both of them have had the `-1` anim happen inbetween them, so I just gave them `_1` and `_2` names respectively
I just overlayed discord on the bottom-right corner …
> idle notifier: add specimen cleaning animation ids

- runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayManager.java
Per https://github.com/runelite/runelite/discussions/17346
WidgetOverlays need to be revalidated so the moved widget can be moved back to its original position.
> overlay manager: revalidate overlays on profile change

- runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerReorder.java
Doesn't update the quick prayers interface if it's open when you change profiles. But people probably won't run into that.
> Prayer: reorder prayers on profile change.

- runelite-client/src/main/java/net/runelite/client/plugins/worldmap/FairyRingLocation.java
The commits in this PR:
- Fix the DIP fairy ring location (it was slightly off)
- Add ~two~ a missing fairy ring~s~ (~the recently added Hosidius Vinery fairy ring and~ the Abyssal Area fairy ring)
- Update the enum to make it easier to keep it in sync with the fairy ring plugin (by alphabetizing the list, un-special-casing Zanaris, and adding comments for missing fairy rings)
> World Map: Update fairy rings enum

- runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
On Linux, FlatLaf will support both yielding window layout to the window manager (for maximizing, edge snapping, etc.) as well as displaying a decorated frame or dialog window only if the following are set:
```
JFrame.setDefaultLookAndFeelDecorated(true);
JDialog.setDefaultLookAndFeelDecorated(true);
```
While these properties are usually already covered by our setting the client frame to be undecorated and the root panel to be decorated as a frame, [FlatLaf explicitly checks these properties][1], so they must be set to take effect in Linux. For reference, [FlatLaf's demo program also sets these properties][2] and also creates a window which can be layouted by the window manager.
[1]: https://github.com/JFormDesigner/FlatLaf/blob/3.2.5/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/Flat …
> clientui: Support Linux WM layout

- runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
`ChatCommandsPlugin#toaTeamSize` excluded `TOA_MEMBER_5_HEALTH`
> chat commands: fix off-by-one team size for out-of-order toa pb

- runelite-api/src/main/java/net/runelite/api/AnimationID.java
- runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/wintertodt/WintertodtPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/WoodcuttingPlugin.java
The crystal felling axe (inactive) uses a different animation id than the charged one for some reason, as outlined in: #17218
Please also refer to that issue for a picture of the animation id.
> idle notifier: add crystal felling axe (inactive) animation

- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/FremennikDiaryRequirement.java
- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/KandarinDiaryRequirement.java
- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/WesternDiaryRequirement.java
they re-introduced the typo that I've fixed twice now
also I found 3 other ones that were changed
<details>
<summary>images</summary>
</details>
> achievement diary: update various tasks

- runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
Previously the branch was unreachable: the label contained uppercase symbols while the selector is lowercase-only (boss.toLowerCase())
> chat commands: fix theatre of blood: entry mode

- runelite-client/src/main/java/net/runelite/client/plugins/worldmap/MiningSiteLocation.java
Adds amethyst rock count to the world map icon for the west (Falador Elite diary) mining guild location.
Closes #17407.
> World Map: Add west mining guild amethyst site info

- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/KourendDiaryRequirement.java
Repairing the fishing cranes in Port Piscarilius requires 30 Construction in addition to 30 Crafting. I think this requirement was added in the course of removing Kourend Favor.
This PR adds the missing requirement to the Achievement Diary requirements plugin.
> achievement diary: add 30 Constr. req. to crane repair task

- runelite-client/src/main/java/net/runelite/client/Notifier.java
- runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java
- Volume control for runelite custom notification sound. 
using javax.sound.sampled.FloatControl (only controls custom notification sound, not native)
- Added config to RuneliteConfig.java
user can control notification volume in Runelite client configuration
Changes to the config marked with red sqare:
> Volume control for RuneLite custom notification sound (Notify.java)

- runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/WoodcuttingSession.java
A division by zero occurs in the calculation of the number of logs/bark cut per hour in the Woodcutting plugin if 0 < `elapsed` < 1ms for `elapsed` the time since the creation of the `WoodcuttingSession`, because `elapsed` is not zero, thus the condition is true, but the calculation uses the value converted to milliseconds, which is zero on the first action (a few thousand nanoseconds).
This results in the following visible bug:
This PR fixes this by only updating `logsPerHr`,`barkPerHr`,  if at least one millisecond has passed since the creation of the `WoodcuttingSession`, i.e. on the second action, since the session is created after the first log/bark.
> woodcutting: prevent division by zero, wait until 3 logs cut for hourly rate

- runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotConfig.java
Adds the required ingame settings to the config descriptions of the screenshot plugin to reduce support traffic.
Because I was editting the config anyway, I uniformized the periods in the config descriptions since some descriptions had periods and others did not. This commit can be changed or dropped if desired.
> screenshot: add required rs settings to descriptions

- runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
Before the window is made visible, window state change events aren't guaranteed to be fired. This causes RuneLite's custom window chrome borders to not be removed when restoring a maximized window on client startup. It's fixed by manually reapplying borders when restoring the maximized window state for the "Remember client position" setting.
The state change event not being guaranteed when the window isn't visible is mentioned here: https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/java/awt/Frame.html#setExtendedState(int)
~~I couldn't find any open issues about this.~~
Closes #17499
> clientui: apply custom borders when maximizing

- runelite-api/src/main/java/net/runelite/api/dbtable/DBTableID.java
The World Map Plugin currently throws the following error when you go over a Quest icon on the world map:
```
2024-02-29 11:29:01 GMT [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
vt: 
at hn.aw(hn.java:60380)
at uq.bx(uq.java:222)
at uq.cc(uq.java:411)
at uz.aq(uz.java:31)
at uz.<init>(uz.java:22)
at lv.om(lv.java:12983)
at uz.oq(uz.java)
at client.getDBRowsByValue(client.java:1355)
at net.runelite.client.plugins.worldmap.WorldMapPlugin.onClientTick(WorldMapPlugin.java:270)
at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
at net.runelite.client.callback.Hooks.post(Hooks.java:205)
at client.zp(client.java:62506)
at client.mg(client.java:3531)
at …
```
> world map: Update outdated DBTableID values

- .github/workflows/CI.yml
This PR:
-   Removes Git credentials/SSH keys after checkout as a security precaution by setting `persist-credentials` to false. They are not used after the initial checkout, and this stops them from accidentally leaking through a script
-   Declares the minimum permissions for the workflows to run at the job level, following principle of least privilege; see [related GitHub security post](https://securitylab.github.com/research/github-actions-building-blocks/)
-   Bumps GitHub Actions to their latest major versions. Main change is they are now using Node 20 instead of 16, which was EOL as of April 2022:
- Changelog for `actions/checkout` can be [found here](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
- Releases for `actions/setup-java` can be [found …
> ci: update github actions

- runelite-client/src/main/java/net/runelite/client/plugins/wiki/WikiConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/wiki/WikiPlugin.java
Allows for the ability to use the wiki DPS calculator button while still hiding the wiki lookup button under the minimap.
Should close #17523
> wiki: Add config option to enable/disable the wiki lookup button 

- runelite-client/src/main/java/net/runelite/client/plugins/party/PartyConfig.java
Since we sometimes have multiple people per day ask us how to ping, or tell us that the ping option is broken / does not work for them, this adds a brief explanation to the config descriptions of the party plugin to reduce support traffic.
Because I was editting the config anyway, I uniformized the periods in the config descriptions since some descriptions had periods and others did not. This commit can be changed or dropped if desired.
> party: add ping information to descriptions

- runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
adds a few new shorthands for regular bosses, and then adds a mapping between all the dt2 shorthands + `awakened` to remove the need for parentheses. Was debating adding support for just `awake` but I felt that was too many mappings.
> chatcommands: add dt2 awakened shorthands

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/SkillChallengeClue.java
With the Kourend Favour rework, you now are required to make a shayzien platebody, not a shayzien supply set for a Skill Challenge in an Elite clue.
> clues: fix outdated skill challenge for shayzien armour

- runelite-client/src/main/java/net/runelite/client/plugins/fairyring/FairyRings.java
- runelite-client/src/test/java/net/runelite/client/plugins/fairyring/FairyRingTest.java
- runelite-client/src/test/java/net/runelite/client/plugins/worldmap/FairyRingLocationTest.java
This PR adds tests for alphabetization of fairy rings to the world map and fairy ring plugins, and it adds a test that all fairy rings in the world map plugin are also in the fairy ring plugin. Because some fairy rings don't appear on the world map, it's not possible (unless I'm missing something) to test that the fairy plugin's fairy rings are in the world map plugin.
I left adding the new Varlamore fairy ring out of this PR because there are already two open PRs that do that. 😄
> Add fairy ring tests

- runelite-api/src/main/interfaces/interfaces.toml
- runelite-api/src/main/java/net/runelite/api/InventoryID.java
- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
Perilous Moons unlocks the Moons of Peril which give rewards from the Lunar Chest
Fortis Colosseum doesn't have a fancy name for its reward chest
Hunters' loot is tracked per tier since they have different loot tables
> loot tracker: track lunar chest & fortis colosseum & hunters' loot sacks

- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingWorld.java
Add additional map regions where farming varbits are transmitted. I also tested the hardwood patch regions which are already correct.
> time tracker: add additional farming region for civitas illa fortis

- runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/fishing/FishingPluginTest.java
Adding a space after 'a' prevents chat messages when catching butterflies from passing the check. Butterfly message: "You catch and..."
Fishing message: "You catch a ..."
Fixes https://github.com/runelite/runelite/issues/17597
> fishing: prevent false positive session

- runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoOverlay.java
Closes #17608
Fixes the Opponent Information plugin showing the HP bar of the Moons of Peril bosses
> opponent info: fix hp bar being shown for moons of peril bosses

- runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
Fixes positioning the RuneLite window off-center when game size is set, but "Remember client position" is not.
Before:  
After:  
Sidebar is opened after client launch, so technically in these pictures it's not centered.
> Apply game size setting before setting the frame location

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/AnagramClue.java
They updated the map so now everyone can see the incorrect coordinates
Fixes #17616
> clues: fix NO OWNER anagram location

- runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldTypeFilter.java
Adds an option to filter high risk worlds to the worldhopper plugin.
> worldhopper: Add High Risk option to world filter.

- runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsButton.java
Currently clicking an active button on the developer tools panel removes its fill color, this PR intends on fixing this so that the buttons retain their original color.
> devtools: restore button laf on toggle

- runelite-client/src/main/java/net/runelite/client/plugins/implings/ImplingSpawn.java
Updated the impling spawn with the 5 spawns for the essence impling.
the essence impling with ID: 1639 has a random spawn location.
the essence impling with the ID: 1649 is connected to the 5 spawn points
fixes: https://github.com/runelite/runelite/issues/17600
> Implings plugin: add 5 spawns for the essence impling

- runelite-client/src/main/java/net/runelite/client/plugins/implings/ImplingSpawn.java
I'm fairly certain these are the actual correct spawn spots, moved the code in-between earth and eclectic where it belongs, and re-ordered them to respect the file standard (lowest X first)
Fixes #17600
> implings: add essence impling spawns

- runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargeConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargePlugin.java
It's useful to know when the Amulet of Chemistry breaks when making potions since it improves output, yet only has 5 charges and breaks frequently.
I've tested both states for the config in-game and it's working.
> Item Charges: Add notification for Amulet of Chemistry

- runelite-client/src/main/java/net/runelite/client/game/NpcUtil.java
Bee swarm does not actually die, just relocates and becomes invisible and not attackable. This PR prevents it from being considered dead when it becomes attackable again. This fixes #17617
> Fix menu entry swapper removing attack option on Bee Swarm 

- pom.xml
Fixes i.a. the ChatCommandsPluginTest.testSecondsToTimeString test failure (expected:<0:03[.]60> but was:<0:03[,]60>) for non-en locales by setting the locale for the surefire plugin to en_US.
All credit goes to Adam, Ron, and NFC.
> surefire: set locale to en_US

- runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerConfig.java
Adds zygomites to the config option description for target weaknesses in the slayer plugin.
> slayer: include zygomites in task weakness config tooltip

- runelite-client/src/main/java/net/runelite/client/plugins/regenmeter/RegenMeterPlugin.java
Close #17677 
Updated regeneration meter plugin to align plugin behavior with in-game behavior after today's game update. Now, when equipping Lightbearer, if less than 15 seconds remain until the next spec regen, the special attack regeneration meter will correctly reflect that the time until next spec regen is preserved as opposed to being set to 15s.
> regeneration meter: fix post-update lightbearer equip behavior

- runelite-client/src/main/java/net/runelite/client/plugins/minimap/MinimapPlugin.java
This PR fixes an issue where changes to config settings from resetting would not be reflected in the plugin.
<details>
<summary>Issue demo</summary>
https://github.com/runelite/runelite/assets/50101641/de38aaeb-8392-4239-9db1-a7c997edf85d
</details>
> minimap: restore map dots on config reset

- cache/src/main/java/net/runelite/cache/MapImageDumper.java
- cache/src/main/java/net/runelite/cache/WorldMapManager.java
- cache/src/main/java/net/runelite/cache/definitions/WorldMapCompositeDefinition.java
- cache/src/main/java/net/runelite/cache/definitions/WorldMapElementDefinition.java
- cache/src/main/java/net/runelite/cache/definitions/loaders/WorldMapCompositeLoader.java
Noticed some labels in underground areas were weird. Turns out the map element positions are not always world coordinates.
Before
After
> cache: transform map label position into world space

- runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialCounterPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialWeapon.java
Adds tonalztics to the spec counter plugin, after testing the spec always applies the hitsplat 2t after speccing regardless of distance, which means it will never queue before a mage or range thrall (which will always be at least 2t later and if they're both 2t the npc action is always processed first) so the last hitsplat logic still works, except for melee thralls (which is also true for dorgeshuun crossbow and accursed scepter, which both additionally can be incorrect on mage and range thralls if you bow/cast from max distance)
> Add Tonalztics spec to spec counter plugin

- runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
Adding these standardizes the normal mode raid commands to all have `3letterName`, `raidName`, `finalBossName`, and `raids #` variations
> chat commands: add more toa normal mode aliases

- runelite-client/src/main/java/net/runelite/client/plugins/worldmap/TeleportLocationData.java
Adds the Fortis Colosseum teleport icon to the world map plugin.
The teleport is a classic 5x5. I've marked the teleport locations during testing:
(The tall object that's marked on the image, is the entrance.)
#17586 (unlisted)
Thanks Astraea for helping me out with testing teleport locations!
> worldmap: add fortis colosseum teleport

- runelite-client/src/main/java/net/runelite/client/game/NpcUtil.java
This PR prevents Giant rats from being hidden when respawning.
> game: add isDying override for tutorial island rat

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/SkillChallengeClue.java
Butterfly jars are not required to complete the skill challenge, only if you want to keep the butterfly.
> clues: remove butterfly jar requirement

- runelite-api/src/main/java/net/runelite/api/VarPlayer.java
- runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/WoodcuttingOverlay.java
Fixes monkey woodcutting:
- idle notifier (closes #547)
- woodcutting overlay when chopping trees as a monkey
The following videos were recorded before I split the varp changes into a separate commit, so the group bonus is not included in this PR anymore.
Before:
https://streamable.com/eo2rjo
After:
https://streamable.com/to6dh2
A separate commit is used for the VarPlayer changes so I could also use that commit in https://github.com/runelite/runelite/pull/17219
> Monkey woodcutting fixes

- runelite-client/src/main/java/net/runelite/client/config/Keybind.java
- runelite-client/src/main/java/net/runelite/client/util/HotkeyListener.java
- runelite-client/src/test/java/net/runelite/client/config/KeybindTest.java
to reproduce:
1. set keybind for pinging in Party plugin to "Ctrl" (can be any keybind outside of key remapping plugin, but this one has more noticeable results.)
2. press down both "shift" and "ctrl".
3. release "ctrl"
4. release "shift"
5. you can no longer walk around in-game until you press and release "ctrl" again, only ping.
> Fix Keybind not matching key released events of modifiers when other modifiers are held.

- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
Should hopefully also work for the rare blighted items.
> loot tracker: Add muddy chest

- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Support teleport submenus on hunter cape in the menu entry swapper plugin.
> menu-entry-swapper: support teleport submenus on hunter cape

- runelite-client/src/main/java/net/runelite/client/events/ConfigChanged.java
As the comment already explained, this value is null when a single config is unset/reset
> events: mark ConfigChanged's newValue as nullable

- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/FaladorDiaryRequirement.java
> Changed the Diary task in Motherlode Mine to require just the Helmet, instead of the entire outfit.
Post-fix:
> achievement diary: fix prospector task

- runelite-client/src/main/java/net/runelite/client/plugins/regenmeter/RegenMeterOverlay.java
Close #17679 
As outlined in the issue, previously the "Show Spec. Attack regen" config option also controlled a medium-opacity white overlay on the special attack orb when selected. After discussing in the Discord, we determined the reason for this behavior and the desired solution. The orb was introduced in [this 03/08/2018 update](https://oldschool.runescape.wiki/w/Update:Tournament_Worlds:_Theatre_of_Blood_rewards) but wasn't made clickable until [this 03/07/2019 update](https://oldschool.runescape.wiki/w/Update:QoL_and_W45_Changes) a year later. In the meantime, we can see that there was [no indication](https://www.youtube.com/watch?v=fqucirw76Bk&t=370s) from the orb about whether your special attack was selected, so this overlay was added to RuneLite. Now that there is a built-in …
> regen meter: remove unneeded spec orb highlight

- runelite-api/src/main/java/net/runelite/api/Varbits.java
Update Varbits for the ore counts changed on May 8th, 2024. This fixes the ore overlay for the blast mine plugin.
Before:
After: 
Inventory:
> Blast mine: update changed varbits

- runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodePlugin.java
Removes superfluous config options from the MLM plugin. Their usages were removed in https://github.com/runelite/runelite/commit/9ade104d8ef7b9fdc9246b06ae494230913f67a5
Also fixed the MLM plugin's description: it's Motherlode, not Motherload.
> mlm: remove superfluous config options

- runelite-client/src/main/java/net/runelite/client/plugins/blastmine/BlastMineRockOverlay.java
Update warning distance to match new explosion distance updated on [May 8th, 2024](https://secure.runescape.com/m=news/project-rebalance-skilling--poll-81-mta-changes?oldschool=true).
> blast mine: update warning distance

- runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterPlugin.java
Closes #14313
CoX messages are of type `FRIENDSCHATNOTIFICATION`, adding this to the switch for game chat filtering will allow CoX messages such as party invite and raid seed drops to be filtered correctly
https://github.com/runelite/runelite/assets/107762963/c64b0384-ef35-4a74-9702-0384f46272ea
> Filter "FRIENDSCHATNOTIFICATION" message type to correctly filter CoX messages

- cache/src/main/java/net/runelite/cache/definitions/AbstractWorldMapDataDefinition.java
- cache/src/main/java/net/runelite/cache/definitions/MapSquareDefinition.java
- cache/src/main/java/net/runelite/cache/definitions/WorldMapCompositeDefinition.java
- cache/src/main/java/net/runelite/cache/definitions/ZoneDefinition.java
- cache/src/main/java/net/runelite/cache/definitions/loaders/WorldMapDataLoader.java
Switch the assignment of `source` and `display` produced by the `WorldMapCompositeDefinition` via renaming to match with the way they are used by Jagex to assemble complex maps. 
While working on updating maps for the Wiki we found some issues with recreating complex maps using the data exposed in #17694.
Complex maps may be composed of squares (64x64) and zones (8x8) which are picked out by Jagex to make maps like:
- ['Ancient Caverns'](https://github.com/runelite/runelite/assets/72635603/f24551c2-6cf0-4ca8-aa2b-7991377fedf0)
- ['God Wars Dungeon'](https://github.com/runelite/runelite/assets/72635603/720faa6b-a85f-450d-9290-5df6922680b4)
- ['Neypotzli'](https://github.com/runelite/runelite/assets/72635603/07772660-c313-4936-aba2-6330c51c6d9d)
For many of them the zones/squares are …
> Switch the names of source and display zones/squares to reflect usage

- runelite-client/src/main/java/net/runelite/client/plugins/agility/Courses.java
There are 4 different tiles you can exit the course from, only the furthest-south tile was listed, causing the lap tracker to only work when you landed on that tile.
> agility: fix falador course

- runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerReorder.java
to replicate:
enter prayer reordering mode
make sure a prayer is hidden.
disable prayer plugin
observe that hidden prayer can be dragged.
> Fix bug where hidden prayers were movable when prayer plugin is off.

- runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerType.java
- runelite-client/src/test/java/net/runelite/client/plugins/prayer/PrayerPluginTest.java
In the [Project Rebalance: Combat Changes](https://secure.runescape.com/m=news/project-rebalance-combat-changes?oldschool=1) update, the prayer drain rate was reduced by 1/3 (from 5 to 1.67 points per minute) for Thick Skin, Burst of Strength and Clarity of Thoughts, Sharp Eye and Mystic Will.
> prayer: update drain rate

- runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
This change adds the Lunar Chest loot from the Moons of Peril to the list of boss rewards that are screenshotted automatically if the "Screenshot Rewards" option is checked in the plugin config. This closes #17839.
Tested myself with my first moons kc
> screenshot: add moons of peril chest loot

- runelite-client/src/main/java/net/runelite/client/plugins/worldmap/MiningSiteLocation.java
> worldmap: fix quarry mining spots

- runelite-client/src/main/java/net/runelite/client/plugins/tithefarm/TitheFarmPlantOverlay.java
As of May 23, 2024, fully grown Tithe plants no longer decay ([blog post](https://oldschool.runescape.wiki/w/Update:Minigame_Tweaks,_Skilling_Adjustments_%26_more!#Minigame_Improvements:~:text=Fully%2Dgrown%20plants%20in%20Tithe%20Farm%20will%20no%20longer%20decay.)).
This makes the progress circle unnecessary for the fully grown plants.
I've removed it here. 
I considered leaving the pie 100% filled for the grown plant as a way to indicate it was actionable but it did not seem proper and it automatically disappeared eventually. Would be interested to know if there's some way to have a similar way to display that.
> Remove Tithe Farm grown plant timer display

- runelite-client/src/main/java/net/runelite/client/input/KeyListener.java
- runelite-client/src/main/java/net/runelite/client/input/KeyManager.java
- runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
- runelite-client/src/main/java/net/runelite/client/util/HotkeyListener.java
Adds overridable focusLost to keyListener and implements it in both ClientUI and KeyManager.
Resolves https://github.com/runelite/runelite/issues/16242
> KeyListener: Release held keys when client focus is lost

- runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java
If a string config value is null by default, that value will get passed to 
`private void setConfiguration(ConfigData configData, String groupName, String profile, String key, @NonNull String value)`. 
The annotation will result in the following exception:
```
2024-07-03 11:44:17 PDT [AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.NullPointerException: value is marked non-null but is null
at net.runelite.client.config.ConfigManager.setConfiguration(ConfigManager.java:874)
at net.runelite.client.config.ConfigManager.setConfiguration(ConfigManager.java:917)
at net.runelite.client.config.ConfigManager.setDefaultConfiguration(ConfigManager.java:1147)
at net.runelite.client.plugins.config.ConfigPanel.lambda$rebuild$5(ConfigPanel.java:423)
at …
```
> config: properly handle null defaults

- runelite-client/src/main/java/net/runelite/client/plugins/party/PartyPanel.java
There is a long-standing issue where OSRS capitalizes the first letter of a message, so users join parties with incorrect capitalization.
https://github.com/TheStonedTurtle/party-panel/issues/27
The current solution is all users just agree to always use all lower case party names, but this is very confusing. We should just standardize that in Runelite by converting everything to lower case.
Then when this is merged I can propagate that change to https://github.com/TheStonedTurtle/party-panel/pull/35
> Convert party names to lower case upon text entry

- runelite-api/src/main/java/net/runelite/api/VarPlayer.java
- runelite-client/src/main/java/net/runelite/client/plugins/ammo/AmmoPlugin.java
Track Dizana's quiver ammo and show it in an infobox. 
The quiver ammo is tracked in two varps: 4141 for the amount, and 4142 for the item id, so it is slightly more involved than just reacting to inventory events as the plugin is already doing.
> ammo: dizana's quiver tracking

- runelite-api/src/main/interfaces/interfaces.toml
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Dizana's quiver adds a new ammo slot to the equipment tab, but:
* this slot is not actually part of the equipment inventory container, and
* probably because of that, the widgets are implemented differently as a couple nested static widgets
As a result, the existing equipment tab custom tab functionality does not recognize it as a valid swap target. However, it can be handled as a normal ui swap by just excluding it from the inventory interface id preconditions.
> mes: custom swaps for dizana's quiver ammo slot

- runelite-api/src/main/java/net/runelite/api/ChatMessageType.java
With the release of While Guthix Sleeps a new ChatMessageType has appeared and it's used for some, newer, npcs speech such as:
* Nex
* Surok Magis
> chat-types: add npc_say chattype

- runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonSpots.java
Adding the following cannon spot for warped creatures.
Personal testing has returned 55k slayer xp/hour using this spot.
> cannon: adding cannon spot for warped creatures, tested as 55k slayer xp/hr

- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/KaramjaDiaryRequirement.java
- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/LumbridgeDiaryRequirement.java
- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/MorytaniaDiaryRequirement.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
the lumbridge change used to be a pickpocket task but never had a pickpocket requirement set xd
<details>
<summary>math clue</summary>
</details>
<details>
<summary>jewellery box</summary>
</details>
<details>
<summary>karamja gloves</summary>
</details>
Closes #18037
> diary clue and mes fixes

- runelite-client/src/main/resources/net/runelite/client/plugins/gpu/regions/regions.txt
Adds GPU regions for the following:
- Castle Wars underground/lobbies
- Viyeldi caves
- Baba Yaga's hut
- Vyre mines
- Jiggig
- Smoke Devil Dungeon
- Observatory Dungeon
> gpu: regions: add various underground areas

- runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/FuzzySearchScorer.java
- runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangePlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/grandexchange/GrandExchangePluginTest.java
Replaces the GE plugin's fuzzy search with a new algorithm: a weighted score between the shared prefix length of the query and item names, and the Jaro-Winkler proximity score. The previous algorithm checked for the length of subsequence in the item name relative to the query.
> grandexchange: fuzzy with prefix + jarowinkler

- runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java
This fixes a NPE which occurs on shutdown for the bank tags plugin.
If the `parent` widget in `TabInterface` is null (e.g. bank has not been accessed yet), calling `.deleteAllChildren` results in NPE.
Fixes #17771
> bank tags: fix npe on shutdown

- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
There are three different ItemIDs for the item "Bag full of gems". The wiki page only has percentages from a moderately sized sample of bags from one of the three sources. I asked in the OSRS Wiki Discord server if this was something that could be crowdsourced, as well as if the three bags should have separate drop tables, and it was suggested that this might be functionality worth adding to Loot Tracker.
Here's the wiki page for Bag full of gems: [Link to wiki page.](https://oldschool.runescape.wiki/w/Bag_full_of_gems)
I've added that functionality. The three different bags will now show up in Loot Tracker as "Bag full of gems (Dusuri)", "Bag full of gems (Percy)", and "Bag full of gems (Belona)".
> Added "Bag full of gems" to Loot Tracker.

- runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaPlugin.java
Progresses #17736 which describes that when changing accounts you lose npc aggression data. 
- Updates `NpcAggroAreaPlugin` to use RSProfileConfiguration
~- Fixes an NPE that can occur when endTime is null~ could not get to reproduce again. 
- Removes the erroneous resetConfig() on login now that profiles are account based. 
Tested by:
1. Login to first account and calibrate so you get npc aggression info
2. Logout
3. Login to second account and calibrate so you get npc aggression info
4. Logout
5. Log back into first account and observe npc aggression info
6. Logout
7. Log back into second account and observe npc aggression info
> Fixes NPC aggression timer config loss when switching accounts

- runelite-client/src/main/java/net/runelite/client/plugins/attackstyles/AttackStylesPlugin.java
This PR fixes a bug with the Attack Styles plugin, where the 'Auto Retaliate' widget remains hidden on plugin shutdown if the option to hide it is enabled.
> attack styles: fix auto retaliate race condition

- cache/src/main/java/net/runelite/cache/MapImageDumper.java
- cache/src/main/java/net/runelite/cache/models/JagexColor.java
Use full HSL ground blending to produce map images that closely resemble the in game world map and [the official world map by Jagex](https://www.runescape.com/oldschool/world-map). Also correct the scaling of sprites and tile shapes to match those sources.
Old color blending:
Jagex world map image:
In game world map:
PR color blending:
> MapImageDumper: Use world map color blending

- runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/skills/FiremakingAction.java
Update Skill Calculator Firemaking XP of "Making Pyre Logs" actions to be a flat 5 XP per dose of Sacred Oil consumed, instead of a variable rate based on how many doses are in the vial.
In line with [31 July 2024 Update](https://secure.runescape.com/m=news/a=13/qol-improvements--further-deadman-armageddon-tweaks?oldschool=1)
> Update Skill Calculator - Making Pyre Logs Firemaking Skilling Actions

- runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargePlugin.java
the notify message for amulet of chemistry running out of charges has two letters capitalized where they should not be. 
This commit fixes that, bringing the message in line with how amulet of chemistry is referred to by jagex.
> Fix: amulet of chemistry notify message 

- runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
This PR fixes a bug with the protection timer for God staves. Currently, changing equipped items (e.g. gloves) will remove the protection timer despite/if having an appropriate staff equipped.
> timers: fix sotd timer removal

- runelite-api/src/main/java/net/runelite/api/SpriteID.java
- runelite-api/src/main/java/net/runelite/api/Varbits.java
- runelite-client/src/main/java/net/runelite/client/plugins/timersandbuffs/BuffCounter.java
- runelite-client/src/main/java/net/runelite/client/plugins/timersandbuffs/ElapsedTimer.java
- runelite-client/src/main/java/net/runelite/client/plugins/timersandbuffs/GameCounter.java
- runelite-client/src/main/java/net/runelite/client/plugins/timersandbuffs/GameIndicator.java
- runelite-client/src/main/java/net/runelite/client/plugins/timersandbuffs/GameTimer.java
- runelite-client/src/main/java/net/runelite/client/plugins/timersandbuffs/GameTimerImageType.java
- runelite-client/src/main/java/net/runelite/client/plugins/timersandbuffs/IndicatorIndicator.java
- runelite-client/src/main/java/net/runelite/client/plugins/timersandbuffs/TimerTimer.java
- runelite-client/src/main/java/net/runelite/client/plugins/timersandbuffs/TimersAndBuffsConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/timersandbuffs/TimersAndBuffsPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/timersandbuffs/ElapsedTimerTest.java
- runelite-client/src/test/java/net/runelite/client/plugins/timersandbuffs/TimersAndBuffsPluginTest.java
This PR:
- Renames timers to timers & buffs
- Sectionizes the config
- Adds the curse of the moons buff (#17586 unlisted)
- Adds the colosseum doom buff (#17586 unlisted)
- Makes vengeance into a buff counter (added later at the request of NFC)
- Adds a timer for the moonlight potion (added later since varbit wasn't initially available/known). Please refer to https://github.com/runelite/runelite/pull/17662#issuecomment-2067964626 for info about this commit
I've also included footage of ingame tests below. If you'd like me to split up the sectionizing into a separate PR, change/drop a commit, or perform other ingame tests etc., please let me know.
<details>
<summary>Colosseum Doom tests</summary>
- Infobox persists between waves and gets removed when the player dies: …
> timers: sectionize and add varlamore buffs

- runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java
This PR fixes a bug with the slayer plugin where checking the current task from the inventory using an eternal slayer ring will not add the slayer task infobox, whereas doing the same action using a regular slayer ring or slayer helmet will. Conversely, using the "Check" option (on the eternal slayer ring) from the worn equipment interface will add the slayer task infobox as expected.
The issue behind the discrepancy is that the "Check" option is a different menuAction (`CC_OP_LOW_PRIORITY`) in the inventory, thus failing the first check. This change addresses that by including the menuAction in the conditional statement.
> slayer: fix checking slayer task from inventory with eternal slayer ring

- runelite-client/src/main/java/net/runelite/client/plugins/tithefarm/TitheFarmPlantOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/tithefarm/TitheFarmPluginConfig.java
The pie timer on fully grown plants was removed in #17931 so this config option doesn't do anything anymore.
> tithe farm: remove unused config

- runelite-api/src/main/java/net/runelite/api/AnimationID.java
- runelite-client/src/main/java/net/runelite/client/plugins/animsmoothing/AnimationSmoothingPlugin.java
Addresses what animations from #16371 I was personally able to verify were still problematic with animation smoothing enabled:
- Harmony Island and Gwenith windmills
- Lithkren generator 
- All 3 Arceuus spellbook Demonbane spells.
> animsmoothing: add Demonbane spells, windmills to blocklist

- runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/dialogue/CrowdsourcingDialogue.java
Checks for a null pointer for logged in player's name
otherwise preserves the current behavior of sanitize() 
fixes #18111
> crowdsourcing: check for null ptr for username

- runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsPlugin.java
Currently with this plugin you cannot get notified when your stats fully drain, only when the drain to level + 1. Setting the threshold to 0 disables the feature. This new param will allow the boost threshold to be set to 0 without it disabling the feature, meaning you can get notified when a stat returns to its base level.
> [Boosts Information plugin] Allow alerting on fully drained stats

- runelite-client/src/main/resources/net/runelite/client/plugins/gpu/regions/regions.txt
Adds the following to the region for the Chasm of Tears:
- Lumbridge castle basement
- Watermill basement
- Dorgeshuun Mines
- Lumbridge swamp caves
Fixes #18265
> gpu: regions: add Lumbridge underground areas to Chasm of Tears region

- runelite-client/src/main/java/net/runelite/client/plugins/worldmap/HunterAreaLocation.java
https://github.com/runelite/runelite/issues/18269
remove HunterCreature.GREATER_SIREN from the Falconry HunterAreaLocation
> fix incorrect hunter area label

- runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/screenshot/ScreenshotPluginTest.java
Updating logic to replace commas from screenshot plugin integer parses, inline with #18258 and 246283549444d1067e9c4785c6534d71407e7e2c
> screenshot: remove commas from integer parses

- runelite-api/src/main/interfaces/interfaces.toml
- runelite-client/src/main/java/net/runelite/client/plugins/wiki/WikiPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/wiki/WikiSearchChatboxTextInput.java
Adds a  menu option to combat achievements that opens the corresponding wiki page.
> wiki: Add wiki menu option for combat achievement tasks

- runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldSwitcherPanel.java
- runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldTableRow.java
Use a sticky table header for the World Switcher.
Before:
[before.webm](https://user-images.githubusercontent.com/2388657/219901216-3193e955-45ce-475e-baa6-859ed1650c72.webm)
After:
[after.webm](https://user-images.githubusercontent.com/2388657/219901226-0bfd6c68-9afc-4c22-88c1-545c95733ced.webm)
(It's been a while since I've done Swing. Let me know if there is a better way to do this to possibly get rid of the `setPreferredSize` and `revalidate`!)
> world switcher: use a sticky table header

- runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java
Currently when viewing all available tags (by right clicking the + in the upper left corner and pressing `view all tags`) searching the bank breaks, this is due to it only closing the tag if there's an "active" tag. The view all tag tabs is a special type of tag and needs to be checked separately.
> Fix searching in view all tag tabs

- runelite-client/src/main/java/net/runelite/client/chat/ChatMessageManager.java
- runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/DiaryRequirementsPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/dialogue/CrowdsourcingDialogue.java
- runelite-client/src/main/java/net/runelite/client/plugins/fairyring/FairyRingPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangePlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/raids/solver/Layout.java
- runelite-client/src/main/java/net/runelite/client/plugins/runenergy/RunEnergyPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
- runelite-client/src/main/java/net/runelite/client/util/Text.java
- runelite-client/src/test/java/net/runelite/client/plugins/chatcommands/ChatCommandsPluginTest.java
Fixes the issue a user reported, their log shows that the value coming in was "1,841". 
[client (4).log](https://github.com/user-attachments/files/17106892/client.4.log)
This also removes the uses of replaceAll with replace for instances that regex is not used.
> chatcommands: fix gotr above 1000 & clean up the use of replaceAll

- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Close [#18322](https://github.com/runelite/runelite/issues/18322)
Make "Pay" and "Pay (*" prioritise over "Trade" in the default menu entry swapper plugin (if/when both options are enabled). 
With the new Varlamore update, patch farmers now have both a "Trade" option and a "Pay" option. The menu entry swapper plugin currently prioritises "Trade" over "Pay", when for farmers this should likely be reversed (similar to Slayer masters prioritising "Assignment" over "Trade"). 
One side effect is that this also makes "Pay" the default option for Petrified Pete at the Volcanic Mine - but if users wish to change this, they can use the shift+right-click feature of the plugin to set a specific override for that NPC. The farmers are by far more common, and would require much more effort by users to …
> menu entry swapper: reprioritise swaps so that farmers have their 'pay' options above 'trade'

- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
Adding two chests to loot tracker:
- <https://oldschool.runescape.wiki/w/Chest_(Aldarin_Villas)> uses `OTHER_CHEST_LOOTED_MESSAGE`
- <https://oldschool.runescape.wiki/w/Chest_(Moon_key)> uses `CHEST_LOOTED_MESSAGE`
> loot tracker: add moon chest and aldarin villas chest

- runelite-client/src/main/java/net/runelite/client/plugins/fairyring/FairyRings.java
- runelite-client/src/main/java/net/runelite/client/plugins/worldmap/FairyRingLocation.java
This PR adds the new fairy ring location (CKQ) to the fairy ring plugin and the worldmap.
> fairyring: add CKQ

- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPanel.java
- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
The price type displays are only updating when rebuilt through other means such as viewing loot details.
> loot tracker: fix price type config changes not immediately reflecting

- runelite-client/src/main/java/net/runelite/client/plugins/timersandbuffs/GameTimer.java
var timers do not require time and unit values - they get those from the varbit value.
Only pure GameTimers might require time and unit values in the GameTimer enum (assuming they're static timers like shadow veil, but not e.g. death charge).
Goading potion on master: https://youtu.be/cUcYLRMiqMU
Goading potion using this PR: https://www.youtube.com/watch?v=wmYAD7kIB3I
DFS using this PR: https://youtu.be/A2QbIoV3rKg
Mark of darkness cooldown using this PR: https://www.youtube.com/watch?v=JBu0zBkdVLg
For purging staff fixes, please refer to my WGS PR.
Additionally also changed removeOnDeath to false for all var timers.
> timers buffs: remove superfluous time and unit values

- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
World metadata is necessary for the crowdsourcing to distinguish F2P and P2P worlds for finding unknown rare loot drop rates.
> loottracker: Muddy Chest world metadata

- runelite-api/src/main/java/net/runelite/api/AnimationID.java
- runelite-client/src/main/java/net/runelite/client/game/LootManager.java
adds huey loot tracking via the death animation
special mentions:
* the boss changes id and plays the death animation at the same time, so either detection method could have worked
* the boss never actually despawns at all
* loot location doesn't seem to be tied to player location, either current or previous tick, so we just check a large area
* mvp gets bones! but that has no bearing on the code
> loot tracker: hueycoatl

- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingWorld.java
This PR adds the Aldarin hops farming patch to the time tracking plugin.
Closes #18344
> timetracking: add aldarin farming patch

- runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/thieving/CrowdsourcingThieving.java
Fixes thieving crowdsourcing currently checking the equipment container for the inventory version of max cape. Currently we have to filter out a decent amount of pickpocket data.
> crowdsourcing: track *worn* max cape instead of inventory one

- runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItem.java
- runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java
- runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/grounditems/config/OwnershipFilterMode.java
- runelite-client/src/test/java/net/runelite/client/plugins/grounditems/GroundItemsPluginTest.java
There are three desired use cases for the ownership filtering logic.
1) Show all items
2) Show only my drops (including group iron teammates)
3) Show my drops (including group iron teammates) and world item spawns.
Before this change only use cases 1 & 2 were supported (due to [pushback](https://github.com/runelite/runelite/issues/17843#issue-2296058488) from certain vocal individuals).
This change replaces the old "Only show own items" checkbox with a dropdown that allows for all three use cases.
Note: Users that previously had the "Only show own items" checkbox enabled will **automatically** have the setting migrated to the dropdown.
> Replace "Only show own items" config with new "Ownership Filter" dropdown

- runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeConfig.java
the uses for these was removed in 3bae3072596a18a2c129a4636e0c0cb3653dce39
> motherlode: remove dead config options

- runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
Addressing the issue of the minimized RuneLite window not restoring despite the notification setting set to "force".
Checked if isVisible flipping is necessary, but the behavior is as expected without any additional changes, and only putting `setState()` in `forceFocus()` as suggested to fix #18381
> Adding setState to force focus on MacOS when RuneLite is minimized

- runelite-client/src/main/java/net/runelite/client/plugins/slayer/Task.java
This PR adds Frost Naguas and Amoxliatl as alternatives to Lesser Nagua tasks, and adds the Araxxor boss task.
> slayer: add araxxor task and lesser nagua alternatives

- runelite-client/src/main/java/net/runelite/client/plugins/attackstyles/AttackStylesPlugin.java
Fixes #18124 
[The cache](https://abextm.github.io/cache2/#/viewer/enum/3930) shows 3rd option as Other for bladed spears, but seems the value read is `null` instead. When set to Other instead of null there is a problem with duplicated overlapping widgets (as mentioned in the issue).
> attack styles: fix blue moon spear

- runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatChanges.java
- runelite-client/src/main/java/net/runelite/client/plugins/itemstats/food/CookedBream.java
- runelite-client/src/main/java/net/runelite/client/plugins/itemstats/food/CookedMossLizard.java
- runelite-client/src/main/java/net/runelite/client/plugins/itemstats/potions/MoonlightPotion.java
- runelite-client/src/main/java/net/runelite/client/plugins/itemstats/special/SunlightMoth.java
- runelite-client/src/test/java/net/runelite/client/plugins/itemstats/ItemStatEffectTest.java
This PR adds new consumables, from the Varlamore update, to the item stats plugin.
#17586 
Consumables added:
- Cooked Bream
- Cooked Moss Lizard
- Eclipse wine
- Moon-lite
- Moonlight Moth / Mix
- Moonlight Potion
- Sunbeam ale
- Sunlight Moth / Mix
- Sun-shine
- Trapper's Tipple
I tried my best to check the effects, though since some depend on players' certain skill level it's hard to test it thoroughly. Data was also used from the OSRS Wiki for the consumables' effect calculations.
~~Update:
The formula for moonlight potion is not accurate for defence skill; converting to draft.~~
> item stats: add varlamore consumables

- runelite-client/src/main/java/net/runelite/client/plugins/worldmap/TeleportLocationData.java
Adds the spider cave teleport to the worldmap. Based on 50-60 teleports (thanks beta worlds!), it's a 3x3 this time.
> worldmap: add spider cave teleport

- runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatChanges.java
Adds boosts for Metztonalli White, Blackbird Red, and Steamforge Brew
> Add boosts for a few Aldarin drinks not in ItemStats

- runelite-client/src/main/resources/net/runelite/client/plugins/gpu/regions/regions.txt
Adds GPU regions for the following areas:
- Ah Za Rhoon (Shilo Village):
- Tomb of Bervirius (Shilo Village)
- Tunnel of Chaos (What Lies Below)
Ah Za Rhoon (Shilo Village):
Tomb of Bervirius (Shilo Village):
Tunnel of Chaos (What Lies Below):
> gpu: regions: add regions for areas from Shilo Village and What Lies Below

- runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldTypeFilter.java
Adds a Bounty Hunter filter option and removes Bounty Hunter worlds from the "normal" world type filter.
Resolves #17960
> worldhopper: add Bounty Hunter option to world type filter

- runelite-api/src/main/java/net/runelite/api/AnimationID.java
- runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
Adds animations for the following to idlenotifier:
- Crushing blessed bones
- Making sunfire wines
- Sacrificing bone shards to the libation bowl
- Searching wealthy citizens' houses for valuables (Varlamore thieving)
> idlenotifier: add Varlamore-related animations

- runelite-client/src/main/java/net/runelite/client/plugins/camera/CameraPlugin.java
- Adds a check for the 'right click moves camera' option when calling setCameraMouseButtonMask. 
Fixes #18484 
Example of new behaviour: https://www.youtube.com/watch?v=lPNe3eYb_qk
> camera: Fix right click moving the camera even with 'right click moves camera' option disabled

- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
It's known that hunters' loot sacks' drops scale depending on woodcutting and herblore levels, so I've added those as metadata for wiki crowdsourcing/drop rates purposes. I threw in hunter level too for good measure, since the wording on the wiki is a bit ambiguous as to whether it *only* depends on wc and herb levels. It could be the case that hunter level affects the meats you receive.
See: https://oldschool.runescape.wiki/w/Hunters%27_loot_sack_(expert)
> loot tracker: record skill levels metadata for hunters' loot sacks

- runelite-client/src/main/resources/net/runelite/client/plugins/gpu/regions/regions.txt
Reported by felanbird.
**Before:**
**After:**
Getting there (probably not needed for this one but including for reference:
*Bring an antidote++, super antifire, and anti-dragon shield or dragonfire shield and use Protect From Magic*
- Burning Amulet to Lava Maze
- Open the gate to the north and climb down the ladder
- Pull the lever
From there, run right all the way to the corner. That's where the before and after screenshots were taken.
> gpu: regions: add KBD lair

- runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java
Closes #12717
Revived from #13065, which was closed as the author deleted their fork.
Clicking an infobox will toggle its collapsed state. See attached video for behavior.
https://github.com/runelite/runelite/assets/2199511/b9cd6660-8616-4ef2-9395-4291b7ea3b5b
> xp tracker: Toggle compact view on click

- runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/chatcommands/ChatCommandsPluginTest.java
- runelite-client/src/test/java/net/runelite/client/plugins/screenshot/ScreenshotPluginTest.java
```
2024-11-29 05:06:24 CET [Client] DEBUG injected-client - Chat message type GAMEMESSAGE: Corrupted challenge duration: <col=ff0000>2:14.40</col>. Personal best: 1:57.00.
2024-11-29 05:06:24 CET [Client] DEBUG injected-client - Chat message type GAMEMESSAGE: Preparation time: <col=ff0000>0:03.60</col>. Hunllef kill time: <col=ff0000>2:10.80</col>.
2024-11-29 05:06:24 CET [Client] DEBUG injected-client - Chat message type GAMEMESSAGE: Your <col=a53fff>Corrupted Hunllef (Echo)</col> kill count is: <col=ff3045>31</col>
2024-11-29 05:06:24 CET [Client] DEBUG n.r.client.config.ConfigManager - Setting configuration value for killcount.rsprofile.uuGybRk_.<col=a53fff>corrupted hunllef (echo)</col> to 31
2024-11-29 05:06:24 CET [Client] DEBUG n.r.c.p.c.ChatCommandsPlugin - Got out-of-order …
```
> kc: remove color tag from boss name

- runelite-client/src/main/java/net/runelite/client/plugins/entityhider/EntityHiderConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/entityhider/EntityHiderPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/entityhider/EntityHiderPluginTest.java
I placed party members above friends, since it is a logically more restrictive group than your entire friends list. It is likely to only contain the people you are actively playing with, and so you might want to hide everyone else, including friends.
PartyService#getMemberByDisplayName performs jagex name sanitization, so it may be desirable to use a cached form of this list if performance is a concern. Let me know and I can add it. I didn't notice any performance impact even at busy places like the GE.
> entityhider: selectively hide party members

- runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java
> timetracking: account for leagues farmtick being 1 minute rather than 5

- runelite-client/src/main/java/net/runelite/client/plugins/runenergy/RunEnergyPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/runenergy/RunEnergyPluginTest.java
8 January 2025 Run Energy Changes
Energy Regeneration was changed from (Agility / 6) + 8 to (Agility / 10) + 15
Energy Drain was changed to include the agility level. (60 + (67 * Weight / 64)) * (1 - Agility/300)
The graceful boost check was looking for the inventory max-cape id rather than the worn max cape which is unrelated to the game update.
> runenergy: Update Run Energy Formulas

- runelite-client/src/main/java/net/runelite/client/Notifier.java
Calling `clip.loop(1)` would cause the clip to be played twice the first time a notification sound should be played. This happens because after a loop finishes, the clips position is set to the last frame. When a new loop with count 1 (meaning repeat once) is started, the clip is instantly reset to the first frame, which counts as the first loop, causing the clip to audibly only be played once.
Setting the frame position to 0 and the loop count to 0 fixes this problem.
In my limited tests using `clip.start()` instead of `clip.loop(0)` worked just as well, but I don't know if the issue described in the comment above the changed lines is still relevant.
Closes #14914
> Fix custom notification sound playing twice the first time after client launch

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java
- runelite-client/src/test/java/net/runelite/client/plugins/cluescrolls/clues/ConfigKeyTest.java
- runelite-client/src/test/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClueTest.java
Addresses first two bullets in #18236:
- Replaces constructors with builder
- Replaces `lightRequired` with a check for the firepit varbit presence
> clues: clean up CoordinateClue

- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/loottracker/LootTrackerPluginTest.java
Adds BA high gambles to the loot tracker.
Partially/mostly implements #11611 
Low and medium gambles aren't included here since there isn't an easy way to distinguish between the two, whereas high gambles have a unique message. As (to my knowledge) the significant majority of BA gambles are from people hunting the pet penance queen and are therefore high gambles, it seemed reasonable to not include low or medium gambles here.
Thanks to @samszotkowski and @coopermor for playing a fair amount of BA to test this.
> loottracker: track Barbarian Assault high gamble rewards

- runelite-api/src/main/java/net/runelite/api/IndexedObjectSet.java
Sorting with the current spliterator is broken due to initial size being 0.
> api: use spliterator with unknown size

- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/loottracker/LootTrackerPluginTest.java
This PR resolves an uncaught case within the loot tracker plugin, when collecting Wintertodt rewards.
A test for Wintertodt loot tracking was also added.
```
2025-02-23 15:40:07 CET [Client] DEBUG injected-client - Chat message type SPAM: <col=ef1020>You found some loot: 17 x Burnt page
2025-02-23 15:40:07 CET [Client] DEBUG n.r.c.p.l.LootTrackerPlugin - Inv change: [ItemStack(id=20718, quantity=17)] Ground items: []
2025-02-23 15:47:15 CET [Client] DEBUG injected-client - Chat message type SPAM: You found some loot: 4,694 x Coins
2025-02-23 15:47:15 CET [Client] DEBUG n.r.c.p.l.LootTrackerPlugin - Inv change: [ItemStack(id=995, quantity=4694)] Ground items: []
```
The reward message for rare loot is identical on both opaque and transparent chats.
<details>
<summary>Spoiler</summary> …
> loot tracker: capture unique wintertodt rewards

- runelite-client/src/main/java/net/runelite/client/plugins/itemstats/potions/AncientBrew.java
- runelite-client/src/test/java/net/runelite/client/plugins/itemstats/ItemStatEffectTest.java
This PR fixes the statChange filter of lowered stats for Ancient Brews to include stats at level 1.
Fixes #18712
> item stats: fix ancient brew obo

- runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaPlugin.java
Currently, once the area lines turn on they always stay active with this combination of settings:
What I would expect with these settings is for the overlay to disappear when I am far away from any NPCs I've named + my current slayer task.
I've changed one line so that this now happens. Now upon teleporting away and stuff like that (game state > LOGGED_IN), it checks if it's supposed to continue showing lines.
It appears that Adam has gone back and forth on this line a handful of times (see commits around Feb 2024) so maybe he will have some thoughts on this.
> NPC aggression timer: clear aggro lines when disengaging from flagged NPCs

- runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
Without checking taskbar support first, [Taskbar.getTaskbar()](https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/java/awt/Taskbar.html#getTaskbar()) will throw `UnsupportedOperationException` on platforms that don't support it (Linux skill issue)
```
2025-03-11 19:55:49 EET [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.UnsupportedOperationException: Taskbar API is not supported on the current platform
at java.desktop/java.awt.Taskbar.getTaskbar(Taskbar.java:217)
at net.runelite.client.ui.ClientUI.flashTaskbar(ClientUI.java:908)
at net.runelite.client.Notifier.notify(Notifier.java:197)
at net.runelite.client.plugins.idlenotifier.IdleNotifierPlugin.onGameTick(IdleNotifierPlugin.java:561)
at …
```
> notifier: check taskbar support before using it

- runelite-api/src/main/java/net/runelite/api/SpriteID.java
- runelite-client/src/main/java/net/runelite/client/plugins/timersandbuffs/GameCounter.java
- runelite-client/src/main/java/net/runelite/client/plugins/timersandbuffs/GameTimer.java
- runelite-client/src/main/java/net/runelite/client/plugins/timersandbuffs/TimersAndBuffsConfig.java
- runelite-client/src/main/java/net/runelite/client/plugins/timersandbuffs/TimersAndBuffsPlugin.java
Adds the WGS timers and buffs:
- Stone of Jas empowerment
- Please DM me for Stone of Jas empowerment testing videos. Alternatively, if it's deemed too niche, the commit can be dropped. I assumed Jagex added it to the EHC buff bar with a reason though.
- Burn damage accumulated and next burn hit
- EHC buff bar video: https://youtu.be/60e66gQ9Z5s
- Test on RL: https://www.youtube.com/watch?v=dI0H-s5mYrE
- Adds smouldering heart & smouldering gland (TD consumables)
- Unlike normally, I was not able to test the these, as they're relatively rare drops from TDs. The varbits are from script 5923, and 25 & 4 are from struct 965 and 966 respectively (param 1541, from script 5923).
-  The wiki notes that teleporting away removes the effect from the smouldering gland -> ``removedOnDeath`` = false …
> timers buffs: add WGS timers and buffs

- runelite-client/src/main/java/net/runelite/client/plugins/itemidentification/ItemIdentification.java
- runelite-client/src/main/java/net/runelite/client/plugins/itemidentification/ItemIdentificationConfig.java
Add jugs of wine (+water) and related config options to the ItemIdentification plugin.
Jugs of wine all look similar, so they're a perfect candidate to be added to the ItemIdentification plugin. Very useful for Cooking training (water -> unfermented -> wine) or Varlamore Prayer training (wine -> sunfire wine -> blessed). 
New Config entry:
Previous/Disabled: 
Medium names: 
Short names:
> item identification: add wines

- runelite-jshell/src/main/resources/net/runelite/jshell/prelude.jsh
The older types that the gameval package replaces are deprecated, so we should promote their replacements in the jshell prelude to align with intended usage.
> jshell: import gameval.*

- runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
re-create of #18878 as it seems they closed their PR and deleted the branch
Changes since that PR:
* use gamevals
* use contains instead of startsWith for chat message since the message has colour codes
> screenshot: add fortis colosseum

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java
The master coordinate clue step "05 degrees 13 minutes north, 04 degrees 16 minutes west" has the player dig right near a multicombat boundary so can spawn either ancient wizards or a Brassican mage, though the overlay only mentions the mage.
Reported by Shush in the wiki Discord server.
> cluescrolls: correct enemy value for 05.13N 04.16W master step

- runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/loottracker/LootTrackerPluginTest.java
This PR fixes a possibility of items being mistakenly registered as loot from the Grubby chest, when checking the loot count ("kc") of the chest.
Instead of using a message shared when both looting and checking the chest (as it is currently), a loot-specific message is used to assume tracking. The message has two variations; one for common loot, and one for unique loot. Though they share a similar beginning, I chose to use a pattern (instead of using a string and checking the start of the message) because the shared string felt too generic and I'm not sure if e.g. opening other types of containers (e.g. clue scroll casket¹/random event casket/other) yield a message with similar beginning. This felt the safest.
¹ I recall there is at least 1 clue scroll step in the dungeon, by the red …
> loot tracker: fix grubby chest false positive loot

- runelite-api/src/main/java/net/runelite/api/VarPlayer.java
- runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/LayoutManager.java
- runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/PotionStorage.java
This PR is intended to make it so that empty vials can also be taken out from potion storage when in a bank tag. As empty vials seem to be unique in how they work in the potion storage, I've added unique methods for handling it.
I've made an assumption that the position for the vials widget in the potion storage children will always be the sum of all potions * 5 + 4, to try and make this more future-proofed. If there's a better way to determine where it'll be placed that'd be better, otherwise the main time this assumption will be challenged is when a new potion gets added to the game.
To allow for vials to be removed without having already opened the potion storage interface, I've added 5 new widgets to prepareWidgets. I've assumed I need to make the non-relevant widgets (line 292-295) …
> bank tags: support vials in potion storage

- runelite-maven-plugin/src/main/java/net/runelite/mvn/ComponentMojo.java
points devs to where the replacement is
> maven plugin: add javadoc for deprecated InterfaceID and ComponentID

- runelite-api/src/main/java/net/runelite/api/HitsplatID.java
While wearing an inoculation bracelet, the hitsplat type for disease damage is 3. (Without an inoculation bracelet, the hitsplat type is still 4)
> api: add DISEASE_BLOCKED to HitsplatID

- runelite-client/src/main/java/net/runelite/client/chat/ChatMessageManager.java
This PR aims to fix message colors being unapplied due to them containing line breaks.
Example
The message `You are now a guest of RuneLite.<br>To talk, start each line of chat with /// or /gc.` is only partially colored up to the line break.
Reapplying the color tag correctly colors the full message:
> chat message manager: fix line break unapplying message color

- runelite-client/src/main/java/net/runelite/client/plugins/keyremapping/KeyRemappingListener.java
Fix the bug in the Key Mappings plugin where if you are in a dialog with options to choose, then we ignore the ctrl mapping when it is mapped to a valid integer speech option
Original Issue: [https://github.com/runelite/runelite/issues/18135](https://github.com/runelite/runelite/issues/18135)
Smoke test passes:
> Fix the bug in the Key Mappings plugin with dialog options

- runelite-client/src/main/java/net/runelite/client/plugins/timersandbuffs/GameTimer.java
- runelite-client/src/main/java/net/runelite/client/plugins/timersandbuffs/TimersAndBuffsPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/timersandbuffs/TimersAndBuffsPluginTest.java
Updated the death charge timer for the changes observed after Yama release.
- Death charge timer will now properly appear whether or not you've used the [Rite of vile transference](https://oldschool.runescape.wiki/w/Rite_of_vile_transference).
- Removed the variable death charge time as it was observed that death charge lasted a full minute on both an account with 99 mage as well as one with 81 mage.
> timers: update death charge for yama changes

- runelite-client/src/main/java/net/runelite/client/game/AgilityShortcut.java
This PR adds the agility shortcut by the [Varrock Palace garden](https://oldschool.runescape.wiki/w/Trellis_(Varrock)), from [this](https://secure.runescape.com/m=news/poll-84-batch-ii?oldschool=1) update, to the agility plugin.
> agility shortcut: add varrock castle garden shortcut

- runelite-client/src/main/java/net/runelite/client/plugins/config/ProfilePanel.java
This PR is intended to fix two issues with profiles where:
1. renaming a profile may mistakenly give an internal status to the profile.
2. excessively long names raise a `FileSystemException` (prilarily Windows)
Currently, the naming policy for profiles, primarily checking for reserved characters from file names, allows for '$'-characters to be included, this is fine if a '$'-character are not the first character in the name. Because profiles whose names begin with '$' are regarded as internal, they will be hidden from the profile list. Disallowing profiles from containing '$'-characters solves this.
An alternative solution would be to strip any leading '$' from the name, but I thought disallowing it altogether is better.
If a user gives a profile a long enough name so that the path is …
> profile panel: improve profile naming policy

- runelite-client/src/main/java/net/runelite/client/plugins/timersandbuffs/GameTimer.java
- runelite-client/src/main/java/net/runelite/client/plugins/timersandbuffs/TimersAndBuffsPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/timersandbuffs/TimersAndBuffsPluginTest.java
- Updated the mark of darkness cooldown timer to 10 game ticks as that was observed to be the current cooldown after the Yama release on both an account with 99 mage as well as one with 81 mage.
- Added tests for mark of darkness and the mark of darkness cooldown.
> timers: update mark of darkness cooldown for yama changes

- runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java
- runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpPanel.java
- runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpSave.java
- runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpSnapshotSingle.java
- runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpState.java
- runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpStateSingle.java
- runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerPlugin.java
Currently the XP tracker allows you to manually reorder skills and to place them in compact view, but neither of these changes are saved to the profile.
This PR fixes this by adding code to synchronise manual reordering to the existing `XpState::order` field, and by adding a new set to `XpSave` that tracks which skills have been made compact.
> xptracker: save drag-and-drop order and compact view toggle to profile

- runelite-client/src/main/java/net/runelite/client/plugins/lowmemory/LowMemoryPlugin.java
avoids deprecated `Client#getScene` and `Client#getPlane`
also fixes:
```
WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: Cannot invoke "net.runelite.api.WorldView.getPlane()" because the return value of "net.runelite.api.Client.getTopLevelWorldView()" is null
at net.runelite.api.Client.getPlane(Client.java:2241)
at net.runelite.client.plugins.lowmemory.LowMemoryPlugin.onBeforeRender(LowMemoryPlugin.java:118)
at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
at net.runelite.client.callback.Hooks.frame(Hooks.java:268)
at client.pm(client.java:29991)
at client.bu(client.java)
at bk.bl(bk.java:472)
at bk.uq(bk.java)
at …
```
> low detail: avoid npe before login

- runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
- runelite-client/src/test/java/net/runelite/client/plugins/screenshot/ScreenshotPluginTest.java
resolves #17831 
Accidentally closed #18051 by force updating my change out of the source branch
Checks if the player enters the animation for a doom death and triggers a screenshot.
Tested with a death via doom manually:
> screenshots: Add doom death screenshots

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java
missed in b2eed70206bc41689d7cdd957be55e1dd9158b2c
picked `VARLAMORE_RAINFOREST_CENTRE` over `VARLAMORE_TLATI_RAINFOREST` because it's called `CLUEHELPER_HOTCOLD_MASTER_VARLAMORE_RAINFOREST_CENTRE` in `DBTableID.java`
> clues: add tlati rainforest hotcold

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
This patch will add highlighting of Laidee Gnonock for the "The doorman of the Warriors' Guild wishes to be impressed by how strong your equipment is." clue step.
After events in the While Guthix Sleeps quest, Laidee Gnonock replaces Ghommal as the Warriors' guild doorman.
> clues: highlight warriors guild doorman after while guthix sleeps

- runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java
Displays the wilderness slayer task streak if the player has a wilderness slayer task.
Spiritual creatures wildy task:
runelite/master
runelite/krystilia-task-streak
Closes #7329
> slayer: display wilderness slayer task streak

- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/ShiftDepositMode.java
Currently, regardless of the in-game "Bank Item Options" setting being on or off, the MES setting "Bank deposit shift-click" is being applied incorrectly in the following cases:
For deposit boxes:
If the deposit box is set to deposit-1, the MES shift-deposit swap is never applied
If the deposit box is set to any other value and MES is set to deposit-all, the menu entry is swapped to deposit-x instead, and when MES is set to deposit-x, the entry is swapped to deposit-all.
For GIM group storage:
If the MES shift-deposit swap is set to deposit-1, the swap is not applied.
This PR resolves the above behavior.
I tested it with "Bank Item Options" both on and off, and checked at the MLM and Barbarian Assault deposit boxes. 
The group storage change was tested by Zoinkwiz as I don't have access …
> mes: correctly apply shift deposit swaps to deposit boxes and GIM storage

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/FaloTheBardClue.java
- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/SkillChallengeClue.java
When receiving these clue steps, the held clue changes text to indicate what the player should do/show them. This PR adds the ability for the clue plugin to proactively update the active clue based on that chatbox text instead of requiring the user to read the clue scroll itself.
Closes #10613
> clues: Identify Charlie the Tramp and Falo the Bard clues from chat messages

- runelite-client/src/main/java/net/runelite/client/plugins/slayer/Task.java
- runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java
This PR adds the Custodian Stalker task (with the “Custodian” target name alias because the 'normal' custodians are prefixed by their age, while the superior variant is suffixed), and add buffalo as a cow task alternative.
[Custodians – OSRS Wiki](https://oldschool.runescape.wiki/w/Custodian_stalker)
[OSRS Update — Varlamore: The Final Dawn Out Now](https://secure.runescape.com/m=news/varlamore-the-final-dawn-out-now?oldschool=1)
> slayer: add custodian stalkers task and cows task alternative

- runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java
The removed HotColdLocation is not obtainable
"North-east of the Arceuus essence mine" is the "real" HotColdLocation for that area
Was confused with the following CoordinateClue
> clues: Remove unobtainable essence mine HotColdLocation
