runelite/runelite

runelite-api/src/main/java/net/runelite/api/Actor.java, runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/Perspective.java, runelite-api/src/main/java/net/runelite/api/TileObject.java, runescape-api/src/main/java/net/runelite/rs/api/Client.java, runescape-client/src/main/java/Client.java
Also, moved getCanvasTilePoly() and getCanvasTextLocation() to Perspective
=> Added worldToMiniMap() and hooked mapOffset

runelite-api/src/main/java/net/runelite/api/widgets/Widget.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevTools.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsOverlay.java
Also, modified WidgetItem bounds to account for padding
=> Updated inventory overlay in DevTools

deobfuscator/src/main/java/net/runelite/deob/Deob.java
Finished my entire deob which took 10 mins but crashed because I didn't supply an output jar :(
=> Please prompt user when invalid amount of args are provided

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifier.java
Adds fletching(cutting and stringing all bows) and glassblowing to the list of activities for the idle notifier.
I'm looking into an implementation of a config for the idle notifier in its current form.
=> Added fletching and glassblowing to idle notifier/animationID class

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/events/ExperienceChanged.java, runelite-client/src/main/java/net/runelite/inject/callbacks/Hooks.java
I went ahead and tested both functions on my account.
=> Add getters for skill experience

runelite-api/src/main/java/net/runelite/api/queries/DecorativeObjectQuery.java, runelite-api/src/main/java/net/runelite/api/queries/GameObjectQuery.java, runelite-api/src/main/java/net/runelite/api/queries/GroundObjectQuery.java, runelite-api/src/main/java/net/runelite/api/queries/TileObjectQuery.java, runelite-api/src/main/java/net/runelite/api/queries/WallObjectQuery.java
Open to discussion on having the getter methods for objects and tiles in a different class, such as ``Client``.
=> Add object queries

runelite-client/src/main/java/net/runelite/client/plugins/PluginManager.java, runelite-client/src/main/java/net/runelite/client/plugins/implings/Implings.java, runelite-client/src/main/java/net/runelite/client/plugins/implings/ImplingsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/implings/ImplingsOverlay.java
As always, feedback is welcome
(especially for getEnabledIDs in ImplingsOverlay)
Is there a better way to do this?
=> Implings plugin

runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java
ConfigPanel now
- shows label and checkbox on the same line
- becomes scrollable
=> ConfigPanel improvements

runelite-client/src/main/java/net/runelite/client/plugins/implings/Implings.java, runelite-client/src/main/java/net/runelite/client/plugins/implings/ImplingsOverlay.java
Only update the config when its changed.
=> Use events instead of Guava for config changes

runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java
Fixes the FPS drop when spam clicking a config checkbox.
=> Moved configuration web request to another thread

runelite-client/src/main/java/net/runelite/client/plugins/PluginManager.java, runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobe.java, runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobes.java, runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesOverlay.java
shows a circle on the top of the screen with a progress arc (similar to rs3) 
currently shows max 5 on the screen for 10 seconds
still to do:
add tooltips
config for size, position, colors (defaults to middle of screen atm)
=> added xp globes plugin

runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java
http://i.imgur.com/q5hqndV.png
http://i.imgur.com/cmtnkAC.png
=> change config to show buttons, which lead to options rather than all options on one page

runelite-api/src/main/java/net/runelite/api/Actor.java, runelite-api/src/main/java/net/runelite/api/Player.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsOverlay.java, runescape-api/src/main/java/net/runelite/rs/api/Actor.java, runescape-api/src/main/java/net/runelite/rs/api/Model.java, runescape-api/src/main/java/net/runelite/rs/api/Player.java, runescape-client/src/main/java/Player.java
Also, fixed Player#getModel() and hooked Actor#getOrientation()
=> Added wireframe rendering to DevTools for local player model

runelite-client/src/main/java/net/runelite/client/plugins/PluginManager.java, runelite-client/src/main/java/net/runelite/client/plugins/jewelrycount/JewelryCharges.java, runelite-client/src/main/java/net/runelite/client/plugins/jewelrycount/JewelryCount.java, runelite-client/src/main/java/net/runelite/client/plugins/jewelrycount/JewelryCountConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/jewelrycount/JewelryCountOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/jewelrycount/JewelryType.java
Only counts glory, ring of dueling, games necklace charges, but can add more later
=> Added jewelry count plugin

runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSpot.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSpotOverlay.java
Red are the flying fish locations
=> Change overlay color for flying fish

runelite-client/src/main/java/net/runelite/client/plugins/runecraft/BindNeckOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/Runecraft.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftOverlay.java
-Since all charges are same ID, it will display a "?" until your current necklace breaks/or you right click check it
=> Add binding necklace to jewelrycount

runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobe.java, runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesOverlay.java
http://i.imgur.com/1MG4rmx.png
=> added xp globe tooltip

runelite-client/src/main/java/net/runelite/client/config/ConfigItem.java, runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java
Added consistency to the ordering of the ConfigItems in the PluginPanel. items are now ordered by keyname alphabetically
=> ConfigItems in the plugin panel ordened alphabetically (from random order)

cache/src/main/java/net/runelite/cache/NpcManager.java
Before we could not use it like ItemManager#getItems()
=> Added getter for npcs ArrayList

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommands.java, runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsConfig.java
added position to buttons.
added !total command (same as !lvl total and !lvl overall) for compatibility with other clients.
=> Lvl commands update

runelite-api/src/main/java/net/runelite/api/ItemID.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftOverlay.java
Added damaged pouches to RC plugin; renamed ItemIDs for them
=> Added damaged pouches to RC plugin; renamed ItemIDs for them

runelite-client/src/main/java/net/runelite/client/plugins/mousehighlight/MouseHighlightConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/mousehighlight/MouseHighlightOverlay.java
Mouse hover plugin did not show when items were being used ( Item -> Object ).
Also added config for border color.
=> Fix mouse highlight and add custom border color

runelite-client/src/main/java/net/runelite/client/plugins/mousehighlight/MouseHighlightOverlay.java
Fix for a critical bug in the mouseHighlight plugin. I never pushed this last night before the PR merge. Sorry about that.
=> Fix mouseHighlight plugin bug

runelite-client/src/main/java/net/runelite/client/plugins/runepouch/RunepouchConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/runepouch/RunepouchOverlay.java
MTV True Life: Addicted to Contributing
Added font color, Runescape small font, show/hide icons, and enabling to Runepouch config.
=> Add runepouch configs

http-service/src/main/java/net/runelite/http/service/config/ConfigService.java
Fixes https://github.com/runelite/runelite/issues/167.
=> http-service: Fix capturing the whole of dot-delimited keys

runescape-client/src/main/java/MachineInfo.java
Boolean variable 32Bit should be 64Bit. Tested this on my own windows 10 64Bit.
=> Changed 32bit to 64bit

deobfuscator/src/main/java/net/runelite/asm/Field.java, runelite-mixins/src/main/java/net/runelite/api/mixins/Copy.java, runelite-mixins/src/main/java/net/runelite/api/mixins/Replace.java, runescape-client-injector-plugin/src/main/java/net/runelite/injector/Inject.java, runescape-client-injector-plugin/src/main/java/net/runelite/injector/MixinInjector.java, runescape-client-injector-plugin/src/test/java/net/runelite/injector/MixinInjectorTest.java
Feature additions:
1. Make copies of game methods
2. Replace the code in game methods
3. Shadow static fields injected by other mixins
MixinInjectorTest is extended to test these additions.
=> Mixin feature additions

runelite-api/src/main/java/net/runelite/api/SpritePixels.java, runelite-client/src/main/java/net/runelite/client/game/ItemManager.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSpot.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSpotOverlay.java, runescape-api/src/main/java/net/runelite/rs/api/RSSpritePixels.java, runescape-client/src/main/java/BuildType.java, runescape-client/src/main/java/Client.java, runescape-client/src/main/java/MilliTimer.java, runescape-client/src/main/java/SpritePixels.java, runescape-client/src/main/java/Widget.java, runescape-client/src/main/java/class219.java, runescape-client/src/main/java/class33.java
Usage:
``BufferedImage itemPicture = ItemManager.getImage(int itemId);``
=> Add item image fetching to ItemManager

runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/config/RuneliteConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/mousehighlight/MouseHighlightOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/runepouch/RuneImageCache.java, runelite-client/src/main/java/net/runelite/client/plugins/runepouch/RunepouchOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/Slayer.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBoxOverlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/tooltips/Tooltip.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/tooltips/TooltipPriority.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/tooltips/TooltipRenderer.java
**Usage:**
```
Tooltip tooltip = new Tooltip(TooltipPriority.HIGH);
tooltip.setText("White text</br><col=ff0000>Second line is red</col> and white.");
runelite.getTooltipRenderer().add(tooltip);
```
TooltipPriority dictates which tooltip gets drawn on top during conflicts.  NONE > LOW > MED > HIGH
Tooltips support linebreaks and color tags in the OSRS format:
```
<col=HEX></col>
</br>
```
=> Add tooltip system

runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java
=> Sort plugins by name

runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java
=> Plugin configuration panel is now scrollable

runelite-client/src/main/java/net/runelite/client/plugins/jewellerycount/JewelleryCountOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/jewellerycount/JewelleryCountPlugin.java
Fix jewellery plugin overlay to actually render.
Broke here, I lack the git-fu to do it (and also made 1 addtl change):
https://github.com/runelite/runelite/commit/18c0eb7ccbfe568414cdcfe3f1e91bd94b6a59bd#diff-7d40b880a716ce1463efa3b9a65f27e1L61
=> Fix jewellery plugin

runelite-api/src/main/java/net/runelite/api/Actor.java, runelite-api/src/main/java/net/runelite/api/Perspective.java, runelite-api/src/main/java/net/runelite/api/Region.java, runelite-api/src/main/java/net/runelite/api/SceneTileModel.java, runelite-api/src/main/java/net/runelite/api/Tile.java, runelite-api/src/main/java/net/runelite/api/WallObject.java, runelite-client/src/main/java/net/runelite/client/plugins/instancemap/InstanceMapOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/instancemap/IntanceMapPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/instancemap/PixelMaps.java, runelite-client/src/main/java/net/runelite/client/plugins/instancemap/WallOffset.java, runelite-client/src/main/java/net/runelite/client/plugins/instancemap/WallShape.java, runelite-mixins/src/main/java/net/runelite/mixins/RSActorMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSTileMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSRegion.java, runescape-api/src/main/java/net/runelite/rs/api/RSSceneTileModel.java, runescape-api/src/main/java/net/runelite/rs/api/RSWallObject.java
Added local player location to instance map
Optimized rendering by drawing the instance only once(on plane/game state/region changed) and storing it in a buffered image. The buffered image is drawn every frame rather than rendering the whole instance every frame. The players location is drawn on top of this buffered image.
Edit:
Added walls and complex tile rendering
=> Update instance map

runelite-api/src/main/java/net/runelite/api/Area.java, runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/GameObject.java, runelite-api/src/main/java/net/runelite/api/IndexedSprite.java, runelite-api/src/main/java/net/runelite/api/ObjectComposition.java, runelite-api/src/main/java/net/runelite/api/TileObject.java, runelite-api/src/main/java/net/runelite/api/WallObject.java, runelite-client/src/main/java/net/runelite/client/game/ItemManager.java, runelite-client/src/main/java/net/runelite/client/plugins/instancemap/InstanceMapOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/instancemap/InstanceMapPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/instancemap/PixelMaps.java, runelite-mixins/src/main/java/net/runelite/mixins/RSGameObjectMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSSpritePixelsMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/TileObjectMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSArea.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java, runescape-api/src/main/java/net/runelite/rs/api/RSIndexedSprite.java, runescape-api/src/main/java/net/runelite/rs/api/RSObjectComposition.java, runescape-api/src/main/java/net/runelite/rs/api/RSWallObject.java, runescape-client/src/main/java/Area.java, runescape-client/src/main/java/PacketBuffer.java, runescape-client/src/main/java/PlayerComposition.java, runescape-client/src/main/java/Projectile.java, runescape-client/src/main/java/RenderOverview.java, runescape-client/src/main/java/ScriptVarType.java, runescape-client/src/main/java/class34.java, runescape-client/src/main/java/class39.java
The instance map now renders trees/bushes/map icons. 
I also switched to rendering walls the way the client source does, and it's fixed walls rendering inside of rivers and added red lines to door.
=> Add rocks/trees/bushes and map icons to instance map

runelite-api/src/main/java/net/runelite/api/Perspective.java, runelite-api/src/main/java/net/runelite/api/Projectile.java, runelite-api/src/main/java/net/runelite/api/ProjectileID.java, runelite-client/src/main/java/net/runelite/client/callback/Hooks.java, runelite-client/src/main/java/net/runelite/client/events/ProjectileMoved.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeProjectile.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeProjectileInfo.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeWarningConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeWarningOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeWarningPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSProjectileMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java, runescape-client/src/main/java/Projectile.java, runescape-client/src/main/java/class184.java, runescape-client/src/main/java/class72.java
Adds AoE warnings for projectiles that cause splash damage when they hit the ground. Especially useful as Lizardman Shamas, and a few raids bosses.
Examples: 
https://i.gyazo.com/2ceea15b5298f0b192b70f4ad6e347a4.gif
https://i.gyazo.com/8e3e883dcab8d4fd52c34c39aabb0f98.gif
https://i.gyazo.com/4fd4a037e53579187f37ff84b5252cce.gif
https://i.gyazo.com/049a61890c6149a058610c1d349504e7.gif
Edit: 
Sorry about the 2nd PR. I managed to delete this branch rather than the empty one i just created
=> Add AoE warning plugin

runelite-api/src/main/java/net/runelite/api/ProjectileID.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeProjectileInfo.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeWarningConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeWarningPlugin.java
=> Add crazy arch to aoe plugin

runelite-api/src/main/java/net/runelite/api/ChatMessageType.java, runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/RuneliteModule.java, runelite-client/src/main/java/net/runelite/client/chat/ChatColor.java, runelite-client/src/main/java/net/runelite/client/chat/ChatColorType.java, runelite-client/src/main/java/net/runelite/client/chat/ChatMessageBuilder.java, runelite-client/src/main/java/net/runelite/client/chat/ChatMessageManager.java, runelite-client/src/main/java/net/runelite/client/game/ItemManager.java, runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/examine/ExamineConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/examine/ExaminePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/volcanicmine/VolcanicMinePlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java, runelite-plugin-archetype/src/main/resources/archetype-resources/src/main/java/ExamplePlugin.java
- Create API for updating chat message based on saved colors for normal
and highlighted message
- Update examine plugin to include setting for showing item price when
examining item and choosing colors for the examine message (using new
chat message API)
- Update chat commands plugin to use the new API
- Update chat commands to use cached item searches
- Add option to globally disable recoloring to RuneliteConfig
=> Show item price when examining item

runelite-client/src/main/java/net/runelite/client/callback/Hooks.java, runelite-client/src/main/java/net/runelite/client/chat/ChatMessageManager.java, runelite-client/src/main/java/net/runelite/client/chat/QueuedMessage.java, runelite-client/src/main/java/net/runelite/client/events/MenuOptionClicked.java, runelite-client/src/main/java/net/runelite/client/plugins/examine/ExaminePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/examine/PendingExamine.java
- Show price of entire stack of stackable items when examined from
inventory, and not only single item in stack
Didn't knew how to do this before so I just shown examine price of one item in stack, but then I noticed how to do it in jewellery count plugin, so here is the change a bit late.
=> Show price of entire stack for stackable items when examined

runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
Fix overlay renderer plugin caching to actually use plugin received from
onPluginChanged hook, because the events are fired before the plugins
are actually added/removed to the plugin list.
=> Fix overlay renderer cache

runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/BackgroundComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/ImagePanelComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/InfoBoxComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/PanelComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/TooltipComponent.java
Example ImagePanelComponent with custom background color
=> Add additional functionality to overlay UI

runelite-api/src/main/java/net/runelite/api/Player.java, runelite-client/src/main/java/net/runelite/client/plugins/teamcapes/TeamCapesConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/teamcapes/TeamCapesOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/teamcapes/TeamCapesPlugin.java, runescape-api/src/main/java/net/runelite/rs/api/RSPlayer.java
Disabled by default. Used by clans when pking.
=> Add Team Capes plugin

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
Added animation IDs for infernal tools to fix their idle notifications
=> Idle fix infernal tools

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
Added animation IDs for dragon pickaxe (or). Added animation ID placeholders for 3rd age items.
=> Idle fix drag pickaxe ornament

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-api/src/main/java/net/runelite/api/MenuAction.java, runelite-api/src/main/java/net/runelite/api/widgets/Widget.java, runelite-client/src/main/java/net/runelite/client/callback/Hooks.java, runelite-client/src/main/java/net/runelite/client/events/GameObjectsChanged.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/hunter/CatchrateOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/hunter/HunterConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/hunter/HunterPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/hunter/HunterTrap.java, runelite-client/src/main/java/net/runelite/client/plugins/hunter/TrapOverlay.java, runelite-mixins/src/main/java/net/runelite/mixins/RSWidgetMixin.java, runescape-client/src/main/java/Tile.java
A plugin that tracks your traps like in osbuddy.
Currently it only works for box traps, deadfall traps and bird snares
Feedback is appreciated =)
=> Hunter plugin

runelite-client/src/main/java/net/runelite/client/ui/overlay/components/BackgroundComponent.java
=> Fix BackgroundComponent's background overflow

runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePlugin.java
Opens the hiscore panel when you right-click and Lookup players in-game.
=> Expand the hiscore panel when looking up players

runelite-client/src/main/java/net/runelite/client/plugins/attackindicator/AttackIndicatorOverlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayPosition.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayUtil.java
=> Changed attack style plugin to render over right side of chatbox

runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java
=> Fix previous result not being cleared in hiscore plugin

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
=> Fall back to default font for glyphs not in the custom font

runelite-client/src/main/java/net/runelite/client/plugins/examine/ExaminePlugin.java
Fixes #294 in the last changed code block and prevents NPE in the first two
=> Fix ExaminePlugin OOB exception

runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
=> Combine BOTTOM_RIGHT and ABOVE_CHATBOX_RIGHT overlays for fixed mode

runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesOverlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/PanelComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/ProgressBarComponent.java
#279 
The mouse was not captured, but it is hovering over the Woodcutting icon.
=> Changed XpGlobes to use new Overlay components

http-api/src/main/java/net/runelite/http/api/worlds/WorldClient.java, http-api/src/main/java/net/runelite/http/api/worlds/WorldType.java, http-service/src/main/java/net/runelite/http/service/worlds/ServiceWorldType.java, http-service/src/main/java/net/runelite/http/service/worlds/WorldsService.java, http-service/src/test/java/net/runelite/http/service/worlds/WorldsServiceTest.java
Enables #284 to consider hopping between normal/dmm/sdmm.
=> Extend world list lookup functionality

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerOverlay.java
This got broken in the native-ui/component updates
=> Slayer plugin - fix "count on items" feature

runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/config/ConfigItem.java, runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java
This allows confirmationWarning to be show when disabling.
=> client: add ConfigItem.warnOnDisable and warnOnEnable

runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
=> Add support for making tar idle notification

runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java
Add search bar to ConfigPanel that will search plugin configuration
names and filter them based on input.
Preview:
=> Add search bar to ConfigPanel

runelite-client/src/main/java/net/runelite/client/ui/overlay/tooltip/TooltipOverlay.java
=> Let overlapping tooltips stack vertically

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-mixins/src/main/java/net/runelite/mixins/PlayerIsClanMemberMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/PlayerIsFriendMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/PlayerIsIgnoredMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSFriendMixin.java
=> Optimize isFriend, isIgnored and add isClanMember to client API

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-mixins/src/main/java/net/runelite/mixins/PlayerIsClanMemberMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/PlayerIsFriendMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/PlayerIsIgnoredMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
- Call the real method from isFriended
- Call the real method from isIgnored
- Add null check for getClanMembers
=> Fix new player-is-x mixins

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/Projectile.java, runelite-api/src/main/java/net/runelite/api/ProjectileID.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeProjectileInfo.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeWarningConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeWarningPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPlugin.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayUtil.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSProjectileMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java, runescape-api/src/main/java/net/runelite/rs/api/RSProjectile.java, runescape-client/src/main/java/Projectile.java, runescape-client/src/main/java/class35.java
An example of what the Projectile Dev Tool looks like
Additionally the following were added to the AoE plugin.
- Vorkath
- Galvek
- Vet'ion
- Chaos Fanatic
- Corporeal Beast
=> Projectiles Dev Tool and Additions to the AoE plugin

runescape-client/src/main/java/AttackOption.java, runescape-client/src/main/java/BoundingBox3D.java, runescape-client/src/main/java/Client.java, runescape-client/src/main/java/CollisionData.java, runescape-client/src/main/java/Coordinates.java, runescape-client/src/main/java/FaceNormal.java, runescape-client/src/main/java/Friend.java, runescape-client/src/main/java/GameCanvas.java, runescape-client/src/main/java/ItemContainer.java, runescape-client/src/main/java/JagexGame.java, runescape-client/src/main/java/KeyFocusListener.java, runescape-client/src/main/java/RenderOverview.java, runescape-client/src/main/java/UnitPriceComparator.java, runescape-client/src/main/java/Widget.java, runescape-client/src/main/java/class27.java, runescape-client/src/main/java/class60.java, runescape-client/src/main/java/class82.java, runescape-client/src/main/java/class89.java
Just to update a few fields, nothing too big found. Maybe the minimapSprite could be interesting.
=> Update a few fields from the RuneLoader modscript

runescape-client/src/main/java/AttackOption.java, runescape-client/src/main/java/Client.java, runescape-client/src/main/java/DecorativeObject.java, runescape-client/src/main/java/FontTypeFace.java, runescape-client/src/main/java/ItemContainer.java, runescape-client/src/main/java/MouseInput.java, runescape-client/src/main/java/MouseRecorder.java, runescape-client/src/main/java/RenderOverview.java, runescape-client/src/main/java/SpritePixels.java, runescape-client/src/main/java/Timer.java, runescape-client/src/main/java/class1.java, runescape-client/src/main/java/class160.java, runescape-client/src/main/java/class168.java, runescape-client/src/main/java/class192.java, runescape-client/src/main/java/class21.java, runescape-client/src/main/java/class22.java, runescape-client/src/main/java/class25.java, runescape-client/src/main/java/class27.java, runescape-client/src/main/java/class285.java, runescape-client/src/main/java/class34.java, runescape-client/src/main/java/class43.java, runescape-client/src/main/java/class82.java, runescape-client/src/main/java/class94.java
Mostly mapped fields and methods related overheadText, drawing text and menu clicks
=> Mapping more fields and methods

runelite-api/src/main/java/net/runelite/api/MenuAction.java
Add MenuActions from https://pastebin.com/0pqjNrZL.
=> Generalize and add MenuActions

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-api/src/main/java/net/runelite/api/ProjectileID.java, runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java
Shows a count of cannonballs atop the cannon
=> Add Cannon plugin

runelite-api/src/main/java/net/runelite/api/ProjectileID.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeProjectileInfo.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeWarningConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeWarningPlugin.java
=> Add gargoyle boss to aoe plugin

runelite-client/src/main/java/net/runelite/client/ui/overlay/components/ProgressBarComponent.java
=> change Progress Bar Component to round percentage down

runelite-api/src/main/java/net/runelite/api/widgets/Widget.java, runelite-mixins/src/main/java/net/runelite/mixins/RSWidgetMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSWidget.java
give more access to widgets for the additions to the widget dev tool
=> Add more methods to modify widgets

runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/NumberField.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/WidgetEditPanel.java
Depends on PR #410 
- Easily test changes without needing to recompile/reload your code
- Display how to access this widget without needing to go through lots of trial & error for widgets with many hidden dynamic children
=> Additions to the Widget Devtool

runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
- Send idle notification only after animation ended and the timeout has
passed, and not start counting the timeout since animation started.
- Change the 1 second schedule to GameTick hook because animations are
changed based on ticks
Fixes #282
=> Fix idle notifications for animation changes

runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
- Cancel animation idle timer when combat begins
- Cancel combat idle timer when animation begins
=> Fix idle animation plugin timer cancelling

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/Builders.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/Combo.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/Effect.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/Food.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/FoodBase.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatChanges.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/Positivity.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/SimpleStatBoost.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/SingleEffect.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/StatBoost.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/StatChange.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/StatsChanges.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/TooltipMode.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/delta/DeltaCalculator.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/delta/DeltaPercentage.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/food/Anglerfish.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/potions/PrayerPotion.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/potions/SuperRestore.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/stats/EnergyStat.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/stats/SkillStat.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/stats/Stat.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/stats/Stats.java, runelite-client/src/test/java/net/runelite/client/plugins/itemstats/ItemStatChangesTest.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
=> Add ItemStat plugin

runelite-client/src/main/java/net/runelite/client/plugins/runepouch/RunepouchConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/runepouch/RunepouchOverlay.java
As requested by ZipMePl0x in Discord.
=> Add hover only option to Runepouch plugin

runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java, runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java
=> Add a Reset button to config panels for resetting to defaults

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/SkillXPInfo.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerPlugin.java
- Add actions, actions/hr, xp gained and progress bar to the XP tracker
- Remove obsolete fishing and woodcutting overlays
Preview:
With total exp:
=> Update XP tracking plugin to include more info

runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java
Change conversion of config stream to map and then creating new stream
and just iterating entries to mapping config stream to pairs (map
entries, becuase Java do not have generic pair implementation).
=> Change conversion of config stream to map to pairs

runelite-api/src/main/java/net/runelite/api/ProjectileID.java, runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java
=> Add granite cannonball support to plugin

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java
As requested by Apo in Discord
=> Add custom colors to ground items

runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
First time contributing to a project on GitHub. Hopefully I'm doing this correctly. I definitely did not automatically upload a fully filled out login screen to imgur by accident to come up with this idea...
=> Disable screenshots on login screen

runelite-client/src/main/java/net/runelite/client/account/AccountSession.java, runelite-client/src/main/java/net/runelite/client/account/SessionManager.java, runelite-client/src/main/java/net/runelite/client/account/WSClient.java, runelite-client/src/main/java/net/runelite/client/plugins/account/AccountPlugin.java, runelite-client/src/test/java/net/runelite/client/config/ConfigManagerTest.java
- Change AccountSession to use lombok features
- Fix access levels of WSClient
=> Cleanup net.runelite.client.account

runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java, runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
-Add raid varbit check to remove potions
-Fixed spelling
=> Fix timers

runelite-api/src/main/java/net/runelite/api/Perspective.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/AbyssOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/AbyssRifts.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftPlugin.java
=> Add Abyss rifts plugin

runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoOverlay.java
=> Fix color tags in OpponentInfo

runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostIndicator.java, runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsPlugin.java
- Fix issue with indicators showing up multiple times
- Fix issue with disabling skill boosts not removing indicators
=> Fix several issues with indicators

runelite-api/src/main/java/net/runelite/api/Actor.java, runelite-client/src/main/java/net/runelite/client/plugins/implings/ImplingsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsOverlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayUtil.java, runescape-api/src/main/java/net/runelite/rs/api/RSActor.java, runescape-client/src/main/java/Actor.java, runescape-client/src/main/java/NPC.java, runescape-client/src/main/java/Player.java, runescape-client/src/main/java/class3.java
This draws the overlay just above where the health bar should be.
Fixes #524
=> Fix overlays drawing too far above player's heads

runelite-client/pom.xml, runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/RuneLiteModule.java, runelite-client/src/main/java/net/runelite/client/discord/DiscordPresence.java, runelite-client/src/main/java/net/runelite/client/discord/DiscordReplyType.java, runelite-client/src/main/java/net/runelite/client/discord/DiscordService.java, runelite-client/src/main/java/net/runelite/client/discord/events/DiscordDisconnected.java, runelite-client/src/main/java/net/runelite/client/discord/events/DiscordErrored.java, runelite-client/src/main/java/net/runelite/client/discord/events/DiscordJoinGame.java, runelite-client/src/main/java/net/runelite/client/discord/events/DiscordJoinRequest.java, runelite-client/src/main/java/net/runelite/client/discord/events/DiscordReady.java, runelite-client/src/main/java/net/runelite/client/discord/events/DiscordSpectateGame.java, runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordGameEventType.java, runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordState.java, runelite-client/src/main/resources/net/runelite/client/runelite.properties
- Add injectable Discord RPC service that will broadcast Discord events
through event bus and have API for setting Discord Rich Presence status
- Add Discord plugin that updates the Discord rich presence currently only
for trained skills
Preview:
=> Add Discord service and plugin

runelite-client/src/main/java/net/runelite/client/RuneLiteProperties.java, runelite-client/src/main/java/net/runelite/client/plugins/info/InfoPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java, runelite-client/src/main/java/net/runelite/client/ui/TitleToolbar.java, runelite-client/src/main/resources/net/runelite/client/runelite.properties
=> Allow titlebar buttons to be moved out of the titlebar

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java
=> slayer plugin: add check for cachedXp when xp changes

runelite-client/src/main/java/net/runelite/client/plugins/runecraft/AbyssOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftConfig.java
=> runecraft plugin: show click boxes of abyss rifts

runelite-api/src/main/java/net/runelite/api/Varbits.java, runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java, runelite-api/src/main/java/net/runelite/api/widgets/WidgetInfo.java, runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/AbsorptionCounter.java, runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZoneConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZoneOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZonePlugin.java
* Send tray notifications on:
* Absorption below threshold
* Overload runs out
* Move NMZ overlay so it dosn't conflict with the opponent/timer overlay (#451)
=> Add Nightmare Zone plugin

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatOverlay.java
also fix theoretical text
from
to
=> Item stat: Fix overlay being shown ontop of menu

runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSpot.java
- Add support for Karambwan fishing spots
- Add support for Karambwanji/Shrimp fishing spots
Karambwan fishing is now great again and this is needed.
Preview:
=> Add support for Karambwan/Karambwanji to fishing

runescape-client-injector-plugin/src/main/java/net/runelite/injector/InjectConstruct.java
Currently if you `@Construct` a class with overloaded constructors it will choose whichever one is first in the method list. This changes it to find the constructor with matching arguments.
=> injector: Choose the right constructor if multiple exist

runelite-client/src/main/java/net/runelite/client/plugins/PluginDependencies.java, runelite-client/src/main/java/net/runelite/client/plugins/PluginDependency.java, runelite-client/src/main/java/net/runelite/client/plugins/PluginManager.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSession.java, runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/WoodcuttingOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/WoodcuttingPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerService.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerServiceImpl.java
=> Add plugin dependencies

runelite-client/src/main/java/net/runelite/client/plugins/agilityplugin/AgilityOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/fightcave/FightCaveOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/hunter/TrapOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/mousehighlight/MouseHighlightOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/prayflick/PrayerFlickOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/specorb/SpecOrbOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesOverlay.java
A check was added for plugins not to be loaded when loading vanilla thus the client is always non-null. Plugins loaded with vanilla don't use client.
=> Remove @Nullable Client annotations

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/plugins/minimap/MinimapConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/minimap/MinimapDot.java, runelite-client/src/main/java/net/runelite/client/plugins/minimap/MinimapPlugin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
This plugin will allow you to modify the following minimap dots:
- Item
- NPC
- Player
- Friend
- Team
- Clan
=> Minimap modifiable dots

runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
=> Fix the game freezing when screenshots are being taken

protocol/src/main/java/net/runelite/protocol/update/decoders/ArchiveResponseDecoder.java
=> Release ByteBuf in CacheClient when downloading chunks

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java
Add a highlighted items option aswell as re-order the config
=> Ground items: Add a highlight items only option

runelite-client/src/main/java/net/runelite/client/ui/NavigationButton.java, runelite-client/src/main/java/net/runelite/client/ui/PluginToolbar.java
This just sorts it alphabetically, but it could be changed quite easily.
=> Sort the PluginToolbar

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java
**Before:** 
**After:**
Fixes #659
=> grounditems: offset text on z axis

runelite-client/src/main/java/net/runelite/client/ui/overlay/components/ImagePanelComponent.java
=> image component: fix images being off-centered

cache/src/main/java/net/runelite/cache/script/Instructions.java, cache/src/main/java/net/runelite/cache/script/Opcodes.java
This is set to 1 on the mobile build. All that it does is change some sprites in the options panel.
=> cache: Add get_is_mobile opcode.

runelite-client/src/main/java/net/runelite/client/plugins/lowmemory/LowMemoryPlugin.java
=> Rename "Low memory" to "Low detail" plugin

runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsOverlay.java
=> Add ability to set custom colors for player indicators

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/plugins/zoom/ZoomConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/zoom/ZoomPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/CameraMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java, runescape-client/src/main/java/Client.java, runescape-client/src/main/java/DecorativeObject.java, runescape-client/src/main/java/Region.java, runescape-client/src/main/java/Script.java, runescape-client/src/main/java/VertexNormal.java, runescape-client/src/main/java/WorldMapType2.java, runescape-client/src/main/java/class19.java, runescape-client/src/main/java/class225.java, runescape-client/src/main/java/class33.java, runescape-client/src/main/java/class94.java
This allows the camera to go completely vertical. I'm really not sure if this is a good idea/if this will get you botwatch'd.
=> Add option to relax the camera's upper pitch limit

runelite-client/src/main/java/net/runelite/client/plugins/raids/Raid.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidRoom.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsTimer.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/solver/Layout.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/solver/LayoutSolver.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/solver/RotationSolver.java
- Remove "plugin" from the name
- Cache colours on startup
- Use regex to split config string so it doesn't include spaces after commas
=> Fix minor issues with Raids plugin

runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java
Fixes the issue above, also looks better :+1:
=> Use normal font weight for input field

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-mixins/src/main/java/net/runelite/mixins/CameraMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java, runescape-client/src/main/java/Client.java, runescape-client/src/main/java/DecorativeObject.java, runescape-client/src/main/java/Script.java, runescape-client/src/main/java/VertexNormal.java, runescape-client/src/main/java/WorldMapType2.java, runescape-client/src/main/java/class225.java, runescape-client/src/main/java/class33.java
=> Fix Perspective when near tall terain

runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java
=> hiscoreplugin: show skill details on hover instead of click

runelite-client/src/main/java/net/runelite/client/Notifier.java, runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java
Makes it so you can disable the beep sound when tray notifications are submitted.
Fixes #471
=> notifier: add option to disable notification sounds

runelite-api/src/main/java/net/runelite/api/Varbits.java, runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoOverlay.java
=> opponentinfo: display the name of the target of your target

runelite-client/src/main/java/net/runelite/client/callback/Hooks.java, runelite-client/src/main/java/net/runelite/client/input/KeyListener.java, runelite-client/src/main/java/net/runelite/client/input/KeyManager.java, runelite-client/src/main/java/net/runelite/client/input/MouseListener.java, runelite-client/src/main/java/net/runelite/client/input/MouseManager.java, runelite-client/src/main/java/net/runelite/client/input/MouseWheelListener.java, runelite-mixins/src/main/java/net/runelite/mixins/RSKeyFocusListenerMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSMouseInputMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSMouseWheelHandlerMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSKeyFocusListener.java, runescape-api/src/main/java/net/runelite/rs/api/RSMouseInput.java, runescape-api/src/main/java/net/runelite/rs/api/RSMouseWheelHandler.java, runescape-client-injector-plugin/src/main/java/net/runelite/injector/MixinInjector.java
This will be required later for movable overlays, the instance map, stretched fixed mode, etc. Related to #615, #540.
=> Add support for hooking input

runescape-client/src/main/java/Area.java, runescape-client/src/main/java/ClanMemberManager.java, runescape-client/src/main/java/Client.java, runescape-client/src/main/java/Coordinates.java, runescape-client/src/main/java/FileOnDisk.java, runescape-client/src/main/java/GrandExchangeEvents.java, runescape-client/src/main/java/LoginPacket.java, runescape-client/src/main/java/MapIcon.java, runescape-client/src/main/java/MapIconReference.java, runescape-client/src/main/java/MapLabel.java, runescape-client/src/main/java/RenderOverview.java, runescape-client/src/main/java/Script.java, runescape-client/src/main/java/SoundTask.java, runescape-client/src/main/java/SourceDataSoundSystem.java, runescape-client/src/main/java/VarPlayerType.java, runescape-client/src/main/java/VertexNormal.java, runescape-client/src/main/java/WorldComparator.java, runescape-client/src/main/java/WorldMapManager.java, runescape-client/src/main/java/WorldMapType1.java, runescape-client/src/main/java/WorldMapType2.java, runescape-client/src/main/java/class162.java, runescape-client/src/main/java/class176.java, runescape-client/src/main/java/class225.java, runescape-client/src/main/java/class277.java, runescape-client/src/main/java/class29.java, runescape-client/src/main/java/class299.java, runescape-client/src/main/java/class31.java, runescape-client/src/main/java/class33.java, runescape-client/src/main/java/class34.java, runescape-client/src/main/java/class44.java
This is just naming some world map stuff. I'm expecting a fair amount of these to be lost due to inlining, unfortunately.
=> Name world map classes

runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonUiOverlay.java
Added:
1. Unloading/emptying cannon
2. Double hit spots
3. UI panel for cannonballs left
https://i.imgur.com/EKDvCvR.png
=> Cannon emptying, double hit spots and UI panel.

runescape-api/src/main/java/net/runelite/rs/api/RSActor.java
=> Remove inSequence import b/c problems with mapping

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
- Mainly for infernal eels (and other eels as well)
Preview:
=> Add support for oily rod fishing to idle notifier

runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoOverlay.java
very rare, but it seems to happen in raids
=> opponent info: remove color tags from opponentOpponent name

runelite-client/src/main/java/net/runelite/client/Notifier.java
* Correct an issue where if `libnotify-bin` is missing then RuneLite doesn't do anything
* Add an icon to the Linux notifications using `libnotify-bin` if it's present
Sample on Ubuntu Budgie:
=> Notifier improvements and fixes for Linux

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
=> Fix visual bug occuring when sidepanel is contracted after resizing

runelite-client/src/main/java/net/runelite/client/Notifier.java
=> Allow other types of alerts when messages are off

runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
=> Remove the timeout for HP/pray thresholds

runelite-client/src/main/java/net/runelite/client/plugins/account/AccountPlugin.java, runelite-client/src/main/java/net/runelite/client/ui/TitleToolbar.java
This makes the entire PluginToolbar "tabs" which should make for better UX, and should reduce misclicks that log you out.
=> Move the Login and Logout buttons to the TitleToolbar

runelite-client/src/main/java/net/runelite/client/plugins/blastfurnace/BlastFurnaceCofferOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpPanel.java, runelite-mixins/src/main/java/net/runelite/mixins/RSHashTableMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSWidgetMixin.java
This removes a few places that allocate a lot of garbage that can be fixed without introducing large changes.
Before:
After:
=> Allocation optimization

runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java
Fixed the HiscorePanel text to reflect the changes in how the HiscorePanel works.
=> Fixed HiscorePanel text

runelite-client/src/main/java/net/runelite/client/plugins/config/FuzzySearch.java
Increase scoring based on string equality and contains checks with
lowercased and original casing.
Preview:
https://cdn.discordapp.com/attachments/301497432909414422/419151014424346625/Peek_2018-03-02_16-16.webm
=> Improve scoring of Jaro-Winkler

runelite-client/src/main/java/net/runelite/client/plugins/chathistory/ChatHistoryPlugin.java
=> Clear saved private chat history upon clear request

runelite-client/src/main/java/net/runelite/client/account/SessionManager.java, runelite-client/src/main/java/net/runelite/client/plugins/feed/FeedPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/feed/FeedPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeItemPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangePanel.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeSearchPanel.java, runelite-client/src/main/java/net/runelite/client/util/LinkBrowser.java
- Add link browser utility service that will try to open specified link in
browser, and in case operation fails displays message box and copy URL
to clipboard.
- Use new LinkBrowser API in SessionManager for opening the links.
Fixes: #434 
Preview:
=> Link navigator

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
=> idle notifier: add barbtail/dragon harpoon animation

runelite-client/src/main/java/net/runelite/client/discord/DiscordService.java
In case loading of Discord library failed, continue running application
and just disable Discord support.
Fixes #826
=> Continue running in case Discord lib load failed

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/Constants.java, runelite-client/src/main/java/net/runelite/client/callback/Hooks.java, runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java, runelite-client/src/main/java/net/runelite/client/input/MouseManager.java, runelite-client/src/main/java/net/runelite/client/input/MouseWheelListener.java, runelite-client/src/main/java/net/runelite/client/plugins/stretchedfixedmode/StretchedFixedModeConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/stretchedfixedmode/StretchedFixedModePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/stretchedfixedmode/TranslateMouseListener.java, runelite-client/src/main/java/net/runelite/client/plugins/stretchedfixedmode/TranslateMouseWheelListener.java, runelite-client/src/main/java/net/runelite/client/ui/ClientPanel.java, runelite-mixins/src/main/java/net/runelite/client/callback/Hooks.java, runelite-mixins/src/main/java/net/runelite/mixins/RSGameCanvasMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSMainBufferProviderMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSMouseWheelHandlerMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/StretchedFixedModeMixin.java, runescape-client-injector-plugin/src/main/java/net/runelite/injector/Inject.java, runescape-client-injector-plugin/src/main/java/net/runelite/injector/MixinInjector.java, runescape-client/src/main/java/MainBufferProvider.java
Adds a "Stretched Fixed Mode" plugin with these configuration options:
* Enable/disable plugin: Enables/disables stretching
* Keep aspect ratio - Keeps the aspect ratio when stretching
* Increased performance mode - Uses a fast algorithm when stretching, lowering quality but increasing performance
**Disabled:**
**Enabled:**
**Increased performance mode:** (click the image to see the quality difference)
**Keep aspect ratio:**
=> Stretched fixed mode

runelite-client/src/main/java/net/runelite/client/plugins/usernamesyncer/UsernameSyncerPlugin.java
=> Restore original username on syncer shutdown

runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonOverlay.java
=> Fix cannon plugin showing incorrect double hit spots after region change

runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
A feature I used a lot in Konduit
=> Add option to disable resizing of window

runelite-client/src/main/java/net/runelite/client/plugins/teamcapes/TeamCapesConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/teamcapes/TeamCapesOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/teamcapes/TeamCapesPlugin.java
Added minimum cape count to team cape plugin to reduce clutter/spam. Default is 1, so current behaviour is unchanged. First commit!
=> Team Capes: Added minimum cape count

runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
- Change isResizable to lockWindowSize
- Update the description and keyName
- Inverse the condition
=> Inverse window resize condition

runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java
=> Fix instance map "show" option not displaying in right-click menu

runelite-mixins/src/main/java/net/runelite/mixins/ScriptVMMixin.java, runescape-client-injector-plugin/src/main/java/net/runelite/injector/raw/ScriptVM.java
The issue is that I was using the AStores in scriptStores, which does not contain 100% of the script AStores.
=> injector: Fix scriptvm not updating currentScript

runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
Add toggles for idle animation notifications and combat idle
notifications to idle notifier plugin.
Preview:
=> Add idle anim and combat idle toggles to notifier

runelite-client/src/main/java/net/runelite/client/plugins/implings/ImplingsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsOverlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayUtil.java
- Add support to Player Indicators plugin to draw names on minimap
(disabled by default).
- Use OverlayUtil in implings plugin
- Remove unused code in OverlayUtil
Preview:
=> Minimap names

runelite-client/src/main/java/net/runelite/client/plugins/attackindicator/AttackIndicatorPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/attackindicator/AttackIndicatorPluginTest.java
I'm still a little unsure of the proper way to implement Mockito so I expect some problems with my test class. I can be reached either on here or in the Discord (@skimborder) if any changes are needed to this code.
=> Resolve Issue #860 - Warned attack modes not properly hiding

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/SkillXPInfo.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpPanel.java
=> Update Xp tracker UI to make it smaller

runelite-client/src/main/java/net/runelite/client/plugins/account/AccountPlugin.java
Added a confirmation window when clicking to sign out of **RuneLite**.
=> Added RuneLite account logout confirmation dialog

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java
- Highlights items above a certain value in the rightclick menu
- Show item quantities in the rightclick menu
=> Loot helper

runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZonePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/main/java/net/runelite/client/util/Text.java, runelite-client/src/test/java/net/runelite/client/util/TextTest.java
Not only is this a slight performance boost it is also nicer to look at compared to the regex that was being used everywhere.
=> Add a util method for removing tags

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/NPC.java, runelite-api/src/main/java/net/runelite/api/NPCComposition.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsOverlay.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java, runescape-api/src/main/java/net/runelite/rs/api/RSNPC.java
This adds the transform method in order to provide proper information for NPCs that were originally null.
=> Fix for null NPCs

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java
- Fixes https://github.com/runelite/runelite/issues/942
=> Fix ground items nullpointer exception

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
=> Title-case and remove "plugin" from ME swapper

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Shark harpoon fishing spots have "Big Net" option, not "Net".
=> Fix menu entry swap for shark harpoon fishing

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java
Superiors will despawn after two minutes: https://twitter.com/JagexAsh/status/777629171027734528
Hopefully this helps a few people not miss out on a chance at those juicy drops
=> Add slayer superior foe notification

runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/KourendLibraryOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/KourendLibraryPlugin.java
=> Fix Kourend Library plugin

runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
- Register services to EventBus before the ConfigManager#load is called
- Send events on loading from file
- Do not invokeLater in invokeLater
=> Fix ClientUI settings loading

runelite-client/src/main/java/net/runelite/client/util/SwingUtil.java
Call click action when selection NavigationButton.
=> Click the navigation button on selecting in

runelite-api/src/main/java/net/runelite/api/events/BoostedLevelChanged.java, runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
Needs more testing, especially with multiple boosts running at once, and stats recovering to base.
Fixes #288
=> Boosts plugin: Add "Next change"

runelite-client/src/main/java/net/runelite/client/plugins/poh/BurnerOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/poh/PohPlugin.java
mounted glory is a decoration object, not game object
Fixes #968
=> Poh plugin: fix mounted glory minimap icon

runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonSpotOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonSpots.java
=> Add common cannon spots

runelite-client/src/main/java/net/runelite/client/plugins/hunter/TrapOverlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/ProgressPie.java
As this will most likely be used elsewhere, figured it should have its own class.
I placed it within the components package even though it is not really a component, welcome to suggest a better location.
=> Add progress pie overlay component

runelite-api/src/main/java/net/runelite/api/model/Jarvis.java
=> jarvis: Allow null points

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
swaps bury/use option
[on why this is allowed now](https://github.com/runelite/runelite/pull/556#issuecomment-374069520)
=> menu entry swapper: swaps bury to use

runelite-client/src/main/java/net/runelite/client/plugins/reorderprayers/ReorderPrayersPlugin.java
- Fixes the prayer order resetting after teleporting to a new area
=> Fix prayer order resetting

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Some fishing spots have "Net" and "Harpoon" and some have "Big Net" and "Harpoon".
=> Fix net and harpoon swap for all fishing spots

runelite-client/src/main/java/net/runelite/client/plugins/agilityplugin/AgilityConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/agilityplugin/AgilityOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/agilityplugin/AgilityPlugin.java
=> Agility plugin: Agility configuration with Select Color

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/potions/PrayerPotion.java
=> itemstats: Support holy wrench effect

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/SkillAbbreviations.java
This should let you use just about any shortname you can think of when querying skills. Corrected a few typos in the comments while I was there.
=> Expand list of skill abbreviations for the !Lvl command

runelite-client/src/main/java/net/runelite/client/plugins/instancemap/InstanceMapInputListener.java, runelite-client/src/main/java/net/runelite/client/plugins/instancemap/InstanceMapOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/instancemap/InstanceMapPlugin.java
- Change instance map to resize on "fixed" layer so it can be layouted
- Scroll minimap only when mouse is in the minimap bounds
Preview:
=> Instance map improvements + moving

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/stats/EnergyStat.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/stats/SkillStat.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/stats/Stats.java
I guess this was missed during refactoring.
=> itemstats: use EnergyStat instead of anonymous stat

runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostIndicator.java, runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/bosstimer/BossTimersPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/bosstimer/RespawnTimer.java, runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonCounter.java, runelite-client/src/main/java/net/runelite/client/plugins/kingdomofmiscellania/KingdomCounter.java, runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/AbsorptionCounter.java, runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZoneOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsTimer.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/TaskCounter.java, runelite-client/src/main/java/net/runelite/client/plugins/timers/TimerTimer.java, runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/Counter.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBox.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBoxManager.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBoxPriority.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/Timer.java
Group InfoBoxes by plugin, then sorting those groups by priority
Boost Indicators are set as HIGH priority
Timers InfoBoxes are set as MED priority
Relevant to #559
=> Info Boxes: Group boxes by plugin, sort by priority

runelite-api/src/main/java/net/runelite/api/Experience.java, runelite-api/src/test/java/net/runelite/api/ExperienceTest.java
Added a few extra ExperienceTests related to virtual levels and negative XP values. Doesn't change how the API can be used. Also added jdocs to the Experience.java methods.
=> Expand tests for and document the Experience API

runelite-api/src/main/java/net/runelite/api/Varbits.java, runelite-client/src/main/java/net/runelite/client/plugins/dailytaskindicators/DailyTasksConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/dailytaskindicators/DailyTasksPlugin.java
Sends a message in chatbox notifying the player if they can collect:
- Herb boxes at NMZ
- Staves from Zaff
- Pure essence from Wizard Cromperty
=> Add daily task indicators

runelite-client/src/main/java/net/runelite/client/plugins/hunter/HunterPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/hunter/TrapOverlay.java
This will show the remaining time on caught hunter traps instead of just a full circle.
=> Show remaining time on successful hunter traps

runelite-client/src/main/java/net/runelite/client/plugins/agilityplugin/AgilityPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/agilityplugin/AgilitySession.java, runelite-client/src/main/java/net/runelite/client/plugins/agilityplugin/Courses.java, runelite-client/src/main/java/net/runelite/client/plugins/agilityplugin/LapCounterOverlay.java
=> agility plugin: Add lap counter

runelite-api/src/main/java/net/runelite/api/widgets/Widget.java, runelite-client/src/main/java/net/runelite/client/plugins/reorderprayers/ReorderPrayersPlugin.java, runescape-api/src/main/java/net/runelite/rs/api/RSWidget.java, runescape-client/src/main/java/AbstractSoundSystem.java, runescape-client/src/main/java/Client.java, runescape-client/src/main/java/FileRequest.java, runescape-client/src/main/java/Fonts.java, runescape-client/src/main/java/GZipDecompressor.java, runescape-client/src/main/java/GameObject.java, runescape-client/src/main/java/GrandExchangeEvent.java, runescape-client/src/main/java/RunException.java, runescape-client/src/main/java/SoundTaskDataProvider.java, runescape-client/src/main/java/Widget.java, runescape-client/src/main/java/WidgetNode.java, runescape-client/src/main/java/WorldMapData.java, runescape-client/src/main/java/WorldMapRegion.java, runescape-client/src/main/java/class167.java, runescape-client/src/main/java/class190.java, runescape-client/src/main/java/class197.java, runescape-client/src/main/java/class21.java, runescape-client/src/main/java/class3.java, runescape-client/src/main/java/class44.java, runescape-client/src/main/java/class95.java
This mainly renames listeners, but it includes some other renaming to widgets also.
=> Refactor Widget defs

runelite-client/src/main/java/net/runelite/client/plugins/implings/ImplingMinimapOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/implings/ImplingsPlugin.java
to render above minimap on resizable, the overlay must be rendered above widgets
Fixes #1185
=> impling plugin: Move minimap overlay into it's own overlay

runelite-client/src/main/java/net/runelite/client/plugins/devtools/WidgetInspector.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/WidgetTreeNode.java
Add known widget names to the widget inspector
=> Widget inspector improvement

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/AnagramClue.java
Reported by Bownerator on Discord.
Source for correct answer http://oldschoolrunescape.wikia.com/wiki/Nurse_Wooned
=> Fix challenge answer for Nurse Wooned clue

cache/src/main/antlr4/net/runelite/cache/script/assembler/rs2asm.g4, runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/ScriptID.java, runelite-api/src/main/java/net/runelite/api/events/ScriptCallbackEvent.java, runelite-client/src/main/java/net/runelite/client/game/ChatboxInputManager.java, runelite-client/src/main/java/net/runelite/client/plugins/banktags/BankTagsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/zoom/ZoomPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSIndexDataBaseMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/ScriptVMMixin.java, runelite-script-assembler-plugin/src/main/java/net/runelite/script/AssembleMojo.java, runelite-scripts/scripts/ChatboxInputHandler.rs2asm, runelite-scripts/scripts/ChatboxInputInit.rs2asm, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java, runescape-api/src/main/java/net/runelite/rs/api/RSScriptEvent.java
Usage:
```
chatboxInputManager.openInputWindow("Hello RuneLite", "Sample Text", str->{
SwingUtilities.invokeLater(()-> JOptionPane.showMessageDialog(null, str));
});
```
=>  Add ChatboxInputManager to provide a RuneScape styled input box

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
=> Menu entry swapper: Swap last destination for spiritual fairy tree

runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZonePlugin.java
=> nmz plugin: reset absorption notification when not in NMZ

runelite-api/src/main/java/net/runelite/api/MenuAction.java, runelite-api/src/main/java/net/runelite/api/MenuEntry.java, runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java, runelite-client/src/main/java/net/runelite/client/plugins/itemprices/ItemPricesOverlay.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
We don't have all of the types in MenuAction and it causes them to get mapped to UNKNOWN when translated back and forth with the API
=> Change MenuEntry type to int

runelite-client/src/main/java/net/runelite/client/plugins/devtools/LocationOverlay.java
=> Highlight current region in Location devtool

runelite-client/src/main/java/net/runelite/client/plugins/reportbutton/ReportButtonPlugin.java
Currently disabling the plugin will not change the text back to "Report", this fixes that issue.
=> Reset report button text to default when plugin is disabled

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatChanges.java
Ugthanki kebab dropped from monster, ex. the smoke devil boss, have a different id and didn't show up in the plugin.
=> Added food to itemstats plugin

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/HintArrowType.java, runelite-api/src/main/java/net/runelite/api/Player.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSPlayerMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java, runescape-api/src/main/java/net/runelite/rs/api/RSPlayer.java, runescape-client/src/main/java/Client.java, runescape-client/src/main/java/class38.java
Expose hint arrows to API to be able to set them in plugins.
=> Add HintArrows to API

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/plugins/animsmoothing/AnimationSmoothingConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/animsmoothing/AnimationSmoothingPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSDynamicObjectMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSModelMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSPlayerMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSSequenceMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSActor.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java, runescape-api/src/main/java/net/runelite/rs/api/RSDynamicObject.java, runescape-api/src/main/java/net/runelite/rs/api/RSFrame.java, runescape-api/src/main/java/net/runelite/rs/api/RSFrameMap.java, runescape-api/src/main/java/net/runelite/rs/api/RSFrames.java, runescape-api/src/main/java/net/runelite/rs/api/RSModel.java
- Adds Smooth(interpolated) Animations for Players, NPCs, Objects and SpotAnims
Before:
After:
Before:
After:
=> Add Smooth Animations Plugin

runelite-client/src/main/java/net/runelite/client/plugins/banktags/BankTagsPlugin.java
Withdraw-X:
Tag editing in the current release:
...and after this change:
=> banktags: Adjust dialog text to match Withdraw-X dialog

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/MapClue.java
Change worldpoint for easy map clue ID 2713 
Fixes https://github.com/runelite/runelite/issues/1309#issuecomment-379477643 on issue #1309
=> Update worldpoint for map clue 2713

runelite-api/src/main/java/net/runelite/api/widgets/Widget.java, runelite-client/src/main/java/net/runelite/client/plugins/reorderprayers/ReorderPrayersPlugin.java, runescape-api/src/main/java/net/runelite/rs/api/RSWidget.java
This made maven unable to do a incremental build for some reason.
=> Rename setClickMask()I > getClickMask()I

runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeOfferSlot.java
=> ge plugin: Display spent price instead of original offer price

runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java
Adds individual clue counts and rank to the highscore plugin
=> Adds individual clue counts to highscore plugin

runelite-api/src/main/java/net/runelite/api/Varbits.java, runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeRocksOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeSackOverlay.java
The following changes have been done:
* Added red color to the "Pay-dirt in sack" overlay when the number of pay-dirt in sack exceeds or is equal to the max allowed.
* Added "Deposits left" to sack overlay. This shows the number of "inventories" left before the sack will be full. This is colored red when deposits left are 0.
* Removed "You are mining" / "You are not mining" as this could not be shown accurately. This showed "You are not mining" when animation stopped, although the character would continue mining straight after.
* Added isInMLM (region check) to most functions
Screenshots:
=> Motherlode Mine - Sack overlay and region check

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollWorldOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/AnagramClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CipherClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/EmoteClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/FairyRingClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/MapClue.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
Add hint arrows for clue locations, NPCs and GameObjects.
Depends on #1282 
Preview:
=> Add clue hint arrows for clues

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
Add the answer of 5096 for the referee's clue.
Addresses #1455
=> Fix referee cryptic clue

runelite-client/src/main/java/net/runelite/client/plugins/herbiboars/HerbiboarMinimapOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/herbiboars/HerbiboarOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/herbiboars/HerbiboarPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeOverlay.java
=> Set herbiboar and mlm overlays to draw ABOVE_SCENE

runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/Book.java
=> Fix minor spelling error in Kourend Library plugin

runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangePlugin.java
Separated the widget loop into a separate function due to the inventory queries being different.
Partially fixes #863. If someone wants to add trade, it should be easy to add in a similar matter.
=> geplugin: add alt-click to bank items

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/TargetClickboxOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/TargetMinimapOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/Task.java
Resolves #1100
Implements icon suggestions from #1149
=> Add slayer target highlighting

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
It had the wrong config/option set.
=> Fix cat chasing menu entry swap

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
Fixes [Issue#1550](https://github.com/runelite/runelite/issues/1550).
I have also made the solution easier to understand.
=> Fixes easy clue

runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java
=> hiscore: lookup local player on double-click

runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscoreConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java, runelite-client/src/test/java/net/runelite/client/plugins/hiscore/HiscorePanelTest.java
=> Display levels above 99 in the hiscore panel

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/AnagramClue.java
=> cluescrolls: fix confusing solution text for Luthas

runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSpot.java
Added small net fishing spot in Corsair Cove to the fishing plugin.
(I don't mean to spam pull requests, I just keep stumbling across these.)
=> Fishing Plugin: Add Corsair Cove net fishing spot

runescape-api/src/main/java/net/runelite/rs/api/RSFriendManager.java, runescape-client/src/main/java/Client.java, runescape-client/src/main/java/CombatInfo2.java, runescape-client/src/main/java/FriendManager.java, runescape-client/src/main/java/Name.java, runescape-client/src/main/java/Nameable.java, runescape-client/src/main/java/NameableContainer.java, runescape-client/src/main/java/class150.java, runescape-client/src/main/java/class157.java, runescape-client/src/main/java/class298.java, runescape-client/src/main/java/class304.java, runescape-client/src/main/java/class322.java, runescape-client/src/main/java/class36.java
=> Refactoring

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
=> Add object and location to a CrypticClue

runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobe.java, runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerService.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerServiceImpl.java
The Xp globe now has an extra field which displays amount of actions left.
=> Add "Actions left" for Xp globes

runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java, runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
Fix for #1586 
Not completely sure how I deleted the branch but either way the only difference is the removal of the unused variable.
=> Screenshot Kingdom Rewards 

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatChanges.java
Support for this overload was removed for unknown reason, so add it
back.
=> Add back support for regular overload (NMZ)

runelite-client/src/main/java/net/runelite/client/plugins/slayer/Task.java
Adds the Rune and Adamant Dragon using their bars as prospective icon. 
Reference #1713
=> More Slayer Task Icons

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
=> clientui: don't update size if already maximized

runelite-client/src/main/java/net/runelite/client/plugins/notes/NotesPanel.java
Is JEditorPane necessary?
JTextArea change addresses #1824/ #1823.
=> Fix notepad wrap 

runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayUtil.java
=> overlay util: remove white outline on minimap dots

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSpot.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
Closes #1852
Closes #1354
Closes #1859
=> Fishing QoL - Add Sacred Eels/Barehand Fishing

runelite-client/src/main/java/net/runelite/client/plugins/agilityplugin/AgilityConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/agilityplugin/AgilityOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/agilityplugin/AgilityPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/agilityplugin/Obstacles.java
This addresses and implements #1981
=> Add Agility shortcut highlight toggle

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
=> Remove unused imports in ClientUI

runelite-client/src/main/java/net/runelite/client/discord/DiscordService.java, runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordGameEventType.java, runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordState.java
Small step towards realising seth's example from #929. This PR only adds the skill icons.
=> Display skill icons in Discord while training

runelite-client/src/main/java/net/runelite/client/plugins/cerberus/CerberusGhost.java, runelite-client/src/main/java/net/runelite/client/plugins/cerberus/CerberusOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/cerberus/CerberusPlugin.java
Add Cerberus plugin that will show order of ghosts in bottom right
corner.
Preview:
=> Add Cerberus plugin

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
=> clue scroll: Add toggle for hint arrows

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
=> Fix cryptic elite clue: Father Aereck

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
=> Brother Tranquility 'talk-to' & ''transport' option swap

runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java
Matches existing progress bar (look&feel) as xp tracker.
Solution for: "Show percentage until next level in HiScores plugin #2185"
=> Adds skill progress bar to hiscore panel

runelite-api/src/main/java/net/runelite/api/Actor.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPlugin.java, runescape-api/src/main/java/net/runelite/rs/api/RSActor.java
This adds the two following commands to the dev tools plugin:
`::anim` `::gfx`
Either one followed by an integer which represents the animation/graphic ID.
=> Add anim, gfx and logger command to devtools

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
I do not own these items, but these should be the animations for them.
=> Add 3rd Age Axe and 3rd Age Pickaxe animations to Idle Notifier

runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoOverlay.java
=> opponent info: reduce padding size

runelite-client/src/main/java/net/runelite/client/plugins/cerberus/CerberusOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/cerberus/CerberusPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/cerberus/CerberusPluginTest.java
=> Use only southermost ghost wave for cerb plugin

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/MapClue.java
Ref:
https://user-images.githubusercontent.com/2199511/39564619-831fa21a-4ea4-11e8-8867-700e77873eca.png
https://user-images.githubusercontent.com/2199511/39564618-830b4996-4ea4-11e8-91e5-4bf73e1a8117.png
=> Add Elite map clue

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/Varbits.java, runelite-api/src/main/java/net/runelite/api/vars/AccountType.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
This adds a way to get the logged in players account type (normal, ironman, uim, and hcim).
=> Add a way to get AccountType

runelite-client/src/main/java/net/runelite/client/Notifier.java, runelite-client/src/main/java/net/runelite/client/callback/Hooks.java, runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java
- Change the notification mode selection to be dropdown
- Add chat message notification mode that will send game message on
notificiation
- Add screen flash notification that will flash screen for few ticks
Preview:
=> Add 2 new notifications modes (message, flash)

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/AnagramClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
Added anagram clue: MAJORS LAVA BADS AIR
Fixed Dagganoth Kings ladder cryptic clue wording
=> Add missing anagram clue, fix dagganoth king cryptic

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
Including a better description of his location and the closest fairy ring.
=> Update to Solution of speaking to Falo the Bard

runelite-client/src/main/java/net/runelite/client/plugins/bosstimer/Boss.java
Add Deranged archeologist, Kraken, Thermy, and Cerberus.
=> BossTimerPlugin: Add missing bosses

runelite-client/pom.xml
=> Disable filtering on logback.xml

runelite-client/src/main/java/net/runelite/client/plugins/implings/Impling.java, runelite-client/src/main/java/net/runelite/client/plugins/implings/ImplingMinimapOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/implings/ImplingType.java, runelite-client/src/main/java/net/runelite/client/plugins/implings/ImplingsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/implings/ImplingsPlugin.java
remove broken dynamic spawn support
=> impling plugin: use spawn events

runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesOverlay.java
Fix compliation error because of move to new PanelComponent system.
=> Move the xp/hr in globes to new system

runelite-client/src/main/java/net/runelite/client/plugins/attackstyles/AttackStylesOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/blastfurnace/BlastFurnaceOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/cerberus/CerberusOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/AnagramClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CipherClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/EmoteClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/FairyRingClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/MapClue.java, runelite-client/src/main/java/net/runelite/client/plugins/fightcave/FightCaveOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeGemOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeSackOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/WoodcuttingOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesOverlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/BackgroundComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/ComponentConstants.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/LineComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/PanelComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/ProgressBarComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/TextComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/TitleComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/TooltipComponent.java
- Add support for customizable gap and border to PanelComponent
- Properly use/not use paddings
- Remove title property and extract it to separate component
- Remove position property, let user handle the positioning
- Extract common constants to ComponentConstants
- Use lombok.Setter on classes instead of fields
Preview:
=> More customization of component system

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/EmoteClue.java
=> Fix Sinclair Mansion emote clue

runelite-client/src/main/java/net/runelite/client/plugins/hunter/HunterPlugin.java
The player is for some traps 2 squares away when setting up the trap
=> HunterPlugin: Fix deadfall traps

runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/plugins/farmingtracker/FarmingTrackerPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
Fix hiscore panel not being able to load image resources due to relying
on toLowerCase()
=> runelite-client: set default locale to english

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java
This will track the charges of the slayer bracelets and update their counter when they are changed or broken.
Things to add moving forward would be an info box of its own instead of only overlay on items/equipment.
=> Slayer bracelet overlay

runelite-client/src/main/java/net/runelite/client/plugins/fightcave/FightCaveOverlay.java
=> Clear previous image components in fight caves overlay

runelite-client/src/main/java/net/runelite/client/plugins/examine/ExaminePlugin.java
=> Show GE and high alch prices for shop items that are examined

runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/KourendLibraryPlugin.java
The X/Y gets unpacked into the ActionParam and WidgetID now
=> kourendlibrary: Fix for rev 170 menu code

runelite-client/src/main/java/net/runelite/client/plugins/fightcave/FightCaveOverlay.java
Fix resetting of background color of Fight Cave plugin overlay.
=> Reset Fight Cave plugin prayer background color

runelite-client/src/main/java/net/runelite/client/ui/overlay/components/ProgressBarComponent.java
=> Do not floor percentage in progress bars

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java
=> Fix hot cold location south of gnome stronghold

runelite-client/src/main/java/net/runelite/client/plugins/fps/FpsOverlay.java
Adds "fps" after the fps count.
=> Add " fps" after the number of FPS

runescape-api/src/main/java/net/runelite/rs/api/RSVarcs.java, runescape-client/src/main/java/Varcs.java
Removes the collision for `varcs`
=> Rename varc fields

runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java
Reverts runelite/runelite#2681
=> Revert "fix: Hide vanilla raid points box when inside chambers of xeric"

runelite-client/src/main/java/net/runelite/client/plugins/friendnotes/FriendNoteOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/friendnotes/FriendNotesPlugin.java
Did some light maintenance as I was documenting this class. See the commit diffs one-by-one.
=> Friend notes plugin: Add documentation and increase code readability

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
=> Fixed typo in a cryptic clue solution

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_mining.json
Addresses https://github.com/runelite/runelite/issues/2903
Uses the red topaz icon (the same icon used in game)
=> Add Gem rocks to mining calculator plugin

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpStateSingle.java
Cause:
Time til next level relied on xp per hour being divided by 3600
(seconds in an hour). For XP rates under 3600 per hour, this would
result in a divide by zero.
Another bug was that if the time was > 24 hours, it would roll over and say 1 hour remaining for 25 hours more training.
Solution:
Simplify the mathematical expression to not use fractional divisions, use custom string formatting
It appears to work as expected.
Fixes #2984
=> Fix til next level time for low xp amounts

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/JewelleryTeleportLocationData.java, runelite-client/src/main/java/net/runelite/client/plugins/worldmap/JewelleryTeleportPoint.java, runelite-client/src/main/java/net/runelite/client/plugins/worldmap/WorldMapPlugin.java
Fixes trying to load the ItemComposition before items are loaded
Fixes items being called Members Object in f2p worlds
=> WorldMap: Fix jewellery item name loading bugs

runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSpot.java
Added the corsair fishing spot into the fishing plugin
=> Corsair fishing spot overlay

runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java, runelite-client/src/main/java/net/runelite/client/ui/components/IconTextField.java, runelite-client/src/main/java/net/runelite/client/util/SwingUtil.java
Small improvements taken from user feedback. Decided to publish the pr now to keep a organized list of the progress and reports.
**This PR has WIP in the title but is always merge-ready. It is wip as I may add new fixes as user reports come in.**
Current issues this fixes:
Fixes #2989 
Fixes #3042 
Fixes #3044
=> Obsidian redesign tweaks

runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSpot.java
=> Add Burgh de Rott fishing spots to fishing overlays

runelite-client/src/main/java/net/runelite/client/plugins/interfacestyles/InterfaceStylesPlugin.java
=> interfacestyles: Run on game thread

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/EmoteClue.java
**Red ✗** - item is not in inventory and is not equipped
**Yellow ✓** - item is in inventory, but not equipped
**Green ✓** - item is equipped/requirement is fulfilled
**Old:**
=>  emoteclues: display when item is in inventory

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java
=> Fix coordinates for venenatis hot cold clue

runelite-client/src/main/java/net/runelite/client/plugins/demonicgorilla/DemonicGorillaPlugin.java
=> Reset gorillas in demonic gorilla plugin on startup and world hop

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/WorldMapConfig.java
=> Fix world map configuration typos

runelite-client/src/main/java/net/runelite/client/plugins/dailytaskindicators/DailyTasksPlugin.java
Don't have an ironman to test with, but I can't forsee any issues with this small of a change.
Fixes #1116
=> Exclude ironmen from daily herb box notifications

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
Ref: https://user-images.githubusercontent.com/36210845/40563762-e33f888e-605d-11e8-8156-8882f8b0e257.png
Fixes runelite/runelite#3310
=> Fix Grand Tree mushrooms clue

runelite-client/src/main/java/net/runelite/client/plugins/devtools/CameraOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPlugin.java
Adds an overlay for Developer Tools displaying relevant camera position information such as X, Y, Z co-ordinates.
=> dev-tools: Add camera position overlay

runelite-client/src/main/java/net/runelite/client/plugins/devtools/LocationOverlay.java
Adds additional information to the LocationOverlay
=> devtools: Add base, local, and region coordinates to LocationOverlay

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
This PR puts the 'travel' option first for the minecart from GE to Keldagrim.
=> Swap menu entries for minecart travel from GE to Keldagrim

runelite-api/src/main/java/net/runelite/api/Varbits.java, runelite-client/src/main/java/net/runelite/client/plugins/blastfurnace/BlastFurnaceClickBoxOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/blastfurnace/BlastFurnaceConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/blastfurnace/BlastFurnacePlugin.java
This draws clickbox same way that conveyor belt clickbox is currently drawn.
Screenshot:
Fixes #2423
=> Blast Furnace - Draw clickbox on bar dispenser

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java
Now that the XP tracker supports level goals, update min/max value in htmlLabel to max skill experience.
=> XpInfoBox - Increase min/max experience

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
=> Add making wines to idle notifications

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/FairyRingMode.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
=> Update menu swapper to support multiple fairy ring defaults

pom.xml
This will make Lombok work with JDK10.
=> Update Lombok to 1.16.22

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Add option to swap "interact" with "empty" on birdhouses
Fixes #1379
=> Update menu swapper for birdhouses

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_construction.json
This is apparently method for UIM to train construction so it is
probably very useful to have.
Preview:
=> Add Limestone attack stone to skill calc

runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/WorldMapLocationOverlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/worldmap/WorldMapOverlay.java
Enabled through a new button in dev tools. Very useful to find the world coordinates of a map icon or location to add new world map points.
=> Dev-tools: Add location overlay to show world map position

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
Ref: https://camo.githubusercontent.com/feb365d64af8a2e563799ccf40f58f4f70cc3249/68747470733a2f2f692e696d6775722e636f6d2f6532736d3549782e706e67
Fixes runelite/runelite#3506
=> Fix "The hand ain't listening." clue step

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java
=> Fix Dad hot-cold clue hint

README.md
Added hyperlinks to the project layout in the README file for quicker access
=> Add hyperlinks to project layout in README

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerPlugin.java
[Preview](https://user-images.githubusercontent.com/8287750/40848319-db9bb74a-658c-11e8-8831-ad2de9996f64.gif)
=> Add reset others to XpInfoBox right click menu

runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/SkillCalculatorPanel.java
This code was left behind from my last material tab clean-up PR by
mistake, my bad.
=> Remove Skill Calculator unused code

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java, runelite-client/src/main/java/net/runelite/client/ui/ContainableFrame.java
=> Fix remember screen bounds for KEEP_GAME_SIZE

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/AnagramClue.java
Changed "hosptial" to "hospital"
=> Fixed clue scroll typo

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/HouseMode.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Closes issues:
- Menuentryswapper PoH Swapping "Enter" to "Friend's house" instead of "Home" #2027
=> Added Menu Entry Swapper options for house portal.

runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangePlugin.java
Changes text from "GE Offers" to "Grand Exchange"
=> Update tooltip for Grand Exchange panel icon to "Grand Exchange"

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-api/src/main/java/net/runelite/api/Perspective.java, runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/MemorizedNpc.java, runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcSceneOverlay.java
Rebased #2404 to work with the current repository.
Add an option to show respawn location and timer to NPC indicators.
=> Add respawn timer to NPC indicators

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/AnagramClue.java
=> Fix Guard Vemmeldo anagram clue location

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
Requested in Discord & had a previous PR before. Adds the Lunar Spells that are more "afk" to the idle notifications.
=> Adds idles to spells bake pie & string jewlery

runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPlugin.java
- Fix uncommon NPE when logging in
- Don't add disposed NPCs when restarting the plugin
=> Npc indicators fix

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPanel.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
Adds a devtool that lets you enable "Orb of Oculus" mode.
Depends !8
=> runelite-client: add detached camera devtool

runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java
Sorry I completely forgot about this in the first PR
=> Fix JColorChooser text not updating properly

runelite-api/src/main/java/net/runelite/api/ChatMessageType.java, runelite-client/src/main/java/net/runelite/client/chat/ChatMessageManager.java
Add support for ChatMessageType PUBLIC_MOD, which is ID 1
Fixes #3703
=>  [chat-color] Add support for Public Chat from Mods

.github/CONTRIBUTING.md
I just discovered this client today, quite amazing! My java is rusty, but I figured I'd try and find a way to help out.
Here is a small update to `contributing.md` to clarify forking and rebasing against the upstream master. Also a small reference to the great developer's guide in the wiki.
=> Small contributing.md clarification

runelite-client/src/main/java/net/runelite/client/chat/ChatMessageManager.java, runelite-client/src/main/java/net/runelite/client/config/ChatColorConfig.java
I made this change off of issue #3531, it allows users to change friend usernames when they appear in public chat.
=> [Chat Color] Add ability to change public chat friend name color in config

runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerCounter.java, runelite-client/src/main/java/net/runelite/client/plugins/screenmarkers/ScreenMarkerRenderable.java, runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesOverlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/ImageComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/InfoBoxComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/LayoutableRenderableEntity.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/LineComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/PanelComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/ProgressBarComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/TitleComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBox.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBoxManager.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBoxOverlay.java
Add support for configurable infobox sizes
Depends and closes #2874
Closes #1771 and closes #1016 
Preview:
=> Add support for configurable infobox sizes

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java
- When highlight value is set to 0, disable highlight for that particular
configuration.
- Make hidden items color configurable
=> Ground item changes (as requested by people in Discord)

runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayManager.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBoxOverlay.java
Use saveOverlay and null all fields to achieve same result.
Fixes #3799
=> Reduce code duplicity in resetOverlay method, fix overlay saving

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java
=> Change ground items box size from 6 px to 8 px

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_crafting.json
Skill Calculator had incorrect item ids for some items.
=> Fixed item ID for some zenyte and onyx items

runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPlugin.java
=> Prevent NPC tagging from interrupting actions

runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/AbsorptionCounter.java
It's quite hard to read the text on this panel, so I added a tooltip.
https://dl.dropboxusercontent.com/s/55mtsvisjnnolmz/java_2018-06-10_18-58-05.png
=> Add tooltip to absorption panel

runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java, runelite-client/src/main/java/net/runelite/client/config/WarningOnExit.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
Add config option to enable the warning popup when exiting the client (feature requests [910](https://github.com/runelite/runelite/issues/910) and [1544](https://github.com/runelite/runelite/issues/1544))
=> Toggle confirmation on exit

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java
Swap gePrice and haPrice in getHidden and getHighlighted calls
correctly.
=> Fix ground item swapped price values

runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java, runelite-client/src/main/java/net/runelite/client/game/ItemManager.java, runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonSpots.java, runelite-client/src/main/java/net/runelite/client/plugins/cerberus/CerberusPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/dailytaskindicators/DailyTasksPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/hunter/TrapOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/info/JRichTextPane.java, runelite-client/src/main/java/net/runelite/client/plugins/instancemap/InstanceMapOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/kingdomofmiscellania/KingdomCounter.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesPlugin.java, runelite-client/src/main/java/net/runelite/client/ui/components/ComboBoxListRenderer.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBoxManager.java
not sure if this is helpful or not but though id do it anyway
=> small code cleanup

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/EmoteClue.java
=> Fix Slayer Tower emote clue

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java
Fixes runelite/runelite#3858
Fixes runelite/runelite#3866
=> Hot cold clue location fixes

runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/KourendLibraryOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/KourendLibraryPlugin.java
Hides the button to open the Kourend Library Plugin when your not in the region.
=>  kourendlibrary: Hide navbutton when not in the library

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
This is mostly a rebase of #1864 due to inactivity since I would like this feature in the main client ;)
I also updated the help text mentioning that it takes priority over the trade swap and added a comment.
=> Menu Swapper - Add Age/Assignment Swapping

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
#3968
Small addition to chat commands: 
```!clues```  - Number of clues completed, any level
```!clues easy``` - Number of easy clues completed
for all clue levels etc...
These commands can also be toggled the same way ```!lvl``` are toggled.
=> Clue chat commands

runelite-api/src/main/java/net/runelite/api/SpritePixels.java, runelite-client/src/main/java/net/runelite/client/plugins/inventorytags/InventoryTagsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/inventorytags/InventoryTagsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/inventorytags/InventoryTagsPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSSpritePixelsMixin.java
=> Add inventory tagging plugin

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
Small mistake. Reset to correct function call.
=> Clue-chat-command fix: Set to correct function call

runelite-api/src/main/java/net/runelite/api/hooks/Callbacks.java
=> Update documentation for Callbacks interface

runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
=> timers plugin: Create timer for stamina mixes

runelite-client/src/main/java/net/runelite/client/plugins/fightcave/FightCaveOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/fightcave/FightCavePlugin.java
- Replace fixed scheduled hook with AnimationChanged hook to determine
what to pray
- Null current attack when Jad despawns (goes out of view)
Closes #3904
=> Make Fight Cave plugin more accurate

runelite-client/src/main/java/net/runelite/client/config/ChatColorConfig.java
=> chat color: Fix description typo

runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSpot.java
Ref:
https://user-images.githubusercontent.com/2199511/42118923-8fe9e94a-7bf6-11e8-93b2-e51bbce4fbf6.png
https://user-images.githubusercontent.com/2199511/42118912-8c7e82c0-7bf6-11e8-9e07-d429439a73d0.png
https://user-images.githubusercontent.com/2199511/42118914-8c982446-7bf6-11e8-9df6-dab9f2b63b4e.png
https://user-images.githubusercontent.com/2199511/42118915-8cb14e62-7bf6-11e8-864f-718f48afb134.png
https://user-images.githubusercontent.com/2199511/42118916-8cca2964-7bf6-11e8-95ab-2f58d62e6e36.png
https://user-images.githubusercontent.com/2199511/42118917-8ce564e0-7bf6-11e8-800e-821c0443100d.png
https://user-images.githubusercontent.com/2199511/42118918-8d0b1f28-7bf6-11e8-9304-0149ac8ab9b9.png
Fixes runelite/runelite#4091
=> fishing plugin: Add cave eel and slimy eel spots

runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/SkillCalculator.java, runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/UIActionSlot.java
=> skill calculator: Fix combined items with decimals

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/AnagramClue.java
Ref:
https://user-images.githubusercontent.com/2199511/42261249-1dffec80-7f57-11e8-8dfe-11f48d144fbc.png
=> clues: Fix Cap'n Izzy No-Beard anagram clue

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatChanges.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/RangeStatBoost.java
=> itemstats: Add variable healing food

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
Make !clues command in ChatCommandsPlugin respect account for rankings.
=> Make !clues command respect account type

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java
=> clues: Fix SW-of-deserted-keep hot-cold location

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/SkillColor.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpSnapshotTotal.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpWorldType.java
Fixes runelite/runelite#4190
Ref: runelite/runelite#3911 (for visibility changes)
cc: @LeviSchuck
=> Remove WorldClient usages from xp tracker plugin

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
- Added `getvarp` & `setvarp` chat commands
- Changed the existing `getvar` & `setvar` to `getvarb` & `setvarb`
=> Add Varp Commands To Developer Tools

runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerBarOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerPlugin.java
Add optional prayer bar under HP bar to prayer plugin.
Reimplemented from and closes #2549
Preview:
=> Add prayer bar to prayer plugin

runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftPlugin.java
=> Add a notification when a runepouch degrades

runelite-api/src/main/java/net/runelite/api/Varbits.java, runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java
=> xp drop plugin: Move text to use hidden icon's space

runelite-client/src/main/java/net/runelite/client/ui/overlay/components/LineComponent.java
This should correct the calculation when multiple lines appear on the right side. 
Has been tested in some scenarios.
=> Fixed line breaking on right side

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
As this was added to official client, it is now unnecessary.
Closes #4292
=> Remove investigate menu entry swap

runelite-client/src/main/java/net/runelite/client/plugins/farmingtracker/PatchImplementation.java
=> farmingtracker: Fix cactus implementation

cache/src/main/java/net/runelite/cache/definitions/ModelDefinition.java, model-viewer/src/main/java/net/runelite/modelviewer/ModelKey.java, model-viewer/src/main/java/net/runelite/modelviewer/ModelManager.java, model-viewer/src/main/java/net/runelite/modelviewer/ModelViewer.java, model-viewer/src/main/java/net/runelite/modelviewer/Scene.java, model-viewer/src/main/java/net/runelite/modelviewer/SceneTilePaint.java
-Fixed objects of variable width and length from being positioned incorrectly on the map.
-Renamed LocationKey to ModelKey and added another field so that cached values are correct for objects using the same models.
-Implemented shading to the scene.
-Implement full SceneTilePaint with variable colors and textures.
-Implement textures while rendering SceneTileModel
-Enable maps to be loaded by their region id instead of just their coordinates.
-Implement full object model creation (replacement colors, replacement textures, resizing, translation)
-Added two new methods to ModelDefinition used in object model creation.
=> Model Viewer Improvements and Additions

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CipherClue.java
Add fairy ring information to cipher clue with King Percival
=> Add fairy ring information to King Percival clue #4344

runelite-client/src/main/java/net/runelite/client/util/Text.java, runelite-client/src/test/java/net/runelite/client/util/TextTest.java
=> text: Fix removeTags for isolated < and > chars

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_construction.json
Adds Mounted Mythical Cape
Fixes 'Teak Table' @ level 52 -> 'Teak Kitchen Table'
Fixes #4335 
Fixes #4317
=> Skill calc additions

runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java, runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/screenshot/ScreenshotPluginTest.java
Add support for taking screenshots of theatre of blood rewards
Relies on #4245
=> Tob screenshots

runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java, runelite-client/src/main/java/net/runelite/client/plugins/timers/TimerTimer.java, runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
=> timers plugin: Reduce visibilities

runelite-mixins/src/main/java/net/runelite/mixins/RSTileMixin.java
=> Remove unused import from RSTileMixin

runelite-client/src/main/java/net/runelite/client/plugins/puzzlesolver/VarrockMuseumAnswer.java
Fix spaces in camels type answer in VarrockMusuem quiz solver.
=> Fix camels type in varrock museum quiz

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
Fixes #4389 by renaming "Blue Moon Inn" to "Bartender"
=> Renaming NPC from Blue Moon Inn to Bartender

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
=> Add chat kc abbreviations #4369

runelite-client/src/main/java/net/runelite/client/plugins/inventoryviewer/InventoryViewerOverlay.java
=> Inventory viewer: make padding between items same as in inventory.

runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java, runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
Add Abyssal Sire stun countdown to Timers plugin. Closes #4132.
=> Abyssal Sire Stun Countdown

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/MapClue.java
The world map is nearly useless if the point is not on the "RuneScape Surface"
=> cluescrolls: Add description to map clues

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
Update resizable only when it is really changed as it messes up window
sometimes if fullscreen
=> Update frame config when needed

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/EmoteClue.java
=> clues: Fix menaphite emote requirements

runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/MorytaniaDiaryRequirement.java
=> achievement diary plugin: Fix Abyssal demon req

runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSpotOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/MinnowSpot.java
Added an option to display time remaining before minnow fishing spot changes. Also changes colour of fishing spot before the change.
=> fishing plugin: add minnows overlay

runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java
=> TimerPlugin: Fix prayer enhance length

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
Added missing config for the killcount chat command.
=> Added missing killcount command config

runelite-api/src/main/java/net/runelite/api/Perspective.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayUtil.java
Fix null pointer exceptions when trying to draw null names on screen.
=> Fix NPE when trying to draw null names

runelite-client/src/main/java/net/runelite/client/RuneLite.java
=> Add simple info log with startup time

runelite-mixins/src/main/java/net/runelite/mixins/TileObjectMixin.java
=> Account for plane in TileObject canvas location

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/FairyRingClue.java
=> Add spade requirement reminder to fairy ring clues

runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerBarOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerFlickLocation.java, runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerFlickOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerPlugin.java
Depends on: #3879 
Adds support to toggle the Prayer Flick Helper between:
Prayer Orb
Prayer Bar
Both
None (Off)
=> Add prayer bar flick

runelite-client/src/test/java/net/runelite/client/ui/FontManagerTest.java
=> Fix FontManagerTest package

runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
=> Fixes issue with no Idle Notification when crafting leather

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPanel.java
It doesn't only track kills, but also clues and raids completions
=> Clarify wording of default message

runelite-api/src/main/java/net/runelite/api/InventoryID.java
Thank you Polar for finding the correct ID
Fixes #4603 
@deathbeam Screenshot of ToB loot tracker https://i.imgur.com/bHT7E3C.png
=> Fix ToB inventoryID

runelite-client/src/main/java/net/runelite/client/callback/ClientThread.java, runelite-client/src/main/java/net/runelite/client/chat/CommandManager.java, runelite-client/src/main/java/net/runelite/client/game/ChatboxInputManager.java, runelite-client/src/main/java/net/runelite/client/game/ItemManager.java, runelite-client/src/main/java/net/runelite/client/game/SpriteManager.java, runelite-client/src/main/java/net/runelite/client/plugins/attackstyles/AttackStylesPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatKeyboardListener.java, runelite-client/src/main/java/net/runelite/client/plugins/demonicgorilla/DemonicGorillaPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/fairyring/FairyRingPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/interfacestyles/InterfaceStylesPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/reportbutton/ReportButtonPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java
Its amazing that this ever worked, and that I didn't think that even though the other callback breaks that this one might too.
=> Prevent crash when updating the fairy ring filter

runelite-client/src/main/java/net/runelite/client/plugins/agility/Obstacles.java
Ref:
https://user-images.githubusercontent.com/2199511/43506201-e027cfaa-9558-11e8-89f7-f0efbabcdc8f.png
https://user-images.githubusercontent.com/2199511/43506202-e043a72a-9558-11e8-984a-5fd9214e889d.png
https://user-images.githubusercontent.com/2199511/43506203-e05d3dc0-9558-11e8-852d-1cf06b99f29d.png
https://user-images.githubusercontent.com/2199511/43506204-e0751c24-9558-11e8-9e33-19ec490b4edb.png
https://user-images.githubusercontent.com/2199511/43506638-2e190156-955a-11e8-90fe-80fa28603b6e.png
https://user-images.githubusercontent.com/2199511/43506639-2e30a040-955a-11e8-8fee-54882adb2f80.png
https://user-images.githubusercontent.com/2199511/43506640-2e4a1a02-955a-11e8-8e72-65742dd776ca.png
Fixes runelite/runelite#2629
=> agility: Add Ungael obstacles

runelite-client/src/main/java/net/runelite/client/plugins/instancemap/InstanceMapPlugin.java
=> instance map: properly remove mouse listener on shutdown

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
=> fix menu entry swapper shiftModifier getting stuck on focus lost

runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsTileOverlay.java
=> player indicators: draw tile highlight on ABOVE_SCENE layer

runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/KandarinDiaryRequirement.java
=> achievement diary plugin: Fix coal mining req

runelite-client/src/main/java/net/runelite/client/plugins/chathistory/ChatHistoryPlugin.java
=> chat history: clear public chat when menu option is clicked

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/FairyRingMode.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
=> menu entry swapper: fix fairy ring swaps not working for zanaris ring, arceuus ring and PoH tree-ring combo

runelite-mixins/src/main/java/net/runelite/mixins/CameraMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
=> mixins: Fix camera pitch relaxer not fully relaxing after a screen shake

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
Add a command showing the combat level and combat related stats similar to osbuddy
=> chat commands: add !cmb command

runelite-client/src/main/java/net/runelite/client/plugins/deathindicator/DeathIndicatorPlugin.java
Switches death check from AnimationChanged event to LocalPlayerDeath event.
=> Optimize death indicator plugin

runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java
=> Add support for preserving raids scouter inside raid + fix checking for raids state on plugin state changes

runelite-client/src/main/java/net/runelite/client/game/ItemManager.java, runelite-client/src/main/java/net/runelite/client/plugins/bankvalue/BankCalculation.java, runelite-client/src/main/java/net/runelite/client/plugins/barrows/BarrowsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/examine/ExaminePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeSearchPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/itemprices/ItemPricesOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
=> runelite-client: Always use the mapped price for items

runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordGameEventType.java
Adds Wintertodt to the "Discord" Plugin.
Closes #4812
=> DiscordPlugin: Add Wintertodt to Activities

runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java
Fix adding timer multiple times when you change option while inside
raids.
Fixes #4808
=> Fix adding of raid timer multiple times in Raids

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CipherClue.java
=> Cluescrolls: Added fairy ring code to Kalphite Lair Entrance clue

runelite-client/src/main/java/net/runelite/client/game/LootManager.java
=> Add Grotesque Guardian special case to loot tracker

runelite-client/src/main/java/net/runelite/client/plugins/agility/Obstacles.java
Adds the Lumber Yard fence by Varrock.
Closes #4860
=> Add Lumber Yard Fence to Agility Plugin

runelite-client/src/main/java/net/runelite/client/plugins/fps/FpsOverlay.java
**Before:**
**After:**
Fixes #2544 
Fixes #3086
=> Fps indicator improvements

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
=> clues: add fairy ring to sinclair mansion clue solution

runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldHopperPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldSwitcherPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldTableHeader.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldTableRow.java
Features introduced:
- Updating the highlighted current world on world hop
- Refresh menu option on the list headers
- 10 minute refresh timer
- Loading world data from ingame widgets
=> World hopper data refreshing

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
=> Add "Fairy Ring CKS" to Ulizius clue

runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldHopperPlugin.java
Makes it retry 3 times before it gives up.
=> worldhopper: fix spam in chatbox when trying to open switcher in bank

runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPlugin.java
Useful for getting accurate boss respawn timers
=> Add debugging to npc highlighter plugin

runelite-client/src/main/java/net/runelite/client/plugins/timetracking/clocks/ClockPanel.java
Fixes #4921 
- Tries to parse the input using the ISO-8601 Durations format if it contains either `h`, `m` or `s`, else it defaults to the `hh:mm:ss` logic
- Supports notations like:
- 1h 30m 20s
- 1h30m20s
- 3000s
- Does **not** support notations like:
- 20s 20m
=> TimeTracking: Add support for intuitive time notations like "1h 30m 10s"

runelite-client/src/main/java/net/runelite/client/plugins/agility/Obstacles.java
=> Added agility shortcut (North River Salve)

runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
Takes a screenshot if boss is killed (default disabled)
Closes #5010
=> Added boss skill screenshots

runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
Change it to use the same formatting used for raids 1/2 and barrows
=> Change boss kill screenshot naming

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java
=> Fix Hot/Cold Nardah Genie Cave tile

runelite-client/src/main/java/net/runelite/client/plugins/timetracking/OverviewTabPanel.java
=> Add special patches to overview tab

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerPlugin.java
=> Add pause all button to xp tracker

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/chatcommands/ChatCommandsPluginTest.java
=> Fix setting of barrows kc from chat

runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldHopperPlugin.java
This implements feature-request #5121, the Hop-To option is added before the Report option in chat.
=> Add Hop-To option in chat

runelite-api/src/main/java/net/runelite/api/GameEngine.java, runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/plugins/PluginManager.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java, runescape-api/src/main/java/net/runelite/rs/api/RSGameEngine.java
- Properly shutdown applet on window close
- Properly remove system tray icon on close
- Shutdown executorService on shutdown
- Stop all plugins on shutdown
=> Properly shutdown everything on window close

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
=> Add trade-with swap to menu entry swapper

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
Add chipping animation used when mining dense essence
Fixes #836
=> Fix dense essence idle animation

runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPluginTest.java
The idle logout timer is 20 min instead of 5 min when in combat
=> Fix in combat idle logout notification and add config option for notification

runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java
This makes cannon spot overlays show only when cannon is present in
player inventory.
Closes #1092
=> Show cannon spot overlay only with cannon

runelite-api/src/main/java/net/runelite/api/widgets/Widget.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/WidgetInfoTableModel.java, runescape-api/src/main/java/net/runelite/rs/api/RSWidget.java
adds setter method for itemId on widgets
=> Widgets: add setItemId

runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayBounds.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayPosition.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayUtil.java
=> Add TOP_CENTER snap corner to snap center viewport

runelite-api/src/main/java/net/runelite/api/widgets/Widget.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/WidgetInfoTableModel.java, runescape-api/src/main/java/net/runelite/rs/api/RSWidget.java
used to make text not look flat
=> widget: expose text shadowed

runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargeConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargeOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargeType.java, runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemWithCharge.java
=> Add item charges display for ogre bellows

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
=> Add Sacred Eeels cutting to idle notifier

runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingWorld.java
Adds the new Weiss herb patch unlocked by the new quest Making Friends with My Arm to the time tracking plugin.
=> Add Weiss herb patch to the farming tracker

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/EmoteClue.java
=> clue scroll plugin: Check for sets across inventory and equipment

runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
Add Quest to quest screenshots so all screenshots of quest completions are grouped
=> Add Quest to quest screenshots

runelite-client/src/main/java/net/runelite/client/plugins/timetracking/OverviewTabPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/timetracking/Tab.java
Timers -> Birdhouses -> Herbs -> Trees -> Special (for seaweed) ->
Flowers (because of recent buff) -> Bushes (whiteberries) -> Grapes
(wine of zammy?) -> Hops
=> Reorder time tracker tabs by priority

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/MinigameLocation.java, runelite-client/src/main/java/net/runelite/client/plugins/worldmap/MinigamePoint.java, runelite-client/src/main/java/net/runelite/client/plugins/worldmap/WorldMapConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/worldmap/WorldMapPlugin.java
Add tooltip showing the name of the minigame on the worldmap
=> WorldMapPlugin: Add tooltip to minigame icons

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java
Closes #5424
Moved dig location 3 tiles east into correct hot-cold dig range.
=> Moved hot-cold dig location 3 tiles east into the correct range.

runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSpot.java
=> fishing plugin: Add Dark Crab fishing spots

runescape-api/src/main/java/net/runelite/rs/api/RSRenderOverview.java
=> runescape-api: Update setWorldMapPositionTarget's name

http-api/pom.xml, http-api/src/main/java/net/runelite/http/api/hiscore/HiscoreClient.java, http-api/src/main/java/net/runelite/http/api/hiscore/HiscoreResultBuilder.java, http-service/pom.xml, http-service/src/main/java/net/runelite/http/service/hiscore/HiscoreController.java, http-service/src/main/java/net/runelite/http/service/hiscore/HiscoreKey.java, http-service/src/main/java/net/runelite/http/service/hiscore/HiscoreService.java, http-service/src/main/java/net/runelite/http/service/xp/XpTrackerService.java, http-service/src/test/java/net/runelite/http/service/hiscore/HiscoreServiceTest.java, http-service/src/test/java/net/runelite/http/service/hiscore/HiscoreTestService.java
=> Make HiscoreClient call the OSRS hiscore API directly

runelite-client/src/main/java/net/runelite/client/game/LootManager.java, runelite-mixins/src/main/java/net/runelite/mixins/RSTileMixin.java
=> Centralize item (de)spawn log messages

runelite-api/src/main/java/net/runelite/api/Varbits.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingPlugin.java
Implements the first part of #5272
=> Add notification for low fishing trawler activity

runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSpotMinimapOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSpotOverlay.java
Add option for displaying only last fished fish's fishing spot.
Closes #5488
=> Add option for displaying only last fished fish

runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSpotOverlay.java
- Add separate config option to display fishing spot tiles
- Add separate config option to display fishing spot names
- Make config option to display fishing spot icons be independant of
fishing spot names
Closes #781
=> Add fishing spot display configuration

runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/BonusCheckBox.java, runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/SkillCalculator.java
=> Change skill calc checkboxes to radio buttons

runelite-client/src/main/java/net/runelite/client/plugins/entityhider/EntityHiderPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/EntityHiderMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
Fixes #1979 
Only works internally until it's merged.
Result: https://gfycat.com/EverlastingLargeAlbino
=> entityhider: make hidden entities not occupy the tile they're on

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-client/src/main/java/net/runelite/client/plugins/wintertodt/WintertodtActivity.java, runelite-client/src/main/java/net/runelite/client/plugins/wintertodt/WintertodtConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/wintertodt/WintertodtInterruptType.java, runelite-client/src/main/java/net/runelite/client/plugins/wintertodt/WintertodtOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/wintertodt/WintertodtPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/wintertodt/config/WintertodtNotifyMode.java
Co-authored-by: Jason <jbfleischman@gmail.com>
=> Add Wintertodt Plugin

runelite-api/src/main/java/net/runelite/api/Client.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
This reverts commit abb28ca5fbd359d8fa2d4c67bbd4952b453304bd.
These methods don't do what they say and what they actually do isn't
useful
=> Revert "Add camera setters to Client.java and RSClient.java."

runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/SceneOverlay.java
https://puu.sh/BcLPs/032089b2be.mp4
=> devtools: Add Interacting arrow devtool

runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerBarOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerFlickOverlay.java
Closes #962
Useful when doing tick manipulation activities other than prayer flicking
=> Add option to always show prayer flick helper

runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangePlugin.java
- Remove last item ID checks completely and simply update the widget
text with OSB actively traded price whenever the widget do not contains
any
- Properly reset grandExchangeText and grandExchangeItem widgets on
plugin shutdown
Fixes #5098
Closes #5158
=> Fix GE OSB actively traded price races

runelite-client/src/main/java/net/runelite/client/plugins/notes/NotesPanel.java
Resolved #5543 feature request
Preview: https://gyazo.com/1d96c7a33e5897a4120d9218337abeec
=> Add Undo Redo support for the Note plugin

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java
Hot/cold location North-eastern part of the Kharazi Jungle is off
Closes #5586
=> Changed the WorldPoint of KARMAJA_KHARAZI_NE to x = 2908, y =2922

runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/SkillCalculator.java, runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/SkillCalculatorPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/SkillCalculatorPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/UIActionSlot.java, runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/UICalculatorInputArea.java, runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/UICombinedActionSlot.java
=> Cleanup skill calculator

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java
=> Hot/Cold clue West of Brimhaven location fix

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java
=> Hot/Cold clue near Fishing tutor location fix

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java
Ref: https://user-images.githubusercontent.com/2199511/45984305-f9c22600-c04f-11e8-8cda-a8f4ab40e678.png
=> slayer plugin: Add parsing for boss task assignments

runelite-client/src/main/java/net/runelite/client/plugins/instancemap/InstanceMapInputListener.java, runelite-client/src/main/java/net/runelite/client/plugins/instancemap/InstanceMapOverlay.java
Adds a button at the top right of the instance map for closing the map.
=> instancemap: add 'X' button on the interface to close map

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
Fixes https://github.com/runelite/runelite/issues/4387
=> Lady of the lake clue scroll rename

runelite-client/src/main/java/net/runelite/client/plugins/agility/Obstacles.java
Not much else to say,
fixes https://github.com/runelite/runelite/issues/5356
=> Add little boulder from weiss into agility obstacles

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_crafting.json
=> Add leather shields to the crafting calculator #4326

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_herblore.json
=> Add Tar to the Herblore Skill calculator

runelite-client/src/main/java/net/runelite/client/plugins/agility/Obstacles.java
Fixes https://github.com/runelite/runelite/issues/5701
=> Added mcgrubor woods railing to agility plugin

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_herblore.json
fixes https://github.com/runelite/runelite/issues/5689
=> Added super antifire to skill calculator

runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/KaramjaDiaryRequirement.java
Fixes https://github.com/runelite/runelite/issues/5688
=> Fixed a achievement diary requirement mistake

runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonSpots.java
=> Use more optimal location for Jatizso Ice Trolls cannon spot

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java
=> Update location for terrorchick cage hot/cold

runelite-client/src/main/java/net/runelite/client/plugins/corp/CorpConfig.java
=> corp plugin: Fix settings description typo

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
fixes https://github.com/runelite/runelite/issues/5691
=> Add location for Salty Peter clue scroll

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
=> Add sand collection to idle notifier

runelite-client/src/main/java/net/runelite/client/plugins/blastfurnace/BlastFurnaceClickBoxOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/blastfurnace/BlastFurnaceCofferOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/blastfurnace/BlastFurnacePlugin.java
- Fix BlastFurnace overlay constructor modifiers
- Fix BlastFurnace plugin subsriber method names
See also #3911
=> Fix BlastFurnace access levels and subscriber names

runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
Fix access modifiers for classes, methods and ctors in ScreenshotPlugin
See also #3911
=> Fix screenshot plugin access levels

runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/Boss.java, runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialCounter.java, runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialCounterPlugin.java
- Fix special attack counter plugin access modifiers
- Fix special attack counter plugin subscriber method names
See also #3911
=> Fix special counter access levels and subscriber names

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/MapClue.java
Closes https://github.com/runelite/runelite/issues/5659
=> Require spade on map dig clues

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java
Fixes https://github.com/runelite/runelite/issues/5687
=> Add support for parsing Wilderness assignment updates to slayer plugin

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerBox.java
This reverts commit 78e6dee8d05c74d585a1cce887c181d5496eadc5.
#5673 should be re-opened when this is merged.
=> Revert "Truncate NPC name instead of subtitle in Loot Tracker (#5740)"

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java
Addresses changes requested in #5777 
Adds support for slayer tasks from a partner
Closes #5777
=> Partner support for slayer plugin

runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZoneConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZonePlugin.java
Closes #5787 
Makes sense to have native support for it in the NMZ plugin rather than having to purposely use another plugin (chat notification etc)
=> Add ultimate force notification trigger to NMZ Plugin

runelite-client/src/main/java/net/runelite/client/plugins/bankvalue/BankValuePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/WidgetInfoTableModel.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/WidgetInspector.java, runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodePlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSWidgetMixin.java
=> Run unsafe widget accesses on client thread

runelite-client/src/main/java/net/runelite/client/plugins/fairyring/FairyRingPlugin.java
=> fairyring: Don't loose scroll position

runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java
=> Fix Raids plugin varbit access not happening on client thread

runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostIndicator.java, runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsOverlay.java
=> Add support for making the boost colour yellow if below boost threshold

runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoOverlay.java
https://github.com/runelite/runelite/pull/2509 appears to be stale.
Rebase of it. 
Closes #58
Closes #2509
=> More accurate NPC hp overlay when max hp is known

runelite-client/src/main/java/net/runelite/client/plugins/attackstyles/AttackStylesPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/barrows/BarrowsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/config/PluginListItem.java, runelite-client/src/main/java/net/runelite/client/plugins/demonicgorilla/DemonicGorillaPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/fightcave/FightCavePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/interfacestyles/InterfaceStylesPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java
=> Add additional search tags for interface styles and pvm plugins

runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java
Variable is never used (it's a duplicate of allRank)
=> Removing unused variable

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java
- Move map clue checking to ItemContainerChanged
- Use NpcSpawned/Despawned events for checking clue NPC
- Move clue inventory/equipment assignment to ItemContainerChanged 
- Fix bug with single object clue scrolls not being highlighted
Closes #4607
=> Optimize clue scrolls

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpSnapshotSingle.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpStateSingle.java
Increased XP accuracy in tracker to 2 decimal places.
=> Increase XP tracker accuracy to 2 decimal places

runelite-client/src/main/java/net/runelite/client/plugins/examine/ExaminePlugin.java
=> Fix examine text for stackable untradables to not show a GE value 

http-api/src/main/java/net/runelite/http/api/item/ItemPrice.java, http-service/src/main/java/net/runelite/http/service/item/ItemController.java, http-service/src/main/java/net/runelite/http/service/item/ItemEntry.java, http-service/src/main/java/net/runelite/http/service/item/ItemService.java, http-service/src/main/java/net/runelite/http/service/item/PriceEntry.java, runelite-client/src/main/java/net/runelite/client/game/ItemManager.java, runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeSearchPanel.java
Fixes assertion failure introduced in b72bda1c7568f383715dc078d1affb752317fa9a
Closes #1338
=> Move item search client side

runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java
=> Use TAG_SEARCH const instead of hardcoding "tag:" in Bank Tags

runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java
Closes #5913 
Supersedes / closes #5914 
=> Properly reset search when deleting active tag tab

runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java
Closes https://github.com/runelite/runelite/issues/5927
=> Fix spellbook widget ids

runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsOverlay.java
=> Fix raid scout overlay not rendering at bank

runelite-client/src/main/java/net/runelite/client/plugins/timetracking/OverviewTabPanel.java
=> Remove duplicate "Patches" from time track overview

runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangePlugin.java
=> Fix OSB price duplication on delayed lookup

runelite-client/src/main/scripts/BankSearchFilter.rs2asm, runelite-client/src/main/scripts/BankSearchLayout.rs2asm
=> Don't limit bank search and title explicitly to 15 characters

runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TimeTrackingPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java
=> time tracking: Remove deprecated config migration

runelite-client/src/main/java/net/runelite/client/plugins/banktags/BankTagsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java
=> Add option to remember last opened tag tab

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/Task.java
=> Fix cave kraken boss task name

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
=> Properly reorder menu entry config & add swaps for quick pass/travel/start

runelite-client/src/main/java/net/runelite/client/ui/overlay/WidgetOverlay.java
Add limiting of widget overlay bounds to parent bounds in order to not
get out of sync with actual overlay position and drawn overlay position.
Fixes stuff like this:
=> Limit widget overlay bounds to parent

runelite-client/src/main/java/net/runelite/client/chat/ChatMessageManager.java
added PRIVATE_MESSAGE_RECEIVED_MOD to case statement fall through
=> Fix for #5938 - PM chat recoloring do not works for pmods/jmods

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java
=> slayer: Add combat bracelet task update handling

runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordGameEventType.java
Adds Motherlode Mine to the "Discord" plugin.
Closes #4222
=> DiscordPlugin: Add MLM

runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordAreaType.java, runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordGameEventType.java, runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordPlugin.java
- Add support for Varbit triggers to Discord plugin
- Add Chambers Of Xeric and Theatre of Blood to Discord plugin
- Put these two to separate category because according to wiki they are
separate
Closes #4223
Closes #4224
=> Add raiding activity to Discord plugin

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Remove the switch case for swapQuick as any swapping that comes later in the else if chain is broken
=> Remove switch case for swapQuick

runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
=> Add option to choose interface (layoutable) overlay font

runelite-client/src/main/java/net/runelite/client/plugins/banktags/TagManager.java, runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java
cleanup code from https://github.com/runelite/runelite/pull/5988
=> Tag tabs: Add to existing tags instead of overwriting them from inv/eq

runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
Closes #1918
Closes #1952
Preview:
=> Add toggle for displaying username in title

runelite-client/src/main/java/net/runelite/client/plugins/banktags/TagManager.java, runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java
=> Add ability to import/export tag tabs with clipboard

runelite-client/src/main/java/net/runelite/client/util/GameEventManager.java
=> Invoke GameEventManager events on ClientThread

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java
=> Clear hint arrow when switching 3 step NPCs

runelite-client/src/main/java/net/runelite/client/plugins/banktags/BankTagsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java
=> Update active tag tab containing edited tag

runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java
=> Filter > 0 when tagging inventory/equipment

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
* new final int for `AnimationID`: `FARMING_MIX_ULTRACOMPOST`
* add case for idle notification's animationChanged method
Closes #6051
=> Add idle notification for mixing ultracompost

runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/Boss.java, runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialCounterPlugin.java
=> Make special attack counter respect ids and npc deaths

runelite-client/src/main/java/net/runelite/client/plugins/banktags/BankTagsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/banktags/TagManager.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollService.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollServiceImpl.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/emote/AllRequirementsCollection.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/emote/AnyRequirementCollection.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/emote/ItemRequirement.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/emote/RangeItemRequirement.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/emote/SingleItemRequirement.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/emote/SlotLimitationRequirement.java
Closes https://github.com/runelite/runelite/issues/5436
=> Bank tags: Search current clue items

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-client/src/main/java/net/runelite/client/plugins/poh/BurnerOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/poh/IncenseBurner.java, runelite-client/src/main/java/net/runelite/client/plugins/poh/PohConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/poh/PohPlugin.java
Credit to the original PR author of #5179 who has now deleted their Github account.
Closes #5179 
Closes #4679 
I have gone through the code submitted on the original PR and looked at previous comments. Please review again to catch anything previously not seen and I will maintain the PR.
=> Add Poh Burner timers

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-client/src/main/java/net/runelite/client/plugins/poh/BurnerOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/poh/IncenseBurner.java, runelite-client/src/main/java/net/runelite/client/plugins/poh/PohConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/poh/PohPlugin.java
=> Add POH incense burner timers

runelite-client/src/main/java/net/runelite/client/plugins/mta/alchemy/AlchemyRoom.java
distanceTo already returns 'int'
=> Remove pointless int cast

runelite-client/src/main/java/net/runelite/client/plugins/banktags/BankTagsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java
=> Prevent tag tab scrolling to scroll bank interface

runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePlugin.java
It is super annoying to accidentally have left-click option on stuff
that never has one.
Closes #3759
=> Make HiScore lookup always deprioritized

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
=> Add missing dot to "She's small" cryptic

runelite-client/src/main/java/net/runelite/client/plugins/agility/Obstacles.java
Screenshot of the rocks: https://gyazo.com/3990d3aaef34c4fab3f0282f1ab2bb5c
=> Added tears of guthix rock obstacle to agility obstacles

runelite-client/src/main/java/net/runelite/client/plugins/mta/telekinetic/TelekineticRoom.java
=> mta telekinetic room: Fix finish point comparison

runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanChatPlugin.java, runelite-client/src/main/java/net/runelite/client/util/Text.java
Closes https://github.com/runelite/runelite/issues/6069
=> Force clan chat names to a specific format

runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityPlugin.java
=> Agility plugin: highlight multiple marks

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerBox.java, runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPanel.java
=> Optimize Loottracker

runelite-client/src/main/java/net/runelite/client/game/chatbox/ChatboxTextInput.java, runelite-client/src/main/java/net/runelite/client/game/chatbox/ChatboxTextMenuInput.java
=> Various ChatboxPanelManager fixes

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
=> Removed Ardougne cloak from the menu entry swapper plugin

runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesOverlay.java
=> XPglobes: capitalize XP in globe tooltip

runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersConfig.java
=> Add consistency to capitalization of timer in Timers settings

runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargeConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargeOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargeType.java, runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemWithCharge.java
=> Item Charges: add Abyssal Bracelet charge tracking

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Co-authored-by: thesnell <hcimsnell@gmail.com>
=> Swap "Perks" option with "Admire" for mounted max cape

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/TeleportLocationData.java
=> #6217 Fixed Aisle to Isle

runelite-api/src/main/java/net/runelite/api/ObjectComposition.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/AnagramClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/MapClue.java, runescape-api/src/main/java/net/runelite/rs/api/RSObjectComposition.java
Fixes #6053 
Depends on and closes #6171
=> Add support for objects to anagram clues

runelite-client/src/main/java/net/runelite/client/plugins/twitch/TwitchPlugin.java
=> #6200 Fixes issue with twitch channel string being case-sensitive

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java
=> Update Hot/Cold location NW of fishing tutor

runelite-api/src/main/java/net/runelite/api/Hitsplat.java
https://i.imgur.com/q4r8kc5.png
=> Fix hitsplat colours

runelite-client/src/main/java/net/runelite/client/Notifier.java
=> Use ChatMessageManager to send game messages in Notifier

runelite-client/src/main/java/net/runelite/client/plugins/banktags/TagManager.java
Closes https://github.com/runelite/runelite/issues/6297
=> Bank tags: tag search should be startsWith not contains

runelite-client/src/main/java/net/runelite/client/plugins/inventorytags/InventoryTagsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
=> Update Inventory tags plugin to use MenuManager

cache/src/main/java/net/runelite/cache/definitions/loaders/LocationsLoader.java, cache/src/main/java/net/runelite/cache/io/InputStream.java
I guess this changed when they hit the 32k object limit.
=> cache: Correct Location loading

runelite-client/src/main/java/net/runelite/client/plugins/twitch/TwitchPlugin.java
=> Make Twitch messages respect custom Chat Colours

runelite-client/src/main/java/net/runelite/client/callback/Hooks.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java, runelite-client/src/main/java/net/runelite/client/util/SwingUtil.java
Draw hide/show sidebar button in top-right corner using Game's draw
hook. This will not work in Vanilla and so it is disabled in it.
This is extracted from #2872
=> Add support for hiding/showing sidebar button with custom chrome disabled

runelite-client/src/main/java/net/runelite/client/chat/ChatMessageManager.java, runelite-client/src/main/java/net/runelite/client/config/ChatColorConfig.java, runelite-client/src/main/java/net/runelite/client/menus/WidgetMenuOption.java, runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/wasdcamera/WASDCameraPlugin.java, runelite-client/src/main/java/net/runelite/client/ui/JagexColors.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/worldmap/WorldMapOverlay.java
=> Add Jagex Colors constants and fix WASD camera chat text color

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatChanges.java
Added range of 5-7 hp for Thin Snail Meat.
Added range of 7-9 hp for Fat Snail Meat.
Closes #6332
=> Added food hover overlay for Thin and Fat Snail meat

runelite-api/src/main/java/net/runelite/api/ScriptEvent.java, runelite-client/src/main/java/net/runelite/client/plugins/banktags/BankTagsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/BankSearch.java, runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/MenuIndexes.java, runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java, runescape-api/src/main/java/net/runelite/rs/api/RSScriptEvent.java
Closes https://github.com/runelite/runelite/issues/5892
Closes https://github.com/runelite/runelite/issues/1297
Closes https://github.com/runelite/runelite/issues/1394
=> Bank Tags: refactor to use new ChatboxPanelManager

runelite-client/src/main/java/net/runelite/client/plugins/agility/Obstacles.java
=> Added Burgh de Rott shortcut to agility plugin

runelite-api/src/main/java/net/runelite/api/EquipmentInventorySlot.java
=> Add AMMO(13) to EquipmentInventorySlot

runelite-client/src/main/java/net/runelite/client/plugins/agility/Obstacles.java
=> Added skeletal wyvern stairs to agility shortcut plugin

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpState.java
=> Check if any experience was gained in skill before tracking action

runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostIndicator.java
=> Make boost overlay to change to yellow at threshold 

runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
=> Prevent overlays from moving off-screen

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
title
before: https://i.imgur.com/kvXHHWd.png
after: https://i.imgur.com/anFnVkt.png
=> Do not swap entries on NPCs with hint arrows

runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpActionType.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerService.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerServiceImpl.java
=> Add support for kills left in xp orbs

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_smithing.json
There were some incorrect values in the Smithing calculator.
Source: http://oldschoolrunescape.wikia.com/wiki/Smithing
Fixes #6334
=> Fix some xp values in skill_smithing.json

runelite-api/src/main/java/net/runelite/api/IconID.java, runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/wasdcamera/WASDCameraPlugin.java
Has a nice side effect of not requiring input to show the icon when the chat unlocks
Before:
After:
=> wasdplugin: Show Ironman Icons when chat is locked

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/FairyRingLocation.java
The original issue was [here](https://github.com/runelite/runelite/issues/6516)
=> Removed fairy ring location BJQ

runelite-client/pom.xml, runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java
=> Fix GPU rendering on Linux

runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java, runelite-client/src/main/resources/net/runelite/client/plugins/gpu/common.glsl, runelite-client/src/main/resources/net/runelite/client/plugins/gpu/comp.glsl, runelite-client/src/main/resources/net/runelite/client/plugins/gpu/comp_small.glsl, runelite-client/src/main/resources/net/runelite/client/plugins/gpu/geom.glsl
=> Fix black lines on intel

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_runecraft.json
Sources:
https://imgur.com/a/zyOxNsN
http://oldschoolrunescape.wikia.com/wiki/Smoke_rune
https://oldschool.runescape.wiki/w/Smoke_rune
=> Updated smoke rune to correct level and sorted

runelite-client/src/main/java/net/runelite/client/game/chatbox/ChatboxTextInput.java, runelite-client/src/main/java/net/runelite/client/util/Text.java, runelite-mixins/src/main/java/net/runelite/mixins/ScriptVMMixin.java
=> Fix carrots in ChatboxTextInput

runelite-client/src/main/java/net/runelite/client/plugins/chatboxperformance/ChatboxPerformancePlugin.java
=> Properly null-check chat performance widgets

runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodePlugin.java
Prevents unnecessary code execution while logged out and Fixes inventory size on initial login.
=> Fix Minor Motherlode Plugin bugs

runelite-client/src/main/java/net/runelite/client/plugins/gpu/SceneUploader.java, runelite-client/src/main/resources/net/runelite/client/plugins/gpu/frag.glsl
=> GPU: Fix Untextured Faces

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java
Add first slayer task dialog #5945
=> First Slayer Task

runelite-client/src/main/java/net/runelite/client/plugins/statusbars/StatusBarsOverlay.java
This prevents all kinds of unsupported formats and number format
exceptions.
Closes #6589
=> Properly parse stat change value in status bars

cache/src/main/java/net/runelite/cache/StructManager.java, cache/src/main/java/net/runelite/cache/definitions/StructDefinition.java, cache/src/main/java/net/runelite/cache/definitions/loaders/StructLoader.java, cache/src/main/java/net/runelite/cache/definitions/providers/StructProvider.java, cache/src/test/java/net/runelite/cache/StructManagerTest.java
This is for loading another data structs that consists of just params.
=> Add StructDefinition to cache

runelite-client/src/main/java/net/runelite/client/plugins/devtools/CameraOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsButton.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/LocationOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/SceneOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/VarInspector.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/WidgetInspector.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/WorldMapLocationOverlay.java
- Change dev tools font to constant
- Create custom dev tools button type with isActive property
- Query this new property instead of bunch of stored boolans and toggle
methods in dev tools overlays and panels
- Move widget and itemIndex to DevToolsOverlay
=> Cleanup dev tools plugin

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
=> Add dense essence chiseling to idle notifier

runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/gpu/config/AntiAliasingMode.java
=> gpu: add scene anti-aliasing

runelite-client/src/main/java/net/runelite/client/game/ItemStack.java, runelite-client/src/main/java/net/runelite/client/game/LootManager.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
=> Fix "Only show loot" ground items

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatChanges.java
Papaya fruit health restore change from 4 to 8 when hovered
=> Change papaya fruit health restore

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_construction.json
Fixes: #6798
Let me know if anything else needs changing in this file whilst I'm at it.
=> Correct Oak Armchair level requirement in Construction Skill Calc

runelite-client/pom.xml, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldHopperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldHopperPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldSwitcherPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldTableHeader.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldTableRow.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/ping/IPHlpAPI.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/ping/IcmpEchoReply.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/ping/Ping.java
=> world switcher: add ping

runelite-client/src/main/java/net/runelite/client/plugins/agility/Obstacles.java
=> Added wyvern cave stairs to agility plugin obstacles

runelite-api/src/main/java/net/runelite/api/MessageNode.java, runelite-api/src/main/java/net/runelite/api/events/SetMessage.java, runelite-client/src/main/java/net/runelite/client/chat/ChatMessageManager.java, runelite-client/src/main/java/net/runelite/client/chat/QueuedMessage.java, runelite-client/src/main/java/net/runelite/client/config/ChatColorConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/chathistory/ChatHistoryPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/timestamp/TimestampPlugin.java, runelite-client/src/main/scripts/ChatBuilder.rs2asm, runelite-mixins/src/main/java/net/runelite/mixins/RSMessageNodeMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSMessageNode.java
=> Add timestamp plugin

runelite-client/src/main/java/net/runelite/client/plugins/wintertodt/WintertodtPlugin.java
🙂 
https://oldschool.runescape.wiki/w/Wintertodt
=> Fix the description of the wintertodt plugin and add boss tag

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java
context: https://youtu.be/r1mROBVh2OM
=> Move Level 37 wilderness hot clue step

runelite-client/src/main/java/net/runelite/client/plugins/timestamp/TimestampPlugin.java
=> Add space after timestamp

runelite-client/src/main/java/net/runelite/client/plugins/cooking/CookingConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/cooking/CookingOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/cooking/CookingPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/cooking/CookingSession.java
As talked about on discord. I have tried to create a basic cooking plugin.
Basic overlay, and there is also burn procentage for "Burnt" food.
=> Cooking plugin

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_crafting.json
=> Add silver jewelry to crafting skill calculator

runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
Since the change to batch post config updates was merged, config changes that happen between last post and client closed aren't synced to the server.
=> Send config updates on close

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_magic.json
https://i.gyazo.com/593fcffcc94ea6a94dda76eac32a4f41.png
https://i.gyazo.com/cbda5ec7463d5e723c49541fe9b12899.png
=> fix charge water orb xp in skill calc

http-service/src/main/java/net/runelite/http/service/loottracker/LootTrackerService.java
Proof that the fix is working:
```
killId	time	type	eventId	itemId	itemQuantity
8	2018-12-23 14:48:56	NPC	Goblin	526	1
8	2018-12-23 14:48:56	NPC	Goblin	995	5
9	2018-12-23 14:48:59	NPC	Goblin	526	1
9	2018-12-23 14:48:59	NPC	Goblin	2347	1
10	2018-12-23 14:49:06	NPC	Goblin	526	1
10	2018-12-23 14:49:06	NPC	Goblin	995	5
11	2018-12-23 14:49:11	NPC	Goblin	526	1
11	2018-12-23 14:49:11	NPC	Goblin	1237	1
12	2018-12-23 14:49:13	NPC	Goblin	526	1
13	2018-12-23 14:49:15	NPC	Goblin	526	1
14	2018-12-23 14:49:19	NPC	Goblin	526	1
14	2018-12-23 14:49:19	NPC	Goblin	1949	1
15	2018-12-23 14:49:21	NPC	Goblin	526	1
16	2018-12-23 14:49:28	NPC	Man	526	1
16	2018-12-23 14:49:28	NPC	Man	313	1
17	2018-12-23 14:49:30	NPC	Man	526	1
17	2018-12-23 14:49:30	NPC	Man	995	3
18	2018-12-23 14:49:46	NPC	Man	526	1
18	2018-12-23 …
```
=> loot tracker service: fix getting loot records

http-api/src/main/java/net/runelite/http/api/item/ItemStats.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatOverlay.java
Change "substracted" to "subtracted" in various ItemStats method
=> Fix Typo in ItemStats: "substracted" to "subtracted"

runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java
=> gpu: limit msaa samples to supported value

http-api/src/main/java/net/runelite/http/api/loottracker/LootTrackerClient.java, http-service/src/main/java/net/runelite/http/service/loottracker/LootTrackerController.java, http-service/src/main/java/net/runelite/http/service/loottracker/LootTrackerService.java, runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerBox.java, runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
Record quantity is limited to the default return value of the API endpoint
=> Display persistent data inside Loot Tracker UI

runelite-client/src/main/java/net/runelite/client/plugins/objectindicators/ObjectIndicatorsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/objectindicators/ObjectIndicatorsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/objectindicators/ObjectIndicatorsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/objectindicators/ObjectPoint.java
Add plugin that can mark any GameObject with shift.
Closes #4497
Closes #3792
Closes #2891 
Preview:
=> Add object indicators plugin

runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
=> Barbarian mix timers

runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSMainBufferProviderMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/Rasterizer2DMixin.java
This removes alot of complexity from ui alphaing, and makes it slightly faster.
This has matching internal changes in !42
=> gpu: Use premultiplied alpha

runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/screenshot/ScreenshotPluginTest.java
=> Split Valuable and Untradeable screenshot options

runelite-client/src/main/java/net/runelite/client/plugins/cooking/CookingPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/cooking/CookingPluginTest.java
Karambwans are missing in the cooking plugin this adds them to it.
=> Add karambwans to cooking plugin.

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_woodcutting.json
=> Fix arctic pine exp

runelite-client/src/main/resources/npc_health.json
=> Add the lvl 20 ardy guards to the npc_health.json

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/events/BeforeRender.java, runelite-client/src/main/java/net/runelite/client/callback/Hooks.java, runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/skybox/Skybox.java, runelite-client/src/main/java/net/runelite/client/plugins/skybox/SkyboxPlugin.java, runelite-client/src/main/resources/net/runelite/client/plugins/skybox/skybox.txt, runelite-client/src/test/java/net/runelite/client/plugins/skybox/SkyboxTest.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSSceneMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
=> Add Skybox plugin

runelite-client/src/main/java/net/runelite/client/config/Range.java, runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPluginConfig.java
=> Add range annotation to gpu draw distance

runelite-client/src/main/java/net/runelite/client/plugins/combatlevel/CombatLevelOverlay.java, runelite-client/src/test/java/net/runelite/client/plugins/combatlevel/CombatLevelPluginTest.java
=> Fix prayer to next combat level calculation

http-service/src/main/resources/net/runelite/http/service/xp/schema.sql
Added Wyrm Bones, Drake Bones, and Hydra Bones
=> Added New Bones to skill_prayer.json

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java
=> Respect "Only show loot" option for item notifications

runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabSprites.java, runelite-client/src/main/java/net/runelite/client/plugins/interfacestyles/InterfaceStylesPlugin.java, runelite-client/src/main/java/net/runelite/client/util/ImageUtil.java
Bank Tags & Interface Styles both use it and future plugins may find it useful.
=> Move getImageSpritePixels into ImageUtil

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
… the tree name in the option.
fixes #7283
=> Add new farming patch trees to Menu Entry Swapper (pay)

runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java
Added the fog as a tag for the GPU plugin. Also added draw distance since that is an other setting the gpu plugin can have.
=> Add "fog" as tag for GPU plugin

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/FarmingPatchLocation.java
Adds tooltips of farming patches on the world map to show the farming patch types for new farming guild.
=> Add Farming Patch world map locations for Farming Guild

runelite-client/src/main/java/net/runelite/client/plugins/agility/Obstacles.java
Adds the missing shortcuts to the plugin.
=> Add Mount Karuulm agility shortcuts to agility plugin

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
=> Swap open with quick-open at hydra

runelite-client/src/main/java/net/runelite/client/plugins/tileindicators/TileIndicatorsOverlay.java
=> Change tile indicator priority to be above ground markers

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
=> Add Alchemical Hydra to chat kc abbreviations

runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/KourendDiaryRequirement.java
=> Add missing Forsaken Tower requirement to kourend & kebos diary plugin.

runelite-api/src/main/java/net/runelite/api/events/ClientTick.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/MenuEntryWithCount.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
Closes #7094 
Closes #3570 
Closes #7225 
Preview:
=> Add menu entry collapser to ground items

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerBox.java
=> Remove tags from loot tracker box title

runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
=> Use client real dimensions for canvasTopRight

runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityConfig.java
Changed "Show Lap count" to "Show Lap Count". So that it is consistent with rest of the plugin.
=> fix-text-agility-plugin

cache/src/main/java/net/runelite/cache/definitions/AreaDefinition.java, cache/src/main/java/net/runelite/cache/definitions/ClientScript1Instruction.java, cache/src/main/java/net/runelite/cache/definitions/FrameDefinition.java, cache/src/main/java/net/runelite/cache/definitions/FramemapDefinition.java, cache/src/main/java/net/runelite/cache/definitions/InterfaceDefinition.java, cache/src/main/java/net/runelite/cache/definitions/InventoryDefinition.java, cache/src/main/java/net/runelite/cache/definitions/ItemDefinition.java, cache/src/main/java/net/runelite/cache/definitions/KitDefinition.java, cache/src/main/java/net/runelite/cache/definitions/ModelDefinition.java, cache/src/main/java/net/runelite/cache/definitions/NpcDefinition.java, cache/src/main/java/net/runelite/cache/definitions/SequenceDefinition.java, cache/src/main/java/net/runelite/cache/definitions/SpotAnimDefinition.java, cache/src/main/java/net/runelite/cache/definitions/StructDefinition.java, cache/src/main/java/net/runelite/cache/definitions/TrackDefinition.java, cache/src/main/java/net/runelite/cache/definitions/WorldMapType0.java, cache/src/main/java/net/runelite/cache/fs/flat/FlatStorage.java, cache/src/test/java/net/runelite/cache/fs/flat/FlatStorageTest.java, pom.xml
I use this to version the cache for the cachecode updater
=> cache: Add FlatStorage

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
Close: #7220 
Added Animation ID 4067 to IdleNotifier
=> Added Tablet Creation animation to Idle Notifier

runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/util/SwingUtil.java
=> Shutdown plugins on window close

runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java, runelite-client/src/main/java/net/runelite/client/config/Keybind.java, runelite-client/src/main/java/net/runelite/client/config/ModifierlessKeybind.java, runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/wasdcamera/WASDCameraConfig.java
Supersedes/Closes #7369
Supersedes/Closes #7331
Closes #7165
=> Ignore modifiers in WASD plugin input

runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/Produce.java
=> Correct Iasor timing tracker typo

runelite-api/src/main/java/net/runelite/api/Perspective.java, runelite-client/src/main/java/net/runelite/client/plugins/hunter/TrapOverlay.java
=> Null-check local location in trap overlay

http-api/src/main/java/net/runelite/http/api/chat/ChatClient.java, http-api/src/main/java/net/runelite/http/api/chat/Task.java, http-service/src/main/java/net/runelite/http/service/chat/ChatController.java, http-service/src/main/java/net/runelite/http/service/chat/ChatService.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java
Closes #798
Supersedes/closes #3645
Adds the `!task` chat command.
=> Add task chat command

runelite-client/src/main/java/net/runelite/client/util/SwingUtil.java
This reverts commit b893e97ccf92c3874f5e9d359599fd1f37de5f13.
Closes #7492
=> Revert "Move close handling to windowClosed event"

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/MapElementConfig.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java, runescape-api/src/main/java/net/runelite/rs/api/RSMapElementConfig.java
=> runelite-api, runescape-api: Rename Area to MapElementConfig

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/RareTreeLocation.java, runelite-client/src/main/java/net/runelite/client/plugins/worldmap/RareTreePoint.java, runelite-client/src/main/java/net/runelite/client/plugins/worldmap/WorldMapConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/worldmap/WorldMapPlugin.java
=> Add Rare Tree map points

runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordGameEventType.java
closes #7557 
pretty much first contribution so let me know if any changes should be made
=> Add Hydra & Karuulm Area to Discord Plugin

runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeOreOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeSession.java
This would fix issue #7381 that I created.
=> Add ore tracker to MLM plugin

runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java, runelite-client/src/main/java/net/runelite/client/plugins/timers/TimerTimer.java, runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/Timer.java
=> Add anti-poison timers to anti-venom potions

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Fixes #1756
Closes #2845
replaces #2845 , which is outdated and non-maintained (the other half of #2845's request was already merged in #6388)
=> Swap pick with pick-lots in cox

runelite-client/src/main/java/net/runelite/client/plugins/chatnotifications/ChatNotificationsPlugin.java
Resolves #7596 and Resolves #7371
=> Remove tags from chat notification matcher

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
=> Add normal colour to the !clues command

runelite-client/src/main/java/net/runelite/client/plugins/party/PartyPlugin.java
=> Add missing config check to party leave message

runelite-client/src/main/java/net/runelite/client/plugins/inventoryviewer/InventoryViewerOverlay.java
=> Inventory Viewer: Fix stackable items not showing stack of "1"

runelite-client/src/main/java/net/runelite/client/game/ChatboxInputManager.java, runelite-client/src/main/java/net/runelite/client/game/chatbox/ChatboxTextInput.java, runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/DiaryRequirementsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java, runelite-client/src/main/java/net/runelite/client/plugins/demonicgorilla/DemonicGorillaPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/WidgetInspector.java, runelite-client/src/main/java/net/runelite/client/plugins/fairyring/FairyRingPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/KourendLibraryOverlay.java
=> client: Use isEmpty() for all Collection emptiness checks
