runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
When the Client was smaller than the minimum size it would flicker on redraw, commenting this line out fixes that, but introduces a new bug that makes the RS Load screen not centered on first load, but as soon as you resize it, it gets centered.
=> Fixed flickering bug.

cache/src/main/java/net/runelite/cache/ItemDumper.java, cache/src/main/java/net/runelite/cache/MapImageDumper.java, cache/src/main/java/net/runelite/cache/NpcDumper.java, cache/src/main/java/net/runelite/cache/definitions/ItemDefinition.java, cache/src/main/java/net/runelite/cache/definitions/ModelDefinition.java, cache/src/main/java/net/runelite/cache/definitions/loaders/ItemLoader.java, cache/src/main/java/net/runelite/cache/definitions/loaders/ModelLoader.java, cache/src/main/java/net/runelite/cache/definitions/loaders/NpcLoader.java, cache/src/main/java/net/runelite/cache/definitions/loaders/SequenceLoader.java, cache/src/main/java/net/runelite/cache/definitions/loaders/SpotAnimLoader.java, cache/src/main/java/net/runelite/cache/definitions/loaders/SpriteLoader.java, cache/src/main/java/net/runelite/cache/models/ObjExporter.java, cache/src/test/java/net/runelite/cache/SequenceDumper.java, cache/src/test/java/net/runelite/cache/SpriteDumperTest.java, model-viewer/src/main/java/net/runelite/modelviewer/ModelViewer.java
1. Standardizes what is passed into definition loaders.
2. Makes the names of ModelDefinition fields more descriptive.
3. Adds texture UV coordinate calculation to ModelDefinition, allowing for correctly applying textures to model faces by making use of software that supports UV mapping, such as OpenGL.
4. Adds previously unknown fields to ItemDefinition.
=> Cache definitions changes/additions

runelite-api/src/main/java/net/runelite/api/Region.java
I noticed that when the Ground Items debug is enabled in devtools that there are a lot of NullPointerExceptions being thrown if you are not on the ground floor in the game world. After looking at the stack trace I can see that `net.runelite.api.Region#getTiles` hydrates a 3d array of Tiles where the tile could be null.
I'm using `isEmpty` as a stub for a method name to check if the underlying `net.runelite.rs.api.Tile` is `null` to avoid NPEs being thrown. This check should probably be in place for all other methods in `net.runelite.api.Tile`, or the constructor should require the `net.runelite.rs.api.Tile` object to be non-null.
=> runelite-api: Add check for tile being null before creating wrapper

cache/src/main/java/net/runelite/cache/script/Instructions.java, cache/src/main/java/net/runelite/cache/script/Opcodes.java
This adds a mapping for opcode 1301 for setting the `dragParent` on a `Widget`.
=> cache: Add mapping for opcode 1301

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java
Since per-item highlighting/hiding through config is a ways off, I figured this would be the next best thing.
Also reformatted GE price to make it look less like a quantity.
=> GroundItems - change text color according to rarity

runelite-api/src/main/java/net/runelite/api/queries/NPCQuery.java
code is reused from the TileObjectQuery class
=> NPCQuery - Add idEquals

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java, runescape-api/src/main/java/net/runelite/rs/api/ItemComposition.java
++ Added support for High Alchemy values, if enabled. Disabled by default.
++ Fixed issue where noted items would not have their GE values calculated.
++ Added configuration key for GE values, can be enabled or disabled by itself. Enabled by default.
-- Removed/commented out the code that hides the overlay when the bank is opened. I'm still trying to find the source of the bug that causes the overlay to permanantly disappear(requiring a client restart) after opening the bank interface in certain banks.
=> Changes/upgrades to GroundItems

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
-The minimum size isn't set until sidebar is expanded allowing you to minimize client until game crashes.
=> Fix for minimum client size

runelite-client/src/main/java/net/runelite/client/config/ConfigInvocationHandler.java
Gets rid of the extreme "access to public member failed" spam in the console along with settings not being loaded, when running the client on Java 9.
=> Fix runelite-client when running on Java 9

pom.xml
Gets rid of the fatal error explained in https://issues.apache.org/jira/browse/MJAVADOC-488 by updating maven-javadoc-plugin to the latest version.
=> Fix running Maven install on JDK9

runelite-mixins/src/main/java/net/runelite/api/mixins/Inject.java, runescape-client-injector-plugin/src/main/java/net/runelite/injector/MixinInjector.java
Adds support for injecting fields into game classes through mixins.
Example usage:
```java
@Mixin(RSActor.class)
public abstract class RSActorMixin implements RSActor
{
// inject "foo" into RSActor
@Inject
public int foo; 
// inject "bar()" into RSActor
@Inject
@Override
public Actor bar()
{
// references will be modified to RSActor.foo from RSActorMixin.foo
foo = 1; 
System.out.println(foo);
}
}
=> Field mixins

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
Removes this black line:
(image taken by Xrio)
Also fixes a minor error with the panel width where resizing the frame horizontally would make the plugin bar overlap a bit over the game.
=> Remove the black line below the game applet

runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBoxOverlay.java
Tooltips now display properly with other left rendered overlays present
InfoBoxes no longer stack when they don't have tooltips (Timers plugin)
=> InfoBox tooltip fixes

runelite-api/src/main/java/net/runelite/api/queries/EquipmentItemQuery.java
Fixed equipped item queries to return -1 (default value for no item in slot) for itemIds that remain in Widgets after removing them:
=> Fix equipItemQuery to remove number after unequip

runelite-client/pom.xml, runelite-client/src/main/java/net/runelite/client/RuneLite.java
Replace current TrayIcon notifications with system-native notifications.
Supports most of the operating systems (the important ones are Windows,
Linux and OS X).
Resolves: #230
=> Add support for native notifications

runelite-client/src/main/java/net/runelite/client/plugins/aoewarnings/AoeWarningOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/attackindicator/AttackIndicatorOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSpotOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/fpsinfo/FPSOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/implings/ImplingsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/instancemap/InstanceMapOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/jewellerycount/JewelleryCountOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/mousehighlight/MouseHighlightOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/pestcontrol/PestControlOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/prayflick/PrayerFlickOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/BindNeckOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/runepouch/RunepouchOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/specorb/SpecOrbOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/volcanicmine/VolcanicMineOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/WoodcuttingOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/zulrah/ZulrahOverlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/DynamicRenderer.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/Overlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/TopDownRendererLeft.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/TopDownRendererRight.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBoxOverlay.java
Instead of checking the login state, click to play screen, and bank interface inside a plugin's overlay render method, the check is now inside of their super class Overlay.
This means that checks in a plugin's overlay like this:
```
if(client.getGameState() != GameState.LOGGED_IN || client.getWidget(WidgetInfo.LOGIN_CLICK_TO_PLAY_SCREEN) != null)
{
return null
}
```
Now become
```
this.setDrawOverClickToPlayScreen(false);
this.setDrawOverLoginScreen(false);
```
Inside the plugin overlay constructor.
There is also a flag for drawing over the bank interface, which avoids having things like ground items drawing while the bank screen is open.
```
this.setDrawOverBankScreen(false);
```
=> Move login/interface check to overlay

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java
Add option to hide items under either Grand Exchange or High Alchemy
value to GroundItems plugin. Also ensure that items with 0 or no GE
price are shown anyway, as they are probably untradeables or inactive.
=> Add hide items under value to GroundItems plugin

runelite-client/pom.xml, runelite-client/src/main/java/net/runelite/client/Notifier.java, runelite-client/src/main/java/net/runelite/client/RuneLite.java
Remove dependency on external notification library and rewrite
notifications to use lightweight native system notification
implementations:
* Linux - notify-send
* OS X - apple script - display notification
* Windows - TrayIcon
=> Make native notifications lightweight

runelite-client/src/main/java/net/runelite/client/config/RuneliteConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/jewellerycount/JewelleryCountOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/BindNeckOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/volcanicmine/VolcanicMineOverlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/Overlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/RenderableEntity.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/BackgroundComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/InfoBoxComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/PanelComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/TextComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/TooltipComponent.java
- Remove unnecessary derivations of runescapeSmallFont
- Render overlays in "safe" environment (restore original font and
tranform after overlay rendering is done)
- Use TextComponent at more places
- Remove unnecessary setting of default font in VolcanicMineOverlay
- Change RenderableEntity from abstract class to interface
- Remove unused tooltip configuration from RuneliteConfig
- Use viewportWidget instead of chatbox widget for positioning the
overlay groups (thanks to Devin for tip)
- Use small font for tooltips and ground items
=> Cleanup overlay logic after native-ui changes

runelite-api/src/main/java/net/runelite/api/Experience.java, runelite-api/src/test/java/net/runelite/api/ExperienceTest.java
To draw the progress bar, `XPGlobesOverlay.drawTooltipIfMouseover()` uses `Experience.getXPForLevel()`, which threw an `IllegalArgumentException` when asked about level 1. This change shifts the `XP_FOR_LEVEL` array over by one, so that `XP_FOR_LEVEL[0]` is the XP required to reach level 1 (i.e. 0), rather than the XP required for level 2.
=> Fix IllegalArgumentExceptions from XPGlobes' tooltips for level 1 stats

runelite-plugin-archetype/src/main/resources/archetype-resources/src/main/java/ExampleOverlay.java
#246 changed the API for overlays slightly. This change fixes the maven archetype plugin to match
=> Fix example plugin to use the new overlay API

runelite-api/src/main/java/net/runelite/api/MenuAction.java, runelite-client/src/main/java/net/runelite/client/plugins/examine/ExaminePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/examine/ExamineType.java
Add support for showing bank, bank inventory and equipment item prices
when examined.
=> Add support for examining bank and eq items price

runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
Clone graphics before rendering overlay, then use the cloned graphics
for the overlay and dispose it afterwards to prevent any unwanted side
effects from overlay.
=> Isolate graphics for each overlay

runelite-plugin-archetype/src/main/resources/archetype-resources/src/main/java/ExampleOverlay.java, runelite-plugin-archetype/src/test/resources/projects/compilationtest/archetype.properties, runelite-plugin-archetype/src/test/resources/projects/compilationtest/goal.txt
This PR fixes the dependency conflict that was introduced in the last fix (#264), and adds a test to make sure that it at least builds.
The test is failing when I run it from IDEA, but works just fine if I run it from a regular shell. I'm pretty sure the issue is just IDEA/my configuration, but we'll see how travis likes it.
=> Actually fix example plugin archetype, and add a test to make sure it stays that way

http-api/src/main/java/net/runelite/http/api/account/AccountClient.java, http-api/src/main/java/net/runelite/http/api/config/ConfigClient.java, http-api/src/main/java/net/runelite/http/api/hiscore/HiscoreClient.java, http-api/src/main/java/net/runelite/http/api/item/ItemClient.java, http-api/src/main/java/net/runelite/http/api/xtea/XteaClient.java, http-service/src/main/java/net/runelite/http/service/hiscore/HiscoreService.java, http-service/src/main/java/net/runelite/http/service/item/ItemService.java, http-service/src/main/java/net/runelite/http/service/worlds/WorldsService.java, runelite-client/src/main/java/net/runelite/client/ConfigLoader.java
When request fails, entire response needs to be wrapped in try with
resources in order to close the connection properly and not only
response body.
=> Fix OkHttp connection leaks on connection error

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java
- Fix alch value applying to one item instead of whole stack
- Fix high alch value display applying to one item instead of whole stack
- Fix coins not having value (will now be shown/hidden depending on amount)
- Show highlighted items independent of value
=> Ground Items - Fix stack alch value, coins value, quantity alch value display, item highlight priority

runelite-mixins/src/main/java/net/runelite/mixins/RSPlayerMixin.java
Player name is null when the player's appearance hasn't been decoded/set.
For the local player I at one instance measured 160ms between having initialized the Player object and having decoded the appearance, which provides a window in which the name field can be null.
=> RSPlayerMixin: Don't NPE when Player name is null

runelite-client/src/main/java/net/runelite/client/plugins/account/AccountPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPlugin.java
Add property to load when outdated to both account and config plugins to
make them visible even when native client is loaded.
=> Show account and config plugins when outdated

runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsOverlay.java
They have been reordered from Left to Right and from Top to Bottom from the skills menu in osrs. It is purposefully missing Hitpoints and Prayer.
#297
=> Added and reordered missing skilling skills from boosts overlay.

runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPanel.java
``refreshWidgets()`` was being run on the Swing Event Dispatch Thread, which caused the UI to freeze because the method takes long to execute.
=> Fix the UI freezing when refreshing widgets in the Dev Tools

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java
As this is not really issue, as in this case the icon just falls back to
the default gem icon, this should not really be a warning message and
spam console logs.
Fixes #292
=> Change warning for not found task to debug

runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
This change improves the framerate in resizable mode by 10-15 fps by reducing the amount of screen clearing done while drawing overlays.
=> Reduce clearRect calls to improve framerate

runescape-api/src/main/java/net/runelite/rs/api/RSGameCanvas.java, runescape-client/src/main/java/Client.java, runescape-client/src/main/java/GameCanvas.java, runescape-client/src/main/java/GameEngine.java, runescape-client/src/main/java/GameSocket.java, runescape-client/src/main/java/TextureProvider.java, runescape-client/src/main/java/class161.java, runescape-client/src/main/java/class192.java, runescape-client/src/main/java/class230.java
This makes mixins that perform actions on those classes work again.
For example:
```
[INFO] Class RSCanvas implements nonexistent interface net.runelite.rs.api.RSRSCanvas, skipping interface injection
```
would show up when trying to build with a mixin on the class ``net.runelite.rs.api.RSCanvas``.
=> Remove "RS" prefixes from runescape-client classes

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
Since it sounds like this isn't just an issue for me and my weird linux+hipster tiling wm setup, here's a PR to fix the cursor weirdness.
Once its gotten close to the edge of the window, my cursor will usually get stuck as one of the resize arrows rather than change back to a normal cursor.  It looks like Substance gets confused about what the last cursor was, and starts "restoring" one of the resize cursors, instead of the pointer, when the cursor moves back away from the edge of the window. Setting the cursor for the frame's LayeredPane fixes the problem.
=> Prevent cursor icon from getting stuck as the wrong shape

runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
Fixes idle notifications (claiming to have just dropped combat) from happening when interacting with another player (following/trading) and banking using an NPC instead of a booth. See #282
=> Incorrect idle notifications

runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java, runelite-client/src/main/java/net/runelite/client/ui/PluginToolbar.java
This is similar to #240 but it adds it as a config option.
Because it is a config option it waits for the config to be loaded before showing the window. This has the positive side affect of not having the contents of the window jump around as plugins are loaded, but makes it take even longer to show the window. It may be a good idea to add a splash screen or loading bar.
=> client: Add option to disable custom window chrome/style

runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanChatPlugin.java
- Use Guava cache instead of scheduled caching to cache clan member
ranks to reduce frequency of caching and simplify logic
=> Improve clan rank caching

runescape-client-injector-plugin/src/main/java/net/runelite/injector/MixinInjector.java
Fixes the injector producing broken code when doing this:
isFriended has a garbage/dummy parameter, so an ``iload 2`` will be injected before the rs$isFriended call to pass the garbage parameter down the line, but "foo" has already taken the lvar slot 2.
```java
@Copy("isFriended")
private static boolean rs$isFriended(String name, boolean mustBeLoggedIn)
{ return false; }
@Replace("isFriended")
private static boolean rl$isFriended(String name, boolean mustBeLoggedIn)
{
boolean foo = ....; // <-- foo has taken local var slot 2
return foo || rs$isFriended(name, false); // iload 2 will be injected for the method call
}
```
This pull request makes it so "foo" uses lvar slot 3, fixing the broken code.
It also prevents injected @Replace-annotated methods from using lvar slots that are > the …
=> Fix mixins producing broken code

runelite-plugin-archetype/src/test/resources/projects/compilationtest/goal.txt, travis/build.sh
- Use "install" instead of "verify" so archetype test can pick up the
latest RuneLite version
- Remove "clean" from goals.txt
Fixes #364
=> Fix runelite-plugin-archetype

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/plugins/tileindicators/TileIndicatorsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/tileindicators/TileIndicatorsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/tileindicators/TileIndicatorsPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
Add tile indicators plugin, that will currently highlight the tile current
player is walking to. It is disabled by default, and have configurable
highlighting color.
Preview:
=> Add tile indicators plugin

runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsPlugin.java
Plugin will be able to display own name (disabled by default), friend
player names and clan member names. Also, to optionally render highlighted tile under players with rendered names. Each of the options is configurable.
Fixes #324
Preview:
=> Add plugin for displaying player names

runelite-api/src/main/java/net/runelite/api/events/WidgetHiddenChanged.java, runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java, runelite-client/src/main/java/net/runelite/client/plugins/attackindicator/AttackIndicatorPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/combatlevel/CombatLevelPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSWidgetMixin.java
An event gets fired as soon as a Widget is created from the GraphicsObject.loadWidget (cj.k) function.
This makes manipulation of widgets much smoother without having to rely on polling.
For example: 
The first combat style is hidden as soon as the weapon is changed where it usually would've been redrawn. The old polling method can be seen with the delayed update of the decimal in the Combat Lvl.
=> WidgetHiddenChanged event

runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
Currently the bottomleft and rightChatBox are unchanged regardless if chatbox is minimized or not.
Currently:
After:
=> Add check for chatbox minimized

runelite-mixins/src/main/java/net/runelite/mixins/RSGameCanvasMixin.java
The client likes to take focus whenever it is resized, this makes it only take focus if it already had it.
=> Prevent the client from taking focus when it doesn't have it.

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java, runelite-client/src/main/java/net/runelite/client/ui/FontManager.java
Fix broken glyphs once and for all (hopefully).
The last pull request that was supposed to fix this (#312) only fixed it for the Swing UI, this fixes it for in-game overlays too.
**Before:**
**After:**
=> runescape-client: Fix broken glyphs

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java
If you don't have a task and change the Slayer plugin settings, the game will crash:
```
Error: bd.ag() | InfoBoxManager:70 Hooks:97 client.ax bd.ag bd.run Thread:748 | java.lang.NullPointerException
error_game_crash
```
This is because "counter" is null when you don't have a task, and the null is registered as an info box.
=> Fix SlayerPlugin crashing the game

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/GameEngine.java, runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java, runelite-client/src/main/java/net/runelite/client/ui/PluginPanel.java, runelite-client/src/main/java/net/runelite/client/ui/PluginToolbar.java
This allow PluginPanels to keep state, primarily so that their scrollbars do not get reset when changing panels. It also allows the ConfigPanel to keep it's scroll and search state when entering and exiting it's sub-pages.
This PR supersedes #371
=> Allow PluginPanels to keep state

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpWorldType.java
Allow hopping/logging out/other GameState changes without resetting XP tracker. Tracker automatically resets when changing characters.
=> XP tracker plugin - Allow hopping/logging out/other GameState changes, Fix login experience drop not being ignored

runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
Fix NPE that happens when titlebar is not present (not using the custom
window decorations) and plugin is trying to remove the screenshot
button from titlebar.
=> Fix NPE in ScreenShotPlugin

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
Extends the idle notifier plugin to notify you after 4 minutes and 40 seconds of being idle and 5h 40min of being logged in.
=> Notify before 5 minute idle and 6h logout

runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesOverlay.java
The widest part of the tooltip would be 146 pixels with "Current Xp: 888,888,888", so I rounded up to 150 for other locales. Fixes #405
=> XpGlobeTooltip now sets width of itself to prevent overlap; fixes #405

cache/pom.xml, http-api/pom.xml, http-service/pom.xml, pom.xml, protocol-api/pom.xml, protocol/pom.xml, runelite-api/pom.xml, runelite-client/pom.xml
Update Project Lombok version to 1.16.20 (from 1.16.18) and specify this
version in runelite-parent instead of having it specified all around the
maven projects.
=> Update Project Lombok version to 1.16.20

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/plugins/lowmemory/LowMemoryConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/lowmemory/LowMemoryPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java, runescape-client/src/main/java/Client.java, runescape-client/src/main/java/MouseRecorder.java, runescape-client/src/main/java/ObjectComposition.java, runescape-client/src/main/java/Region.java
Add configurable flag for RuneScape low memory mode that disables ground
textures and drawing of multiple floors to RuneLiteConfig.
Preview:
=> Add low memory mode flag

runelite-api/src/main/java/net/runelite/api/ItemLayer.java, runelite-api/src/main/java/net/runelite/api/TileObject.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java, runelite-mixins/src/main/java/net/runelite/mixins/TileObjectMixin.java
Takes into account the height of the ItemLayer for drawing the text for the GroundItems plugin.
Before:
After:
=> Incorporate height into the GroundItems overlay

runescape-client/src/main/java/BaseVarType.java, runescape-client/src/main/java/BoundingBox3DDrawMode.java, runescape-client/src/main/java/Client.java, runescape-client/src/main/java/Player.java, runescape-client/src/main/java/class61.java
These fields were previously swapped.
Evidence:
- On fixed-screen, printing the viewport width and height outputs roughly 300 and 500 respectively (swapped dimensions).
- Numerous instances in the client code where the viewport height is read or set __first__, even though generally the dimension tuple goes like _(width, height)_.
- For example,
```
Client.screenX = var0 * Client.scale / var1 + Client.viewportHeight / 2;
Client.screenX = var0 * Client.scale / var1 + Client.viewportWidth / 2;
```
=> Swapped viewport width and height fields.

runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java, runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
Adds a "game size" setting to the client's own config panel. I didn't want to split it up into a standalone plugin because it feels more like a completely client feature.
Unfortunately the input fields are not reset to their minimum/maximum when you go outside the bounds, because of missing functionality in the config system that I don't feel like adding because it can probably get a bit big.
Solves #390
=>  Add a config setting for the game's size

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
Fix java.awt.IllegalComponentStateException: The frame is displayable
that is caused by window being packed before showWithChrome method is
called.
=> Fix the frame is displayable exception

runelite-client/src/main/java/net/runelite/client/plugins/attackindicator/AttackIndicatorOverlay.java
Fix coloring of warned attack styles for attack indicator plugin. This
was in before, but probably got lost during the changes to use new UI
comoponents.
Preview:
=> Fix coloring of warned attack styles

runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java
Super antifires have been buffed in the update from last Thursday.
http://services.runescape.com/m=news/barbarian-assault-ranged-rework?oldschool=1
=> Change duration of Super Antifire Potions from 2 to 3 minutes

runelite-client/src/main/java/net/runelite/client/plugins/metronome/MetronomePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/metronome/MetronomePluginConfiguration.java
Adds support to the Metronome Plugin to make a (now configurable) sound every n-ticks instead of every tick.
=> Extend Metronome Plugin with configurable sound and tick delay

runescape-client-injector-plugin/src/main/java/net/runelite/injector/MixinInjector.java
```java
@Copy("isFriended")
private static boolean rs$isFriended(String name, boolean mustBeLoggedIn)
{
throw new IllegalStateException();
}
@Replace("isFriended")
private static boolean rl$isFriended(String name, boolean mustBeLoggedIn)
{
// invoking these twice or more would produce broken code (or if you'd invoke another copied method)
rs$isFriended(name, mustBeLoggedIn);
rs$isFriended(name, mustBeLoggedIn); 
.....
}
```
Also disallows invoking copied methods from injected methods.
=> mixins: Fix invoking copied methods multiple times producing broken code

runelite-client/pom.xml
Because currently Hashing.java is using only in mixins, it gets removed
by maven-shade-plugin from the shaded jar. So tell the plugin to keep
these classes.
=> Preserve guava classes in the shaded jar

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/potions/SuperRestore.java
Hovering over a SuperRestore throws an Exception because java has a good type system.
=> Fix SuperRestore and friends

runescape-api/src/main/java/net/runelite/rs/api/RSCacheableNode.java
They are different than RSNode's next and previous, but have the same signature so they can get called instead. This caused the ground overlay to only show 1 item because it was iterating the cache, not the item list.
=> runescape-api: remove RSCacheableNode::getNext() and getPrevious().

runelite-client/src/main/java/net/runelite/client/plugins/examine/ExaminePlugin.java
Examine messages now look like this:
Fixes #495
=> Include unit prices in examine messages

runescape-client-injector-plugin/src/main/java/net/runelite/injector/Inject.java, runescape-client-injector-plugin/src/main/java/net/runelite/injector/InjectHook.java, runescape-client-injector-plugin/src/main/java/net/runelite/injector/InjectInvoker.java
These were the most populous, and least helpful, lines in my build log, as I was trying to figure out how I'd managed to upset the injector. As far as I can tell, this information isn't actually important to have at hand for every single build ever.
=> Decrease the injector plugin's verbosity

runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostIndicator.java, runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsPlugin.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/InfoBoxComponent.java
Add the option to show boosts as indicators
=>  Add indicators to boosts plugin

runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsPlugin.java
`shownSkills` wasn't being initialized until it received `ConfigChanged` event, causing a `NullPointerException` when the overlay tried to iterate over `shownSkills`
=> Fix NullPointerExceptions from Boosts Plugin

runelite-api/src/main/java/net/runelite/api/TextureProvider.java, runelite-client/src/main/java/net/runelite/client/callback/Hooks.java, runelite-client/src/main/java/net/runelite/client/plugins/agilityplugin/AgilityOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/barbarianassault/BarbarianAssaultOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSpotOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/hunter/TrapOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/implings/ImplingsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/jewellerycount/JewelleryCountOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeRocksOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeSackOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/prayflick/PrayerFlickOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/AbyssOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/BindNeckOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/runepouch/RunepouchOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/specorb/SpecOrbOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/tileindicators/TileIndicatorsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesOverlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/Overlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/tooltip/TooltipOverlay.java, runescape-api/src/main/java/net/runelite/rs/api/RSTextureProvider.java, runescape-client/src/main/java/TextureProvider.java, runescape-client/src/main/java/class3.java
In order to not draw UI overlays over bank interfaces (and similar popup
interfaces), change default overlay position to UNDER_WIDGETS.
Fixes #451
Preview:
=> Change default overlay position to UNDER_WIDGETS

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java
Ground items will now render
- in the full viewport in resizable
- under widgets
- with interfaces (like bank) open
=> Show ground items under widgets and with interfaces open

runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeSackOverlay.java
Currently MLM plugin sack overlay layer is set to ABOVE_SCENE, but it
needs to be set to UNDER_WIDGETS so overlay renderer can tile it
correctly with other overlays (and also to be rendered over overheads
and HP bars).
=> Fix MLM plugin overlay layer

runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java, runescape-client/src/main/java/AbstractSoundSystem.java, runescape-client/src/main/java/BoundingBox3DDrawMode.java, runescape-client/src/main/java/Client.java, runescape-client/src/main/java/MouseRecorder.java, runescape-client/src/main/java/ObjectComposition.java, runescape-client/src/main/java/SourceDataSoundSystem.java, runescape-client/src/main/java/WidgetNode.java, runescape-client/src/main/java/class114.java
Fixes the audio in low memory mode being sped up, by making the audio always use the "high memory" mode.
Also renames highMemory to audioHighMemory and ocLowDetail to objectCompositionLowDetail. 
I shouldn't have to go into the engine code to see what "oc" in ocLowDetail means.
=> Low memory mode audio fix

runelite-client/src/main/java/net/runelite/client/plugins/info/JRichTextPane.java
- Remove log.info on each hover of the JRichTextPane
- Change log.info to log.warn when browser cannot be opened in the
JRichTextPane
=> Fix logging inside info panel plugin

deobfuscator/src/main/java/net/runelite/asm/attributes/code/instructions/IfNe.java, runelite-client/src/main/java/net/runelite/client/callback/Hooks.java, runelite-mixins/src/main/java/net/runelite/client/callback/Hooks.java, runelite-mixins/src/main/java/net/runelite/mixins/ScriptVMMixin.java, runelite-scripts/scripts/OptionsPanelRebuilder.rs2asm, runelite-scripts/scripts/OptionsPanelZoomMouseListener.rs2asm, runelite-scripts/scripts/OptionsPanelZoomUpdater.rs2asm, runelite-scripts/scripts/ScrollWheelZoomHandler.rs2asm, runescape-api/src/main/java/net/runelite/rs/api/RSScriptEvent.java, runescape-client-injector-plugin/src/main/java/net/runelite/injector/Inject.java, runescape-client-injector-plugin/src/main/java/net/runelite/injector/MixinInjector.java, runescape-client-injector-plugin/src/main/java/net/runelite/injector/raw/ScriptVM.java, runescape-client/src/main/java/FrameMap.java, runescape-client/src/main/java/ScriptState.java, runescape-client/src/main/java/class84.java
Fixes #550 
Fixes the zoom plugin
This exports some other fields because I thought I could use a string operand, but the script loader doesn't support that. They are left here for ease of adding a script stack trace generator.
=> Raw injector for script VM

runelite-client/src/main/java/net/runelite/client/plugins/zoom/ZoomConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/zoom/ZoomPlugin.java, runelite-scripts/scripts/OptionsPanelRebuilder.rs2asm, runelite-scripts/scripts/OptionsPanelZoomMouseListener.rs2asm, runelite-scripts/scripts/OptionsPanelZoomUpdater.rs2asm, runelite-scripts/scripts/ScrollWheelZoomHandler.rs2asm
This adds an option to the zoom plugin to expand your inner zoom limit.
It also changes the options panel's zoom scrollbar to be exponential so it is actually usable with the limit increased.
=> Zoom plugin: Relax inner zoom constraint

runelite-client/pom.xml, runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/resources/logback.xml
Add dependency on logback and configure logger to log to
~/.runelite/logs/application.log with rolling file appender, that means
every 10MB file will be rolled and also every day file will be rolled
with maximum history of 30 days, to not flood user's system space.
Add new console parameter -debug, because logback properties cannot be
set from console like slf4j-simple ones, so it needs to be done in a bit
more complicated way.
=> Add logback logger that will log to file

runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
Feature request made in #537.
This adds a new options to the RuneLite config section, which allows the user to set the client always on top. This option is disabled by default.
=> Client always on top

runelite-mixins/src/main/java/net/runelite/api/mixins/Inject.java, runescape-client-injector-plugin/src/main/java/net/runelite/injector/MixinInjector.java
Mixins with static initialized variables and static blocks will now be injected
Mixins can now create constructors annotated with `@Inject` which will be run after the base class's constructor.
=> injector: Allow injection of <init> and <clinit>

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java, runelite-client/src/main/java/net/runelite/client/ui/TitleToolbar.java
This changes the TitleToolbar to use a custom layout manager that supports removing components. It also changes the SubstanceTitlePane's layout manager to support our TitleToolbar, and it's resizability.
Required for #351
=> Fix removing items from the TitleToolbar

runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java
Disable configuration button in ConfigPanel when all configuration items
of the plugin are hidden.
=> Disable configuration button when all items hidden

runelite-client/src/main/java/net/runelite/client/plugins/mousehighlight/MouseHighlightOverlay.java
Check for option instead of target presence when renderingt the mouse
highlighting overlay.
Fixes: #490
Preview:
=> Display tooltips for widget actions

protocol/src/main/java/net/runelite/protocol/update/encoders/ArchiveResponseEncoder.java
from: http://netty.io/wiki/reference-counted-objects.html#derived-buffers
> In contrast, `ByteBuf.copy()` and `ByteBuf.readBytes(int)` are not derived buffers. The returned ByteBuf is allocated will need to be released.
This means we need to release the `ByteBuf` that is created when calling `file.readByte(CHUNK_SIZE)`.
=> Fix Netty resource leak

runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/AbsorptionCounter.java, runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZoneConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZoneOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZonePlugin.java
* Changed the default text color to green
* If the absorption points goes below the threshold, the text becomes red
* Added config fields to change the color if needed
Fixes #606
=> Fix color of text in the NMZ absorption infobox

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/events/ChatMessage.java, runelite-client/src/main/java/net/runelite/client/callback/Hooks.java, runelite-client/src/main/java/net/runelite/client/chat/ChatMessageManager.java, runelite-client/src/main/java/net/runelite/client/chat/QueuedMessage.java, runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/chathistory/ChatHistoryPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanChatPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/examine/ExaminePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
- Change sendGameMessage call to addGameMessage to allow modifying of
sender as well
- Rework ChatMessageManager to provide easier API for adding messages
without making lengthy method paramaters
- Instead of directly updating chat messages, put them to queue to not block message processing
- Fix names of fields for ChatMessage event 
- Add chat history plugin that will be able to preserve the chat history
during logout/world hop
Preview:
=> Add chat history plugin

runelite-client/src/main/java/net/runelite/client/ui/overlay/components/TooltipComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/tooltip/TooltipOverlay.java
With black background for better visibility:
I couldn't really manage to get the old regex solution working with another tag, so I just replaced it with what the game does when parsing text with tags, and I think having it that way makes it much easier to understand too.
Fixes #415
=> Render modicons in tooltips

runelite-client/src/main/java/net/runelite/client/plugins/info/InfoPlugin.java
Currently the info panel's nav button never gets removed.
=> Allow the info panel's navButton to be removed on shutDown

runelite-client/src/main/java/net/runelite/client/plugins/puzzlesolver/PuzzleSolverOverlay.java
Set PuzzleSolverOverlay layer to be above widgets so the arrows would
actually render over the puzzle box.
=> Fix PuzzleSolverOverlay layer

http-service/src/main/java/net/runelite/http/service/updatecheck/UpdateCheckService.java
This PR aims to better future proof the update check service. Currently the service builds the world address by the following manner:
`"oldschool" + nextWorld + ".runescape.com"`
If we query the .slr file we can see that some worlds use hosts with 'a' or 'b' appended after the world id:
`
oldschool6b.runescape.com
oldschool13a.runescape.com
`
Even though both hosts still reply to js5 requests (`oldschool6.runescape.com` and `oldschool6b.runescape.com`) this behavior could change leading to temporarily erroneous replies until the service `Supplier<Boolean>` cache expires.
Further work can be done to make the service return an error whenever it fails the js5 handshake.
=> Use the address returned by the worldlist api instead of building our own

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-client/src/main/java/net/runelite/client/plugins/hunter/CatchrateOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/hunter/HunterConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/hunter/HunterPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/hunter/HunterTrap.java, runelite-mixins/src/main/java/net/runelite/mixins/RSTileMixin.java
- Add support for maniacal monkey large boulder traps to hunter plugin
- Add support for notifications on maniacal monkey catch/escape
- Store last gameObject as static variable in tile mixin and in case new
event is exactly same as last one in game object spawned, do not
proceed.
Preview:
=> Hunter maniacal monkeys

runelite-client/src/main/java/net/runelite/client/Notifier.java
- Add default timeout of 10 seconds to notify-send on Linux to not depend
on default notification timeout on Linux notify daemon, because on some
system the default can be never hide unless timeout is set.
=> Add default timeout of 10 seconds to notify-send on Linux

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
Fix crash that can happen when ConfigChanged event arrives to ClientUI
and pack method is called in the event thread. Move swing/awt related
calls to swing thread to avoid this issue.
=> Fix crash in ClienUI configChanged event

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
Make the panel actually expand outwards of the client instead of inwards. Fixes inconsistency of game size.
Fixes #463
=> Fix panel expanding inconsistency

runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/OrbCentering.java, runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesOverlay.java
xp progress arcs now render correctly and are neat circles at 99.9% progress. Slightly changed position of the xp orbs and the stroke width of the progress arc. also added customization to change the position and stroke width and more. The progress arc now also starts from the top.
old : https://i.imgur.com/1UgpxLy.png
new : https://i.imgur.com/hQhlMLd.png
The old settings were a stroke width of 2 and positioned in the middle of the canvas. you can now set this in settings.
=> Xp orb fixes

runelite-mixins/src/main/java/net/runelite/mixins/RSModelMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSModel.java
verticesX.length doesn't always equal verticesY.length and verticesZ.length.
I changed it for triangles/indices too.
=> Fix ArrayIndexOutOfBoundsException on getting vertices of certain gameobjects

runelite-client/src/main/java/net/runelite/client/plugins/examine/ExaminePlugin.java
Makes it so it doesn't print out the price of items you interact with like it did below:
=> examineplugin: only capture menuactions with the option "Examine"

runelite-client/src/main/java/net/runelite/client/plugins/minimap/MinimapPlugin.java
If shutdown was called but startup was not, this would throw NPE.
NPE example:
```
net.runelite.client.plugins.PluginInstantiationException: java.lang.reflect.InvocationTargetException
at net.runelite.client.plugins.PluginManager.stopPlugin(PluginManager.java:376)
at net.runelite.client.plugins.PluginManager.lambda$null$0(PluginManager.java:126)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at …
```
=> Fix NPE in minimap plugin

runelite-client/src/main/java/net/runelite/client/Notifier.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java, runelite-client/src/main/java/net/runelite/client/util/OSType.java
More info (and demo) in issue #730 
Additionally, OSType was extracted out of Notifier for reuse.
=> Add platform-specific code to enable native fullscreen mode on OSX

deobfuscator/src/main/java/net/runelite/deob/deobfuscators/mapping/AnnotationIntegrityChecker.java
RS API classes have the prefix "RS", and the Implements annotation does not have that.
=> deobfuscator: fix aic failing to determine if a field is imported

runelite-client/pom.xml, runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/config/FuzzySearch.java
Add fuzzy search to config panel. Searches for matching query in list of
entries (plugin names) based on
[Jaro-Winkler Distance](https://en.wikipedia.org/wiki/Jaro%E2%80%93Winkler_distance).
=> Add fuzzy searching to config panel

runelite-client/src/main/java/net/runelite/client/Notifier.java, runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/RuneLiteModule.java, runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZoneConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZonePlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/PluginManagerTest.java
- Move enabling of tray notifications to RuneLiteConfig
- Move request when focused notification option to RuneLiteConfig and
use it in notifier
- Move request window focus to RuneLiteConfig and use it in notifier
- Change Notifier to use Guice for creation
- Remove notification settings from NMZ that are now contained in
RuneLiteConfig.
- Remove options that are now contained in RuneLiteConfig from idle
notifier.
=> Move the notification options to Notifier

runelite-api/src/main/java/net/runelite/api/Varbits.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/Raid.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsTimer.java
- Now shows raid layout code on the overlay
- Ability to whitelist/highlight rooms
- Ability to whitelist boss rotations
- Ability to whitelist layouts
- Timer now shows floor completion times on hover
Current behaviour:
Whitelisted rooms will ALWAYS show up in green (highlight)
Blacklisted rooms and rotations that aren't whitelisted will show up in red
Any boss rotations that partially match a whitelisted one will show the extra boss in red (shown in first picture)
The ideal raid after setting up your settings would show everything in white/green on the overlay.
Input for layout whitelist is `SCSPFCCSPF`, add more separating them with a comma.
Input for boss rotation whitelist is `[vespula, shamans, vasa]` being one rotation. (example used in the first picture)
Fixes #710
=> Add more features to raids plugin

runelite-mixins/src/main/java/net/runelite/mixins/CameraMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSRegionMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java, runescape-client/src/main/java/AudioInstrument.java, runescape-client/src/main/java/Region.java, runescape-client/src/main/java/WorldComparator.java
In rev 165 a extra check for pitch was added in Region.drawRegion which caused tiles to be rendered at a different pitch than 2D extras. Because the new limit is only a local variable I couldn't use the same trick. Instead, this just recomputes the pitchCos and pitchSin with the unlimited values when they are changed. Additionally, the visibilityMap code is removed because it no longer crashes without it, due to the new limit.
=> Fix camera pitch

runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingOverlay.java
Replace equality check with contains check due to recent renaming of
some fishing spots from OSRS side.
Fixes: #755
=> Fix "You are fishing" in fishing plugin

runelite-client/pom.xml, runelite-client/src/main/java/net/runelite/client/Notifier.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java, runelite-client/src/main/java/net/runelite/client/util/OSXUtil.java
I also extracted the OSX-specific tools into a new util class so that all the apple-related reflection is done in one place.
Now focus will correctly switch to the RuneLite window when the setting is enabled on OSX.
=> Fix "request focus on notification" on OSX

runelite-client/src/main/java/net/runelite/client/Notifier.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
Correctly focus game canvas when requesting ClientUI focus. Also, move
the call to OSXUtil.requestFocus() to clientUI.
=> Correctly focus game canvas when requesting focus

runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
When you splash or miss too many times client
thinks that NPC have -1 HP and then idle notifier ignores that action, that means
- It do not register start of action, so never throws notification
- Or it will not register continuation of action, so it will throw false notification
=> do not registers start of the action
After some testing, seems like that health check is not necessary and checking for combat level is enough.
=> Make idle notifier work for splashing/missing

runelite-client/src/main/java/net/runelite/client/chat/ChatMessageManager.java, runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java
As this is not used in chat commands only anymore, and since it is
configuration parameter that noone needs to disable, it is unnecessary
and is just causing confusion.
=> Remove unnecessary chatCommandsEnabled from config

runelite-client/src/main/java/net/runelite/client/plugins/instancemap/InstanceMapInputListener.java, runelite-client/src/main/java/net/runelite/client/plugins/instancemap/InstanceMapOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/instancemap/InstanceMapPlugin.java
- Can now scroll to traverse trough planes
- Closes on ESC
Removed the "ascend" and "descend" options from the right click menu since scrolling now performs these actions.
I also moved the map a bit so it kinda matches the positioning of the other widgets
=> Instance map: Add support for user input

runelite-client/src/main/java/net/runelite/client/plugins/teamcapes/TeamCapesPlugin.java
For most of people this plugin is not relevant so it should be disabled
by default as it adds unnecessary clutter in populated areas.
=> Disable team capes plugin by default

runelite-client/src/main/java/net/runelite/client/plugins/notes/NotesPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/notes/NotesPlugin.java
When logged into a sync account, the notes plugin was loading notes before the ConfigClient updated config. Add an event to update notes when the config changes.
=> Fix notes plugin loading notes from account

http-api/src/main/java/net/runelite/http/api/worlds/World.java, http-service/src/main/java/net/runelite/http/service/worlds/WorldsService.java, runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/World.java, runelite-api/src/main/java/net/runelite/api/WorldType.java, runelite-client/src/main/java/net/runelite/client/plugins/defaultworld/DefaultWorldConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/defaultworld/DefaultWorldPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSWorldMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java, runescape-client/src/main/java/Client.java, runescape-client/src/main/java/TotalQuantityComparator.java, runescape-client/src/main/java/UrlRequester.java
- Add default world plugin where user will be able to set his default
world. In case invalid world is set, the client default/selected one
will be used instead.
- Add setWorld to the RuneLite API
- Export World from RS client
- Export changeWorld method
- Create new method for creating RuneScape world
- Add support for mask and index fields to the WorldService.
Fixes #475 
Closes #749
=> Default world

runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanChatPlugin.java
Fixes #583 
There was honestly no need for this check here since messages with the type `CLANCHAT` would always require the clan chat to have at least 1 member (aside from when we set them e.g. trough chat history). Unless there's something I don't know of, this should work just fine.
=> Fix clanchat messages not showing rank icons during region loading

runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
Remove the first duplicate config check for Anti-venom+ in TimersPlugin (other one begins line 175, left this one so that all antivenom are grouped)
=> Remove duplicate anti-venom+ config check

runelite-client/src/main/java/net/runelite/client/game/ItemManager.java, runelite-client/src/main/java/net/runelite/client/plugins/blastfurnace/BlastFurnaceCofferOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/examine/ExaminePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeOfferSlot.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java, runelite-client/src/main/java/net/runelite/client/util/StackFormatter.java, runelite-client/src/test/java/net/runelite/client/util/StackFormatterTest.java
Adds a util class with three formatter functions:
- runescape style (which matches the one in game)
- "pretty" style with locale-aware formatting and 3 sig figs
- string to number for converting the other direction (open to criticism, it was a little tricky to find a good method)
Open to suggestions for a better name. ItemManager called it "stack size" so that's what I went with.
Additionally, it updates plugins using gp to use the new formatter.
Before
After
I wish I had a better variety of stuff to show it off on but I'm a poor noob
Addresses issue #764
=> Consistent number formatting for stacks

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java
The color for default, non-highlighted ground items is now configurable.
=> Allow customization of the default color for ground items

runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java
This allows the user to disable the skill icons on XP drops.
Fixes #801
=> Allow disabling of the skill icons on XP drops

runelite-client/src/main/java/net/runelite/client/ui/overlay/components/TooltipComponent.java
Fixes #866 
Ideally we should probably have some parser util that can do a better job of parsing their markup language, one that gives some iterateable collection containing elements such as color change, regular text, modicons, and replace TooltipComponent's parser with that.. But this is a quick fix to get arrows to work.
=> runelite-client: fix Use tooltip arrow not being displayed

runelite-api/src/main/java/net/runelite/api/Perspective.java
Fixes Perspective#worldToMinimap not returning correct values if in fixed mode and using the stretched fixed mode plugin.
I looked for other usages of Canvas width/size and couldn't find any that would be affected by the same behaviour.
Fixes #846
=> runelite-api: fix worldToMiniMap not working correctly in stretched mode

runelite-client/src/main/java/net/runelite/client/plugins/barbarianassault/BarbarianAssaultConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/barbarianassault/BarbarianAssaultPlugin.java
Being able to spam left click without paying attention to what actually needs to be called is overpowered. Until we come up with something better (like binding the different calls to Ctrl, Alt, Ctrl+Alt) we shouldn't offer this particular feature.
=> Remove left click calling from BA plugin

runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeItemPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeSearchPanel.java
before it was just returning if the image icon was not found, now it should still display the item, just with no icon if it is null
=> ge search: remove null check from item icon

http-api/src/main/java/net/runelite/http/api/item/ItemClient.java, runelite-client/src/main/java/net/runelite/client/game/SkillIconManager.java, runelite-client/src/main/java/net/runelite/client/plugins/account/AccountPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/barbarianassault/BarbarianAssaultPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/feed/FeedPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/feed/FeedPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/fightcave/FightCaveOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeSearchPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java, runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/info/InfoPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/Book.java, runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/KourendLibraryPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/notes/NotesPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/poh/PohIcons.java, runelite-client/src/main/java/net/runelite/client/plugins/puzzlesolver/PuzzleSolverOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/specorb/SpecOrbOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerPlugin.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java, runelite-client/src/main/java/net/runelite/client/ui/TitleToolbar.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/MinimapOrb.java
ImageIO.read(...) is not really thread-safe, as calling it on several threads at the same time can cause NullPointerExceptions and ConcurrentModificationExceptions, as reported in https://bugs.openjdk.java.net/browse/JDK-8058973 and https://bugs.openjdk.java.net/browse/JDK-6986863.
This commit changes all usages of this method to synchronize on ImageIO.class, so the method is never run asynchronously.
This fixes the feed plugin throwing these exceptions at times.
=> Synchronize usages of ImageIO.read(...)

runelite-api/src/main/java/net/runelite/api/Perspective.java
Fixes a problem where the coordinates of the bottom right and bottom left corner of a canvas tile would lie on the neighbouring tiles. This resulted in weird tile indicators when those neighbouring tiles where on a different plane. This only occurred on bridges as far as I know.
Before:
After:
=> More accurately draw tiles to canvas

runelite-client/src/main/java/net/runelite/client/plugins/tileindicators/TileIndicatorsOverlay.java
Stops the tile indicator plugin from always calculating the tile indicator even though it is not going to be drawn.
=> Remove unneeded drawRegionTile calls

runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
Add ability to open screenshot folder by right clicking the screenshot button. This partially fixes #797.
This is similar to how OSB lets you quickly access the screenshot folder.
=> Add right click menu to screenshot button

runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/LocationOverlay.java
Adds a panel which will display current tile in relation to world location as well as display the current map regions
=> dev tools: add location to dev tools plugin

runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/hunter/TrapOverlay.java
Since we have the ability to render behind widgets now, the "check if viewport contains" is not necessary anymore. Instead replace it with distance check to remove it if ran off screen.
=> Remove viewport contains from cannon/hunter plugin

runelite-client/src/main/java/net/runelite/client/plugins/hunter/HunterPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/hunter/HunterTrap.java, runelite-client/src/main/java/net/runelite/client/plugins/hunter/TrapOverlay.java
This changes the hunter plugin to not iterate over all tiles, and continue working across loading zones. This also changes how the HunterTrap is stored. Before it would use getWorldLocation in its equals and hashCode, which can change over time due to loading boundaries.
Before:
After:
=> hunter plugin: Don't iterate over all tiles

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/NPC.java, runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoOverlay.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSNPCMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java, runescape-api/src/main/java/net/runelite/rs/api/RSNPC.java
If you fire a ranged weapon and stop interacting with an enemy, it's opponent info will still be on screen but it won't update once it's taken damage which can be annoying. Now it will update until the info panel disapears.
=> Continue to update opponent info while on screen

runelite-client/src/main/java/net/runelite/client/plugins/defaultworld/DefaultWorldPlugin.java
Automatically append 300 to every world that is lower than 300 to
support both f.e. 22 and 322 formats for specifying the world.
=> Allow specifying default world in [0-9]{2} format

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java, runescape-client/src/main/java/class169.java
The following menu entries will now be left-click:
- Pickpocket (on Man, Woman, etc. You still need attack option set to hidden)
- Bank (on bank NPC)
- Exchange (on Grand Exchange Clerk, Tool Leprechaun, Void Knight, etc.)
- Harpoon (on swordfish and shark Fishing spot)
- Trade (on Shop keeper, Shop assistant, etc.)
- Travel (includes Take-boat, Pay-fare and Charter. On Customs officer, Monk of Entrana, Trader Crewmember, Squire, etc.)
- Pay (on farmers like Elstan, Heskel, etc.)
- Home (on POH Portal)
- Last destination (XXX) (on Fairy ring)
- Reset (on box trap)
- Investigate (on Catacombs of Kourend entrance statue)
- Rub (on jewellery)
- Teleport (on equipable items)
This plugin will not bring the menu entry to the top of the menu if the menu entry it's swapped with wouldn't be at the …
=> Add Menu Entry Swapper plugin

runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsMinimapOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsService.java
Move drawing player names on minimap to separate overlay, so the minimap
names can be rendered over minimap in resizeable mode.
Fixes #940
=> Fix drawing of player names on minimap

runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsMinimapOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsService.java, runelite-mixins/src/main/java/net/runelite/mixins/RSPlayerMixin.java
- Add null check for getRsName, because when logging to game, sometimes it
is null, and throws NPE.
- Change the PlayerIndicators model to use injection
- Create new set from overlays when getOverlays is called
=> Fix NPEs on startup from PlayerIndicators

runelite-client/src/main/java/net/runelite/client/plugins/regenmeter/RegenMeterPlugin.java
Spec orb regen was off by 1 tick, which made it get more and more off as the regen went on
After regening from 0 to 100 the regen progress bar was off by almost 1/4 of the bar
=> Fix spec orb regen timing

runelite-client/src/main/java/net/runelite/client/callback/Hooks.java, runelite-mixins/src/main/java/net/runelite/mixins/MenuEntryEventMixin.java, runescape-client/src/main/java/class169.java
The previously-hooked addMenuEntry method in runescape-client is one that occasionally gets inlined which can cause weird breakages like MenuEntryAdded not getting fired for menu entries defined in
ItemDefinitions. Hooking the menuOptionCount field should be more reliable.
Fixes #936
=> Use a fieldhook for MenuEntryAdded events

runelite-client/src/main/java/net/runelite/client/plugins/herbiboars/Herbiboars.java
Add null check for client.getMapRegions because during plugin startup
when game is loading, they are null.
=> Fix herbiboar plugin NPE on startup

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java
Add an option in plugin config to set a time for the infobox to expire
Change setTask to only fire on initial login (to stop infobox appearing on every map change)
Infobox reappears on getting task, checking task, killing slayer monster, and initial log in
First contribution to a project of this nature so please let me know if there is anything that should be changed
Closes #526
=> Add timer to hide Slayer infobox

runelite-client/src/main/java/net/runelite/client/plugins/agilityplugin/AgilityPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/herbiboars/HerbiboarOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/herbiboars/HerbiboarPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/herbiboars/Herbiboars.java
- Remove unused variables in Herbiboar plugin
- Rename Herbiboars to HerbiboarPlugin
- Rename HerbiboarsOverlay to HerbiboarOverlay
- Rename "Herbiboars" to "Herbiboar" plugin name
- Fix Herbiboar plugin naming conventions
- Fix AgilityPlugin naming conventions
=> Fix agility plugin and herbiboar plugin codestyle

runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/instancemap/InstanceMapInputListener.java, runelite-client/src/main/java/net/runelite/client/plugins/instancemap/InstanceMapOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/instancemap/InstanceMapPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/WoodcuttingOverlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/BackgroundComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/ImagePanelComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/PanelComponent.java
- Set correct offsets for overlays based on resizable or fixed mode
- Change PanelComponent inside padding to be slighly smaller
- Set correct offset to instance map
- Change instance map to use BackgroundComponent border
Before:
After:
=> Set correct offsets to overlays, smaller panels

runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
- Removes the resetting of menu entries after a loading screen
before:
after:
=> Remove reset menu entries

runelite-client/src/main/java/net/runelite/client/ui/overlay/components/TooltipComponent.java
- Swap originalWidth with width
=> Fix tooltip modicon OutOfBounds

runelite-client/src/main/java/net/runelite/client/plugins/itemprices/ItemPricesConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/itemprices/ItemPricesOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/itemprices/ItemPricesPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/mousehighlight/MouseHighlightOverlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/tooltip/TooltipManager.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/tooltip/TooltipOverlay.java
Options are added to the mouse highlight plugin to display exchange prices and/or high alch values on mouse tooltips over items in the inventory and bank. (options are off by default)
The value-based color highlights are ripped from the ground items plugin, including color config options. It may be useful in the future to consolidate these options somewhere so other plugins can use the same options. I know there was at least one more PR that did some value-based highlighting.
This also includes refactoring of the mouse highlight overlay render method to use a switch on the first menu action type to determine whether tooltips should be drawn (and if anything should be added to them). I think this should be easier to maintain / add to in the future.
Also, while I was there, I removed …
=> Add Item Prices plugin for item price/value tooltips

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemInputListener.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java
- Alt is the default key bind
- It will display all ground items when key bind is pressed
Fixes #453
=> ground items: add support for quickly hiding/highlighting items

runelite-client/src/main/java/net/runelite/client/plugins/itemprices/ItemPricesOverlay.java
Displaying amount of items in stack is unnecessary because the
information is shown on item itself, so it is just making the tooltip
unnecessary big.
=> Do not display stack in price tooltips

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java, runelite-client/src/main/java/net/runelite/client/ui/JShadowedLabel.java, runelite-client/src/main/java/net/runelite/client/ui/JShadowedLabelUI.java
This adds a shadow to your current level, changes the text color to yellow, and makes the progress bars use HSB rather than RGB interpolation.
=> Make XP panel easier to read

runelite-client/src/main/java/net/runelite/client/plugins/prayflick/PrayerFlickOverlay.java
Removed the white background on the the prayer orb when overlay was on which made it hard to tell if quick prayers were on
Fixes #972
=> prayer flick overlay: remove background arc

runelite-client/src/main/java/net/runelite/client/plugins/agilityplugin/AgilityConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcClickboxOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcMinimapOverlay.java
- Remove "Placeholder" description of Agility plugin and replace it with real description
- For consistent plugin naming "NPC Highlighting" plugin should be named NPC Indicators
to follow the naming of Tile Indicators and Player Indicators.
- Title-case chat commands plugin name
=> Consistent plugin naming

cache/src/main/java/net/runelite/cache/script/Instructions.java, cache/src/main/java/net/runelite/cache/script/Opcodes.java, runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/SettingsTracker.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/VarbitMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java, runescape-client/src/main/java/Client.java, runescape-client/src/main/java/NPCComposition.java, runescape-client/src/main/java/ObjectComposition.java, runescape-client/src/main/java/Timer.java, runescape-client/src/main/java/World.java, runescape-client/src/main/java/class110.java, runescape-client/src/main/java/class237.java, runescape-client/src/main/java/class25.java, runescape-client/src/main/java/class281.java, runescape-client/src/main/java/class3.java, runescape-client/src/main/java/class5.java
This changes the internal naming for `widgetSettings` and `settings` to `clientVarps` and `serverVarps` respectively.
Also removes `Client#getSettings()` since `Client#getVarps()` will essentially return the same values.
=> Rename widgetSettings and settings

runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java
I'm not 100% sure this is what is causing our config corruption problem, but this can be called from multiple threads and is not locked at all.
=> configmanager: Synchronize disk access

runelite-client/src/main/java/net/runelite/client/ui/overlay/components/TooltipComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/tooltip/Tooltip.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/tooltip/TooltipOverlay.java
- Move tooltip default position to right-bottom of mouse cursor
- Automatically adjust cursor position based on space around the tooltip
- Remove the ability from Tooltip manager to have other tooltips other
than mouse tooltips (for custom-positioned tooltips use tooltip
component directly)
Depends on: #989 
Depends on: #1071 
Preview:
=> Move tooltip to the right of the mouse

runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
Sometimes right after login overlays can be null instead of empty list.
Add null check to prevent ending on NPE.
=> Add null-check for overlays in OverlayRenderer

runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonSpots.java
=> Fix Lizardmen cannon spot plane

runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonSpots.java
Add Cave Horror cannon spot to the Cannon Plugin.
Preview:
=> Add Cave Horror cannon spot

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemInputListener.java
This will allow the default behaviour of dragging the screen camera whilst holding alt again, previously it would consume the event completely while alt was held.
=> Ground items: Only consume mouse clicks when a checkbox has been clicked

deobfuscator/src/main/java/net/runelite/asm/attributes/code/instructions/LDC.java, deobfuscator/src/main/java/net/runelite/asm/pool/Class.java, runelite-mixins/src/main/java/net/runelite/mixins/ScriptVMMixin.java, runescape-client-injector-plugin/src/main/java/net/runelite/injector/Inject.java, runescape-client-injector-plugin/src/main/java/net/runelite/injector/MixinInjector.java
This makes the injector transform `XXMixin.class` into the name of the class being injected into, and forcibly injects `$assertionsDisabled` if it doesn't exist already in the target. This also fixes multiple mixins on the same class not being able to use `<init>` and `<clinit>`.
=> injector: Allow use of assert

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/examine/ExaminePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeItemPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeOfferSlot.java, runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java, runelite-client/src/main/java/net/runelite/client/plugins/itemprices/ItemPricesOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZoneOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpPanel.java, runelite-client/src/main/java/net/runelite/client/util/StackFormatter.java
- Add formatNumber methods to StackFormatter that reuse the NumberFormat
instance
- Use new methods instead of using created NumberFormats on other places
- Use new formatter in NightmareZonePlugin
=> Add formatNumber methods to StackFormatter

runelite-client/src/main/java/net/runelite/client/plugins/itemprices/ItemPricesOverlay.java
=> Item price tooltip: use linebreak instead of comma

runelite-api/src/main/java/net/runelite/api/Varbits.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatChanges.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/StatChange.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/special/SpicyStew.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/stats/Stat.java
Adds 4 new varbit indices to check the latest stew's ingredients. All that's left is to decide on the colour logic, which is a bit ambiguous due to the random nature of the stew's boosts.
Submitting this early just in case anyone wants to try finishing it themselves, I'm off for today.
=> Add spicy stews to item stats plugin

runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java
Add null-checks for Client, what can be null when in Vanilla to
MenuManager (e.g HiscorePlugin is calling it when Client can be null
when it is running).
=> Add null-check for Client to MenuManager

runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePlugin.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java, runelite-client/src/main/java/net/runelite/client/ui/NavigationButton.java, runelite-client/src/main/java/net/runelite/client/util/SwingUtil.java
- Remove changing of isSelected property on navigation button in order
to open it
- Change navigation button handling to always "click" the wrapped button
no matter if button is selected or not and let the special callback
handle it
=> Expand panels based on click event not isSelected

runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
Fix screenshot offset by exposing getCanvasOffset from ClientUI and
using it when taking screenshots with game frame enabled.
=> Add getCanvasOffset to clientUI, fix screenshots

runelite-client/src/main/java/net/runelite/client/plugins/dailytaskindicators/DailyTasksPlugin.java
- Fixes #1068
Previously it'd check if the value of the essence varbit is LESS THAN 0, rather than EQUAL TO 0.
=> Fix daily task indicators

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/VarClient.java, runelite-api/src/main/java/net/runelite/api/Varcs.java, runelite-client/src/main/java/net/runelite/client/plugins/mousehighlight/MouseHighlightOverlay.java, runelite-mixins/src/main/java/net/runelite/mixins/RSVarcsMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java, runescape-api/src/main/java/net/runelite/rs/api/RSVarcs.java, runescape-client/src/main/java/BoundingBox.java, runescape-client/src/main/java/Client.java, runescape-client/src/main/java/FileRequest.java, runescape-client/src/main/java/FontName.java, runescape-client/src/main/java/GZipDecompressor.java, runescape-client/src/main/java/GameObject.java, runescape-client/src/main/java/VarCInt.java, runescape-client/src/main/java/VarCString.java, runescape-client/src/main/java/Varcs.java, runescape-client/src/main/java/Widget.java, runescape-client/src/main/java/class132.java, runescape-client/src/main/java/class153.java, runescape-client/src/main/java/class190.java, runescape-client/src/main/java/class25.java, runescape-client/src/main/java/class3.java, runescape-client/src/main/java/class47.java, runescape-client/src/main/java/class88.java, runescape-client/src/main/java/class95.java
- Add mappings for Varc class and varc field in it
- Update mappings that reference to Varc field
- Update widget mappings for boolean that determines if widget have
mouse action
- When rs tooltips are visible, don't display our tooltips in Mouse
Highlighting plugin
Preview:
=> Do not display mouse tooltips over RS tooltips

runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZoneConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZonePlugin.java
A pretty simple change, just scans the chat like the overload notification. This makes afk NMZ completely notification driven if you, like me, want to collect zappers or power surges for extra points/prayer.
=> Add notifications for NMZ power-up spawns

runelite-api/src/main/java/net/runelite/api/Varbits.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPointsOverlay.java
Replaces the default client's point box with our own overlay. This will also allow the user to move it around freely.
Also shows raid party size.
=> Replace default raids points widget with our own overlay

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
`SwingUtil` adds a click event to focus the frame, but the frame isn't fully built when the icon is created. Clicking after the icon was made and before the frame was built caused a crash. Moved the icon creation to after the frame is built, should resolve the problem. Fixes #1130.
=> Fix tray icon crash when clicked quickly on start

runelite-client/src/main/resources/npc_health.json
Fixes level 172 Black demons not having hp numbers in the opponent info plugin.
=> Fix capitalization of 'Black demon' in npc_health.json

runelite-client/src/main/java/net/runelite/client/plugins/kingdomofmiscellania/KingdomConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/kingdomofmiscellania/KingdomPlugin.java
To help mitigate complaints on the infobox appearing when they never asked.
=> Disabled kingdom plugin by default, and it's options

runelite-api/src/main/java/net/runelite/api/events/WidgetLoaded.java, runelite-client/src/main/java/net/runelite/client/plugins/reorderprayers/ReorderPrayersPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java, runescape-client/src/main/java/Client.java, runescape-client/src/main/java/FriendManager.java
- Fixes widget loaded event
runWidgetOnLoadListener has not been inlined since atleast release 1.2.2 so it should be stable
=> Fix widget loaded event for prayer reordering

runelite-client/src/main/java/net/runelite/client/RuneLite.java
To remove the need for restarting plugins or reloading configurations
when plugins are loaded and then their confifguration changes, load
session configuration in advance.
Closes: #1121
=> Move loading of session before starting plugins

runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
Move viewport widget check below logged in check and click to play
screen check.
Fixes: #1190
=> Move viewport check below gamestate and CTP

runelite-api/src/main/java/net/runelite/api/events/ItemLayerChanged.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItem.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSTileMixin.java
- Reduce amout of iterations per frame by pre-collecting the ground
items on game tick
- Collect ground items in ground item plugins and pre-compute some
easy-to-get values
- Replace the looping over all tiles with looping over collected ground
items
- Change GroundItemOverlay logic to support single list of items instead
of multi-dimensional array
- Color hidden ground items gray when in item highlight mode to show
different between non-hidden and hidden items.
Closes: #882 
=> Improve ground items plugin

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java
Adds simple number input for the ground item plugin.
Fixes #1126
=> Add configuration options for ground item plugin

runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/game/ItemManager.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java
- Invalidate item manager composition cache when person is hopping or goes
to login screen to prevent issues with changing from p2p to f2p worlds.
- Instead of clearing ground items after game state change, just mark the
ground items dirty.
=> Invalidate ground items and item composition cache

runelite-client/src/main/java/net/runelite/client/plugins/agilityplugin/AgilityPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/agilityplugin/Courses.java
Some courses have obstacles that have XP equal to another courses last obstacle making it trigger a new course. This adds a region check to make sure you are in the correct region before setting a new course
=> agility plugin: Add region check to lap counter

runelite-client/src/main/java/net/runelite/client/game/ItemManager.java
To prevent ItemManager initializing with null client change reference to
the client to Provider<Client>.
=> Use provider for client in item manager

runelite-client/src/main/java/net/runelite/client/plugins/info/InfoPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/info/InfoPlugin.java, runelite-client/src/main/java/net/runelite/client/ui/ClientPluginToolbar.java, runelite-client/src/main/java/net/runelite/client/ui/ClientTitleToolbar.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
When native window decorations are enabled (e.g when custom window
chrome is disabled), to reduce code complexity, but to maintain current
usability (e.g prevent adding new UI elements in order to position the
icons somewhere) move the title toolbar icons to sidebar.
Preview:
=> Move title toolbar buttons to sidebar in native

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/Perspective.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
Clips overlays on the above scene layer to the size and position of the viewport so the text doesn't draw over the minimap
Before:
After:
=> Clip overlays on the above scene layer to the viewport

runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsInput.java, runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPlugin.java
currently, npc tagging causes some npc's to have the tag option as left click which can cause miss clicks (most notably when hunting chins). This adds the ability to add the "tag" menu option only when shift is being pressed
Fixes #1082
=> npc indicator: add shift right click to add tag option

runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSpot.java
Add missing fishing spot on Mount Qudamortem.
Closes: #848
=> Add raids fishing spot

runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/pestcontrol/PestControlOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/pestcontrol/PestControlPlugin.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayUtil.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/TooltipComponent.java
- Add option for toggling between small and large font for in-game
overlays
- Normalize the font size usage around overlays
Closes: #1214
Preview:
=> Add option for enabling small font

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java
The box was based off the width of the font, which made the box super small when using the small RS font. This will provide a fixed rectangle size on any font.
before
after
=> ground item overlay: Fix boxes appearing very small with small font

runelite-api/src/main/java/net/runelite/api/queries/InventoryItemQuery.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/AbyssOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftPlugin.java
Highlights the Dark mage NPC tile in the abyss when there is a degraded pouch in your inventory. The goal is to help players (like myself) who constantly forget to repair degraded pouches.
This is my first contribution attempt so any feedback / tips very welcome!
=> Highlight dark mage NPC in the center of the abyss when inventory contains a degraded pouch

runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java
To make the behaviour consistent with the spinners, save configuration
value of text field when user presses enter.
=> Save text configuration value on enter

runelite-client/src/main/java/net/runelite/client/plugins/account/AccountPlugin.java
This helps clarify what the login and logout buttons do.
With the upcoming change to add the login/logout button to the side bar adding a little more information to the tooltip may be helpful.
=> Add small clarification to Account Plugin tooltip

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/EmoteClue.java
=> Fixed typo for lighthouse clue

runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftPlugin.java
The client was throwing a null pointer exception on the runecrafting plugin and I wasn't even runecrafting, a small null check was added to prevent this.
=> Add a null check to Runecrafting Plugin.

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
This was oversight and swaps pickpocket options when black-jacking what
is something that other clients don't do.
=> Swap pickpocket only on H.A.M. members

runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/screenshot/ScreenshotPluginTest.java
Fixes #1060.
Plugin now uses a regex for validation of text in the level-up widget, because that widget is sometimes re-used for other game dialogs. Those dialogs will now be safely ignored.
=> Fix ArrayIndexOutOfBounds errors in screenshot plugin

runelite-api/src/main/java/net/runelite/api/Actor.java, runelite-mixins/src/main/java/net/runelite/mixins/RSActorMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSActor.java
Actor.getWorldLocation is currently based on getX/getY which is the current position of the actor in the client. We should instead base it on pathX[0]/pathY[0] which is the location of the actor on the server.
=> Fix Actor.getWorldLocation to use pathX/pathY instead of getX/getY

runelite-client/src/main/java/net/runelite/client/callback/Hooks.java
It makes more sense to have the game tick event run after npcs, players, game object etc have all been updated. This fixes a few issues like [#1276](https://github.com/runelite/runelite/issues/1276).
The fix for the hunter plugin also depends on pull [#1325](https://github.com/runelite/runelite/pull/1325).
=> Update game tick event to run after packets have been processed

runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsOverlay.java
Devtools gets null pointers when drawing NPCs in lumbridge on these compositions.
=> Lumbridge npcs have some bad compositions and return null

runelite-client/src/main/java/net/runelite/client/plugins/attackstyles/AttackStyle.java, runelite-client/src/main/java/net/runelite/client/plugins/attackstyles/AttackStylesConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/attackstyles/AttackStylesOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/attackstyles/AttackStylesPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/attackstyles/WeaponType.java, runelite-client/src/test/java/net/runelite/client/plugins/attackstyles/AttackStylesPluginTest.java
Motivated by a visitor on Discord who didn't realise this was the plugin he was looking for when he asked us to add it. The label needs to describe the plugin's scope more clearly.
This pr also renames code references for clarity, although not the `keyName` of course.
=> Rename "Attack Indicators" plugin to "Attack Styles"

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerPlugin.java
Fix #1273
Upon logging into a new character or world mode (which has different XPs) we clear the info boxes in the panel.
Yet we forget to clear the data that powers those boxes. 
Simple, clear the data AND the ui.
=> Reset XP on log-in of another character / mode

runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java
Fix bank title bar, item count and item container widget ids due to
changes in widget IDs (possibly caused by new container).
=> Fix bank widget IDs due to container changes

runelite-client/src/main/java/net/runelite/client/plugins/banktags/BankTagsPlugin.java
Fixes the placeholder release option by only consuming the event when the edit tags is clicked
=> Fix bank placeholder release option

runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePlugin.java
Solves the issue with looking up ironmen from the chat (fails lookup because of `<img>`)
Fixes #1436
=> Remove tags from highscore lookup

runelite-api/src/main/java/net/runelite/api/Perspective.java
All uses of `worldToMiniMap` seem to expect it to be null if something fails, when it actuality it returns a Point(-1, -1).
This caused weird behavior for some drawing on the minimap. Tested and it solved #1385. 
My first PR on here and though it might be a very small one, please tell me if I did something incorrectly.
=> Fix worldToMiniMap for locations outside of range - fixes #1385

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/EmoteClue.java
Change worldpoint for Panic by the mausoleum in Morytania emote clue
Fixes issue https://github.com/runelite/runelite/issues/1425
=> Fix worldpoint for mausoleum clue

runelite-api/src/main/java/net/runelite/api/SpriteID.java, runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java
This fixes #555.
Plugin wasn't actually checking whether the XP drop widgets were for the relevant combat skill before recolouring them, so I've added their SpriteIDs to verify the skill icons as they appear.
Both grouped and ungrouped XP drops work as expected now.
=> Fix XP Drop plugin recolouring ALL drops whenever a combat prayer is enabled

runelite-client/src/main/java/net/runelite/client/plugins/implings/ImplingMinimapOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/implings/ImplingsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/implings/ImplingsPlugin.java
- Change Magpie impling name in `ImplingsConfig`
- Add config option for placing impling names on minimap
Note to the main authors of RuneLite, it would be nice if the README could be updated with a How-To for running test suites, and launching the client locally.
=> Impling Configuration Improvements

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpPanel.java, runelite-client/src/main/java/net/runelite/client/util/LinkBrowser.java
- Add "overall" link to the top of the XP panel that will link logged in
user to the website XP tracker showing his overall gains in 1 week
- Add right click menu to open XP tracker for each skill, same rules as
in "overall"
Preview:
=> Add link to web XP tracker to XP panel

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
As target is lowercased, make the condition lowercased too so it can be
properly matched.
Fixes: #1478
=> Make condition for H.A.M. pickpockets lowercase

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpPanel.java
Due to HttpUrl.Builder being mutable, this causes duplicate URL path
segments when tracking more than 1 skill at a time.
=> Do not reuse HttpUrl.builder for building xp urls

runelite-client/src/main/java/net/runelite/client/ui/overlay/tooltip/TooltipOverlay.java
This is more noticeable for larger tooltips, but changing this feels more natural in general.
Before:
After:
=> tooltips: hug edge of screen instead of jumping

runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
Instead of applying this configuration option to both layouted overlays
that are supposed to follow XP tracker layout 1 to 1, apply this setting
only for dynamic overlays and tooltsip (e.g mouse highlighting, ground
items, player names).
Closes: #1288
=> Apply small font option only to dynamic overlays

runelite-api/src/main/java/net/runelite/api/Perspective.java
Same adjustment as https://github.com/runelite/runelite/pull/888 but for the south and west side of the tile.
Before:
After:
=> More accurately draw tile indicators 

runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java
Correct time is 12 seconds not 15.
=> Change magic imbue timer to 12 seconds

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Remove both "teleport" and "cast bloom" menu entry swapping from menu
entry swapper plugin as they both can be done with shift-click
customization, and usually the teleport and wear option is not wanted to
be swapped.
=> Remove "teleport" and "cast bloom" swapping

runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsOverlay.java
Prevents player names from drawing over certain overlays.
example: XP Globe tooltip
before:
after:
=> Reduce player indicators overlay priority to MED

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Add an option for "Teleport to Abyss" for the Menu Entry Swapper plugin. This affects the mage of zamorak NPC.
I'm not sure if other clients offer this feature.
=> Add "Teleport to Abyss" to Menu Entry Swapper

runelite-client/src/main/java/net/runelite/client/plugins/bankvalue/BankCalculation.java, runelite-client/src/main/java/net/runelite/client/plugins/bankvalue/BankValuePlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/bankvalue/BankCalculationTest.java
Use longs instead of ints for per-item price calculations to avoid int
overflows.
Fixes: #1460
=> Fix bank value overflow

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Currently it doesn't swap Dismantle and Reset for failed traps.
=> Menu Entry Swapper: Add 'Reset' on dismanteled traps and 'Lay' on expired traps as first value.

runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java
the current timer starts at 4 mins 50 seconds, but the enhance wears off at the 15 second warning. this means the actual timer is 4 mins 35 seconds. [reference](https://imgur.com/a/NUMe7)
=> fix prayer enhance timer

runelite-client/src/main/java/net/runelite/client/callback/Hooks.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java, runescape-client/src/main/java/Client.java
This fixes the issue with the menu going "off screen" and text overflowing the menu background when the menu entries have been changed on MenuOpened.
Before:
After:
=> Change menuOpened from FieldHook to Hook

runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeGemOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeSession.java
When mining with an alumet of glory the chance of receiving uncut gems increases significantly.
This introduces an overlay to the Motherlode Mine Plugin which shows the numer of gems found during the current mining session.
Screenshot:
=> Motherlode Mine - Gem overlay

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java
When user does not have any more clues left in inventory, hide clue
scroll interface.
Depends on: #1569 
=> Hide clue scroll interface when no clue is present

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/AnagramClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CipherClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/EmoteClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/FairyRingClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/LocationClueScroll.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/MapClue.java
- Add new LocationClueScroll interface that will mark location-based
clues
- Move setting of the hint arrows to ClueScrollPlugin
- Properly prioritize hint arrows (always try location first, but then
override with NPC/object locations)
Closes #1609
Depends on #1493 for proper hiding of the clue interfaces
Preview:
=> Centralize setting of hint arrows for clues

runelite-api/src/main/java/net/runelite/api/coords/Angle.java, runelite-api/src/main/java/net/runelite/api/coords/Direction.java, runelite-api/src/main/java/net/runelite/api/coords/WorldPoint.java, runelite-api/src/test/java/net/runelite/api/coords/AngleTest.java, runelite-client/src/main/java/net/runelite/client/plugins/hunter/HunterPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSGameObjectMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSGameObject.java
This is a bugfix for the problems described in #1169 and #1553.
**Problem**:  The hunter plugin stores the incorrect trap tile depending on the angle of the small tree. 
**Solution**: Whenever a trap change is detected that is not in our hash map (and thus null), we cannot assume it is our trap blindly. For each of these traps, we look up adjacent tiles in the hash map. If a tile is one of our keys, we have identified our trap. The changes also separate salamander handling to its own case body, in order to reduce the scope of these scans to salamanders only.
**Considerations**: While I could have shortened the code that was added, I wanted to ensure that there were no unnecessary calculations that could impact performance even in the smallest degree. That's why there are several …
=> Hunter Plugin: Fix salamander net display (Fixed)

runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeOverlay.java
To correctly layour motherlode overlay, change it's layer from
ABOVE_WIDGETS to BELOW_WIDGETS (what should be the correct layer for it
anyway).
=> Fix layer of MotherlodeOverlay

runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java
The ChatMessage event runs before the ProjectileMoved event but the server seems to process them in the opposite order. The cannonballs left counter would go to 31, which was reduced to 30 by a check, but the projectile event (if fired in the same game tick) would then reduce it to 29 when it should really have been 30, so the counter would always show 1 less cannonball than the cannon actually had, and eventually it'd go to -1. This pull removes the check which fixes the issue.
=> Fix cannon cannonball count

runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeInputListener.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangePlugin.java
Note: This does not "add" a tooltip, but instead replaces the default action.
Since clicking while holding ALT searches the GE, update the default action so the player can discover that the functionality exists.
Example:
Depends on #1319.
I'll probably rebase if PR #1319 gets merged.
=> Add tooltips when pressing ALT for searching the GE

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/EmoteClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/emote/AllRequirementsCollection.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/emote/AnyRequirementCollection.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/emote/Emote.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/emote/ItemRequirement.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/emote/RangeItemRequirement.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/emote/SingleItemRequirement.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/emote/SlotLimitationRequirement.java
Closes #1429 
Closes #1299 
Group item variants:
You no longer must wear a specific type of an item when any type can be used for a clue.
Example: before it would display "Red boater" for "wear any boater", now it displays "Any boater".
Displaying when to unequip items:
=> cluescrolls: group emote item variants + display when to unequip items

runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeSackOverlay.java
- When there is 0 deposits left/sack is completely full color the entire
panel red for strong visual indicator to stop mining immediately
- When there is 1 deposit left, color the line with deposit red to
indicate that you are close to sack being full and after this inventory
you should bank
Closes #1702
Preview:
=> Stronger visual indicators for MLM sack

runelite-client/pom.xml
After changes to artifacts names, fix shading of runelite-client to make
it keep everything that is required.
=> Fix runelite-client shading

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/MapClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/ObjectClueScroll.java
- Instead of using object world locations and using query to find
objects, if object clue also has location, just find all objects on tile
on that clue's location and check if ID is matching
- Fix varrock west bank cryptic clue (what was used also during testing)
Fixes #1692 and fixes #1314 and fixes #1732 
=> Do not use object world locations for clues

runelite-client/src/main/java/net/runelite/client/plugins/stretchedfixedmode/TranslateMouseListener.java
The MouseEvent constructor says in its documentation to pass the extended modifiers. This contains alt, ctrl, meta, etc. Doing this also requires passing down the button pressed in the constructor.
Fixes #1618
=> stretched mode: pass extended modifiers on click

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java
Request from issue #1017
Slayer task amount is now updated correctly when the player uses a Bracelet of Slaughter or an Expeditious Bracelet.
=> Slayer plugin: Added support for slayer bracelets.

runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java
Fix for ref #1751 , works exactly as described in the feature request.
=> Add support for colored HP xp drops if XP drops are splitted and a combat prayer is active

runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingPlugin.java
The default sort of fishing spots ends up drawing further things on top of closer things, as it has no relation to the camera.
To solve this, convert the camera point to a `LocalPoint` and then sort by comparing local points from the NPC to the camera's point. However, the sort is inverted by `-1 *` so that further things are drawn first, and closer things are drawn last--this way closer things are always on top.
Fixes #1737
=> Sort Fishing spots by distance from camera

runelite-client/src/main/java/net/runelite/client/plugins/herbiboars/HerbiboarMinimapOverlay.java
Prevent NPE in herbiboar minimap overlay. This will remove any
performance and blinking issues.
=> Fix herbiboar performance/blinking

runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/InfoBoxComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBoxOverlay.java
allow the user to set the amount of info boxes per row. setting this value to 1 will make the boxes appear vertically. setting it to 0 will default to normal horizontal behavior
I wasn't sure if this config option should be added to the runelite settings, or made an entirely separate "InfoBox" config options. I opted for the first choice, but can easily be changed.
> [9:01 PM] Adam: I would be ok with some stopgap settings on the infobox overlay renderer for max row/column/verticle etc
=> infobox overlay: Configure the amount of info boxes per row

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java, runelite-client/src/main/java/net/runelite/client/util/SwingUtil.java
- Instead of changing the frame width, just revalidate the width to match
minumum size in case the size is smaller than it
- On restoration from maximize, revalidate frame size to not end up in
having small window with opened sidebar
Closes #1795 and closes #1300
=> Cleanup sidebar expanding/closing

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/plugins/entityhider/EntityHiderConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/entityhider/EntityHiderPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/EntityHiderBridgeMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/EntityHiderMixin.java
Allows the user to hide players, npcs and projectiles. The plugin is disabled by default, and when enabled, friends, clan mates and attackers are by default always visible.
It does not support hiding any objects, because I don't think we should hide elements that cannot be walked through, as you cannot walk through these even though they are hidden, which might look like a bug to some users.
It does not remove minimap dots because this turned out to be not that easy to do. Player#hidden and NPCComposition#isMinimapVisible do indeed remove the dots when set to their hidden state, but they also hide the 3D part of the player/npc at the same time, making it so you can't easily separate minimap hiding and game hiding.
Closes #636
=> Add entity hider plugin

runelite-client/src/main/java/net/runelite/client/plugins/agilityplugin/AgilityConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/agilityplugin/AgilityOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/agilityplugin/AgilityPlugin.java
Wouldn't mind seeing this in the client, something I enjoyed in OSB, useful if you aren't really paying attention to the game while training but don't want to miss those marks.
- Added optional highlighting for marks of grace.
- Added two new configuration options to agility settings.
Uses single tile location as only one mark seems to be able to spawn. From my testing there wasn't a need to use a list and store/highlight multiple tiles.
Like so
=> Add Mark of Grace highlighting to Agility plugin

runelite-mixins/src/main/java/net/runelite/mixins/EntityHiderMixin.java
This fixes an issue where the entity hider would not hide the local player when this option was enabled. The cause of this was the player is seen as a clan member and thus it was affected by the isClanMember check.
=> Fix issue where hiding local player would not hide you when in clan

runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/boosts/StatChangeIndicator.java
- Move the next stat change text to the top
- Add stat change indicator when indicators are selected
=> boosts plugin: Add stat change indicator

runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsOverlay.java
This PR adds a toggle to the Player Indicators plugin to allow the user to disable drawing names above players in-game. With this toggle players can reduce the amount of clutter on their screen by limiting the indicators to the minimap only.
(Requested on Discord)
=> Add toggle for drawing overhead player names to PlayerIndicators plugin

runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
This change will make the default option for notification on low HP/Prayer to off by setting it to 0. Also changes logic so that a value of 0 disables the notification.
=> Hp and prayer notification fix

runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotInput.java, runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
As it says on the tin. A config option to enable/disable taking screenshots with the INSERT key. The suggestion mentioned F11 as a possible default, but it is already used by many (me included) in the vanilla client, so I decided to go with INSERT (which as also the OSBuddy default).
I'm a bit unsure about the wording in the config panel and I'd be happy to change it (or other aspects of the code) if you have any other suggestions.
Would fix issues #1013  and #1501
=> Add a shortcut key to take screenshots

runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilitySession.java, runelite-client/src/main/java/net/runelite/client/plugins/agility/Courses.java, runelite-client/src/main/java/net/runelite/client/plugins/agility/LapCounterOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/agility/Obstacles.java
Agility is the only plugin which has the word "plugin" in its package name, which probably would've been corrected if it was PR'd today. This brings it in line with other plugin packages like `plugins.hunter` and `plugins.woodcutting`.
=> Rename agilityplugin package to agility

runelite-client/src/main/java/net/runelite/client/plugins/reorderprayers/ReorderPrayersPlugin.java
Always locks the prayers after turning off the plugin
Fixes: https://github.com/runelite/runelite/issues/2089
=> Fix prayer reorder shutdown

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java
- Save last item ID on either map clue or when reading regular clue
- If this item is removed from inventory reset clue
- If we opened clue but it is uknown simply reset clue overlay
Fixes #1966
Preview:
=> Fix clue resetting

runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java
The cannon can still go out of sync for a short moment when the player goes out of range, but it should now correctly resync when it is reloaded or goes out of ammo.
Fixes #2019
=> Fix cannonball out of sync

runelite-client/src/main/java/net/runelite/client/plugins/reportbutton/ReportButtonPlugin.java
Right now, the timer and clock modes of this plugin frequently jump ahead by 2 seconds instead of 1, due to the `@Schedule` callback being imperfectly in sync with the system seconds. Doubling the frequency of the time updates to 500ms fixes the problem.
Note that there's still some visible jerkiness in the seconds timing, which doesn't improve even when using faster time updates like 100ms, but I'm not aware of a way to fix this.
=> Report button plugin: Fix the skipping seconds digits

runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesOverlay.java
If hovered over an XpGlobe, the timer is now reset so the globe doesn't disappear if you don't gain XP for a while.
Closes #1892 & #2033
=> Fix XpGlobe: now stays on screen while hovered over it

runelite-client/src/main/java/net/runelite/client/plugins/farmingtracker/FarmingTrackerPanel.java
fixes progress bar background not resetting when state = null
=> farming panel: reset progress bar background

runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
Fix of NullPointerException you get when you spam the screenshot button as you login. During development, I noticed getLocalPlayer().getName() is longer null than the getLocalPlayer() method and this causes the error.
=> Fix of NullPointerException

deobfuscator/src/main/java/net/runelite/asm/Method.java, deobfuscator/src/main/java/net/runelite/asm/attributes/code/LocalVariable.java, deobfuscator/src/main/java/net/runelite/asm/attributes/code/Parameter.java, deobfuscator/src/main/java/net/runelite/asm/visitors/CodeVisitor.java, deobfuscator/src/main/java/net/runelite/deob/updater/ParameterRenamer.java, deobfuscator/src/main/java/net/runelite/deob/updater/UpdateMappings.java, http-service/pom.xml, pom.xml, runelite-mixins/pom.xml, runescape-client/pom.xml
Allow the mapper to transfer method parameter names between versions
This was tested by renaming a parameter in runescape-client and running the actions from runelite/updater shell script.
I am going to keep doing further testing, including running this on the next game update.
=> Add support for mapping parameter names

runelite-client/src/main/java/net/runelite/client/plugins/farmingtracker/FarmingTrackerPlugin.java
When teleporting to a updating region (ardy teleport), it would save the new region's varbits to the old region's config.
As reported by `@Littens#3548` on discord.
=> farmingtracker: Prevent saving when teleporting

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpSnapshotSingle.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpSnapshotTotal.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpState.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpStateSingle.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpStateTotal.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpUpdateResult.java
Fixes #1273 
Root cause: copying the current skill XPs on game tick is a bad idea. Only use it to recalculate dynamic values like xp/hr.
Game tick happens AFTER login, but BEFORE current XP loads for the current user and then gets
broadcasted as an event. Therefore, the first login gets 0's. Subsequent logins get the last logged in user's skills! In the previous code, if the current XP was less than the starting XP, it would ignore it and drop the update. Thus, the user would not see any updates.
I attempted to fix it by dropping the data on hard reset (logged in as **different user** or **different world type**) in #1351. However, due to coupling in the view (`XpInfoBox` and `XpPanel`), that was DOA as we lost references to what the UI used to display! Gah! As such, I have redone how the …
=> Redo XP Tracking data structures

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
Due to some race condition, we can't really rely on applet's minimum
size, so add verification for minimum size when size is changed.
Fixes: #2261
=> Verify game's minimum size

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java
=> Allow "degree" and "minute" in coordinate clues

runelite-client/src/main/java/net/runelite/client/ClientLoader.java, runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/UpdateCheckMode.java
Adds `--help` and replaces `--no-rs` and `--disable-update-check` with `--rs`. This also removes use of Optional from ClientLoader because it just called `orElse(null)`.
```
Option                               Description                       
------                               -----------                       
--debug                              Show extra debugging output       
--developer-mode                     Enable developer tools            
--help                               Show this text                    
--rs <[AUTO,NONE,VANILLA,RUNELITE]>  Select client type (default: AUTO)
```
=> runelite-client: Cleanup cli arguments

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpStateSingle.java
Closes #1734
Summary:
If you start a skill like fishing lobster after logging in, you will have the xpGained value as `90`. But, since you just started the skill, it will divide by `0`. This results in the max integer value of `2147483647`.
If you did fletching before fishing, and had a XP per hour of `40000`. Then when you add the fishing XP per hour of `2147483647`, the result overflows and you get a negative number as the total XP per hour.
Solution:
Don't divide by zero, instead suppose that the skill has been active for **at least** 60 seconds. This will result in a fair estimate that improves as the skill continues to be used, rather than the ridiculous estimate of 2 Billion one second and 200K the next second.
60 seconds is chosen over 1 or 5 or 10 seconds as the result is more …
=> Fix negative total XP calculation when skill starts

runelite-client/src/main/java/net/runelite/client/plugins/demonicgorilla/DemonicGorillaPlugin.java
Two small tweaks:
+ Renames `Demonic gorillas` to `Demonic Gorillas` for consistency in the plugin list.
+ Replaces 4 uses of `!anyMatch()` with `noneMatch()` for better readability.
The latter is actually one of IntelliJ's commit-time warnings, so I just fixed before pushing.
=> Demonic gorilla plugin: Capitalise plugin name

runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/Boss.java, runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialCounter.java, runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialCounterPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialWeapon.java
This will add a plugin to keep track of the succesful defence reducing special attacks.
The damage of the Bandos Godsword special is added cumulative to a counter.
The other special attack weapons only show the amount of succesful hits.
Counter will reset on the death of interacted NPC or if the player interacts with a different NPC,
Fix #492
=> Add special Attack Counter

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/AnagramClue.java
The wiki says the NPC's name is Immenizz, but in-game it is just named "Impling".
Fixes #2329
=> Use Immenizz's in-game name

runelite-client/src/main/java/net/runelite/client/plugins/fps/FpsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/fps/FpsDrawListener.java, runelite-client/src/main/java/net/runelite/client/plugins/fps/FpsLimitMode.java, runelite-client/src/main/java/net/runelite/client/plugins/fps/FpsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/fps/FpsPlugin.java
This depends on PR #1349 
Only pay attention to what is in `runelite-client/src/main/java/net/runelite/client/plugins/fps/` or review https://github.com/runelite/runelite/pull/1350/commits/eb2f738891b253f62aac122dcdd4894910f4e79d
Add FPS plugin, main features: Show FPS, Limit FPS always, Limit FPS on unfocus
Main motivation: OSRS likes to burn my laptop's battery in the form of heat with its software rendering. I want my laptop to stay cool and not need a charging cord for hours.
On my desktop, this goes from 50% CPU to about 10-20% when around 15fps. It depends on whether or not the game is in expanded render mode.
You may notice the display smooths down to about 16, this is the number given by client.getFPS, which is not quite accurate as far as counting the milliseconds goes and is …
=> Fps plugin

runelite-client/src/main/java/net/runelite/client/plugins/farmingtracker/FarmingTrackerConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/farmingtracker/FarmingTrackerPanel.java
Make farming tracker use english for dates by default and allow swapping between system default and English, Fix #2268
=> Make farming tracker use english for dates by default

runelite-api/src/main/java/net/runelite/api/WorldMapData.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/worldmap/WorldMapOverlay.java, runescape-api/src/main/java/net/runelite/rs/api/RSWorldMapData.java
Adds plane check to WorldMapOverlay rendering
=> WorldMapOverlay: Add check for current plane

runelite-client/src/main/java/net/runelite/client/plugins/fps/FpsPlugin.java
Issue:
@deathbeam reported that the limits were not applying immediately after start up
and this required dirtying the config manually to get it to apply.
Problem:
The draw listener expects `reloadConfig` to be called prior to its active use, so it is also an initalizing method.
`reloadConfig` was only being called if the config changed, and not when the plugin was activated.
Solution:
Call `reloadConfig` when the plugin is activated so it has been initialized.
=> FPS plugin: fix startup not applying limits

runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilitySession.java, runelite-client/src/main/java/net/runelite/client/plugins/agility/Courses.java
Stop the laps remaining overlay from disappearing on level up at end of course (Fixes #2282 )
Make the laps remaining counter count the laps remaining to the next level if the previous next level was reached with the exp gained.
Select the active course based on regionId as the results from selecting by exp are unreliable because there are courses that give uneven amounts of exp/lap
=> Fix agility laps left counter

runelite-client/src/main/java/net/runelite/client/plugins/runepouch/RunepouchOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/runepouch/config/RunePouchOverlayMode.java
Showing a tooltip on mouseover when the same information is already visible on screen seems unnecessary.
=> Add config option that enables/disables mouse tooltip on rune pouch hover

runelite-client/src/main/java/net/runelite/client/plugins/devtools/LocationOverlay.java
Clear children each frame in LocationOverlay to prevent infinite adding
of components there.
=> Clear children in LocationOverlay

runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsService.java
- Name the player indicators options properly
- Extend the clan ranks icon setting to support also overhead names
Preview:
=> Sanitize player indicators options

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
The previous description is no longer accurate as stronghold slayer cave was split up.
=> Updated cryptic clue solution for Kalphite area

runelite-client/src/main/java/net/runelite/client/config/ExpandResizeType.java, runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java, runelite-client/src/main/java/net/runelite/client/ui/ContainableFrame.java
- Add config for remembering the screen position of the client after exiting and reopening
- Add config for making the client stay contained in the screen (only works if custom window chrome is enabled)
- Make the client more reliably stay within the screen bounds when opening/closing a sidepanel
Fixes #1542, #1844 and #1874
=> Improve client window functionality

runelite-api/src/main/java/net/runelite/api/coords/WorldPoint.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdArea.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java
https://streamable.com/vfbie
The hot-cold clue scroll plugin is an extension of the existing clue scroll plugins. When a hot-cold clue is opened, instructions for obtaining the strange device will be displayed. Once the user attempts to use the strange device, the panel component will switch to showing names of world areas and how many possible final locations are in each world area. Once the user checks in a different spot, the list of world areas and number of possible final locations will be updated to reflect the temperature obtained from the strange device. From the second check onward the warmer/colder result of the strange device will also be considered (same temperature is not considered at this time because I couldn't figure out a good way to implement it, but the process is …
=> Add hot-cold clue scroll plugin

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/IndexDataBase.java, runelite-client/src/main/java/net/runelite/client/game/SpriteManager.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java, runescape-client/src/main/java/AbstractByteBuffer.java, runescape-client/src/main/java/Area.java, runescape-client/src/main/java/AttackOption.java, runescape-client/src/main/java/CombatInfo2.java, runescape-client/src/main/java/Widget.java, runescape-client/src/main/java/class281.java
Adds a SpriteManager class, similar to the ItemManager, to load sprites from the cache.
Required for #947
I want to convert most usage of resource-sprites to use this, probably in a separate PR
=> Add SpriteManager to get sprites from the cache

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java
There was an issue with the "and warmer than" case for the strange device check that made it exclude more areas than it should have. The changes fix that issue, and a few related variable and method names are renamed to help avoid similar confusion in the future.
Here's a video showing the bug: https://streamable.com/4cgyt
The bug is shown in the first half where the correct solution is "West of the Jatizso mine entrance", but it gets excluded from consideration after checking in camelot and ardy. The second half shows the same actions done with the corrected code, and "West of the Jatizso mine entrance" is kept for consideration.
=> Fix warmer/colder consideration for hot-cold plugin

runelite-client/src/main/java/net/runelite/client/Notifier.java, runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java
#2180 made it so Windows users could not have sound and a tray notification at the same time. This splits the enum into separate booleans
Cherry-picked from: #2230
=> runelite-client: Make notification options not mutually excusive

suppressions.xml
This makes Checkstyle's IDEA plugin ignore the clashing code style in the deobbed RS client.
=> Suppress checkstyle warnings in runescape-client package

runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/TooltipComponent.java
This dropdown is similar to to #1651 but for tooltips. Other PR is inactive and having issues. 
Dropdown:
Small:
Regular:
Bold:
=> Add tooltip font type dropdown

runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/agility/Obstacles.java
Add an option to show an overlay over traps in agility courses.
This only shows traps on the Agility Pyramid. I am not sure of other locations that this should include.
Closes #1184
I would like to draw a hull overlay of those traps, but I'm not sure if there is a way to do that for non-clickable objects. This may be good enough.
=> Add trap overlay for agility plugin

runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesOverlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/ProgressBarComponent.java
- Add minimum, maximum and value properties to ProgressBarComponent
- Add label display mode that will differentiate between percentage and
current/maximum display modes
- Properly center the text in progress bar
- Use panel component with custom paddings for opponent info
- For opponent/opponents opponent names use TitleComponent that is
horizontally centered
- Use new progress bar with full display mode when needed
Preview:
=> Opponent info panel improvements

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/plugins/antidrag/AntiDragConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/antidrag/AntiDragPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
- Allows you to configure the delay before you start dragging an item in your inventory in client ticks (20ms)
- Choose whether you want the delay while holding shift only
Adds https://github.com/runelite/runelite/issues/1062, https://github.com/runelite/runelite/issues/1669, https://github.com/runelite/runelite/issues/2299
=> Add Anti Drag Plugin

http-api/src/main/java/net/runelite/http/api/RuneLiteAPI.java
We get a minimum of one person a day having this error because maven can't build correctly on first run. This makes throws a more useful exception when this happens.
=> http-api: Print a more helpful error message when maven has not worked

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItem.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java
Add back ItemLayer#getHeight consideration when drawing ground items.
=> Add ItemLayer height to GroundItems overlay

runelite-client/src/main/java/net/runelite/client/ui/overlay/components/ProgressBarComponent.java
Added *100 to correctly display the opponent's health on the Opponent info overlay.
=> Fixed % on opponent health

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscoreConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java, runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/hiscore/NameAutocompleter.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSFriendContainer.java
Starts work on #785. It currently only looks at cached players and clan members. This feature can be toggled in the HiScore settings.
=> Autocomplete name when looking up player on HiScores

runelite-api/src/main/java/net/runelite/api/Perspective.java
This is in an effort to make NPEs in render methods happen slightly less
=> runelite-api: Annotate Perspective methods with `@Nonnull`

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollWorldMapPoint.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/LocationsClueScroll.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/worldmap/WorldMapOverlayMouseListener.java
- Improve the WorldMapPointManager to handle multiple world points
better
- Create new interface for clues that will return multiple locations,
have update and reset methods for clues with undetermined location
- Implement new LocationsClueScroll and LocationClueScroll to
HotColdClue to add support for displaying all the points on world map
- Handle the LocationsClueScroll to add each WorldPoint to the world map
when found
- Move part of the HotCold logic to the HotColdClue
- Improve the ClueScrollWorldMapPoint to not create BufferedImage for each of it's instance
=> Add support for map for hot/cold clues

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/LocationsClueScroll.java
Properly reset the WorldMapPoints when Hot/Cold clue updates.
=> Fix updating of Hot/Cold clue

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollOverlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/PanelComponent.java
- If panel component child exceeds the preferred size, correctly send this
new max size to other children, so they can resize/reposition themselves
correctly.
- To prevent affecting other clue types, reset the preferred size of the
clue scroll panel component to default value each render cycle, as the
clues can modify it.
Preview:
=> Fix overlay system sizing

runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayUtil.java
If a plugin used a combination of renderPolygon and either used other util methods or draw on their own using the same graphics object, the stroke would get applied as well.
Before:
After:
=> overlayutil: reset stroke for renderpolygon

runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java
Since commit 08c816e, the varbit change event is fired after this widget is shown and inRaidChambers is always false at that point. This would prevent the vanilla point box from being hidden.
Fixes #2621
=> fix: Hide vanilla raid points box when inside chambers of xeric

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/callback/Hooks.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
This broke the speccounter plugin, and is moderately incorrect because client scripts can update varbits before a tick has happened, and the event should reflect that.
=> Revert #2530 "Make VarbitChanged only fire once..."

runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/Bookcase.java
Bookcases on the eastern side of western rooms on the ground floor were classified incorrectly.
=> Fix bounds for west bookcases in Kourend Library

runelite-client/src/main/java/net/runelite/client/plugins/lowmemory/LowMemoryPlugin.java
To not change low detail flag before sounds are loaded, delay it to be
set only when arriving at login screen to not end up with corrupted
sound data.
Fixes: #696
=> Delay setting of low detail mode

runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/farmingtracker/FarmingPatchPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/farmingtracker/FarmingTrackerPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/feed/FeedPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeItemPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeOfferSlot.java, runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java, runelite-client/src/main/java/net/runelite/client/plugins/info/InfoPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/BookPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/KourendLibraryPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/UIActionSlot.java, runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/UICombinedActionSlot.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpPanel.java, runelite-client/src/main/java/net/runelite/client/util/SwingUtil.java
Apparently, the setOpaque method on JPanels was causing some performance
issues on the client, the original reason I had these was so that the
base panel would have a color defined, and every container or wrapper
panel on top would just be transparent.
To fix this I have set a default JPanel background color and replaced
calls to setOpaque with calls to
setBackground with the appropriate colors.
=> SetOpaque UI performance fix

runelite-client/src/main/java/net/runelite/client/callback/Hooks.java, runelite-client/src/main/java/net/runelite/client/plugins/fps/FpsDrawListener.java, runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java, runelite-client/src/main/java/net/runelite/client/ui/DrawManager.java
This improves the plugin's performance significantly, by making it use your GPU instead of CPU when stretching.
**Before:**
28 fps in fullscreen
**After:**
50 fps in fullscreen
=> Improve stretched fixed mode performance

runelite-client/src/main/java/net/runelite/client/plugins/friendnotes/FriendNotesPlugin.java
Notes were being saved without tags then queried with tag intact, causing them not to be shown.
=> Fix friend note not displaying due to color tags

runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java
`result.getSkill(null)` throws an IllegalArgumentException, which meant the hiscores were never set beyond combat level.
Introduced in https://github.com/runelite/runelite/pull/3035/files#diff-63f5372602c8f4a5d59848b8189532adR467
=> Fix setting of hiscore stats after combat level

runelite-client/src/main/java/net/runelite/client/plugins/antidrag/AntiDragConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/antidrag/AntiDragPlugin.java
Due to complains in PKing community, nerf this feature to work exactly
like its counterpart in other clients and make it work only when SHIFT
key is pressed.
=> Change Anti-Drag plugin to work only with SHIFT

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/MapClue.java
The Y coordinate for the crate is off by one.
=> Clue Scrolls: fix dark warrior fortress clue crate coordinates

runelite-client/src/main/java/net/runelite/client/plugins/devtools/VarInspector.java
Varcs is set during cache load, so we race it while starting
=> varinspector: Lazily initialize var arrays

runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/farmingtracker/FarmingTrackerPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/feed/FeedPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeItemPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangePanel.java, runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java, runelite-client/src/main/java/net/runelite/client/plugins/info/InfoPanel.java, runelite-client/src/main/java/net/runelite/client/util/SwingUtil.java
The aim of this pull request is to improve the ui experience by providing visual feedback when certain ui elements are hovered by the mouse. Some elements did this but others didn't!
The info plugin panel containers now behave more like buttons:
(ignore the pointer going transparent, that's a gyazo issue)
Changes the mouse to a pointer to help indicate the news items are hyperlinks:
(ignore the pointer going transparent, that's a gyazo issue)
The highscore panel buttons highlight on hover to help indicate they are hovered and clickable:
Same with the farming panel buttons:
Same with the GE panel:
Changes the cogs in the config panel to change when hovered to help indicate that they are hovered and clickable:
@psikoi
=> UI element mouse hover improvements

runelite-client/src/main/java/net/runelite/client/plugins/dailytaskindicators/DailyTasksPlugin.java
Currently the plugin reads varbits right on GameStateChanged event, but varbits are not yet initialized to the correct values, which means the dailies will always be available. This delays this check until next game tick.
=> Daily Task Indicators: delay the varbit check to allow them to initialize

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java
When leaving fight caves during a Jad task the task will be cancelled - this isn't detected by the slayer plugin.
=> slayerplugin: cancel task when leaving fight caves

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java
This change offers slight fps improvement compared to the original solid dig area overlay. Discussed in issue #3123. 
Note: The square that is marked as the dig location may be inaccurate. The marked square is supposed to be the center of the true 9x9 final area, but because the central coordinates were collected manually from pictures on the wiki, many of them are slightly off center. If the center points we have for an area are 5 or more squares away from their true center, then the dig location will not work. Getting the true centers will improve the calculations used to find the areas, so if anyone gets an inaccurate clue its center should be updated in plugins/cluescrolls/clues/hotcold/HotColdLocation.java.
New:
Old:
=> Change hot/cold overlay to only show outline of dig area

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
Tested with all bones that work on gilded altar, they seem to be using same animID.
=> idlenotifier: add support for gilded altar

runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcClickboxOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcMinimapOverlay.java
- Unify the logic and coloring of NPC tagging and highlighting
- Merge highlightedNpcs and npc tags to one list
- Compare npc index with list of tags on NPC spawn and add to
highlighted NPCs list instead of getting NPC from client.getCachedNPCs
- Add brackets to single line ifs, remove redundant code
- Cleanup code
=> Unify Highlight and Tag colors for NPC indicators, cleanup code

runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java, runelite-client/src/main/java/net/runelite/client/ui/components/FlatTextField.java, runelite-client/src/main/java/net/runelite/client/ui/components/IconTextField.java
When I refactored the IconTextField to include a new component called
FlatTextField, I forgot to change the methods to add/remove key
listeners.
All I had to do is override de addKeyListener/removeKeyListener
methods on both the IconTextField and FlatTextField instead of some
useless no-sense-making similar methods I had.
Easy fix.
Fixes #3202
=> Fix Hiscore auto-complete

runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/SkillCalculator.java, runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/SkillCalculatorPanel.java
As the skilling calculator was taking a long time to switch to other
side panel tabs, I had to go in and improve performance to reduce the
delay (by a few seconds), **however to shave off the few hundred milliseconds that are left,
a lot more overall changes to the client have to be made, I will be
doing those in a separate PR.**
- Changed layout manager to DynamicGridLayout with a 5px hgap instead of
using rigid areas to add gaps.
- Removed useless bottom gap, and added bottom empty border
=> Skill calcs performance improvement

runelite-client/src/main/java/net/runelite/client/plugins/screenmarkers/ui/ScreenMarkerPanel.java
If you have the 'always on top' option on and showing a confirm dialog with `null` as the `parentComponent`, it would show behind the main window, making it impossible to click and basically freezing the program, with the only way out being to kill the process (on Windows 10 atleast).
There are two other instances of `null` being passed to the same method but there is no way (that I know of) to access the parent component at this time. These are in LinkBrowser.java and AccountPlugin.java.
Also fixes a typo.
=> Fix for confirm dialog appearing behind main UI window

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java
Read the bracelet charge directly from chat rather than using an internal cache to keep the counter more accurate.
=> slayerplugin: read bracelet charges directly from chat

runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java, runelite-client/src/main/java/net/runelite/client/util/OSXUtil.java
Add support for toggle in "RuneLite" settings to go into fullscreen
mode, that will make RuneLite window fully fullscreen without any weird
hacks.
Preview (ignore my WM top bar):
=> Add support for fullscreen mode

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java
When getting assigned a new task through NPC contact, there is no space between the word 'kill' and the killcount, thus failing the regex check.
When asking about your current assignment from a slayer master, the dialog will use a semicolon instead of a comma.
Fixes #1150
=> slayerplugin: fix current task regex and new task via npc contact regex

runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsConfig.java, runelite-client/src/main/java/net/runelite/client/ui/PluginPanel.java
- Add layout manager that supports grid of components with variable sizes.
- For better readability of text configurations, change TextField to
TextArea that can span multiple lines.
Preview:
=> Change TextField to TextArea that can span multiple lines

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
Fixes #3199 (completely, and other bugs of the sort)
The current way ClientUI switches tabs on the side panel is by adding
and removing them from a container panel. This is slow on panels with a
large number of components.
To fix this, I decided to use a cardlayout, as suggested by abex.
So now, the container panel has a CardLayout and all the plugin panels
are added with their names as keys, and when a NavigationButton is
clicked, the cardlayout will show a panel based on its key. (Ex: Xp
Tracker).
Before this commit, switching from the construction skill calcs to any other tab would result in a +/- 1 second delay, after this, even after every item is repeated 20 times, smooth transition with no delay, that's a giant improvement.
I would request a look from @Abextm and @deathbeam.
=> Refactor ClientUI using CardLayout

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
- New CardLayout requires also preferredSize in addition to maximum and
minimum sizes to expand/contract properly without leaving artifacts +
also requires revalidation.
- Remove entire container repaint to prevent unnecessary slowdown for no
reason
=> Properly set preferredSize of navContainer

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpPanel.java
This was somehow removed in the latest PluginPanel updates, all other
panels were unaffected, by this was. Simple fix, a 50px empty border
should do the job.
=> Add top margin to the error panel

runelite-client/src/main/java/net/runelite/client/chat/CommandManager.java
Fixes the following exception:
```2018-05-19 15:25:19 [Thread-5] WARN  net.runelite.client.RuneLiteModule - uncaught exception in event subscriber
java.lang.ArrayIndexOutOfBoundsException: 0
at net.runelite.client.chat.CommandManager.scriptEvent(CommandManager.java:70)
at sun.reflect.GeneratedMethodAccessor110.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor …
```
=> Fix ArrayIndexOutOfBoundsException when an empty command is typed

runelite-client/src/main/java/net/runelite/client/plugins/bosstimer/Boss.java, runelite-client/src/main/java/net/runelite/client/plugins/bosstimer/BossTimersPlugin.java
Improve the accuracy of the boss respawn timer by starting it when the boss despawns.
Added KQ boss to boss list per request #2630
Fixed Vet'ion timer to start after 2nd phase death instead of first per request #3017
=> Improve boss respawn timer

runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeOfferSlot.java
Adds proper formatting for large values in the 'Price each' line of additional information of a grand exchange offer. For example, "19000000" gets formatted as "19,000,000".
=> grandexchange: Format 'Price each' value for items

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java
This PR:
1) Fixes the issue with using "Check" on bracelets that have one charge. Previously it only supported (x) charges, meaning '1 charge' chat message was ignored.
2) Fixes the issue with reading expeditious bracelet charges. The code was expecting to see
```Your expeditious bracelet helps you progress your slayer task faster```
while the correct chat message is
```Your expeditious bracelet helps you progress your slayer faster```
3) Expand the slayerplugin test class to check for bracelets with one charge.
=> slayerplugin: fix expeditious bracelet counter and one charge issue

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/MapClue.java
This moves the location within the anvil room, which notably speeds up
completion of this clue step.
Ref: runelite/runelite#3308
=> Improve Yanille anvil room map clue location

runelite-client/src/main/java/net/runelite/client/plugins/screenmarkers/ScreenMarker.java, runelite-client/src/main/java/net/runelite/client/plugins/screenmarkers/ScreenMarkerOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/screenmarkers/ScreenMarkerPlugin.java
To create fully unique identifier, store markers based on epoch millis
instead of using their name, to allow renaming.
=> Store markers based on epoch millis

runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/SkillCalculator.java, runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/UIActionSlot.java
This PR updates the skill calculator to show an orange indicator on actions that will become available before the target level has been reached.
As well as the addition of an orange indicator, the PR also includes some basic clean-up that was supposed to be included as part of a closed PR before the apocalypse.
=> Skill Calculator: Orange indicator for actions that will become available before target.

runelite-client/src/main/java/net/runelite/client/plugins/screenmarkers/ScreenMarkerOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/screenmarkers/ui/ScreenMarkerPanel.java
This new feature adds names to screen markers, and allows a user to
rename an existing marker, with save and cancel options.
**Needs #3328 to be merged first**
=> Add naming to screenmarkers

runelite-client/src/main/java/net/runelite/client/plugins/screenmarkers/ui/ScreenMarkerPanel.java
Implements getDisplayName() so the screen marker name is correct in the panel.
=> Screen Markers - Fix for screenmarker display name

http-api/src/main/java/net/runelite/http/api/config/ConfigClient.java, http-api/src/main/java/net/runelite/http/api/examine/ExamineClient.java, http-api/src/main/java/net/runelite/http/api/xp/XpClient.java, http-api/src/main/java/net/runelite/http/api/xtea/XteaClient.java, runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java, runelite-client/src/main/java/net/runelite/client/plugins/examine/ExaminePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/xtea/XteaPlugin.java
Change most post/put/delete http requests to enqueue() instead of execute().
This allows the UI to not block when the api is acting slow or when it's down, since the calls now run on okhttp's thread pool instead of using RuneLite's thread pool.
Tested by simulating a slow connection and disabling/enabling a plugin with: `sudo tc qdisc add dev INTERFACE root netem delay 2000ms`
This won't "fix" all problems in case the API is down, but this should mitigate most of the annoying ones.
Closes the main issue of #2666
=> Enqueue most post/put/delete requests

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java
Before this fix, if an item did not have a grand exchange value, the overlay would use its High Alchemy value, but the right click menu would use the full store price value.
For Example, I have Green set to >20k and Blue set to >100k 
This happens because, to get that 61.5k alch value, the Ecu key's Store Price is ~102k.
=> Fix items with no Grand Exchange Price using Store Price for the right click menu instead of High Alchemy value

runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeNotification.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeNotificationHandler.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangePlugin.java
Adds notifications to Grand Exchange offers.
* Toggleable notifications
* Delays notifications by a configurable amount of seconds so notifications don't immediately overwrite each other
* Delays notifications in a slot by a tick so any quick partial buy/sell to complete buy/sell events will coalesce into just the "Finished buying/selling" notifications
* Only sends notifications on buying/selling/bought/sold events. Cancelled offers don't cause any notifications
Tested with basic offers, as well as partial orders that complete non-quickly by buying over the buy limit of an item, and then selling the amount that were partially-bought with the original offer still in place. This correctly shows a partial buy notification, then a finished notification for the original offer. Also, as this …
=> Add notifications to Grand Exchange plugin

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpPanel.java
This should help keep columns aligned across different boxes.
Also avoids constant resizing of info box when 'XP/Hour' text is longer than 'XP Gained' text and is changing.
=> Use single GridLayout for XPTracker stats

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/MapClue.java
People have been confused by how the clue scroll overlay works on the world map.
This PR updates the text on Map and Coordinate clues to be more clear on how the overlay functions.
=> Clue Scroll Plugin: Add wording to direct users to world map

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java
fixed to include both messages when the word "task" is present or omitted
=> slayer plugin: fix expeditious regex pattern

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
Example: Spirit Tree NULL_1293.
Fixes #1926
Closes #3480
=> Fix null names for quest objects in cryptic clues

runelite-client/src/main/java/net/runelite/client/plugins/farmingtracker/FarmingTrackerPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangePanel.java, runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/SkillCalculatorPanel.java, runelite-client/src/main/java/net/runelite/client/ui/components/materialtabs/MaterialTab.java
As material tabs started being used in different ways than planned, the code
around them started being a little inconsistent. With this change I created a new constructor for Icon Tabs (skill calculator, farm timer) and also add hover effects to them. These hover effects were previously added on each plugin that used them.
I also refactored the plugins that included these tabs to use the new constructor.
**These tabs will look and behave exactly like they do currently in master, it's just a code improvement.**
=> Improve Material Tabs Code

runelite-client/src/main/java/net/runelite/client/plugins/tithefarm/TitheFarmPlantOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/tithefarm/TitheFarmPlugin.java
Instead of creating logic for drawing arcs by itself, use PieCompo
and similar appearance of the pies as hunter plugin
##Change schedule to GameTick sub in Tithe plugin
Instead of using 600ms schedule, use GameTick event for subscribin
game ticks.
=> Use pie component in Tithe farm plugin

runelite-client/src/main/java/net/runelite/client/plugins/farmingtracker/Produce.java
As described in #3552, the tickrate should be 5 rather than 10 as it only takes 35 minutes to grow rather than 70. I have not tested whether this is true or not.
Fixes #3552
=> farmingtracker - Change tickrate for giant seaweed from 10 to 5

runelite-client/src/main/java/net/runelite/client/plugins/regenmeter/RegenMeterOverlay.java
If the minimap orb is hidden, don't render the regen meter. This is mostly noticeable during cutscenes and if the minimap is hidden in general.
=> regen plugin: don't show regen if the minimap orb is hidden

runelite-api/src/main/java/net/runelite/api/model/Jarvis.java
When zooming in the camera the canvas points for the convex hull calculation could be very small/large and would cause the cross product to underflow/overflow the minimum/maximum integer value. That could cause the convex hull calculation to find the wrong set of points and would find a loop without revisiting the left most point, and thus never exiting the main loop.
Fixes #3377
Might also fix other peoples issues with client freezing (#2718?), but it's hard to tell if that was caused by this bug or if it was something else.
=> Fix Jarvis infinite loop

runelite-api/src/main/java/net/runelite/api/GraphicID.java, runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java, runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
Turns out a lot of things reuse that animation. Apparently the AnimationID is reused by the God Spells as well, so the chat message is the only option.
Thanks to @josharoo for reporting this issue and @Kamielvf for suggesting this fix.
=> Fix Charge timer showing with every teleport

runelite-client/src/main/java/net/runelite/client/chat/ChatMessageManager.java, runelite-client/src/main/java/net/runelite/client/config/ChatColorConfig.java
Added an option for Clan Chat Info Highlights, as the Raids plugin used them
Added a default highlight for Game messages. This makes the Daily Task text look like it did before the update, and it also fixes the issue with it not working with the Transparent chatbox (which was an outstanding issue)
=> Fix some chat colour issues

runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerCounter.java, runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerFlickOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerType.java
This will add a Prayer Indicator plugin to show the current prayers being used by the player in infoboxes.
Also will this merge with the prayer flicking plugin.
The player can opt out to not show overheads in the infoboxes.
Fix #1537
=> Add Prayer indicator plugin by merging prayer flick plugin

runelite-client/src/main/java/net/runelite/client/RuneLite.java
Because we now have several thread checks that use assertions, but not many people have assertions on, so we keep getting code with threading problems that no one notices.
If for some reason you need developer mode with assertions disabled you can add `-ea:net.runelite.client.RuneLite` to your JVM params
=> runelite-client: Require assertions when developer mode is on

runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPlugin.java
This toggle will turn on highlighting the current tile under the mouse as well as show a tooltip containing the world location of that tile.
=> Add Tile location tooltip option to dev tools

runelite-client/src/main/java/net/runelite/client/plugins/screenmarkers/ScreenMarkerMouseListener.java, runelite-client/src/main/java/net/runelite/client/plugins/screenmarkers/ScreenMarkerPlugin.java
This will allow drawing screen markers in every direction.
I had to remove the support for constraining proportions because it was causing some issues. If it is desired to return this behavior I will take another look at it.
Fixes #3524
=> Allow drawing of screen markers in every direction

runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
This just takes a screenshot whenever a PvP kill message is received.
=> Update Screenshot plugin to have option to automatically take screenshot for PvP kills

runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/RuneLiteProperties.java, runelite-client/src/main/java/net/runelite/client/plugins/info/InfoPanel.java
- Use Lombok for creating setters and getters for variables in RuneLite
- Use correct spacing and final modifiers
- Propagate RuneLite launcher version to client via system property and
add this property to RuneLite properties file.
- Show this version in info panel
This also requires changes in https://github.com/runelite/launcher to propagate this system property.
Preview:
=> Add support for launcher version

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java
The locations for these two hot-cold clue spots were not fully accurate (digging on the spot marked did not advance to the next clue step), so I've updated them with spots which will work when digging on them.
=> Fix hot cold clue locations

runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
Stops screenshots taken on kills from overwriting screenshots taken same day, and remove double spacing
=> ScreenshotPlugin: Stop overwrite

runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/RuneLiteProperties.java, runelite-client/src/main/java/net/runelite/client/plugins/info/InfoPanel.java
Packr doesn't let us add jvm arguments from the command line, so this disables the assertion check if the launcher version is present
=> runelite-client: Allow developer-tools to run from the launcher

runelite-client/src/main/java/net/runelite/client/plugins/demonicgorilla/DemonicGorillaOverlay.java
The overlay was off by a few pixels when using fixed screen size
=> Fix demonic gorilla overlay position on fixed screen

runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoOverlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/PanelComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/TitleComponent.java
- Remove the auto-expanding of PanelComponent based on children size
because then the size cannot be ever reduced
- Make TitleComponent return preferredSize if it is smaller than string
width
- Make opponentInfo assign the preferred size to panel based on input
strings
=> Remove auto-expanding from PanelComponent

runelite-api/src/main/java/net/runelite/api/Actor.java, runelite-client/src/main/java/net/runelite/client/config/ConfigInvocationHandler.java, runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java
As it is now, any plugin with an invalid config value fails to load. This makes it load with the default value instead.
=>  runelite-client: Don't fail on invalid config values

runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java
Allows for seeing the colours you have set at a glance. Very nice for figuring out exactly what your Chat colours are set to.
Before:
After:
=> Make Color config options show their colour instead of "Pick a color"

runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZonePlugin.java
This was due to the old method checking to see if the only map tile loaded is 9033, which is both the KBD lair and NMZ (early OSRS reuses a lot). 
This doesn't cause issues with the normal KBD lair, as there are (mostly) empty but valid regions around the KBD lair ([See this map](https://i.imgur.com/JuUZE2S.png)).
Fixes #3692
=>  Fix NMZ points overlay appearing in the KBD instance lair

runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsPlugin.java
Adds a counter in the boost information plugin, which specifies a threshold value for when a boosted skill gets low. When the amount of levels boosted reaches this value, a notification is sent. A value of 0 will disable notification. Solves issue #3449.
=> Add notification when skill boosts get low

runelite-client/src/main/java/net/runelite/client/plugins/chatnotifications/ChatNotificationsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/chatnotifications/ChatNotificationsPlugin.java
Highlight own username example:
Highlight arbitrary words example (Highlighted words were "Abyssal Whip" and "Doughnut")
The highlights work with all types of chat, and the highlight colour is controlled by that chat's highlight option in Chat Color.
Oh yeah, and there are chat notifications now.
=> Add Chat Highlighting and Chat Notifications

runelite-client/src/main/java/net/runelite/client/plugins/crystalmathlabs/CrystalMathLabs.java
This plugin is an opt-in plugin. When activated, the plugin will try and make a request to the CrystalMathLabs API when the user logs in and logs out. 
That would mean that a user does not have to manually track when logging in and out on CML.
I've spoken to both Adam and the owner of CML and they are both ok with it.
Adam is ok with it as long as it's not going through the RuneLite API.
=> add CrystalMathLabs plugin.

runelite-api/src/main/java/net/runelite/api/ItemComposition.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItem.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemInputListener.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/config/PriceDisplayMode.java, runescape-api/src/main/java/net/runelite/rs/api/RSItemComposition.java
- Change the price displaying to dropdown menu
- Show (GE:, (HA: only when showing both prices at once, otherwise do
not add label at all
Instead of checking for GE price being above 0, use isTradeable boolean
to determine if the price checks should apply or not and add
configuration value to disable this behaviour.
Remove the possibility of having the item both highlighted and hidden
when using the highlight/hidden boxes.
- Expand the clickbox for highlighting/hiding item to it's entire name
- Left click on name highlights item, right click hides item
- Highlight background when in highlighting mode of the background item
that is hovered
- In order to help in cluttered environment, bring ground item that is
hovered to front.
These changes makes easy to see what item are you trying to …
=> Improve ground items

runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/SkillCalculator.java
The top action (Combined action slot) was not being updated when you changed a target level or exp. This fixes that.
=> Skill Calc - Fix combined action slot not updating when an input field was changed

runelite-client/src/main/java/net/runelite/client/plugins/screenmarkers/ScreenMarkerPlugin.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayManager.java
The TreeSet was removing most overlays (except the ones I tested with) because they
were equal to the comparator.
=> Fix overlays

runelite-client/src/main/java/net/runelite/client/ui/overlay/Overlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayManager.java, runelite-client/src/test/java/net/runelite/client/ui/overlay/OverlayManagerTest.java
- Generated equals from Lombok can cause falsy equals checks and so match
with unrelated overlay.
- Do not add overlay twice to overlay list based on equals
=> Use Object.equals for Overlays

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java
In ground items, consider anything that has positive GE value as
tradeable and exclude it from untradeable checks.
=> Consider anything with GE > 0 as tradeable too

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java
=> Fix south-of-mausoleum hot-cold clue location

runelite-client/src/main/java/net/runelite/client/plugins/farmingtracker/FarmingTrackerPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java, runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/SkillCalculatorPanel.java, runelite-client/src/main/java/net/runelite/client/ui/components/materialtabs/MaterialTab.java, runelite-client/src/main/java/net/runelite/client/ui/components/materialtabs/MaterialTabGroup.java
In an attempt to clean-up and re-use UI elements, I am applying the material tabs to the hiscores plugin (previously it was jpanels that looked exactly like tabs because at the time this panel was made, there were no icon material tabs yet).
With this, I expanded the functionality on the Material Tabs by adding a new event instead of Runnable.
From the commit message:
This new functionality allows a tab to not be selected depending on the
value of onTabSelected.
For example, for the hiscores, I want to block tab switching when the
plugin is already loading someone's hiscores, and in this scenario, I
have to return false to make sure the tabs don't switch.
**Small visual improvements were done to the hiscores search bar (it broke because of the new tabs, just had to readjust some …
=> Material Tabs in Hiscores + OnTabSelected event

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java
This issue was caused by ground item values not being copied to
ArrayList when modified. To avoid unnecessary allocations, create new
copy only when required (e.g when holding alt).
=> Fix UnsupportedOperationException in ground items

runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java
remove the unnecessary tool tip for JTextArea that can sometimes take up the entire screens width
Fixes #2716
=> configPanel: remove tooltips for JTextArea

runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeConfig.java
Depending on 3rd party API is bad enough, having it enabled by default
is worse.
=> Disable OSB prices by default

runelite-client/src/main/java/net/runelite/client/plugins/zoom/ZoomConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/zoom/ZoomPlugin.java
Instead of having the plugin enabled and everything inside disabled just
disable it and by default enable 1 option.
=> Disable camera zoom by default (because all options inside are anyway disabled by default)

runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargeConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargeOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargePlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/itemcharges/ItemChargePluginTest.java
Resolves: #2931 
Created a new plugin category called "Thieving" to hold these options based off how Runecrafting holds binding necklace and Slayer holds bracelets.
Edit:
I'm going to tag on a summary as to why I believe this belongs in it's own plugin as I don't believe my initial was sufficient and to summarize my comments below:
First lets look at the "Jewellery Charges" plugin. The "Jewellery Charges" plugin current is used for displaying the overlay on items that change ItemID on different charges. That is items that have (#) next to there name. For example "Amulet of Glory (4)" "Amulet of Glory (3)", etc. It would almost make sense to change this plugin name to Teleport charges but it also contains the non teleport and non jewellery items water skin and imp in a box. Overall …
=> Created dodgy necklace charge overlay and break notification.

runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerInputListener.java, runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerOverlay.java
This plugin is marking ground, it should be at lowest possible layer to
not interfere/draw over other overlays.
=> Fix ground marker plugin layer

runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsPlugin.java
From what i have been able to test there are 4 "sections" of 15 seconds each until your stats drain.
Preserve only needs to be on for the entirety of the last one for it to activate, once it does so you get 30 seconds extra even if you turn off preserve.
This will display the new decay timing while you have preserve on, if you don't turn it on soon enough or take it off too early it will catch that and display correctly.
This fulfills request #1059
=> Preserve prayer tracking in boost timer

.github/CONTRIBUTING.md
Because the coding conventions are somewhat extensive, provide link to wiki article rather than listing a few of the conventions.
=> CONTRIBUTING.md - Provide link to coding conventions

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java
Add back support for recoloring right-click menu in Ground Items, but
make it optional and disabled by default.
=> Optional support for recoloring right-click menu

runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPlugin.java
Fix an issue introduced by #3778 that would prevent the player from clicking the "Tag" option on pillars in the pinball random event.
=> Fix NPC indicators to not consume tags clicks on non-NPCs

runelite-client/src/main/java/net/runelite/client/callback/Hooks.java, runelite-mixins/src/main/java/net/runelite/client/callback/Hooks.java, runelite-mixins/src/main/java/net/runelite/mixins/GraphicsObjectMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSActorMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSGameEngineMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSItemCompositionMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSKeyFocusListenerMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSMessageNodeMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSProjectileMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSRegionMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSTextureProviderMixin.java
In order to cleanup the Hooks class a bit, replace runescape-client
Hook with MethodHook in mixins where possible/convenient.
Depends on !13
Depends on !14
=> Replace Hook with MethodHook where possible

runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/Book.java, runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/BookPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/Bookcase.java, runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/KourendLibraryOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/KourendLibraryPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/Library.java, runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/LibraryCustomer.java, runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/SolvedState.java
Relating to #3911 
Simply reducing public methods/class to package-private to prevent re-use of plugin logic/classes external to the plugin itself
Tested post-change
=> #3911 - Update library plugin encapsulation

runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerCounter.java, runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerDoseOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerFlickOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerItems.java
Relating to #3911
Simply reducing public methods/class to package-private to prevent re-use of plugin logic/classes external to the plugin itself
Tested post-change
Boost Indicator/Overhead indicator
Flick Helper
Dose Indicator
prayer stats
=> Update prayer plugin encapsulation

runelite-client/src/main/java/net/runelite/client/plugins/inventoryviewer/InventoryViewerOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/inventoryviewer/InventoryViewerPlugin.java
This a rebase of the inventory viewer due to inactivity.
This also has some code changes, such as exiting early if the item container is null. If there was a reason to always show the panel, I can change it back and add a comment to the code.
This undoes the changes made to the panel component. That should be in a separate PR IMO, if people want it.
[Here](https://github.com/runelite/runelite/blob/279d2e3ca56c606e3bbcfb9faf27da7e08dc325f/runelite-client/src/main/java/net/runelite/client/plugins/inventoryviewer/InventoryViewerOverlay.java) is the original overlay file for reference.
Screenshots:
Closes #2214
=> Add inventory viewer plugin

runelite-mixins/src/main/java/net/runelite/mixins/RSGameCanvasMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/StretchedFixedModeMixin.java
To fit with fixed mode with stretched fixed disabled, center stretched
fixed mode horizontally.
Preview:
=> Center stretched fixed mode horizontally

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
This should be clearly separated from other options and be priority at
the top.
This feature is mostly unnecessary as it is way too spefic and with very
little use.
=> Remove age menu entry swap, move shift-click to the top

runelite-client/src/main/java/net/runelite/client/config/Keybind.java
Without this certain key combos that java doesn't support (fn+fkeys on laptops) are supposed to be hit by the equals check, but ofc they weren't
=> runelite-client: Add a equals implementation to Keybind

runelite-client/src/main/java/net/runelite/client/plugins/corp/CorpDamageOverlay.java
This is completely unnecessary as it is obvious and is just using screen
estate for no real reason. Also we dont do this for any other plugin.
=> Remove title from corp panel

http-api/src/main/java/net/runelite/http/api/hiscore/HiscoreClient.java, runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java, runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/PlayerComparisonOverlay.java
This adds a configuration to the opponent information plugin which, if
enabled, will show a table comparing the stats of your player and
players you interact with, highlighting any differences with green and
red.
Fixes runelite/runelite#2961
=> Add Player Comparison table to Opponent Information plugin

runelite-client/src/main/java/net/runelite/client/config/Keybind.java
Without this OSX shows a replacement character, see #4006. When/If #4006 is merged, this should be reverted.
=> runelite-client: Don't use system specific modifier key names

runelite-client/src/main/java/net/runelite/client/plugins/screenmarkers/ScreenMarkerPlugin.java
This fixes an issue where the screen-marker panel would render invisible
=> screen-markers: fix graphical bug

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_cooking.json
Corrects the Dark Crab Cooking requirement listed in the Cooking Skill Calculator Plugin, reported in Issue #4069
=> Cooking Skill Calculator Fix

runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java, runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
Instead of using graphic make SOTD/SOTL timer use chat message as that
one is more reliable and same for both.
Fixes #4078
=> Make SOTD/SOTL timer use chat messsage

runelite-client/src/main/java/net/runelite/client/ui/overlay/components/TitleComponent.java
To return parent defined dimensions properly, return preferredSize.width
instead of text width, as this is block component so it should act like
block and not return custom sizes.
=> Return preferredSize.width from TitleComponent

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpStateSingle.java
Fixes runelite/runelite#3639
Some screenshots to prove that it is working:
* [Current behavior (old goal was level 79 - 84)](https://user-images.githubusercontent.com/2199511/41439881-0235e594-701c-11e8-8c39-91d23f6144c0.png)
* [New behavior (no change to smithing goal)](https://user-images.githubusercontent.com/2199511/41439883-03710010-701c-11e8-8136-6ea4c7b8c5d1.png)
* [New behavior is identical for current goals (and showing my currently-set goals)](https://user-images.githubusercontent.com/2199511/41439884-05320e30-701c-11e8-995e-1e28eaee8d58.png)
=> Ignore level goals which have been passed

runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeSearchPanel.java
Before: (note: the render is refreshed upon attempting to scroll while hovering the old rendered panels)
After:
Also fixes some typos in an error message string in a separate commit.
=> Fix empty GE search render bug

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java
Currently the slayer plugin checks for slayer items on each game tick, which on occasion causes text to be persist longer than expected when swapping between the inventory and equipment instances.
The queries are now run in the render call in the SlayerOverlay class, preventing this issue from occurring.
=> Slayer overlay items refresh on render

runelite-client/src/main/java/net/runelite/client/util/StackFormatter.java, runelite-client/src/test/java/net/runelite/client/util/StackFormatterTest.java
Addresses #4054 in that it represents stacks with decimals as . rather than ,
I believe the other formatters format logically, since they don't maintain a decimal, and instead produce output like `100,000`
Test updated to reflect the `10.5k` format rather than `10,5k`
=> #4054 Represent decimals as .'s not ,'s

runelite-client/src/main/java/net/runelite/client/plugins/farmingtracker/PatchImplementation.java, runelite-client/src/main/java/net/runelite/client/plugins/farmingtracker/Produce.java, runelite-client/src/test/java/net/runelite/client/plugins/farmingtracker/PatchImplementationTest.java
There were several places where the autogenerated patch implementations would double count a stage, and miss another. PatchImplementationTest now checks for missed stages, excluding the final stage because that is often missed on plants which do not have a "Check-health" stage. There were also a couple produces with incorrect tick counts.
Supersedes #4119
=> farmingtracker: Correct several patch timings

runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordState.java
Correctly reset Discord state only if now > updated + timeout instead of
updated > start + timeout.
=> Reset Discord state if now > updated + timeout

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPanel.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
Default oculus orb speed is hardly useable when trying to explore
something so this will set it to more reasonable default.
Depends on !9
Preview:
=> Set oculus speed to 36 (x3) in DevTools

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
- Remove ambiguous "archaelogist" abbreviation and replace it with
respective crazy and deranged arch abbrevs
- Add "chambers" abbrev to raids 1
- Add "theatre", "verzik" and "verzik vitur" abbrevs to raids 2
- Fix "verxik" typo in ChatCommandsPlugin
=> Fix !kc abbreviations and add more abbreviations

runelite-client/src/main/java/net/runelite/client/plugins/tearsofguthix/TearsOfGuthixOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/tearsofguthix/TearsOfGuthixPlugin.java
Adds a `ProgressPieComponent` overlay to the blue tear streams that spawn in the Tears of Guthix minigame. Each tear stays for 9 seconds, the overlay displays the time remaining before the stream disappears.
Closes #3180
=> Add stream progress overlay for Tears of Guthix minigame

runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java
Prevent client shutting down from main method in case settings contain
illegal unicode string due to config file corruption.
=> Do not explode on illegal unicode char in settings

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
This pull request adds the ability to swap the talk-to menu entry with the decant menu entry which is used at NPC's at the GE. 
The default state for this is set to off, to not conflict with anyone's existing gameplay.
Fix #4101
=> Fix #4101 - Add swap options for Decant

runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsPlugin.java
Correctly reset change up and change down times when boosts are set to
NEVER instead of resetting it only after first tick down.
=> Correctly reset boosts when on NEVER

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java
Fixes the regex matching to eliminate all commas in the numbers parsed before converting them to Integers.
Updates the REWARD_POINTS pattern to take into account possibility of commas.
fixes: #3673 
Before: ![](https://i.imgur.com/UReYuS9.png)
After: ![](https://i.imgur.com/i8qUOFw.png)
=> Slayer tooltip fix

runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java, runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/screenshot/ScreenshotPluginTest.java
- Rename references to Chambers of Xeric in preparation for ToB
See #4246 
- Correct hunter lvl up message
The hunter lvl up widget is different from other widgets and uses another string, the matcher was therefore always returning null. Add special case for hunter lvl up widget.
- Move from hideWiget to more robust loadWidgets event
The hideWidget event would often not fire resulting in raids and barrows screenshots not being taken. All of the screenshots relying on that event has therefore been moved to the more reliable loadWidget event. 
Fixes #2485 
Fixes #2114
Fixes #986
=> ScreenshotPlugin: Bugfixes

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerOverlay.java
QueryRunner is now injected in the constructor.
Method checkInventory moved bellow the constructor.
Restructured queries inside checkInventory to utilize idEquals.
Renamed method checkInventory to getSlayerItems to better reflect the new business logic.
Removed the now unnecessary check in the render call.
Changed Set<Integer> of slayer equipment to ImmutableIntArray, and expanded it to include jewelry to prevent the necessity of repeated concat calls when calling idEquals.
=> Slayer overlay code structure and query refactoring.

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java
`null` can never be an instance of any type of object, thus `clue != null` is not needed when the other check is `clue instanceof TextClueScroll`.
```
java> null instanceof Object
java.lang.Boolean res0 = false
```
=> clue scroll plugin: Remove useless null check

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpPauseState.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpPauseStateSingle.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpState.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpStateSingle.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerPlugin.java, runelite-client/src/main/java/net/runelite/client/ui/components/DimmableJPanel.java, runelite-client/src/main/java/net/runelite/client/ui/components/ProgressBar.java
Add the ability to manually pause a skill, automatically pause a skill after logout, or after a timeout of no XP changes. Similarly, skills will be auto unpaused when XP is gained or when (if paused due to logout) logged back in.
Some players would like to pause their expectations on skill ETAs when having lunch, going on a break, or sleeping for the night. By only counting effective time in game, players don't need to account for time outside of game or between skills when training.
Added a setting for pausing skills without any XP changes, default value: 0 which behaves as no auto pausing by timeout
Added a setting for auto pausing skills in relation to logout, default value: Never
No changes to default behavior
ProgressBar now extends a new Component class which comes with dimming of …
=> Add pause skill timing feature to the XP Tracker

runelite-mixins/src/main/java/net/runelite/mixins/RSMouseInputMixin.java
The 172 client calls mouseMoved from mouseEntered and mouseDragged, so the events get processed twice.
Fixes #4401
=> mixins: Don't post mouse events that have already been posted

runelite-client/src/main/java/net/runelite/client/plugins/runecraft/AbyssOverlay.java
This increases usability of running the abyss. Because if you can see the portal sooner, you know which direction/entry obstacle is closest to it.
=> Render abyss rift portals as soon as visible

runelite-api/src/main/java/net/runelite/api/Perspective.java
Fixes an issue that was introduced in 2599db2
issue at hand:
after fix:
=> perspective: fix regression caused by 2599db2

runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoPlugin.java
SDMM worlds have both `DEADMAN` and `SEASONAL_DEADMAN` types, so we
must check for the latter first to accurately determine the hiscore
lookup endpoint.
=> opponent info plugin: Fix SDMM hiscore lookup

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
Without this chat commands were not working because it just exited
early for pmods.
=> Add support for mod public chat to ChatCommands

runelite-client/src/main/java/net/runelite/client/config/Keybind.java, runelite-client/src/main/java/net/runelite/client/util/HotkeyListener.java
KeyTyped consumer any non-modifier key while the hotkey is being pressed because there is no good way to determine if a KeyTyped event matches a Keybind due to it's keyCode being zeroed.
=> runelite-client: Consume hotkeys in HotkeyListener

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpStateSingle.java
PR #4114 added XP pausing and changed how timing was done. This introduced a regression which caused all skills to have time added, whether or not they have gained xp.
The previous behavior was that the initial time was only set after the xpGained changed from 0 to > 0.
Similarly, tick will now not add time if xpGained is the initial value.
Resolves #4452 
This was tested with an hour of gameplay, doing cannon balls, then trying some fletching.
You will notice the behavior where the first 60 seconds of experience are scaled to 60 seconds, that was introduced a long time ago to help with near division by zero problems. This demonstrates that the time for this skill JUST started.
=> Fix XP Timing regression

runelite-api/src/main/java/net/runelite/api/Experience.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpSnapshotSingle.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpStateSingle.java
This is a fix for endLevelExp being set to -1, which then causes an exception later when creating a snapshot for the GUI. That exception is thrown in `Experience.getLevelForXp` on a `< 0` xp amount.
The fix is to use the max XP value, which also is convenient for those that want to hit the max XP in the game, namely 200,000,000.
Used `::addxp fishing <big number here>` to test this.
Resolves #3658
=> Fix level 126 next goal to be max XP (200,000,000) instead of -1 xp

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java
Propagate item layer height to ground items again
=> Propagate height to ground items

runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeInputListener.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeSearchPanel.java
Rewrote the logic to use menu entries instead of purely a mouse listener. This simplifies the code and fixes several bugs.
Fixes #4040
Some other things fixed now:
- Spam clicking the alt search on an item no longer crashes the applet (however, the exception is still thrown)
- The applet no longer loses focus when using alt search, which caused the tooltip to go away (and may have been the reason for the crash?)
- Now works in the shop interface
=> Allow alt search while grand exchange inventory is active

runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/chat/ChatMessageManager.java
ConfigChanged is no longer propagated on startup, so colors need to be
loaded explictly for first time.
=> Fix loading of chat colors on startup

runelite-mixins/src/main/java/net/runelite/mixins/ScriptVMMixin.java
Due to the extensive use of globals in the ScriptVM it is not reentrant
=> mixins: Prevent runScript from being called recursively

runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayUtil.java
The function renderMinimapLocation() inputs expected a top-left position, but was given centre positions. It now expects a centre position.
This fixes issue #4518
=> Centre minimap highlight dot over target location

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
- Instead of packing frame first and then resizing and revalidating it,
pack it at the end so there is no overhead of resize and repaint events.
This save another like 200ms from startup time.
- Validate screen bounds after setting them to minimum size
- Update frame config after window custom chrome is set
See also #4470
=> Pack and show frame only after properties update

runelite-client/src/main/java/net/runelite/client/Notifier.java, runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/chat/ChatMessageManager.java, runelite-client/src/main/java/net/runelite/client/chat/CommandManager.java, runelite-client/src/main/java/net/runelite/client/game/ClanManager.java, runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java, runelite-client/src/main/java/net/runelite/client/plugins/PluginManager.java, runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePlugin.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBoxOverlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/tooltip/TooltipOverlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/worldmap/WorldMapOverlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/worldmap/WorldMapOverlayMouseListener.java, runelite-client/src/main/java/net/runelite/client/util/SceneTileManager.java
Instead of using providers in classes that should not be even used when
the optional dependencies are not present, move all Provider<> injects
to RuneLite (and to other top-level classes in other cases).
=> Properly use javax.inject.Provider

runelite-client/src/main/java/net/runelite/client/Notifier.java, runelite-client/src/main/java/net/runelite/client/chat/ChatMessageManager.java, runelite-client/src/main/java/net/runelite/client/menus/WidgetMenuOption.java, runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/DiaryRequirementsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/RequirementStringBuilder.java, runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/friendnotes/FriendNotesPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeOfferSlot.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/inventorytags/InventoryTagsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/itemprices/ItemPricesOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerDoseOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/puzzlesolver/PuzzleSolverPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/runepouch/RunepouchOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java, runelite-client/src/main/java/net/runelite/client/util/ColorUtil.java, runelite-client/src/main/java/net/runelite/client/util/SwingUtil.java, runelite-client/src/test/java/net/runelite/client/util/ColorUtilTest.java
This adds `ColorUtil::colorTag`, `ColorUtil::prependColorTag`, and `ColorUtil::wrapWithColorTag`, and implements them in existing plugins, as well as moving some color-related functions from `SwingUtil` into this new class.
Uses of `<col` in strings have been maintained as it is entirely proprietary to our code. (specifically the chat notifications plugin) Some uses of `<col=` ([1](https://github.com/Nightfirecat/runelite/blob/37407976a529cffc4cf34ee8fef5216c750a76b2/runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargePlugin.java#L53), [2](https://github.com/Nightfirecat/runelite/blob/37407976a529cffc4cf34ee8fef5216c750a76b2/runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/KourendLibraryPlugin.java#L199), …
=> Add color utility class

runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/LumbridgeDiaryRequirement.java
=> Fix achievement diary plugin requirements

cache/src/test/java/net/runelite/cache/script/assembler/AssemblerTest.java
Tests were failing on Windows for me when running `mvn install`. Fixed by replacing \r\n with \n when asserting the `expected` value.
Another workaround is disabling autocrlf in git for this project, but I feel it's not reasonable to expect all contributors on Windows to do this.
=> Fix Assembler tests when autocrlf=true on Windows

runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java, runelite-client/src/main/java/net/runelite/client/util/HotkeyListener.java
Finding when keyUp actually happens is difficult because you have to store state to tell if a key is up on modifier or it's optional non-modifier. The current implementation is good enough for masking events, but not accurate enough for generating them
Fixes #4513
=> runelite-client: Make hotkeys run on KeyPressed

runelite-api/src/main/java/net/runelite/api/Perspective.java
Safe-check tile settings size to prevent array out of bounds exception.
Fixes #4579
=> Fix tile setting and tile height ArrayOutOfBounds

runelite-client/src/main/java/net/runelite/client/game/LootManager.java
We pack scene x/y and not world x/y, so create world point from scene.
=> Fix LootManager zulrah location

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
- Reverse ClientUI sidebar condition as when opening sidebar is always
open so current master will effectively shrink window instead of
restoring to correct size
- Apply this condition also to KEEP_WINDOW_SIZE
=> Reverse ClientUI sidebar condition

runelite-client/src/main/java/net/runelite/client/game/LootManager.java
Remove special cased wizard death animations from loot manager as as of
latest OSRS update this now works normally:
The Elemental Wizards south of Falador now give loot at the end of their
death animation rather than the beginning.
=> Remove special cased wizard death from loot manage

runelite-client/src/main/java/net/runelite/client/plugins/screenmarkers/ui/ScreenMarkerPanel.java
Instead of using marker overlay name use marker name, as marker overlay
name contains date.
Fixes #4634
=> Use correct marker name when cancelling edit

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerBox.java, runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerItemEntry.java, runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
- Account for linked item id when getting item price
- Format item price tooltip
- Create new data structure for loot tracker and precompute it
to avoid calling methods that are unsafe outside of client thread
Fixes #4644
=> Account for linked item id, format tooltip

runelite-client/src/main/java/net/runelite/client/RuneLite.java
Currently the session simply overwrites default settings and if they
were not persisted before, they will be just null. Load session before
loading default config to fill empty places.
Fixes #4681
=> Fix order of loading session settings

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatOverlay.java
Fixes #1505
This fix will change the plugin to use the last menu entry instead of the widget item query it did before.
The widget item area is off by a pixel (needs to be moved +1 from top and left). If it is desired to keep using the widget item query then this PR should be discarded.
Issue at hand:
After fix:
=> item stats: fix tooltip not appearing when hovering over item

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
All chat messages are either checked for equality to command strings
which are not followed by spaces or are checked to start with command
strings followed by a space, and use the constants' length (plus one,
for the space) to get the command argument.
=> chat commands plugin: Use consistent message check

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
Added tablet creation animation to the idle notifier. Tested with b2p, 3 enchants and 3 teleports.
All had same animation.
Resolves #4694
=> Add tablet creation animation to idle notifier

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
If frame is opened too fast and game did not managed to create the
canvas yet, frame will crash during startup on NPE.
Log with error: https://pastebin.com/AdF74i3p
=> Add null-check for game canvas

runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/feed/FeedPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/KourendLibraryPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/notes/NotesPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/SkillCalculatorPanel.java
Now all plugin panels have tooltips so the headers are not necessary and
most of plugins do not have them already.
Preview:
=> Remove unnecessary headers from plugin panels

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/IndexDataBase.java, runelite-api/src/main/java/net/runelite/api/hooks/Callbacks.java, runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/callback/Hooks.java, runelite-client/src/main/java/net/runelite/client/plugins/zoom/ZoomPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSIndexDataBaseMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
Instead of creating new callback and then simply setting boolean on
RuneLite to dump it somewhere, expose this boolean from IndexDatabase
and remove injection of RuneLite.
=> Move isOverlayOutdated to IndexDatabase

runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesOverlay.java
Add support for integration of XP globes with DETACHED overlay system,
e.g making them moveable.
Preview:
=> Add support for making XP globes moveable

runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java
With the latest update some widget IDs changed. Report button was no longer showing any text set from the Report Button plugin.
=> Update chatbox widget IDs

runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordGameEventType.java
Add the Woodcutting Guild location to the activities on the "Discord" plugin.
Concerns #4218
=> DiscordPlugin: Add Woodcutting Guild to Activities

runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TimeTrackingPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/timetracking/hunter/BirdHouseTracker.java
Remove the plane check for the farming tracker, since seaweed patches are found on plane 1, not 0.
Fixes #4807
=> time tracking: fix detection of state for seaweed patches

runelite-client/src/main/java/net/runelite/client/ui/components/IconTextField.java
Simple little addition to all searchbars. If anyone wants to style it better, just ask for push access.
Updated:
The PR originally looked like this:
=> UI: Add a clear button (×) to IconTextField

runelite-client/src/main/java/net/runelite/client/ui/components/IconTextField.java
As .setText on FlatTextField is called from non-swing threads, send
showing of the 'x' button back to swing thread. This prevents freeze of
the game in rare scenarios.
=> Fix FlatTextField unsafe swing access

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpPanel.java
This reduces the top margin of the exp tracker UI to match the other sides and the similarly designed Loot Tracker.
Before:
After:
=> Fix exp tracker UI margin incosistency

runelite-client/src/main/java/net/runelite/client/util/HotkeyListener.java
The client doesn't care if it gets erroneous keyReleased events, and fixing this is not entirely trivial.
Fixes #4897
=> runelite-client: Don't consume keyReleased events

runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldHopperPlugin.java
Currently you can left-click a player's message in the chatbox and it will try to hop, which will more than likely cause unintentional hops or even fatal ones.
The raiding party has no use here because when you are in one, only members on the same world are displayed.
=> Do not add Hop-to option to chatbox and raiding party

runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldHopperPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldSwitcherPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldTableRow.java
Bugs reported by @devLotto.
- Add to favorite/Remove from favorites menu options now update when clicked
- When you hop off a world it will now have a correct coloring on the activity label
- Remove default world hightlighting to prevent issues with the default world plugin running after the list has been painted
=> More World hopper bug fixes

runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java, runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
Beginning in Autumn 2018, teleblock timers will be half that of the
normal game mode: 150 seconds for a full teleblock, and 75 seconds if
the target had Protect from Magic active.
Ref: https://services.runescape.com/m=news/deadman-autumn-finals-and-winter-season?oldschool=1
=> timers plugin: Add fall/winter DMM teleblock timers

runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldSwitcherPanel.java
- If ordering by activity, it will now push empty activity worlds to the bottom of the list
- Activity ordering will now be consistent with the other ordering modes, ascending by default
Fixes #4938
=> World hopper activity ordering improvements

runelite-client/src/main/java/net/runelite/client/plugins/pestcontrol/Game.java, runelite-client/src/main/java/net/runelite/client/plugins/pestcontrol/PestControlOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/pestcontrol/PestControlPlugin.java
Closes https://github.com/runelite/runelite/issues/4974.
An update for mobile broke checking the shield widgets for hidden. They never technically hide until the game is over.
=> Fix pest control ui

runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPluginTest.java
Do no try to parse the list to strings including empty names.
Closes #5012
=> Omit empty strings in NPC indicators

runelite-client/src/main/java/net/runelite/client/plugins/wasdcamera/WASDCameraListener.java
Make pressing BKSPACE with empty chat buffer text exit typing mode in
WASD plugin.
=> Make pressing BkSPACE with empty chat exit chat

runelite-client/src/main/java/net/runelite/client/plugins/corp/CorpConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/corp/CorpDamageOverlay.java
People soloing/teaming corp don't necessarily care about their damage because BGS damage is tracked through special attack tracker.
=> corp: hide damage overlay

runelite-api/src/main/java/net/runelite/api/Client.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
I just wanted to verify this is the proper way to add camera setters before continuing work on a new plugin.  The plugin will add a 'look south', 'look east', and 'look west' to the compass similar to the current 'look north' option in the vanilla client. Thanks.
=> Add camera setters (X, Y, Z, Pitch, and Yaw).

runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPluginTest.java
- To make the notifier more precise make combat idle notifier use
interacting changed.
- In order to make animation idle notifier work with timer resetting, make
it remember last animation.
- When someone logs out, reset all timers to not have sent the
notifications after they are no longer relevant.
- When player clicks in-game, he obviously changed his activity, so reset
all idle timers to default non-valid state.
Closes #1614
Closes #5013 
=> Idle notifier fix combat notifications, reset notifications on interaction

runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldHopperPlugin.java
Fixes #5068
Now it is possible to quick hop into (and out) w26
=> #5068 fix: cant quick hop to w26

runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldHopperPlugin.java
This was preventing from the config.hopOutOfDanger to work properly when
disabled.
=> Remove dupe PVP_HR entry in world hopper

runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftPlugin.java
Checking a binding necklace with 1 charge shows "one" in the chat instead of 1.
=> Add "one" to binding necklace regex matching group

runelite-client/src/main/java/net/runelite/client/plugins/blastfurnace/BlastFurnaceConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/KourendLibraryOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/KourendLibraryPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/poh/PohConfig.java
A lot of people visit blast furnace without intention to actually do the
activity (e.g to buy ores) so simply disable the clickbox noise by
default and leave to user if they want them.
Make KourendLibrary plugin overlay show only on interaction with
bookcase or with customer after login, as by default the noise caused by
the overlays is horrendous.
To reduce default plugin noise add some common hidden items to
GroundItemsPlugin (basically same default hidden list as OSBuddy has).
Majority of players do not care about these and it is just permanent
noise in POH for them, leave the enabling of this setting to minority.
=> Reduce default plugin noise for regular users

runelite-api/src/main/java/net/runelite/api/coords/WorldPoint.java, runelite-client/src/main/java/net/runelite/client/game/LootManager.java, runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
Only triggering one event per location per tick should fix #4839
Player Death check Should fix #4653
Checking for onion in ToB inventory fixes #4695
=> Add player death check, ToB region check and 1 loot per-tile per-tick check to loot tracker events

runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSession.java
Show fishing overlays only when player can actually fish (e.g is in
fishing session or has fishing equipment). This drastically reduces
noise for casual players.
Closes #1069
=> Show fishing overlays only when player can fish

runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesPlugin.java
Vanilla RuneScape interface together with XP tracker already provides
all informations that is contained withing XP globes, so disable this
plugin by default to reduce the unnecessary noise for casual users.
=> Disable XP globes plugin by default

runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerDoseOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/runenergy/RunEnergyOverlay.java
Fixes both prayer and run energy orb overlays showing when minimap is hidden.
Before:
After:
=> Don't show orb overlays when the orbs are hidden

runelite-client/src/main/java/net/runelite/client/plugins/runenergy/RunEnergyOverlay.java
I'm not sure if there should be a separate toggle (probably not..) for this, since the hover does show in minutes:seconds instead of just seconds like the orb.
Before:
After:
=> Show run energy remaining in overlay if orb shows run time remaining

runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayBounds.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayManager.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayPosition.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayUtil.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/WidgetOverlay.java
Instead of making RuneScape widgets detached, make them layoutable
- Add new snap corner CANVAS_TOP_RIGHT that is basically minimap
position
- Make WidgetOverlay use standard overlay layouting
- Adjust paddings in the OverlayRenderer to match game more closely
- Fix issue with ordering of the overlays
Preview:
=> Make RuneScape widgets layoutable

runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
Make bottom-right snap corner not account for chatbox being opened or
not.
Closes #5344
=> Make bottom-right snap corner not account for chatbox

runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingPlugin.java
Check both inventory and equipment when receiving item container change
events instead of hiding overlay if item is not contained in all
item containers.
Closes #5341 
=> Fix fishing plugin inventory/equipment check

runelite-api/src/main/java/net/runelite/api/ScriptID.java, runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/DiaryRequirementsPlugin.java
This interface was ported to a different widget (in #5346), but that interface has a dynamic length, controlled by cs2 2523, which is called by the server when the interface is filled. Simply call the cs2 again after the next one has ran with our new linecount.
=> diaryreqs: Update scrollbar with new length

runelite-api/src/main/java/net/runelite/api/queries/ActorQuery.java, runelite-api/src/main/java/net/runelite/api/queries/DecorativeObjectQuery.java, runelite-api/src/main/java/net/runelite/api/queries/GameObjectQuery.java, runelite-api/src/main/java/net/runelite/api/queries/GroundObjectQuery.java, runelite-api/src/main/java/net/runelite/api/queries/InventoryItemQuery.java, runelite-api/src/main/java/net/runelite/api/queries/NPCQuery.java, runelite-api/src/main/java/net/runelite/api/queries/PlayerQuery.java, runelite-api/src/main/java/net/runelite/api/queries/TileObjectQuery.java, runelite-api/src/main/java/net/runelite/api/queries/WallObjectQuery.java
Deprecate all queries that have already existing
spawned/despawned/change events.
=> Deprecate queries with already existing events

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java
Closes #5414
Simple fix, they wanted highlights to clear after they have killed the final monster on task. Previously it would only remove them once a new task was received from a slayer master.
Not sure if entirely useful or wanted but only took a minute so do with it as you please.
=> Remove npc highlights on task completed message.

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPluginTest.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
- Add mappings for mouse last pressed millis 
- Use mouseLastPressedMillis instead of mouseIdleTicks as
only mouse press events indicate that player is idle, and not mouse
movements
- Use also keyboard check when resetting idle when active
Closes #5374
=> Use mouse press events and not mouse movement events in idle notifier

runelite-client/src/main/java/net/runelite/client/plugins/PluginManager.java, runelite-client/src/main/java/net/runelite/client/util/GameEventManager.java
- Rename RegionTileManager to GameEventManager
- Add simulating of ItemContainerChanged events
=> Simulate ItemContainerChange events on plugin startup

runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSpot.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSpotMinimapOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSpotOverlay.java
As now the fishing spots get hidden automatically and shown
automatically it is no longer necessary to have per-spot configuration.
=> Remove unnecessary fishing spot configuration

runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java
Fixed WidgetIDs for Barbarian Assault plugin to work as intended:
before:
after:
fixes #5471
=> BA plugin: widget overlay fix

runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoPlugin.java
The plugin is initialized with `lastTime` as null, meaning that if
`onGameTick` is called before `onInteractingChanged`, you can encounter
a case where after starting the client or plugin, `lastTime` has not yet
been set while `client.getLocalPlayer().getInteracting` is null (because
`onGameTick` gets sequenced before `onInteractingChanged` per tick),
causing an NPE when trying to compare a null Duration.
Fixes runelite/runelite#5451
=> opponent info plugin: Fix possible onGameTick NPE

runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsPlugin.java
This will cause the "Lookup" player menu entry to be colorized according
to the player indicators plugin options.
Fixes runelite/runelite#3806
=> hiscore plugin: Colorize "Lookup" player menu entry

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollEmoteOverlay.java
The visible area of emote widgets will now be highlighted, regardless of
whether the widget is partially outside the emote window.
Fixes runelite/runelite#4163
P.S. This is the code I used to test the updated rendering logic: https://gist.github.com/Nightfirecat/8775bcc940988914535167efa84c4731
=> clue scroll overlay: Show visible emote widget area

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java
Fix & centers the WorldPoint tile for the Asgarnia Warriors HotColdLocation entry
=> Fix Asgarnia Warriors Hot/Cold WorldPoint

runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcSceneOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/RenderStyle.java
Config option added to highlight the southwestern tile in the NPC indicators plugin.
[Example](https://i.imgur.com/PA6rOoK.png)
Closes #5265
=> Show southwestern tile on highlighted NPCs (useful for safespotting/bursting/chinning large NPCs)

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerBox.java
Fixes #5573 
There was a check in the box's constructor that checked if the subtitle was null or empty. This was left from the first version of the loot tracker where a box's subtitle would never change, but now, a box's title can be changed in grouped view.
All I had to do was still add the subtitle label to the container regardless of wether the initial subtitle was valid or not.
=> Fix loot tracker box subtitle

runelite-client/src/main/java/net/runelite/client/plugins/notes/NotesPanel.java
=> Reduce tab size in notes panel to 2

runelite-client/src/main/java/net/runelite/client/discord/DiscordPresence.java, runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordState.java
Updated plugin to allow disabling of elapsed time. EventWithTime start property now nullable and will be set depending upon config checkbox.
Also fixed a comment that was a copy paste error.
Closes #5282
=> Add option to disable time elapsed on discord activity

runelite-client/src/main/java/net/runelite/client/ui/overlay/worldmap/WorldMapOverlay.java
The bounds for the canvas in fixed mode are offset to the right by the size of the border. This translates the canvas bounds back to the left so we don't clip the icon if it's on the left side.
Fixes #5618
=> Fix clipping in fixed mode for edge snapping map points

runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerBarOverlay.java
Changes the Prayerbar background color from white to black.
The flick line indicator is given a variable for easier configuration and changed from black to red.  Red contrasts starkly with the cyan and the black.
Fixes #5582
=> Change Prayerbar Color Scheme to be Colorblind Friendly

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java
Now match the location suggested by user and cross-referenced with osrs wiki to confirm as there were two possibilities.
Fixes #4453
=> Fix West of the Keldagrim entrance Hot/Cold clue location

runelite-api/src/main/java/net/runelite/api/Actor.java, runelite-api/src/main/java/net/runelite/api/Perspective.java, runelite-client/src/main/java/net/runelite/client/plugins/blastmine/BlastMineRockOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonSpotOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/demonicgorilla/DemonicGorillaOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/SceneOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSpotOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/hunter/TrapOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/KourendLibraryOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeRocksOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/mta/alchemy/AlchemyRoom.java, runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcSceneOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerBarOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/tithefarm/TitheFarmPlantOverlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayUtil.java, runelite-mixins/src/main/java/net/runelite/mixins/RSActorMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSDecorativeObjectMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSGameObjectMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSGroundObjectMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSModelMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSPlayerMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSWallObjectMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/TileObjectMixin.java
- Properly rename world->local Perspective methods and force them to
accept LocalPoint to prevent confusion
- Remove unused params from Perspective methods
=> Properly name Perspective methods, remove unused method params

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/NodeCache.java, runelite-client/src/main/java/net/runelite/client/plugins/interfacestyles/InterfaceStylesPlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/SpriteMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/WidgetSpriteMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
- Expose NodeCache interface in RuneLite
- Expose Client.getWidgetSpriteCache and reset method on it
- Change setters for sprite and widget overrides to be getters
=> Make sprite and widget sprite overrides more flexible

runelite-client/src/main/scripts/ChatboxInputHandler.rs2asm, runelite-client/src/main/scripts/ChatboxInputInit.rs2asm
Whenever the widetids for the chatbox input change the listener gets added twice, so all inputs get duplicated. This makes our handler check the varc before adding text, preventing this from happening as much.
=> runelite-client: Don't duplicate chatbox input when widget ids are wrong

runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsOverlay.java
This will prevent the scout overlay from rendering while at Olm as the information there is obsolete.
Closes #5721
=> Make raids scout overlay not show at Olm

runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/wasdcamera/WASDCameraPlugin.java
After the player indicators commit revert there was still an opportunity for ColorUtil functions to be applied, as well as in the newly-added (since creating ColorUtil) WASD camera plugin.
=> Use ColorUtil functions instead of creating the color tag manually

runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
Fixes #5176.
This PR updates the stamina potion timer functionality so that the timer also shows up when the player gets a stamina boost from another player (via Boost Potion Share spell)
=> update stamina potion timer to include shared stamina potions

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerBox.java
Fixes #5673.
Only truncates the title of the log. Which means both subtitle and price will show up totally.
Because the name can now be truncated, I also added a tool tip for usability sake.
Example of it working:
=> Implemented NPC name truncation in loot tracker

runelite-client/src/main/java/net/runelite/client/config/ChatColorConfig.java
This is to prevent the highlight color from bleeding trough which happens currently for the raids ending message (see image)
It also changes the highlight colour to red because:
1) it seems the other raids messages use the pink as normal colour and red as highlight
2) the pink is sometimes (e.g. transparent chat) not easily readable.
=> Add default cc info chatcolor and change cc info highlight to red

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
Adds usage hints to the config description for each of the chat commands.
Closes #4298
=> Chat Commands: Add hints to config description

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/plugins/tileindicators/TileIndicatorsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/tileindicators/TileIndicatorsOverlay.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
Add tile that is currently being hovered to tile indicators.
Preview:
=> Add currently hovered tile to TileIndicators

runelite-api/src/main/java/net/runelite/api/Experience.java, runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerPlugin.java
Fixes #2631.
Not sure if two different configurations was the best way of do it. I could have used the XP Tracker config for the XP Globals, but thought mixing configs was a mess.
Let me know if I should change this.
=> Implemented the ability to hide both globes and xp tracker after 99

runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordGameEventType.java
Closes #5802
Corrects the spelling of Burthorpe for Discord's rich presence.
=> Fix Burthorpe spelling in Discord Rich Presence

runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java, runelite-client/src/main/java/net/runelite/client/ui/SkillColor.java
The previous similar PR has been abandoned for months even tho I supplied most of the code for it (wasn't a lot anyways).
This is a simple improvement to the exp globes, something that I'm sure a lot of people want, including me.
**If any of you native english speakers have some ideas on how to improve the wording of the config item, i'd appreciate it, I had a bit of trouble with that.**
Should probably close #4591
Closes #2888
=> Add default skill color to XP globes

runelite-client/src/test/java/net/runelite/client/util/StackFormatterTest.java
Start of my crusade against the stack formatter, however likely worthwhile as a standalone readability improvement.
Removes the need for the developer to know how java's default number formatter will format a given string to understand a test.
=> Improve readability of stackformatter tests

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-api/src/main/java/net/runelite/api/GraphicID.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
Closes #5571 
Prevents Idle alert notifications being sent for:
- Fertile Soil
- Boost/Stat Potion Share
- NPC Contact
=> Remove idle alerts from Lunar Spells shared animation

runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesOverlay.java
The old progress bar was annoying me apparently @deathbeam too, I decided to try and improve the progress display.
Started by refactoring slightly the logic on the "on hover" rendering as it made little sense.
I also had to move the rendering of the skill image as it was being displayed on top of the dark overlay, the whole point of the dark overlay was to darken the background so that the white text was very readable.
I'm sure there are going to be people that complain about loosing the decimal places, but the exp tracker also does not show them and I haven't heard of that being an issue yet, who cares if it's 25,6 or 25, come on.
=> XP Globes - Move progress bar display from tooltip to globe

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
Skip all empty spots in ItemContainer#getItems array by checking if
itemId > 0.
=> Skip empty spots in Loot Tracker when getting items

runelite-api/src/main/java/net/runelite/api/VarPlayer.java, runelite-api/src/main/java/net/runelite/api/Varbits.java, runelite-client/src/main/java/net/runelite/client/plugins/kingdomofmiscellania/KingdomPlugin.java
Now uses the correct varp from the quest list completion state script (1358).
Additionally, allows the infobox to show if the quest is in progress to allow users to check favor during the last part of the quest. 
Closes #1980
=> Kingdom Plugin: fix throne completion state check

runelite-api/src/main/java/net/runelite/api/VarClientInt.java, runelite-client/src/main/java/net/runelite/client/plugins/mousehighlight/MouseHighlightOverlay.java
VarClientInt(2) is set to `1` whenever a tooltip is present, meaning we should never render a tooltip when it is set that way. Some menu options (world map dungeon links) have a null widget associated with them, and do not utilize the TOOLTIP_TIMEOUT VarClientInt, so this check is necessary to avoid adding a duplicate tooltip.
Fixes runelite/runelite#3278
=> mouse tooltips: Don't add a tooltip if another is present

runelite-client/src/main/java/net/runelite/client/plugins/chatnotifications/ChatNotificationsPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/chatnotifications/ChatNotificationsPluginTest.java
This fixes an issue where the chat notifications plugin would not split word higlights when input as `some,highlight` even though they are supposed to be valid.
=> Fix chat notification highlight words split regex

runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
This is to fix an issue where under certain circumstances such as input or dialogue being open, these snapped overlays were not being rendered.
=> Fix snapped overlays above chatbox not being rendered

runelite-client/src/main/java/net/runelite/client/plugins/regenmeter/RegenMeterOverlay.java
This will prevent the end of the stroke from overlapping the beginning
=> Change regen meter stroke end-cap style to CAP_BUTT

runelite-client/src/main/java/net/runelite/client/RuneLiteModule.java, runelite-client/src/main/java/net/runelite/client/plugins/account/AccountPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeSearchPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java, runelite-client/src/main/java/net/runelite/client/plugins/info/InfoPanel.java, runelite-client/src/main/java/net/runelite/client/util/CallableExceptionLogger.java, runelite-client/src/main/java/net/runelite/client/util/ExecutorServiceExceptionLogger.java
By default, executor service eats all exceptions and forwards them to
failed futures, so in order to actually see what happened one must check
the resulting future, what is not ideal. Instead, log every exception
from scheduled service using slf4j logger.
I used this for debugging #5695, and I think it is good addition so stuff like that will not happen in future.
=> Add executor service logger that logs exceptions

runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordGameEventType.java
Closes #5802
Original issue was to fix the spelling of Burthorpe whilst in the city. It was mentioned today that the spelling was also incorrect whilst in the Minigames room.
=> Fix spelling of Burthorpe Games Room in Discord Rich Presence

runelite-client/src/main/java/net/runelite/client/plugins/banktags/BankTagsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java
Closes: https://github.com/runelite/runelite/issues/3561
Also fixes active tab unactivating with long tags and editing tags
=> Fix tags resetting when bank window is closed and active tab matching for long tags

runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java
Fixes an issue reported from IRC/discord.
```
When I have three bank tag tabs, third bank tag tab in focus; When I right click second tag tab and "change icon", then immediately click "change icon" again to cancel that action, my icon changes (to a dust rune). This does not happen when I do the same to my tag tab in focus.
Similarly, the bug happens with first bank tag tab except it turns into a mist rune. The two runes aren't next to each other in the actual bank tab (there's an earth rune in between).
```
=> Don't fetch itemid of Change Icon menu option on tabs

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java
Because it is now updated from changed events, this will simply make the
item reqs not work.
=> Do not reset equipment/inventory in clues croll plugin each tick

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatChanges.java
=> Add Gout Tuber heal info to Item Stats plugin

runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsOverlay.java
- Remove "Raid scouter" title
- Move raid layout to title instead
This change is because the raid scouter is quite big and now that it can
be persisted after raid starts, it is a bit annoying in fixed mode.
Also, the title is effectively useless as it is visible only in raid and
it is quite obvious what is it.
=> Move raid scouter layout to title

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
Even though the swapper plugin is disabled by default, many people
enable it and these defaults are very niche and annoying in some
scenarios.
=> Disable bury and harpoon swaps by default

runelite-client/src/main/java/net/runelite/client/util/GameEventManager.java
I don't think this will affect many (if any) plugins currently, but it will be useful for some work I'll soon be submitting to remove deprecated `Query` usage.
=> GameEventManager: Simulate Actor spawn events

runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java
In order to not have config file flooded with invalid and corrupted
properties in case of file corruption, remove all these invalid
properties from property map on configuration load.
In order to prevent failures on reading/writing incorrectly escaped
characters or writing special UTF-8 characters on save as gibberish,
explicitly specify UTF-8 encoding when loading and writing properties.
Use OS-wide exclusive lock when writing configuration file to filesystem
to prevent config file corruption when multiple concurrent writers try
to write to same config file at same time.
Closes #4853
=> Implement locking and corrupted file sanitization to ConfigManager

runelite-api/src/main/java/net/runelite/api/VarPlayer.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java
When opening the slayer reward shop it will update your remaining task count granted runelite already knows what task you have.
Closes https://github.com/runelite/runelite/issues/5984
=> Update slayer task based on VarPlayer value if available

runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java
In addition to sorting config panel options by position, sort them also
by name to remove need of setting positions everywhere for consistent
order.
Closes #1270
=> Sort config panel options by name as well

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java
Given the recent, and ongoing problems with clue text, this adds an error when we fail to match against any known clue.
This means in scenarios where strange formatting on jagex's side is to blame, the user can provide the needed information on how the string is formatted, rather than a developer having to run clues until they're able to reproduce it.
=> Log error when encountering an unmatched clue string

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/ThreeStepCrypticClue.java
- Instead of depending on specific formatting and size of clue text, just
split and parse everything stripping all tags when needed.
- Null-check location in multi-location clues (sometimes it can be null)
- Fix #5968 punctuation
Closes #5968 
=> Make 3 step cryptic clues more robust

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java
Previously location was inside of a tree: 
Correct dig position:
=> Fix ASGARNIA_MIAZRQA Hot-Cold clue location.

runelite-api/src/main/java/net/runelite/api/VarPlayer.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java
This reverts commit f6aad4c4f1afc23b0c76a3db916c734513c772dc.
VarPlayer 261 is used in a multitude of scripts that updates to other values unrelated to slayer.
=> Revert #5989

runelite-client/src/main/java/net/runelite/client/Notifier.java
This will allow for icons for OSX notifications and its usually pretty
standard library to have. Also allows grouping of notifications and
click-to-activate.
Preview:
=> Use terminal-notifier when available for OSX

runelite-client/src/main/java/net/runelite/client/plugins/banktags/BankTagsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/banktags/TagManager.java, runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java
Instead of trying to tag and find notes and placeholders, find real item
ids.
=> Unify calls for getting real item id for bank tag

runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPlugin.java
Adds a new option to the dev tools to show more info of the currently hovered NPC, object or item. The ID and, if applicable, the world coords are added after the examine target in the right click menu.
=> Add examine info to dev tools

runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanChatPlugin.java
Fixes recent clan chats showing behind new account overlay
=> Don't show recent chats if account is new enough

runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java
The feature displays your display name in the title, not your login username. This change is to avoid ambiguity between the two.
=> Change 'username' to 'display name' in usernameInTitle

runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldHopperPlugin.java
Fixes #5679 
Because `getChatPlayerFromName` checks to see if the target player is a friend first, it finds the target player as their friend. However, if their private chat is off, their world will be returned as `0`, and thus the hop-to option is not displayed. This fix checks for the target player in the clan chat list first, and if it can't find the player, then it searches the friends list.
=> Allow hop-to option in clan chat menu when target player is a friend and their private chat is off

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
As now the config options are sorted by name, and that was the only
purpose of having the positions set in menu entry swapper config, remove
them.
=> Remove position config from menu entry swapper

runelite-client/src/main/java/net/runelite/client/plugins/puzzlesolver/PuzzleSolverOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/puzzlesolver/solver/PuzzleSolver.java, runelite-client/src/main/java/net/runelite/client/plugins/puzzlesolver/solver/PuzzleState.java, runelite-client/src/main/java/net/runelite/client/plugins/puzzlesolver/solver/heuristics/ManhattanDistance.java
Makes it easier to distinguish between -1 as in an 'unset' value and -1 as in the blank tile value.
=> puzzlesolver: break out blank tile value into a constant 

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
In cerb lair the option is "Quick Pass" not "Quick-pass" like in Raids
1.
=> Swap also "quick pass" in Cerb lair

runelite-client/src/main/java/net/runelite/client/plugins/wasdcamera/WASDCameraListener.java
For quick entering in-game and RuneLite commands. Same principe as for
clan chat applies.
=> Make colon (":") enter chat in WASD mode

runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobe.java, runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerService.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerServiceImpl.java
Use correct target XP so actions left with set goal are not wrong (and
also to simply support in-game target goals).
=> XpGlobes: Use correct target XP

runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayManager.java
The update needs to be done ALWAYS before widgets are drawn
=> Keep WidgetOverlay always on UNDER_WIDGETS layer
