runelite/runelite

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java
Remove full clue description (clue text) from cryptic clues and hot/cold clue as the solutions are written right below and with the full text this sometimes makes clue helper unusable in fixed mode.
=> Remove full clue description from Hot/Cold and Cryptic Clues

runelite-client/src/main/java/net/runelite/client/plugins/attackstyles/AttackStylesPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/attackstyles/AttackStylesPluginTest.java
There's no good reason for this plugin to have 3 separate events for a Varbit changing
=> Refactor AttackStyles Plugin events

runelite-client/src/main/java/net/runelite/client/plugins/stretchedmode/StretchedModePlugin.java
Fixes #6294
Triggers max canvas size to set itself again. Now with the usual max size and not our getRealDimensions one.
=> stretchedmode: fix size not being reset on plugin disable

runelite-client/src/main/java/net/runelite/client/plugins/tileindicators/TileIndicatorsOverlay.java
Currently it's wrong by 4 pixels horizontally and vertically when left clicking on fixed screen
=> Improve hovered tile accuracy

runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPluginTest.java
- Properly update last action times in Idle Notifier right after the
action is changed/updated.
- Do not reset lastCombatCountdown in resetTimers()
- Take lastCombatCountdown in account when throwing combat idle notif. In case user has combat idle set to 0, this ensures that the idle notif
will not fire right away.
Supersedes/closes #6241
Extracted from #5369
Closes #5961 
=> Properly update last action times in Idle Notifier

runelite-api/src/main/java/net/runelite/api/Perspective.java, runelite-client/src/main/java/net/runelite/client/plugins/demonicgorilla/DemonicGorillaOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerBarOverlay.java
Our localToCanvas isn't taking the viewport offset into account which means a lot of scene overlays are currently misplaced by 4 pixels both horizontally and vertically when using fixed screen.
Before:
After:
Closes #4539
=> Fix localToCanvas on fixed screen

runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoOverlay.java
Added new checkbox that if left unchecked, will not display the opponents opponent when in multi combat areas for the opponent info overlay, acting as it does in single combat areas.
Closes #4361
=> Opponent Info - Added Show opponents opponent checkbox

runelite-client/src/main/java/net/runelite/client/chat/ChatMessageManager.java
Currently, Chat Commands doesn't work on dev builds when updating messages outside of the client thread, due to `ChatMessageManager#update` calling `Client#getVar` to get whether the chatbox is transparent. The value of this varbit is already stored when it changes, so it can be changed to work even outside the client thread.
Fixes #6348
=> [CMM] Make update not access varbits outside the client thread

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_agility.json
~~Looks like the XP for the Penguin course was copied to the Werewolf course.~~
Edit: as waycooler pointed out, Jagex have doubled the stick bonus.
=> Fix Werewolf agility XP given in skill calculator

runelite-client/src/main/java/net/runelite/client/plugins/zoom/ZoomPlugin.java
Any value greater than 1004 can cause an overflow with a large height, causing 3dzoom to be zero, crashing the renderer
Fixes #6358
=> zoom: Adjust inner zoom limit to safe value

runelite-mixins/src/main/java/net/runelite/mixins/StretchedModeMixin.java
Following concerns from BeefaloKing on Discord, scaling is now done differently so that the game isn't as stretched out when the window is wide and the scaling % is high.
=> stretchedmode: retain aspect ratio when scaling

runelite-client/src/main/java/net/runelite/client/game/NPCManager.java, runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpAction.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpActionType.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpState.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpStateSingle.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerPlugin.java
- Move NPC health data to NPCManager
- Extract action-related data from skill experience snapshots to separate class
- Add possibility for snapshot to hold multiple types of actions
- Add support for ACTOR_HEALTH action type that shows kills left, kills done and kills/hr in XP tracker sidebar
Preview:
Fixes #1594
Closes #4015
=> Add support for kills left, kills done and kills/hr to XpTrackerPlugin

runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/DiaryRequirementsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/Requirement.java, runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/RequirementStringBuilder.java, runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/KaramjaDiaryRequirement.java, runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/LumbridgeDiaryRequirement.java, runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/MorytaniaDiaryRequirement.java, runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/VarrockDiaryRequirement.java, runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/WesternDiaryRequirement.java
Added ability to add combat requirements to diarys also added all the current combat requirements.
ScreenShots:
When you meet the combat requirement.
When you don't meet the combat requirement.
=> Add ability to set combat requirements for achievement diaries

runelite-mixins/src/main/java/net/runelite/mixins/StretchedModeMixin.java
- The limits are no longer necessary as it is limited anyway to fixed mode
base size, and with new method of scaling the 100% max is quite
limiting.
- Instead of limiting width and height when stretching to fixed mode size,
limit scaling factor to fixed mode size to prevent improportional
stretching in resizable mode.
=> Unlimit stretched resizable mode and properly limit scaling factor

runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeItemPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeOfferSlot.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeSearchPanel.java
This PR changes the background color of all panels for the GE plugin to match the rest of RuneLite's plugins. It is the only one using medium_gray rather than darker_gray.
=> Make Grand Exchange plugin panel background color consistent

runelite-client/src/main/java/net/runelite/client/game/chatbox/ChatboxPanelManager.java
Otherwise key listeners stay running and that is not a good idea on the login screen
=> ChatboxPanelManager: Kill panels when logging out.

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Adds a config option that will swap `Shared` and `Private` on Raids storage units.
Closes #6015
=> Add raids private storage menuentryswapper config

runelite-client/src/main/java/net/runelite/client/plugins/barrows/BarrowsOverlay.java
- Make barrows minimap respect client minimap colors (what are
configurable from minimap plugin)
- Show all players on minimap inside barrows
Closes #2941
=> Make barrows minimap respect client minimap colors, show players

runelite-client/src/main/java/net/runelite/client/plugins/interfacestyles/InterfaceStylesPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/interfacestyles/WidgetOffset.java
When using the Bottom Line mode in resizeable, the icons are fine until one of the following events happens:
* The window is resized
* The plugin's state is toggled
* The game frame that should be applied is changed
Currently, fixing this requires the user to go into fixed mode and back into resizeable.
This happens due to the plugin using a widget's original X and Y values as the positions to reset the widget to. For every other widget, this works perfectly, but for whatever reason the original X and Y values for these icons are completely wrong. To fix this, the plugin now simply re-validates each widget, letting RuneScape place them in the correct position.
Before:
After:
=> interfacestyles: Fix resizeable mode widgets 

runelite-client/src/main/java/net/runelite/client/plugins/friendnotes/FriendNotesPlugin.java
Requires #6430 to avoid an issue where a player's password can become the note by relogging while editing the note.
=> friendnotes: Use new chatbox input dialogue

runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayUtil.java
The dots are supposed to be size of 4 and not 5.
=> Fix size of RuneLite minimap dots

runelite-client/src/main/java/net/runelite/client/plugins/puzzlesolver/PuzzleSolverOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/puzzlesolver/solver/PuzzleSolver.java
Fixes #5325.
Waits 1500ms after the start of computation before it thrashes the solver and remakes it.
Most puzzles take less than 20ms to solve, so it should always display a solution even though the user is spamming tiles (or, eh.. solving it quickly themselves).
=> puzzlesolver: wait a duration before recomputing the solution

runelite-mixins/src/main/java/net/runelite/mixins/ClickboxMixin.java
The bounding box limitation is not enough for preventing users from interacting with objects far away when the game window is wide.
This introduces a limit on how far away the camera can be from objects for you to be able to interact with them, remedying the issue above.
Fixes #6510
=> gpu: limit interaction distance from camera

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/plugins/loginscreen/LoginScreenConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/loginscreen/LoginScreenPlugin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
- Based on what field is currently selected, add support for pasting to that field with standard Ctrl-V keybinding (disabled by default)
- Add export for login screen password
- Add mappings for current login screen field selected
As OSB added this feature recently, and it is very useful one, also do not provides any security risks, there is no reason to not implement it.
Closes #3793
=> Add support for Ctrl-V pasting to Login Screen

runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java
The flag needs to be set before context is made current  and GL is
obtained.
After enabling the flag, this error should be now correctly logged to console in debug:
```
GLDebugMessageHandler: GLDebugEvent[ id 0x3e8
type Error
severity High: dangerous undefined behavior
source GL API
msg glUniformBlockBinding has generated an error (GL_INVALID_VALUE)
when 1542376048340
source 4.5 (Compat profile, arb, debug, compat[ES2, ES3, ES31], FBO, hardware) - 4.5.13521 Compatibility Profile/Debug Context 24.20.11021.1000 - hash 0x139f7e4]```
=> Fix JOGL context debug logging flag

runelite-client/src/main/java/net/runelite/client/plugins/hunter/HunterPlugin.java
Closes #6269 
As far as I can tell, this bug occurred because when the player's distance to the trap was greater than 1 tile, it didn't register the trap as being set by the player. As the boulders are 2x2 objects, the threshold needs to be set to 2 tiles.
=> Fixed maniacal monkey hunting trap bug

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
Use same icon alignment that is used for opening/closing sidebar with
custom chrome.
Closes #6435
=> Make sidebar icon consistent without custom chrome

runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java
Unlocking it on Windows with some iGPUs apparently causes problems and
this is relevant only for X11, so unlock only there.
=> Unlock surface only with X11JAWTWindow

runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java
This is necessary in order to properly free all resources on e.g Linux
(happens less often on Windows). Without
NewtFactoryAWT.destroyNativeWindow, the JAWT window created display
stays open after disabling the plugin and is freed only on application
close.
=> Properly destroy JAWT window on plugin shutdown

runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java
If GL is not even created due to missing library error or unsupported
version, this throws a lot of unnecessary exceptions to log and fails
on shutDown resulting in possibly improperly feed objects and displays.
=> Null-check GL and window on plugin shutdown 

runelite-client/src/main/java/net/runelite/client/plugins/attackstyles/AttackStylesPlugin.java
In side stones view, going through the spell autocast selection process
will cause the combat widget to become unloaded and reloaded, rather
than triggering the previous code path where the widget would change
hidden state. This commit adds a second subscriber to handle this path
as well.
Why do they do this differently? Who knows! :woman_shrugging: 
Fixes runelite/runelite#6557
=> attack styles: Fix style hiding after autocast selection

runelite-client/src/main/java/net/runelite/client/plugins/gpu/GLUtil.java, runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java
Draws the scene + ui on a frame buffer that is then stretched when it's drawn on the default framebuffer.
Maybe there is a more clever way but this seems like it works, on my system anyway.
Fixes #6487
=>  gpu: add stretched mode support 

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpStateSingle.java
fixes #6623 
works because after the 1st action skillTime is 0 so the two checks for `skillTime == 0` force the hourly actions and time to goal to be force set to 0.
we don't need these checks because the line in getTimeElapsedInSeconds that forces the skillTime to 60 if it's less than 0 handles the case of skillTime = 0 in addition to the really small skillTimes that line of code was designed to handle (according to the comment)
=> Fix action and time estimates only appearing after 2 actions

runelite-client/src/main/java/net/runelite/client/plugins/gpu/SceneUploader.java
The software renderer ignores the alpha when drawing textured faces
Fixes: https://github.com/runelite/runelite/issues/6540
Before:
After:
=> GPU: Fix Textured Faces With Alpha

runelite-client/src/main/java/net/runelite/client/plugins/loginscreen/LoginScreenPlugin.java
Trying to log in after pasting a string that was too long into the username or password field would cause an ArrayIndexOutOfBoundsException beforehand.
=> Truncate username and password string before pasting if necessary

runelite-client/src/main/java/net/runelite/client/ui/overlay/worldmap/WorldMapOverlay.java
Changes the world map overlay to only clip the graphics if it's necessary. `setClip` is fairly expensive and re-setting the clip for every map point could almost halve FPS when the world map was open.
=> World Map Plugin: optimize clipping for world map points

runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java
This ensures that we do not accidentally use constant from wrong GL
version than we are using atm.
=> Do not use static imports for GL constants

runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java
- Context can be created without GL being assigned (e.g in case version
is not supported)
- We need to lock jawtWindow if it is not locked always in case it is
not null, and not only when GL is set
=> Properly close GL context and lock surface

runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPluginTest.java
Using interactions instead of animations detects idling while fishing much sooner because fishing animations are incredibly long and can persists for up to 10 seconds beyond the point when the character has stopped fishing.
Here is a video demonstration of the new notification while barehanded fishing sharks. You can see how the  animation continues long after fishing has stopped.
https://www.youtube.com/watch?v=g5IkN4N8GtM
Example with cage fishing for lobsters too:
https://www.youtube.com/watch?v=Ju5m9RSAYMQ
One further change I made was to improve the check that prevents idle notifications from being sent while you're actually playing the game.
At the start of the onGameTick method in there is a check that includes checking for whether the user has clicked recently. If the user has …
=> Improve responsiveness of fishing idle notification

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/Constants.java
While working with getMouseIdleTicks(), getKeyboardIdleTicks() and getMouseLastPressedMillis() I noticed that the comments were incorrect or misleading so I've clarified them.
=> Correct some explanatory comments in runelite api

runelite-client/src/main/java/net/runelite/client/plugins/loginscreen/LoginScreenPlugin.java
Use the default command modifier key to paste on macOS instead of control.
=> Enable Command-V login screen pasting on macOS

runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityOverlay.java
This is no longer necessary (as we are using spawn events) and with GPU
plugin not limiting it is better (well, we are still limited by their
spawns obviously).
Closes #1360
=> Remove distance check from agility plugin

runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java, runelite-client/src/main/resources/net/runelite/client/plugins/gpu/fraguipremul.glsl, runelite-client/src/main/resources/net/runelite/client/plugins/gpu/vertuipremul.glsl
This changes the previous behavior, which instead of just scaling the UI texture, rendered the entire game into a smaller framebuffer and stretched that. This is much closer to actual UI scaling, in that we render the world view at its native resolution and only scale up the UI.
This should support all the options in the stretched mode menu as well as both fixed and resizeable mode.
Before:
After:
=> Add UI scaling when using GPU with stretched mode.

runelite-client/src/main/java/net/runelite/client/plugins/stretchedmode/StretchedModePlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/StretchedModeMaxSizeMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/StretchedModeMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSGameEngine.java
Now it takes max 1 frame for it to resize the canvas after changing the scaling percentage, instead of at most 500ms.
It now sets the max width and height right before the canvas is resized, so the canvas size uses those max bounds immediately, instead of setting it 500ms after the canvas is resized initially.
=> stretchedmode: reduce wait time after changing scaling percentage

runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
When becoming affected by an ice spell, such as Ice Barrage, when moving
prior to the effect's start, the previous code had a subtle bug where
the freeze timer would be applied in the chat message subscriber, but
the `client` would update the player's position before the onGameTick
subscriber was executed, meaning any movement on the same tick the
player became frozen would be registered as "movement", thus removing
that timer.
This fix sidesteps that issue by also ensuring that the client's tick
is different than the freeze tick, since that value appears to remain
unmodified between execution of these two methods.
Fixes runelite/runelite#6658
=> timers: Correctly add freeze timer upon frozen while moving

cache/src/main/java/net/runelite/cache/script/disassembler/Disassembler.java, cache/src/test/java/net/runelite/cache/definitions/savers/ScriptSaverTest.java, cache/src/test/resources/net/runelite/cache/script/assembler/681.rs2asm, cache/src/test/resources/net/runelite/cache/script/assembler/91.rs2asm, cache/src/test/resources/net/runelite/cache/script/assembler/Unicode.rs2asm
The id is needed for the script to be picked up, and is annoying to have to add manually.
=> Add id to script output

runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java
Fixes #6649.
Previous behavior:
New behavior:
=> Fix screenshots in GPU mode with Stretched Mode enabled

runelite-client/src/main/java/net/runelite/client/plugins/tearsofguthix/TearsOfGuthixOverlay.java
Canvas location can be null if the object is too far from view, so
null-check it.
=> Check for canvas location being non null in TOG

runelite-client/src/main/java/net/runelite/client/game/ItemManager.java, runelite-client/src/main/java/net/runelite/client/game/UntradeableItemMapping.java, runelite-client/src/main/java/net/runelite/client/game/UntradeableItemSellPrice.java
Add support to set prices of untradable items. The price of the untradable item is an amount of a tradable item (for example a mark of grace is worth 10 amylase crystals). These prices will be used in the getItemPrice method of the ItemManager. 
As a result, these prices will be displayed as GE prices in examine messages and the bank value. 
The following untradable items are already added:
* Marks of grace + Full graceful set
* Golden nuggets + Full prospector outfit
Fixes #6418
=> Untradable item price support for ItemManager

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerBox.java
The items container would show up empty if only ignored loot was dropped, validating the loot tracker box before repainting fixes this.
closes #6240
=> loot tracker: validate boxes after rebuilding

runelite-mixins/src/main/java/net/runelite/mixins/Rasterizer2DMixin.java
Gradient widgets (like smoke dungeon gradient and grotesque guardians gradient) are incorrectly turning opaque overlays behind them into black. This is due to us passing the color 0 instead of the correctly multiplied color to `drawAlpha`. The value is only used when the background is opaque however, which made it quite uncommon to encounter the bug.
=> Fix black overlays behind gradients in GPU plugin

runelite-client/src/main/resources/net/runelite/client/plugins/gpu/comp.glsl, runelite-client/src/main/resources/net/runelite/client/plugins/gpu/comp_small.glsl
Compute shaders should be supported on GL4.2 with ARB_compute_shader
extension so try to load the GLSL version with 420 support.
=> Try to enable compute shaders on GL 4.2

runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java, runelite-client/src/main/java/net/runelite/client/plugins/timers/GameIndicator.java, runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java, runelite-client/src/main/java/net/runelite/client/plugins/timers/IndicatorIndicator.java, runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
Adds an indicator to the Timers plugin that shows when vengeance is active on the player.  
Removes indicator when vengeance is used, player enters their house, or logs out.
I wasn't sure about where to put this feature. @deathbeam suggested the Timers plugin. I created `GameIndicator` in the plugin for indicator-type InfoBoxes . It might be worth creating a new plugin "GameIndicators" and adding non-timer or boost related indicators to it. (e.g. I'd like to add an InfoBox for current poison/venom hit amount.) Feel free to discuss in comments.
Edit: Addresses #3809
=> Vengeance active indicator

runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPluginTest.java
This is made under the Idle Notifier plugin as requested by @Adam- in the #3922 thread. Users should  be notified when special attack energy naturally regenerates to a set value (and if set to 0 it will be disabled just like other options in the plugin).
Fixes #1727
Closes #3922
=> Notify on Full Special Attack

runelite-api/src/main/java/net/runelite/api/GameEngine.java, runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java
Fixes #6524 
Not gonna lie, I don't really know what I'm doing here because there doesn't seem to be a way to see exactly what setReplaceCanvasNextFrame() does other than inferring from its name, but this fixes the issue I was having by calling setReplaceCanvasNextFrame(true) on shutdown of the GPU plugin.
=> Fix freeze on disabling GPU plugin

http-api/src/main/java/net/runelite/http/api/RuneLiteAPI.java, http-api/src/main/java/net/runelite/http/api/item/ItemClient.java, http-api/src/main/java/net/runelite/http/api/item/ItemEquipmentStats.java, http-api/src/main/java/net/runelite/http/api/item/ItemStats.java, runelite-client/src/main/java/net/runelite/client/game/ItemManager.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatOverlay.java
=> Add support for equipment stats to item stats plugin

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatOverlay.java
Fix the Item Stats overlay null pointer exception when item container is null.
Before:
After:
=> Fix Item Stats overlay with null equipement container

runelite-api/src/main/java/net/runelite/api/ScriptID.java, runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java
new file:   runelite-client/src/main/java/net/runelite/client/plugins/fakexpdrop/FakeXpDrop.java
new file:   runelite-client/src/main/java/net/runelite/client/plugins/fakexpdrop/FakeXpDropConfiguration.java
Enable fake xp drops on given tick to help with timing in efficient skilling as suggested by #6840. Defaults to disabled.
Closes #6840
=> xp drop on a set tick for efficient skilling

runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java, runelite-client/src/main/resources/net/runelite/client/plugins/gpu/comp.glsl, runelite-client/src/main/resources/net/runelite/client/plugins/gpu/comp_small.glsl, runelite-client/src/main/resources/net/runelite/client/plugins/gpu/comp_unordered.glsl
Use 4.3 for Windows, and 4.2 with extensions for Linux.
Closes #6931 
=> Make GL version choosing platform specific

runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityOverlay.java
Reverts runelite/runelite#6697. This very negatively affects FPS in elven lands since there are a large number of objects there with clickboxes, and it is checking each one on the whole scene each frame.
=> Revert "Remove distance check from agility plugin"

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatChanges.java
Fixes #6957, which requested to add the Bottle of Wine item (+14 hp, -3 attack levels) to the item stats plugin. This PR does so.
=> Add Bottle of Wine stats to item stats plugin

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/TargetWeaknessOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/Task.java
Fixes: #784
Current behaviour shows the required item to finish an NPC off above it's head when it's health is below the required threshold.
Works for Rockslugs, Gargoyles and Desert Lizards. (Let me know if I forgot any others).
=> Add Item overlay to show when monsters are weak enough to finish off

runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java, runelite-api/src/main/java/net/runelite/api/widgets/WidgetInfo.java, runelite-client/src/main/java/net/runelite/client/callback/Hooks.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/WorldMapLocationOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/WorldMapRegionOverlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayLayer.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/worldmap/WorldMapOverlay.java
Skips all overlays that aren't map related if the fullscreen map is open. 
Closes #5851
=> OverlayRenderer: Prevent overlays rendering if fullscreen map is open

runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordGameEventType.java
Currently we have this implemented inverse. Training should be "details"
as it is more detailed description of what player is currently doing,
and "state" should be "In Game", "In Menu", "Exploring", "Raiding" etc,
as that describes best what is player currently doing (also, e.g for
discord party integration, it is appended after state, so there always
MUST be some state, and this PR ensures that).
=> Flip state and details in Discord status

runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonSpots.java
Update cannon spots to add the Wilderness slayer spots as outlined in the Oblivion Wilderness Slayer Points guide.
=> Add wilderness cannon spots

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/FarmingPatchLocation.java, runelite-client/src/main/java/net/runelite/client/plugins/worldmap/FarmingPatchPoint.java, runelite-client/src/main/java/net/runelite/client/plugins/worldmap/WorldMapConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/worldmap/WorldMapPlugin.java
In response to #7091. 
Simply changes the tooltips of farming patches on the world map to show the farming patch type (Bush, Tree, Herb...).
Closes #7091
=> Add farming patch type to tooltips on world map

runelite-client/src/main/java/net/runelite/client/plugins/objectindicators/ObjectIndicatorsPlugin.java
When trying to highlight an object such as a trapdoor, the one to Keldagrim from the GE for example, or a staircase, the down stairs in Varrock West Bank for another example, a Null Pointer Exception was being thrown. Make sure the target objects tile is not null before trying to find the object to mark.
=> Fix NPE Object Indicators Plugin

runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/SkillCalculator.java
Any search bar filters persist when the user switches between skill calculators - instead, clear them.
=> Clear search bar when switching between skill calculators

runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java
This commit fixes the occasional issue of xp drops not being highlighted
while flicking prayer from the prayer menu; that is, before this commit
it was possible to select or deselect a prayer between xp drop widgets
being spawned, causing different highlighting for them. This commit
saves the active prayer at the beginning of each tick and uses that
tick's prayer for all widgets unhidden during that tick.
Fixes runelite/runelite#1280
Closes runelite/runelite#6679
=> experiencedrop: Maintain active prayer per tick

runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldTableHeader.java, runelite-client/src/main/java/net/runelite/client/util/ImageUtil.java
Closes #7022
Highlighted text is now a golden color (same color as the "Members World" color in WorldTableRow.java). Removed the white arrow images and replaced them with golden ones.
=> worldhopper: change WorldTableHeader highlight text and arrow color

runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsOverlay.java
After the introduction of the new ABOVE_MAP layer, the dev tools overlay
was no longer able to draw above the map, which is needed for the widget
inspector.
=> dev tools: Fix overlay layer

runelite-client/src/main/java/net/runelite/client/plugins/inventorytags/InventoryTagsPlugin.java
The client will use the first menu entry for 'Cancel' and only resets the menu action and menu option as that's all it uses. Overwriting the menu entries with all custom entries caused the 'Cancel' option to have erroneous fields.
Closes #5579
=> Inventory Tags: preserve 'cancel' when creating the custom menu

runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java
Closes #7001 
The right-click -> lookup option checks if the current world is a DMM world and will display the corresponding high scores tab instead of defaulting to the normal high scores.
=> World-Specific Highscores lookup

runelite-client/src/main/java/net/runelite/client/plugins/skybox/Skybox.java, runelite-client/src/main/java/net/runelite/client/plugins/skybox/SkyboxPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/skybox/SkyboxTest.java
This prevents the skybox from turning black when the camera goes out of bounds, but the player is still inbounds.
Closes #7239
=> Skybox: Do bounds check on the localPlayer's location, not the camera's

runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TimeTrackingConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/timetracking/clocks/ClockManager.java
The default time for timers in the timetracking plugin is now configurable.
Closes #7224
=> timetracking: add default time in minutes to config

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java
- Add new master clue hot/cold location, south-west of the Farming Guild.
- Add "general store" as a more accurate description for the Tree Gnome Village general store hot/cold step
Fixes #7254
=> Update Tree Gnome Village h/c description and add Farming Guild h/c location

runelite-client/src/main/java/net/runelite/client/plugins/crystalmathlabs/CrystalMathLabs.java
Make the CML Plugin only log the IOException message on failure to submit CML update.
<br>
<details><summary> The log.warn() output to console before:  </summary>
<br>
`
2019-01-02 14:26:48 [OkHttp https://crystalmathlabs.com/...] WARN  n.r.c.p.c.CrystalMathLabs - error submitting CML update
java.net.SocketTimeoutException: timeout
at okio.Okio$4.newTimeoutException(Okio.java:227)
at okio.AsyncTimeout.exit(AsyncTimeout.java:284)
at okio.AsyncTimeout$2.read(AsyncTimeout.java:240)
at okio.RealBufferedSource.indexOf(RealBufferedSource.java:344)
at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:216)
at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
at …
=> Only log the IOException message on failure to submit CML update.

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/FairyRingLocation.java
It was misplaced by 1 tile.
Before: 
After:
=> Worldmap: Fix CIR fairy ring location

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatOverlay.java
- Add support for unarmed attack speed to item stats plugin (6)
- Inverse attack speed display (lower is better)
=> Add support for unarmed a speed, and inverse a speed display

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java
Fix some pattern matching for new slayer game text, and record task locations. Locations are also stored in config, and displayed on the task counter:
(ignore the zero points/streak, the config was somehow wiped out, unrelated to this PR)
This does **NOT** add the new slayer monsters to the plugin, I will leave it to someone else to pick the icons for that.
The game text currently understood:
- Gem 'Check" progress (same as slayer helmet?)
- Konar dialogue for new task
- Konar dialogue with current Konar task
- Konar dialogue with current non-Konar task
- Slayer master dialogue with current Konar task
I don't know what the game text is for Konar tasks with:
- Receiving a task from a slayer partner
Testing this is slow, so help testing would be appreciated.
This would resolve #7267.
=> Add Slayer Task Locations (Konar)

runelite-api/src/main/java/net/runelite/api/MenuAction.java, runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/Overlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayManager.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
Adds the ability to add right-click menu options to overlays. By default these options requires the `shift` modifier key to be held when right-clicking but this can be changed via the RuneLite config settings.
<details>
<summary>
Code for adding the right click menu options
</summary>
<p>
```java
@Override
public List<MenuOption> buildMenuOptions()
{
List<MenuOption> options = new ArrayList<>();
options.add(new MenuOption("Reset", () -> log.info("Reset Option")));
options.add(new MenuOption("Pause", () -> log.info("Pause Option")));
options.add(new MenuOption("Something", () -> log.info("Something Option")));
return options;
}
```
</p>
</details>
=> Add right click menu functionality to overlays

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
Fixed [#7095](https://github.com/runelite/runelite/issues/7095)
Default Idle notifications will execute when animation 7199 (pisc crane repair) has ended.
=> Idle Notifier for repairing Piscarilius Cranes

runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPluginConfig.java
Add a cap to the 'fog depth' config in the GPU Plugin using the `@Range` annotation. The `@Range` annotation is already used for the 'draw distance' config, so I'm just adding it to the 'fog depth' config as well. The cap was selected to be 100, though 100 seems excessive, surely some people will/would like to use higher than my decided cap of 50, which I personally think is the highest reasonable fog depth, but to each their own. we'll set the cap to 100 for now.
=> Cap fog depth to 100 in the GPU Plugin.

runelite-client/src/main/java/net/runelite/client/Notifier.java
Default colour won't change since both Game highlights are `#EF1020` by default
Examples alongside other Game type messages
=> Make Game Notification use the Game message highlight colour

runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
It should've been here in first place, there is no reason for it to be
in ClientUI.
=> Move configManager.sendConfig to RuneLite#shutdown

runelite-client/src/main/java/net/runelite/client/discord/DiscordService.java
Even construction of DiscordEventHandlers causes UnsatisfieldLinkError
on unsupported systems, avoid this.
The error: https://pastebin.com/Md80g8KU
=> Wrap DiscordEventHandlers in native lib try/catch

runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java
Changed Anti-venom timer overlay time from 12 minutes to 1 minutes. Which is now consistent with Anti-vemon plus.
=> Add correct time for anti vemon potion

runelite-api/src/main/java/net/runelite/api/ScriptID.java, runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatKeyboardListener.java
Chatbox input is normally only rebuilt after a key is pressed, which caused a visual discrepancy after using clear shortcuts.
Closes #7466
=> chat commands: rebuild chatbox input after using clear shortcuts

http-service/src/main/java/net/runelite/http/service/xp/XpTrackerService.java
Do not discard all requests except last one in 1 second interval in XP
tracker.
=> Do not discard 1 second requests in Xp tracker

runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBoxManager.java
Refresh infoboxes only when removeIf and remove actually removes
anything to avoid constant refreshing for no reason.
=> Refresh infoboxes only when needed

runelite-client/src/main/java/net/runelite/client/plugins/cerberus/CerberusOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/inventoryviewer/InventoryViewerOverlay.java
Two plugins were using `OverlayMenuEntry` when they had nothing to configure.
Interacting with this menu item resulted in a null pointer being thrown inside `ConfigPanel` locking up a portion of the side panel until scrolling or clicking off onto another navitem.
Didn't see a need to add a check inside `ConfigPanel` to handle this as it shouldn't occur in the first place.
Removed two occurrences of this. I don't believe it is present in any other plugin.
=> Remove invalid OverlayMenuEntries

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/Raid.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/solver/Layout.java, runelite-client/src/main/java/net/runelite/client/util/Text.java
- Move ChatCommandsPlugin#sanitize to Text
- Add toRoomString and toCodeString Raid utilities - Add new util methods that will build room and code string from current raid layout.
- Send raid layout message on raid enter - Sends raid layout message as clan chat game message when entering raid.
Preview:
=> Add raid layout message

runelite-client/src/main/java/net/runelite/client/plugins/bankvalue/BankValuePlugin.java
If showing only GE or HA value do not add the GE/HA prefix.
Closes #1479
=> Dont display bank value GE/HA text when not needed

runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTabPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java, runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/PatchPrediction.java
This makes the farming plugin think ticks happen early, so if the tick actually is early it won't say your patch is done early.
=> farming: Give a more conservative estimate of when patches are done

runelite-client/src/main/java/net/runelite/client/plugins/barrows/BarrowsOverlay.java
Check the isMinimapVisable variable before drawing NPC dot on minimap in
barrows plugin.
Fixes #6672
Closes #6698 
=> Check if NPC is visible on minimap at barrows

runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java, runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsInput.java, runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPlugin.java
Fixes the tag option staying on npc's if they despawn while holding shift
Closes #4206
Closes #3844
Closes #4676
Note, this moves the tag option below walk here
https://i.imgur.com/Q9MT3D1.png
=> Change npc indicator plugin to not edit npc composition

runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordGameEventType.java
The space in the Discord Rich Presence is very limited and it is being
truncated by non-important prefix, so remove this prefix.
=> Remove activity prefix from Discord plugin

runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
Limit only overlays that are layoutable/moveable but not in snap corner.
Closes #7087
=> Limit only overlays that are not snapped

runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
Enabled by default. This was on original PR review and was discussed in
Discord. It is better to just use what we already use for adding our
custom entries at other places, and there is possibility that overlays
will have a lot of right click menus in future, so making it require
shift is most sane option.
=> Add option to require shift for overlay menus

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/chatcommands/ChatCommandsPluginTest.java
To avoid breaking existing plugins instead of properly escaping anymatch
(dot) just remove it as it do not changes the functionality.
Fixes #7615
=> Remove anymatch regex from chat commands plugin patterns

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java
Slayer points are updated while in the rewards menu, including before
and after a purchase. Previously, the points variable was updated on
each tick to whatever was displayed in the "Slayer points: "
widget, but that change was never reflected in the tooltip until the
next tooltip update. The tooltip now updates whenever a change in
slayer points is detected while in the rewards menu.
Closes #7611
=> Update slayer points in tooltip while in rewards

runelite-client/src/main/java/net/runelite/client/config/Alpha.java, runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java, runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/objectindicators/ObjectIndicatorsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/screenmarkers/ui/ScreenMarkerPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/tileindicators/TileIndicatorsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesConfig.java, runelite-client/src/main/java/net/runelite/client/ui/components/colorpicker/ColorPanel.java, runelite-client/src/main/java/net/runelite/client/ui/components/colorpicker/ColorValuePanel.java, runelite-client/src/main/java/net/runelite/client/ui/components/colorpicker/ColorValueSlider.java, runelite-client/src/main/java/net/runelite/client/ui/components/colorpicker/HuePanel.java, runelite-client/src/main/java/net/runelite/client/ui/components/colorpicker/PreviewPanel.java, runelite-client/src/main/java/net/runelite/client/ui/components/colorpicker/RuneliteColorPicker.java, runelite-client/src/main/java/net/runelite/client/util/ColorUtil.java
Closes #890
Closes #2503
Supersedes/closes #6414 
Alpha slider has been made to work and the color space uses a three-way HSB gradient.
Config colors can use the alpha slider by adding the `@Alpha` annotation.
=> Add custom RuneLite Color picker

runelite-client/src/main/java/net/runelite/client/config/ChatColorConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/timestamp/TimestampConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/timestamp/TimestampPlugin.java
This color is used ONLY in timestamp plugin but it was for some
reason included in core.
=> Move timestamp color config to timestamp plugin

runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPlugin.java
This toggle was here originally because NPC tagging did not required
shift, but now it does so to bring it with line of other shift-click
plugins, simply remove this option.
=> Remove "Tag" toggle from NPC indicators

runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordState.java
Instead of setting activity to in_game, in_menu just send again current
discord activity.
=> Do not reset current activity on discord party update

runelite-client/src/main/java/net/runelite/client/plugins/party/PartyStatsOverlay.java
Instead of checking for current value being > 0 to determine if we have
any stat data, instead check for max value.
=> Do not hide party bars when value is changed to 0

runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordState.java
When force-refreshing discord presence use updated party size values.
=> Fix Discord party size refresh

runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
This would throw except because Ints.constrainToRange would be between
0 and negative number in case overlay is bigger than screen.
=> Prevent negative values when overlay is bigger than screen

runelite-client/src/main/java/net/runelite/client/plugins/barrows/BarrowsOverlay.java
It is already drawn as white square later.
Closes #6918
=> Do not draw yellow dot for local player in barrows plugin

runelite-client/src/main/java/net/runelite/client/plugins/wintertodt/WintertodtPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/chatnotifications/ChatNotificationsPluginTest.java
These were probably just missed. They cause warnings in the console and
make it so the Wintertodt plugin doesn't start
Stack trace below:
```
2019-02-07 23:02:12 [main] WARN  n.r.client.plugins.PluginManager - Unable to start plugin WintertodtPlugin. {}
net.runelite.client.plugins.PluginInstantiationException: java.lang.IllegalArgumentException: Subscribed method public void net.runelite.client.plugins.wintertodt.WintertodtPlugin.onSetMessage(net.runelite.api.events.ChatMessage) should be named onChatMessage
at net.runelite.client.plugins.PluginManager.startPlugin(PluginManager.java:342)
at net.runelite.client.plugins.PluginManager.startCorePlugins(PluginManager.java:207)
at net.runelite.client.RuneLite.start(RuneLite.java:296)
at net.runelite.client.RuneLite.main(RuneLite.java:221) …
```
=> Migrate onSetMessage to onChatMessage

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_prayer.json
Ourg bones are wrongly positioned in the list of bones, fix this.
Signed-off-by: Will Thomas <github@willthoms.org.uk>
=> Reorder skill calculator bone order

runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldHopperPlugin.java
Fixes #6923
We can't submit tasks to shutdown Executors. These need to be recreated
on startup
=> Make sure WorldHopperPlugin's executor is active on startup

runelite-client/src/main/java/net/runelite/client/ui/ClientPluginToolbar.java
Push sidebar non-tab buttons with custom chrome disabled to bottom.
Preview:
=> Push sidebar non-tab buttons to bottom

runelite-api/src/main/java/net/runelite/api/VarPlayer.java, runelite-client/src/main/java/net/runelite/client/plugins/poison/PoisonConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/poison/PoisonInfobox.java, runelite-client/src/main/java/net/runelite/client/plugins/poison/PoisonOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/poison/PoisonPlugin.java
Adds an infobox and tooltip to show the next poison damage that the player will receive, along with an estimate as to when that will be. The time until the poison will naturally cure is shown on the tooltips.
Poison Box:
Venom Box:
Closes #1005 (Thanks @haakonrp)
=> Add Poison and Venom damage tooltip and infobox

runelite-client/src/main/java/net/runelite/client/plugins/cerberus/CerberusPlugin.java
When leaving the are with cerberus ghosts player will not receive
despawn events for them and so they will be stuck (they are just GCed
later instead). This solves the issue and goes in line with rest of
logic we have that relies on spawn/despawn events.
=> Clear Cerberus ghost on LOADING game state

runelite-client/src/main/java/net/runelite/client/Notifier.java
Make notifications only flash during the LOGGED_IN GameState
Fixes #7316
=> client: notification flash during login only

runelite-client/src/main/java/net/runelite/client/plugins/party/PartyPlugin.java
Currently, if the user joins a party whilst on the login screen, they don't get the instructional message on how to leave the party
=> Show party instructional message on login if user joined on login screen

runelite-api/src/main/java/net/runelite/api/Actor.java, runelite-api/src/main/java/net/runelite/api/Perspective.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerNameLocation.java
This allows players to select from a number of positions where they
would like highlighted player's names to be drawn relative to the
player's model.
Closes #878
=> Player indicator name positions

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/RangeStatBoost.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/RangeStatChange.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/StatBoost.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/StatChange.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/special/SpicyStew.java, runelite-client/src/main/java/net/runelite/client/plugins/statusbars/StatusBarsOverlay.java
Particularly since exposing StatBoosts and StatChanges through the item
stats service, it has become evident that storing stat change data as a
human-readable string is not especially useful for consumers of the
service as they must handle string processing, particularly for special
cases such as range stat boosts or spicy stews. This patch changes
StatChanges to expose their relative, theoretical, and absolute change
values as ints instead for ease of consumption, and adds methods to get
human-readable versions of these relative and theoretical values for
display purposes.
Fixes runelite/runelite#6594
=> item stats: Represent boost data as ints

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/AgilityShortcutLocation.java
The agility shortcut to the upper level of Taverly Dungeon (the one leading to blue dragons) has a level 70 agility requirement.
=> Add agility shortcut entry for Taverly Dungeon to World Map plugin

runelite-client/src/main/java/net/runelite/client/plugins/party/PartyPlugin.java
This makes more sense for party messages, mainly if we will be sending
party-related messages with source in future.
=> Use CLANCHAT_INFO for party messages

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/QuestStartLocation.java
Found the locations using debug outputs in developer mode, so they might be one or two grid points off. Not sure if there's a better way to do this?
=> Added two missing tooltips for Kourend quests

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
There was no shorthand for Challenge Mode Chambers of Xeric killcount so I decided to add some. Before this you had to type out the whole thing "!kc chambers of xeric:challenge" and now you can also use "chambers:cm", "olm:cm", "raids:cm", "cm", "cm cox" and "challenge mode".
=> Add chat command shorthand for challenge mode raids killcount

runelite-client/src/main/java/net/runelite/client/plugins/cooking/CookingOverlay.java
So it is consistent with rest of plugins, mainly session ones.
=> Use default PanelComponent size in Cooking plugin

http-service/src/main/java/net/runelite/http/service/cache/CacheService.java, http-service/src/main/java/net/runelite/http/service/item/ItemService.java
It is not very useful exception and cache entry is null-checked everywhere else. Replace the exception with simple warning in logs.
Exception:
```
at net.runelite.http.service.cache.CacheDAO.findIndexForCache(CacheDAO.java:63) ~[classes!/:na]
at net.runelite.http.service.cache.CacheService.findIndexForCache(CacheService.java:199) ~[classes!/:na]
at net.runelite.http.service.cache.CacheService.getItems(CacheService.java:236) ~[classes!/:na]
at net.runelite.http.service.item.ItemService.reloadItems(ItemService.java:491) ~[classes!/:na]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) …
```
=> Null-check cache when getting items in http service

runelite-client/src/main/java/net/runelite/client/util/LinkBrowser.java
Desktop#browse only supports GNOME environments on Linux. This PR adds functionality to use xdg-open, which should work for nearly every Linux environment.
=> Use xdg-open for link browsing on Linux

http-service/src/main/java/net/runelite/http/service/xp/XpTrackerService.java, http-service/src/main/java/net/runelite/http/service/xp/beans/PlayerEntity.java, http-service/src/main/resources/net/runelite/http/service/xp/schema.sql
Use player rank to set how often the same player is allowed to be looked
up. Replace the ConcurrentLinkedDeque with a synchronized ArrayDeque
which has a constant time size().
=> xptracker: limit how often the same players are looked up

runelite-api/src/main/java/net/runelite/api/DecorativeObject.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsOverlay.java, runelite-mixins/src/main/java/net/runelite/mixins/RSDecorativeObjectMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSDecorativeObject.java
There are a number of things wrong with the way we do it now
1) There are up to 2 models in each `DecorativeObject`, so we have to have a `getConvexHull` method for each of them. Both models must be from the same ObjectComposition, but have different rotations.
2) `renderable1` gets offset by `offset[XY]`
3) `DecorativeObject::rotation` is not the 0-2048 "JAU" rotation, but the 0-8 type rotation
4) The rotation is baked into the model, and does not need to be accounted for by `Model::getConvexHull`
=> Fix DecorativeObject ConvexHulls

http-service/src/main/java/net/runelite/http/service/feed/FeedController.java
Seeing same exceptions over and over again is not very useful, mainly
when their stacktraces are not useful too.
=> Log only exception message on feed lookup failures

runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBoxManager.java
Debug log infobox removal from infobox manager only if infobox was
really removed.
=> Log infobox removal only if infobox was removed

runelite-mixins/src/main/java/net/runelite/mixins/ProcessClientErrorMixin.java
This lets the client print the cs2 vm stack to our logs
=> mixins: Include game crash string in log

runelite-api/src/main/java/net/runelite/api/ScriptID.java, runelite-api/src/main/java/net/runelite/api/VarClientStr.java, runelite-api/src/main/java/net/runelite/api/vars/InputType.java, runelite-client/src/main/java/net/runelite/client/plugins/chathistory/ChatHistoryConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/chathistory/ChatHistoryPlugin.java
Pressing tab again while typing a private message will change the target recipient by cycling through the list of recipients
Closes #7885
=> Add PM Target Cycling to Chat History plugin

runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordState.java
1. It's common practice to put version info to tooltip
2. It reduces my time wasted providing support to people running outdated or custom versions in Discord
=> Add version information to Discord tooltip

runelite-client/src/main/java/net/runelite/client/discord/DiscordService.java, runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordState.java
Having big image with RuneLite logo and then small image with RuneLite
logo in it's corner do not looks very good, so update the small icon
only when it is showing something interesting.
=> Do not use default smallImageKey for Rich Presence

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_magic.json
Was using it a bunch and noticed the calculator contained the incorrect amount.
Before: 47 XP
After: 48 XP
[Here's the wiki link](https://oldschool.runescape.wiki/w/Falador_Teleport) in case you'd like to double-check.
=> Correct Falador teleport XP in Skill Calc

runelite-client/src/main/java/net/runelite/client/discord/DiscordService.java
=> Catch JVM incompatible library JNA error when initializing Discord

runelite-client/src/main/java/net/runelite/client/plugins/slayer/TargetWeaknessOverlay.java
In order to not draw the weakness overlay under NPC HP bars
and prayers move overlay 1 layer up to UNDER_WIDGETS.
=> Move slayer weakness overlay 1 layer up above

runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/KourendLibraryConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/KourendLibraryOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/KourendLibraryPlugin.java
Added a config in the Kourend Library setting to hide book you already have in your inventory.
Since you can't have any duplicate books in your inventory.
=> Kourend Library Plugin: Add config option to hide duplicate books

runelite-client/src/main/java/net/runelite/client/plugins/defaultworld/DefaultWorldPlugin.java
Wanted to set my home world but couldn't find the Default World plugin when I searched for home.
=> Add home tag to Default World plugin

http-service/src/main/java/net/runelite/http/service/account/AccountService.java
This will allow users to select what Google Account to use, since Chrome will just use the currently logged in account without a prompt.
The user will now see this upon logging in
=> Add account prompt to the OAuth URL

runelite-api/src/main/java/net/runelite/api/GraphicID.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
A splash doesn't make a hitsplat, but will still keep you logged in.
Useful for when splashing on yourself
=> Fix splashes not resetting idle countdown

runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java
This field can be null if the config service do not find absolutely
anything in config table for the user.
=> Null-check remote configuration in config manager

runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanChatConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanChatIndicator.java, runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanChatPlugin.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/Counter.java
Shows amount of clan members near you (default disabled). Can be useful for when trying to know how many clan members turned up to an event, so you don't have to manually count them.
=> Clanchat: Show amount of members near you

runelite-api/src/main/java/net/runelite/api/coords/WorldPoint.java
This fixes the bug introduced in #7788. Original (working) code used the plane of the worldPoint being translated rather than relying on `client.getPlane()`. Going back to that seems to fix instance tile checks when loading into multi-plane instances.
Fixes runelite/runelite#7985
Fixes runelite/runelite#8045
=> worldpoint: Fix plane value in toLocalInstance

runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerPlugin.java
This fixes the bug introduced in runelite/runelite#5890 where attempting
to mark a non-marked tile while having the "Remember color per tile"
config disabled would prevent new tiles from being marked. Instead, it
properly ensures that unmarking tiles with that config disabled will not
re-mark it with an updated color, causing a second unmark to be needed.
=> ground markers: Fix marking non-marked tiles

checkstyle.xml
https://checkstyle.org/dtds/configuration_1_3.dtd is a link that exists (see https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml for an example). The old puppycrawl links 404 (both HTTP and HTTPS).
=> Update CheckStyle XML link to one that exists

runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanChatPlugin.java
Currently the clanchat counter change #7707 didn't take into account that players could already be in scene thus giving wrong numbers. 
This change makes it count players already in scene when joining a clanchat, or removes the counter when leaving a clanchat
=> Clanchat: count players already in scene

runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanChatConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanChatPlugin.java
Updates the Clan Chat plugin to add rank icons to public & private messages. Each feature has a config toggle that is on by default.
=> Add CC icons to Public Chat & Private Messages

runelite-api/src/main/java/net/runelite/api/events/ClanMemberJoined.java, runelite-api/src/main/java/net/runelite/api/events/ClanMemberLeft.java, runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanChatPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanMemberActivity.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClanMemberManagerMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSNameableContainer.java
Ranks would be cached at the time of join/leave which was incorrect. Using the rank from ClanMember will always be correct and won't require the user to have spoken recently to cache their rank.
=> clanchat: retrieve rank from ClanMember rather than ClanManager

runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanChatPlugin.java
Clear counter on logging_in state instead of loading. Sometimes when you run into new regions (revenant caves pking for example) you get the loading state which clears the counter.
=> Clanchat: clear counter on login/connection lost instead of loading

http-service/src/main/java/net/runelite/http/service/feed/twitter/TwitterService.java
When using Twitter's new theme, https://twitter.com/statuses/[tweet_id] style links don't redirect to the tweet in question.
Urls before this change:
https://twitter.com/statuses/1102962117509087234
After this change:
https://twitter.com/OldSchoolRS/status/1102962117509087234
=> http-service: fix twitter feed links not working with newer theme

http-api/src/main/java/net/runelite/http/api/loottracker/LootTrackerClient.java
GET is default method for OkHttp request builder, no need to explicitely
define it.
=> Remove unnecessary .get() on OkHttp request

runelite-client/src/main/java/net/runelite/client/plugins/slayer/Task.java
`\runelite\runelite-client\src\main\java\net\runelite\client\plugins\bosstimer\Boss.java` contains `ItemID.ANCIENT_STAFF` as it's sprite as well 👍 
Closes: #8019
=> Changed Chaos Fanatic's slayer task info box sprite from pet to ancient staff to match the respawn timer

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
If we don't check the length of the message before we access it with substring(command.length() + 1) we will get a string index out of range error.
This fixes issue #8047 and #8057.
(Also as a note it's my first pr here so if I did something wrong please let me know thanks!)
Closes #8047
=> Check message length before use.

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatPlugin.java
When side panels are enabled, the inventory is loaded when the GE is closed rather than being unhidden. Now uses `GameTick` to reset when the GE has closed. 
Using `WidgetLoaded`, alongside `WidgetHiddenChanged` is also possible, but is a tick slower than checking in `GameTick`. 
This PR also fixes an issue where `resetGEInventory` was not always being called on the client thread.
=> item stats: fix detecting when GE has closed, fix threading issue

runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/Produce.java
Well not much to say except that before the pictures used for maple and yew tree were from the construction skill icons. These have been changed to pictures of the logs to stay consistent with the other trees.
Before:
After;
I don't have a picture for maple trees because I was not growing them at the time, teehee.
=> Changed  produce image of maple and yew trees to their respective logs

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatPlugin.java
When closed with esc, the container is hidden rather than unloaded.
Closes #8211
=> item stats: check if GE container is hidden when detecting GE close

runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsOverlay.java
This patch updates the boosts overlay to match the threshold color
comparison used in the plugin (for notifications) and in the indicator
infobox.
Ref/actually fixes: #6243
=> boosts plugin: Fix overlay below-threshold color

runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/ArdougneDiaryRequirement.java, runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/FaladorDiaryRequirement.java, runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/FremennikDiaryRequirement.java, runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/KandarinDiaryRequirement.java, runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/MorytaniaDiaryRequirement.java, runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/WesternDiaryRequirement.java
Fixes #8210 
**Ardougne Easy**  - "Go out fishing on the Fishing Trawler" - requires 15 fishing 
**Fremmy Easy** - "Enter the troll stronghold" - requires death plateau and started troll stronghold
**Kandarin Easy**  - kill 1 of each elemental in the workshop - requires starting elemental workshop
**Kandarin Hard** - Kill a shadow hound in the Shadow Dungeon - requires starting Desert Treasure and 53 thieving
**Falador Hard** - Kill the blue dragon under the Heroes' Guild - requires Heroes' Quest
**Morytania Easy** - Kill a werewolf in its human form using the Wolfbane Dagger - requires Priest in Peril
**Morytania Easy** - Mix a Guthix Balance potion while in Morytania - requires 22 herblore not 36
**Western Diary** - Teleport to Pest Control using the Minigame teleport - requires 40 …
=> Achievement Diary: Add Missing Requirements

runelite-api/src/main/java/net/runelite/api/coords/WorldArea.java, runelite-api/src/main/java/net/runelite/api/geometry/Geometry.java, runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java, runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/AggressionTimer.java, runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaNotWorkingOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaPlugin.java
Adds a timer and displays the area of which the player can move within without making NPCs aggressive again.
There's a config of which the user can edit to decide at which NPCs the plugin should be active at, and I suspect people might want a list of useful NPCs, so I've also put together one with some of the more commonly killed NPCs where this plugin would be useful at: https://pastebin.com/wYfVfu9S
Uses the same geometry methods as #6097 so if one PR gets merged, the other needs rebasing.
=> Add NPC unaggression timer

runelite-client/src/main/java/net/runelite/client/game/chatbox/ChatboxPanelManager.java
If RESET_CHATBOX_INPUT doesn't invoke runelite_callback resetChatboxInput because the script hash mismatches panels never get killed, so they a) break jagex inputs, and b) can be lost and not get unregistered, so they will record passwords on the login screen
=> ChatboxPanelManager: Be more resilient when scripts mismatch

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java
Two farming guild locations were listed, although only 1 exists
Per the [wiki](https://oldschool.runescape.wiki/w/Treasure_Trails/Guide/Hot_Cold#Kebos_Lowlands), the western location is correct.
Closes #7570
=> Remove incorrect farming guild hot-cold clue location

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
Because there was no object ID listed, it automatically set it to -1, making the WorldOverlayHint mark a dig location instead of marking the object (drawers)
Closes #8237 
EDIT: Also closes #6705
=> Clue Scroll: Fixe Varrock East Bank Cryptic Clue

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
Adds loot from brimstone chest to the loot tracker.
Closes #7749
=> Add brimstone chest support to loot tracker

runelite-api/src/main/java/net/runelite/api/events/MenuShouldLeftClick.java, runelite-client/src/main/java/net/runelite/client/plugins/bank/BankCalculation.java, runelite-client/src/main/java/net/runelite/client/plugins/bank/BankConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/bank/BankPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/bank/BankCalculationTest.java, runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
Closes #2867
When the options are enabled, the relevant Deposit options are set to open the right click menu, like the Bank Fillers currently do.
In Action:
This is in it's own plugin due to not really being a Menu Entry swap, and I'm tempted to merge the other bank plugins into it (Bank Value, Bank Tags), though I'm not sure if merging Bank Tags would be a good idea. Open to ideas on that front.
=> Add ability to disable Left Click to bank inventory, equipment, and looting bag options

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_farming.json
Resolves issue #8309, super basic fix. I went through and verified all other levels too in farming just as a sanity check, and they all seem good.
=> Fix Skillcalc plugin for Dragon Fruit level

runelite-api/src/main/java/net/runelite/api/Perspective.java, runelite-mixins/src/main/java/net/runelite/mixins/RSActorMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSDecorativeObjectMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSGameObjectMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSModelMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSNPCMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSPlayerMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSModel.java
the Models returned by getModel are already contoured if required; we do not need to do it again.
Closes #7872
=> mixins: Fix convex hulls being incorrectly contoured

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
Fixes crystal chests counting as brimstone chests in the loot tracker by checking the current region the player is in.
Closes #8356
=> Fix crystal chest in loot tracker

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/config/ValueCalculationMode.java
Fixes #7737.
Right now the color highlighting(low/medium/high/insane) uses whatever's highest of Grand Exchange and High Alchemy to determine an item's color. Not all players care about both, however.
This PR lets users select a specific mode for the color highlighting. Default is BOTH, which is the current functionality.
Example of usage: https://imgur.com/a/PRISDUB
=> Added ability to change which coin value GroundItems color highlighting uses

runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerDoseOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerPlugin.java
Currently, the Prayer Dose indicator will show when you can drink a prayer potion, even if you're using Super Restores or Sanfews which both restore more prayer. This leads to lost prayer points.
=> prayer: fix dose indicator not accounting for super restores or sanfews

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
Specifically this fixes the Kourend Library plugin panel button. Plugins that dynamically add/remove buttons to the plugin panel based on game state would cause the layout to break. Behavior isn't observed when enabling/disabling plugins entirely since it looks like the config invalidates all plugin buttons when it saves.
Steps to reproduce:
1. Turn on Kourend Library plugin, and ensure Hide Button config option selected.
2. Enter Kourend Library region
3. Button appears at top-left of plugin panel, rather than correctly listed with rest of plugins.
=> Fix plugin list layout when a plugin dynamically adds / removes buttons.

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
Closes #7494
@Adam- Please review as you recently committed the centralized spade check in this snapshot
This was overlooked because the issue is missing a "clues" label
=> Cluescrolls Plugin: Adds Spade Check to Cryptic Clues

runelite-client/src/main/java/net/runelite/client/plugins/puzzlesolver/solver/PuzzleSolver.java
If the executor waits a while until it starts executing the puzzle solver, the stopwatch will have a null value when hasExceededWaitDuration is called the next frame, causing a NullPointerException to be thrown. This has the effect that the puzzle solver never finishes.
Extract from [whatnamenow's client log](https://gist.github.com/whatnamenow/2738e85bf99ab70a8fc934c2ec4495de): 
```
2019-04-04 18:03:08 [Thread-7] WARN  net.runelite.client.callback.Hooks - Error during overlay rendering
at net.runelite.client.plugins.puzzlesolver.solver.PuzzleSolver.hasExceededWaitDuration(PuzzleSolver.java:81)
at net.runelite.client.plugins.puzzlesolver.PuzzleSolverOverlay.render(PuzzleSolverOverlay.java:344)
at …
```
=> client: fix puzzle solver not completing if executor waits before starting solver

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java, runelite-client/src/main/java/net/runelite/client/ui/components/ProgressBar.java
Closes #7479
XP bar progress is stored as an integer of percentage, while the intermediate markers are stored as a double from 0 to 1. This means that even if the progress is higher than the intermediate level (but not by more than 1%), the intermediate line will render to the right.
This PR makes both as a percentage integer, which means both are rounded in the same fashion, preventing any discrepancy in rendering.
(This is a duplicate PR because I messed up my branches. The old one has been closed.)
=> Use consistent rounding for XP bar markers

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_runecraft.json
Closes #6953 
Based on the conversation in the issue, this appears to be the easiest way to consider the xp from dark essence blocks when crafting blood and/or soul runes.
=> Fix Inaccurate Blood & Soul Rune XP

http-api/src/main/java/net/runelite/http/api/hiscore/HiscoreResult.java, http-api/src/main/java/net/runelite/http/api/hiscore/HiscoreResultBuilder.java, http-api/src/main/java/net/runelite/http/api/hiscore/HiscoreSkill.java, http-service/src/test/java/net/runelite/http/service/hiscore/HiscoreServiceTest.java, runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java
Fixes #8469
~Fixed the hiscore lookup, not sure if I should use this branch to fix the HiScore plugin itself to (Like add the clue icon)~
According to Adam I can put that fix/feature in this PR too.
Also fixes:
- Hiscore Plugin
- Adds `!clues beginner` to Chat command Plugin
Also: Sorry for the messy PR, I wanted to do this but didn't have the tools to do it correctly at the moment.
=> Add Beginner Clue to Hiscore lookup, Hiscore plugin and Chat commands plugin

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
This also fixes an issue where the Loot Tracker completely breaks after the user completes a Beginner clue and views the details of a specific monster/event
=> loottracker: add support for beginner clues

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java
Adds the following new location to the hot & cold clue scroll plugin.
=> Add hot-cold clue location: wilderness lvl 27

runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaPlugin.java
Upon turning on the `NPC Aggression Timer` plugin there should be an overlay informing the user that they need to teleport away or enter a dungeon to make it work. This works correctly upon login, but not if you previously had the plugin turned off and then switch it on while in-game.
This should solve some of the confusion people sometimes have as to why this plugin isn't working for them.
<details><summary>Current: turning on the plugin doesn't show the warning</summary>
</details>
<details><summary>Fixed: turning on the plugin shows the warning</summary>
</details>
=> Fix Npc Aggression Timer instructions not showing up when plugin is first turned on

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPanel.java
Fixes #8401
Changes the rigid area separating the two elements in the below photo to be a compound border so it doesn't take up space when these containers are empty/not visible.
Gif showing fixed:
=> Fix empty Loot Tracker text alignment

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java
The duplicate entry causes the client to crash when trying to build the ImmutableMap.
=> Remove duplicate coordinate clue

runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
=> stop overlay methods from triggering off of hidden items

runelite-client/src/main/java/net/runelite/client/plugins/skybox/Skybox.java
Skybox was incorrectly calculating the brightness, causing high blue/green values to overflow. This was only noticeable by changing the default skybox color to a less vibrant blue. 
Before
After
=> skybox: calculate brightness increase in HSB format

runelite-client/src/main/java/net/runelite/client/plugins/ammo/AmmoCounter.java, runelite-client/src/main/java/net/runelite/client/plugins/ammo/AmmoPlugin.java
Closes #864
Shows the current ammo the player has equipped. If the player is using a stackable weapon (chinchompas, darts, etc) those will show, otherwise it'll show the ammo slot (unless the item is a blessing or empty)
If the value is over 1,000,000 the number will have an M. If it's over 10,000 the number will have a K. Let me know if I should add colours
I tried to find an existing plugin this would fit in, but I couldn't find a suitable one. If you can think of one, please let me know and I'll move it.
=> Add Ammo plugin

runelite-client/src/main/java/net/runelite/client/plugins/agility/LapCounterOverlay.java
Removed slang "till'" from the lap counter overlay string and added colons to the end for cleanliness and aesthetic.
=> Update lap counter overlay strings for clarity.

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java
Closes #8573 
Also edits the Level 27 Wilderness location's description (from #8481) to match the [Wiki](https://oldschool.runescape.wiki/w/Treasure_Trails/Guide/Hot_Cold#Wilderness).
=> Cluescrolls: Add Level 32 Wilderness Hot Cold Clue Location

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/EmoteClue.java
`Dig in the centre of a great city of 5 districts.`
became
`Dig in the centre of a great kingdom of 5 cities.`
`Cheer at Iffie Nitter. Equip a chef's hat and a red cape.`
should have been 
`Cheer at Iffie Nitter. Equip a chef hat and a red cape.`
=> clues: Fix Easy Cryptic & Beginner Emote

runelite-client/src/main/java/net/runelite/client/plugins/chathistory/ChatHistoryPlugin.java
Fixes the max size for the friends deque to ensure it doesn't go over 5.
Also updated to clear the deque when pm history is cleared
=> Fix private message cycling deque

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
Figured Herbiboar deserved a spot in the loot tracker. The code already there to process chest loot fit Herbiboar pretty well so I moved some of it around as to be more general purpose.
Closes #6136
=> Add Herbiboar support to the Loottracker

runelite-client/src/main/java/net/runelite/client/plugins/customcursor/CustomCursorPlugin.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
To not expose swing components directly just to set cursor on them,
create convenient proxy methods for updating and resetting cursor. Also
document that it is working properly only on Windows.
=> Use proxy methods for setting cursor via ClientUI

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_fletching.json
Fix bronze dart in skillcalculator to be the correct level requirement
=> fix bronze dart requirement in skillcalculator

runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java, runelite-client/src/main/java/net/runelite/client/plugins/itemidentification/ItemIdentification.java, runelite-client/src/main/java/net/runelite/client/plugins/itemidentification/ItemIdentificationConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/itemidentification/ItemIdentificationMode.java, runelite-client/src/main/java/net/runelite/client/plugins/itemidentification/ItemIdentificationOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/itemidentification/ItemIdentificationPlugin.java
Close #7201
A plugin that shows identifying text over items with problematic sprites, such as herb seeds and tree saplings.
Works on Herbs, Saplings, Herb Seeds, Poison Ivy Seeds, and Whiteberry Seeds
Has options for Short and Medium length names. Full length names sadly take up too much space and overflow into other items.
Works in the following Inventories:
Inventory
Seed Box
Looting Bag
Deposit Box
Item Reclaim chest/NPC
Guide Price screen
Items Kept on Death screen
=> client: add item identification plugin

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/FaloTheBardClue.java
Closes #2730 
I only just realised these weren't supported yet when I got on my master clue so I added them in since I had one to test on.
=> clue scroll plugin: add support for Falo the Bard clues

runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaPlugin.java
Fixes `java.lang.IllegalArgumentException: negative period!` when logging in if the monsters in the area you are aren't aggro'd to you anymore.
=> Aggro area: only add a timer if the time left isn't negative

runelite-client/src/main/java/net/runelite/client/chat/ChatMessageManager.java
If we send messages on tutorial island it looks like this and can get in the way of the tutorial.
=> chat message manager: don't send messages if player is on tutorial island

http-api/pom.xml
Security update for [CVE-2018-19360](https://nvd.nist.gov/vuln/detail/CVE-2018-19360), [CVE-2018-19361](https://nvd.nist.gov/vuln/detail/CVE-2018-19361) and [CVE-2018-19362](https://nvd.nist.gov/vuln/detail/CVE-2018-19362)
[2.2.6](https://github.com/git-commit-id/maven-git-commit-id-plugin/releases/tag/v2.2.6) upgrades the jackson-databind dependency which resolves a potential security issue.
Jackson-databind security issue can be found [here](https://github.com/FasterXML/jackson-databind/issues/2186).
=> Upgrade git commit id plugin from 2.2.5 to 2.2.6

runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/WidgetItemOverlay.java
allow overlays (e.g. item charges) to be displayed whilst in the seed vault interface
resolves #8359
=> Add seed vault inventory to widget item overlays

runelite-client/src/main/java/net/runelite/client/plugins/barbarianassault/BarbarianAssaultPlugin.java
Makes equipment querying consistent across the client by changing the Barbarian Assault plugin to use the equipment ItemContainer instead of the local player's PlayerComposition.
=> ba: use equipment ItemContainer instead of PlayerComposition

runelite-client/src/main/java/net/runelite/client/plugins/blastfurnace/BlastFurnacePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/blastfurnace/ForemanTimer.java
For players that are utilizing blast furnace and require to pay the
foreman fee every 10 minutes, this will assist in tracking the time
remaining before the next fee payment is required. This defaults to
disabled, but is bundled with the Blast Furnace plugin config.
Resolves #8769
=> Adds foreman fee counter for Blast Furnace under level 60 smithing

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java, runelite-client/src/main/java/net/runelite/client/util/StackFormatter.java, runelite-client/src/test/java/net/runelite/client/util/StackFormatterTest.java
Some users believe that the XP Tracker doesn't display experience values with enough precision when above 1m. For example, if you do skilling methods that give you between 1 and 1.1m xp/hr, it will just say 1m/hr when they want it to say e.g. "1.035m/hr".
This pull request changes the XP Tracker to display values over 1 million with higher precision.
=> xp tracker: display >1m exp with higher precision

runelite-client/src/main/java/net/runelite/client/plugins/smelting/SmeltingConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/smelting/SmeltingOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/smelting/SmeltingPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/smelting/SmeltingSession.java, runelite-client/src/test/java/net/runelite/client/plugins/smelting/SmeltingPluginTest.java
Closes #8418 
This new plugin keeps track of the amount of bars/cannonballs smelted for the current session. 
With the plugin, it will look something like this:
If no cannon balls were smelted during the session, it will only display bars smelted and vice versa. Likewise, if the player smelted both cannon balls and bars, then it will display both.
=> Add plugin displaying smelting info bar.

runelite-client/src/main/java/net/runelite/client/plugins/barrows/BarrowsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/barrows/BarrowsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/barrows/BarrowsPrayerDrainTimer.java
Fixes https://github.com/runelite/runelite/issues/2134
This adds a timer that has a duration of 18.2 seconds and only appears inside Barrows crypts or tunnels. I've tested all situations of being in a crypt and then going into a tunnel, being in a crypt/tunnel and logging out, and dying in Barrows. It's my first PR so please point out any mistakes I made! Really hoping this can be in the next release. I've found it quite useful :)
=> Add barrows prayer drain timer

runelite-api/src/main/java/net/runelite/api/Constants.java, runelite-client/src/main/java/net/runelite/client/callback/Hooks.java, runelite-client/src/main/java/net/runelite/client/plugins/antidrag/AntiDragConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/barbarianassault/GameTimer.java, runelite-client/src/main/java/net/runelite/client/plugins/barbarianassault/Round.java, runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcSceneOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/poh/PohPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerDoseOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/regenmeter/RegenMeterConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/regenmeter/RegenMeterPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/runenergy/RunEnergyPlugin.java
Adds a configuration option for notifying the player before their next HP regen occurs, and refactors existing code to utilise `Constants.GAME_TICK_LENGTH` where approperiate.
The following notification is sent:
Should be especially useful for NMZ. Its accuracy is limited to that of the Regeneration Meter plugin itself.
Closes #2704.
**Note:** the config accepts the amount of milliseconds before the regen to send the notification, but this is instead converted to the earliest corresponding 0.6s tick interval in the code. Maybe it would be a better idea to accept something like seconds instead?
=> regenmeter: notif before next hp regen & refactor existing code to use Constants.GAME_TICK_LENGTH

runelite-client/src/main/java/net/runelite/client/plugins/blastfurnace/BlastFurnaceOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/blastmine/BlastMineOreCountOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/cerberus/CerberusOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/inventoryviewer/InventoryViewerOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/teamcapes/TeamCapesOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBoxOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerPlugin.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/ComponentOrientation.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/PanelComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/ProgressBarComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/SplitComponent.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBoxOverlay.java
This pull request adds the option to add your xp trackers to your game canvas. PR comes with a new layout renderable component that is the split component. This component makes it easier to layout two components either next to eachother or above eachother.
=> Xp tracker: Show on canvas

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBoxOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerConfig.java
Add configurable option for on screen XP display mode, what now
includes:
- Actions done
- Actions left
- Xp gained
- Xp left
=> Add options for actions left and done for on screen XP

runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/WesternDiaryRequirement.java
The requirement for pickpocketing an elf is to have started Mourning's
End Part I for access to Lletya, not to have completed Mourning's End
Part II.
Fixes runelite/runelite#8806
=> western diary: Fix elf pickpocket quest requirement

runelite-client/src/main/java/net/runelite/client/plugins/combatlevel/CombatLevelOverlay.java, runelite-client/src/test/java/net/runelite/client/plugins/combatlevel/CombatLevelPluginTest.java
After reading the issues (#7411) and pull requests (#7526) I found out that the combat level plugin has had a lot of problems with prayer level calculation. I also found this bug on my own in which needed prayer levels for the next combat level was 0 instead of 2 in some corner cases.
This PR should fix the issue by (1) changing the usage of Math.floor to Math.ceil and (2) subtracting 1 from the needed levels if the current prayer level is an odd number.
**For example**: Let prayer level `p` be an odd number. The current combat level is exactly same for `p` and `p - 1`. Therefore given `n` is the number of needed prayer levels for a combat level with prayer `p - 1` then `n - 1` is the needed prayer levels for a combat level with prayer `p`.
The usage of Math.floor was incorrect in every …
=> Combat level plugin: Yet another prayer level calculation fix

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CipherClue.java
fixes #8828 
fixed a typo in the 'Arnold Lydspor' Cipher Clue
=> clue scroll plugin: fix typo

runelite-client/src/main/java/net/runelite/client/Notifier.java, runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java
This adds a Runelite config option for logging notifications. My use case for this is handling the notifications outside of Runelite. I want to be able to run a NodeJS script that watches for certain notifications and performs actions based on them. Ie on log file change, if the notification i was looking for was added, perform XYZ.  Currently, at least on OSX, its very tricky finding where notifications are stored in the filesystem. This solves that problem.
=> log notifications

runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterType.java, runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/fps/FpsLimitMode.java, runelite-client/src/main/java/net/runelite/client/plugins/itemidentification/ItemIdentificationMode.java, runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/RenderStyle.java, runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerFlickLocation.java, runelite-client/src/main/java/net/runelite/client/plugins/runepouch/config/RunePouchOverlayMode.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/SubscriptionFilterMode.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerConfig.java, runelite-client/src/main/java/net/runelite/client/ui/components/ComboBoxListRenderer.java, runelite-client/src/main/java/net/runelite/client/util/Text.java
Makes it so enum options that don't override toString already don't shout at you anymore.
For example, CONFIG becomes Config and CONFIG_OPTION becomes Config Option.
You can still override toString on the enums if you want the config option to display apostrophes for example.
**Before:**
**After:**
=> Format config enums as "Config Option" by default

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBoxOverlay.java
https://github.com/runelite/runelite/pull/8816/files#diff-33d61506b07f292b5a93fe379bc9a203 broke it:
=> xp tracker: fix on-screen information type label

http-api/src/main/java/net/runelite/http/api/RuneLiteAPI.java, runelite-client/src/main/java/net/runelite/client/SessionClient.java
- Add support fo specifying runelite.session.url java prop to be used
instead of RuneLite session base
- Add support fo specifying runelite.http-service.url java prop to be used
instead of RuneLite api base url
- Add support fo specifying runelite.ws.url java prop to be used
instead of RuneLite websocket url
- Add support for specifying runelite.static.url java prop to be used
instead of RuneLite s.r.n url
=> Support specifying API endpoins via java props

runelite-client/src/main/java/net/runelite/client/chat/ChatCommandManager.java
This allows ChatCommandManager to handle also priv messages from pmods.
=> Add MODPRIVATECHAT to chat command manager

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBoxOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerConfig.java
Add option to switch between xp/hour and actions/hour for bottom line of
XP tracker.
=> Add configurable bottom line contents for XP tracker

runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/BeginnerMapClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/MapClue.java
Implements part of #8504
Despite the ID of all beginner clues being the same, they use unique widgetIDs. All clue locations have been checked, and they match up with their respective existing clues (4 easies and a medium). Each clue also has a description.
=> clues: add support for beginner maps

runelite-api/src/main/java/net/runelite/api/WallObject.java, runelite-mixins/src/main/java/net/runelite/mixins/RSDecorativeObjectMixin.java, runelite-mixins/src/main/java/net/runelite/mixins/RSWallObjectMixin.java
Closes #8825
Orientation for WallObject and DecorativeObject is not used for rendering, as their rotation is baked into their model. As such it not in the normal jagex angle format, and should not be used for projection.
=> correct misunderstandings related to wall orientation

runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/HitpointsDisplayStyle.java, runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoOverlay.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/ProgressBarComponent.java
A simple and maybe niche feature -- but I've sometimes found it useful to see both the opponent's HP and HP percentage (as a number):
Currently, you can only see either the approx. HP value (if max HP is known) **_or_** the raw percentage. 
With this proposed _Both_ option, the percentage from the approx. health over max health ratio is shown too.
This PR slightly changes the `ProgressBarComponent` to allow both its current value and percentage to be shown if wanted.
There should be enough room to display up to 9999 HP with the _Both_ setting without the label escaping the bounds of the panel by default, I think.
=> opponentinfo: Option to show both HP value and percentage

runelite-client/src/main/java/net/runelite/client/plugins/cooking/CookingPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/cooking/CookingPluginTest.java
Previously, the wine fermentation timer would enter into a negative range if the user cooked an inventory full of wine and then tried to cook another inventory.
This change resets the fermentation timer each time the player is performing the wine cooking animation, giving a more accurate measure of the remaining time to fermentation.
=> Fix wine fermentation timer to begin at appropriate time

runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanChatConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanChatPlugin.java, runelite-client/src/main/scripts/CommandScript.rs2asm
This allows typing messages with the clanchat tab focused without having
to prepend them with '/'.
Closes #4697
Closes #8264
=> clanchat plugin: add clan tab chat option

runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/config/PluginListItem.java
This adds a hover color effect and a popup menu linking to the plugin's
wiki page to each plugin name label both in the plugin panel and
configuration panels. In the plugin panel, for plugins which have
configurable settings, it also adds a "Configure" menu item to the
added popup menu.
Fixes runelite/runelite#1518
=> plugins panel: Add wiki link to name label

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java
The recent Hosidius rework update caused a regression. 
I based the description off of the [wiki](https://oldschool.runescape.wiki/w/Treasure_Trails/Guide/Coordinates)
Closes #8932
=> Update Hosidius Coordinate Clue Hint

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
The Hosidius Rework moved this clue slightly north west, and into the kitchens
Reported by `Prxgmatic` on the Discord
=> clues: update Easy Cryptic in Hosidius

runelite-client/src/main/java/net/runelite/client/plugins/keyremapping/KeyRemappingConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/keyremapping/KeyRemappingListener.java, runelite-client/src/main/java/net/runelite/client/plugins/keyremapping/KeyRemappingPlugin.java
This is a revised edition of the keyboard remapping that adds functionality for the use of Fn keys through their numerical counterparts (1~10). This consolidates WASD and the FN keys to one plugin with separated boolean configs, but keeping the wasd customization.
=> Rename WASDCamera to add Fn key remapped functionality

cache/src/main/java/net/runelite/cache/fs/flat/FlatStorage.java, runelite-client/src/main/java/net/runelite/client/plugins/runepouch/Runes.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/components/TooltipComponent.java
Remove all instances of redundant .length() calls in the String substring calls.
Both the following samples produce the same output:
```
str2 = str1.substring(beginIndex, str1.length()); 
str2 = str1.substring(beginIndex);
```
This minor enhancement removes unnecessary String length() calls.
[substring(int beginIndex, int endIndex) Javadoc](https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#substring(int,%20int))
[substring(int beginIndex) Javadoc](https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#substring(int))
=> Remove redundant subString endindex .length() calls

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/GameState.java, runelite-client/src/main/java/net/runelite/client/plugins/loginscreen/LoginScreenPlugin.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
- Add new LOGIN_SCREEN_AUTHENTICATOR game state
- Export otp and loginIndex from rs api
- Add support for pasting to authenticator pin (otp) field
Depends on !67
=> Add support for pasting authenticator code on login screen

cache-updater/src/main/java/net/runelite/cache/updater/CacheUploader.java, http-service/src/main/java/net/runelite/http/service/cache/CacheService.java
Replace all instances of redundant StringBuilder append String.subString with append CharSequence 
Both the following samples produce the same output:
```
sb.append(str.substring(startIndex, endIndex));
sb.append(str, startIndex, endIndex);
```
This minor enhancement removes an intermediate String construction during append
[append(CharSequence s, int start, int end) Javadoc](https://docs.oracle.com/javase/7/docs/api/java/lang/StringBuilder.html#append(java.lang.CharSequence,%20int,%20int))
[Relevant Stack Overflow discussion](https://stackoverflow.com/questions/52559564/call-to-substring-is-redundant)
=> Replace redundant StringBuilder append String.subString with append CharSequence

runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/mining/Rock.java, runelite-client/src/main/java/net/runelite/client/plugins/mining/RockRespawn.java
It looked weird having the timers appear at floor level while the mining icons in MLM appear at height offset of 150. So I added support for an offset and used it to shift the overlay for veins in MLM to match the MLM plugin.
Did amethyst too because it looks nicer this way IMO.
MLM before:
MLM after:
Amethyst after:
=> mining plugin: draw overlay at correct height for mlm and amethyst

runelite-client/src/main/java/net/runelite/client/plugins/mining/Rock.java
Fixes issue from this comment: https://github.com/runelite/runelite/issues/9042#issuecomment-499691513
Wiki says 30 seconds, but on testing it out personally I found the respawn time to be 29.4 seconds.
All the timers should be multiple of 0.6 seconds to match game ticks so I also corrected those and overlays now match up perfectly with the ores respawning.
Also came across this copper rock which wasn't yet in the plugin while testing the copper rock timer.
=> mining plugin: correct coal timer, missing copper rock and align other timers to game ticks

runelite-client/src/main/java/net/runelite/client/plugins/mining/Rock.java
The plugin is also missing a Copper ID, but that's being added by #9076
=> mining: add missing Silver ID

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Example - the [fishing shop in Witchhaven](https://oldschool.runescape.wiki/w/Lovecraft%27s_Tackle) is `shop`, not `trade`. Don't know if there are others.
=> MenuEntrySwapper: include "shop" for trade option

runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/mining/Rock.java
Veins in MLM are on a variable timer. So far the longest and shortest respawns that I've witnessed have been +/- 15 seconds from the 108 seconds set in the plugin. This PR addresses one half of that by removing the progress pie once the vein has respawned.
Example of what I'm talking about, which this PR fixes:
=> mining plugin: remove progress pie from mlm veins that respawned early

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/FaloTheBardClue.java
The osrs wiki had the wrong text (hope -> hopes). Here is an image of the clue in game after correcting the text in the plugin:
Found another one, wiki text was missing a comma. Updated:
=> clues: correct falo the bard typos

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
=> Fix typo in master clue step Kill the spiritual, magic and godly whilst representing their own god.

runelite-client/src/main/java/net/runelite/client/plugins/itemprices/ItemPricesOverlay.java
Fixes Item Prices plugin to correctly show High Alchemy profit when show High Alchemy values is disabled.
Fixes #9011
=> Fix Item prices high alch profit

runelite-client/src/main/java/net/runelite/client/plugins/mining/Rock.java
Fixed ash pile respawn timer not appearing (mining plugin).
Closes #9126
=> Fixed ash pile respawn timer not appearing (mining plugin)

runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
In the last game update, Jagex changed the teleblock message for some unknown reason, as seen on their blogpost
=> timers: fix teleblock message

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/EmoteClue.java
Some clues may have item requirements, but no STASH unit, which would
cause NPEs during rendering. This commit also marks stashUnit as
nullable so this issue can hopefully be avoided in the future.
=> EmoteClue: Add null checks for stashUnit

runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSpot.java
1 Fly Fishing spot (8524), and 3 Harpoon/Big net spots to the west of the farming guild (8525, 8526, 8527)
Reported by `Prxgmatic` on Discord
=> fishing: add missing spots near farming guild

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/events/AreaSoundEffectPlayed.java, runelite-api/src/main/java/net/runelite/api/events/SoundEffectPlayed.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/devtools/SoundEffectOverlay.java, runelite-mixins/src/main/java/net/runelite/mixins/SoundEffectMixin.java
Adds ```SoundEffectPlayed``` and ```AreaSoundEffectPlayed``` events.
Adds sound effects and area sound effects to devtools and a ```::sound [id]``` command.
White = Sound effect
Yellow = Area sound effect
Grey = Area sound effect where the local player is too far away to hear it
Depends on #6085
=> Add sound effect events and add sound effects to devtools

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/SoundEffectVolume.java, runelite-client/src/main/java/net/runelite/client/plugins/metronome/MetronomePlugin.java, runelite-mixins/src/main/java/net/runelite/mixins/SoundEffectMixin.java, runescape-api/src/main/java/net/runelite/rs/api/RSAudioTaskNode.java, runescape-api/src/main/java/net/runelite/rs/api/RSAudioTaskNodeQueue.java, runescape-api/src/main/java/net/runelite/rs/api/RSClient.java, runescape-api/src/main/java/net/runelite/rs/api/RSRawAudioNode.java, runescape-api/src/main/java/net/runelite/rs/api/RSResampler.java, runescape-api/src/main/java/net/runelite/rs/api/RSTaskDataNode.java
Closes #530 
Depends on !47
Manually queues sound effects, bypassing the volume check the vanilla client normally does. 
Currently uses a medium high volume (2nd to last pip on the slider) but it may be more desirable to have this configurable or a different volume, not sure.
=> metronome plugin: allow metronome to play sound effects while volume is muted

runelite-client/src/main/java/net/runelite/client/plugins/cooking/CookingPlugin.java
The burn message for stews is
> "You accidentally spoil the stew."
Closes #9196.
=> Burnt stews now count towards burn counter in Cooking plugin

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/RareTreeLocation.java
Also removes the rogue icon near Tithe farm but too much work to screenshot.
=> Fix WC icons around Hosidius area

runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsButton.java
closes #4458
replaces #5186 (approach of shortening the button names was not received well)
Before: 
After:
=> Add tooltips to devtool buttons

cache/src/test/java/net/runelite/cache/AreaDumper.java, cache/src/test/java/net/runelite/cache/EnumDumperTest.java, cache/src/test/java/net/runelite/cache/FrameDumper.java, cache/src/test/java/net/runelite/cache/FramemapDumper.java, cache/src/test/java/net/runelite/cache/InventoryDumper.java, cache/src/test/java/net/runelite/cache/KitDumperTest.java, cache/src/test/java/net/runelite/cache/OverlayDumper.java, cache/src/test/java/net/runelite/cache/SequenceDumper.java, cache/src/test/java/net/runelite/cache/SoundEffectsDumperTest.java, cache/src/test/java/net/runelite/cache/StructManagerTest.java, cache/src/test/java/net/runelite/cache/TextureDumper.java, cache/src/test/java/net/runelite/cache/UnderlayDumper.java, cache/src/test/java/net/runelite/cache/VarbitDumper.java, cache/src/test/java/net/runelite/cache/WorldMapDumperTest.java
The Guava [Files.write(CharSequence from, File to, Charset charset)](https://guava.dev/releases/28.0-jre/api/docs/com/google/common/io/Files.html#write-java.lang.CharSequence-java.io.File-java.nio.charset.Charset-) is deprecated and is [scheduled to be removed in October 2019. ](https://github.com/google/guava/commit/554ca092bc57f44c5a69ce44078df5bb0793b232#diff-f2d9908269a353910c986657b03f048c)
Currently, the deprecated write function simply calls the suggested replacement [asCharSink(to, charset)](https://guava.dev/releases/28.0-jre/api/docs/com/google/common/io/Files.html#asCharSink-java.io.File-java.nio.charset.Charset-com.google.common.io.FileWriteMode...-).write(from) meaning this PR does not change any functionality, just removes the deprecated middle man.
=> Replace use of deprecated Guava Files write method

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdSolver.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdTemperature.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdTemperatureChange.java, runelite-client/src/test/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/BeginnerHotColdLocationTest.java, runelite-client/src/test/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdSolverTest.java, runelite-client/src/test/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdTemperatureChangeTest.java, runelite-client/src/test/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdTemperatureTest.java, runelite-client/src/test/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/MasterHotColdLocationTest.java
This PR adds a generic hot-cold solver class, as well as abstracts the concepts of temperature and change-of-temperature into interfaces for general use. It uses this class to implement master-level hot-cold clues, and to add an implementation for beginner-level hot-cold clues.
This addresses the hot-cold portion of #8504
=> Implement beginner hot-cold clue solutions 

runelite-client/src/main/java/net/runelite/client/plugins/screenmarkers/ui/ScreenMarkerPanel.java
- On screen marker renaming, ENTER to save, ESC to cancel
- On screen marker title hover, preview that screen marker ingame
(This last one is useful when you have a bunch of hidden markers and you want to look for a specific one, faster than toggling one at a time)
=> Screen markers UX improvements

runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPlugin.java
By killing a monster which has a known respawn timer and leaving its
respawn area (by walking away or teleporting) and returning to it some
time after it has respawned, the plugin can erroneously overwrite its
respawn time with a much longer one. This commit fixes that issue by
assuming that the lower of the observed respawn time and the previously
recorded respawn time is the correct one.
=> npc indicators: Fix long respawn timer bug

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdTemperature.java, runelite-client/src/test/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdTemperatureTest.java
Bugfixes/improvements for the hot-cold port.
1. Hot-cold temperature gets the wrong temperature of the string "The device is warm, but colder than last time."
2. When a locator orb is activated at a location where it is visibly shaking, it resets the possible locations list instead of displaying the location.
3. When reading a new hot-cold clue, if a location had been marked from a prior hot-cold clue in the session, the final location is not cleared.
cc: @Hydrox6, as he helped point out some of these bugs. This branch should address the issues you found
=> Hot cold fixes

cache/src/test/java/net/runelite/cache/FrameDumper.java
=> cache/FrameDumperTest: Don't get the wrong framemaps for a frame

runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldSwitcherPanel.java
Put worlds with unknown ping at the bottom of the list and fix secondary sorting when sorting by activity, e.g. when sorting by "Ping" and then by "Activity".
Here's a couple of images comparing the results of sorting by "Ping" and then by "Activity":
Before | After
:-------------------------:|:-------------------------:
Closes https://github.com/runelite/runelite/issues/8176
=> Improve world hopper sorting

runelite-client/src/main/java/net/runelite/client/ui/ContainableFrame.java
Java's GraphicsConfiguration::getBounds() is completely nonfunctional for me, returning nearly random values, which causes the our window to move itself to random places, often outside of my displays' bounds
=> runelite-client: Don't try to contain to screen when contain is off

runelite-client/src/main/java/net/runelite/client/plugins/mta/telekinetic/TelekineticRoom.java
The bug happened when the Telekinetic projectile existed on the same game tick as the guardian moving.
Closes #3946
=> mta: fix Telekinetic solver not moving

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
This prevents loot entries for Chamber of Xeric and Theatre of Blood
chests from being duplicated when viewed multiple times.
Fixes runelite/runelite#4754
Closes #9255
=> loottracker: Fix duplicate cox and tob chest loots

runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
fixes #4374
Simply added more precise seconds to the file name.
=> Stop screenshot plugin from overwriting pictures

runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/screenmarkers/ScreenMarkerPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/screenmarkers/ui/ScreenMarkerPanel.java, runelite-client/src/main/java/net/runelite/client/ui/components/colorpicker/ColorPickerManager.java, runelite-client/src/main/java/net/runelite/client/ui/components/colorpicker/RecentColors.java, runelite-client/src/main/java/net/runelite/client/ui/components/colorpicker/RuneliteColorPicker.java
Closes https://github.com/runelite/runelite/issues/7926
Only 1 color picker can be open at a time now. When a new one is opened, the onClose will be executed for the old one.
Everyone will start with no recent colors and then it will slowly build up until there are 16 colors and start evicting the oldest color.
=> Color Picker: add recent colors

runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningOverlay.java
The current threshold is too low, the ores in the lower MLM often respawn way after the 123 seconds set originally. After tracking the respawn times in WallObjectSpawned event for an hour while standing in one spot in MLM I discovered that every half a minute there was a respawn that occurred after a longer time than 123s. Mostly it would be 140-150 second respawn, but there were also a few 165s occurrences and one time it was 166s. That exception could be a floating point error I guess?
The below is my debug overlay that showed up after there were no progress pies for the marked wall objects as they have exceeded their "max" respawn time.
=> mlm: fix ore vein max respawn time threshold

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java
This patch will cause menu entries to have their options and/or targets
recolored in the same way as "Take" menu entries are already recolored
when telegrab menu entries are added.
Closes runelite/runelite#4930
=> grounditemsplugin: Color telegrab menu entries

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/Task.java, runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java
This adds a field to Task which dictates the expected exp gain of the
task. When set to a non-zero value, it will prevent slayer exp gains
from registering as a kill unless they are of exactly that amount.
Closes runelite/runelite#1865
=> slayerplugin: Correct Jad and Zuk task tracking

runelite-client/src/main/java/net/runelite/client/plugins/config/PluginListItem.java
I wasn't able to repro myself, but commenting out the `mouseExited` override method of the mouse listener is a simple way to see that this change works.
Fixes runelite/runelite#9007
=> PluginListItem: Reset label color on popup menu item click

runelite-client/src/main/java/net/runelite/client/RuneLite.java
This reverts commit 6e080949f9943ac118b62840bac0624f1f3e6d7b.
This never worked because it ran stopPlugin on the AWT thread
which calls invokeAndWait, which throws when not on the awt
thread. Also stopPlugin only attempts to stop plugins that are
marked as disabled, but it is only called for plugins which are
enabled, so nothing actually happens. This also creates a deadlock
if you try to close the client while starting it, because
startPlugin is locked on one thread, but stop plugin is trying
to take the lock on the edt.
Closes #7633
=> Revert "Shutdown plugins on window close"

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java
Saw this in discord:
Before:
After:
My first pull request so let me know if I did anything wrong!
=> XP tracker: Fix issue where progress bar shows 100.00% before level up

runelite-client/src/main/java/net/runelite/client/util/ImageUtil.java
The runescape client applies this, but we hit ImageIO alot before that happens.
Closes #9156
=> runelite-client: Don't write all images to disk when loading them

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/AnagramClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CipherClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/MusicClue.java
I noticed some of the hint overlays use "Area" and others use "Location". Figured I would do this for consistency's sake, but if it's not worth it, I'll close it.
=> Cluescrolls: Use "Location" Label Consistently in Hint Overlays

runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/JagexPrintableCharMatcher.java, runelite-client/src/test/java/net/runelite/client/plugins/chatfilter/ChatFilterPluginTest.java
Fixes #8545 
The chat history plugin replaces spaces with NBSPs (`\u00A0`) when it replays historical messages so that the chat commands and chat notifications plugins don't trigger on these messages. The problematic line of code in the chat filter plugin removes all characters that cannot be displayed in the chatbox, *including the NBSP*, via the `jagexPrintableCharMatcher.retainFrom` call. This results in a historical message of `hello world` turning into `helloworld` before being checked for matching filter patterns, because the space gets converted into an NBSP by the chat history plugin, and this NBSP is then removed by the chat filter plugin.
I've added NBSP to the list of characters that JagexPrintableCharMatcher matches so that multi-word historical messages keep their spaces …
=> Fix issue where chat replayed from the chat history plugin is not filtered through the chat filter plugin

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
The looted message "You have successfully cleared this patch for new crops." seems to be unique to the Hespori patch.
Closes #9249
=> Add Hespori to loot tracker

runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java
GL_STATIC_DRAW means that the buffer will be created once, set once, and
used once, but its created once, updated a lot, and used a lot, what
means it should use GL_DYNAMIC_DRAW (this param affects how
glBufferSubData later works).
Closes #7320 
=> Use GL_DYNAMIC_DRAW for ever-changing uniformBuffer

runelite-client/src/main/java/net/runelite/client/plugins/smelting/SmeltingOverlay.java
Smelting cannonballs takes 10 ticks per bar so the current delay was simply too short. 
Closes #9418
=> Fix overlay when smelting cannonballs

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatChanges.java
Adds hp restore values to item stats plugin for the following items:
https://oldschool.runescape.wiki/w/Spider_on_stick#Cooked
https://oldschool.runescape.wiki/w/Spider_on_shaft#Cooked
=> itemstats: Add Tai Bwo Wannai spider on a stick/shaft fooditems

runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java
Performance enhancement, prevents Pattern.compile(regex) being run more than necessary.
=> Precompile the split regex in RaidsPlugin

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatChanges.java, runelite-client/src/main/java/net/runelite/client/plugins/itemstats/potions/GauntletPotion.java, runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
Adds the potion and food from the Gauntlet to the item stats plugin. Also adds the stamina timer tooltip when you drink the potion via the timers plugin.
=> Add Gauntlet consumable information

runelite-client/src/main/java/net/runelite/client/plugins/fps/FpsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldHopperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldHopperPingOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldHopperPlugin.java
Moved my other PR into world hopper as it was redundant to have its own plugin. The current ping time is every second. It can be changed if that is too frequent. 
If display current ping is checked it will also update the world hopper ping panel as well, so they are consistent.
=> Add display current ping to world hopper

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Text is based on the game update blog post. I believe this is correct but cant test until update is live.
=> menuentryswapper - Add volcanic mine entrance

runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java
Yaw and pitch for these effects is only altered during scene drawing, so we need to cache those values at that point.
Closes #7585
=> gpu plugin: fix camera effects used for drunkeness and fishing trawler

runelite-client/src/main/java/net/runelite/client/plugins/inventorygrid/InventoryGridOverlay.java
When dragging an item and its original slot gets emptied, the dragged item sprite is removed to indicate that you are no longer dragging an item. The inventory grid should be held to the same standard.
Closes #9053
=> Disable inventory grid if the dragged item is removed

runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
This prevents overlay graphics configurations leaking to other overlays.
=> Snapshot all grahics2d properties in safeRender

runelite-api/src/main/java/net/runelite/api/InventoryID.java, runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
saw some inventory checks have region checks but not 100% sure as to why. I got the region id for managing miscellania (10044) and can add if needed.
=> LootTracker: Add Kingdom of Miscellania

runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordGameEventType.java
The Discord plugin has some spelling errors when displaying a user's location in some obscure locations, namely Jatizso Mines and Yanille Agility dungeon.
=> Discord: Fix spelling errors in broadcasted locations

runelite-client/src/main/java/net/runelite/client/plugins/attackstyles/AttackStylesOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/attackstyles/AttackStylesPlugin.java
Hiding attack styles primarily relies on a subscription to onWidgetHiddenChanged but when swapping between bludgeon to bow this event fires before onVarbitChanged which means that when swapping quickly between the two the longrange option will not be hidden.
There is also a NPE fix.
Closes #9564
=> Fix hiding attack styles when switching weapons

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java
Depends on !75
Jagex appears to be syncing the current tab varbit more aggressively now, so if the active tab was not the first tab before switching to a tag tab, bank layout would misbehave when the bank was reopened.
Closes #9401
=> bank tags: properly open saved tab

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-api/src/main/java/net/runelite/api/ScriptArguments.java, runelite-api/src/main/java/net/runelite/api/ScriptID.java, runelite-api/src/main/java/net/runelite/api/VarClientInt.java, runelite-api/src/main/java/net/runelite/api/widgets/Widget.java, runelite-client/src/main/java/net/runelite/client/game/chatbox/ChatboxPanelManager.java, runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/BankSearch.java, runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java, runelite-client/src/main/java/net/runelite/client/plugins/chatboxperformance/ChatboxPerformancePlugin.java
- trip an assertion when invoking a script with the wrong number of arguments
- Store the number of args machine readably in our repo
- stop tripping the aforementioned assertion
=> Ensure runScript is invoked with the correct number of arguments

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerRecord.java
The panel is currently rebuilt with the earliest loots at the top.
For consistency's sake it should be the other way around.
Closes #9575
=> Fix loot tracker order on client reload

runelite-client/src/main/java/net/runelite/client/plugins/slayer/Task.java
The Sarachnis boss slayer task remaining KC overlay will no longer show the slayer gem default. It will now use the pet like other bosses.
=> Use the Sarachnis pet, Sraracha, as the slayer task overlay icon.

runelite-client/src/main/java/net/runelite/client/ui/overlay/worldmap/WorldMapOverlay.java
Closes #8697, Closes #9622
This also corrects the clip so that tooltips don't render above the surface selector menu.
=> world map: correct canvas bounds location and clip tooltips properly

runelite-client/src/main/java/net/runelite/client/plugins/examine/ExaminePlugin.java
Removed the GE and HA price message when examining coins since it's redundant information.
Closes #9483
=> Fix examine coins extra line

runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/mining/Rock.java
Fix respawn timers for
- Adamant rocks in Wilderness Resource area
- Coal rocks in Miscellania
The doubled respawn rate of the adamant rocks is a possible Jagex bug as
they are the only type of rock within the Wilderness resource area to do so.
The coal rocks in Miscellania are mined for favour instead of ores
and therefore have a shortened respawn time.
Closes #9442, #9452
=> Fix wrong rock respawn timers

runelite-client/src/main/resources/net/runelite/client/plugins/gpu/frag.glsl
Fixes the white pixels at the edges of objects when using MSAA.
Before:
After:
=> Fix MSAA white pixels

runelite-client/src/main/java/net/runelite/client/ui/components/colorpicker/RuneliteColorPicker.java
Closes #9587 
Bug occured because focus lost events are fired after the window closing event in Swing. Thus the selected color wasn't updated yet.
=> colorpicker: force hex color to update on window close

runelite-client/src/main/java/net/runelite/client/rs/ClientConfigLoader.java, runelite-client/src/main/java/net/runelite/client/rs/ClientLoader.java, runelite-client/src/main/java/net/runelite/client/rs/HostSupplier.java
Some people seems to be unable to connect to the servers that Jagex's load balancer, so if we can't connect to that we now instead:
- try to grab the worldlist from api.runelite.net and choose some random servers from that
- failing above; try some random server hostnames
=> runelite-client: Bypass Jagex load balancer if we can't connect

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java
null tasks are technically valid, it only means they arent explicitly defined in the Task enum.  allow them through so that if there is a task capture failure the counter will still work.  
This functionality was especially useful when Konar was released as every one of her tasks were not captured properly and ended up being null, this allowed people to have counters that worked as they expected until the release that captured her tasks correctly.
=> slayer: allow unknown tasks to still decrement counter

runelite-client/src/main/resources/net/runelite/client/plugins/skybox/skybox.txt
Affects every plane.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
=> skybox: add Braindeath Island

runelite-client/src/main/resources/net/runelite/client/plugins/gpu/frag.glsl, runelite-client/src/main/resources/net/runelite/client/plugins/gpu/geom.glsl
#9354 caused an issue where (mostly) Intel iGPUs complained about a type mismatch in the shaders, due to the fragment shader providing a `float` when it was expecting a `centroid float`.
=> Fix "Fix MSAA white pixels"

runelite-api/src/main/java/net/runelite/api/Actor.java, runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerPlugin.java
Right-clicking in the black void outside of for example puro-puro sets the `selectedSceneTile` to null.
In addition to this fix, I also annotated the following methods as Nullable:
- `Actor::getName`
- `Client::getLocalPlayer` - Is null after startup on login screen.
- `Client::getDraggedWidget` - returns null if no widget is dragged 
- `Client::getDraggedOnWidget` - returns null if no widget is dragged
=> Fix NPE in groundmarkerplugin and annotate some methods as nullable

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java
Because a user can have 0 slayer experience on a new account, we cannot
rely on 0 as the pre-login value. Prior to this change, a player getting
their first slayer kill in the described scenario would cause it not to
be counted toward the tracked task.
=> slayerplugin: Fix first slayer kill not being registered

runelite-client/src/main/java/net/runelite/client/plugins/slayer/Task.java
fixes #9689 
Jagex uses British spelling. [Vampyre](https://oldschool.runescape.wiki/w/Vampyre)
=> slayer: correct Vampyre task spelling

runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsPlugin.java
Being only interested in the stat change timer and not the cluttering of the combat boosts, there is now a toggle to not display combat boosts.
=> Add toggle to not display combat boosts

runelite-client/src/main/java/net/runelite/client/chat/ChatMessageManager.java
closes #6351
I was not able to test how MODPRIVATECHAT type works, so it may be caught in a crossfire unnecessarily.
We should maybe consider adding a setting to color From/To tags and the colon in a different color than the username itself after the config grouping PR is merged.
=> chat: fix private chat username recolouring, improve responsiveness to config settings

runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java
Closes #9681
I think this started happening more often because the splash screen delayed the client ui's window getting created, so this race gets hit much more frequently.
=> gpu: wait for canvas to get it's native peer before starting OpenGL

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java
Fixes #3987.
This PR adds a boolean in setTask that specifies whether the method was called by performing an action (e.g checking your slayer gem) or if it was called by logging in/starting up. 
Previously if the user were to log in the Instant used to time out the infobox was set to be current. This caused unwanted behaviour where the infobox would appear for the first five minutes of being logged in eventhough the user had not performed any slayer related actions.
=> slayer plugin: do not show task infobox on login

runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPluginTest.java
Works similar to the Idle Animations component - sends a notification after `waitDuration` milliseconds if the player's character stops moving.
Some may find it useful for activities with long walking durations, like Runecrafting or Fishing.
=> Added idle movement notifications to the Idle Notifier plugin

runelite-client/src/main/java/net/runelite/client/plugins/runecraft/AbyssMinimapOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/AbyssOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftPlugin.java
Moving the AbyssOverlay down to the correct layer stopped the runes from displaying on the minimap. Why an overlay was trying to do both Scene and Minimmap rendering I have no idea, but I've moved the minimap code to its own overlay. I've also moved the "what rifts to render" stuff to the plugin, since it's now common
=> runecraft: give minimap icons their own overlay

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/HouseAdvertisementMode.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
The motivation for adding a menu entry swapper to the house advertisement was to get the "visit-last" option on left click. This is nicer to use than "friend's house" on the POH portal because it doesn't require you to 1.  retype in the friends name or 2. click the last POH name in the chat box
Fixes #9868
=> menu entry swapper: add house advertisement board

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/EmoteClue.java
Fixes this:
Somehow, the ordering has been wrong since https://github.com/runelite/runelite/commit/a244ca22649c71eb92dd1a890eced2fe1a82036c, for a month and a half.
=> clues: fix emote hint ordering

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java
When receiving a new beginner or master clue step (which can be detected
by checking the item ID shown in the chat dialog), the clue ID does not
change, because all beginner and master clues share a single ID. Hence,
we can reset the current clue when the "You've found a new clue!" dialog
appears to prevent stale clue information from persisting between steps.
Closes #9830
=> cluescrolls: Reset clue on new beginner/master step 

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerBox.java
Closes #5673
Doesn't break with high killcount, even up to the limit of a `long` (though it's not really usable at that point anyway)
=> loot tracker: truncate name instead of kills

runelite-client/src/main/resources/npc_health.json
Add NPCs in the Forthos Dungeon to the <a href="https://github.com/runelite/runelite/blob/master/runelite-client/src/main/resources/npc_health.json">npc_health.json</a> as described in https://github.com/runelite/runelite/issues/9780
Closes #9890
=> Bug/9780 Add Forthos Dungeon monsters to the NPC health list

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java
Fixes #9847
Made change to Gu'Tanoth hard coordinate clue to add help text for user ease of use. After hopping over the bridge, the flag for the 20gp is reset, resulting in the player having to provide another 20gp on next visit.
=> Added Gu'Tanoth Hard Coord Clue Step Help Text

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_crafting.json
Just added a net icon and the values for the drift net at the crafting calculator.
closes #9957
=> Added Drift Net to Crafting Calculator

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpStateSingle.java
Since the base xp for level 1 is 0 the startLevelXp was initialized from the current level which made the progress bar calculations wrong as they were based on the xp earned from the current level base xp and not level 1.
=> xptracker: fix goals set from level 1

runelite-client/src/main/java/net/runelite/client/plugins/inventorygrid/InventoryGridOverlay.java
Display the sprite of the swapped item in the inventory grid overlay, if there is one.
=> Inventorygrid: Draw image for replaced item

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerPlugin.java
Prevents an assertion error being thrown when hopping between world types.
Closes #9668
=> XpTracker: Fix hopping to/from DMM worlds

runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
Right now the timer itself is random. Sometimes the prayer enhance infobox timer is longer than the actual effect. This removes the infobox when the prayer enhance expires.
Not tested but the message was taken straight from the debug logs.
=> timers plugin: remove prayer enhance infobox on expire

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
The ranged bonus of the toxic blowpipe is dynamic depending on darts and does not count when trying to complete this cryptic clue. As per the [Wiki](https://oldschool.runescape.wiki/w/Robin#Treasure_Trails)
=> Clarify that blowpipe won't work with Robin clue

runelite-client/src/main/java/net/runelite/client/plugins/banktags/BankTagsPlugin.java
Fixes issue reported in discord. If a user has no tagtabs, null will be returned from config manager during the first `removeInvalidTags` on line 158.
<details>
<summary>Stacktrace</summary>
```
2019-10-15 14:19:34 [main] WARN  n.r.client.plugins.PluginManager - Unable to start plugin BankTagsPlugin
net.runelite.client.plugins.PluginInstantiationException: java.lang.reflect.InvocationTargetException
at net.runelite.client.plugins.PluginManager.startPlugin(PluginManager.java:350)
at net.runelite.client.plugins.PluginManager.startCorePlugins(PluginManager.java:209)
at net.runelite.client.RuneLite.start(RuneLite.java:339)
at net.runelite.client.RuneLite.main(RuneLite.java:245)
Caused by: java.lang.reflect.InvocationTargetException: null
at …
```
=> banktags: null check for no tagtabs

runelite-client/src/main/java/net/runelite/client/plugins/randomevents/RandomEventConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/randomevents/RandomEventPlugin.java
- Configurable notifications for random events spawning
- Removes talk/dismiss options for random events that don't belong to you.
Doesn't support Strange Plant as there's no way to reliably determine if it belongs to you. 
Closes #1634
Supersedes #7755
=> client: add random event plugin

runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/timers/TimersPluginTest.java
They changed the 5 minute teleblock message so it doesn't specify the seconds anymore
=> Timers: Fix 5 minute tb message

http-service/src/main/resources/application.yaml
The Feed plugin now uses <https://twitter.com/RuneLiteClient/lists/feed-plugin> instead of my list.
=> feed: use RuneLiteClient's Twitter list

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPanel.java
Unfortunately, people lose their loot this way.
Logged in with sync warning:
Not logged in or sync turned off warning:
=> loottracker: add confirm dialog to reset all

runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/SkillCalculator.java
It doesn't make much sense to combine actions across skills.
=> skill calc: clear combined action slot on skill change

runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSpotMinimapOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSpotOverlay.java
For some people, the default cyan color on fishing spots blends in with the water surrounding it.
This makes the colors in the Fishing plugin configurable so you can change them according to your liking.
=> fishing: make overlay colors configurable

runelite-client/src/main/java/net/runelite/client/plugins/randomevents/RandomEventPlugin.java
On login, `interactingChanged` fires once with both player and target set to null.
=> random events: fix npe on login

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPluginTest.java
This PR adds a new option to the menu entry swapper plugin what when enabled adds shift click functionality to teleport spells with multiple options. Idea from #9992. This is almost a duplicate pr as #4031 exists however their solution only swapped one way whereas this one swaps both ways and that PR did not include the house teleport. 
Enable the option and test that the following teleports swap correctly when shift clicking them. Test they work in both directions (i.e change your default and ensure it still swaps the option when shift is held) 
Closes  #9992
=> Add shift click option to teleport spells with multiple locations

runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java
This was previously fixed for Withdraw-X, this applies the same fix to depositing as well.
=> tabinterface: remember search after clicking deposit-x

runelite-client/src/main/java/net/runelite/client/plugins/music/MusicPlugin.java
```
Gamma1991:
2019-10-24 21:10:25 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
at net.runelite.client.plugins.music.MusicPlugin.updateMusicOptions(MusicPlugin.java:445)
at net.runelite.client.plugins.music.MusicPlugin.applyMusicVolumeConfig(MusicPlugin.java:237)
at net.runelite.client.plugins.music.MusicPlugin.onVolumeChanged(MusicPlugin.java:205)
at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:72)
at net.runelite.client.eventbus.EventBus.post(EventBus.java:218)
at net.runelite.client.callback.Hooks.post(Hooks.java:164)
at client.cy(client.java:43538)
at fu.jp(fu.java:10850)
at client.gh(client.java:6552)
at client.yb(client.java:2446)
at client.as(client.java:1001)
at …
```
=> music: check parent and siblings for null

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerBox.java, runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerItem.java, runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPriceType.java
Closes: #5813
Closes: #7858
Adds an option to use HA values in the loot tracker, along with an option to visually show what type each price is. Also adds both prices to the item tooltips.
=> loot tracker: show HA prices

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/AnagramClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CipherClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
Closes #2740
This keeps the answer overlay visible if the user opens the Challenge Scroll itself, which is required when doing Elite clues.
There are a couple of clues I'm not sure about, specifically any with a number greater than 1,000 that doesn't have commas, but the information seems to be much more accurate than Sherlock's text was.
Also bundled are a few minor clue changes:
* Thanks to Cook from OSW, it has been discovered that the `HICK JET` clue never had a challenge scroll.
* The two Mandrith clues have been made distinct; now, one is for the question, and the other is for the Puzzle/Light box.
=> clues: add Challenge Scrolls to their clue scrolls

runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
closes #10183 
Fixed ScreenshotPlugin so that checking Kingdom of Miscellania does result in double screenshots.
=> Fix ScreenshotPlugin Kingdom of Miscellania double screenshot

runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonSpots.java
A great cannon spot at the bottom level of the Chasm of Fire.
Edit: This spot is perfect for rangers/mages. It will attack a few demons around the area. You can 100% safe spot if you stand where my character is.
=> Add Black Demon cannon spot in Chasm of Fire

runelite-client/src/main/java/net/runelite/client/plugins/examine/ExaminePlugin.java
Fixes #6201.
This PR updates a conditional in the `ExaminePlugin` so that price look-ups are triggered when examining items on the ground and a message is posted to chat, the same way it behaves when examining an inventory item.
The diff looks a lot bigger than it is because of indentation changes.
=> update ExaminePlugin to account for ground items

runelite-client/src/main/java/net/runelite/client/plugins/inventorygrid/InventoryGridConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/inventorygrid/InventoryGridOverlay.java
Replace the time dependant showing of the inventory overlay with a distance based one. An item sprite only follows the mouse if the mouse is held down and dragged ~5 pixels. Thus, the overlay will only show when you are certain to be dragging an item and the time-delay is unnecessary.
Original PR by Jbleezy. Supersedes/Closes #9764
=> inventorygrid: use mouse dragged distance to determine if overlay should show

runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java
Closes #9826 
The divine effect persists for the full duration, even if you die; you just lose the current boosted stats. Drinking a divine super combat potion -> dying -> regular super combat potion still allows boosted stats for the 5 minutes
=> update divine potion timers to not disappear on death

runelite-client/src/main/java/net/runelite/client/plugins/music/MusicConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/music/MusicPlugin.java
Closes #10176 
I noticed that area sounds can be created by players, npcs, or neither, so I added the option to mute each independently (as well as the player them-self), as opposed to just other players.
This is my first contribution here (and to any open source project in general!) so please roast me if necessary!
=> Add more area mute options

runelite-client/src/test/java/net/runelite/client/plugins/attackstyles/AttackStylesPluginTest.java
When swapping between bludgeon and bow, `onWidgetHiddenChanged` is called before the weapon varbit is set. Since that varbit determines which widgets should be hidden we would like to make sure the widget is set to hidden even after a varbit change.
This should probably have been a part of #9578, but it's here now :slightly_smiling_face:
=> attack styles: add test for swap between bludgeon and bow

runelite-client/src/main/java/net/runelite/client/Notifier.java
Makes it so moving the mouse over the window doesn't cancel notifications (Ie you're moving mouse from right to left monitor without noticing notification, so you end up cancelling unintentionally)
=> Require client focus for "until cancelled" notifications cancelling

runelite-client/src/main/java/net/runelite/client/plugins/chathistory/ChatHistoryPlugin.java
Normal world: `Welcome to Old School RuneScape.`
Twisted league: `Welcome to Old School Runescape: Twisted League!`
fixes #10297
=> Update ChatHistoryPlugin welcome message string to include TL

runelite-client/src/main/java/net/runelite/client/plugins/inventorygrid/InventoryGridOverlay.java
Currently, the item will use a quantity of 1 when dragging an item, which doesn't look good when moving an item with different sprites for different quantities.
=> inventory grid: use correct item quantities for drag previews

runelite-client/src/main/java/net/runelite/client/plugins/music/MusicPlugin.java
resolves #10248
This will also mute teleports cast by the player, as there is no simple way to tell who created the sound without a source. Note that using a mounted amulet of glory still makes the teleport sounds, even if every possible selection is muted.
Perhaps you'd rather have teleports be environmental sfx anyway? This seemed like a better place to put them, though.
=> Reclassify teleport sfx as other players' area effects instead of environmental area effects

runelite-client/src/main/java/net/runelite/client/config/ConfigInvocationHandler.java, runelite-client/src/main/java/net/runelite/client/eventbus/EventBus.java, runelite-client/src/main/java/net/runelite/client/util/ReflectUtil.java
The private ctor we used for `MethodHandles$Lookup` is gone in jdk-14.
See https://github.com/runelite/runelite/issues/9909#issuecomment-543913435
There are still [some issues related to using jdk14+](https://bugs.openjdk.java.net/browse/JDK-8222677), but I don't think they impact runtime significantly, as they are all wrapped in a try/catch `Throwable`
=> runelite-client: use privateLookupIn for invokespecialing defaults

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerConfig.java
Fix typo in the syncPanel ConfigItem of the loottracker plugin.
=> loottracker plugin: fix typo

runelite-client/src/main/java/net/runelite/client/plugins/leaguechaticons/LeagueChatIconsPlugin.java
**Changes:**
- Rename plugin from `Chat League Icons` to `League Chat Icons`
=> League Chat Icons: Rename plugin

runelite-api/src/main/java/net/runelite/api/VarPlayer.java, runelite-client/src/main/java/net/runelite/client/plugins/camera/CameraConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/camera/CameraPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/camera/ControlFunction.java
Added a small plugin that allows rotating of the camera through right-click when there are no menu entries.
I find this plugin very useful when there's lots of camera rotating.
Clicking anywhere on the floor, a wall or in the sky will allow you to rotate the camera.
This makes it so you dont have to keep swapping your finger to the scroll wheel.
Turning you camera with right-click realy shines in activities like agility, runecrafting, stealing artifacts, or bosses like Vorkath.
Options are available to ignore "Examine" entries and to open the menu though middle-click.
I've added an option to make middle-click open the menu, this so you can prepare a "Walk here", for example during bossing.
Give it a go, hope you'll like it!
=> Right-Click Camera, Rotate te camera with right-click

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java
Fixes bug #10374, that receiving a first slayer task from Konar isn't detected by the Slayer plugin.
All I did was slightly modify the regex to work with the default masters' first task text and with Konar's.
=> Adds detection for first slayer tasks given by Konar

runelite-client/src/main/java/net/runelite/client/plugins/twitch/TwitchPlugin.java
Currently, the Twitch plugin doesn't assign timestamps to messages, which looks weird alongside in-game messages
=> twitch: add timestamps to messages

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Closes #10393 . Swaps "Teleport Menu" with the most recently traveled destination when hovering over the Jewellery Box in a player owned house.
=> Add Jewellery Box to Menu Entry Swapper

runelite-client/src/main/java/net/runelite/client/plugins/objectindicators/ObjectIndicatorsPlugin.java
poh and cox instances use a different plane in their source chunks than
the destination chunks, which made this unable to remove the objectPoint
in most poh wallkits. This also makes it so if you add a dungeon to your
poh it won't destroy your markers
Fixes #10371
=> objectindicators: Correctly match template plane

runelite-client/src/main/java/net/runelite/client/plugins/examine/ExaminePlugin.java
Stack prices for the Examine plugin are calculated with 32-bit integers. If the stack price was over 2.147 bil (such as if you had multiple tbows or something) it would overflow and display a negative number. This fixes that by just casting the item price to a long int before calculating the stack price.
This issue is also present in the ItemPrices plugin, which I've created another pull request for.
This Fixes: #10443
=> Fix integer overflow on Examine plugin price text

runelite-client/src/main/java/net/runelite/client/plugins/itemprices/ItemPricesOverlay.java
Stack prices for the ItemPrices plugin are calculated with 32-bit integers. If the stack price was over 2.147 bil (such as if you had multiple tbows or something) it would overflow and display a negative number. This fixes that by just casting the item price to a long int before calculating the stack price.
This issue is also present in the Examine plugin, which I've created another pull request for.
This fixes a related issue pointed out in: #10443
=> Fix integer overflow on ItemPrices price text

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootReceived.java, runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
Adds a `LootReceived` event to the Loot Tracker plugin so external plugins can utilize new loot data.
=> Add LootReceived event to Loot Tracker plugin

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatChanges.java
The stat tooltip for White tree fruit was incorrect.
[Wiki Reference](https://oldschool.runescape.wiki/w/White_tree_fruit) plus manual testing on several accounts to confirm it is a range based on Agility level. (Probably a step function but I don't have enough data points to calculate an actual formula.)
=> Fix White Tree Fruit stat change info

runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/WoodcuttingPlugin.java
game objects only update when the player can see them on their current plane
track the previous onGameTick player plane to ignore any despawn event that does not occur on that same plane
the server only spawns and despawns objects on your current plane
so when you go down stairs you get hit with all the changes that happened while you were gone, this means any tree that has been chopped while you were upstairs gets a fresh new despawn event.  
this pr accounts for that by only allowing the plugin to act on those events if you have been on that plane for a tick already
fixes #10449
=> woodcutting: fix inaccurate despawn events

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/GEItemCollectMode.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
closes #10434 
Adds an additional feature to the Menu Entry Swapper plugin allowing the user to choose the default item withdrawal from a GE offer (Notes, items, or bank).
=> add menu swap support for grand exchange offer withdraw

runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java
match the white/blacklisted room against a lax contains check on the room name itself which allows the old way of specifying a unknown room to still function for people as expected when highlighting it on the overlay
=> raids:  allow "unknown" to evaluate to both unknown room types

runelite-client/src/main/java/net/runelite/client/chat/ChatMessageManager.java
This fixes the recent issue of clan chat rank icons not showing if the channel name was recoloured. What happened was the Chat Message Manager was using the event's field for the channel name, which isn't updated with changes from the Clan Chat Plugin, and was therefore overwriting the icon that was added.
=> chat message manager: make sender recoloring use messageNode

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerPlugin.java
If the wrong password is entered, the xp tracker unpauses for a brief moment since the `GameState` is no longer `LOGIN_SCREEN`.
Closes #10491
=> xp tracker: don't unpause on failed login

runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityOverlay.java
Closes #10556
Adds a toggle to the agility plugin to show or hide agility course clickboxes.
=> add toggle for visibility of agility course clickboxes

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java
With [today's update](https://secure.runescape.com/m=news/a=13/eating-in-the-bank?oldschool=1), the Duel Arena coordinate clue has been moved. This updates the hint for it.
=> cluescrolls: update hint for Duel Arena Coordinate Clue

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
closes #10567
Adds a shift click swap to the NPC Contact spell, similar to the shift click teleport swap.
=> add shift click swap to npc contact spell

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
This update swaps the options for Board (slow) and Pay-Fare (fast) on the Brimhaven cart, if the Travel menu entry swapper plugin setting is on.
=> Add Brimhaven cart to Travel menu entry swapper plugin

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
Fixes #2335 
Seeing as #5112 hasn't seen any activity in a while I thought I'd take a look at this one. This solution works on Windows 10.
Tested with and without custom chrome as well as minimised, maximised and with the client always on top option turned on (you can still minimise it when that is on). 
Implements [this workaround](https://stackoverflow.com/questions/309023/how-to-bring-a-window-to-the-front/7435722#7435722) with additional code to avoid resizing the client.
=> Fix client not coming to front on Windows while using "Request focus on notification"

runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java
They were moved back when the show unlock message option was added
=> widgetid: change sound slider ids

runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanChatPlugin.java
Users might accidentally prepend their message with / by force of habit.
Closes: #10514
=> clanchat plugin: strip leading / from clan tab chat messages

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/ShiftDepositMode.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/ShiftWithdrawMode.java, runelite-client/src/test/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPluginTest.java
Closes #10612
Ctrl-clicking will now swap the left click to Withdraw-All or Deposit-All. Ctrl-click was chosen instead of Shift-click because Shift is used for the Swap Bank Op option (shift-click for eating/wearing/etc).
This is super useful for when you want to alternate between Withdraw-1/5/etc and Withdraw-All quickly without having to select the All button or right click. An example would be if you had a stack of Ava's devices (which I do). I could just left click Ava's Accumulator to withdraw 1 like usual, and then ctrl-click my arrows to withdraw them all. Really simple and helpful QOL change.
=> Shift-Click to Withdraw-All/Deposit-All

runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPluginTest.java
adds back the fishing animations to check for animation idle
checks to see if the character has been interacting notified when attempting to send animation notification for the same activity, if so it skips the animation notification.
fixes #8429 
fixes #9714
=> idle notifier: allow animations fallback for interacting checks

runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java, runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java, runelite-client/src/main/java/net/runelite/client/config/Units.java, runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/cooking/CookingConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/regenmeter/RegenMeterConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/smelting/SmeltingConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/stretchedmode/StretchedModeConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TimeTrackingConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/wintertodt/WintertodtConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/WoodcuttingConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerConfig.java
Adds an annotation (like `@Range`) to specify the units to be displayed in the box. This should lessen confusion on certain config items that have their units hidden by length or by being in the tooltip.
=> Add Unit support to Config

runelite-client/src/main/java/net/runelite/client/plugins/Plugin.java, runelite-client/src/main/java/net/runelite/client/plugins/banktags/BankTagsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/banktags/TagManager.java, runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabManager.java, runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java
Some plugins create config keys that aren't reset by the config reset button (IE banktags).
This adds an overridable method to the Plugin class that that is called on reset button click.
=> Add additional reset configuration for plugins

runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java
Fixes an issue reported in discord. Child 2 is a layer for LMS.
https://gyazo.com/5042fd2149e1575454fad7c4fbe129f3
=> widgetid: fix LMS INFO

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdSolver.java, runelite-client/src/test/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdSolverTest.java
The hot-cold solver previously was unable to perform narrowing if given
a temperature change of "SAME", leading to less-than-optimal results
when a number of otherwise-possible solutions could be removed from the
possible results by inferring that since they would have yielded a
"COLDER" or "WARMER" temperature change. This commit removes possible
solutions which are absolutely closer or farther from the previous
tested location.
One pre-exisitng test needed to be updated to pass with this change, as
it expected results to be narrowed more slowly than they now are. In
addition, a minimal test case with only two starting locations has been
added to demonstrate this change is working correctly.
=> HotColdSolver: Add same-temperature solution narrowing

runelite-client/src/main/java/net/runelite/client/plugins/customcursor/CustomCursor.java, runelite-client/src/main/java/net/runelite/client/plugins/customcursor/CustomCursorPlugin.java
Fixes #8764 
Looks like we have no choice put to force users to put their image file in the runelite directory to avoid breaks between machines. Alternative implementation to #8774 and simpler because it just adds another dropdown choice instead of a file chooser. Result is the same though in terms of having my own crab cursor. 🦀
=> Allow a custom image cursor

runelite-client/src/main/java/net/runelite/client/plugins/config/PluginHubPanel.java
This maintains the current behavior of only supporting html if the description starts with `<html>`
Supersedes/Closes #10713
=> PluginHubPanel: Limit height of description to 2 lines, enable word wrap

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java
Adds the worldpoint for the elite step that takes place within Prifddinas.
Fixes #10702
=> Add description to an elite clue step within Prifddinas

runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPlugin.java
This commit adds a number of related tags to the RuneLite configuration
in order to make it more easily discoverable as many users are not able
to find the settings it contains via search.
Closes runelite/runelite#8491
=> ConfigPlugin: Expand RuneLite plugin tags

runelite-client/src/main/java/net/runelite/client/game/LootManager.java
Special handling is required to log drops from the nightmare due to the unfortunate mechanics of how she "dies". To summarize how the plugin currently works, it first logs all item spawns that happened, after that it waits for a trigger (either a npc despawning or a npc animating) on the same tick. Unfortunately the nightmare doesn't do any of the current trigger, thus special logic is required.
How this special case addition works:
- When the nightmare dies it transmogs from 9430 to 9433, when the plugin detects that it keeps the reference to the npc and starts searching the adjacent tiles for loot for the next 15 game ticks;
- If loot is found in an adjacent tile it dispatches a `NpcLootReceived` event and stops the procedure;
- If no loot is found in the specified time it stops …
=> loot-tracker: Log nightmare of ashihama drops

runelite-client/src/main/java/net/runelite/client/externalplugins/ExternalPluginManager.java, runelite-client/src/main/java/net/runelite/client/plugins/PluginManager.java, runelite-client/src/main/java/net/runelite/client/plugins/config/PluginListPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java
The current way of invoking it on the executor would let the client have
a start and a stop for a plugin sitting in the executor's queue, making
it toggle endlessly. This only was because we were using invokeAndWait
in startPlugin, which can't be invoked on the EDT because it would
deadlock with itself.
Fixes #10677
=> PluginManager: require start/stop to be invoked on the EDT

runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangePlugin.java
The Grand Exchange plugin doesn't currently upload any trade history for buy/sell orders that were cancelled after being partially completed. This commit updates the plugin to upload the portion of the trade that was successfully bought/sold prior to the trade being cancelled, so that the Grand Exchange trade history on the RuneLite website will more closely match the in-game history.
=> Log cancelled buy/sell orders in GE history tracker

runelite-client/src/main/java/net/runelite/client/plugins/implings/ImplingsPlugin.java
Implings that spawn in a 'puff of smoke' will now always trigger a notification
Fixes #10750
=> Fix impling notifications

runelite-client/src/main/java/net/runelite/client/util/ImageCapture.java
if a screenshot was manually taken there is no filename passed to the capture function causing the appended space meant to separate the date from a filename to be the first character in the filename.
fixes #10800
=> ImageCapture: only append space when filename isnt empty

runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java, runelite-client/src/main/java/net/runelite/client/plugins/timers/TimerTimer.java, runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
This commit allows the poison timer to be much more accurate as it
receives periodic updates from the server, and covers edge cases where
poison may be delayed or cured from sources besides potion clicks.
(banked potion drinks, HP orb "Cure" menu option, etc.)
This commit removes the `initialDelay` field from GameTimer as the field
was used only to chain antivenom timers into their follow-up antipoison
timers.
Fixes runelite/runelite#1471
Fixes runelite/runelite#10724
Closes runelite/runelite#7956
Co-authored-by: Lucas <lws.ned1260@gmail.com>
=> Timers: Use poison VarPlayer value for antipoison/venom timers

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/cluescrolls/ClueScrollPluginTest.java
Location clue scrolls added a hint arrow when the player was nearby one
of the clue's locations. It did not, however clear that arrow if the
locations were changed and the previously-set hint arrow location was no
longer marked. This commit updates this behavior to clear the active
hint arrow should that be the case. (and if no NPC hint arrows are set)
Fixes runelite/runelite#10370
=> cluescroll plugin: Clear stale location clue hint arrows 

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_herblore.json
To be consistent with the [update from 20 June 2019](https://secure.runescape.com/m=news/wilderness-updates-and-dmm-summer-finals?oldschool=1), the Herblore skill calculator has been changed to show that a Compost Potion requires level 22 to make.
Fixes #10768
=> change herblore level needed to make compost to 22 in skill calculator

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
Clue solution text updated to reflect that the dig spot is no longer at the end of the tunnel.
Fixes #10744
=> update clue solution text for wilderness cryptic clue

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
Adds a reminder to bring a pet rock and rune thrownaxe to a clue requiring access to the DK lair.
Fixes #10738
=> add pet rock and rune thrownaxe to DK clue

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/AnagramClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CipherClue.java, runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java, runelite-client/src/test/java/net/runelite/client/plugins/cluescrolls/clues/AnagramClueTest.java, runelite-client/src/test/java/net/runelite/client/plugins/cluescrolls/clues/CipherClueTest.java, runelite-client/src/test/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClueTest.java, runelite-client/src/test/java/net/runelite/client/plugins/cluescrolls/clues/EmoteClueTest.java, runelite-client/src/test/java/net/runelite/client/plugins/cluescrolls/clues/FairyRingClueTest.java, runelite-client/src/test/java/net/runelite/client/plugins/cluescrolls/clues/FaloTheBardClueTest.java, runelite-client/src/test/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClueTest.java, runelite-client/src/test/java/net/runelite/client/plugins/cluescrolls/clues/MusicClueTest.java, runelite-client/src/test/java/net/runelite/client/plugins/cluescrolls/clues/SkillChallengeClueTest.java, runelite-client/src/test/java/net/runelite/client/plugins/cluescrolls/clues/ThreeStepCrypticClueTest.java
Fixes runelite/runelite#10775
Feel free to drop the second commit if it's not wanted. It doesn't change behavior but is a safeguard against weird cases like this in the future.
=> Clear clue scroll on empty dev command

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_construction.json
**Is your feature request related to a problem? Please describe.**
I cannot calculate how many Long Bones I need for my next Construction level with the RuneLite calculator
**Describe the solution you'd like**
I'd like to be able to know how many Long Bones I need for my next construction level.
**Describe alternatives you've considered**
I looked up how much xp long bones give, the amount of xp I need to level, and I know how to do basic division.
**Long Bone Details**
_Level:_ **1** (There is no construction requirement for Death to the Dorgeshuun or any of its prerequisite quests)
_Category:_ **Miscellaneous**
_Planks:_ **N/A**
_Count:_ **1**
_XP:_ **4500**
I completely accept if this isn't the kind of thing that y'all want on your skill calculator, but it _is_ a method of training …
=> Add Long Bone to Construction Calculator

runelite-client/src/main/java/net/runelite/client/plugins/inventorygrid/InventoryGridConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/inventorygrid/InventoryGridOverlay.java
If a player for example tries to drop an entire inventory quickly with the overlay turned on, the inventory grid will flash for each small mouse movement if the left mouse key is held down. This change mitigates the issue by adding a delay option that controls the amount of time the user has to wait after pressing it before enabling any overlay functionality. Showing the grid still requires the mouse to be moved ~5px away from the first clicked position.
This delay just delays the activation of the overlay, as the the delay countdown is started upon item press rather than the exit this ~5px range. Making it respect the exit is needlessly complex as desired functionality is reached with the current changeset.
Closes #10269
=> inventorygrid: re-add a delay to showing the overlay

runelite-client/src/main/java/net/runelite/client/plugins/barbarianassault/GameTimer.java, runelite-client/src/main/java/net/runelite/client/plugins/barbarianassault/Round.java, runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java, runelite-client/src/main/java/net/runelite/client/util/RSTimeUnit.java
This PR adds a list of time units used in some duration calculations, specifically client ticks and game ticks, and applies them to plugins using `Duration` calculations where they would be applicable.
=> Add RS-specific time units

runelite-client/src/main/java/net/runelite/client/externalplugins/ExternalPluginManager.java, runelite-client/src/main/java/net/runelite/client/plugins/PluginManager.java
If you loaded an external plugin that throws LinkageErrors it could cause the client not to start
=> PluginManager: try/catch Throwable all the plugin startup stuff

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java
Modified Shilo Village elite coordinate clue scroll hint to enhance readability.
Fixes #10844
=> Modified Shilo Village elite clue scroll hint for readability

runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java, runelite-client/src/main/java/net/runelite/client/ui/FatalErrorDialog.java, runelite-client/src/main/java/net/runelite/client/util/LinkBrowser.java
This should fix up most errors opening folders. Primarily this effects Linux where the Desktop.open() functionality isn't as robust as other platforms.
=> Implement LinkBrowser.open() and change instances of Desktop.Open()

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java
Closes #8009
I've gotten a couple of boss tasks from Konar recently, and noticed that they don't get picked up correctly.
Used a screenshot from MrNoSleep's 1k Alchemical Hydras video, since I forgot to take a screenshot on my end. [Video Link](https://youtu.be/MQIQAh_6yrE?t=237)
=> slayer: fix boss task parsing to support Konar

runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPluginConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/gpu/config/UIScalingMode.java, runelite-client/src/main/resources/net/runelite/client/plugins/gpu/fragui.glsl, runelite-client/src/main/resources/net/runelite/client/plugins/gpu/scale/bicubic.glsl, runelite-client/src/main/resources/net/runelite/client/plugins/gpu/scale/xbr_lv2_common.glsl, runelite-client/src/main/resources/net/runelite/client/plugins/gpu/scale/xbr_lv2_frag.glsl, runelite-client/src/main/resources/net/runelite/client/plugins/gpu/scale/xbr_lv2_vert.glsl
Related to #5781. Adds a UI scaling mode dropdown into the GPU plugin config, with an option for a new Catmull-Rom bicubic sampling function. It's a decent bit sharper than the old linear sampling both at 200% stretched mode scaling (nearest neighbor is still best for integer scale factors), and at non-integer scale factors. This makes 150% UI scaling look good enough for me.
150% NN
150% Linear
150% Catmull-Rom
200% NN
200% Linear
200% Catmull-Rom
=> UI bicubic & xBR rescaling

runelite-client/src/main/scripts/LayoutResizableStones.rs2asm
Closes #10846 
The script updater didn't merge correctly and causes the script to always skip our feature.
=> LayoutResizableStones: fix bad script merge

runelite-client/src/main/java/net/runelite/client/externalplugins/ExternalPluginManifest.java, runelite-client/src/main/java/net/runelite/client/plugins/config/PluginHubPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/config/PluginListItem.java, runelite-client/src/main/java/net/runelite/client/plugins/config/PluginListPanel.java, runelite-client/src/main/java/net/runelite/client/util/Text.java
1) Changed the panel to sort by display name, not internal name
2) The existing search logic gives basically useless results.
This makes it more in line with how the main plugin panel's search works.
=> Plugin Hub: Reorder plugin panel and rework the search function

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java
Highlighted and Hidden item lists currently become unordered when the lists are updated. This changes HashSets to ArrayLists to avoid this.
Duplicates in the lists will no longer be removed but since they can only happen by manually adding something to the list twice, it's not a huge issue.
=> GroundItems: Keep item lists in input order

runelite-client/src/main/java/net/runelite/client/plugins/wintertodt/WintertodtConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/wintertodt/WintertodtPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/wintertodt/config/WintertodtNotifyDamage.java
I've separated the notification options for the different Wintertodt events, as well as making the damage event notifications a choice between always notifying, and only notifying on interrupts (which now check for idle as well as woodcutting).
Supersedes #10535
=> Separate Wintertodt Notification Options

runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/config/UnitFormatter.java
Currently, trying to enter a value directly into an option with a unit will fail unless the user also inputs the unit.
I was trying to avoid writing a whole AbstractFormatter initially, since it seemed overkill. Evidently, it was the only way to do it properly.
Putting both the Formatter and the Factory in the same file is probably bad. Please let me know how you want it doing
Thanks to Trevor for notifying me of this issue.
=> config: fix entering values directly into options with units not working

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java
Closes #10840
Previously the Low/Medium/High/Insane threshold highlighting would take priority over the Highlight threshold highlighting. This simply puts Highlight at the top of the list, giving it priority.
Example:
My High value is 250k and Insane value is 1000k: An Abyssal Whip (2400k) it'll be highlighted as Insane, a Blessed D'hide Body (600k) will be highlighted as High.
If I set my Highlight threshold to 500k, the Blessed D'hide Body will now be highlighted with the Highlight color.
=> Make Highlight value take priority over other value thresholds

runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java, runelite-client/src/main/java/net/runelite/client/util/ImageCapture.java
This PR expands the ImageCapture util to allow a parameter to specify a subdirectory where, within a player's screenshots directory, the captured image will be stored, and extends the screenshot plugin to utilize this added functionality.
Closes runelite/runelite#8711
Closes runelite/runelite#8813
Closes runelite/runelite#10204
=> Add screenshot subdirectories

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatOverlay.java
This fixes the bug introduced in commit af00494a which incorrectly
compared the attack speed field and labeled it "Stab" in the item stats
tooltip.
Fixes runelite/runelite#10926
=> item stats: Fix tooltip stab bonus comparison

runelite-client/src/test/java/net/runelite/client/plugins/woodcutting/WoodcuttingPluginTest.java
I would rather my github profile be linked instead of my email.
=> Change to use github link instead of email

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java
=> HotColdLocation: Center South-east Dark Warriors' Fortress location

runelite-client/src/main/java/net/runelite/client/RuneLite.java, runelite-client/src/main/java/net/runelite/client/RuneLiteModule.java, runelite-client/src/main/java/net/runelite/client/account/SessionManager.java, runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java, runelite-client/src/test/java/net/runelite/client/config/ConfigManagerTest.java, runelite-client/src/test/java/net/runelite/client/plugins/PluginManagerTest.java, runelite-client/src/test/java/net/runelite/client/plugins/loottracker/LootTrackerPluginTest.java, runelite-client/src/test/java/net/runelite/client/plugins/motherlode/MotherlodePluginTest.java, runelite-client/src/test/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPluginTest.java, runelite-client/src/test/java/net/runelite/client/plugins/raids/RaidsPluginTest.java, runelite-client/src/test/java/net/runelite/client/plugins/screenshot/ScreenshotPluginTest.java
budget profiles
The behavior of this is as follows:
input file is relative to the RL dir unless an absolute path or a path that starts with "./" or ".\"
The --config arg does nothing if the user is logged into runelite (it keeps the current behavior of putting the config in the rl/profile dir)
=> client: add sessionfile and config arguments

runelite-client/src/main/java/net/runelite/client/plugins/antidrag/AntiDragPlugin.java
Fixes #10891
Changes default bank drag delay from 0 to 5, in line with official client behavior.
=> Fix Shift Anti Drag default bank drag delay

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/TransportationPointLocation.java
- Add worldmap target-snapping for Wilderness Levers in Ardougne & Edgeville
- Add target locations to Wilderness Lever tooltips
=> worldmap: add targets to Wilderness Levers & clarify their tooltips

runelite-api/src/main/java/net/runelite/api/ItemComposition.java, runelite-client/src/main/java/net/runelite/client/game/chatbox/ChatboxItemSearch.java
Depends on !78
Closes https://github.com/runelite/runelite/issues/9644
Supersedes/Closes  https://github.com/runelite/runelite/pull/9647
Uses item model information to filter out duplicate item images.
=> ChatboxItemSearch: check for duplicate item images

runelite-api/src/main/java/net/runelite/api/SpriteID.java
With the hitsplat changes on the 5th of March, Jagex has moved the venom hitsplat into the slot of an old Gameblast promo.
=> api: fix venom hitsplat sprite id

runelite-client/src/main/java/net/runelite/client/plugins/inventorygrid/InventoryGridOverlay.java
With the addition of overlays following dragged items this was overlooked.
Fixes the third point of #10696
=> inventory grid: fix showing the replaced item in the initial spot

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerBox.java
I've found myself manually calculating the average anyway out of curiousity.
This adds a tooltip to the number of kills label so that the average can be seen.
For those who'd prefer, it also allows the total GP to be replaced with the average value.
The tooltip will show the option not selected.
=> Add an option to show the average amount for a loot source in the loot tracker

runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java, runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/hiscore/NameAutocompleter.java, runelite-client/src/test/java/net/runelite/client/plugins/hiscore/HiscorePanelTest.java
Saves a certain amount of names (set to 25 right now) to the configuration. Only those that had been successfully queried.
Happy to get any remarks.
Closes #10809
=> Hiscore: autocomplete recent search history

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/ItemThreshold.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/NamedQuantity.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/WildcardMatchLoader.java
Adds the ability to use `<` and `>` when configuring highlighted and hidden drops.
Closes #1123
Supersedes/Closes #10533
=> ground items: add support for quantity thresholds

runelite-api/src/main/java/net/runelite/api/Varbits.java, runelite-client/src/main/java/net/runelite/client/plugins/driftnet/DriftNet.java, runelite-client/src/main/java/net/runelite/client/plugins/driftnet/DriftNetConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/driftnet/DriftNetOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/driftnet/DriftNetPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/driftnet/DriftNetStatus.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
This will add a plugin which shows the status of your nets and highlights any fish you haven't tagged.
Closes #9731
Supersedes/Closes #10139
=> drift net fishing: add plugin

runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/SkillCalculator.java
Closes #10445 
When clicking the same selected skill it will now only fetch the current XP
=> Skill Calculator: Fetch only the XP when opening the same skill

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatKeyboardListener.java
I can only check Ubuntu and Windows which both act the same where
`word1 word2 word3   word4   ` becomes `word1 word2 word3   ` 
(Keeps the trailing spaces after the word)
Using [this stack overflow thread]( https://stackoverflow.com/questions/228477/how-do-i-programmatically-determine-operating-system-in-java) as how to determine the OS
=> chatcommands: Don't remove spaces before cleared word

runelite-client/src/main/resources/net/runelite/client/plugins/skybox/skybox.txt
Added nightmare dungeon area to skybox colors.
Previously (Line 218 originally in skybox.txt) encompassed a tiny room. That line was removed, and the new region encompasses the previously removed region.
The color chosen is #0a0a0a (RGB 10,10,10).
Resolves 1 of 2 in #10771
=> Added nightmare dungeon area to skybox.txt

runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonSpots.java
=> Corrected Gnome Stronghold dungeon Bloodvelds cannon location.

runelite-client/src/main/java/net/runelite/client/plugins/timetracking/SortOrder.java, runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TimeTrackingConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TimeTrackingPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/timetracking/clocks/ClockManager.java, runelite-client/src/main/java/net/runelite/client/plugins/timetracking/clocks/ClockPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/timetracking/clocks/Timer.java, runelite-client/src/main/java/net/runelite/client/plugins/timetracking/clocks/TimerPanel.java
Originally made by @jakewilson 
Rebased, added proposed changes and tested. 
From my testing I fixed a couple of bugs, for example, timer going to 0 and then starting it over would show in warning color even if it was above the warning threshold.
Also when the timer is stopped in a warning state it shows the same color rather than a darker color.
Lets the user sort by ascending or descending time.
Lets the user choose a time for showing a timer warning in orange.
Closes #7240
Supersedes #7361
=> timetracking: add timer warning colors and ability to sort timers.

runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoOverlay.java
This seems to be against the rules again
> Indicates which player an NPC is focused on
https://secure.runescape.com/m=news/a=13/another-message-about-unofficial-clients?oldschool=1
reverts commit 34f94e973c18627a3d7f20faf8160647b87c09c9.
=> Revert "opponentinfo: add opponent's opponent for npcs"

runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialCounterPlugin.java
The spec plugin uses the first hitsplat after you spec. This adds some validation to at least make sure the NPC the hitsplat is on is the same one you speced.
=> spec counter plugin: fix other NPC hitsplats affecting specs

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/TeleportLocationData.java
Update the desert amulet teleport to reflect the new location from the [update ](https://secure.runescape.com/m=news/game-improvements?oldschool=1)
=> worldmap: update desert amulet nardah teleport location

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/ItemThreshold.java, runelite-client/src/test/java/net/runelite/client/plugins/grounditems/ItemThresholdTest.java
The regex used was explosive and wouldn't complete with large inputs that can appear when the user has a mildly corrupted config
=> grounditems: manually match item thresholds

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/AnagramClue.java
In the 26/03/20 update, Immenizz's NPC name was changed from `Impling` to `Immenizz` in an undocumented change. This fixes it.
=> clues: update Immenizz's master clue to reflect his NPC's name change

runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
prevent moving DYNAMIC and TOOLTIP overlays as these are not intended to be able to be moved.  
This fixes an issue where the Mouse Tooltips plugins tooltip can be accidentally moved and cannot be returned to its normal position 
[video showing them being moved on release](https://streamable.com/v4xav)
getting your cursor into a position where its rendering and you could be dragging another overlay at the same time seemed to be the best way to "start it",  from there the tooltips bounding box would be visible in one of the snap corners and you could then drag it anywhere you wanted
=> OverlayRenderer: prevent moving DYNAMIC and TOOLTIP overlays

runelite-client/src/main/java/net/runelite/client/util/SwingUtil.java
Currently any tooltips added using `my_toggle.addModalTooltip()` do not show until after the user has interacted with the button at least once. As a result, most plugins in the plugin list do not show the `pin plugin` or `enable plugin` tooltips. This bug can be reproduced simply by restarting the client and hovering the mouse over a plugin's star icon.
The reason for this is that `addModalTooltip()` looks as follows:
```java
public static void addModalTooltip(AbstractButton button, String on, String off)
{
button.addItemListener(l -> button.setToolTipText(button.isSelected() ? on : off));
}
```
The listener that we add only sets the tooltip text upon its state changing. If the button remains in its default state without any interaction (off), then the tooltip text doesn't show.
To fix …
=> Fix addModalTooltip to show tooltip before interaction

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingOverlay.java
closes #10900 
In render method, provide additional check to see if `WidgetInfo.LEVEL_UP` widget is loaded.
------
This solution works in all cases whereupon leveling up Fishing does NOT unlock new fish.
In the cases where you do unlock fish, there is a second dialogue describing which new fish you can catch. If you click through the level up dialogue, the fishing status will resolve to "Fishing" as if the second dialogue wasn't there. For other skills (Cooking, Mining) when you unlock something upon leveling up, a widget with groupId `DIALOG_SPRITE_GROUP_ID`, 193, is loaded, which would enable checking against presence of `WidgetInfo.DIALOG_SPRITE` to determine if player was in 'unlock new stuff' dialogue. However, when unlocking Fishing, the loaded groupId is 11, which is not assigned …
=> Check player animation to update fishing status

runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerFlickOverlay.java
This fixes it, but I don't know about the difference between MINIMAP_PRAYER_ORB and MINIMAP_QUICK_PRAYER_ORB.
Fixes #11133
=> Hide prayer flick indicator when minimap is hidden

runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/Axe.java, runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/WoodcuttingOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/WoodcuttingPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/WoodcuttingSession.java
This fixes a bug where the overlay would become hidden when chopping at
a tree without successfully chopping a log for longer than the
configured timeout, and would display "NOT woodcutting" if a log was
successfully chopped thereafter.
Fixes #7506
=> Fix woodcutting overlay hiding during long chop delays

runelite-client/src/main/java/net/runelite/client/plugins/runenergy/RunEnergyPlugin.java
Updates the energy recovery rate calculation to reflect the changes made
in the [9th January 2020 game update](https://secure.runescape.com/m=news/eating-in-the-bank?oldschool=1).
Each individual piece of graceful now boosts your recovery rate by 3%,
with an extra 1% for the top and legs. With the full set, an extra boost
of 10% is added, totalling 30%. Previously, there was no boost for
individual pieces, instead the full set was required for a flat boost of
30%.
**Edit:** Closes #10577
=> runenergy: update graceful recovery rate logic to reflect 9 Jan game update

runelite-client/src/main/java/net/runelite/client/Notifier.java
This was leaking instances of Clip, which on linux/alsa+alsa-pulseaudio
keeps a connection to pulseaudio open forever, for each notification
which will eventually lock/crash the pulse daemon.
If we just made it close the clip, it would become difficult to change
the volume because the volume interface would go away as soon as the
clip has stopped playing, so instead we keep the clip around after it
has been loaded if the mtime of the file hasn't changed.
=> Notifier: Reuse Clip instances

runelite-client/src/main/java/net/runelite/client/plugins/barrows/BarrowsPlugin.java
I was doing some smithing in Varrock, when all of a sudden my object indicators disappeared.
The only stacktrace I could find was this:
```
2020-03-31 01:01:39 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
at net.runelite.client.plugins.barrows.BarrowsPlugin.isInCrypt(BarrowsPlugin.java:252)
at net.runelite.client.plugins.barrows.BarrowsPlugin.onGameStateChanged(BarrowsPlugin.java:166)
at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:73)
at net.runelite.client.eventbus.EventBus.post(EventBus.java:222)
at net.runelite.client.callback.Hooks.post(Hooks.java:167)
at client.oz(client.java:62117)
at bn.ew(bn.java:1275)
at client.zl(client.java:2476)
at client.u(client.java:1114)
at …
```
=> barrowsplugin: fix null pointer exception in region check

runelite-client/src/main/java/net/runelite/client/chat/ChatMessageManager.java
Fixes the twitch plugin showing wrong timestamps
=> ChatMessageManager: Don't set timestamp if it's default

runelite-client/src/main/java/net/runelite/client/plugins/questlist/QuestListPlugin.java
Closes #11065 
The problem was 'currentFilterState' was being set on game state change only when logging in.
Fix was to set it on plugin start up to ALL
=> Quest Plugin: Fix null filter state bug

runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/BookPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/KourendLibraryConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/KourendLibraryPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/KourendLibraryPlugin.java
Adds a visual indicator on screen pointing to the location of the book which the player is currently being asked to retrieve. This is the same indicator used by the cluescrolls plugin.
Additionally, this changes the colors of the books in the sidebar to the following:
- Green: requested book, book not in inventory
- Orange: not requested book, book not in inventory
- White: book in inventory
Closes #10418
=> Kourend library features

runelite-client/src/main/java/net/runelite/client/plugins/music/MusicPlugin.java
Moving the music plugin's slider handles after their creation causes them to visually jump as shown in the GIF above.
This is because the handle's width is still 0 after its creation in `updateMusicOptions()`, as a call to `revalidate()` is missing after its original width is set. This then causes the slider's computed `newX` value to be incorrect.
=> music: revalidate slider handle on creation

runelite-api/src/main/java/net/runelite/api/Varbits.java, runelite-client/src/main/java/net/runelite/client/plugins/antidrag/AntiDragConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/antidrag/AntiDragPlugin.java
The changes made reflect the exact same sentiments stated by @dekvall  [in PR #10870](https://github.com/runelite/runelite/pull/10870).
The following features have been reverted/added to the anti-drag plugin:
- **Shift Anti-Drag** plugin has been reverted back to original **Anti Drag**
- _Shift Only_ anti-drag still remains an option.
- Any form of anti-drag is disabled in PvP scenarios. (Detected by the spec orb enabling/disabling). Including in PvP worlds and wilderness.
- Anti drag is enabled for banking.
With the addition of removing all forms of anti-drag for PvP scenarios, I believe this sufficiently solves the issue/uproar in the PvP community that caused the plugin to get reverted in the first place.
Example on a PvP world:
=> Revert Shift Anti-Drag and Disable in PvP Scenarios

http-api/src/main/java/net/runelite/http/api/npc/NpcInfo.java
These fields are never used. If we need this information we can get it from the client's cache
I intend to include the `name` field in the non-`.min` versions of this for easier debugging.
=> http-api: remove unused fields from NPCInfo

runelite-client/src/main/java/net/runelite/client/plugins/combatlevel/CombatLevelConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/combatlevel/CombatLevelPlugin.java
Personally, I like the functions that the Combat level plugin provides, but I much prefer to see a rounded combat level. This is of course a small QOL feature, that I don't think will hurt the plugin as it doesn't have many configs available currently.
=> Adds the option to disable the precise combat level display in the Combat Level plugin

runelite-api/src/main/java/net/runelite/api/ScriptID.java, runelite-client/src/main/java/net/runelite/client/plugins/bank/BankPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/BankSearch.java
The client will normally layout the bank during a search only once every 40 client ticks, causing slow response times after the search input is updated. Instead, hook the search refresh script that is called every client tick, and if the bank hasn't been laid out on the current tick, and the search input has changed, lay it out early.
Closes #9569
=> bank plugin: improve responsiveness of bank searches

runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsPlugin.java
Fixes the right-click menu targets expanding forever if clan rank or color decoration is enabled in the plugin. 
Menu entries don't get cleared while the menu is open, which was resulting in colors and ranks getting prepended on every client tick.
(The bug can be observed in-game by enabling 'Show clan ranks' and disabling 'Colorize player menu')
=> player-indicators: fix right-click menu targets expanding forever

runelite-client/src/main/java/net/runelite/client/plugins/antidrag/AntiDragPlugin.java
Currently, when opening the bank with `On Shift Only` enabled, delay is applied even if shift is not being held down.
Thanks to `Cholby` in the Discord for finding and reporting this
=> antidrag: fix onShiftOnly not being respected when opening the bank

runelite-client/src/main/java/net/runelite/client/plugins/bank/BankPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/itemprices/ItemPricesOverlay.java
Grand Exchange is addressed as GE everywhere, EX is confusing and can be mistaken for EXperience.
This changes the label placed over items on the ground.
=> Properly address Grand Exchange price as 'GE' abbreviation instead of 'EX'

runelite-client/src/main/java/net/runelite/client/input/KeyManager.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java, runelite-client/src/main/java/net/runelite/client/util/HotkeyListener.java
This prvent HotkeyListener from running on login screen without being
explicitely enabled to do so.
=> Prevent HotkeyListener from consuming input on login screen

runelite-api/src/main/java/net/runelite/api/ScriptID.java, runelite-client/src/main/java/net/runelite/client/plugins/interfacestyles/InterfaceStylesPlugin.java
this reverts commit abaf45092b9f20d1068698da3ed726db6b35bce2
We need to run this every frame because the client can update the widget
bounds cache without calling [proc,toplevel_resize]. This is easily
reproducible by resizing the client in fixed mode, which causes the
the tli to be revalidated, but because its in fixed mode it doesn't run
the resize listener because the bounds don't actually change.
We use BeforeRender instead of ClientTick because ClientTick is posted
before cs2s are evaluated each tick, so if [proc,toplevel_resize] (or
any other cs2 that can touch these widgets) is called the widget would
be in the vanilla position for the next frame.
Closes #11149
=> interfacestyles: update widget bounds before every render

runelite-api/src/main/java/net/runelite/api/Hitsplat.java, runelite-client/src/main/java/net/runelite/client/plugins/dpscounter/DpsCounterPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialCounterPlugin.java
I have not tested much, will test more but this should be fairly straightforward. The hitsplats were taken from the cache.
I didn't think this was worth putting in the javadoc but
The cyan hitsplats are used at the nightmare and verzik p1
The yellow hitsplats are use on the nightmare pillars
I have no idea where the white/orange hitsplats are used or if there are any usages I missed for the above two.
=> hitsplats: add missing multihitsplat varients

runelite-api/src/main/java/net/runelite/api/AnimationID.java
So, each of these rods have 2 animation IDs, with one of them showing the casting of the rod. This casting animation is used by the normal and oily rods. **However**, for whatever reason, the Fly fishing and Barbarian rods both use the non-casting animation whilst active.
Thanks to `Kaan` on the Discord for reporting this.
=> api: correct pearl fly fishing and barbarian rod animations

runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/RegionFilterMode.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldHopperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldHopperPlugin.java
This enhancement will add an option to the World Hopper plugin that will limit the quick-hop feature to worlds of a given region.
=> Add region filter to world quick-hopping

runelite-client/src/main/java/net/runelite/client/plugins/account/AccountPlugin.java
There's a typo in the tooltip text for the login button from the account plugin. Namely it uses `login` instead of `log in`, and `login` is only a noun, not a verb. It reads to me like the verb is the intended usage here. This PR switches `login` and `logout` to `log in` and `log out`.
Article describing difference: https://grammarist.com/spelling/log-in-login/
=> Fixed typo in account plugin

runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/timers/TimersPluginTest.java
When playing using the resizable viewport and the transparent chatbox,
teleblock messages are sent using a different color than when using the
standard chatbox. This commit removes that color matching entirely from
messages indicating that a teleblock timer has been applied or removed.
=> timers: Remove color matching for teleblock messages

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBoxOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpPanelLabel.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpProgressBarLabel.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpStateSingle.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerConfig.java
closes #10888
closes #8373 
This PR makes the XP tracker panel (and Overlay Canvas) labels configurable for different metrics.
TTL in Progress bar:
Customizable XpInfoBox
Config menu
=> xp-tracker: Add Time-To-Level to Canvas And XP Tracker

runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaNotWorkingOverlay.java
Ever since this "feature" was merged, users have been getting confused when the plugin magically doesn't work. The hint isn't a tutorial overlay, it's an integral part of user feedback. Hiding it permanently should never have been merged in the first place; a user should either get the plugin to work by following the instructions, or turn the plugin off.
=> npcaggro: remove hint hiding option

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerMapping.java, runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/loottracker/LootTrackerPluginTest.java
closes #11416 
Fixes the bug where clue scroll variations (excluding beginner & master) were not being stacked in loot tracker.
=> loot-tracker: make clue scroll drops stackable

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/special/CastleWarsBandage.java
Castle Wars bandages heal amount increases **by** 50% when the bracelet effect is on.
Currently, the plugin incorrectly calculates it as 50% of the total hitpoints level.
=> Item Stats: Fixed heal from Castle Wars bandages with CW Bracelet

runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordGameEventType.java
Adds the corner region ID of the Iorwerth dungeon with the elves.
=> Add missing region ID 12737 to the Iorwerth Dungeon Discord dungeon

runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeConfig.java
Gave the geSearchMode option in the grandexchange plugin a more meaningful descriptions so users can differentiate between what each search mode does
Closes #11431
=> Updated geSearchMode description

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java
For Tai Bwo Wannai Elite Clue specified 100 trading sticks are required to enter the hardwood area.
=> Additional elite clue information

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java
>25 degrees 48 minutes north
>35 degrees 0 minutes east
https://oldschool.runescape.wiki/w/Lithkren
Note: I couldn't figure out if/how these were organized so I just added it at the end of the elite clues.
=> Adds a new Elite Clue Coordinate direction

runelite-client/src/main/java/net/runelite/client/plugins/chathistory/ChatHistoryPlugin.java
Fixes bug with menu option not appearing on friend's messages
Allows copying of the "<" and ">" characters
=> Fix check for menu entry type for copy to clipboard not working on friend messages

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
Provides the option to swap Enter with Enter-corrupted when entering The Gauntlet.
=> Added menu entry swapper option for entering the corrupted gauntlet.

runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldHopperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldHopperPlugin.java
Simple change of the `showSidebar` option name from 'Show world hopper sidebar' to 'Show world switcher sidebar' to match the the actual World Switcher icon on the sidebar.
Closes #6777
=> Change `showSidebar` option name to 'Show world switcher sidebar' to match sidebar icon label

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
Adds seeds taken from seed packs into loot tracker
Closes #10604
KC is tracked as per 'take' action so a single seed pack could have 6-10 entries each. If multiple seeds are taken in the same tick then the kc will not be correct, but loot will be properly tracked still. Since I would assume most people only care about profits I don't think these issues are a problem.
=> Added seed packs to loot tracker

runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
Re-do of #10638 because I'm an idiot. Last time I *promise*.
Adds a config option for the existing Ctrl+F11 hotkey which hides the sidebar entirely.
Adds a new configurable hotkey that toggles the current/last open plugin panel (defaults to Ctrl+F12).
Both configs are at the bottom of the Runelite config panel.
=> Sidebar toggle hotkey changes

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/config/HighlightTier.java
Closes #9241
Closes #10961
Highlighted items should serve a specific purpose imo: for items you're specifically looking for. With `Highlight > value`, it turned the Highlighted items into another value tier, with the only difference between it and the low->insane values was that it provided notifications.
With the recent change to how the tiers are ordered, and the confusion around it, there seems to be a big desire for notifications by an item's value (a fixed version of the old functionality)
=> ground items: remove Highlight > value, add Notify >= Tier

runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
Closes #11362 
Adds a check to see whether or not you are in the Gauntlet prior to taking a screenshot of an untradeable drop due to spamming of the screenshot directory.
=> Screenshot: Block Untradeable Drops within the Gauntlets

runelite-api/src/main/java/net/runelite/api/IconID.java, runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java, runelite-client/src/test/java/net/runelite/client/menus/MenuManagerTest.java
A player in the wilderness of a bounty hunter world with a bounty hunter
emblem in their inventory will have their name decorated in the player
menu with an emblem icon and the tier of emblem they are carrying. Before
removing any tags, that name will look like this:
<col=ffffff>bfmoatbio<img=20>10<col=00ff>  (level-126)
where "<img=20>10" represents the emblem icon (<img=20>) and tier (10).
removeTags will remove the icon tag but leave the emblem tier, resulting
in an incorrect username returned by getMenuTarget (in the case of the
example, bfmoatbio10).
Before calling removeTags on a player menu target, perform a special
remove of the bounty hunter emblem icon and its tier, if present.
Closes #11440
=> Remove bounty hunter emblem tier from player name for lookup

runelite-api/src/main/java/net/runelite/api/Client.java, runelite-client/src/main/java/net/runelite/client/plugins/interfacestyles/InterfaceStylesConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/interfacestyles/InterfaceStylesPlugin.java
When playing with stretched mode on the right click menu can take up a lot of space.
This works on both the normal and 2010 menu.
Normal:
2010:
Both gifs are with 50% transparency.
Depends on !113
Closes #10501
=> Add support for transparent right-click menu 

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
From today's OSRS update:
> [The elite clue that requires a player to kill a green dragon will now accept a brutal green dragon.](https://secure.runescape.com/m=news/a=13/vanguard-improvements?oldschool=1)
=> clues: add brutal green dragon variant to cryptic clue

runelite-client/src/main/java/net/runelite/client/ui/overlay/components/BackgroundComponent.java
Instead of fixed color offsets for outer and inner border colors switch
to multiplicative offsets. This also makes overlay color alpha
recoloring work properly with background component border.
=> Use multiplicative color offsets for BackgroundComponent border

runelite-client/src/main/java/net/runelite/client/plugins/metronome/MetronomePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/metronome/MetronomePluginConfiguration.java
Closes #10347. Without setting and resetting the client sound effect volume as implemented, the sound effect is only played at the configured volume when sound effects are muted in-game.
=> metronome: add independent volume configuration

runelite-client/src/main/java/net/runelite/client/plugins/screenmarkers/ScreenMarkerMouseListener.java, runelite-client/src/main/java/net/runelite/client/plugins/screenmarkers/ScreenMarkerPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/screenmarkers/ScreenMarkerWidgetHighlightOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/screenmarkers/ui/ScreenMarkerPluginPanel.java
Gives you the ability to put the screen marker around a widget by clicking on the said widget.
Supersedes/Closes #3952
=> screenmarker: add ability to put screen markers around widgets

runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java
This fixes an issue where the tab would reactivate if you clicked the active tab while the withdraw-x dialog was open. This was caused by the handling for withdraw-x, which activates the tab again a tick after the withdraw-x dialog is closed.
=> bank tags: clear remembered search when the active tag tab is clicked

runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsPlugin.java
Closes #11665 
I have added a checkbox in the Boosts Information plugin to enable/disable notification sending. A value of 0 will still disable notification.
=> Add checkbox for allowing notification sending for boosted stats.

runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/chatfilter/ChatFilterPluginTest.java
A few things to note:
1. I decided to use a cache for keeping count of the messages
- This allows it to count more than just the chat buffer length, so if you are logged in for many hours, message counts can go into the hundreds or thousands with no problem
- This also prevents modification of the chat buffer itself, so it will retain all of the chat history. This means if the plugin is turned off after consolidating the chats, the chat will go back to normal
- To prevent this cache from growing unbounded, I added a configurable max size. I defaulted to 500, however this is left up to the user. This size corresponds to unique messages, not total messages.
2. Public chat consolidation is configurable
- Only the "spammy" message types are consolidated by default: ENGINE, GAMEMESSAGE, …
=> Add duplicate chat options to chatfilter

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
Amazingly none of the various util libraries we pull in have a "startsWithVowel" method or anything of the like.
=> loot tracker: Use "an" prefix for monster names starting with vowels

runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPluginConfig.java
Closes #11387
Adding a warning should hopefully make it more clear to users what this feature requires, and that they need to restart the plugin.
The plugin being able to restart itself would be better, but until then this should help.
=> gpu: add warning message to compute shaders option

runelite-client/src/main/java/net/runelite/client/game/ItemManager.java, runelite-client/src/main/java/net/runelite/client/plugins/examine/ExaminePlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/itemprices/ItemPricesOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/examine/ExaminePluginTest.java
This ensures returned item prices are accurate even for noted item IDs. (This fixes a bug in the recently-added [NPC and PVP kill chat message feature](https://github.com/runelite/runelite/pull/10035))
Closes #11616
=> Canonicalize ItemManager price lookup IDs

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPanel.java
Loot tracker panel now attempts to push the related group box to the top of the panel upon obtaining a drop
Closes #8519
=> Float loot tracker groups to top of list when obtaining drop

runelite-client/src/main/java/net/runelite/client/plugins/keyremapping/KeyRemappingConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/keyremapping/KeyRemappingListener.java
Hi I wanted to be able to remap space in the KeyMapping plugin when you are talking to NPCs. So I added this as an option in the KeyMapping plugin. Also added an option for remapping shift for dropping items. I did this because I am using a splitted keyboard and my space button is actually on the right side of the keyboard which makes it awkward to hold in space whilst talking to NPCs.
=> KeyRemapping: Add space as an option to remap.

runelite-client/src/main/java/net/runelite/client/plugins/itemprices/ItemPricesConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/itemprices/ItemPricesOverlay.java
Closes #11172 
If the "Show prices while alching" option is enabled, the tooltip will always show while alching.
Works the same as the picture in the issue: https://i.imgur.com/DXKtwNn.png
=> item prices: always show tooltip when alching if option is enabled

runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/SkillCalculator.java, runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/UICalculatorInputArea.java
Skill calculator changes to improve formatting of numbers and to include the required amount of experience between current xp and target xp.
=> Skill calculator change to show needed xp and xp number formatting

runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaOverlay.java
This allows you to hide the overlay entirely while NPCs are aggressive, e.g. if you are slaying.
=> npcunaggroarea: split color config depending on timer status

runelite-api/src/main/java/net/runelite/api/VarPlayer.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java
steps to reproduce:
start a raid on account 1
scout another raid in the same world on account 2
leave the raid on account 1 and it will not reset correctly
Also, this case did not happen consistently because in order to happen the raid party varp had to get set before the first game tick after you loaded outside of the raid. This seemed pretty random so ti was hard to test but the bug never happened after testing for like 10 mins on this branch so it is probably fine.
clip of bug happening which is how we knew how to reproduce the bug https://clips.twitch.tv/ResoluteElegantDolphinYouDontSay
=> raid plugin: fix plugin not reseting in niche case

runelite-api/src/main/java/net/runelite/api/MenuAction.java, runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsPlugin.java, runelite-client/src/test/java/net/runelite/client/menus/MenuManagerTest.java
Fixes #11448 which appeared because of https://github.com/runelite/runelite/commit/087b2ac9695778464962f6d28b02db7c2e3ae9cd. The issue is that custom menu entries of type RUNELITE are decorated even if they aren't related to a player.
To fix the issue, the MenuAction.RUNELITE menu type is split into RUNELITE and RUNELITE_PLAYER. With RUNELITE_PLAYER being assigned to player options only, the Player Indicators plugin should no longer try to decorate general menu entries such as Edit-tags, and also not the right-click Lookup in chat or other menu entries that aren't player options.
Why this issue wasn't observed before https://github.com/runelite/runelite/commit/087b2ac9695778464962f6d28b02db7c2e3ae9cd: 
The plugin was changed in that commit to use the ClientTick event instead of …
=> player-indicators: don't decorate non-player custom menu options

runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java
The update moved the infobox down the widget tree so the widgetid of the raids points infobox changed
=> api: fix raids points infobox widget id

runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsConfig.java
Clarify & remove typo from the tooltip for "Boost amount threshold"
=> Clarify Boosts Information Tooltip

runelite-client/src/main/java/net/runelite/client/plugins/chathistory/ChatHistoryPlugin.java
closes #11730
The cleanup commit in the previous PR accidentally switched `.contains` to `.equals`
=> chat-history: fix plugin not clearing history

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java
Prevent duplicate quantities in Ground Item Notifications
This resolves #10319 
- The `" x {quantity}"` part of the string was removed, because the `"({quantity})"` style is what is used for text on items on the ground, so this aligns with that style.
- Closing `!` was also removed, because it looked a little odd in the notification text (Also duplicated in the `Lots!` case) - I'm fine with whatever consensus or general preference is here
=> Remove duplicate Item Count in GroundItem notifs

runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcMinimapOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcSceneOverlay.java
Add a toggle to the NPC indicators plugin that stops NPCs being highlighted if they're dead. Notably, doesn't work until the NPC is actually dead (works post-projectile).
[Video example of plugin in action.](https://streamable.com/34ts1j)
=> Make highlighting dead NPCs optional in the NPC indicators plugin.

runelite-api/src/main/java/net/runelite/api/AnimationID.java, runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
Closes #11575
There are 2 animations for each pearl rod (except Oily). Usually it
seems that only one is used when actually fishing, which were the ones
present before this commit. However, it seems that Jagex is not
consistent about what animations are used, as Anglerfish fishing uses
the other animation of the normal pearl rod. Given that the other two
exist, and they're technically usable (and can be used as the starting
animation), it's only a matter of time before Jagex accidentally gets
them the wrong way round again, so this is a pre-emptive measure. It
also means that the UI won't show "Not Fishing" for a split second when
casting out.
=> Add all other pearl rod animations

runelite-client/src/main/java/net/runelite/client/plugins/config/PluginListPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java, runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePlugin.java, runelite-client/src/main/java/net/runelite/client/ui/components/IconTextField.java
Fixes #11417
Supersedes/Closes #11507
This is intended to make the tags feature more discoverable, as people keep requesting "plugin categories". Putting plugins into a singular category that will make sense for most users is impossible, as many plugins will can logically be placed into multiple categories.
The Category Tag list is intended to be a short, curated, list of tags that are helpful to a user trying to find plugins.
The icon for this list only shows up when the input is empty, otherwise it shows the existing `x` clear button.
=> Plugin tag discoverability

runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
Uses JFrames builtin setOpacity method to set window opacity. Requires  the frame to be undecorated and thus requires the custom window chrome option to be enabled.
Adds a new config entry to the RuneLite config group.
The opacity is limited from 10-100% as anything below 10% would make it near impossible to change it back.
Only tested on Windows, but the implementation avoids setting the window opacity if it is not supported by the system.
Screenshots:
100% opacity
75% opacity
10% opacity
=> ClientUI: Add support for changing window opacity.

runelite-client/src/main/java/net/runelite/client/plugins/keyremapping/KeyRemappingListener.java
Fixes #11578 
This PR makes it so that when keys are remapped and pressed. They still fire the unmapped key press when the chatbox is not focused.
This allows players to "pre-press" menu options by holding them down before the menu is opened.
=> Add a check for if chat is focused to consume key typed events

runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/screenshot/ScreenshotPluginTest.java
Closes #5353. See my original post, since I make references to it here.
I wrote an example solution that applies Option 2 to exception #*1*, #*2* and #*5*, Option 2a to exception #*4*, and Option 1 on the other exceptions. This means there are 2 constants and 4 if blocks worth of extra code from the base solution. When I talk simplicity vs accuracy, I made the file 2 constants and 4 if blocks less simple to make 18 names more accurate, but that begs the question: was that effort worth implementing? I chose these exceptions as a proof of concept of what "extra" code means, and they seemed the most simple to handle. (Some exceptions, using option 2, would use ~~dicts~~ maps, which hinders simplicity quite a bit; I wouldn't prefer to use maps.)
=> screenshot: fix method for naming quest complete screenshots

runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPlugin.java
Add highlighting  for spell casting and use-item menu entries in the NPC indicators plugin. Useful in conjunction with #11567 for barraging stacked NPCs, and just in general for keeping the highlighting consistent.
=> Add additional NPC indicator menu-entry highlights.

runelite-client/src/main/java/net/runelite/client/plugins/PluginManager.java
If you had an external plugin with a PluginDependency on a core plugin
the core plugin would be included in the external `loadPlugins`
dependency graph, which would make it be instantiated twice. Since
external plugins can't depend on other external plugins, and core
plugins are guaranteed to be loaded first with no external dependencies,
we can just exclude dependency edges for nodes outside of the current
load list.
=> PluginManager: don't duplicate dependency plugins if they already exist

runelite-client/src/main/java/net/runelite/client/plugins/antidrag/AntiDragConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/antidrag/AntiDragPlugin.java
Currently you need to enable shift-antidrag globally to use the plugin in PvP at all.
This PR instead makes it so shift is still required in PvP, but it is always enabled regardless of the PvM setting.
=> antidrag: Enable shift-antidrag in PvP regardless of onShiftOnly config

runelite-client/src/main/java/net/runelite/client/plugins/metronome/MetronomePlugin.java
When the metronome is set to a high tick count and toggled off, the counter is left paused. When the plugin is resumed, the metronome will 'tick' after the remaining number of game ticks. 
This change resets the counter when it is toggled back on to allow the full # of game ticks set before another 'tick'.
=> Reset metronome tick count when toggled on.

runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodePlugin.java
When standing in front of Mercy on the upper level of MLM, the vein overlay switches from the upper level to the lower level due to the player's tile height being less than -500.
I've adjusted UPPER_FLOOR_HEIGHT to accommodate for this.
I also tested every other tile on the upper level and only the one directly in front of Mercy has this issue.
=> Fix MLM vein overlay not displaying on upper level

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/AnagramClue.java
Closes #11827
Updated to the exact position of Lumbridge guide, found here with ::renderself off:
=> Update Lumbridge guide's position for anagram clue

runelite-client/src/main/java/net/runelite/client/config/ChatColorConfig.java, runelite-client/src/main/java/net/runelite/client/config/ConfigDescriptor.java, runelite-client/src/main/java/net/runelite/client/config/ConfigItemDescriptor.java, runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java, runelite-client/src/main/java/net/runelite/client/config/ConfigObject.java, runelite-client/src/main/java/net/runelite/client/config/ConfigSection.java, runelite-client/src/main/java/net/runelite/client/config/ConfigSectionDescriptor.java, runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/implings/ImplingsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargeConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/itemidentification/ItemIdentificationConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/keyremapping/KeyRemappingConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/randomevents/RandomEventConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerConfig.java
Closes #11602
Certain configs have always been begging for some form of section system. When merging multiple plugins together, being able to separate their options would be very useful.
Sections can be toggled by clicking anywhere on them, and are persisted through the config. It is possible to nest configs inside one another. Each level of nesting adds a small but noticeable margin on the left side.
I have added sections to Chat Color (which desperately needed it) to show users that there are 2 sets of options, and to Ground Items to hide potentially gigantic item lists.
Feedback on the design of the sections is very much appreciated
(Above gif is outdated, as the text is now RL orange. See comments below)
=> Add Config Sections

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
Closes #11114 .
Seeing as this is something only one individual seems to come across, it's very hard to test whether or not this FULLY works to resolve the duplicate problem, though I don't believe this additional check is going to hurt any.
Logistics behind the reasoning on why this should fix it:
- CoX and ToB are the only two chest-related tracking events that get scanned through, currently.
- CoX and ToB are both 'Instanced Regions'
- Whenever you leave CoX or ToB, you are no longer in an instanced region and it should flag the loading gamestate event, which is what the prior check solely relied on to reset the chestLooted variable.
I doubt you anyone _should_ be able to get a duplicate entry past this.. but.. here this is.
I HAVE tested that it works in CoX by doing a completion and …
=> Loot Tracker: Removes CoX Duplicate Tracking Events

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatOverlay.java
Fixes #11563
This also fixes the unintended feature where hovering over a bank tab with an item set as its image would display the item stats.
Before:
After:
=> item stats overlay - Limit bank widgets to item containers

runelite-client/src/main/java/net/runelite/client/plugins/chatnotifications/ChatNotificationsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/chatnotifications/ChatNotificationsPlugin.java, runelite-client/src/main/java/net/runelite/client/plugins/emojis/EmojiPlugin.java, runelite-client/src/main/java/net/runelite/client/util/Text.java, runelite-client/src/test/java/net/runelite/client/util/TextTest.java
Adds a chat notification option for Jagex broadcasts. 
There are times when you might not be paying attention to your client and/or chat, and Jagex sends out a broadcast. This ensures you don't miss any potentially important information, official Twitch streams, etc.
=> chat: Add chat notification for Jagex broadcast

runelite-client/src/main/resources/net/runelite/client/plugins/gpu/priority_render.glsl
Putting this if statement behind `localId < size` causes major visual
glitches with the Mesa graphics driver.
=> gpu: fix major visual glitches on linux

runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/chatfilter/ChatFilterPluginTest.java
Chat filter plugin was not collapsing messages that included any formating like colors.
Fixes #11734
=> chatfilter: fix colored messages not being collapsed

runelite-client/src/main/java/net/runelite/client/plugins/driftnet/DriftNet.java, runelite-client/src/main/java/net/runelite/client/plugins/driftnet/DriftNetConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/driftnet/DriftNetOverlay.java, runelite-client/src/main/java/net/runelite/client/plugins/driftnet/DriftNetPlugin.java
Changes to drift net plugin:
- Only untag fish shoal when tick timeout reached or fish shoal is adjacent to a drift net that is not catching fish (= full or unset). 
You can still sometimes have a shoal that is shown as tagged while it is actually not, this rarely happens so I'm not able to determine how this happens. After the tick timeout it will still become untagged.
- Add option to highlight Annette when no more drift nets are left in inventory.
I don't have a lot of experience with Java so any feedback is appreciated!
=> Improve drift net plugin

runelite-client/src/main/java/net/runelite/client/game/LootManager.java, runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
This commit makes it so LootTracker tracks items that fall on the floor during an inventory-based loot. This works because ItemSpawned/ItemQuantityChanged events happen before ItemContainerChanged events.
It keeps a running track of items that spawned directly below the player during the current tick, and if that is in the same tick as as an inventory change that correlates to (e.g.) a chest or seed pack event, we include the ground items as part of the loot. I've tested this fairly extensively for crystal chests, with good results.
The shades part is relatively straightforward, and uses the object IDs. The only tricky thing is that unlike seed packs, just clicking "Open" is not sufficient – you need to also have a key in your inventory. The game gives you a message if you fail to have a …
=> LootTracker support for shade chests; support ground items

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/loottracker/LootTrackerPluginTest.java
This time leveraging InventorySnapshot, lot less changes required and now benefiting from the recent merge into LootTracker of picking up potential grounditems. I did add an additional check to ensure players inventory has 28 items before trying to grab ground spawns.
=> LootTracker update for Coffins in Hallowed Sepulchre

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/SkillChallengeClue.java
When the text was updated back in https://github.com/RuneLite/RuneLite/commit/78164374c3b358c2d948740e7a54d51a45b42f4f, the author didn't update the overlay hint text to mention that it needed to be in the Slayer Tower.
=> clues: add mention that nechryael has to be in the slayer tower

runelite-client/src/main/java/net/runelite/client/plugins/mousehighlight/MouseHighlightConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/mousehighlight/MouseHighlightOverlay.java
Closes #8634
Adding a config option to disable spell book tooltips.
=> Add toggle to remove spellbook tooltips

runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityConfig.java
Part of the Agility config list is currently mislabeled, resulting in the settings displaying in an incorrect order:
Fixed:
=> agility: Fix config order

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java, runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerConfig.java
Closes #11766 
Adds a toggle that, when enabled, moves skills to the top of the xp tracker if xp has been earned.
=> xp tracker: add option to sort skills by most recently gained xp

runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargePlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/itemcharges/ItemChargePluginTest.java
Closes #11822
Updated the regex for amulet of chemistry to update the amulet's charge count when creating less than 4-dose potions
=> item charges: update amulet of chemistry charges when creating less than 4-dose potions

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/chatcommands/ChatCommandsPluginTest.java
This will fix the bug where if you get a pb with 24+ players as the team size it did not count is a new pb.
Also adds the ability for cox pb tracking to check if a pb mentioned in the raid end message is better than the one saved in config.
=> Fix the 24+ player team size bug for cox pb and allow for pb times from raid end message

runelite-client/src/main/java/net/runelite/client/plugins/friendschat/FriendsChatConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/friendschat/FriendsChatPlugin.java
Adds a new config option to the clan chat plugin. 
Allows the user to set the tick delay before a Join/Leave message is removed. 
Setting the delay to 0 stops the messages from being removed. 
closes [#11703](https://github.com/runelite/runelite/issues/11703)
=> Add timeout config option to clanchat join/leave message dissappearing.

runelite-client/src/main/java/net/runelite/client/ui/overlay/components/TextComponent.java
This commit prevents fonts with thin and angled glyphs from having gaps
between the characters and their outline by offsetting outline draws in
one direction exclusively.
=> TextComponent: Draw outline using one axis offset at a time

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
This commit ensures the previously-active plugin panel can be reopened
with the plugin panel toggle hotkey after being closed via mouse click.
Fixes #11886
=> ClientUI: Fix panel toggle after closing with click

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/AnagramClue.java
Apparently Jagex changed this at some point. See: https://clips.twitch.tv/LitigiousImpartialCoffeeJonCarnage
=> AnagramClue: Fix Cam the Camel elite step text

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
I'm not sure why this wasn't included with the rest of them, but this is confusing and should be the same for both the sidebar and plugin panel toggles
=> ClientUI: Allow hotkey plugin panel toggles on login screen

runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPlugin.java
Closes #11961
Adding config option to have the "Tag" or "Untag" option to instead modify the "Npcs To Highlight" option which allows the tags to persist through restart.
=> Adding config option to persist tags through restart

runelite-client/src/main/java/net/runelite/client/plugins/chatnotifications/ChatNotificationsConfig.java, runelite-client/src/main/java/net/runelite/client/plugins/chatnotifications/ChatNotificationsPlugin.java
In an attempt to curb notification spam during PVM and other activities, this commit changes the behavior of notifyOnOwnName so that it only notifies the user when their name is mentioned in public, private, friendschat, modchat, or modprivatechat rather than every single time their name is mentioned.
Currently, if you want to be notified when someone mentions you by name, you are subject to notification inundation while doing PVM or other activities during which your name is mentioned regularly:
closes #10710
=> chat notification: Apply notifyOnOwnName when player-mentioned only

runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java, runelite-api/src/main/java/net/runelite/api/widgets/WidgetInfo.java, runelite-client/src/main/java/net/runelite/client/ui/overlay/WidgetOverlay.java
Allows the new toggleable health bar widget used for various boss encounters (nightmare, cox) to be moveable.
Closes #12020
=> widget-overlay: make encounter health bar moveable

runelite-client/src/main/java/net/runelite/client/input/KeyManager.java, runelite-client/src/main/java/net/runelite/client/plugins/keyremapping/KeyRemappingListener.java, runelite-client/src/test/java/net/runelite/client/plugins/keyremapping/KeyRemappingListenerTest.java
Closes #12045
Adding change to allow authenticator use with Key Remap Plugin. Currently the functionality is only prevented on the Login Screen and not the authenticator screen as well
=> Key Mapping Plugin and authenticator

runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeItemPanel.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeOfferSlot.java, runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangePlugin.java
This allows looking up GE prices for items already on offer, without the need to manually search for the item on the Search tab. Accessed via a new popup menu.
I made this PR because I've always wanted a way to lookup prices for an item in the Offers tab to see if prices have changed since I made the offer.
=> Add GE links to the offers panel

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java, runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java
Prior to this commit it was possible to receive a change or update in
task by playing on mobile or another client, log back in to RuneLite
with incorrect task information saved to config and, once updated via
checking a slayer gem or speaking with a slayer master, having a task
amount greater than the saved initial task length. This updates the
plugin to use the greater of these numbers so that case is no longer
possible.
Closes #11945
=> slayer: Update initial amount if current amount is higher

runelite-client/src/main/java/net/runelite/client/input/KeyListener.java, runelite-client/src/main/java/net/runelite/client/input/KeyManager.java, runelite-client/src/main/java/net/runelite/client/plugins/loginscreen/LoginScreenPlugin.java, runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java, runelite-client/src/main/java/net/runelite/client/util/HotkeyListener.java
This commit moves login screen handling out of the KeyManager into the
KeyListener interface so it does not need any knowledge of
HotkeyListener's implementation.
=> KeyListener: Add isEnabledOnLoginScreen() method

runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java
Selecting #FFFFFF as a prayer color yields an RGB value of -1. Since all
values will be negative numbers, 0 should be used as an "unset" value
instead.
=> xpdrops: Fix white xp drop text recolors

runelite-client/src/main/java/net/runelite/client/ui/components/ThinProgressBar.java
Closes #8262
The color of the green progress bar in the farming tab, for instance, has too little contrast between the "filled" and "unfilled" parts of the progress bar.
Currently the contrasts are 1.86:1 (measured with [this tool](https://webaim.org/resources/contrastchecker/)) and the [accessibility guidelines](https://www.w3.org/TR/WCAG20/) for the web require a contrast ratio of 3:1 or 4.5:1 depending on the content
I think the background of the unfinished portion of the bar should be a darker color.
Preview here (before and after): 
Adding another `darker()` would make it look like this, which IMO is too dark. 👇
=> Change thin progress bar to have darker background for the unfinished portion

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
`!kc ape atoll agility` already works as is, this just adds a couple shorthand options.
Closes #12096
=> chat commands: add ape atoll agility to longBossName

runelite-client/src/main/java/net/runelite/client/game/chatbox/ChatboxItemSearch.java, runelite-client/src/main/java/net/runelite/client/game/chatbox/ChatboxPanelManager.java, runelite-client/src/main/java/net/runelite/client/game/chatbox/ChatboxTextInput.java, runelite-client/src/main/java/net/runelite/client/game/chatbox/ChatboxTextMenuInput.java, runelite-client/src/main/java/net/runelite/client/plugins/wiki/WikiSearchChatboxTextInput.java
Closes #11996 
KeyRemapping has this check too, and [proc,keypress_permit] has similar, though not identical one.
=> rl-client: Prevent chat inputs from taking keys from the worldmap search

runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterConfig.java
The chat filter config can get pretty unruly if you have a lot of word and regex filters. This adds a config section akin to the `Item Lists` section in `Ground Items`.  `Filter type` config is shifted down to be with the rest of the configs.
=> ChatFilter: Add config section for Filter Lists

runelite-client/src/main/java/net/runelite/client/Notifier.java
Moved the input/timer check to the start of the processFlash method.
=> Fix 20ms flash when screen flash notification ends between two flashes

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/TransportationPointLocation.java
Adds new canoe location in Ferox Enclave to world map
=> worldmap: Add Ferox Enclave canoe location
