runelite-client/src/main/java/net/runelite/client/plugins/party/PartyPlugin.java

If user is in party request party data syncup on party plugin startup

Request party sync on party plugin startup

---

runelite-client/src/main/java/net/runelite/client/plugins/party/PartyPlugin.java

Play party ping sound only when ping is in scene

---

runelite-api/src/main/java/net/runelite/api/AnimationID.java
runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java

added animation id for crafting amethyst to Animation list and Idle Notifier plugin.
close #7709

Added Amethyst to Idle Notifier plugin

---

runelite-client/src/main/java/net/runelite/client/plugins/slayer/Task.java

Changed Flesh crawler task name

---

runelite-client/src/main/java/net/runelite/client/plugins/party/PartyPlugin.java
runelite-client/src/main/java/net/runelite/client/util/ColorUtil.java

Use HSB instead of RGBA to generate color from object

---

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_prayer.json

Polls passed recently to increase the experience from the 3 new bones by 20 exp each. This will likely get implemented this week.
:shirtrl:

Update bone exp in Prayer calculator based on passed poll options

---

runelite-client/src/main/java/net/runelite/client/plugins/barrows/BarrowsOverlay.java

Use correct player dot color in barrows plugin

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/AnagramClue.java

Fix anagram clue "A Basic Anti Pot"

---

runelite-api/src/main/java/net/runelite/api/NPCComposition.java
runelite-client/src/main/java/net/runelite/client/plugins/barrows/BarrowsOverlay.java
runescape-api/src/main/java/net/runelite/rs/api/RSNPCComposition.java

Fixes spelling Visable -> Visible

fix spelling Visable -> Visible

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java

Adds a missing hard cryptic clue to the clue scrolls plugin

Add kebos swamp cryptic clue

---

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/RareTreeLocation.java

World Map: Fix Ape Atoll tree type

---

runelite-client/src/main/java/net/runelite/client/ui/components/ProgressBar.java

dulling removed to prevent difficult to see markers

---

http-api/src/main/java/net/runelite/http/api/ws/messages/party/Join.java
http-api/src/main/java/net/runelite/http/api/ws/messages/party/UserJoin.java
http-api/src/main/java/net/runelite/http/api/ws/messages/party/UserPart.java
http-api/src/main/java/net/runelite/http/api/ws/messages/party/UserSync.java
protocol-api/src/main/java/net/runelite/protocol/api/handshake/LoginHandshakePacket.java
protocol-api/src/main/java/net/runelite/protocol/api/handshake/UpdateHandshakePacket.java
runelite-client/src/main/java/net/runelite/client/events/ChatboxInput.java
runelite-client/src/main/java/net/runelite/client/events/PrivateMessageInput.java
runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordUserInfo.java
runelite-client/src/main/java/net/runelite/client/plugins/party/messages/LocationUpdate.java
runelite-client/src/main/java/net/runelite/client/plugins/party/messages/TilePing.java

Add EqualsAndHashCode to Lombok data/value that do not extend Object

---

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

Use ItemVariations when using Reset option for shift-click

---

http-service/src/main/java/net/runelite/http/service/xp/XpMapper.java

Fix unmapped target property "time" warning

---

http-api/src/main/java/net/runelite/http/api/ge/GrandExchangeClient.java
http-api/src/main/java/net/runelite/http/api/ge/GrandExchangeTrade.java
http-api/src/main/java/net/runelite/http/api/osbuddy/OSBGrandExchangeClient.java
http-api/src/main/java/net/runelite/http/api/osbuddy/OSBGrandExchangeResult.java
http-service/src/main/java/net/runelite/http/service/ge/GrandExchangeController.java
http-service/src/main/java/net/runelite/http/service/ge/GrandExchangeService.java
http-service/src/main/java/net/runelite/http/service/ge/TradeAction.java
http-service/src/main/java/net/runelite/http/service/ge/TradeEntry.java
http-service/src/main/java/net/runelite/http/service/osbuddy/OSBGrandExchangeController.java
http-service/src/main/java/net/runelite/http/service/osbuddy/OSBGrandExchangeService.java
runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangePlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/SavedOffer.java

Add GE history tracker

---

http-service/src/main/java/net/runelite/http/service/loottracker/LootTrackerController.java
http-service/src/main/java/net/runelite/http/service/loottracker/LootTrackerService.java

Add offset to loot tracker API

---

http-api/src/main/java/net/runelite/http/api/loottracker/LootRecord.java
http-service/src/main/java/net/runelite/http/service/loottracker/LootTrackerService.java
runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java

loottracker service: include time in loot record

---

runelite-api/src/main/java/net/runelite/api/Client.java
runelite-client/src/main/java/net/runelite/client/game/ItemManager.java
runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
runescape-api/src/main/java/net/runelite/rs/api/RSClient.java

Reset item composition cache on menu shift-click change

---

runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java

screenshot plugin: Add Challenge Mode raid support

---

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java

Normalize CoX CM naming from boss log and chat message

---

runelite-client/src/main/java/net/runelite/client/plugins/tileindicators/TileIndicatorsConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/tileindicators/TileIndicatorsOverlay.java

Make color of hovered tile highlight configurable

---

runelite-client/src/main/java/net/runelite/client/plugins/party/PartyStatsOverlay.java

- Remove invisible border
- Add standard gap

Make party stats overlay consistent with other overlays

---

runelite-client/src/main/java/net/runelite/client/game/chatbox/ChatboxTextInput.java
runelite-client/src/main/java/net/runelite/client/plugins/wiki/WikiSearchChatboxTextInput.java

Closes #7175
By default it wraps infinite lines. A max number of lines can be set with the `limit` method.

ChatboxTextInput: add text wrapping

---

runelite-api/src/main/java/net/runelite/api/coords/WorldPoint.java
runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerPlugin.java

api: add method to find instanced tiles in the scene

---

runelite-client/src/main/java/net/runelite/client/plugins/objectindicators/ObjectIndicatorsOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/objectindicators/ObjectIndicatorsPlugin.java

Add decorations to object marker plugin

---

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/RareTreeLocation.java

Wanted to test out building and contributing. The yew tree location in Rimmington changed because of the update where Veos moved again :)

Update Rimmington yew tree location after Veos moved

---

runelite-client/src/main/java/net/runelite/client/plugins/screenmarkers/ScreenMarkerRenderable.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/components/ImageComponent.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/components/InfoBoxComponent.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/components/LayoutableRenderableEntity.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/components/LineComponent.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/components/PanelComponent.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/components/ProgressBarComponent.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/components/TitleComponent.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBoxOverlay.java

Add .getBounds() to LayoutableRenderableEntity

---

runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordPlugin.java

Check for area update on Discord plugin startup

---

runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java

Already bound at https://github.com/runelite/runelite/blob/c379e631d521d23eac45de69e249d334ce8974ae/runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java#L1141

gpu: Remove unnecessary texture bind

---

runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java
runelite-client/src/main/java/net/runelite/client/plugins/wiki/WikiPlugin.java

wiki plugin: Add skill guide lookup

---

runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargeConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargeInfobox.java
runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargeOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargePlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemWithSlot.java
runelite-client/src/test/java/net/runelite/client/plugins/itemcharges/ItemChargePluginTest.java

Closes #1318
Closes #2911
Closes #7008

Add infoboxes to item charges plugin

---

runelite-client/src/main/java/net/runelite/client/plugins/itemprices/ItemPricesConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/itemprices/ItemPricesOverlay.java

An implementation of [7913](https://github.com/runelite/runelite/issues/7913),
Closes #7913

Add the option to show the profit/loss of High Alchemy on items 

---

runelite-api/src/main/java/net/runelite/api/widgets/WidgetType.java
runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java

Widget loops refactor external

---

runelite-client/src/main/java/net/runelite/client/ui/overlay/components/InfoBoxComponent.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBoxOverlay.java

Do not try to draw infobox caption if text is null or empty

---

runelite-api/src/main/java/net/runelite/api/AnimationID.java
runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java

Closes #7975 
Added property with specified animation value '931' to 'AnimationID' and added it to the case statement in 'IdleNotifierPlugin'

Fixes #7975 - Adding enchanting jewelry to the idle notification plugin.

---

runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/KourendLibraryOverlay.java

It is sometimes hard to tell if you already have the book in your inventory that the library customer asks for, to simply change the color of the tile under the NPC from WHITE to GREEN it would solve this problem.

Added color to the library customer based on player inventory

---

runelite-client/src/main/java/net/runelite/client/plugins/banktags/TagManager.java
runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/MenuIndexes.java
runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java
runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabManager.java
runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TagTab.java

Cleaned up some of the widget code, search code, and rename code from #6855.
Supersedes/closes #6855
Closes #6486

Add right-click rename to Tag Tabs

---

runelite-api/src/main/java/net/runelite/api/Client.java
runelite-api/src/main/java/net/runelite/api/EnumComposition.java
runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
runelite-mixins/src/main/java/net/runelite/mixins/RSEnumMixin.java
runescape-api/src/main/java/net/runelite/rs/api/RSClient.java
runescape-api/src/main/java/net/runelite/rs/api/RSEnum.java

api: add RS Enum API

---

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_farming.json

Add trees added with farming guild and snapegrass/giant seaweed.
Signed-off-by: Will Thomas <github@willthoms.org.uk>

skills calc: add new farmable crops and trees

---

runelite-client/src/main/java/net/runelite/client/plugins/wiki/WikiPlugin.java

Wiki Plugin: Add support for achievement diaries

---

http-api/src/main/java/net/runelite/http/api/item/ItemClient.java
runelite-client/src/main/java/net/runelite/client/game/ItemManager.java
runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatOverlay.java

Closes #7081
Closes #7051 
Closes #7048
Closes #6966
Closes #6975

Convert item stats mapping to use item ids instead of names

---

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_herblore.json

Adds Compost, Bastion and Battlemage potions to the Herblore skill calculator.

Herblore Skill Calculator Additions

---

http-service/src/main/java/net/runelite/http/service/account/AccountService.java

Change logged-in redir to redirect to HTTPS

---

suppressions.xml

Update suppressions.xml dtd link to one that exists

---

runelite-api/src/main/java/net/runelite/api/ChatLineBuffer.java
runelite-api/src/main/java/net/runelite/api/Client.java
runelite-api/src/main/java/net/runelite/api/ScriptID.java
runelite-api/src/main/java/net/runelite/api/events/ClanMemberJoined.java
runelite-api/src/main/java/net/runelite/api/events/ClanMemberLeft.java
runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanActivityType.java
runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanChatConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanChatPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanJoinMessage.java
runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanMemberActivity.java
runelite-client/src/main/java/net/runelite/client/ui/JagexColors.java
runelite-mixins/src/main/java/net/runelite/mixins/RSChatLineBufferMixin.java
runelite-mixins/src/main/java/net/runelite/mixins/RSClanMemberManagerMixin.java
runelite-mixins/src/main/java/net/runelite/mixins/RSClientMixin.java
runelite-mixins/src/main/java/net/runelite/mixins/RSNameableContainerMixin.java
runescape-api/src/main/java/net/runelite/rs/api/RSChatLineBuffer.java
runescape-api/src/main/java/net/runelite/rs/api/RSClanMemberManager.java

clan chat: add temporary join/leave messages

---

runelite-client/src/test/java/net/runelite/client/util/ColorUtilTest.java
runelite-client/src/test/java/net/runelite/client/util/ImageUtilTest.java

Replace assert keyword with JUnit assertX functions.

Replace Java asserts in test code with JUnit asserts.

---

runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/KourendDiaryRequirement.java

Creating the tablet does not require quest completion. Closes #7309.

Remove Monkey Madness I requirement from Kourend Diary.

---

runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanChatPlugin.java

clanchat: Update clan members set on clan chat join/leave events

---

http-service/pom.xml
http-service/src/main/java/net/runelite/http/service/account/AccountService.java
http-service/src/main/java/net/runelite/http/service/cache/CacheController.java
http-service/src/main/java/net/runelite/http/service/config/ConfigController.java
http-service/src/main/java/net/runelite/http/service/examine/ExamineController.java
http-service/src/main/java/net/runelite/http/service/feed/FeedController.java
http-service/src/main/java/net/runelite/http/service/hiscore/HiscoreController.java
http-service/src/main/java/net/runelite/http/service/item/ItemController.java
http-service/src/main/java/net/runelite/http/service/loottracker/LootTrackerController.java
http-service/src/main/java/net/runelite/http/service/osbuddy/OSBGrandExchangeController.java
http-service/src/main/java/net/runelite/http/service/sprite/SpriteController.java
http-service/src/main/java/net/runelite/http/service/worlds/WorldController.java
http-service/src/main/java/net/runelite/http/service/xp/XpTrackerController.java
http-service/src/main/java/net/runelite/http/service/xtea/XteaController.java
http-service/src/main/templates/markdown.hbs
http-service/src/main/templates/operation.hbs
http-service/src/main/templates/security.hbs
http-service/src/main/templates/template.html.hbs

This is alternative method to #7846 
Preview: http://ix.io/1B11
(download and run in browser)

Add Swagger static document generation

---

runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java

TabInterface: remember search when clicking withdraw-x

---

runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcSceneOverlay.java

NpcIndicator no longer displays tags above-head

---

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

Add contract for farming guildmaster to menu entry swapper.

Add contract for farming guildmaster to menu entry swapper

---

http-api/src/main/java/net/runelite/http/api/feed/FeedClient.java
http-api/src/main/java/net/runelite/http/api/hiscore/HiscoreClient.java
http-api/src/main/java/net/runelite/http/api/item/ItemClient.java
http-api/src/main/java/net/runelite/http/api/loottracker/LootTrackerClient.java
http-api/src/main/java/net/runelite/http/api/osbuddy/OSBGrandExchangeClient.java
http-api/src/main/java/net/runelite/http/api/worlds/WorldClient.java
http-service/src/main/java/net/runelite/http/service/feed/blog/BlogService.java
http-service/src/main/java/net/runelite/http/service/feed/osrsnews/OSRSNewsService.java
http-service/src/main/java/net/runelite/http/service/feed/twitter/TwitterService.java
http-service/src/main/java/net/runelite/http/service/item/ItemService.java

changed response.message() to call toString() instead

---

runelite-api/src/main/java/net/runelite/api/Actor.java
runelite-api/src/main/java/net/runelite/api/events/OverheadTextChanged.java
runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterType.java
runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/JagexPrintableCharMatcher.java
runelite-client/src/main/scripts/ChatBuilder.rs2asm
runelite-client/src/main/scripts/ChatSplitBuilder.rs2asm
runelite-client/src/test/java/net/runelite/client/plugins/chatfilter/ChatFilterPluginTest.java
runelite-mixins/src/main/java/net/runelite/mixins/RSActorMixin.java
runescape-api/src/main/java/net/runelite/rs/api/RSActor.java

Add a plugin that censors user-defined words/sentences, changes the message, or removes the entire message containing them.
https://i.imgur.com/G47DJE2.gifv
(The overhead is also removed)
Fixes [Ian's request](https://twitter.com/ianspam/status/1058104900121518082)
Fixes #1798
Supersedes #6309
Supersedes #6310

Add Chat filter plugin

---

runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java

Make GPU plugin DPI aware on Java 9+

---

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/chatcommands/ChatCommandsPluginTest.java

Reads from server chat messages and stores herbiboar kc, so herbiboar kc can be shared using !kc herbiboar.
This is my first time contributing to an open source project, so be sure to tell me if there are things I should improve.

Add !kc herbiboar

---

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/TeleportLocationData.java

 Corrected wrong name on world map for Shayzien Teleport

---

runelite-client/src/main/resources/net/runelite/client/plugins/skybox/skybox.txt

skybox: Add Cerberus area

---

runelite-client/src/main/resources/npc_health.json

added karuulm slayer monsters to the npc health list

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java

Change coordinate clue to better describe location

---

runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostIndicator.java
runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/boosts/StatChangeIndicator.java

Change boosts config wording for consistency

---

runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerMinimapOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerPlugin.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayUtil.java

Add option to display ground markers on minimap

---

runelite-client/src/main/java/net/runelite/client/plugins/dailytaskindicators/DailyTasksPlugin.java

Daily task reminders corrected for "Relog" message

---

runelite-client/src/main/java/net/runelite/client/plugins/timestamp/TimestampConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/timestamp/TimestampPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/timestamp/TimestampPluginTest.java

I wanted a config option for seconds, I thought this was better. Added year, month, day simply because I was already making it customize-able not because I thought they were useful. Someone might want that who knows.
EDIT: replaces #6955

Add customizable timestamps

---

runelite-api/src/main/java/net/runelite/api/AnimationID.java
runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java

Idle notifier: Add dragonstone amulet enchanting

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollWorldOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/MusicClue.java

- Fix access levels in existing Clue Scroll plugin code
- Properly use Lombok like we do everywhere else in new music clue code

Cleanup clue scroll plugin (fix access levels and properly use Lombok)

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java

First time contributing. Added all the easy cryptic clues for milestone 1.5.20

clue plugin: Added easy cryptic clues

---

runelite-client/src/main/java/net/runelite/client/plugins/statusbars/StatusBarsOverlay.java

Fix status bar poison background color

---

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/TransportationPoint.java
runelite-client/src/main/java/net/runelite/client/plugins/worldmap/TransportationPointLocation.java
runelite-client/src/main/java/net/runelite/client/plugins/worldmap/WorldMapConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/worldmap/WorldMapPlugin.java

Add tooltips to all Transportation icons

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java

clue plugin: Add new cryptic clues

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CipherClue.java

clue plugin: Add new cipher clues

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java

clue plugin: Add new coordinate clue descriptions

---

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/QuestStartLocation.java

Pirate's treasure quest start location update

---

runelite-client/src/main/java/net/runelite/client/plugins/ammo/AmmoPlugin.java

ammo: fix weapon check

---

runelite-api/src/main/java/net/runelite/api/Client.java
runelite-api/src/main/java/net/runelite/api/HealthBar.java
runelite-api/src/main/java/net/runelite/api/events/PostHealthBar.java
runelite-client/src/main/java/net/runelite/client/plugins/interfacestyles/InterfaceStylesPlugin.java
runelite-mixins/src/main/java/net/runelite/mixins/RSHealthBarMixin.java
runescape-api/src/main/java/net/runelite/rs/api/RSClient.java

interface styles: increase padding of overridden healthbar

---

runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanChatPlugin.java

Do not count local player in nearby clan member counter

---

runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaNotWorkingOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaPlugin.java

npc aggro timer: Add option to hide hint overlay

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java

Add missing 'knows' to Hans beginner clue

---

runelite-client/src/main/java/net/runelite/client/plugins/ammo/AmmoPlugin.java

ammo: fix the infobox not getting removed

---

runelite-client/src/main/java/net/runelite/client/plugins/slayer/Task.java

Fix Mutated Zygomite fungicide weaknes threshold

---

runelite-api/src/main/java/net/runelite/api/Varbits.java
runelite-client/src/main/java/net/runelite/client/plugins/dailytaskindicators/DailyTasksConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/dailytaskindicators/DailyTasksPlugin.java

Added Thirus' daily dynamite from the Kourend diaries to the DailyTasks plugin.
Closes #7462

Added Thirus's Dynamite to the DailyTasks plugin.

---

runelite-api/src/main/java/net/runelite/api/AnimationID.java
runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java

Closes #8630 
- Potter's Wheel
- Pottery Oven

Idle Notifier: Notifications for Pottery Crafting

---

runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPlugin.java

npcindicators: Add option to highlight NPC name in right click menu

---

runelite-client/src/main/java/net/runelite/client/plugins/virtuallevels/VirtualLevelsConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/virtuallevels/VirtualLevelsPlugin.java

Resolves #5878
(Used a mock total level above to show virtual total, I don't have any skills past 99)

Optionally prevent virtual levels from effecting total level

---

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java

slayer: add 'south of' to task regex

---

runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPlugin.java

Reverts runelite/runelite#8673

Revert "npcindicators: Add option to highlight NPC name in right click menu"

---

runelite-client/src/main/java/net/runelite/client/plugins/dailytaskindicators/DailyTasksPlugin.java

I also removed the relog message from the checkStaves method on accident. This can be added back if it is wanted but I got the impression that adam did not want to deal with the relogging stuff.

daily tasks plugin: fix broken if statement

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java

Fix Hot/Cold Misthalin Location Spelling Error

---

runelite-api/src/main/java/net/runelite/api/AnimationID.java
runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java

Idlenotifier: Add Plank Make

---

runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingPlugin.java

fishing trawler time left for one tick fixed

---

runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java

Remove Ammo Counter Overlay when Cannon Degrades

---

runelite-api/src/main/java/net/runelite/api/Experience.java
runelite-client/src/main/java/net/runelite/client/plugins/combatlevel/CombatLevelOverlay.java
runelite-client/src/test/java/net/runelite/client/plugins/combatlevel/CombatLevelPluginTest.java

Also move most calculations to the Experience utility class.
Fixes #7411.

Refactor combat level calculations to use closed-form formulas.

---

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_magic.json

skill-calc: Fix incorrect Bones to Peaches xp value

---

runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingWorld.java

timetracking: Update farming patches for the Hosidius rework

---

runelite-client/src/test/java/net/runelite/client/plugins/PluginManagerTest.java

This prevents runtime errors if an erroneously duplicated keyName is
used in a plugin's configuration.

PluginManagerTest: Ensure config keyNames are not duplicated

---

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/TeleportLocationData.java

Update Xeric's Glade teleport location icon on World Map

---

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

Added an option in Menu Entry Swapper for:
-Rionasta's Send-Parcel
-Hardwood Grove's Quick-Pay(100)

Added Hardwood Grove Menu Swap Option

---

runelite-client/src/main/java/net/runelite/client/plugins/musiclist/MusicListPlugin.java

Adds the same searching and filtering options as the QuestListPlugin to the music list.

Added music list plugin to search and filter

---

runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterPlugin.java
runelite-client/src/main/scripts/ChatBuilder.rs2asm
runelite-client/src/main/scripts/ChatSplitBuilder.rs2asm
runelite-client/src/test/java/net/runelite/client/plugins/chatfilter/ChatFilterPluginTest.java

add ability to exclude yourself, friends, or clan members from your filter
closes #8282

chat filter: add options to filter friends and clan members

---

runelite-client/src/main/java/net/runelite/client/ui/overlay/components/ProgressBarComponent.java

Add support for center label to ProgressBarComponent

---

runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/mining/Rock.java
runelite-client/src/main/java/net/runelite/client/plugins/mining/RockRespawn.java

Shows progress indicators for respawn times on all rocks that can be mined.
Closes #3097

client: add mining plugin

---

runelite-client/src/main/java/net/runelite/client/plugins/barbarianassault/BarbarianAssaultPlugin.java

No longer rely on the previously used "icons" to determine the role, instead use the role widget currently loaded. Tested and working https://i.imgur.com/x0JnDsD.png

Fix BA plugin after latest game update.

---

runelite-client/src/main/java/net/runelite/client/plugins/inventorytags/InventoryTagsOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargeOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/itemidentification/ItemIdentificationOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/runepouch/RunepouchOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerOverlay.java
runelite-mixins/src/main/java/net/runelite/mixins/RSWidgetMixin.java

Gif showing it works
Closes #8618

Fix WidgetItemOverlay render position

---

runelite-api/src/main/java/net/runelite/api/Client.java
runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/examine/ExaminePlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/inventorygrid/InventoryGridConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/inventorygrid/InventoryGridOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/inventorygrid/InventoryGridPlugin.java
runelite-mixins/src/main/java/net/runelite/mixins/RSWidgetMixin.java
runescape-api/src/main/java/net/runelite/rs/api/RSClient.java

Fixes #1333
Closes #1774
Closes #4722

Add inventory grid plugin

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java

Add Weiss coordinate clue

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/AnagramClue.java

update anagram clue location

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java

Add additional info to waterbirth coordinate clue

---

runelite-client/src/main/java/net/runelite/client/plugins/mining/Rock.java

Add sandstone and granite to mining plugin

---

runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java
runelite-client/src/main/java/net/runelite/client/plugins/itemidentification/ItemIdentificationOverlay.java

Add ItemIdentification to Seed Box, Looting Bag, and Miscellania collection screen

---

runelite-client/src/main/java/net/runelite/client/plugins/examine/CacheKey.java
runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/keyremapping/KeyRemappingPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/puzzlesolver/solver/PuzzleState.java

These changes do not affect the return result, just removes some redundant if checks

Remove some redundant if statements in the client module

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java

Improve medium clue hint

---

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatOverlay.java

items stats: add option to show weight
resolves #6939

items stats: add option to show weight

---

runelite-client/src/main/java/net/runelite/client/Notifier.java
runelite-client/src/main/java/net/runelite/client/config/FlashNotification.java
runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java

I wanted an even more noticeable notification so added some options to the flash notification:

Additional flash notification options

---

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_crafting.json

Added snakeskin gear to skill calculator

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/FaloTheBardClue.java

FaloTheBardClue:Fix Typos

---

runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcSceneOverlay.java

fix names showing as null in the NPC highlight plugin
fixes #9084

npchighlight: fix names showing as null

---

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

Add Barbarian Assault quick-start option to menu entry swapper

---

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java

Added Larran's chest to loot tracker

---

runelite-client/src/main/java/net/runelite/client/config/ChatColorConfig.java

Change default examine chat color to green

---

http-api/src/main/java/net/runelite/http/api/chat/ChatClient.java
http-service/src/main/java/net/runelite/http/service/chat/ChatController.java
http-service/src/main/java/net/runelite/http/service/chat/ChatService.java
runelite-api/src/main/java/net/runelite/api/Varbits.java
runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java

Add BA high gamble count chat command

---

http-api/src/main/java/net/runelite/http/api/chat/ChatClient.java
http-api/src/main/java/net/runelite/http/api/chat/Duels.java
http-service/src/main/java/net/runelite/http/service/chat/ChatController.java
http-service/src/main/java/net/runelite/http/service/chat/ChatService.java
runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/chatcommands/ChatCommandsPluginTest.java

Fixes #8909
<https://i.imgur.com/ZHfe2oh.png>

duel arena chat command

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java

The previous coordinates used in this clue pointed around the Forthos Ruin

Fix Father Jean's coordinates in easy cryptic clue

---

runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/timers/TimersPluginTest.java

Teleblock timer is not showing after message because of the new message format.
Closes #9257

Teleblock timer not showing fix

---

runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningOverlay.java

mining plugin: only show timers on same level in motherlode mine

---

runelite-api/src/main/java/net/runelite/api/AnimationID.java
runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java
runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java

adds timer for dragonfire shield timer (2 minutes)
closes #9213

Add Dragonfire Shield timer to timers plugin

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java

Fixed typo in watch tower clue

---

runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterPlugin.java

Chat Filter plugin now refreshes chat on config change

---

runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerBarOverlay.java

prayer: fix HD prayer bar flick location

---

runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterPlugin.java

Add option to remove logged in/out messages

---

runelite-api/src/main/java/net/runelite/api/AnimationID.java
runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java

Idle notifications after farming

---

http-service/src/main/java/net/runelite/http/service/config/ConfigService.java
http-service/src/main/java/net/runelite/http/service/hiscore/HiscoreService.java
http-service/src/main/java/net/runelite/http/service/worlds/WorldController.java
http-service/src/test/java/net/runelite/http/service/config/ConfigControllerTest.java
http-service/src/test/java/net/runelite/http/service/loottracker/LootTrackerControllerTest.java
runelite-client/src/main/java/net/runelite/client/RuneLiteModule.java
runelite-client/src/main/java/net/runelite/client/chat/ChatCommandManager.java
runelite-client/src/main/java/net/runelite/client/game/SpriteManager.java
runelite-client/src/main/java/net/runelite/client/game/chatbox/ChatboxTextMenuInput.java
runelite-client/src/main/java/net/runelite/client/plugins/gpu/GLUtil.java
runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeSearchPanel.java
runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/objectindicators/ObjectIndicatorsPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/party/PartyPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTabPanel.java
runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldSwitcherPanel.java
runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpPanel.java
runelite-client/src/main/java/net/runelite/client/util/ExecutorServiceExceptionLogger.java

I just repeated #4605 and found more unused slf4j.

Remove unused Slf4j annotations and imports

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java

Fixed incorrect clue scroll description

---

runelite-api/src/main/java/net/runelite/api/Varbits.java
runelite-client/src/main/java/net/runelite/client/plugins/dailytaskindicators/DailyTasksConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/dailytaskindicators/DailyTasksPlugin.java

Closes runelite/runelite#8581
Closes runelite/runelite#8583

dailytasksplugin: Add Rantz ogre arrow collection notification

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java

hotcoldclue: Display npc location before using device

---

runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java

closes https://github.com/runelite/runelite/issues/1302
Mimics withdraw-x behavior by not closing on scroll clicking

Bank Tags: close chat input like withdraw-x

---

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

Add swap for quick enter[ToB]

---

runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java
runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
runelite-client/src/main/java/net/runelite/client/ui/ContainableFrame.java

runelite-client: Allow partial screen containment again

---

runelite-api/src/main/java/net/runelite/api/Client.java
runelite-client/src/main/java/net/runelite/client/callback/ClientThread.java
runelite-client/src/main/java/net/runelite/client/game/SpriteManager.java
runelite-client/src/main/java/net/runelite/client/plugins/barrows/BarrowsPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/cooking/FermentTimer.java
runelite-client/src/main/java/net/runelite/client/plugins/instancemap/InstanceMapOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/puzzlesolver/PuzzleSolverOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsTimer.java
runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/statusbars/StatusBarsOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/timers/GameIndicator.java
runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java
runelite-client/src/main/java/net/runelite/client/plugins/timers/IndicatorIndicator.java
runelite-client/src/main/java/net/runelite/client/plugins/timers/TimerTimer.java
runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/components/InfoBoxComponent.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBox.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBoxManager.java

runelite-client: Handle startup with an empty cache better

---

runelite-client/src/main/java/net/runelite/client/plugins/mining/Rock.java

Adding Gem rock tracking to the Mining Plugin.

---

runelite-api/src/main/java/net/runelite/api/ScriptID.java
runelite-client/src/main/java/net/runelite/client/plugins/zoom/ControlFunction.java
runelite-client/src/main/java/net/runelite/client/plugins/zoom/ZoomConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/zoom/ZoomPlugin.java
runelite-client/src/main/scripts/ScrollWheelZoomHandler.rs2asm

Fixes #9035 , #5904 
Example:
https://youtu.be/KDI0c3bSvkc

Add Zoom Speed Changer

---

runelite-api/src/main/java/net/runelite/api/ItemComposition.java
runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

Fixed casing in these files
ItemComposition.java
MenuEntrySwapperPlugin.java

Fixes Casing

---

runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerPlugin.java

Why was it even using the CANCEL action before? 🤔

groundmarkerplugin: Use RUNELITE menu action

---

runelite-api/src/main/java/net/runelite/api/Client.java
runelite-client/src/main/java/net/runelite/client/game/ItemManager.java
runelite-client/src/main/java/net/runelite/client/game/chatbox/ChatboxItemSearch.java
runelite-client/src/main/java/net/runelite/client/game/chatbox/ChatboxTextInput.java
runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java

Closes https://github.com/runelite/runelite/issues/6021
Depends on !71
Includes:
* tab + arrow key navigation
* pressing enter selects if you have been navigating with keys

Tag tabs: Add item search for change icon

---

runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/components/TooltipComponent.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/tooltip/TooltipOverlay.java
runelite-client/src/test/java/net/runelite/client/ui/overlay/components/TooltipComponentTest.java

Fix tooltip error handling

---

runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/objectindicators/ObjectIndicatorsPlugin.java

Use "Un-tag" and "Unmark" menu options for tagged NPCs and marked objects/tiles

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java

These being off center can make the solver wrong sometimes. I will try and fix these when I come across them doing clues

hot cold clues: center kandarin outpost dig location

---

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerPlugin.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayManager.java

Add skill tab canvas menu options

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/AnagramClue.java

Add new medium clue step

---

runelite-client/src/main/java/net/runelite/client/plugins/questlist/QuestListPlugin.java

Quest List Plugin: Add not completed filter

---

runelite-client/src/main/java/net/runelite/client/plugins/itemprices/ItemPricesOverlay.java

Show HA profit while casting HA on items

---

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItem.java
runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/grounditems/LootType.java

Co-authored-by: Matthew Smith <matthew.smith813@gmail.com>

grounditems: add despawn timers

---

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java

Prevents any loot from player kills inside Last Man Standing from appearing in the loot tracker
Also fixed a typo in the herbiboar bit

Block LMS player loots from loot tracker

---

http-api/src/main/java/net/runelite/http/api/ws/WebsocketGsonFactory.java
http-api/src/main/java/net/runelite/http/api/ws/messages/party/PartyChatMessage.java
runelite-client/src/main/java/net/runelite/client/RuneLite.java
runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java
runelite-client/src/main/java/net/runelite/client/util/JagexPrintableCharMatcher.java
runelite-client/src/main/java/net/runelite/client/util/Text.java
runelite-client/src/main/java/net/runelite/client/ws/PartyService.java

- Add support for PartyChatMessage
- Add support for sending raids layout message to whole party if user is in party
Closes #7736

Add support for sending raids layout message to party

---

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java

Adds Loot tracker support for the new Gauntlet chest.

Loot Tracker - Add Gauntlet support

---

runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingWorld.java
runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/PatchImplementation.java
runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/Produce.java

~I'm not 100% sure the tickrate is correct, because Jagex says its an \~8 hour crop, but this matches everything else.~
I sat and watched it, its 80 minutes

timetracking: Support Prifddinas patches

---

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/chatcommands/ChatCommandsPluginTest.java

Adds Prifdiinas Agility Course to pb and kc.
Not sure  if 'kill count' is correct here since you don't actually kill anything.
Image of chat commands:
Image of lap message:

Add Prifddinas Agility Course pb and kc commands

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java

hot cold clues: center level 38 wilderness dig location

---

runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSpot.java

Add lava eel to fishingspot plugin

---

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/chatcommands/ChatCommandsPluginTest.java

Support for regular & corrupted Gauntlet killcounts, as required by #9459

Gauntlet: Add !kc command

---

runelite-client/src/main/java/net/runelite/client/plugins/mining/Rock.java

Added the object IDS for the mining rocks in the prifddinas mines, Timers should be up and running now

Prifddinas mining rocks

---

runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java

Timers Plugin: Remove Tb when TeleBlocking Opponent Dies

---

runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZoneOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZonePlugin.java

closes #6268 and closes #7607 and closes #6701

nmz: Add total and per hour points to NMZ overlay

---

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_agility.json
runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_farming.json

I did a few laps with and without taking a portal and the avg came to 1220 so that's what I went with. If its believed it should always account for taking a portal I can change that.

skill calc: SotE additions

---

runelite-api/src/main/java/net/runelite/api/AnimationID.java
runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java

idle notifier: notify when adding feathers or heads to shafts

---

runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/ArdougneDiaryRequirement.java

Achievement Diary Plugin: Update Ardougne Hard Diary Text

---

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_fletching.json

skill calc: Support Dragon bolts

---

runelite-client/src/main/java/net/runelite/client/plugins/hunter/HunterPlugin.java

Added Ferret boxes id to the hunter plugin

---

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_herblore.json

Add four dose stamina to herblore calculator

---

runelite-client/src/main/java/net/runelite/client/game/AgilityShortcut.java

Add missing shortcut clickbox highlight to Trollweiss Mountain Cave

---

runelite-client/src/main/java/net/runelite/client/game/ClanManager.java

ClanManager: handle startup with an empty cache

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java

hot cold: center 'west of farming guild' location

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java

Clue text:
"A general who sets a 'shining' example."

cryptic: Added the new General Hining cryptic clue.

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java

hotcold: Center level 5 wilderness location

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java

Monk camp clue step has wrong location in the clue scroll plugin

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java

hot cold clues: center northern blast mine and eastern part of piscatoris hunter area dig locations

---

runelite-client/src/main/java/net/runelite/client/plugins/agility/Courses.java
runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_agility.json

made the calc this time just always account for taking the portal, since thats what people will be wanting to do anyways especially since they are highlighted now

Update prif agility course

---

runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java

Timers: Imbued Heart Resets On Death

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java

Turns out it was Mawrth in LLetya all along!

clues: correct "Has no one told you it is rude to ask a lady her age?"

---

runelite-client/src/main/java/net/runelite/client/game/chatbox/ChatboxItemSearch.java

ChatboxItemSearch: lowercase name to check for null names

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/SkillChallengeClue.java

clues: fix abyssal head recognition

---

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/TransportationPoint.java
runelite-client/src/main/java/net/runelite/client/plugins/worldmap/TransportationPointLocation.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/worldmap/WorldMapOverlayMouseListener.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/worldmap/WorldMapPoint.java

worldmap: add on-click jumping for unambiguous single-target transports

---

runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesOverlay.java

Just added conditionals to control what is displayed inside the tooltip box.
Closes #9497

Add toggles to XP Orb hovered line items display

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java

Fixes #9864
Edited clue solution that became incorrect due to Hosidius rework.

Hosidius clue rework

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java

Add Deviant spectre variant to cryptic clue info

---

runelite-client/src/main/java/net/runelite/client/plugins/bank/BankPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/banktags/BankTagsPlugin.java
runelite-client/src/main/scripts/BankSearchFilter.rs2asm
runelite-client/src/test/java/net/runelite/client/plugins/bank/BankPluginTest.java

Closes #6778
Supersedes/Closes #6902
Supersedes/Closes #9577 
Tests are included

Add bank item value search

---

runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilitySession.java
runelite-client/src/main/java/net/runelite/client/plugins/agility/LapCounterOverlay.java

AgilityPlugin: Add "Laps to Goal" and toggles for overlay

---

runelite-api/src/main/java/net/runelite/api/Client.java
runelite-api/src/main/java/net/runelite/api/MenuAction.java
runelite-api/src/main/java/net/runelite/api/SpriteID.java
runelite-client/src/main/java/net/runelite/client/menus/MenuManager.java
runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/devtools/WidgetInspector.java
runelite-client/src/main/java/net/runelite/client/plugins/devtools/WidgetInspectorOverlay.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java

Depends on !79
https://cdn.discordapp.com/attachments/419891709883973642/616076574734942208/2019-08-27_19-06-52.mp4

WidgetInspector: Add widget picker

---

runelite-client/src/main/java/net/runelite/client/plugins/music/MusicConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/music/MusicPlugin.java

Add volume overrides

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/SkillChallengeClue.java

skillchallengeclue: Fix "Cook a swordfish" elite clue

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java

i went to the wilderness camp because i didn't pay attention to the map and i felt dumb so

clues: clarify bandit camp location in coordinate hint

---

runelite-api/src/main/java/net/runelite/api/WallObject.java
runelite-client/src/main/java/net/runelite/client/plugins/objectindicators/ObjectIndicatorsOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/objectindicators/ObjectIndicatorsPlugin.java

object indicators: add ability to mark wall objects

---

runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingOverlay.java

Since you are not getting fish while the flying fish is active, you are not actually fishing any minnows.
Closes #8584

fishing: Set status to NOT fishing when the flying fish is active

---

runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonSpots.java

Add Cannon Spot for Priff Guards in marketplace
closes #10013

Add Elf Cannon Spot in Priff

---

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_crafting.json

skillcalc: add Broodoo shield

---

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_smithing.json

Add Spears and Hastae smithing to Skill calculator

---

runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java
runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/config/PluginListItem.java

Properly update plugin toggle button on plugin state change

---

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/TransportationPointLocation.java

Add Rimmington to the Andougne / Brimhaven ship transportation.
Also fix minor placement errors on two transportation icons in east Karamja.

Add Rimmington / Ardougne / Brimhaven ship

---

runelite-client/src/main/java/net/runelite/client/game/chatbox/ChatboxTextInput.java
runelite-client/src/main/java/net/runelite/client/plugins/banktags/BankTagsPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java

Closes https://github.com/runelite/runelite/issues/6644
Closes https://github.com/runelite/runelite/issues/6911
The tags get stripped out on master and cause issues with displaying the correct text in the right click menu and bank title.

Don't allow tag characters in bank tags

---

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java

Resolve #10066 - actually fixed it using VCS in IDEA this time!
See #10067 for more history.

Fix slayer infobox disappearing on '0' timeout

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java

Closes #10072
Added Island of Stone location descriptor for coordinate clue scroll.

Add Island of Stone location descriptor.

---

runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java

combat level plugin: fix wilderness level ranges

---

runelite-client/src/main/java/net/runelite/client/ui/overlay/WidgetOverlay.java

Make the PvP kill/death counter moveable

---

runelite-api/src/main/java/net/runelite/api/InventoryID.java
runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java
runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java

loottracker: add fishing trawler

---

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/FarmingPatchLocation.java

Closes #10111
Added enum constant for herb/flower patch.
Changed priff previous(allotment/flower/herb) patch to new constant(allotment/flower).

Add enum constant for allotment/flower + change priff allotment patch

---

runelite-client/src/main/resources/net/runelite/client/plugins/gpu/common.glsl
runelite-client/src/main/resources/net/runelite/client/plugins/gpu/geom.glsl
runelite-client/src/main/resources/net/runelite/client/plugins/gpu/to_screen.glsl

GPU: Floating point screen coordinates to eliminate vertex snapping

---

runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java

Add option to manually broadcast raid layout message

---

runelite-client/src/main/scripts/ChatSplitBuilder.rs2asm

chat timestamps: add timestamps to split private chat

---

runelite-client/src/main/java/net/runelite/client/plugins/music/MusicPlugin.java

Closes #10198
Added sound and volume tags to music plugin

Added sound and volume tags to music plugin

---

runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java

Closes #10189
This is probably wrong but this code is too well obfuscated for me to tell.

OverlayRenderer: Update bounds before render

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java

highlight correct crate for Rommik's shop clue

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java

Someone got their directions mixed up

clues: correct direction of Miscellania island coordinate clue

---

runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeSearchPanel.java
runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/SkillCalculator.java
runelite-client/src/main/java/net/runelite/client/ui/components/IconTextField.java

Closes #9545 
Closes #10196 
Closes #9634
Closes #9741

Properly clear skill calc and grand exchange selections after clear button press

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/SkillChallengeClue.java

clues: fix yew tree Sherlock challenge

---

runelite-client/src/main/java/net/runelite/client/plugins/defaultworld/DefaultWorldConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/defaultworld/DefaultWorldPlugin.java

store the last world you were connected to and apply on startup.

defaultworld: store the last world you were connected to

---

runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonSpots.java

Add cannon spot for trolls at Quidamortem
closes #10233

cannon: Add cannon spot for trolls at Quidamortem #10233

---

runelite-client/src/main/java/net/runelite/client/plugins/deathindicator/DeathIndicatorPlugin.java

add Kourend respawn region to death indicator plugin

---

runelite-api/src/main/java/net/runelite/api/Client.java
runelite-client/src/main/java/net/runelite/client/plugins/entityhider/EntityHiderConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/entityhider/EntityHiderPlugin.java

Depends on !90
https://streamable.com/d6yfl
Closes #2794

Entity Hider Plugin: add support for hiding pets

---

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_crafting.json

Added bird houses to crafting skill calculator
Fixes #10274

add all bird houses to crafting skill calculator

---

runelite-client/src/main/java/net/runelite/client/plugins/runepouch/RunepouchOverlay.java

add rune pouch overlay to rune pouch (l)

---

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

adds feature request [#10338](https://github.com/runelite/runelite/issues/10338)

menu entry swap plugin: add captain khaled talk-to/task swap

---

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

Menu Entry Swapper: Add 'help' swap to Arceuus library customers

---

runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/TreeRespawn.java
runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/WoodcuttingPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/WoodcuttingTreesOverlay.java

woodcutting: show respawn timers after GameState change

---

runelite-client/src/main/resources/net/runelite/client/plugins/gpu/vert.glsl

before and after video clips: https://imgur.com/a/5GM2t7D

GPU: smooth out fog corners by 1 tile, eliminating the diagonal line

---

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_fletching.json

This is my first ever open source commit. Let me know if I need to improve anywhere.

change arrow shaft xp rate to per unit xp for unit produced

---

runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java

Cannonball ammo count notification added. Replaces the choice between no notification and notification at 0.
Closes #10365

Cannonball ammo count notifications

---

runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/KourendLibraryPlugin.java

kourendlibrary: clear tracked NPCs when changing worlds

---

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatKeyboardListener.java

chatcommands: support keybinds in pms

---

runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/KourendLibraryPlugin.java

Also fix the code to add/remove the nav button being run on unnecessary config changes

kourendlibrary: fix panel reloading not being done on the swing thread

---

runelite-api/src/main/java/net/runelite/api/Client.java
runelite-api/src/main/java/net/runelite/api/annotations/VisibleForExternalPlugins.java

Add getVar methods for external plugins

---

.gitignore
runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_cooking.json

add vscode to gitignore
add missing foods to skill_cooking.json

Cooking calculator: add missing foods

---

runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/raids/RaidsPluginTest.java

Adds the functionality to view raids loot value when opening the chest

Show raids loot value at the end of the raid

---

http-api/src/main/java/net/runelite/http/api/hiscore/HiscoreResultBuilder.java
http-service/src/test/java/net/runelite/http/service/hiscore/HiscoreServiceTest.java

Jagex finally added them to the `index_lite` format :tada:

hiscore api: add Callisto and Cerberus

---

runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java

To make way for the equipment button

banktags: move new tagtab button to the bottom of the list

---

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPluginTest.java

Fix ToB door quick-enter swap and add a test for it

---

runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/SkillCalculator.java

See issue #8879 for a description.

Added target level functionality for skill calculator

---

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItem.java
runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/grounditems/LootType.java

grounditems: show your dropped items with onlyShowLoot active

---

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_thieving.json

Added the four sq'irkjuices to the datafile for the thieving skill calculator.
This resolves #10538

Add all four sq'irkjuices to the thieving skill calculator.

---

cache/src/main/java/net/runelite/cache/definitions/WorldMapDefinition.java
cache/src/main/java/net/runelite/cache/definitions/WorldMapType0.java
cache/src/main/java/net/runelite/cache/definitions/WorldMapType1.java
cache/src/main/java/net/runelite/cache/definitions/WorldMapType2.java
cache/src/main/java/net/runelite/cache/definitions/WorldMapType3.java
cache/src/main/java/net/runelite/cache/definitions/loaders/WorldMapLoader.java

Changed the WorldMapType field names from fieldxxx to values
that represent what they actually mean (mostly x, y, z coordinates)

Update WorldMapDefinition attributes

---

cache/src/main/java/net/runelite/cache/ConfigType.java
cache/src/main/java/net/runelite/cache/definitions/HitSplatDefinition.java
cache/src/main/java/net/runelite/cache/definitions/loaders/HitSplatLoader.java
cache/src/main/java/net/runelite/cache/io/InputStream.java
cache/src/test/java/net/runelite/cache/HitSplatDumper.java

This PR simply adds hitsplat definition decoding capabilities to the cache project.

cache: Add hitsplat definition

---

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/chatcommands/ChatCommandsPluginTest.java

Makes #10603 actually work. for CoX

Fixes cox personal best time tracking

---

runelite-client/src/main/java/net/runelite/client/plugins/wiki/WikiConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/wiki/WikiPlugin.java

Let me know if this code style is too ugly, I felt dumb using a switch for a boolean. I also removed a switch with a single case and instead used if.

Add ability and config to swap Lookup and Search in wiki plugin

---

runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java
runelite-client/src/main/java/net/runelite/client/config/TooltipPositionType.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/tooltip/TooltipOverlay.java

Allows changing the position of the tooltip to be under (default) or above the cursor depending on the configuration.

Add configurability of tooltip position relative to cursor

---

runelite-client/src/main/java/net/runelite/client/plugins/antidrag/AntiDragPlugin.java

As requested by:
https://github.com/runelite/runelite/issues/10262#issue-522920236

Change AntiDrag to support Bank interfaces.

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java

Closes #10602 
Added a more descriptive solution to the General Bentnoze clue step.

Update General Bentnoze clue step solution

---

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPanel.java
runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
runelite-client/src/main/java/net/runelite/client/util/SwingUtil.java

This also fixes some bugs with the visible/hide icon getting out of sync with the actual state.

Optimize loottracker UI

---

runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/timers/TimersPluginTest.java

As is the case with other graphics-based timers, the imbued heart timer
will not fire if enough other graphics animations are triggered (such as
those created when fighting the Dagannoth Kings). To add this timer more
reliably, this commit will add the timer when a Magic stat boost occurs
which is large enough that it can only be triggered by the heart.
Because the heart's boost scales with the player's level, it gives an
equal boost to the Magic essence and Magic potion boosts, depending on
the base magic level. To account for this, it will only be applied if
the user's base magic level is high enough to assuredly identify that a
potion was not used to trigger the boost.
Fixes runelite/runelite#3516
Co-authored-by: Jordan Atwood <jordan.atwood423@gmail.com>
P.S. This is continued from …

timers plugin: Improve imbued heart detection

---

runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/npcunaggroarea/NpcAggroAreaPlugin.java

Not necessarily looking to have this merged as-is, feedback is welcome

NPC unaggro timer: Added a notification feature to the Unaggro plugin

---

runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java

fixed dfs spec to 192 ticks

---

runelite-api/src/main/java/net/runelite/api/Opcodes.java
runelite-api/src/main/java/net/runelite/api/events/ScriptPostFired.java
runelite-api/src/main/java/net/runelite/api/events/ScriptPreFired.java
runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPanel.java
runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/devtools/ScriptInspector.java

Relies on !96
Picture of the dev tool 
Swing sucks and I suck at swing.

Add script fired events and add script inspector devtool

---

http-api/src/main/java/net/runelite/http/api/loottracker/LootRecordType.java
http-service/src/main/java/net/runelite/http/service/loottracker/LootTrackerService.java
runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerBox.java
runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPanel.java
runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerRecord.java
runelite-client/src/test/java/net/runelite/client/plugins/loottracker/LootTrackerPluginTest.java

Add pickpocket events to loot tracker

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java

hot cold clues: add new slepe location

---

runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/timers/TimersPluginTest.java

This reverts commit 45c5df3379767146f91e1e4a1f48d9692599a1d4.
Re-opens #3516

Revert "timers plugin: Improve imbued heart detection"

---

runelite-api/src/main/java/net/runelite/api/kit/KitType.java

Fix KitType index for the head slot

---

runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java

First pass at optimization for issue #10819
(Will improve pull request over time, submitting early for testing.)

Improve GPU Plugin performance

---

runelite-api/src/main/java/net/runelite/api/Client.java
runelite-api/src/main/java/net/runelite/api/events/GrandExchangeSearched.java
runelite-client/src/main/java/net/runelite/client/game/ItemVariationMapping.java
runelite-client/src/main/java/net/runelite/client/plugins/banktags/BankTagsPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/banktags/BankTagsPluginTest.java

Closes https://github.com/runelite/runelite/issues/6236
Depends on !72

Bank tags: search tags in ge search

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/AnagramClue.java

first contribution and was unsure of how exactly to get a worldpoint... any tips much appreciated!
Fixes #10747

add new slepe anagram clue

---

runelite-client/src/main/java/net/runelite/client/Notifier.java
runelite-client/src/main/java/net/runelite/client/events/NotificationFired.java

For external plugins to do custom notification stuff.

client: add notification fired event

---

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java

chat commands: add Bounty Hunter, Bounty Hunter Rogue, and Last Man Standing commands

---

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatOverlay.java

Items already equipped or items that are the same should still show their stats.

itemstats: Add 'Always Show Base Stats' & 'Show Stats In Bank' 

---

runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/UICalculatorInputArea.java

Strip out non-digits characters in skill calculator

---

runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java

Added 'prayer' to the tags for XPDropPlugin to facilitate finding the plugin from the client plugin search feature.
Closes #10829

XPDropPlugin: Added 'prayer' to the tags for XPDropPlugin

---

runelite-client/src/main/java/net/runelite/client/plugins/inventorytags/InventoryTagsConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/inventorytags/InventoryTagsPlugin.java

Increase inventory tag color count

---

runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilitySession.java
runelite-client/src/main/java/net/runelite/client/plugins/agility/LapCounterOverlay.java

- Merge laps until next level and laps until next goal together
- Switch to XpTrackerService for determining goal experience

Use XpTrackerService to determine goals in Agility plugin

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java

Modified clue hint for Yanille Agility dungeon cryptic clue scroll for accuracy.
Closes #10871

Modified clue hint for Yanille Agility dungeon cryptic clue scroll.

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/SkillChallengeClue.java

Modified Necryael slaying clue scroll raw text to reflect reality.

---

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_herblore.json

Herblore Skill Calculator: Add Guthix Rest

---

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java

Cancel slayer task when leaving the Inferno

---

runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/mining/Rock.java

mining: add urt, efh, te and basalt respawn timers

---

runelite-client/src/main/java/net/runelite/client/plugins/reportbutton/ReportButtonPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/reportbutton/TimeStyle.java

Counts game ticks since login and displays them on the Report button

reportbutton: Add Game Ticks option

---

runelite-api/src/main/java/net/runelite/api/MessageNode.java
runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/chatfilter/ChatFilterPluginTest.java

Closes #10923 
Can use regular expressions or just word filtering. "Censor Words" option stars out the entire message which is a bit ham-fisted but I'm not sure what to do in that case, open to suggestions.
https://i.imgur.com/FBsZiaF.gifv

chatfilter: add filtering by username

---

runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/mining/Rock.java
runelite-client/src/main/java/net/runelite/client/plugins/mining/RockRespawn.java

After making #10381 i noticed the mining plugin had this same fault so i decided to refactor it aswell.

mining: show respawn timers after GameState change

---

runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java

widgetid: fix lms ingame info

---

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

menuentryswapper: swap talk-to with teleport on rune essence mine npcs 

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/NamedObjectClueScroll.java
runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/SkillChallengeClue.java

For the skill challenge clue "Fix a magical lamp in Dorgesh-Kaan.",
highlight lamps in the area which are broken.
Fixes #10069
Closes #10117

Add NamedObjectClueScroll interface, highlight broken Dorgesh-kaan lamps

---

runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesOverlay.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/components/TooltipComponent.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/tooltip/Tooltip.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/tooltip/TooltipOverlay.java

Add panel component tooltips and migrate XpGlobesOverlay tooltips to new system

---

runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordGameEventType.java

Added nightmare dungeon and nightmare boss to discord game events for the discord status message.
Resolves 2 of 2 in #10771

Added nightmare dungeon and nightmare boss to discord game events.

---

runelite-client/src/main/java/net/runelite/client/plugins/objectindicators/ColorTileObject.java
runelite-client/src/main/java/net/runelite/client/plugins/objectindicators/ObjectIndicatorsOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/objectindicators/ObjectIndicatorsPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/objectindicators/ObjectPoint.java

Closes #9632
Supersedes/Closes #10124

object indicators: add support for multiple colors

---

runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonSpots.java

Added common cannoning spot for Lizard Shamans.

---

runelite-client/src/main/java/net/runelite/client/plugins/customcursor/CustomCursor.java
runelite-client/src/main/java/net/runelite/client/plugins/customcursor/CustomCursorPlugin.java

Added option to use equipped weapon image as cursor.

---

runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonSpots.java

Added Black Knights cannoning spot in Taverley Dungeon

---

http-api/src/main/java/net/runelite/http/api/worlds/WorldRegion.java
http-service/src/test/java/net/runelite/http/service/worlds/WorldsServiceTest.java
runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldTableRow.java

Adds the region of the world the scout was performed in.
Before: W303         Username
Now:    W303 (GER)   Username

raids: add world region to scout overlay

---

runelite-api/src/main/java/net/runelite/api/widgets/Widget.java
runelite-api/src/main/java/net/runelite/api/widgets/WidgetModelType.java
runelite-client/src/main/java/net/runelite/client/plugins/devtools/WidgetInfoTableModel.java

This commit also adds these widget properties to the widget inspector
dev tool.
Depends on !103

widget: Expose model id, rotation, and zoom accessors

---

runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityPlugin.java

Similar to highlighting 'Mark of Grace' when doing Rooftop Agility Courses, it would be helpful to highlight the 'Stick' when doing Werewolf Agility Course.
Closes #6474

Highlight 'Stick' in Werewolf Agility Course

---

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/loottracker/LootTrackerPluginTest.java

Allow Loot Tracker to track Herbiboar loot with an Open Herb Sack

---

runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostIndicator.java
runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsPlugin.java

boosts: Hide restore timer when no boosts are visible

---

runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZonePlugin.java

Nmz Plugin - Fix area check to exclude KBD lair

---

runelite-client/src/main/java/net/runelite/client/plugins/slayer/Task.java
runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java

- Fix https://github.com/runelite/runelite/issues/11104. The solution is to add an entry to the `SlayerTaskPlugin`'s `Task` whitelist.

Fix Jormungand's prison task location for the Slayer Plugin

---

runelite-api/src/main/java/net/runelite/api/MenuAction.java
runelite-client/src/main/java/net/runelite/client/plugins/playerindicators/PlayerIndicatorsPlugin.java

player-indicators: highlight the 'Walk here' menu entry too

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java

HotColdLocation: Center Rimmington mine dig location

---

runelite-client/src/main/java/net/runelite/client/ui/overlay/WidgetOverlay.java

Fixes #11207 
Defaulted LMS info and KDA widget positions to the TOP_RIGHT anchor point.

Corrected LMS info and KDA widget postitions.

---

runelite-client/src/main/java/net/runelite/client/RuneLite.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/tooltip/TooltipManager.java

Reset repositioned tooltip overlays

---

runelite-client/src/test/java/net/runelite/client/plugins/itemstats/ItemStatOverlayTest.java

Mock ConfigManager in ItemStatOverlayTest to inject TooltipManager

---

runelite-api/src/main/java/net/runelite/api/Client.java
runelite-client/src/main/java/net/runelite/client/plugins/camera/CameraConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/camera/CameraPlugin.java

camera: add option to invert camera mouse controls

---

http-api/src/main/java/net/runelite/http/api/config/ConfigClient.java
runelite-api/src/main/java/net/runelite/api/Client.java
runelite-client/src/main/java/net/runelite/client/ClientSessionManager.java
runelite-client/src/main/java/net/runelite/client/RuneLite.java
runelite-client/src/main/java/net/runelite/client/chat/ChatMessageManager.java
runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java
runelite-client/src/main/java/net/runelite/client/eventbus/EventBus.java
runelite-client/src/main/java/net/runelite/client/events/ClientShutdown.java
runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java
runelite-client/src/main/java/net/runelite/client/util/SwingUtil.java

Requires !107
This should hopefully make the client not corrupt it's cache randomly, and prevents the config sets from racing shutdown

runelite-client: add ClientShutdown event

---

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

Deposit box interface update broke shift-modifiers for deposit boxes.

Fix shift-modifier for deposit box after new interface update

---

runelite-api/src/main/java/net/runelite/api/AnimationID.java
runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java

fishing & idle notifer: add pearl rod animations

---

runelite-api/src/main/java/net/runelite/api/AnimationID.java
runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java

I think everyone forgot about this existing.

fishing & idle notifer: add oily pearl rod animations

---

runelite-api/src/main/java/net/runelite/api/AnimationID.java
runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java

I'm quite surprised that this hasn't already been added.
Thanks to `PaPa` in the Discord for reporting this.

idle notifier: add support for enchanting bolts

---

runelite-client/src/main/java/net/runelite/client/plugins/screenmarkers/ScreenMarkerOverlay.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/Overlay.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java

Prevent screen marker overlays from being reset

---

runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilitySession.java
runelite-client/src/main/java/net/runelite/client/plugins/agility/LapCounterOverlay.java

Agility: Course laps per hour display

---

runelite-client/src/main/java/net/runelite/client/game/chatbox/ChatboxTextInput.java
runelite-client/src/main/java/net/runelite/client/plugins/banktags/BankTagsPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java
runelite-client/src/main/java/net/runelite/client/plugins/fairyring/FairyRingPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/music/MusicPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/questlist/QuestListPlugin.java

Closes #11078 
Stops the quest filter input from closing when pressing enter

quest list: stop chat input from closing when pressing enter

---

runelite-client/src/main/java/net/runelite/client/plugins/xpupdater/XpUpdaterConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/xpupdater/XpUpdaterPlugin.java

Adding automatic tracking on logout to my new app [Wise Old Man](https://wiseoldman.net/).

Add wise old man tracking to xp updater plugin

---

runelite-api/src/main/java/net/runelite/api/Client.java
runelite-client/src/main/java/net/runelite/client/RuneLiteModule.java

rl-api, rl-client: Remove core logger

---

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerBox.java
runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPanel.java
runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java

Adds a config option similar to the IgnoreItems but that works on the event level.
Closes #7482

loottracker - Add ignore events config option

---

runelite-client/src/main/java/net/runelite/client/ClientSessionManager.java

Saw this as a good easy bug to fix to get introduced to runelite. Is this a good solution?
#11354

Preventing ClientSessionManager from calling onClinetShutdown multiple times 

---

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItem.java
runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java

fixes mouse tooltip item value color not matching ground item value color

---

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/HunterAreaLocation.java
runelite-client/src/main/java/net/runelite/client/plugins/worldmap/HunterAreaPoint.java
runelite-client/src/main/java/net/runelite/client/plugins/worldmap/WorldMapConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/worldmap/WorldMapPlugin.java

worldmap: add hunter area tooltips

---

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/FarmingPatchLocation.java

Hosidius farming tooltip to new point on world map

---

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_agility.json

skill calc: add barbarian fishing to agility skill calculator

---

runelite-client/src/main/java/net/runelite/client/game/FishingSpot.java
runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSpotMinimapOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingSpotOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/worldmap/FishingSpotLocation.java
runelite-client/src/main/java/net/runelite/client/plugins/worldmap/FishingSpotPoint.java
runelite-client/src/main/java/net/runelite/client/plugins/worldmap/WorldMapConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/worldmap/WorldMapPlugin.java

Add fishing spot tooltips to worldmap

---

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/loottracker/LootTrackerPluginTest.java

Closes runelite/runelite#10034

loottracker: Show chat message after NPC and PVP kills

---

runelite-api/src/main/java/net/runelite/api/Varbits.java
runelite-client/src/main/java/net/runelite/client/plugins/raids/Raid.java
runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java

Scouter: https://streamable.com/sjvq3

raids plugin: update scouter on chunk load and let players relog without breaking

---

runelite-client/src/main/java/net/runelite/client/plugins/tileindicators/TileIndicatorsConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/tileindicators/TileIndicatorsOverlay.java

Same concept as from [this close PR](https://github.com/runelite/runelite/pull/2764).
In action:
https://streamable.com/4uir6

Add true current tile to tile indicator plugin

---

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPanel.java

loot tracker: Fix "Show each kill separately" view

---

runelite-api/src/main/java/net/runelite/api/WorldType.java
runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordGameEventType.java
runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordPlugin.java

discord: Update activity message while playing PVP or DMM

---

runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java

Add option to take a screenshot when kicking a user from clan chat

---

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_construction.json

Add gnome bench to construction skill calculator

---

runelite-client/src/main/java/net/runelite/client/plugins/objectindicators/ObjectIndicatorsPlugin.java

Closes https://github.com/runelite/runelite/issues/10576

object indicators: check for null compositions

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CipherClue.java

Clue: Update Iron Man tutor clue cypher

---

runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayManager.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayPanel.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/components/PanelComponent.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBoxOverlay.java

Make background color of panel components configurable

---

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/BuyMode.java
runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/SellMode.java

Pull request for issue #11427.

Adds menu entry swaps for Buy 1/5/10/50 and Sell 1/5/10/50.

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java
runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java

FIxes #11158 
Specified additional item requirements in Dragontooth Island elite coordinate clue
Specified additional item requirements in Viyeldi Caves master cryptic clue

Specified additional item requirements in two clue scrolls

---

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_crafting.json

Add clay crafting items to crafting calculator

---

runelite-client/src/main/java/net/runelite/client/plugins/reportbutton/ReportButtonPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/reportbutton/TimeFormat.java

Closes #2861
Supersedes/closes #6433

Add 24h clock and clock tag to report button

---

runelite-client/src/main/java/net/runelite/client/game/ItemManager.java

f9d3647db1a6c8b715d50d39a5141b006f5f3840 made ItemManager return a price
for placeholders, which is wrong.
Closes #11686

ItemManager: only canonicalize notes

---

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/chatcommands/ChatCommandsPluginTest.java

Fixes the the tracking for cox after the update

 chatcommands: fix chambers of xeric pb tracking 

---

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/chatcommands/ChatCommandsPluginTest.java

Adds the ability to use theatre of blood !pb command, which will include the best wave/challenge time.
Closes #8454

chatcommands: add tob personal best tracking

---

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsConfig.java

Minor grammar fixes for ConfigItem descriptions.

client: Fix grammar in Ground Items config

---

runelite-client/src/main/java/net/runelite/client/game/AgilityShortcut.java

Add Witchaven Dungeon agility shortcut to agility plugin

---

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPanel.java

loot tracker - Fix total values when not grouping loot

---

runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanChatConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/clanchat/ClanChatPlugin.java
runelite-client/src/main/scripts/ClanSendKick.rs2asm

Changes the "Attempting to kick player from friends chat..." message to include the name instead of player.

Kick players by name

---

runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java

remove stamina timer upon entering the Gauntlet

---

runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeSearchPanel.java
runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/SkillCalculator.java
runelite-client/src/main/java/net/runelite/client/ui/components/IconTextField.java

This would put the ge search panel into an invalid state where it could no longer be interacted with

IconTextField: fire clear listener after text has been cleared

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/SkillChallengeClue.java

Jagex has changed the text for this master-level challenge.
Thanks to `melky` for finding this.

clues: update ranging mix sherlock master challenge

---

runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/agility/LapCounterOverlay.java

client: Add reset option to Agility lap counter session overlay

---

runelite-client/src/test/java/net/runelite/client/ui/overlay/infobox/InfoBoxManagerTest.java

See: 406c2bc7dbb8b9db70e8e525fb51aad5f3f56e0d

infoboxmanager: Test infoboxes with same plugin and priority

---

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_construction.json
runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_farming.json

Update farming skill calculator with Sq'irk fruits and POH garden plants

---

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java

Closes #4778
Revival of #5763
All credits to @raiyni for this.

Respect multiple displays when saving/loading client position

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java

Added "if 76 Agility" to the BJS clue
Resolves #11889

Added if 76 Agility to BJS Clue for issue #11889

---

runelite-api/src/main/java/net/runelite/api/MenuAction.java
runelite-client/src/main/java/net/runelite/client/RuneLite.java
runelite-client/src/main/java/net/runelite/client/events/InfoBoxMenuClicked.java
runelite-client/src/main/java/net/runelite/client/events/OverlayMenuClicked.java
runelite-client/src/main/java/net/runelite/client/plugins/deathindicator/DeathIndicatorPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPanel.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayManager.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/components/InfoBoxComponent.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBoxOverlay.java

Add support for menu options on infoboxes

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java

Encourages people to use monastery teleport instead of Edgeville teleport

Better description of Ice Mountain location

---

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_runecraft.json

Skill Calculator - Add Daeyalt essence bonus

---

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/components/TextComponent.java

Add option to outline grounditems text

---

runelite-client/src/main/java/net/runelite/client/plugins/antidrag/AntiDragPlugin.java

antidrag: add antidrag to inventory when bank interface is open

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/SkillChallengeClue.java

SkillChallengeClue: Fix "Mine a mithril ore" step

---

runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/mining/Rock.java

Adds time overlays to the daeyalt essence mines.
Closes #11812

mining: Daeyalt essence timers

---

runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java

This has been a minor annoyance when playing multiple accounts.
I had a pull request not based on a separate branch earlier, I closed that one so I could make this.
Closes #2312

ClientUI: Remember sidebar state

---

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

Fixes the issue in this comment: https://github.com/runelite/runelite/issues/11986#issuecomment-649919929

menuentryswapper: Fix claim slime swap

---

runelite-client/src/main/java/net/runelite/client/plugins/raids/Raid.java
runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidRoom.java
runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/raids/events/RaidReset.java
runelite-client/src/main/java/net/runelite/client/plugins/raids/events/RaidScouted.java

This is made for external plugins

raid plugin: add raid scouted/reset events

---

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_fletching.json

fix xp for maple longbow (u)

---

runelite-client/src/main/java/net/runelite/client/ui/overlay/tooltip/TooltipOverlay.java

tooltips: make overlay color background option affect tooltips

---

runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargeConfig.java

Minor fixes for grammar and wording in `ItemChargeConfig`.

ItemChargeConfig: Fix grammar and wording

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java

Updated following Ferox Enclave release. The coordinates are the same.
New clue text: https://www.reddit.com/r/2007scape/comments/hs9x7b/clue_issue_clan_wars_cup/

clues: Update text and description for clan cup clue

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/FaloTheBardClue.java

FaloTheBardClue: Add Avernic to Defender step

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/BeginnerMapClue.java

clues: Fix champs guild beginner clue description

---

runelite-client/src/main/java/net/runelite/client/plugins/inventorygrid/InventoryGridOverlay.java

closes #9055 
Enable grid when viewing the bank.

inventory-grid: show grid when viewing bank

---

runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/CombatLevelRequirement.java
runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/DiaryRequirementsPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/FavourRequirement.java
runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/OrRequirement.java
runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/QuestPointRequirement.java
runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/QuestRequirement.java
runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/Requirement.java
runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/SkillRequirement.java

Add satisfiesRequirement to Requirement interface that all other requirements implement Instead of using instanceOf to see if each requirement is satisfied.

achivement dairy plugin: add satisfiesRequirement to Requirement

---

runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPanel.java
runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/devtools/InventoryDeltaPanel.java
runelite-client/src/main/java/net/runelite/client/plugins/devtools/InventoryInspector.java
runelite-client/src/main/java/net/runelite/client/plugins/devtools/InventoryItem.java
runelite-client/src/main/java/net/runelite/client/plugins/devtools/InventoryLog.java
runelite-client/src/main/java/net/runelite/client/plugins/devtools/InventoryLogNode.java
runelite-client/src/main/java/net/runelite/client/plugins/devtools/InventoryTreeNode.java

Adds an inventory inspector to the dev tools which tracks `ItemContainerChanged` events while open, updating the snapshots when the `refresh` button is clicked.

Dev Tools - Add Inventory Inspector

---

runelite-client/src/main/java/net/runelite/client/plugins/banktags/BankTagsPlugin.java

Invoking the tab separator removal allowed tab separators to be visible and interactable for a frame. On slower computers, users could click and navigate to a tab during that period. The removal no longer needs to be invoked after e4b43d9 so we can just invoke the script run.

bank tags: invoke only the scrollbar update after removing separators

---

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java

Adds `nm`, `tnm`, and `nmare` as aliases for `!kc nightmare` command
Closes #12347

chat commands: add Nightmare abbreviations

---

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java

grounditems plugin: fix despawn timer for private KBD instances

---

runelite-client/src/main/java/net/runelite/client/plugins/antidrag/AntiDragPlugin.java

adds anti drag to deposit box using bank drag delay

Anti drag: add deposit box for bank drag

---

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java

Close #11745 
Changed condition for a highlighted drop notification to be sent.

GroundItems: Fix notifications for highlighted drops

---

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

Add option for Haskell NPC that might have been missed in #12333

menuentryswapper: Island of Stone fast-travel

---

runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java

Quick swap around of the NPC Ids for abyssal sire to get his timer started and stop. 
Thanks to @abextm for listing the correct NPC Ids.
Fixes #12397

Update stunned abyssal sire NpcId

---

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_construction.json

This pull request adds carpenter's outfit into the current calculator

Add carpenter outfit into construction skill calculator

---

runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java
runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java

Closes #12459 
Added timers for both full and half length Mage Arena 2 teleblock patterns.

timers: add Mage Arena 2 teleblock patterns.

---

runelite-client/src/main/java/net/runelite/client/plugins/mining/Pickaxe.java

Noticed when I was mining Amethyst that the Mining indicator didn't ever register as mining.

mining: add overheard mining animations

---

runelite-client/src/main/resources/net/runelite/client/plugins/skybox/skybox.txt

skybox: include twisted league and hosidius POH themes

---

runelite-client/src/main/java/net/runelite/client/RuneLite.java
runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostIndicator.java
runelite-client/src/main/java/net/runelite/client/plugins/timers/TimerTimer.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/Overlay.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBox.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBoxManager.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBoxOverlay.java
runelite-client/src/test/java/net/runelite/client/plugins/itemcharges/ItemChargePluginTest.java
runelite-client/src/test/java/net/runelite/client/plugins/raids/RaidsPluginTest.java
runelite-client/src/test/java/net/runelite/client/plugins/screenshot/ScreenshotPluginTest.java
runelite-client/src/test/java/net/runelite/client/ui/overlay/infobox/InfoBoxManagerTest.java

Co-authored-by: Ron Young <admin@ryoung.io>

infobox: add support for multiple infobox groups

---

runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/CrowdsourcingManager.java
runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/CrowdsourcingPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/cooking/CookingData.java
runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/cooking/CrowdsourcingCooking.java
runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/dialogue/CrowdsourcingDialogue.java
runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/dialogue/DialogueOptionsData.java
runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/dialogue/NpcDialogueData.java
runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/dialogue/PlayerDialogueData.java
runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/movement/CrowdsourcingMovement.java
runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/movement/MovementData.java
runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/music/CrowdsourcingMusic.java
runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/music/MusicUnlockData.java
runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/skilling/SkillingEndReason.java
runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/skilling/SkillingState.java
runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/thieving/CrowdsourcingThieving.java
runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/thieving/PickpocketData.java
runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/woodcutting/CrowdsourcingWoodcutting.java
runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/woodcutting/WoodcuttingData.java
runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/zmi/CrowdsourcingZMI.java
runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/zmi/ZMIData.java

Note to any reviewers: this a slight modification of https://github.com/leejt/osrs-wiki-crowdsourcing

Move Crowdsourcing plugin from hub to default client

---

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

Close #12574
Swaps the clean/use option on herbs

menu entry swapper: add clean swap

---

runelite-client/src/main/java/net/runelite/client/plugins/banktags/BankTagsPlugin.java

banktags: Don't lose scroll position when hiding separators

---

runelite-client/src/main/java/net/runelite/client/plugins/runecraft/AbyssRifts.java
runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftPlugin.java

Refactored `updateRifts()` and general cleanup. No functionality changes.

runecraft: cleanup

---

runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/components/InfoBoxComponent.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBoxOverlay.java

config: Add infobox component outline option

---

runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterPlugin.java

Close #12416 
Adds game message filtering and a toggle in the configs.

chatfilter: Add option to filter game chat

---

runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java

The ClientUI changes are somewhat gross and non-DRY, but it seemed better than overengineering more abstractions.
Fixes #12463

Fix screenshot with hidpi scaling with GPU plugin

---

runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java
runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingWorld.java

timetracking: correctly bound Catherby patches

---

runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeGemOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeOreOverlay.java

Originally wanted a way to see how much GP I'd earned in a given mlm session but didn't have time to figure out Java UI to add tooltips to the individual ImageComponents. The style is copied from the blast mine overlay, don't think anyone actually asked for this but I wanted it for myself, figured I'd put it up for a PR.

Motherlode mine sack ores overlay

---

runelite-client/src/main/java/net/runelite/client/util/ImageUtil.java

Close #10708
I came with this idea to show exact place where file should be.
Is there any better way to handle it?

ImageUtil: add error log with path

---

runelite-client/src/main/java/net/runelite/client/plugins/worldhopper/WorldTableRow.java

Color source: https://secure.runescape.com/m=news/gielinor-gazette-september-2020?oldschool=1

Worldhopper: Update league world color for Trailblazer

---

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java

Leagues are approximately three weeks out and i assume that they will not add another league endpoint.
Closes #10301

chat-commands: add league points command

---

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpState.java
runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpWorldType.java

This will not account for potential xp boosting relics, but it should be ok to start out with.
Closes #10304

xp-tracker: support league & dmm modifiers for kills remaining

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java

Ref: #9601 
Centers a hot/cold location and fixes its description.

HotColdLocation: Center a location spot.

---

runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodePlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeSceneOverlay.java
runelite-client/src/test/java/net/runelite/client/plugins/motherlode/MotherlodePluginTest.java

When strut is broken, red border with hammer icon will show around it.
closes #2018

motherlode: Add overlay for broken water wheel struts

---

runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java

experiencedrop: dont npe when trying to prayer highlight noncombat drops

---

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java
runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpPanel.java
runelite-client/src/main/java/net/runelite/client/plugins/xpupdater/XpUpdaterPlugin.java

Wise old man is launching a [trailblazer tracker](https://trailblazer.wiseoldman.net) and this should make the tracker go to the right place.

xp: add support for wise-old-man trailblazer

---

README.md

Instead of linking to image link to actual workflow

Link to CI workflow from CI badge

---

runelite-client/src/main/scripts/ChatBuilder.rs2asm

Closes #8542
I've been testing this for around half a year now, kept forgetting to PR it.

chat timestamps: add timestamps for all message types

---

runelite-client/src/main/java/net/runelite/client/plugins/keyremapping/KeyRemappingConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/keyremapping/KeyRemappingListener.java
runelite-client/src/test/java/net/runelite/client/plugins/keyremapping/KeyRemappingListenerTest.java

Added ability to rebind control key

---

runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargeConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargeOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargePlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargeType.java
runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemWithSlot.java
runelite-client/src/test/java/net/runelite/client/plugins/itemcharges/ItemChargePluginTest.java

Add Chronicle to Item Charges plugin

---

runelite-client/src/main/java/net/runelite/client/plugins/slayer/Task.java

Slayer info from https://oldschool.runescape.wiki/w/Cyclops - notable synergy with Unnatural Selection in Trailblazer league

Add Cyclops to hill giants task list

---

runelite-client/src/main/java/net/runelite/client/plugins/opponentinfo/OpponentInfoPlugin.java

opponent info: fix npcindicator color not working with opponent info

---

runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java

widgetid: correct quest completed group

---

runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java

So i completely forgot about the screenshot filename in #12783 and only checked if it actually took a screenshot. Sorry about that.

widgetid: correct quest completed text

---

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

menu swapper: Add NPC Deposit-Items swap

---

runelite-api/src/main/java/net/runelite/api/ScriptID.java
runelite-client/src/main/java/net/runelite/client/plugins/bank/BankConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/bank/BankPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/bank/BankSearch.java
runelite-client/src/main/java/net/runelite/client/plugins/banktags/BankTagsPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java

Closes #3994
Supersedes/Closes #10151
Rebased and tested it.

bank plugin: add ctrl+f hotkey to initiate bank search

---

runelite-api/src/main/java/net/runelite/api/SpritePixels.java

Import SpritePixels methods for better positioning of custom Sprites

---

runelite-api/src/main/java/net/runelite/api/Constants.java
runelite-client/src/main/java/net/runelite/client/plugins/skybox/SkyboxPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/skybox/SkyboxPluginConfig.java

Current state of these options:
Adds a custom sky color picker, and a dropdown to replace the sky color in either the overworld or everywhere. I should probably change this to a toggle and custom color picker for overworld and caves separately, to accommodate both #7299 and #9159. 
Old text:
> Addresses #9159, although further options might still be nice and the current UX feels a bit strange.
> 
> Adds the following options to the skybox plugin:
> 
> *Custom sky color* - standard color picker
> 
> *Mode* - dropdown, "None", "Replace target sky color", "Overworld" and "Everywhere". *None* is the current behavior of using the sky map and making no substitutions. *Replace target sky color* uses the custom color in place of a specific color value, and blending between areas still works …

Skybox color customization options

---

runelite-client/src/main/java/net/runelite/client/plugins/slayer/Task.java

Add Battlefront to list of locations for !task command

---

runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingPlugin.java

Closes #12806 
Added Crystal and Trailblazer Harpoons on the Fishing Overlay list

Update FishingPlugin.java - Adding crystal harpoon / trailblazer harpoon to the overlay list

---

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

menuentryswapper: fix menu entry swap for sedridor

---

runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangeConfig.java

Updates the hint text for the settings to be more descriptive

Update Grand Exchange Plugin Settings Hint Text

---

runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordGameEventType.java

The rest of the island is not accessible.

discord: add Soul Wars regions

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/FaloTheBardClue.java

clue: add dragon scimitar or to falco the bard cluestep

---

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

menu entry swapper: add dwarven rock cake swap

---

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

add skull sceptre 'invoke' to teleport item menu entry swapper

---

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/TeleportLocationData.java

worldmap: add Watson teleport scroll location

---

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/MiningSiteLocation.java

worldmap: change ore amount for battlefield mine tooltip

---

runelite-client/src/main/java/net/runelite/client/plugins/bank/BankPlugin.java

getItemContainer is Nullable and should be checked to avoid NPEs
resolves #13039

Handle possible NPE.

---

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

MenuEntrySwapperPlugin: Added Spria

---

runelite-client/src/main/java/net/runelite/client/plugins/cooking/CookingPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeGemOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/motherlode/MotherlodeOverlay.java

Minor change to make code consistent with plugin.

cooking: change sinceCut to sinceCooked to match plugin

---

runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialCounterPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialWeapon.java

Additions include Barrelchest Anchor, Bone Dagger (including poisoned), and Dorgeshuun Crossbow.

Add additional weapons' special attacks to the damage tracker.

---

runelite-client/src/main/java/net/runelite/client/plugins/tearsofguthix/TearsOfGuthixConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/tearsofguthix/TearsOfGuthixOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/tearsofguthix/TearsOfGuthixPlugin.java

@abextm I think the linked issue and comments like https://github.com/runelite/runelite/pull/12862#issuecomment-766186979 are a great reason to add this toggle back. Would you kindly review?

Add Green Tears of Guthix Timer Option (fixes #13023)

---

http-api/src/main/java/net/runelite/http/api/RuneLiteAPI.java
http-api/src/main/java/net/runelite/http/api/gson/ColorTypeAdapter.java
http-api/src/main/java/net/runelite/http/api/gson/IllegalReflectionExclusion.java
http-api/src/main/java/net/runelite/http/api/gson/InstantTypeAdapter.java
http-api/src/main/java/net/runelite/http/api/ws/WebsocketGsonFactory.java
http-api/src/test/java/net/runelite/http/api/gson/ColorTypeAdapterTest.java
http-api/src/test/java/net/runelite/http/api/gson/InstantTypeAdapterTest.java
runelite-client/src/main/java/net/runelite/client/RuneLiteModule.java
runelite-client/src/main/java/net/runelite/client/account/SessionManager.java
runelite-client/src/main/java/net/runelite/client/externalplugins/ExternalPluginClassLoader.java
runelite-client/src/main/java/net/runelite/client/externalplugins/ExternalPluginClient.java
runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/CrowdsourcingManager.java
runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangePlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/groundmarkers/GroundMarkerSharingManager.java
runelite-client/src/main/java/net/runelite/client/plugins/objectindicators/ObjectIndicatorsPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/screenmarkers/ScreenMarkerPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/timetracking/clocks/ClockManager.java
runelite-client/src/main/java/net/runelite/client/plugins/wiki/WikiSearchChatboxTextInput.java
runelite-client/src/main/java/net/runelite/client/util/ImageCapture.java
runelite-client/src/main/java/net/runelite/client/util/ReflectUtil.java

Includes workarounds for:
- [JDK-8173978](https://bugs.openjdk.java.net/browse/JDK-8173978) (Java 14)
- [JEP396/JDK-8255363](https://bugs.openjdk.java.net/browse/JDK-8255363) (Java 16)
Closes #10113

Java 14-16 compatability

---

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/WorldMapPlugin.java

worldmap: change from skill level to boosted level for map icons

---

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/grounditems/LootType.java

grounditems: add despawn timer for items placed on tables

---

runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/screenshot/ScreenshotPluginTest.java

Add independent valuable drop screenshot minimum value threshold

---

runelite-api/src/main/java/net/runelite/api/AnimationID.java
runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java

Idle notifier will now trigger after the following animations:
- Filling buckets of slime
- Emptying bone crusher bin
- Grinding the bones (last animation played if the player has no container for the crushed bones)
Fix for: #13144

Idle notifier: ectofuntus

---

runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingPlugin.java

Flying fish notification at minnows

---

runelite-client/src/main/java/net/runelite/client/Notifier.java
runelite-client/src/main/java/net/runelite/client/plugins/fishing/FishingPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/regenmeter/RegenMeterPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/grounditems/GroundItemsPluginTest.java
runelite-client/src/test/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPluginTest.java

This also removes the player's ingame name from notifications which are
referring to the active player in favor of the title.
Closes #13114

notifier: Add username to tray notification title

---

runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/cooking/CrowdsourcingCooking.java
runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/woodcutting/CrowdsourcingWoodcutting.java

Add more data to track for crowdsourcing woodcutting and cooking. New log object ids, log messages, and a spit-roast cooking message.

Add new trees to Woodcutting and a new cook message to Cooking Crowdsourcing

---

runelite-client/src/main/java/net/runelite/client/config/ConfigManager.java

If you did a getConfiguration while the config was being loaded from
the client you could get a value from the new config or the old config.
Since some plugins would check profile values from the ConfigChange
events being posted it could cause the ConfigManager to observe an unset
rsprofile.loginSalt, which would make it generate a new one, overwriting
the one the server had, causing all profiles to be lost.

ConfigManager: don't allow access to partially loaded configs

---

runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningPlugin.java

Add minimap arrow pointing to the active daeyalt rock

---

runelite-client/src/main/java/net/runelite/client/plugins/music/MusicPlugin.java

Fixes music granular sliders after today's update (Script ID 3885 arguments changed).

MusicPlugin: Fix after today's update

---

pom.xml
runelite-api/pom.xml
runelite-client/pom.xml
runelite-client/src/main/java/net/runelite/client/eventbus/EventBus.java
runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsFrame.java
runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPanel.java
runelite-client/src/main/java/net/runelite/client/plugins/devtools/DevToolsPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/devtools/InventoryInspector.java
runelite-client/src/main/java/net/runelite/client/plugins/devtools/ScriptInspector.java
runelite-client/src/main/java/net/runelite/client/plugins/devtools/ShellFrame.java
runelite-client/src/main/java/net/runelite/client/plugins/devtools/VarInspector.java
runelite-client/src/main/java/net/runelite/client/plugins/devtools/WidgetInspector.java
runelite-jshell/pom.xml
runelite-jshell/src/main/java/net/runelite/jshell/JShellAutocompleteProvider.java
runelite-jshell/src/main/java/net/runelite/jshell/RLShellExecutionControl.java
runelite-jshell/src/main/java/net/runelite/jshell/RemappingThrowable.java
runelite-jshell/src/main/java/net/runelite/jshell/ShellPanel.java
runelite-jshell/src/main/java/net/runelite/jshell/TeeLogger.java
runelite-jshell/src/main/resources/net/runelite/jshell/darcula.xml
runelite-jshell/src/main/resources/net/runelite/jshell/default.jsh
runelite-jshell/src/main/resources/net/runelite/jshell/prelude.jsh

Adds a shell to devtools that lets you execute test programs.
This makes the client require Java 11 or higher to build. It still runs on any Java 8+, however the shell will be inaccessible for these older VMs.

devtools: add shell window

---

runelite-api/src/main/java/net/runelite/api/widgets/Widget.java
runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/music/MusicPlugin.java

Close #13183 #13160
Also fixed NPE in `SettingsSideSlider.shutdown()` when user disables "Granular volume sliders" on login screen.

music and chatcommands: fix several NPE

---

runelite-client/src/main/java/net/runelite/client/plugins/chatnotifications/ChatNotificationsPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/chatnotifications/ChatNotificationsPluginTest.java

chat notifications: Prevent localPlayer highlights and notifications

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/SkillChallengeClue.java

Otherwise, I have to go to the wiki to find out how many bars I need.

Specify the number of bars required for shayzien armor set elite clue sherlock step.

---

runelite-client/src/main/java/net/runelite/client/plugins/cooking/CookingPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/cooking/CrowdsourcingCooking.java
runelite-client/src/test/java/net/runelite/client/plugins/cooking/CookingPluginTest.java

Fix POH altar burners false positive burn message

---

http-api/src/main/java/net/runelite/http/api/gson/ColorTypeAdapter.java
http-api/src/main/java/net/runelite/http/api/gson/InstantTypeAdapter.java
http-api/src/test/java/net/runelite/http/api/gson/ColorTypeAdapterTest.java
http-api/src/test/java/net/runelite/http/api/gson/InstantTypeAdapterTest.java
http-service/src/test/java/net/runelite/http/service/loottracker/LootTrackerControllerTest.java

http-api: encode Color & Instant more nicely

---

runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobe.java
runelite-client/src/main/java/net/runelite/client/plugins/xpglobes/XpGlobesOverlay.java

xpglobes: Add dynamic globe icon sizing

---

runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargeConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargeOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargePlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/itemcharges/ItemChargePluginTest.java

From [this comment](https://github.com/runelite/runelite/pull/13225#discussion_r578182495), it doesn't make sense to just make the new addition use RSProfile without updating the old ones, so here it is!

item charges: use RSProfiles for items with stored charges

---

runelite-api/src/main/java/net/runelite/api/Varbits.java
runelite-client/src/main/java/net/runelite/client/plugins/wiki/WikiPlugin.java

Wiki Plugin: Checks for vanilla settings before displaying the vanilla wiki banner

---

runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialCounterPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialWeapon.java
runelite-client/src/test/java/net/runelite/client/plugins/specialcounter/SpecialCounterPluginTest.java

Combine BGS and BGS(OR) as one special weapon to count as same counter

---

runelite-client/src/main/java/net/runelite/client/plugins/friendlist/FriendListConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/friendlist/FriendListPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/friendlist/FriendListPluginTest.java

Add world to friend login message

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/SkillChallengeClue.java
runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_magic.json

Fixes the SkillChallengeClue reanimation to require the correct runes
Fixes the arceuus spells in the skill calc.

Arceuus spellbook changes

---

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/chatcommands/ChatCommandsPluginTest.java

chat commands: add support for tempoross pb messages

---

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_fletching.json

Add battlesaff to fletching skill calculator

---

runelite-client/src/main/java/net/runelite/client/plugins/examine/ExaminePlugin.java

Update plugin description and add tags "high alchemy" and "prices". 
Tested in client by searching for prices, high, high alchemy, and alchemy in configuration tab and ensuring Examine came up in results.
Closes #13392

Update Examine Plugin description and tags

---

runelite-client/src/main/java/net/runelite/client/plugins/music/MusicPlugin.java

Null check added to music plugin when shutting down.

---

runelite-client/src/main/java/net/runelite/client/plugins/camera/CameraConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/camera/CameraPlugin.java
runelite-client/src/main/scripts/ToplevelCompassOp.rs2asm

camera: add option to preserve pitch on compass look menu entries

---

runelite-client/src/main/java/net/runelite/client/plugins/inventorygrid/InventoryGridConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/inventorygrid/InventoryGridOverlay.java

A friend wanted to change the color to something else, so allow changing the color of the grid and highlight.
(I think the original PR was going to have an option to change the color, but changing the alpha didn't exist at the time, so it was not put in. And someone will probably make a PR like this eventually.)
Closes #13705

Inventory Grid Plugin: Add color configuration

---

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatChanges.java
runelite-client/src/main/java/net/runelite/client/plugins/itemstats/potions/StaminaPotion.java

Closes #13560 
Basically duplicating the logic for prayer potions which checks for Ring of Gods and swapping the ring.

Fix stamina restore with Ring of Endurance

---

runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePlugin.java

Same as the world hopper change in 1c75a97df543c7286d6000b928e6ef1917c0bae6.

hiscore: add lookup clan member

---

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

Add configuration for Achievement Diary items with nonstandard teleports

Menu Entry Swapper: Achievement Diary Teleports

---

runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcSceneOverlay.java

Added a server tile option and a stroke width config

npc indicators: add outline width

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java

clues: Add the new cryptic clue at Giant's Den

---

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_agility.json
runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_magic.json
runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_prayer.json

Adds the new Demonic ashes, the Shayzien agility courses, and the new Arceuus spellbook to the skill calc

skill calc: add akd content

---

runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/LumbridgeDiaryRequirement.java

Actual: ![before](https://user-images.githubusercontent.com/83126316/120720771-a825f680-c49a-11eb-8b3a-3a4512cb0e37.PNG)
Fixed: ![after](https://user-images.githubusercontent.com/83126316/120720772-a825f680-c49a-11eb-87d1-b45107c580bf.PNG)

Reword of the hard Lumby diary entry of smite prayer for the requirement to apply

---

runelite-client/src/main/java/net/runelite/client/plugins/music/MusicPlugin.java

the client now synchronizes the music volume with what is stored in the
var during toplevel_redraw, so if music was muted according to vanilla
it would stop music playback even if we were setting it higher.

music: don't restart when rendrawing tli

---

runelite-client/src/main/java/net/runelite/client/game/LootManager.java

loot manager: fix tracking of phosani's nightmare

---

runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/DesertDiaryRequirement.java

Reword of the hard desert diary entry for the dust devils for the reqs to show

---

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_thieving.json

https://github.com/runelite/runelite/issues/13409

add wall safe thieving action in skill calculator plugin, Close #13409 

---

runelite-client/src/main/java/net/runelite/client/plugins/reportbutton/ReportButtonPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/reportbutton/TimeStyle.java

Add idle time option to report button plugin.

---

runelite-client/src/main/java/net/runelite/client/plugins/timetracking/OverviewTabPanel.java
runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TabContentPanel.java

timetracking: don't fail rendering overview with dead contracts

---

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

Adds Desert Amulet 4 teleport swaps to Menu Entry Swapper

---

runelite-client/src/main/java/net/runelite/client/plugins/slayer/Task.java

Change moss giants slayer task icon to mossy key.

---

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java

Tracking the lockboxes from the Camdozaal Vault

[loot] - added tracking for lockboxes from the Ruins of Camdozaal Vault

---

runelite-client/src/main/java/net/runelite/client/plugins/interacthighlight/InteractHighlightPlugin.java

Fixes a bug where the highlight color of autoretaliated is dependent on the last interact the player performed.

Fix auto retaliate highlight color

---

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatChanges.java

Add the new Crystal Paddlefish from The Gauntlet to itemstats.

itemstats: Add new Gauntlet food

---

runelite-client/src/main/java/net/runelite/client/plugins/antidrag/AntiDragConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/antidrag/AntiDragPlugin.java

This feature has been added to the official Steam client -- no reason to omit it from RuneLite
First PR to this project -- If I've missed any protocols, please let me know

Enable antidrag in pvp

---

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_herblore.json

added magic essence potion (3) to skill calculator

Update Skill Calculator : Herblore

---

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatChanges.java

#13954 missed the corrupted version of the new gauntlet food

itemstats: Add Corrupted Paddlefish

---

runelite-client/src/main/resources/net/runelite/client/plugins/skillcalculator/skill_prayer.json

skill calc: added urium remains to the list along with 50% bonus

---

runelite-client/src/main/java/net/runelite/client/plugins/banktags/BankTagsPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/TabInterface.java

Currently it cannot be scrolled, which is a problem if you have more tag tabs than it can display - some tag tabs will be below the visible area and can't be clicked on or re-ordered.

Make tag tab tab scrollable.

---

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatChanges.java

itemstats: added prayer point gained for jangerberry

---

runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/KaramjaDiaryRequirement.java

Jagex changed this with the update on 09/09

achievementdiary: correct spelling of shortcut

---

runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java
runelite-client/src/main/java/net/runelite/client/plugins/inventorytags/InventoryTagsOverlay.java
runelite-client/src/main/java/net/runelite/client/ui/overlay/WidgetItemOverlay.java

Closes https://github.com/runelite/runelite/issues/14086
Gravestone widget added in the overlay.

feat: inventory-tags implemented in gravestone interface

---

runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/CrowdsourcingPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/varbits/CrowdsourcingVarbits.java
runelite-client/src/main/java/net/runelite/client/plugins/crowdsourcing/varbits/VarData.java

This is a slight modification of varbit tracking found here https://github.com/leejt/osrs-wiki-crowdsourcing. The CrowdsourcingVarbits class is itself a modified version of [Abex's VarInspector devtool](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/devtools/VarInspector.java).

Move wiki varbit crowdsourcing into default client

---

runelite-client/src/main/java/net/runelite/client/plugins/inventorytags/InventoryTagsOverlay.java

[Preview](https://imgur.com/a/sX5N7qC)

Inventory Tags: Add support for CoX storage chests

---

runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialCounterPlugin.java

Since the list is growing a bit, I took the opportunity to also add some comments.

spec counter: add sire spawns and scions to ignore list

---

runelite-client/src/main/java/net/runelite/client/plugins/tileindicators/TileIndicatorsConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/tileindicators/TileIndicatorsOverlay.java

Commit based on this issue: https://github.com/runelite/runelite/issues/14445
My first commit :) happy to work with you guys

Added settings for tile indicator fill colors

---

runelite-client/src/main/java/net/runelite/client/plugins/hiscore/NameAutocompleter.java

Fix NPE in hiscores

---

runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java
runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java

Closes #14443 
Until I saw this issue, I hadn't realized I wasn't the only one that didn't like the icon.

Add option to disable system tray icon

---

runelite-client/src/main/java/net/runelite/client/plugins/loginscreen/LoginScreenOverride.java
runelite-client/src/main/java/net/runelite/client/plugins/loginscreen/LoginScreenPlugin.java

Add random option to login screen plugin

---

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/Pet.java

chat-commands - Add Nexling pet

---

runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/Tree.java

add missing trees on the isle of souls:
- Regular
- Maple
- Yew
- Mahogany
- Teak

[Woodcutting] Add Isle Of Souls Trees

---

runelite-client/src/main/java/net/runelite/client/plugins/barrows/BarrowsPlugin.java

Hello I'm a student in IT and this is my first time trying to contribute to a project. I added a test to make sure that the chest is empty before geting the items.

Added a condition to check if the barrowsRewardContainer is null before trying to getItems()

---

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java

track hallowed sack loot in the loot tracker

---

runelite-client/src/main/resources/net/runelite/client/plugins/roofremoval/overrides.jsonc

roof removal: Add Grim Tales tower override

---

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java

Not something I can test ingame right now due to outages, but the loot string and region are correct

Add Guardians of the Rift rewards

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/AnagramClue.java
runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

March 23 2022 update changed his name.

plugins: Rename Sedridor to Archmage Sedridor

---

runelite-client/src/main/java/net/runelite/client/plugins/statusbars/BarRenderer.java
runelite-client/src/main/java/net/runelite/client/plugins/statusbars/StatusBarsConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/statusbars/StatusBarsOverlay.java

Status Bars Plugin - Customize width of status bars for resizable mode

---

runelite-api/src/main/java/net/runelite/api/Perspective.java

Perspective: fix clickbox for type 11 objects

---

runelite-api/src/main/java/net/runelite/api/SpriteID.java
runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/skills/MagicAction.java

Quick fix for [#14900](https://github.com/runelite/runelite/issues/14900)
fixes #14900

Typo patch

---

runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java

Added message registered when Shadow Veil prevents being stunned & corresponding detection to remove counter.
Resolves #14682

[TINY] TimersPlugin: Added Shadow Veil protection detection to resolve timer showing when not stunned.

---

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatChanges.java
runelite-client/src/main/java/net/runelite/client/plugins/itemstats/potions/MixedPotion.java
runelite-client/src/test/java/net/runelite/client/plugins/itemstats/ItemStatEffectTest.java

itemstats: Add mixed (barbarian) potions

---

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPanel.java

loottracker: reverse collapse all tooltips

---

runelite-client/src/main/java/net/runelite/client/account/SessionManager.java

This also logs in user on website

Send username and sessionid when redirecting to /logged-in page

---

runelite-client/src/main/java/net/runelite/client/plugins/objectindicators/ObjectIndicatorsConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/objectindicators/ObjectIndicatorsOverlay.java

Add options to highlight an object by the click-box and tile:

ObjectIndicators: Add more highlight options

---

runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerConfig.java

Updated XpTrackerConfig "Hide maxed skills" to an accurate description.

---

runelite-client/src/main/java/net/runelite/client/game/NpcUtil.java

Add Damis first form to isDying block list

---

runelite-client/src/main/java/net/runelite/client/plugins/regenmeter/RegenMeterPlugin.java

regen-timer: add lightbearer support

---

runelite-client/src/main/java/net/runelite/client/ui/components/IconTextField.java

+ Adds method for ImageIcon in IconTextField.java

Allow Custom ImageIcon in IconTextField.java

---

runelite-api/src/main/java/net/runelite/api/Client.java

client: fix logout timer javadoc typo

---

runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/timers/TimersPluginTest.java

Co-authored-by: Brady Ryun <39814792+bradyryun@users.noreply.github.com>
Rebase of #14376 due to inactivity
Closes #14376
Closes #14375

Add Martin the Master Farmer pickpocket timer

---

runelite-api/src/main/java/net/runelite/api/ObjectID.java
runelite-client/src/main/java/net/runelite/client/plugins/agility/Obstacles.java

agility: add Necropolis obstacle

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/MusicClue.java

clues: add world map hint for music clue scrolls

---

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java

chat commands: add fishingtodt mapping to tempoross.

---

runelite-client/src/main/java/net/runelite/client/plugins/entityhider/EntityHiderConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/entityhider/EntityHiderPlugin.java

Feature request: https://github.com/runelite/runelite/discussions/15096
Adds the option to hide Thralls

entity hider: add option to hide Thralls

---

runelite-api/src/main/java/net/runelite/api/Varbits.java
runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/chatcommands/ChatCommandsPluginTest.java

Supports adventure logs' "counters" to get the data

chat commands: Adds PB commands for team sizes

---

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

noticed this ingame, little typo. fix is untested

[Menu entry swapper][easy] Remove extra space in MenuEntrySwapper.java

---

runelite-client/src/main/java/net/runelite/client/plugins/boosts/BoostsOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/boosts/CompactBoostsOverlay.java

Adds support for `DisplayChangeMode.ALWAYS` to panel display and compact display
* Closes #15248

boosts: panel+compact support for always show buff/debuff timer

---

runelite-api/src/main/java/net/runelite/api/Varbits.java
runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java
runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java

Adds support for [Menaphite remedy](https://oldschool.runescape.wiki/w/Menaphite_remedy#4_dose) to the timers plugin.

timers: Add menaphite remedy

---

runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/slayer/SlayerPluginTest.java

slayer: Set streak and points when receiving first task

---

runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java
runelite-client/src/main/java/net/runelite/client/plugins/randomevents/RandomEventConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/randomevents/RandomEventPlugin.java

Fixes #14696 
Add following random events to the random events plugin notification options:
- Capt' Arnav's Chest
- Certers
- Drunken Dwarf
- Evil twin
- Pillory
- Pinball
- Rick Turpentine
- ~~Strange plant~~

Add missing random events

---

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java

Adds abbreviation names for the new Phantom Muspah boss.

chat commands: add short names for Phantom Muspah

---

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java

Nice and simple change.
Part of #16133

loot tracker: add support for frozen caches

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/EmoteClue.java

EmoteClue - updated iorwerth clue to include bowfa as well as crystal bow

---

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java

Fixed Al Kharid !kc return issue as per
https://github.com/runelite/runelite/issues/16218
Tested with chat commands found
https://github.com/runelite/runelite/wiki/Chat-Commands

ChatCommandsPlugin: Fixed Al Kharid Return

---

runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java

MES: Remove tags from UI swap feedback message

---

runelite-api/src/main/java/net/runelite/api/AnimationID.java
runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java

Idle Notifier: Add Imcando Hammer Infernal Eel Crushing Animation ID

---

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java

Add Constant for KQ Lair Region ID and add it to Instance Exceptions for Despawn Times

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CipherClue.java
runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperConfig.java

Noticed this while doing clues. Pr fixes all instances of the typo.

Rename Ectofunctus to Ectofuntus

---

runelite-client/src/main/java/net/runelite/client/plugins/slayer/Task.java

Add "Phantom Muspah" to the list of available slayer tasks

---

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/DungeonLocation.java

Fixes a spelling error on the worldmap

Spelling fix: Skeltal > Skeletal

---

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePlugin.java

Closes #16510 
Follow-up from https://github.com/runelite/runelite/commit/b3ec120efa7a4ee67b019702a1c16db2cda6c4bf

hiscore: avoid AccountType enum usage

---

runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/GrandExchangePlugin.java

Presently the panel is not populated on startup, even when logged in and `client.getGrandExchangeOffers()` could be used to populate its contents.

grand exchange: Initialize offers panel on startup

---

runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargePlugin.java

Item charges Plugin: Fix explorer's ring charges bug

---

runelite-api/src/main/java/net/runelite/api/Varbits.java
runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/screenshot/ScreenshotPluginTest.java

Screenshot: Screenshot plugin screenshots when level up interface is disabled

---

runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordState.java
runelite-client/src/test/java/net/runelite/client/plugins/discord/DiscordStateTest.java

discord: add a tooltip on the RuneLite logo to show if the client is running in safe mode

---

runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java

This includes the untradeable LMS staff of the dead and the staff of balance.

timers: Support all staff of the dead variants

---

runelite-client/src/main/java/net/runelite/client/plugins/attackstyles/AttackStylesConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/attackstyles/AttackStylesPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/attackstyles/AttackStylesPluginTest.java

Added a chat message which shows when a player's attack style is changed to an unwanted style.

Warning for Changing Attack Styles

---

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java

Add loot tracker support for Bounty crates tier 1-9.

loottracker: Add support for Bounty crates.

---

runelite-client/src/main/java/net/runelite/client/plugins/fairyring/FairyRings.java
runelite-client/src/main/java/net/runelite/client/plugins/worldmap/FairyRingLocation.java

A new fairy ring was added with desert treasure 2.
See #16819

Add BLS fairy ring.

---

runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/CompostTracker.java
runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingWorld.java
runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/PatchImplementation.java
runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/Produce.java

It's called a Big Compost Bin:
https://oldschool.runescape.wiki/w/Big_Compost_Bin
NB: I didn't want to replace the variable names, just renamed what is displayed on the UI.

fix(timetracking): s/Giant/Big/g

---

runelite-client/src/main/java/net/runelite/client/plugins/kingdomofmiscellania/KingdomPlugin.java

Fix for this issue: The Miscellania favor reminder should update at midnight GMT like the rest of the dailies #17004
Link: https://github.com/runelite/runelite/issues/17004

Update miscellenia favor GMT time

---

runelite-client/src/main/java/net/runelite/client/plugins/bank/BankPlugin.java

Fixed seed vault not showing prices when first opened

bank: use clientThread.invokeLater for updating vault price

---

runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargePlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/itemcharges/ItemChargePluginTest.java

I noticed this bug myself when mining clay in Prif the other day. Thought it would be a good bug for my 1st contribution.
Fixes #15653
I see #15864 open but hasn't been active for 11 months

Prevent bracelet of clay charges from decreasing when mining in prif with 1 free inventory slot

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java

clue scroll: in HotColdClue, fix issue where methods were called before the class's static initializer had run. Specifically, the static inititializer called `initializeSolver` which referenced the static variables BEGINNER_CLUE and MASTER_CLUE, which are not yet initialized at this time. This commit removes that call. This also removes a spurious warn message that was logged.
This commit also cleans up a lot of code not directly related to the above bug:
- It is also not necessary to null check the hotColdSolver as it is never null when it is used, so these null checks have been removed.
- This commit also adds a boolean `isBeginner` which allows the `HotColdClue` to know if it is a beginner or master clue without reference comparing to the `BEGINNER_CLUE` and `MASTER_CLUE` instances. …

Fix HotColdClue running code before static initializer finishes. Also removes spurious log message.

---

runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java

Made change to GroundItemsOverlay.java to amend wrong despawn timer in the Inferno as described in issue #17256

fix ground items inferno despawn timer

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java

Noticed this was off while doing this clue step during Leagues. [Source](https://oldschool.runescape.wiki/w/Donovan_the_Family_Handyman)

cryptic clues: fix description of medium clue step solution

---

runelite-client/src/main/java/net/runelite/client/plugins/worldmap/FairyRingLocation.java

world map: add AKR fairy ring

---

runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/Book.java
runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/KourendLibraryConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/KourendLibraryOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/KourendLibraryPanel.java
runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/Library.java
runelite-client/src/test/java/net/runelite/client/plugins/kourendlibrary/LibraryTest.java

kourendlibrary: remove dark manuscripts

---

runelite-client/src/main/java/net/runelite/client/plugins/xpupdater/XpUpdaterConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/xpupdater/XpUpdaterPlugin.java

This adds support for RuneTracker to the xp updater. I have built and tested it locally and it works

xp updater: add runetracker support

---

runelite-api/src/main/java/net/runelite/api/Varbits.java
runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java
runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java

timers: Track god wars altar cooldown via varbit

---

runelite-api/src/main/java/net/runelite/api/Varbits.java
runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java
runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java

Updated Timers plugin to include Spellbook Swap timer

add Spellbook Swap timer to Timers plugin

---

runelite-client/src/main/java/net/runelite/client/plugins/chathistory/ChatHistoryPlugin.java

Changes the selected menu entry to prevent entries from plugin to be selected and preventing the chat message to be copied 
Fixes #17295

Chat History: Fix entry selection to allow message from friends to be copied

---

runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/ArdougneDiaryRequirement.java
runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/FremennikDiaryRequirement.java
runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/KandarinDiaryRequirement.java
runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/WesternDiaryRequirement.java

They fixed all the random changes they implemented 2 weeks ago, and I found 3 others that were probably also changed today.
<details>
<summary>Details</summary>
</details>

achievement diary: update various tasks

---

runelite-client/src/main/java/net/runelite/client/game/LootManager.java

Fixes https://github.com/runelite/runelite/issues/16943

fix nightmare loot tracking

---

runelite-client/src/main/java/net/runelite/client/plugins/interfacestyles/InterfaceStylesConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/interfacestyles/InterfaceStylesPlugin.java

Add player option condensing to InterfaceStylesPlugin

---

runelite-maven-plugin/pmd-ruleset.xml
runelite-maven-plugin/pom.xml
runelite-maven-plugin/src/main/java/net/runelite/mvn/ComponentMojo.java

pmd: Run checks against runelite-maven-plugin module, require locale for case conversions

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java
runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/MapClue.java

clues: fix incorrect naming for Wizards' Guild/Tower

---

runelite-client/src/main/java/net/runelite/client/plugins/mining/MiningPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/mining/MiningPluginTest.java

The mining plugin previously did not correctly track runite ore.

Correct mining message pattern for runite ore

---

runelite-client/src/main/java/net/runelite/client/plugins/hunter/HunterPlugin.java

Unlisted item but is for #17586

Add Embertailed jerboa to hunter plugin

---

runelite-api/src/main/interfaces/interfaces.toml
runelite-client/src/main/java/net/runelite/client/ui/overlay/WidgetOverlay.java

supersedes #17599 without depreciated changes and with more accurate name

widget: make moons of peril overlay movable

---

runelite-client/src/main/java/net/runelite/client/plugins/hunter/HunterPlugin.java

This adds support to the hunter traps placed for
- Embertailed Jerboas
- Pyre foxes
- Tecu salamanders

hunter: add varlamore hunter traps

---

runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/skills/AgilityAction.java

Adds entry for the Dorgesh-Kaan Agility Course to the skill calculator.

skillcalculator: Add Dorgesh-Kaan Agility Course

---

runelite-api/src/main/java/net/runelite/api/HitsplatID.java

Adds Doom and Burn hitsplats introduced in Varlamore: Part One
#17586

hitsplat: add doom and burn hitsplats

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java

this section of the Kharazi jungle is multi now(?), user reported in the RL discord that the ancient wizards jumped him, and I went over and confirmed that the area is now multi, and updated the wiki

clues: update SW Kharazi jungle HotCold step

---

runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingContractManager.java
runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingWorld.java

As discussed on Discord https://discord.com/channels/301497432909414422/419891709883973642/1222613583125418024
Likely due to Jagex fixing multinpcs chatheads
Fixes #17635

farming: fix tracking contracts & marcellus protection

---

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java

Fixes: https://github.com/runelite/runelite/issues/17699

Add lunar chest variants for !kc command

---

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/chatcommands/ChatCommandsPluginTest.java

Adds the hunter rumour kc command as asked in https://github.com/runelite/runelite/discussions/17782
Also adds variations for the rumour kc command

Add hunter rumour kc

---

runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java

Add 'Units' to createDoubleSpinner so that a Double ConfigItem can have units the same as Int.

Add Units to Double spinner.

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java
runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java

they finally added an agility skip here so I've updated the wording
alternatives:
`or 85 agility`
`unless 85 agility`
`85 agility, otherwise bring pet rock...`

clues: update steps with newly added agility shortcuts

---

runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatChanges.java

Added new foods from Varlamore expansion
- COOKED_GRAAHK
- COOKED_KYATT
- COOKED_PYRE_FOX
- COOKED_DASHING_KEBBIT
- COOKED_SUNLIGHT_ANTELOPE
- COOKED_MOONLIGHT_ANTELOPE

item stats: Add new foods

---

runelite-client/src/main/resources/net/runelite/client/plugins/gpu/regions/regions.txt

Adds Waterbirth dungeon to GPU regions. Closes #17819. All testing by Yves.

gpu: regions: add waterbirth dungeon

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java

they forgot to keep the cryptic clue, cryptic

clues: update Hunter Guild easy step

---

runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialCounterConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialWeapon.java
runelite-client/src/test/java/net/runelite/client/plugins/specialcounter/SpecialWeaponTest.java

Adds new elder maul spec to spec counter

spec counter: add Elder Maul

---

runelite-client/src/main/resources/net/runelite/client/plugins/gpu/regions/regions.txt

Adds regions for Blast Furnace and Paterdomus.
Resolves #17333

gpu: regions: add Blast Furnace, Paterdomus

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java

This clue step refers to Mr. Barker as "the Barker", erroneously implying that he is some kind of town crier. 
This is a blight on the Barker name

Update CrypticClue - Barker is his name!

---

runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.java

Switch to tournament endpoint for seasonal deadman tournament.

hiscores: switch from leagues to dmm tournament

---

runelite-client/src/main/java/net/runelite/client/plugins/mta/telekinetic/TelekineticRoom.java

I'm not sure on the cyan square. But this speeds up the room a lot.

Update Telekinetic room to show one move ahead.

---

runelite-client/src/main/java/net/runelite/client/plugins/grandexchange/FuzzySearchScorer.java

partial regression introduced by #16973
Searches that did not share a prefix string with the item name, such as searching "splinters" for "Sunfire splinters", was not returning expected results, as the heavy bias toward shared prefixes was penalizing the query for not matching "Sunfire". This is unexpected, and the fuzzy search scorer should handle searches that do not begin at the start of the item name as well.
This PR replaces the prefix bias with a longest-common-subsequence bias, to better handle those mid-string terms. It uses the maximum LCS between any pair of search words and item words, and then still defers to jaro-winkler for close-scoring tiebreakers.
This still maintains some of the preferred behaviours of the original change (#16973) such as prioritizing short-named items …

grandexchange fuzzy: handle mid-term matches better

---

runelite-api/src/main/java/net/runelite/api/coords/WorldArea.java

The existing `thisWorldArea.hasLineOfSightTo(otherWorldArea)` gets the closest single point between the two and checks if that comparison point has LoS to the other world area.
This runs into issues when source WorldArea is larger than one tile and there is partial obstacle obstruction between the two WorldAreas:
The shaded corners would be the point used to check for LoS and the black line is an obstacle. The current LoS method returns false, but the blue line shows it should return true.
This PR should resolve this by performing an LoS check from each of the points on the potentially visible edges from each WorldArea. Since in most cases this likely isn't an issue, the points are sorted by distance to the target area to hopefully prevent unnecessary checks.
This shows which tiles will …

Fix line of sight check for multi-tile `WorldArea`s

---

runelite-client/src/main/resources/net/runelite/client/plugins/gpu/regions/regions.txt

Adds GPU regions for the following:
- HAM Storeroom
- Mor Ul Rek/Fight Pit
- ~~Fight Cave~~
- Barbarian Assault lobby
- Mage Training Arena
- Water Ravine Dungeon
- Kalphite Cave
- Kalphite Lair
- Chasm of Tears

gpu: regions: add various areas

---

runelite-client/src/main/java/net/runelite/client/plugins/slayer/Task.java

title, just got a slayer task while skipping and did a cox, learned they count

slayer: skeletal mystics count as skeletons

---

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/chatcommands/ChatCommandsPluginTest.java

This adds a chat command to track the kc of bird's eggs sacrificed at the shrine in the woodcutting guild.
Discussion: https://github.com/runelite/runelite/discussions/18230

chat commands: add bird's egg sacrifices kc

---

runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java

screenshot: fix kc pattern

---

runelite-client/src/main/java/net/runelite/client/plugins/itemidentification/ItemIdentification.java

Added blurite bar into item identification

Add blurite bar to item identification

---

README.md

Replaces Discord invite link with link to runelite.net/discord

README.md: Update Discord link

---

runelite-client/src/main/java/net/runelite/client/plugins/bosstimer/Boss.java

bosstimer: properly upper case AMOXLIATL name in boss enum

bosstimer: properly upper case AMOXLIATL

---

runelite-api/src/main/java/net/runelite/api/Varbits.java
runelite-client/src/main/java/net/runelite/client/plugins/agility/AgilityPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/agility/Courses.java
runelite-client/src/main/java/net/runelite/client/plugins/agility/Obstacles.java

This PR adds the colossal wyrm agility courses (basic, advanced) to the agility plugin.

agility: add colossal wyrm courses

---

runelite-client/pom.xml

Enables LWJGL and flatlaf optimizations that are specific to jdk 9+ and 10+ in the shaded jar
* https://github.com/LWJGL/lwjgl3/blob/3.3.2/modules/lwjgl/core/src/main/java10/org/lwjgl/system/MathUtil.java
* https://github.com/LWJGL/lwjgl3/blob/3.3.2/modules/lwjgl/core/src/main/java10/org/lwjgl/system/MultiReleaseMemCopy.java
* https://github.com/JFormDesigner/FlatLaf/blob/main/flatlaf-core/src/main/java9/com/formdev/flatlaf/ui/StackUtilsImpl.java

build: enable multi-release optimizations

---

runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcIndicatorsPlugin.java

~~I didn't test this (yet).~~
Played with this for a few days now and seems to work alright.

NPC Indicators: Ignore impossibly long NPC respawn times

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/hotcold/HotColdLocation.java

[wiki](https://oldschool.runescape.wiki/w/Treasure_Trails/Guide/Hot_Cold#:~:text=the%20Villa%20Lucens-,theatre,-stage%20in%20Aldarin)

clues: add Villa Lucens hot/cold location

---

runelite-client/src/main/java/net/runelite/client/plugins/agility/Courses.java

~~this is probably correct but I'm not bonded so I didn't test it, if someone else wants to~~

agility: fix wilderness course

---

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java

loot tracker: add Wintertodt reward cart

---

runelite-client/src/main/java/net/runelite/client/plugins/skillcalculator/skills/ConstructionAction.java

Adds the new dmm rug to the construction calculator.
Wiki:

skillcalculator: Add Deadman rug

---

runelite-api/src/main/java/net/runelite/api/ScriptID.java
runelite-client/src/main/java/net/runelite/client/plugins/fairyring/FairyRingConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/fairyring/FairyRingPlugin.java

closes #12388 (found after writing this up)
I didn't see until after I created this that #15968 existed, I had searched for "fairy ring" and only saw the one where the PR only edits the description and not adds the ability to add your own tags. Whoops.
Anyways:

Fairyring plugin: add tags

---

runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/chatcommands/ChatCommandsPluginTest.java

Documentation PR: https://github.com/runelite/wiki/pull/131
* Larran's small chest
* Larran's big chest
* Brimstone chest
* crystal chest
---
Also removed some duplicate code in unit tests, and added a missing double backslash to the pattern for bird eggs.

chat commands: add chests

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java

Add nearby fairy ring to the solution for the Aldarin easy clue step

clues: Update Aldarin easy clue solution

---

runelite-client/src/main/java/net/runelite/client/plugins/twitch/TwitchConfig.java

https://github.com/runelite/wiki/pull/138

twitch: update oauth website

---

runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/WoodcuttingConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/WoodcuttingPlugin.java

I wanted to customize this event's notification, but I couldn't without the change in this PR. 😄

Update woodcutting leprechaun event to use new notification system

---

runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterPlugin.java

chatfilter: Add NPC_SAY to game chat filter and collapsable messages

---

runelite-api/src/main/java/net/runelite/api/VarPlayer.java
runelite-api/src/main/java/net/runelite/api/Varbits.java
runelite-client/src/main/java/net/runelite/client/plugins/runecraft/EssencePouchOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/runecraft/EssencePouchOverlayTest.java

Colossal pouch degradation does not work because of a Jagex bug.

runecraft: add essence pouch amount + degradation overlay

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/SkillChallengeClue.java

Add the costume needle as an alternate for both needle and thread for the sherlock skill challenge

Add costume needle as alternate for needle and thread

---

runelite-api/src/main/java/net/runelite/api/Varbits.java
runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/WoodcuttingConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/WoodcuttingOverlay.java
runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/WoodcuttingPlugin.java
runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/WoodcuttingSceneOverlay.java
runelite-client/src/test/java/net/runelite/client/plugins/woodcutting/WoodcuttingPluginTest.java

Added an Indicator for easily identifying End of Rainbow during forestry events at a glance
Added an optional counter for Leprechauns Luck charges

Woodcutting Plugin: Leprechaun Forestry Event Improvements 

---

runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java

If he is in the edgeville dungeon the arrow won't show on the overworld map, which is confusing.

cluescrolls: include viggora location in solution text

---

runelite-client/src/main/java/net/runelite/client/Notifier.java
runelite-client/src/main/java/net/runelite/client/audio/AudioPlayer.java

Adds new `@Inject`able `AudioPlayer` w/ APIs to play sound from various inputs.
The intent here is to provide a dedicated sound playback channel to prevent caller/plugin misuse of audio streams or lines.

client: add @injectable AudioPlayer

---

runelite-client/src/main/java/net/runelite/client/plugins/animsmoothing/AnimationSmoothingPlugin.java

Ignore the shadow firing amethyst arrows, just wanted to confirm using the anim switcher plugin.
https://github.com/user-attachments/assets/6b0a8e31-2bc9-498b-90c1-a5f9dc496548
https://github.com/user-attachments/assets/4294304c-38f7-46f5-97b9-93cd50942281

anim smoothing: Fix tumeken's shadow and basilisk knight melee animations

---

runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargePlugin.java

Fixes #18992
The game message for making combo runes changed slightly with today's game update. This updates the regex to match either the new message or the old one, in case the change gets reverted.

itemcharges: update binding necklace used pattern to match new message

---

runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java
runelite-client/src/test/java/net/runelite/client/plugins/screenshot/ScreenshotPluginTest.java

Updates the boss kc message pattern to also match the Yama kc message.
Fixes #19006
Tested by @DominickCobb-rs [here](https://discord.com/channels/301497432909414422/419891709883973642/1373726604194222103)

screenshot: match yama kc message

---

runelite-client/src/main/java/net/runelite/client/plugins/emojis/Emoji.java

cat -> grinning/smiley cat
frown -> a very frowny face i don't know the real name for
cat joy -> joy
from assets.zip
current
expected

emoji: switch a few emoji

---

runelite-client/src/main/java/net/runelite/client/plugins/timersandbuffs/TimersAndBuffsPlugin.java

Updating master ca tier to 2min due to changes by summer sweep up today

Update master ca thrall timer to 2min

---

runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialCounterConfig.java
runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialWeapon.java

Adds tracking of Eye of Ayak special attacks to the SpecialCounter plugin.

SpecialCounter: add Eye of Ayak special attacks

---

runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java

Fixes the support for loot keys which has been broken since Jagex adopted the deadman-style wilderness loot keys in the main game.
- Hooked the loot tracker into the updated Wilderness loot key interface so it scans the five Deadman loot containers, records each tab separately (with a legacy fallback).
- Updated the chest-reset logic to clear only after all key containers (old and new) are empty.
Fixes #19295

Loot tracker: Track updated wilderness loot keys
